### ISSUE TITLE
[BUG] Set-PnPTenantSite -Url {siteURL} -SharingCapability ExternalUserSharingOnly command fails each time with a 401 Unauthorized error. 

### ISSUE THREAD

**Issue by nganbui** [pnp/powershell#1002]
### Reporting an Issue or Missing Feature
Set-PnPTenantSite -Url {siteURL} -SharingCapability ExternalUserSharingOnly worked before but now getting 401 Unauthorized error

### Expected behavior 
Set-PnPTenantSite -Url {siteURL} -SharingCapability ExternalUserSharingOnly command should succeed without error.

### Actual behavior
Running cmdlets below 
Set-PnPTenantSite -Url {siteURL} -SharingCapability ExternalUserSharingOnly
Getting the error
Set-PnPTenantSite : The remote server returned an error: (401) Unauthorized.

### Steps to reproduce behavior
Connect-PnPOnline -Tenant [tenantID] -ClientId [AppId] -Thumbprint [Thumprint] -Url "https://{abc}-admin.sharepoint.com"
Set-PnPTenantSite -Url {siteURL} -SharingCapability ExternalUserSharingOnly

Note: LegacyAuth is tenant-wide disabled in our tenant

### What is the version of the Cmdlet module you are running?                     
 PnP.PowerShell   version 1.7.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by fz8975** [comment]
Facing same issue while setting quota using Set-PnPTenantSite

**Comment by maheshkhiste** [comment]
same thing ..Set-PnPSite command throwing (401) Unauthorized Error , we have automation using it , it was working fine until yesterday not sure what happened suddenly ? Any workarounds or standard MS Cmd which can used to set quota through Azure Functions ?

**Comment by nganbui** [comment]
I think changes pushed on 1.7.16-nightly to fix this bug. Try using PnP.PowerShell 1.7.16-nightly. It should work.

**Comment by gautamdsheth** [comment]
@nganbui - is it working with the latest nightly ?

**Comment by fz8975** [comment]
> @nganbui - is it working with the latest nightly ?

Yes it is working. But what caused this ?

**Comment by gautamdsheth** [comment]
It was fixed by this PR - https://github.com/pnp/powershell/pull/969

**Comment by poi-radvine** [comment]
@nganbui how comes this started being an issue exactly starting on Aug 1st? We have automations running and several Set-PnpSite Commands stopped working.

**Comment by aungminko93750** [comment]
________________________________

**Comment by poi-radvine** [comment]
My issues was automatically resolved. It probably has to do with changes in the backend. This raises the question on who is responsible for this? We raised a ticket at MSFT and it was closed (mostly bc. PNP is not supported) even though I explained it was not changing any modules or Powershell versions and happening on all our maintained tenants.
