### ISSUE TITLE
[BUG] Set-PnPTenantSite Url Trailing Slash Issue

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#1005]
### Reporting an Issue or Missing Feature
This is a bug

### Expected behavior 
When working with Set-PnPTenantSite I would expect there should be no difference if the site URL has a trailing slash or not.

### Actual behavior 
When running a command like `Set-PnPTenantSite -url https://contoso.sharepoint.com/sites/test/ -Owners user@contoso.com` it would produce an error:
`Set-PnPTenantSite: The managed path sites/test is not a managed path in this tenant.`
![image](https://user-images.githubusercontent.com/5260172/129271481-2c05a82b-b99b-463f-a994-59874c4054a0.png)

However when I omit trailing slash in URL it would complete no problem.

### Steps to reproduce behavior

1. Connect to SharePoint Online Admin Center with PnP
2. Run  `Set-PnPTenantSite -url https://contoso.sharepoint.com/sites/test/ -Owners user@contoso.com`. with a trailing slash in URL
3. Repeat the same command  `Set-PnPTenantSite -url https://contoso.sharepoint.com/sites/test/ -Owners user@contoso.com` without a trailing slash this time.

### What is the version of the Cmdlet module you are running?
```
Name    : PnP.PowerShell
Version : 1.7.0
```
### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Fixed it, thanks for reporting.
Will be available in tomorrow's nightly !
