### ISSUE TITLE
[BUG] Add-PnPMicrosoft365GroupToSite  Microsoft.Office.Server.Directory.RequestFailure

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#1006]
### Reporting an Issue or Missing Feature
I am reporting a bug

### Expected behavior 
Add-PnPMicrosoft365GroupToSite  should not produce errors.

### Actual behavior 
When running a command similar to
`Add-PnPMicrosoft365GroupToSite -Url https://contoso.sharepoint.com/sites/IT-Test-YuriySamorodov-20210608-00037 -Alias "Team.IT.Test.YuriySamorodov.20210608.00037" -DisplayName "Team.IT.Test.YuriySamorodov.20210608.00037" -Description "Test Microsoft 365 Group Owner: Yuriy Samorodov" -IsPublic:$false -Owners user@contoso.com -KeepOldHomePage:$false`
I get an error:

> Add-PnPMicrosoft365GroupToSite: Microsoft.Office.Server.Directory.RequestFailure

I have tried to omit dots in the Alias, but that was not helpful.

This is quite similar to the issues below:
https://github.com/SharePoint/sp-dev-docs/issues/3799
https://github.com/SharePoint/sp-dev-docs/issues/3718

### Steps to reproduce behavior

1. Connect to SharePoint Online Admin Site with PnP
2. Run `Add-PnPMicrosoft365GroupToSite -Url https://contoso.sharepoint.com/sites/IT-Test-YuriySamorodov-20210608-00037 -Alias "Team.IT.Test.YuriySamorodov.20210608.00037" -DisplayName "Team.IT.Test.YuriySamorodov.20210608.00037" -Description "Test Microsoft 365 Group Owner: Yuriy Samorodov" -IsPublic:$false -Owners user@contoso.com`

### What is the version of the Cmdlet module you are running?
```
Name    : PnP.PowerShell
Version : 1.7.0
```

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by YuriySamorodov** [comment]
Seems like I traced back the issue. Look like `Add-PnPMicrosoft365GroupToSite` does not support application permissions. Is that true?

**Comment by gautamdsheth** [comment]
@YuriySamorodov - Yep, looks like that. We can't do anything about it.
