### ISSUE TITLE
[BUG] Add-PnPTeamsTeam Authentication method is not allowed

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#1007]
### Reporting an Issue or Missing Feature
I am reporting a bug

### Expected behavior 
`Add-PnPTeamsTeam` should create a new team and attach it to an existing site

### Actual behavior 
When I try running `Add-PnPTeamsTeam` while connected to the site I want a team attach to with my global admin credentials
![image](https://user-images.githubusercontent.com/5260172/129281016-3fcfcac6-0dfa-4cac-9b22-4fbf80b0d083.png)
 I get an error below:

> Add-PnPTeamsTeam: {"odata.error":{"code":"10005","message":{"lang":"en-US","value":"Authentication method is not allowed."}}}

![image](https://user-images.githubusercontent.com/5260172/129279918-38ef8b8f-30f3-47cf-9e7a-4a86566dd6e2.png)

### Steps to reproduce behavior
```
$credentials = Get-Credentials
Connect-PnPOnline -Url https://contoso.sharepoint.com/sites/test -Credentials $credentials
Get-PnPConnection
$splat = @{
    Url = 'https://contoso.sharepoint.com/sites/test'
    Alias = 'test'
    DisplayName = 'test'
    Owners = 'user@contoso.com'
}
Add-PnPMicrosoft365GroupToSite @splat
Add-PnPTeamsTeam
```

### What is the version of the Cmdlet module you are running?
```
Name    : PnP.PowerShell
Version : 1.7.0
```

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by glasserre** [comment]
Hello.
I have this error too hen using PNP Provisioning template.

```
Invoke-PnPTenantTemplate -Path "clt-projectv3.xml" -Parameters $Parameters
WARNING: Teamifying site at URL - https://xxxxx.sharepoint.com/sites/test-v3-ww-cust-pj1 failed due to an exception:- {"odata.error":{"code":"10005","message":{"lang":"en-US","value":"Authentication method is not allowed."}}}
```

**Comment by gautamdsheth** [comment]
Fixed it, will be available in tomorrow's nightly.
Thanks @YuriySamorodov for bringing this up, was pending for quite some time 👍

**Comment by YuriySamorodov** [comment]
Appreciate that @gautamdsheth! The way you and whole @erwinvanhunen team support PnP brings experience with this technology to the next level!
