### ISSUE TITLE
[FEATURE] Set-PnPMicrosoft365Group Restrict Adding Guests

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#1014]
**Is your feature request related to a problem? Please describe.**
Not related to any issue

**Describe the solution you'd like**
It would be great to be able changing group membership restriction settings with ```Set-PnPMicrosoft365Group```
Something like:
```Set-PnPMicrosoft365Group -AllowGuests $true```

**Describe alternatives you've considered**
Right now the only option Microsoft provides is using AzureADPreview module:
```
$GroupName = "<GroupName>"
Connect-AzureAD
$template = Get-AzureADDirectorySettingTemplate | ? {$_.displayname -eq "group.unified.guest"}
$settingsCopy = $template.CreateDirectorySetting()
$settingsCopy["AllowToAddGuests"]=$False
$groupID= (Get-AzureADGroup -SearchString $GroupName).ObjectId
New-AzureADObjectSetting -TargetType Groups -TargetObjectId $groupID -DirectorySetting $settingsCopy
```

**Additional context**
https://docs.microsoft.com/en-us/microsoft-365/solutions/per-group-guest-access?view=o365-worldwide

**Comment by gautamdsheth** [comment]
This has been added via Set-PnPMicrosoft365GroupSettings cmdlet:

https://pnp.github.io/powershell/cmdlets/Set-PnPMicrosoft365GroupSettings.html#example-2

You can also use New-PnPMicrosoft365GroupSettings to set this property.

Going to close this feature request , thanks !
