### ISSUE TITLE
connect-pnponline clientid and clientsecret not recognized

### ISSUE THREAD

**Issue by neil-patel77** [pnp/powershell#1019]
When using connect-pnponline I am warned to use -ClientId and -ClientSecret instead of using -AppId and -AppSecret.  However, when I use -ClientId and -ClientSecret, I receive the error stating:

Connect-PnPOnline -Url $siteURL -ClientId $ClientId -ClientSecret $ClientSecret
Connect-PnPOnline : Parameter set cannot be resolved using the specified named parameters.
At line:2 char:1
+ Connect-PnPOnline -Url $siteURL -ClientId $ClientId -ClientSecret $Cl ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Connect-PnPOnline], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,PnP.PowerShell.Commands.Base.ConnectOnline

I am using the latest version of the module.

**Comment by veronicageek** [comment]
Closing as no answer.
