### ISSUE TITLE
Enhance the Get-PNPFileVersion command to allow filtering

### ISSUE THREAD

**Issue by rbishop-etq** [pnp/powershell#1023]
**Is your feature request related to a problem? Please describe.**
The command of get-pnpfileversion does not allow filtering or piping to where-object so as to only allow removing the versions that we want

**Describe the solution you'd like**
Update the get-pnpfileversion and remove-pnpfileversion commands to allow for filtering by date or version number, and let us set ranges etc. of which versions we want to remove in order to clear space.

**Describe alternatives you've considered**
As of now we have to remove each version individually if we want to remove all but the most recent 10 or so versions. This is quite a pain when there are hundreds of versions on a file.

**Additional context**
Currently the command to "Remove-PnPFileVersion" only provides two options: remove file versions one at a time, or remove ALL saved versions of a given file.
I have been able to find no functional method of using filtering inside powershell to only grab all file versions older than a certain date, or a RANGE of versions. Filtering methods such as piping it to "where-object" simply do not function as expected.
Please improve this to allow us to more easily clear out versions that are between certain version numbers, or all versions older than a given value or date, so we arent forced to remove versions one at a time when OneDrive/Sharepoint has been saving 500+versions and we only want to remove everything older than a week or so.

**Comment by gautamdsheth** [comment]
Hi @rbishop-etq , have fixed the issue related to Get-PnPFileVersion ! Now, it supports piping and where-object .
Thanks for raising the request, it will be available in tomorrow's nightly build.

**Comment by veronicageek** [comment]
@rbishop-etq - You need to use the `-AllowPrerelease` parameter. The version will then be (for example) `1.10.62`. Is that what you've done?

**Comment by veronicageek** [comment]
We should release the major version soon

**Comment by rbishop-etq** [comment]
Okay if you can share the release schedule or any other info on when we can expect this i would appreciate it. 
Please also share confirmation that we will be able to run a get-pnpfileversion piped to a where-object filter and then pipe that to a foreach-object command to remove only the specific versions wanted. Otherwise please provide the recommended way to only remove a specific filter of file versions.

**Comment by rbishop-etq** [comment]
Hello, i just noticed that 1.11.0 is now released, and it appears to be working as requested.
Thanks so much for the assistance with this!!

**Comment by rbishop-etq** [comment]
I know this has been closed, and it is technically working, but it moves SO SLOWLY.
When you run the command to remove all versions, its done in seconds, as is removing a single version.
But when utilizing where-object and foreach-object to specify a range of versions to remove, it take SO LONG to complete, meaning each version takes 5-10 seconds to delete which really adds up when there are hundreds or thousands of versions of a file. Is there any faster method to remove a range of versions outside of piping them to a foreach and making powershell do the remove call for each version one at a time?
