### ISSUE TITLE
[FEATURE] Huge file transfer

### ISSUE THREAD

**Issue by CrustyApplesniffer** [pnp/powershell#1026]
I'm trying to publish a setup program, an artifact of a devops build pipeline, to Sharepoint Folder.
Now it is a huge binary (almost 1GB) and I get the following message:
`The request message is too big. The server does not allow messages larger than 262144000 bytes
`
Is there any plan to add a variation of Add-PnPFile cmd to allow uploading files bigger then 262144000 bytes ?

(maybe using something like : https://sharepoint.stackexchange.com/questions/161845/using-chunked-upload-startupload-with-sharepoint-rest-api)

**Comment by gautamdsheth** [comment]
Hello, we are already doing chunk upload for files >10 MB. 
Can you try to upload a video or similar large file in your local machine instead of devops ?

**Comment by gautamdsheth** [comment]
Closing it due to lack of response. 
Please use the latest version of PnP PowerShell and open a new issue if it still happens
