### ISSUE TITLE
Add-PnPSiteCollectionAppCatalog does not work

### ISSUE THREAD

**Issue by dbahnms** [pnp/powershell#1028]
Its more an information
PnP.Powershell

### Expected behavior 
Add-PnPSiteCollectionAppCatalog creates an whitelist entry to enable the site collections app catalog

### Actual behavior 
![image](https://user-images.githubusercontent.com/84786547/130217577-2c476662-4152-49dc-921d-7b79d50d5d21.png)
Tested with SharePointPnP.Modules, too. Here it works.

### Steps to reproduce behavior
$con = Connect-PnPOnline -Url $url_admin -Interactive #-UseWebLogin
Add-PnPSiteCollectionAppCatalog -Site $url -Connection $con

Connection info:
![image](https://user-images.githubusercontent.com/84786547/130218078-c608ee2f-9344-43fe-b4ff-f490b78fafd0.png)
Module info:
![image](https://user-images.githubusercontent.com/84786547/130218132-b7ff3a43-82ec-4a75-9c32-1cfc030b409e.png)

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@dbahnms - What is it you're reporting exactly? Information or issue? If an issue, can you please translate the error message in english please? Thanks.

**Comment by dbahnms** [comment]
Hi, it´s an issue. But currently exist so much PnP.Powershell problems mostly with the same error (401), this indicates a fault in a basic component.

Add-PnPSiteCollectionAppCatalog generates an error (short form) "Permissions required (site collection admin or tenant admin) to change app catalogue entries"

**Comment by gautamdsheth** [comment]
@dbahnms - yeah you need to be a SharePoint admin to execute this cmdlet, 401 most likely indicates that you dont have sufficient permissions to execute them. 

Please try them with a tenant admin account.

**Comment by dbahnms** [comment]
> @dbahnms - yeah you need to be a SharePoint admin to execute this cmdlet, 401 most likely indicates that you dont have sufficient permissions to execute them.
> 
> Please try them with a tenant admin account.

![image](https://user-images.githubusercontent.com/84786547/132326273-baaf3ec4-119a-49b5-affd-435bb40eca02.png)

**Comment by gautamdsheth** [comment]
Sorry unable to reproduce this issue:

![image](https://user-images.githubusercontent.com/8832018/133853826-c58da075-cd3d-4e33-8853-b640c438df47.png)

Any chance you can try this on another site collection or another tenant maybe ?

**Comment by KoenZomers** [comment]
Works fine here too: 

![image](https://user-images.githubusercontent.com/5940670/134886681-d7391d70-b09b-4c00-84e6-bb33faaa753a.png)

@dbahnms mind sharing a Fiddler trace privately (do not post it here!) while you execute these cmdlets so we can try to see why it fails for you?

**Comment by dbahnms** [comment]
Yes, now it works. I changed nothing. Even #963 works without changing the library (1.7.0). Strange....
Issue can be closed.
