### ISSUE TITLE
[FEATURE] Allow setting ThumbnailUrl when creating/updating site designs

### ISSUE THREAD

**Issue by tarjeieo** [pnp/powershell#1029]
**Is your feature request related to a problem? Please describe.**
With the cmdlets Add-PnPSiteDesign and Set-PnPSiteDesign, you cannot set ThumbnailUrl, like you can in the classic SPO cmndlets https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spositedesign?view=sharepoint-ps.

**Describe the solution you'd like**
It would be helpful if ThumbnailUrl was added as a parameter to allow setting the preview image for site designs. Contrary to what you would expect, setting the parameter "PreviewImageUrl" does not set this (actually I don't know what the effect of this parameter is, I can't see anything is changing in the UX).

**Comment by gautamdsheth** [comment]
Hey @tarjeieo , thanks for creating this feature request.
It has been done, will be available in tomorrow's nightly build onwards, 1.7.26-nightly onwards !

**Comment by tarjeieo** [comment]
That was fast! Great stuff 🤩 Thanks
