### ISSUE TITLE
Get-PnPView Not showing all public views

### ISSUE THREAD

**Issue by JaeEmAre67** [pnp/powershell#1031]
Connect-PnPOnline https://oursite.com -UseWebLogin
Get-PnPView -List "OurList"

These commands show most of the views available in OurList however not all. A Public view, Public View, was created manually a few days ago. However this does not show in the list of views from the above commands. A Private view, PrivateView, that was created months ago *is* showing in the list.

**Comment by veronicageek** [comment]
Closing as no answer.
