### ISSUE TITLE
[FEATURE] Remove-PnPSiteCollectionAdmin Unable to remove user as it wasn't found. User will be skipped.

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#1032]
**Is your feature request related to a problem? Please describe.**
When running ```Remove-PnPSiteCollectionAdmin -Owner useer@contoso.com``` it will throw a warning also a user is on the list of site collection administrators:
```
WARNING: Unable to remove user as it wasn't found. User will be skipped.
```
It appears ```Remove-PnPSiteCollectionAdmin``` enumerates through user titles, not email addresses, which annoying

**Describe the solution you'd like**
It would be great to have ```Remove-PnPSiteCollectionAdmin``` accept email addresses with ```-Owners``` parameter.

**Describe alternatives you've considered**
```Get-PnPSiteCollectionAdmin | where { $_.Email -eq 'owner@contoso.com' } | Remove-PnPSiteCollectionAdmin```

**Additional context**
PnP.PowerShell 1.7.22

**Comment by gautamdsheth** [comment]
Can you try with the latest nightly ? I fixed some stuff related to this command.

**Comment by gautamdsheth** [comment]
Closing this due to lack of response. Please reopen it if the issue exists.

**Comment by robertcaretta** [comment]
@gautamdsheth - Could you re-open this ticket? I'm actually having the same issue.  

**SPO Processes**
WORKS: I have added my account as an additional site collection administrator. That part works fine. I used Set-SPOUser -Site $site.Url -LoginName $adminAcct -IsSiteCollectionAdmin $true 

DOESNT WORK: Then I tried the SPO commands to remove the account and it does not like that, it nags saying "A user may not remove his or her account from a site collection".

**PnP Process**
DOESNT WORK: I am signed in with that account and connected to a test site.  That account definitely is an additional administrator. I am attempting to remove the account using Remove-PnPSiteCollectionAdmin -Owners 'myemail@company.com', by using the same account.  I am receiving the message from this ticket "_WARNING: Unable to remove user as it wasn't found. User will be skipped._"

I'm trying to find a way to mass add an account to several sites, make a change, then remove that same account.  Struggling with finding a clean way of doing this.
