### ISSUE TITLE
Using Set-PnPPage creates a new page instead of changing the options on pages in folders

### ISSUE THREAD

**Issue by mattdreher** [pnp/powershell#1036]
Similar to issue #755 , when I use Set-PnPPage to turn off comments on the page that exists in a folder, it creates a new page instead of modifying the page in the folder.

Run this on the existing page that exists in a separate folder for example /SitePages/Test/Test.aspx
`Set-PnPPage -Identity "Test.aspx" -CommentsEnabled:$false`

The existing page isn't modified, a new page at the root is created with the same contents of /SitePages/Test/Test.aspx  I am not creating the page though PowerShell using Add-PnPPage, so I cannot pipe that output to modify the page as these pages are already created.  Using version 1.7.0.

**Comment by veronicageek** [comment]
@mattdreher - There's no issue with the `Set-PnPPage` command. I've tried with `1.7.39` and I can turn off the comments when the page already exist.

```powershell
$page = 'PagesFolderTest/TestPage.aspx'
Set-PnPPage -Identity $page -CommentsEnabled:$false
```

**Comment by mattdreher** [comment]
I just tried it with version 1.7.39 after your message and it works. Thanks.
