### ISSUE TITLE
Set-PnPListItem - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Yermek-Zhandauov** [pnp/powershell#1037]
SharePoint Online
PSVersion 7.1.0
PnP.PowerShell - 1.7.4 

![error](https://user-images.githubusercontent.com/59475472/127667515-40a76785-f758-4383-bbd6-758425e71eca.PNG)

When trying to update Managed Metadata field **Set-PnPListItem -List $ListName -Identity $id -Values @{"Field Name" = $TermGUID} -Connection $PnPConnection -UpdateType SystemUpdate -Batch $batch**  I am getting error with the message: 

Message          : Object reference not set to an instance of an object.
Stacktrace       :    at PnP.PowerShell.Commands.Utilities.ListItemHelper.GetFieldValues(IList 
                   list, IListItem existingItem, Hashtable valuesToSet, ClientContext 
                   clientContext, PnPBatch batch)
                      at PnP.PowerShell.Commands.Lists.SetListItem.ExecuteCmdlet()
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()

**Comment by veronicageek** [comment]
@Yermek-Zhandauov - Can you please update the module to the latest and ALSO try without the `-Batch` option. Thanks

**Comment by veronicageek** [comment]
Closing as no response.
