### ISSUE TITLE
[BUG] Few commands not working

### ISSUE THREAD

**Issue by Employee87** [pnp/powershell#1042]
### Reporting an Issue or Missing Feature

These do not work

1. Changing theme to one of the out of the box ones
Set-PnPWebTheme -Theme "Teal"
But if I use a name of a custom theme I've deployed, it works

2. Remove sections of the page
$pg = Get-PnPPage -Identity "Home"
$sectionsCount = $pg.Sections.Count
for($i=$sectionsCount-1; $i -ge 0; $i--) {
    write-host $i
    $pg.Sections.RemoveAt($i)
}
$page = Set-PnPPage -Identity $pg -Publish

3.
Remove an add-in (spfx extension) from a site (not app catalogue)
Uninstall-PnPApp -Identity 150520F1-9488-423C-8006-AC541078B029

### Expected behavior 
1. Should change the theme to the out of the box Teal theme
2. Should remove all sections of the home page
3. Should remove the addin from the site (not remove from the app catalogue)

### Actual behavior 
1. gives unknown error
2. Nothing happens, sections still on page
3. App add-in is still on site

### Steps to reproduce behavior
Connect to site using latest version with -Interactive and run the above code.

### What is the version of the Cmdlet module you are running?
Manifest   1.7.0      PnP.PowerShell

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

These commands worked in the legacy version.

**Comment by veronicageek** [comment]
@Employee87 - Please open an issue for each command that is not working, that'll facilitate troubleshooting and they might not use the same code behind the scene. Do not bundle them all together.
