### ISSUE TITLE
[BUG] - Get-PnPListItem only returning folder, if param -Query is included

### ISSUE THREAD

**Issue by brunoferreira2007** [pnp/powershell#1046]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
When we run the command "Get-PnPListItem" we get the items on a specific list/library. By including the param "-Query" we can specify a filter to apply to the resulting items array.

### Actual behavior 
On a Document Library, if we apply this param, we only get folders in return (no files).

### Steps to reproduce behavior
on an existing document library with some files and folders, run the following

`Get-PnPListItem -List <ID> `
Result: you should be able to see an array with all files and folders

`Get-PnPListItem -List <ID> -Query "<View><Query><Where><IsNotNull><FieldRef Name='ID' /></IsNotNull></Where></Query></View>"`
Result: you should be able to see the same result, but only folders are returned

### What is the version of the Cmdlet module you are running?
V1.7.0

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@brunoferreira2007 - I have no problem running your query and showing the same results with `1.7.39`. Please update and try again.

![image](https://user-images.githubusercontent.com/25181757/132031197-e85504aa-82c7-46d5-9104-a7f7a1ce160d.png)

![image](https://user-images.githubusercontent.com/25181757/132031235-24cd2146-b2ad-4afa-a5d9-d95db7084d91.png)

**Comment by veronicageek** [comment]
Closing as no answer.

**Comment by brunoferreira2007** [comment]
@veronicageek , sorry I was on vacation could not answer before... 
I update it to v1.7.59 but I'm still getting the same issue... could be this related with a dependency?
![image](https://user-images.githubusercontent.com/33944868/134524344-9218b1cb-237f-4610-bd61-69539b4d4ebe.png)
