### ISSUE TITLE
[BUG] New-PnPSite -Type TeamSite does not take owner when using application permission

### ISSUE THREAD

**Issue by RoSchoe** [pnp/powershell#1047]
### Reporting an Issue or Missing Feature
If you connect with
`$con= Connect-PnPOnline -Tenant $aadomain -ClientId $appId  -Thumbprint $thumbprint -Url $site -ErrorAction Stop`

and you want to use it with App-Principal to create moder teamsite with group:
  
`$newUrl = New-PnPSite -Type TeamSite -Title "DEV Owner Test" -Alias "owner00135" -Owners "max.mustermann @tenant.onmicrosoft.com" -ErrorAction Stop `

owners are ignored. 
Only the App-Principal is set as owner to group.

If you now add the owner to the group with graph it takes about 10 minutes if they are usable in SharePoint GUI of modern page to add other users.
      

### Expected behavior 
owners should be added

### Actual behavior 
owners are ignored

### Steps to reproduce behavior
connect to m365 like above
use command above

### What is the version of the Cmdlet module you are running?
pnp 1.7

### Which operating system/environment are you running PnP PowerShell on?
Azure Automation

**Comment by veronicageek** [comment]
Closing as no response.
