### ISSUE TITLE
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Apply-PnPProvisioningTemplate : Cannot invoke method or retrieve property from

### ISSUE THREAD

**Issue by AravindaRao** [pnp/powershell#1053]
We are able to connect to the SharePoint site using Connect-PnPonline. We getting error when running Get-PnpTermGroup command.

**Comment by AravindaRao** [comment]
We are able to connect to the SharePoint site using Connect-PnPonline. We getting error when running Get-PnpTermGroup command.

error: Get-pnPTermGroup : cannot invoke method or retrieve property from null object. Object returned by the following call stack is null. "GetDefau1tSitec011ectionTermstore 
Microsoft.Sharepoint.Taxonomy.Taxonomysession.Get Taxonomysession

**Comment by AravindaRao** [comment]
`Connect-PnPOnline "https://SharePoint Site URL"
Get-PnPtermGroup`

SharePoint 2013 PnP PowerShell Version: 3.29.2101.0

**Comment by AravindaRao** [comment]
tried below steps but still not working -
Go to the managed Metadata service (Central Admin -> Service Applications)
	
Select Managed Metadata Service Proxy and click Properties (button in the ribbon).
	
Check option "this application is default storage for keywords and for termsets".

**Comment by gautamdsheth** [comment]
Hello, going to close this issue because this module only works for SharePoint online, not for OnPrem 
The older version of PnP PowerShell, which you are using has been deprecated so we wont be fixing issue related to it.

**Comment by AravindaRao** [comment]
Hi , thanks for responding. I see  3.29.2101.0 as the current version.

**Comment by gautamdsheth** [comment]
Yeah, that version is deprecated. We don't support that version.
This is repo is for the new PnP PowerShell, with a major version 1.7.0
This new module is for SharePoint online only.

**Comment by AravindaRao** [comment]
Sorry to askagain , but is there any other GitHub place , were I can go for support for older versions of PnP?
