### ISSUE TITLE
-confirm parameter not taken by rename-PnPFile

### ISSUE THREAD

**Issue by GeorgeChiuTheHartford** [pnp/powershell#1056]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting
-confirm 

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

-confirm parameter so there will be no need to acknowledge every single rename

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

See below

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)
PS C:\WINDOWS\system32> Connect-PnPOnline -Url 'https://thehartford.sharepoint.com' -Interactive
PS C:\WINDOWS\system32> Rename-PnPFile -confirm:$false -ServerRelativeUrl "/sites/ClaimsITPortal/Large Loss Notice Reporting/_Daily Reports/Archive/sue/Test1.xlsx" -TargetFileName "TestChiu.xlsx" -confirm:$false
Rename-PnPFile : A parameter cannot be found that matches parameter name 'confirm'.
At line:1 char:16
+ Rename-PnPFile -confirm:$false -ServerRelativeUrl "/sites/ClaimsITPor ...
+                ~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Rename-PnPFile], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,PnP.PowerShell.Commands.Files.RenameFile

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

1.7.0

PS C:\WINDOWS\system32> Get-Module -Name "PnP.PowerShell" -ListAvailable

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.7.0      PnP.PowerShell                      {Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add-PnPClientSideText, Add-PnPClientSideWebPart...}

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Maybe you can use it like this ? 

`Rename-PnPFile -confirm:$false -ServerRelativeUrl "/sites/ClaimsITPortal/Large Loss Notice Reporting/_Daily Reports/Archive/sue/Test1.xlsx" -TargetFileName "TestChiu.xlsx" -Force`

**Comment by GeorgeChiuTheHartford** [comment]
While -confirm flag is not working.   -force flag works so I am good but the documentation should be updated in my opinion.

**Comment by veronicageek** [comment]
@GeorgeChiuTheHartford - That's correct. The `-Confirm` parameter doesn't exist so not sure why it's in the _Parameters_ section. The `-Force` param should be used. We'll amend the documentation.

**Comment by gautamdsheth** [comment]
@GeorgeChiuTheHartford , the documentation has been updated by @veronicageek !
Please use the `-Force` parameter to avoid the confirmation prompt.
Thanks for reporting.
