### ISSUE TITLE
[BUG] Add-PnPDataRowsToSiteTemplate : List does not exist in the template file!

### ISSUE THREAD

**Issue by Macro21** [pnp/powershell#1058]
### Notice

When I try to add the elements of a list to a pnp template with the names of lists and columns in multiple languages, I get this error:

![image](https://user-images.githubusercontent.com/24574303/131793736-cfa5570d-452c-48aa-af45-bf43439e22aa.png)

And in the template.pnp:

![image](https://user-images.githubusercontent.com/24574303/131793937-11eefc83-cb74-4a73-b7ec-0a044b4eae28.png)

.resx files:

![image](https://user-images.githubusercontent.com/24574303/131795164-117f8a9c-795a-49d1-b52e-ac232a7a8e5e.png)

### Steps to reproduce behavior

1. Install **PnP.PowerShell 1.7.0** 
2.  Use **Get-PnPSiteTemplate** -Out ./template.pnp -PersistMultiLanguageResources
3. Use **Add-PnPDataRowsToSiteTemplate** -Path template.pnp -List 'TemplateList' -Query "xml for the query (image 1)"

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@TamasAkos - You're using the SharePoint Management Shell from Microsoft. **Not the PnP PowerShell module** (this repo).

However, if this issue also occurs with the Microsoft module, then it could a problem on the server side. Can you and @Macro21 update the PnP Module to the latest release (major `1.9.0` or nightly release) and feedback.

@gautamdsheth @KoenZomers - FYI.

**Comment by gautamdsheth** [comment]
Hi, have merged a PR to fix this issue.
It will be available from tomorrow's nightly.
Thanks for raising the issue.
