### ISSUE TITLE
[BUG] Connect-PnPOnline - Keyset does not exist

### ISSUE THREAD

**Issue by Nibushi** [pnp/powershell#106]
### Reporting an Issue or Missing Feature
If I run Connect-PnPOnline locally using a certificate (stored in the local machine certificate store) and supplying the parameters (Tenant, Thumbprint and ClientId ) the command fails when using PnP.PowerShell (0.3.33):

Connect-PnPOnline -Url $Url -Tenant $tenant -Thumbprint $thumbprint -ClientId $clientId

Error message: Connect-PnPOnline: Keyset does not exist
Message : Keyset does not exist
Stacktrace : at PnP.PowerShell.Commands.Base.ConnectOnline.ProcessRecord() in D:\a\powershell\powershell\src\Commands\Base\ConnectOnline.cs:line 293
at System.Management.Automation.CommandProcessor.ProcessRecord()
ScriptLineNumber : 1

If I run the exact same command and parameters (Tenant, Thumbprint and ClientId ) on my local machine but use SharePointPnPPowerShellOnline (3.22.2006.2) the Connect-PnPOnline command works. The same command and parameters also works inside an Azure Function without any issues.

### Expected behavior 
Would expect the command to successfully establish a connection with SharePoint Online

### Actual behavior 
Error message: Connect-PnPOnline: Keyset does not exist
Message : Keyset does not exist
Stacktrace : at PnP.PowerShell.Commands.Base.ConnectOnline.ProcessRecord() in D:\a\powershell\powershell\src\Commands\Base\ConnectOnline.cs:line 293
at System.Management.Automation.CommandProcessor.ProcessRecord()
ScriptLineNumber : 1

### Steps to reproduce behavior
Create App registration using certificate
Supply tenant, thumbprint and clientId as variables

Connect-PnPOnline -Url $Url -Tenant $tenant -Thumbprint  $thumbprint -ClientId $clientId

### What is the version of the Cmdlet module you are running?
0.3.33 - Have tried previous versions as well.

As I say above, the exact same command and parameter values works using the SharePointPnPPowerShellOnline module.

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by LeonArmston** [comment]
Hi Nibushi

I have just tried upgraded to the nightly version 0.3.33 and tried to connect using exact same command (albeit with a certificate I created a while back) and I was able to connect fine then get all the lists in the SharePoint site (see image below). I am using Windows

![image](https://user-images.githubusercontent.com/12968962/104293936-82319280-54b6-11eb-8226-664a37365050.png)

From memory KeySet is to do with the certificate are you using the same certificate when you auth usingSharePointPnPPowerShellOnline

Also check the certificate created has a primary key and has been generated correctly.

**Comment by Nibushi** [comment]
Hi @LeonArmston, thanks for testing this. The certificate was created using New-PnPAzureCertificate and is the exact same certificate which I use SharePointPnPPowerShellOnline. I've retried the command again and I am still getting the KeySet issue.

**Comment by erwinvanhunen** [comment]
@Nibushi : We identified an issue that might cause this. We're working on/testing a fix as we speak. It can mean you will have to recreate your certificate though.

**Comment by Nibushi** [comment]
@erwinvanhunen no problem. Thanks for letting me know. Happy to test once the fix has been released.

**Comment by erwinvanhunen** [comment]
We just release 0.3.34-night. A few things have changed:

New-PnPAzureCertificate now supports a -Store parameter, allowing you to immediately add a certificate to the store. We also changed the way we generate the certificate when running on Windows.
Register-PnPAzureAAApp will by default now use popup windows when executed on Microsoft Windows to walk people through the consent flow.
Register-PnPAzureADApp will by default export the certificates to the file system too.

**Comment by Nibushi** [comment]
I ran the following command using build 0.3.35 and can confirm that the step through process worked which was really good:
Register-PnPAzureADApp -DeviceLogin -ApplicationName TestApp -Tenant $tenant -CertificatePassword (ConvertTo-SecureString -String $certPassword -AsPlainText -Force) -Store CurrentUser

I was then able to connect using
Connect-PnPOnline -Url $Url -Tenant $tenant -Thumbprint $thumbprint -ClientId $clientId

You may need to update the Example text in the help as I had to build the command up based on the text in the other examples.

I noticed that the certificate was put in the local user certificate, this may have been the issue initially as I had the certificate installed in the local machine personal certs. I'll go back and look at that myself, however, the issue is now resolved.

Really like the walk through process, works really well.

**Comment by elementlu** [comment]
I'm trying to understand this thread and I'm not sure what the resolution is. The key was to use the -store command at the time of certificate generation?

I am getting the keyset does not exist error. However when I go to the certificate management, remove the cert, then add the cert back, everything works. However after a week, I will get keyset does not exist again.

My import is:
Import-PfxCertificate -Exportable -CertStoreLocation Cert:\LocalMachine\My -FilePath .\$certname.pfx #Install certificate

Thank you in advance.

**Comment by Nibushi** [comment]
Hi @elementlu , I never experienced the issue again when using the new releases of the module. I think the combination of things being fixed behind the scenes and me ensuring that the certificate was in my local user's certificate store resolved the issues I had.

I've recently used the New-PnPAzureCertificate and the Register-PnPAzureADApp commands for different demos and both worked successfully. I've never had to re-import the certificate periodically.

Sorry I can't be of more use.

**Comment by elementlu** [comment]
i imported the cert into the user store instead of system and the keyset error has not comeback. still odd though

**Comment by Nibushi** [comment]
Hi @elementlu , I have been able to reproduce the "Connect-PnPOnline: Keyset does not exist" message again using the Register-PnPAzureADApp cmdlet. 

I normally use VS Code for PowerShell so that is where I do most of my testing and using the certificate created by Register-PnPAzureADApp works in there without any issues. I ran the following command:

Register-PnPAzureADApp -ApplicationName $ApplicationName -OutPath "E:\tempPnPCerts" -CommonName "xxxxxxxxxxxxxxxx" -ValidYears 1 -CertificatePassword $pwd -Store CurrentUser -Tenant "xxxxxxxxxxxx" -GraphApplicationPermissions Group.ReadWrite.All,User.Read.All -SharePointApplicationPermissions Sites.FullControl.All, User.Read.All -Interactive

The app and the certificate were created successfully and Connect-PnPOnline worked without any issues in VSCode.

However, as a test I tried using the Windows Terminal and PowerShell 7.2.1 using the same certificate and I received the Keyset does not exist message. After re-importing the certificate which had been created I was able to successfully connect using Connect-PnPOnline. 

 Not sure what console you are using but I have been able to reproduce this behavior three times this morning.

@erwinvanhunen, is this something that you can test? I've only tried this on a single machine at the moment so I can't rule out something particular with my Windows Terminal set up but it hasn't been altered in anyway.

**Comment by elementlu** [comment]
@Nibushi I was doing my testing with PowerShell ISE. The server I was trying to run this job didn't have VScode.

**Comment by BartRamharter** [comment]
After getting this same problem, I can indeed confirm that certificates from the LocalMachine store can only be read from an elevated process when using connect-pnponline. I have not tested adding the SharePointPnPPowerShellOnline back to the mix, but I do remember removing it because it was no longer necessary (I thought) after upgrading to v 1.11 of PnPOnline.
But preliminary test does show that it works when started elevated and gets the keyset error when not elevated.

**Comment by weyCC81** [comment]
For you Information: Run the PowerShell as Admin and it woks to Access the Computer Certificate Store

**Comment by BartRamharter** [comment]
That is what 'run in elevated process' means... But as I mentioned, the day after, it also works when running as (non-admin) regular process. Still no idea why.

**Comment by iainfm** [comment]
I think I've figured this out. It is a permissions thing. To fix:

Open mmc/local computer certs
Locate the cert under Personal\Certificates
Right-click -> All Tasks -> Manage private keys
Grant the user(s)/group(s) read permission
