### ISSUE TITLE
[BUG] Set-PnPTraceLog: log file is empty

### ISSUE THREAD

**Issue by sadomovalex** [pnp/powershell#1061]
### Reporting an Issue or Missing Feature
When use Set-PnPTraceLog (PnP.PowerShell 1.7.0) output log file is empty:
```powershell
Set-PnPTraceLog -On -LogFile "output.log" -Level Debug
```

### Expected behavior 
Output log file is not empty and contains logging information from PnP.PowerShell cmdlets.

### Actual behavior 
Output log is empty.

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 1.7.0

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows

**Comment by Leif-Frederiksen** [comment]
I have same issue.

**Comment by jmcanally** [comment]
Same issue here, specifically with Get-PnPSiteTemplate

**Comment by gautamdsheth** [comment]
Hopefully, will be resolved by this fix.
Am keeping the issue open till we release 1.8, strangely it works with nightly releases, so will keep an eye on it.

**Comment by YeeSkywalker** [comment]
I have the same issue with command 'Invoke-PnPTenantTemplate -Path ./starterkit.pnp '

**Comment by AndreSchiemann** [comment]
Any updates on this issue? 
I do not get trace logs in the console using the command **Invoke-PnPSiteTemplate** using version 1.7.0 or 1.8.0.

**Comment by Micael-stack** [comment]
Same here on 1.8.0. Trace log is created but empty. Ps 7.2 on win 10.

**Comment by salascz** [comment]
It's kind of annoying issue, specially when an error occurs on build environment :-(. (Without interactive prompt option)

Do we know, what went wrong? The trace logger listener seems to be working, but there are no messages written to the Trace...

Any workaround?

Thanks

**Comment by ygrenier** [comment]
I had an idea.

PnP.PowerShell use the PnP.Framework.Diagnostics.TraceLogger (from the  PnP.Framework.dll) wich using the System.Diagnostic.Trace class.

In the PnP.Framework project I see in the Release configuration the TRACE variable is not defined, so because the ConditionalAttribute on the Trace class, the code calling Trace methods is not generated.

I tested with building a new PnP.Framework.dll with the TRACE variable enabled, and my log files are filled.

I don't know how to report this feedback ?

Regards

**Comment by Micael-stack** [comment]
@ygrenier that would be on the pnp site core side of the project, https://github.com/pnp/pnpframework. Thanks for validating. If we could find which commit changed this variable though, that would be nice...

**Comment by ygrenier** [comment]
> @ygrenier that would be on the pnp site core side of the project, https://github.com/pnp/pnpframework. Thanks for validating. If we could find which commit changed this variable though, that would be nice...

Thanks, I found the problem: the nightly build use the Release configuration instead of Debug since some month.

**Comment by Micael-stack** [comment]
Merci @ygrenier ! Ok it's in the build script that changes were done. I wasnt looking at the right place! So if using Build-Debug.ps1 locally, it fixes the problem...

![image](https://user-images.githubusercontent.com/52808567/145852971-ebf6f778-7010-4017-a9f8-da87a08755f0.png)

**Comment by sadomovalex** [comment]
thanks @ygrenier for sharing your finding!
@Micael-stack are there any plans for providing this fix in upcoming release?

**Comment by sadomovalex** [comment]
@gautamdsheth @erwinvanhunen could you check provided information please. I think root cause is found

**Comment by ygrenier** [comment]
> @gautamdsheth @erwinvanhunen could you check provided information please. I think root cause is found

Yes @gautamdsheth opened a PR [Fix #547 - issue with trace log](https://github.com/pnp/pnpframework/pull/548) to fix it.

**Comment by jdegiglio** [comment]
All - I just ran the test that I posted in Oct using version 1.9.0 and the log file was populated as expected. Thanks for the hard work tracking this down!

**Comment by gautamdsheth** [comment]
@jdegiglio - thanks for confirming the fix.

@ygrenier - thanks for the amazing investigation :) 

Closing it now !
