### ISSUE TITLE
[BUG] Get-PnPUser does not return values for non-default retrievals when also using the -Identity option

### ISSUE THREAD

**Issue by joerodgers** [pnp/powershell#1065]
### Reporting an Issue or Missing Feature
When using the Get-PnPUser cmdlet with the _-Identity_ and _-Includes_ options, none of the properties listed in the includes option are returned.  The options are returned if remove the -Identity option and filter the result set on the client side, but that's a terrible practice when needing to target a single user.

### Expected behavior 
I would expect the Expiration property value to be returned by this cmdlet syntax.

`Get-PnPUser -Identity "i:0#.f|membership|john.doe@contoso.onmicrosoft.com" -Includes Expiration`

### Actual behavior 
The defined property value, _Expiration_ in this case, is not returned for the user object.  

### Steps to reproduce behavior

User expiration is populated:

```
$user = Get-PnPUser -Includes LoginName, Expiration | Where-Object -Property LoginName -eq "i:0#.f|membership|john.doe@contoso.onmicrosoft.com"
$user.Expiration 
```

User expiration is not populated:

```
$user = Get-PnPUser -Identity "i:0#.f|membership|john.doe@contoso.onmicrosoft.com" -Includes LoginName, Expiration 
$user.Expiration 
```

### What is the version of the Cmdlet module you are running?
1.7.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by KoenZomers** [comment]
I can't get this reproduced. In both cases, it will retrieve the Expiration property. Although I must say in both cases it returns an empty string for me, but it does query SharePoint Online for it in both scenarios. Can you elaborate on what I need to do to get a value populated in the Expiration column?

**Comment by gautamdsheth** [comment]
Closing it due to lack of response.
