### ISSUE TITLE
[BUG] Unregister-PnPHubSite 

### ISSUE THREAD

**Issue by arnemo** [pnp/powershell#1066]
### Reporting an Issue or Missing Feature
Unregister-PnPHubSite -Site https://{my-tenant}.sharepoint.com/sites/{my-site} throws an error. The site exists and is a hub site.

### Expected behavior 
Cmdlet to execute without error and the target site should be unregistered as a hub site

### Actual behavior
Unregister-PnPHubSite : Objektreferensen har inte angetts till en instans av ett objekt. (Objectreference has not been designated as an instance of an object)
CategoryInfo          : WriteError: (:) [Unregister-PnPHubSite], NullReferenceException
FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Admin.UnregisterHubSite

### Steps to reproduce behavior
1. Create communication site
2. Make it a hub site
3. Connect-PnPOnline (to target tenant)
4. Unregister-PnPHubSite -Site https://{my-tenant}.sharepoint.com/sites/{my-site}

### What is the version of the Cmdlet module you are running?
1.7.0

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@arnemo - I have no problem with `1.7.39`. Can you please update and try again.

![image](https://user-images.githubusercontent.com/25181757/132027790-54533c80-e3fe-40ac-b72c-0064d7550cfe.png)

**Comment by arnemo** [comment]
Issue persists with 1.7.39-nightly

**Comment by arnemo** [comment]
![Inkedpowershell_ise_tUrYZOiNok_LI](https://user-images.githubusercontent.com/4289376/132194068-3f58e733-8d2f-467e-ab6e-7d93dcb997bc.jpg)
![Inkedchrome_RoXrlRw3CE_LI](https://user-images.githubusercontent.com/4289376/132194090-d305fbba-06a9-4248-825b-c72af44aa078.jpg)

**Comment by veronicageek** [comment]
Can you try creating another 2 (test) sites and make one the hubsite, and link the other one. Then re-run the `Unregister-PnPHubSite` on your (new) hubsite? I have no problem so hard to troubleshoot.

**Comment by arnemo** [comment]
Created new sites, created hub and connected the other one. Targeted the hub with Unregister-PnPHubSite, got the same error. Did the same procedure on another tenant and it executed as expected (no error).

**Comment by gautamdsheth** [comment]
Then its safe to say that there is some issue with your tenant or site collection and not with the PnP PowerShell cmdlet. Not sure we can do anything about it.
