### ISSUE TITLE
[BUG] Set-PnPHomePage is showing "File Not Found Error "

### ISSUE THREAD

**Issue by rohit18121812** [pnp/powershell#1074]
### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting
Set-PnPHomePage is showing "File Not Found Error "

I use this script -
**Connect-PnPOnline -Url https://<tenant>/sites/<site collection><subsite>
 $sites=Get-PnPSubWebs
 foreach($site in $sites)
 {
 $site.ServerRelativeUrl
 Set-PnPHomePage -RootFolderRelativeUrl \sitepages\Home.aspx -web $site.ServerRelativeUrl
 }****
### Expected behavior 
Should set the home page for each subiste to home.appx
THe site pages gallery is there when home.aspx as I am mannually able to go and make it home page.

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.
Set-PnPHomePage : File Not Found.
At line:6 char:1
+ Set-PnPHomePage -RootFolderRelativeUrl \sitepages\Home.aspx -web $sit ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPHomePage], ServerException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Branding.SetHomePage

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

Connect-PnPOnline -Url https://<tenant>/sites/<site collection><subsite>
 $sites=Get-PnPSubWebs
 foreach($site in $sites)
 {
 $site.ServerRelativeUrl
 Set-PnPHomePage -RootFolderRelativeUrl \sitepages\Home.aspx -web $site.ServerRelativeUrl
 }

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
1.7.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows

**Comment by gautamdsheth** [comment]
The correct way to set the home page is like this - `Set-PnPHomePage -RootFolderRelativeUrl SitePages/Home.aspx`

**Comment by rohit18121812** [comment]
** Didnt work, got the same error ****

Set-PnPHomePage : File Not Found.
At line:6 char:1
+ Set-PnPHomePage -RootFolderRelativeUrl SitePages/Home.aspx -web $site ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPHomePage], ServerException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Branding.SetHomePage
