### ISSUE TITLE
[BUG] Connect-PnPOnline Operations that change non-concurrent collections must have exclusive access. 

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#1088]
### Reporting an Issue or Missing Feature
I am reporting a bug

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

### Actual behavior 
When trying to enumerate SharePoint Online Sites using ```foreach -parallel``` it would throw an error:

> Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
![image](https://user-images.githubusercontent.com/5260172/132707564-6fce6b1b-362b-4eb3-9a68-b3aeb585f9f8.png)

### Steps to reproduce behavior
```
Connect-PnPOnline -Url https://contoso-admin.sharepoint.com -Credentials ( Get-Credential )
$PnPSites = Get-PnPSSite
$PnPSites | foreach -Parallel  { 
    function Connect-PnPSite {
        [CmdletBinding()]
        param (
            $Url
        )
        #should be specified explicitly when inside foreach -parallel 
        $Params = [ordered]@{
            TenantAdminUrl = https://contoso-admin.sharepoint.com
            Thumbprint = 0000-0000-0000-0000
            ClientId = 0000-0000-0000-0000
            Tenant = 0000-0000-0000-0000
        }
        Connect-PnPOnline @PSBoundParameters @Params
    }
Connect-PnPSite -Url $_.url | Out-Null
$lists = Get-PnPList
}
}
```

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 1.7.44

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@YuriySamorodov - Although I tried with `ClientId` and `ClientSecret` (not Thumbprint), I'm **not** able to reproduce your error.  I'm also not familiar with the `-Parallel` parameter to be honest, so not sure what's the goal for it.

There are also a couple of typos in your copy/paste: 
- `$PnPSites = Get-PnPSSite` should read `Get-PnPSite` 
- The last bracket seems unnecessary

**Comment by YuriySamorodov** [comment]
Hi @veronicageek , ```-Parallel``` speaks for itself. This helps enumerate through a collection in multiple threads.

**Comment by YuriySamorodov** [comment]
@veronicageek , just to give you a basic idea of what ```foreach -parallel``` does. 
Here I am looping through 1158 sites using one thread:
![image](https://user-images.githubusercontent.com/5260172/132930149-f6c99efd-37bb-42bb-8550-835cf67f60a2.png)
And here the results if I use 25 threads:
![image](https://user-images.githubusercontent.com/5260172/132930163-b8678210-4c9a-4986-a163-95ea2c7dd420.png)
Quite a difference, right?
However if I uncomment Get-PnPList it would start to throw errors:
![image](https://user-images.githubusercontent.com/5260172/132930213-6370de55-55f6-4c66-9566-c6e1cdf9b667.png)

**Comment by veronicageek** [comment]
Thanks for the explanation @YuriySamorodov. 
I don't know if there's anything happening in the background between PowerShell Core and PnP.PowerShell, so I'll leave this one for @gautamdsheth / @erwinvanhunen.

**Comment by YuriySamorodov** [comment]
Hi, @veronicageek !
Thanks for pointing me in the right direction. It appears the issue is on my side.

Lessons learned:

- ```Foreach-Object -Parallel``` is not the same as ```foreach```.
- ```Foreach-Object -Parallel``` creates a separate PowerShell instance for each new thread
- It's not possible to use functions inside ```foreach -parallel```
- You have to be careful with the connection. In case the following errors get returned, you may need to run ```Disconnect-PnPOnline```:

> Object reference not set to an instance of an object.

> The current connection holds no SharePoint context. Please use one of the Connect-PnPOnline commands which uses the -Url argument to connect.
