### ISSUE TITLE
[BUG] - Error importing PnP.PowerShell module

### ISSUE THREAD

**Issue by anthonywhite** [pnp/powershell#1096]
### Reporting an Issue
Error importing PnP.PowerShell module

### Expected behavior 
Should import

### Actual behavior 
`Import-Module: Bad IL format. The format of the file 'C:\<psmodulepath>\PowerShell\Modules\PnP.PowerShell\1.7.0\Core\PnP.PowerShell.dll' is invalid.`

### Steps to reproduce behavior
Installed module in CurrentUser scope alongside `Microsoft.Online.SharePoint.PowerShell` module

### What is the version of the Cmdlet module you are running?
**1.7.0** on **PowerShell Core 7.1.4**

### Other Information
Connect-SPOService from Microsoft module works as expected in same PowerShell session, installed in same way on same module path

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows 10 x64
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@anthonywhite - I have no issue on my side with PowerShell 7.1.4 and PnP.PowerShell 1.7.0 (Windows/MacOS). 
It might have been a moment in time, or perhaps try on another machine.

![image](https://user-images.githubusercontent.com/25181757/132959363-7b6cfdaa-20e4-48c4-8e15-16002910767e.png)

**Comment by anthonywhite** [comment]
Hi Veronica,
Has persisted through reboots and multiple uninstall/reinstalls. Yes another device works, though slightly different Windows build. Very odd. Has this error been seen before? New to me.

**Comment by veronicageek** [comment]
If it works on another device, then we can agree that this isn't an issue with PnP.PowerShell, so I'm gonna have to close this issue. If this was working before on this particular machine, then you may want to check any potential changes (GPO, missing packages, conflicts, etc...).
