### ISSUE TITLE
[BUG] Get-PnPFileVersion does not return Current Version

### ISSUE THREAD

**Issue by ToddKlindt** [pnp/powershell#1098]
### Reporting an Issue or Missing Feature
Get-PnPFileVersion does not return Current Version. Its output is always one version less than the UI has, and it's always missing the Current version of the file.

### Expected behavior 
I expect the Current version to be included in the list of file versions

### Actual behavior 
I see all of the versions except the Current version.
![image](https://user-images.githubusercontent.com/2659747/132997147-d6be5cd8-f5a7-47c8-9c46-155228092d5d.png)

### Steps to reproduce behavior
 Get-PnPFileVersion -Url "/sites/blah/Shared Documents/Building materials licences to budget for Storytelling.docx"

### What is the version of the Cmdlet module you are running?
1.7.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@ToddKlindt - I had the same question a while ago, and got the following answer from @erwinvanhunen:

> You only see the older versions. Version XYZ is the current version that you get with Get-PnPFile. Eg that's how CSOM works.

**Comment by ToddKlindt** [comment]
If that's the case I propose we make one of two changes. Either change the cmdlet to also make the same CSOM call that Get-PnPFile does to get the current version, or change the help to reflect. Currently it says, "Retrieves all versions of a file." which does not seem true if it's not retrieving the current version of the file.

**Comment by gautamdsheth** [comment]
Agree with you @ToddKlindt , we need to change the docs.
Changing the cmdlet to include the latest version is not possible because we use a different CSOM method to fetch it.
Would you or @veronicageek like to submit a PR to do that ?

**Comment by veronicageek** [comment]
@gautamdsheth - I will amend the documentation 👍🏻

**Comment by ToddKlindt** [comment]
Is editing [this page](https://github.com/pnp/powershell/blob/dev/documentation/Get-PnPFileVersion.md) the correct way to update the documentation and help for the cmdlet?

**Comment by veronicageek** [comment]
Closing as PR has been merged.
