### ISSUE TITLE
[BUG] Add/Set-PnPListItem fails with "Unknown timezone mapping" when updating date fields

### ISSUE THREAD

**Issue by adzero** [pnp/powershell#1109]
### Reporting an Issue
Add-PnPListItem or Set-PnPListItem fails with "Unknown timezone mapping" message when used to update some date fields. 
Date values are set using `ToUniversalTime()`  method. 
Commands are used in batch mode. 

If `ToUniversalTime()` is removed, another error message is displayed : 

```
Set-PnPListItem : A possible object cycle was detected which is not supported. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 0.
Au caractère Ligne:1 : 1
+ Set-PnPListItem -id $itemId -List $listTitle -Values @{DateField=(get-date).ToUniversalTime()}  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPListItem], JsonException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Lists.SetListItem
```

### Expected behavior 
List item should be added or updated with provided date values. 

### Actual behavior 
Command fails when providing Date field in Values parameter inside custom script. 

### Steps to reproduce behavior
Connect-PnPOnline -Url $url -Credentials $credentials
$batch = New-PnPBatch
Set-PnPListItem -id $itemId -List $listTitle -Values @{DateField=(get-date).ToUniversalTime()} -Batch $batch

ends with 

```
Set-PnPListItem : Unknown timezone mapping
Au caractère Ligne:1 : 1
+ Set-PnPListItem -id $itemId -List $listTitle -Values @{DateField=(get-date).ToUniversalTime()}  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPListItem], ArgumentException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Lists.SetListItem
```

Connect-PnPOnline -Url $url -Credentials $credentials
$batch = New-PnPBatch
Set-PnPListItem -id $itemId -List $listTitle -Values @{DateField=(get-date)} -Batch $batch

ends with 

```
Set-PnPListItem : A possible object cycle was detected which is not supported. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 0.
Au caractère Ligne:1 : 1
+ Set-PnPListItem -id $itemId -List $listTitle -Values @{DateField=(get-date).ToUniversalTime()}  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPListItem], JsonException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Lists.SetListItem
```

Connect-PnPOnline -Url $url -Credentials $credentials
$batch = New-PnPBatch
Set-PnPListItem -id $itemId -List $listTitle -Values @{DateField=(get-date).ToUniversalTime()}

OK

### What is the version of the Cmdlet module you are running?
Using the 1.7.0 version of PnP.PowerShell module. Error doesn't occur with 1.6.0 version. 

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@adzero - After testing with `1.7.0`, I can partially reproduce your issue(s)

1) I have no problem with the UTC format and using `-Batch`

![image](https://user-images.githubusercontent.com/25181757/133929931-1ee6857d-95e3-42eb-9768-4244ffc4a8dd.png)

2) I can run with `Get-Date` but you need to use a subexpression `$(Get-Date)` and for some reason, it doesn't update the values when using the `-Batch` (and not providing any error message). Otherwise on its own, it works.

![image](https://user-images.githubusercontent.com/25181757/133930098-11f2b1b3-6d7f-46b5-99fd-77652858614f.png)
 
Note: There are currently some (other) issues with `-Batch` that we're be looking at.

@gautamdsheth / @KoenZomers - FYI

**Comment by adzero** [comment]
@veronicageek , 

thank you for your answer. 
Back to work this morning I did the same tests as you with or without quotes for subexpression : 

![image](https://user-images.githubusercontent.com/7522988/133965864-cdb7d93d-3302-4928-a616-54206f83ac97.png)

As you mentioned, even if the Set command doesn't display an error message, value isn't updated after calling `Invoke-PnPBatch`.

**Comment by a1mery** [comment]
Hi,
I don't know if it helps but I have the same issue and I also work with sites set in French language.

**Comment by veronicageek** [comment]
OK, I'll setup a site in French and try again.

**Comment by veronicageek** [comment]
@adzero @a1mery - I've tested on a site with French settings, and indeed I can get the error "Unknown timezone mapping". when using the `-Batch`. Otherwise, it works (again) on its own (without a subexpression)...

![image](https://user-images.githubusercontent.com/25181757/134051744-5b570c24-3c8b-4bc1-bf16-ebe253f38c30.png)

![image](https://user-images.githubusercontent.com/25181757/134052033-dca21f7f-97de-41a3-aee0-74b965ce14c8.png)

Something's up with the `-Batch` option, we'll have a look at it when we can.

**Comment by KoenZomers** [comment]
I cannot reproduce this issue on my end. It works for me. What am I doing different?

![image](https://user-images.githubusercontent.com/5940670/135361669-b0024ca2-0691-41f8-8602-4afb15b6c339.png)

![image](https://user-images.githubusercontent.com/5940670/135361711-06d80db6-ac5d-4dd3-a6b0-f9c20dbceef1.png)

I am connecting through -Interactive. Could that make the difference here? I do not have non MFA enabled accounts and therefore cannot use -Credentials.

**Comment by veronicageek** [comment]
@KoenZomers - the language needs to be changed. Your list on the screenshot is still in english. I've done the testing and could reproduce above when I had set it French.

**Comment by KoenZomers** [comment]
On my last screenshot I show that I have switched the site regional settings to French. That's not enough? Where should I change the language?

**Comment by adzero** [comment]
@KoenZomers ,

I made another attempt this morning and I'm still able to reproduce the issue. 

![image](https://user-images.githubusercontent.com/7522988/135813244-5cc324a0-9c0a-4089-b55d-af280627dbd7.png)

![image](https://user-images.githubusercontent.com/7522988/135813304-5824f189-411c-4355-81e1-68241074d014.png)

When not using batch, command works with and without using a sub-expression.

**Comment by gautamdsheth** [comment]
Is the issue still present ? Can you please test with the latest 1.8 nightly and check ? I tried this with a French site and language + regional settings, but couldnt reproduce it.

**Comment by a1mery** [comment]
On my side, I cannot reproduce the issue anymore 👍 
Thank you !

**Comment by KoenZomers** [comment]
@a1mery Thanks for confirming.
@adzero Can you also verify this on your side with the latest nightly to see if the issue has been solved for you?

**Comment by adzero** [comment]
@KoenZomers 

I tried the same commands using the 1.8.25-nightly. 
I'm not able to reproduce the timezone mapping error anymore. 
FYI, the **object cycle** one still occurs but as I mentioned only the timezone mapping problem in the issue title, it can be considered as solved. 

Thank you.

**Comment by KoenZomers** [comment]
Thanks @adzero for confirming as well. Please open a new issue for the object cycle so we can have a look at that as well.
