### ISSUE TITLE
[BUG] Set-PnPWebPermission asking for Identity when its optional

### ISSUE THREAD

**Issue by Employee87** [pnp/powershell#1111]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
Should be able to modify permissions of the site without providing Identity param, in order to target current site

### Actual behavior 
It asks for Identity param.
Identity is optional (see docs here https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpwebpermission?view=sharepoint-ps)

### Steps to reproduce behavior
`Set-PnPWebPermission -Group "MyGroup" -AddRole Contribute`

Then it says

```
cmdlet Set-PnPWebPermission at command pipeline position 1
Supply values for the following parameters:
Identity:
```

### What is the version of the Cmdlet module you are running?
Manifest 1.7.0 PnP.PowerShell

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by Employee87** [comment]
The workaround is to provide the Identity with the GUID of the current site.

**Comment by gautamdsheth** [comment]
Thanks for reporting @Employee87 , have removed the Identity parameter as mandatory
