### ISSUE TITLE
Set-PnpListItemPermission - revoking unique access for external users after invite to tenant is accepted

### ISSUE THREAD

**Issue by rhyspmurphy** [pnp/powershell#1112]
### Reporting an Issue or Missing Feature
Using a csv and script to automate inviting guest users to a tenant, adding those users to a security group that is added to a SharePoint site collection visitors group for read access to site collection and then creating a folder for them in a document library that has unique permissions so that only the external user and site owners can view that folder. The script seems to assign permissions correctly but as soon as the invite is clicked by the external user permissions disappear from the folder. 

The following command is used to assign the permission of the external user to the folder:

Set-PnPListItemPermission -List $Library -Identity $listItem.Id -User $Email -AddRole 'Contribute'

### Actual behavior 
If I run the script the external user receives an invite to the tenant, gets added to the group and has the permissions set on the folder. Prior to accepting the invite as a site collection admin I can check the access of the folder and can see that it is correct with External User having access see below image:

<img width="161" alt="ManageAccessBeforeInviteAccepted" src="https://user-images.githubusercontent.com/67466680/133618215-d19d59d8-2bf9-42ee-85e6-3ca81d7e224d.PNG">

Once I click accept invitation to the tenant in the external users email the user can go to the site collection but cannot see the folder. When I go back in as an admin and check access on the folder the access for the external user has now gone:

<img width="168" alt="ManageAccessAfterInvite Accepted" src="https://user-images.githubusercontent.com/67466680/133618551-02c13c94-0930-46c0-9750-88ee3ea81cbb.PNG">

### Steps to reproduce behavior
Create an SP site collection. 
Add a security group to site collection visitors group. 
Create a folder in library and stop inheriting permissions and remove members and visitors for the folder
Send a tenant invite to a guest user
Add user to the security group that is part of the site collection visitor group in step 2

Run this command:
Set-PnPListItemPermission -List $Library -Identity $listItem.Id -User $Email -AddRole 'Contribute'

This should set permissions on the folder for the external user to access

If you check the permissions on that folder after running that command as a site admin you will see it says the external user has been given access.

If you then accept the invitation to the tenant as the external user and check the permissions again the access gets removed for the external user. 

It's worth noting that if you set the external access to the folder via sharepoint rather than this pnp command and then accept the invite to tenant the access stays as I would like it to

### What is the version of the Cmdlet module you are running?
1.7

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows

**Comment by veronicageek** [comment]
@rhyspmurphy - Can you update the module to the latest release (major `1.9.0` or nightly release) and feedback please.

**Comment by veronicageek** [comment]
Closing as no response.
