### ISSUE TITLE
ConvertTo-PnPPage incorrectly formatting pages with HTML tables

### ISSUE THREAD

**Issue by muratsoenmez** [pnp/powershell#1113]
### **Issue**
ConvertTo-PnPPage incorrectly formatting pages with HTML tables

### **Expected behavior**
Modern Pages created with the conversion of classic pages should have the correct content and structure as the classic pages.

### **Actual behavior**
Modern Pages have wrong design/formatting/content after the conversion.
Please see the reference to the discussion below 

### **Steps to reproduce behavior**
Create a classic page containing any HTML-Table with 6 columns, and insert text AND image content to table columns.

```

> <TABLE>
> <tr>
> 	<td>TEXT CONTENT 1</td>
> 	<td><img src="img1.jpg"/></td>
> 	<td><img src="img2.jpg"/></td>
> 	<td><img src="img3.jpg"/></td>
> 	<td><img src="img4.jpg"/></td>
> </tr>
> <tr>
> 	<td>TEXT CONTENT 2</td>
> 	<td><img src="img5.jpg"/></td>
> 	<td><img src="img6.jpg"/></td>
> 	<td><img src="img7.jpg"/></td>
> 	<td><img src="img8.jpg"/></td>
> </tr>
> <tr>
> 	<td>TEXT CONTENT 3</td>
> 	<td><img src="img9.jpg"/></td>
> 	<td><img src="img21.jpg"/></td>
> 	<td><img src="img31.jpg"/></td>
> 	<td><img src="img41.jpg"/></td>
> </tr>
> </TABLE>

```

Use ConvertTo-PnPPage method to convert page to modern.

`ConvertTo-PnPClientSidePage -Identity $sourcePageName -Library "Site Pages" -TargetWeb $targetSiteUrl -TargetPageFolder "/" -PublishingPage -LogVerbose -LogType File -CopyPageMetadata -KeepPageCreationModificationInformation -Overwrite -PageLayoutMapping "$($appRoot)\pagelayoutmapping.xml" -Connection $sourceConnection -TargetConnection $targetConnection -SkipHiddenWebParts -SkipTermStoreMapping -AddTableListImageAsImageWebPart -LogFolder "C:\temp\transformationlogs" -WarningAction Ignore`

Use attached pagelayoutmapping.xml. [pagelayoutmapping.txt](https://github.com/pnp/powershell/files/7226828/pagelayoutmapping.txt)

### **What is the version of the Cmdlet module you are running?**###
 1.5.0      

### **Which operating system/environment are you running PnP PowerShell on?**###
 **x** Windows

<div type='discussions-op-text'>

<sup>Originally posted by **Xileize** March 25, 2021</sup>
We are currently in the process of migrating some classic publishing pages from on-prem SP2013 into SPO and modernising them. A lot of these pages contain HTML tables, particularly HTML tables with images inside.

Whenever we try to use ConvertTo-PnPPage on these pages, they copy successfully, but there is no page content. However, if we convert them using a custom -PageLayoutMapping containing:

`<Field Name="PublishingPageImage" TargetWebPart="SharePointPnP.Modernization.WikiImagePart" Row="1" Column="1">
          <Property Name="ImageUrl" Type="string" Functions="ToImageUrl({PublishingPageImage})" />
          <Property Name="AlternativeText" Type="string" F
[pagelayoutmapping.txt](https://github.com/pnp/powershell/files/7226768/pagelayoutmapping.txt)
unctions="ToImageAltText({PublishingPageImage})" />
          <Property Name="Anchor" Type="string" Functions="ToImageAnchor({PublishingPageImage})" />
          <Property Name="Caption" Type="string" Functions="ToImageCaption({PublishingImageCaption})" />
        </Field>
        <Field Name="PublishingPageContent" TargetWebPart="SharePointPnP.Modernization.WikiTextPart" Row="3" Column="1">
          <Property Name="Text" Type="string" />
        </Field>` 

The page content copies over successfully, but with incorrect formatting. It bolds all text on the page, leaves broken URL references on the images within the page body to the PublishingImages folder on the target site (as those images haven't been converted over to the site), and then adds the images to the bottom of the page in a separate image web part rather than in the main content body.

I would be surprised if the conversion couldn't correctly handle HTML tables, so I can only assume that we are making incorrect use of the mapping files, but I'm not sure what we're doing wrong.

Any help would be greatly appreciated. </div>

**Comment by veronicageek** [comment]
@darthbazi - Appreciate you've created this issue from a Discussion, but please fill the _Issue Template_ below:


### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by darthbazi** [comment]
Thanks for the info, I have edited the post.

**Comment by veronicageek** [comment]
Thanks for that. 
First, can you update the module to the latest version and feedback please. Thanks.

**Comment by veronicageek** [comment]
Closing as no response.
