### ISSUE TITLE
Get-PnPListItem fails when authenticated using Windows Credentials

### ISSUE THREAD

**Issue by Gauzdx** [pnp/powershell#1117]
Reporting a weird behaviour when using the `Get-PnPListItem` cmdlet. I'd like to connect using the credentials so the script can be automated. Connecting using different methods can cause it to fail. 

**Steps to reproduce behavior**
When connecting to a SharePoint site using Windows Credential like below
`Connect-PnPOnline -Url $url -Credentials "SharePointAuth"` where SharePointAuth is a saved Windows Credential, the `Get-PnPListItem` would fail with the error:
`Get-PnPListItem : No list found with id, title or url 'ListName'` on the line: 
`$listItems = Get-PnPListItem -List ListName`

**Temporary fix**
The issue is fixed when I connect to the SharePoint site using the `-UseWeblogin` parameter instead of Windows Credentials

**What is the version of the Cmdlet module you are running?**
1.7.0

**Comment by Gauzdx** [comment]
Connecting using `-Interactive` too doesn't work and throws the same error.

**Comment by veronicageek** [comment]
@Gauzdx - Please DO NOT delete the template when creating an issue. It's there to be filled.

I have no issue using both methods (`-Credentials` from the Credential Manager, or `-Interactive`) 

![image](https://user-images.githubusercontent.com/25181757/133925442-dfeda395-8cb6-4849-a49b-06954df53626.png)

![image](https://user-images.githubusercontent.com/25181757/133925445-ad243cf2-88d7-4973-acd7-1a9f8cb95180.png)


Knowing the `Connect-PnPOnline` is used millions of times everyday and we haven't got any other reports, we can only assume your credentials are not correct. Please try again on another site or list (or another tenant if you can).
