### ISSUE TITLE
[BUG] Set-PnPListItem _sometimes_ chokes on field I don't try to set ("TriggerFlowInfo")

### ISSUE THREAD

**Issue by heinrich-ulbricht** [pnp/powershell#1118]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
I'm setting list item properties using `Set-PnPListItem`. I expect this command to _always_ work.

### Actual behavior 
I see the command fail sometimes. Running it multiple times it sometimes works and sometimes fails.

The error message I get is:

`Set-PnPListItem: Die Spalte 'TriggerFlowInfo' ist nicht vorhanden. Möglicherweise wurde sie von einem anderen Benutzer gelöscht.` which is `Set-PnPListItem: Column 'TriggerFlowInfo' does not exist. It may have been deleted by another user.`

Here is a screenshot of me running the command 9 times, with different results:
![image](https://user-images.githubusercontent.com/3469970/133747850-92b4f2e1-1cc4-49c2-b118-ef3c0db14b5d.png)

That is: success, success, success, fail, fail, fail, success, success, fail.

What the heck? And this column "TriggerFlowInfo" - Google has _no_ results for it. Is this new?

### Steps to reproduce behavior

My setup is as follows:

* create a Teams team
* in the default documents library of the connected SharePoint site:
* add a site content type that derives from "Folder", add some site fields (in my case that's `vdBeschreibung`)
* enable content types for the default document library and add the new folder content type
* create folders from this content type (inside of the "General" folder, if that matters)
* use `Set-PnPListItem` to set field values for this folder (multiple times)

Boom.

I checked the `General` folder - it indeed has a field called "TriggerFlowInfo". My folder does not. But this shouldn't matter.

(Note: I'm not sure if the `-ContentType` parameter is necessary. I tried with and without, in both cases the error occurs.)

### What is the version of the Cmdlet module you are running?

1.7.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [x] Azure Functions
- [ ] Other : please specify

Both on Windows an Azure the error happens.

**Comment by heinrich-ulbricht** [comment]
Using Fiddler to look at the traffic I see a difference. Here are one failed and one successful call:

![image](https://user-images.githubusercontent.com/3469970/133751693-eff41a1f-6787-4dd9-bfda-6ac617b8a712.png)

The failed one seems to try to retrieve all field values of an element:
![image](https://user-images.githubusercontent.com/3469970/133751899-0e668df8-f983-4eab-aef5-a00a4a44df5f.png)

My `vdBeschreibung` Field (from the Content Type) is there, but also the `TriggerFlowInfo` field:
![image](https://user-images.githubusercontent.com/3469970/133752077-ab396377-cf33-4b06-9d26-07fb8b4cae53.png)
So maybe it requests fields for my element that it got from the list/library but which are not included in my content type?


This is the error response:
![image](https://user-images.githubusercontent.com/3469970/133752188-74d4df08-bf93-43a3-b2af-9744b1f10ca8.png)
(TraceCorrelationId=cb50f09f-6085-3000-1bc9-5c8be0e71152)


The successful call also requests field values of items, but seems to not request the offending `TriggerFlowInfo` field.

Strange is that it sometimes works and sometimes not. A caching thing?

**Comment by heinrich-ulbricht** [comment]
My workaround for now looks like this:

```powershell
do {
    $pnpError = $null
    $null = Set-PnPListItem -List $siteDefaultDocLib -Identity $itemId -Values $itemMetadataForFolder -ContentType $ct -Connection $siteConnection -ErrorVariable pnpError
    Start-Sleep -Milliseconds 500
} while ($pnpError.Count)
```

😑

**Comment by gautamdsheth** [comment]
Hi @heinrich-ulbricht , is the issue still occurring ? Can you try with the latest 1.9.0 release and let us know ? 

AFAIK, we are not supposed to touch the document library connected to Teams. Doesn't mean we shouldn't 😜
This error definitely shouldn't occur and looks quite weird.
Also, as a workaround, can you try modifying it using the `-Batch` parameter ? Maybe CSOM is going crazy, but if you use Batch parameter , we make a REST call so there is a slightly different behavior.

**Comment by heinrich-ulbricht** [comment]
It's hard to reproduce reliably and occurs in a production script. I can add some logging and monitor the logs to see if it still happens.

**Comment by gautamdsheth** [comment]
@heinrich-ulbricht - Thanks, any chance you are able to reliably reproduce ? Also, did you try the other different approach that I mentioned in the above comment of using Batch parameter ?

**Comment by gautamdsheth** [comment]
Closing this due to lack of response , feel free to reopen it if the issue happens.
Also, where possible, please the latest 1.10 release which should contain the latest CSOM.
