### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bdani1** [pnp/powershell#113]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
Remove the specified Role

### Actual behavior 
Error message, saying: Object reference not set to an instance of an object.

### Steps to reproduce behavior
Set-PnPGroupPermissions -Identity 'My Site Members' -RemoveRole "Read"
(the key is to only use the parameter RemoveRole without AddRole)

### What is the version of the Cmdlet module you are running?
0.3.27

### Which operating system/environment are you running PnP PowerShell on?
Windows
![Capture](https://user-images.githubusercontent.com/77395745/104460768-cdc76780-55ae-11eb-907b-d3ffe44f8c86.PNG)

**Comment by erwinvanhunen** [comment]
Good catch!

**Comment by erwinvanhunen** [comment]
Fixed, merged. It will be available in the upcoming nightly release.
