### ISSUE TITLE
Microsoft365GroupsUtility.cs doesnt accept pnp icons

### ISSUE THREAD

**Issue by timtatam** [pnp/powershell#1155]
Hi guys,
it seems there is an issue with the https://github.com/pnp/powershell/blob/1.7.59-nightly/src/Commands/Utilities/Microsoft365GroupsUtility.cs class accepting pnp icons

Line 452 should be `case ".png":` instead `case "png":`

not sure if there is also an error in line 454
`contentType = "image/jpeg";`
this should be `contentType = "image/png";` or?

BR Timo

**Comment by gautamdsheth** [comment]
Fixed the issue, should be available in tomorrow's nightly.
Thanks for reporting !
