### ISSUE TITLE
[BUG] Register-PnpManagementShellAccess freezes for Sovereign cloud

### ISSUE THREAD

**Issue by NikCharlebois** [pnp/powershell#1180]
### Reporting an Issue or Missing Feature
Running the Register-PnPManagementShellAccess ccmdlet with the -AzureEnvironment param set to USGovernmentHigh freezes the PowerShell console.

### Expected behavior 
Prompt me to grant consent to my GCCH account.

### Actual behavior 
Freezes the PowerShell console and doesn't open any prompts.

### Steps to reproduce behavior
- Open a new PowerShell Console
- Run **Register-PnPManagementShellAccess -AzureEnvironment USGovernmentHigh**

### What is the version of the Cmdlet module you are running?
1.7.0

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by KoenZomers** [comment]
Looking into this

**Comment by KoenZomers** [comment]
Found the issue. Trying to fix it.

**Comment by KoenZomers** [comment]
Turns out to be quite difficult to fix this one. Will discuss it in our next team meeting how to deal with it.

**Comment by gautamdsheth** [comment]
@NikCharlebois - is the issue still there ? Can you update to the latest version, preferably the nightly build, try and let us know ? We did make some changes internally to the Authentication handling, maybe it fixes your issue ?

**Comment by NikCharlebois** [comment]
Sorry for the delay folks. Same behavior as before with 1.9.0

**Comment by desmay** [comment]
Any more updates on this issue, issue still present in 1.10.0

**Comment by johnweeding** [comment]
@NikCharlebois @KoenZomers  any progress on resolution of this bug? Still experiencing freezing behavior against GCCH environment.

**Comment by KoenZomers** [comment]
I've done an attempt to fix this issue. As I don't have a login account to a GCCH tenant, I could only get as far as the login dialog being shown. Can any of you try and see if the custom build in [this branch](https://github.com/KoenZomers/pnppowershellcore/tree/Issue1180) fixes your issue?

To test it, I ran:

`Register-PnPManagementShellAccess -AzureEnvironment USGovernmentHigh -TenantName "xxx.onmicrosoft.us"`

Which results in the login dialog being shown:

<img width="756" alt="image" src="https://user-images.githubusercontent.com/5940670/172966506-25b62ee5-8db8-418f-b06d-9fcaca516606.png">

**Comment by gautamdsheth** [comment]
@desmay - any update on this ? Were you able to test it , if so , could you share the results ?

**Comment by Brijeshoo7** [comment]
@NikCharlebois Maybe Nick can help better in my case ( this time I am working on Azure US Gov tenant for M365dsc). @gautamdsheth  thanks gautam will keep track here on the same.

**Comment by desmay** [comment]
Sorry it's been a while, lost access to GCCH tenant but I got it back now. I just test with 1.12.0 and get the following error after I type in credentials. I'm running the following: Register-PnPManagementShellAccess -AzureEnvironment USGovernmentHigh -TenantName "xxxx.onmicrosoft.us". 

Can we reopen this issue ?

<img width="753" alt="image" src="https://user-images.githubusercontent.com/43035577/205152482-989e380d-ea7f-43d0-87ac-025acb9d5666.png">
