### ISSUE TITLE
[BUG] Set-PnP Term command missing

### ISSUE THREAD

**Issue by knaveenstar** [pnp/powershell#1186]
### Reporting an Issue or Missing Feature
I am trying to update the Term value using the Set-Pnp Term command but it says the command is not recognized

### Expected behavior 
Should execute command

### Actual behavior 
![image](https://user-images.githubusercontent.com/30283702/135592483-9a66406e-24b2-45ea-8c40-0a548339244b.png)

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

### What is the version of the Cmdlet module you are running?
Name                          Version    
----                          -------    
SharePointPnPPowerShellOnline 3.29.2101.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
-

**Comment by veronicageek** [comment]
@knaveenstar - Just seen you're using `SharePointPnPPowerShellOnline 3.29.2101.0` which is the old module and not maintained anymore. Please install PnP.PowerShell (this repo) and try again.
