### ISSUE TITLE
Unable to add user to SharePoint Site security group when site name has special characters

### ISSUE THREAD

**Issue by mohammadamer** [pnp/powershell#1190]
### Expected behavior 
The expected behavior here is to execute Add-PnPGroupMember and get the member added to the SPO group but instead got error and when tried with a site which has no special characters it worked fine.

### Actual behavior 
Error:
Add-PnPGroupMember : Invalid request.

### Steps to reproduce behavior
A SharePoint Site that has a name with special characters EX: Økonomi

```
$site = "https://tenant.sharepoint.com/sites/Økonomi"
$client1 = "00000000-0000-0000-00000000"
$cert1 = "C:/Cert1.pfx"
$certPass1 = (ConvertTo-SecureString -String "Password1" -AsPlainText -Force)
Connect-PnPOnline  -Url $site -ClientId $client1 -CertificatePath $cert1 -CertificatePassword $certPass1 -Tenant "tenant.onmicrosoft.com"

$MembersGroup = Get-PnPGroup -AssociatedMemberGroup
Add-PnPGroupMember -LoginName "AD Group Title" -Identity $MembersGroup.Title

Error:
Add-PnPGroupMember : Invalid request.

Add-PnPGroupMember -LoginName "AD Group Title" -Identity  $MembersGroup.Id
Same error:
Add-PnPGroupMember : Invalid request.
```

### What is the version of the Cmdlet module you are running?
1.7.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows

**Comment by KoenZomers** [comment]
Diving into this.

**Comment by KoenZomers** [comment]
@mohammadamer How did you even manage to create a sitecollection with Økonomi in the URL? If I try it through the web UI it  will just take out that entire letter. If I try it using New-PnPSite it will normalize it to Okonomi instead.

**Comment by mohammadamer** [comment]
@KoenZomers I am using PnP Powershell and the site has been created with this title "ØkonomiOgFinansiering" and this name "ØkonomiOgFinansiering" :)

**Comment by KoenZomers** [comment]
I need more information to try to reproduce this. When I simply use `New-PnPSite` to try to create a site with this name, it normalizes it to a normal o:

![image](https://user-images.githubusercontent.com/5940670/135926841-ad37232e-41f3-421d-bb41-69abb377392e.png)

How exactly did you create a site where the Ø would be retained in the URL?

**Comment by mohammadamer** [comment]
@KoenZomers 
This is how we create site using PnP Powershell.
The only difference is that I am using a JSON file which contains every site Title, URL etc. Urls in my Json file has URL and title with these special characters as I explained.
 
I a for loop I am using the following line to create sites using the data in JSON file.
`New-PnPSite -Type $Site.SiteType -Title $Site.Title -Url $Site.URL -Owner $Site.SiteOwner`

**Comment by KoenZomers** [comment]
Which version of PnP PowerShell are you using? New-PnPSite does not have a -Url parameter. New-PnPTenantSite does, but that does not have a Type parameter. So I'm still confused :)

Can you share the output of:

`Get-InstalledModule PnP.PowerShell | Select Name, Version | FT`

**Comment by mohammadamer** [comment]
@KoenZomers, After you specify the type parameter, Url parameter will be present.

PnPPowershell Version
PnP.PowerShell 1.7.0

**Comment by gautamdsheth** [comment]
@mohammadamer - I think its a bug in SharePoint's side that you were able to create a site with a URL having special characters. As Koen mentioned, its not possible to create a site from UI with this URL. We added a fix in the site creation code to normalize these characters. 

Can you try with the latest nightly to create a new site and then add members ?
In any case, we are not going to be able to fix the issue because it is the server that is sending us this response.

**Comment by gautamdsheth** [comment]
Can you provide the minimal repro steps that you used for site creation ? Am not able to create sites with special chars, so I could be missing something. 

We are using the latest PnP version , so maybe you can try with that ?

**Comment by mohammadamer** [comment]
@gautamdsheth

Power shell for site creation:

![image](https://user-images.githubusercontent.com/19314043/139960904-523e8678-7f9a-48cd-9268-db6e1d6099b2.png)


Sites have been created:

![image](https://user-images.githubusercontent.com/19314043/139961097-be2c74c6-591f-45c9-843e-ea2e6ca65442.png)

**Comment by KoenZomers** [comment]
I can create a site with that character in the URL now using:

```
new-pnpsite -type TeamSite -title "ØkonomiOgFinansiering1" -Url https://tenant.sharepoint.com/sites/ØkonomiOgFinansiering1 -owner koen@tenant.onmicrosoft.com
```

When I then connect to that tenant and try to add a user to the group, it works without any problems:
<img width="977" alt="image" src="https://user-images.githubusercontent.com/5940670/212208684-1146c21f-b8c8-441f-96ab-6933cf7a0ef1.png">

Still must be missing something here, but no idea what.
