### ISSUE TITLE
[BUG] PreviewImageURL is not displaying when applying site template (Add-PnPSiteDesign or Set-PnPSiteDesign)

### ISSUE THREAD

**Issue by miguelisidoro** [pnp/powershell#1197]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue
    
### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

Hi,

I was able to successfully create a site design using the below script (using latest version of PnP.PowerShell).

$SharePointAdminURL = "https://mytenant-admin.sharepoint.com"
$ClientId = ""
$ClientSecret = ""
$SiteScriptTitle = "Project Site Template"
$SiteDesignTitle = "Project Site Template"
$SiteScriptDescription = "Site Template to use for project sites"
$SiteDesignDescription = "Site Template to use for project sites"
$CurrentPath = Get-Location
$PreviewImageURL = "https://mytenant.sharepoint.com/SiteAssets/SiteProjeto.png"
Write-Host "CurrentPath: $CurrentPath"
$SiteScriptPath = "$CurrentPath\SiteProjeto.json"
Write-Host "SiteScriptPath: $SiteScriptPath"
$SiteScripJsonContent = Get-Content $SiteScriptPath -Raw
Write-Host "SiteScripJsonContent: $SiteScripJsonContent"
Connect-PnPOnline -URL $SharePointAdminURL -ClientId $ClientId -ClientSecret $ClientSecret

$sitescript = Add-PnPSiteScript -Title $SiteScriptTitle -Description $SiteScriptDescription -Content $SiteScripJsonContent
Add-PnPSiteDesign -Title $SiteDesignTitle -SiteScriptIds $sitescript.Id -Description $SiteDesignDescription -WebTemplate TeamSite -PreviewImageURL $PreviewImageURL

The problem is that the my custom PreviewImage is not displayed, the default preview imagem is instead.

I tried to update the site design using the script below:

Set-PnPSiteDesign -Identity <sitedesignid> -PreviewImageURL "https://mytenant.sharepoint.com/SiteAssets/SiteProjeto.png" but also without success.

Can you please investigate?

Thanks
Miguel

**Comment by veronicageek** [comment]
@miguelisidoro - Please DO NOT delete the template when creating an issue. It's there to be filled.

> using latest version of PnP.PowerShell

Major or pre-release? Which number is it?
What other tests have you performed?

**Comment by KoenZomers** [comment]
I've used this myself a few weeks ago. It works, but I remember it requires a bit weird image URL path to be used. Let me see if I can figure it out again and document it better.

**Comment by KoenZomers** [comment]
Turns out you need to use `-ThumbnailUrl` instead of `-PreviewImageUrl` to have the image display in the new "Apply a site template" feature. The others were used by the old approach where you would select the template when creating the site. You use the full URL to the image you would like to use, like you already do, so that's correct. I'll update the documentation to reflect this.

**Comment by KoenZomers** [comment]
PR submitted with updated documentation. Updated documentation can be found here while it has not been merged yet: https://github.com/pnp/powershell/blob/61451826ebaaa40007a094cd47bae565bbb78fb0/documentation/Add-PnPSiteDesign.md . Assuming this will resolve the issue for you, I will proceed with closing this issue. In case it still does not work for you, feel free to reopen.

**Comment by miguelisidoro** [comment]
Hi,

According to https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpsitedesign?view=sharepoint-ps, there is no ThumbnailUrl parameter. I tried the parameter and the cmdlet throws an error saying parameter does not exist.

Are you refering to the SPO cmdlet? I would like to use the PnP version...

**Comment by KoenZomers** [comment]
Please try this using

**Comment by KoenZomers** [comment]
Please try this using the latest prerelease of PnP PowerShell by running `Install-Module PnP.Powershell -AllowPrerelease`.

**Comment by miguelisidoro** [comment]
I am getting an error when running 

Install-Module PnP.PowerShell -AllowPrerelease -Force

Install-Module : A parameter cannot be found that matches parameter name 'AllowPrerelease'.

How to solve this?

Thanks

**Comment by jimmywim** [comment]
Sounds like your `PowerShellGet` is out of date. Update it with:

```
Install-Module PowershellGet -Force
```

**Comment by miguelisidoro** [comment]
Yeap that did it.

Installed:

Install-Module -Name PackageManagement -Repository PSGallery -Force
Install-Module -Name PowerShellGet -Repository PSGallery -Force

Then restarted the shell and it worked.

Tks

**Comment by miguelisidoro** [comment]
Spoke too soon.

Getting the error when running

Install-Module PnP.PowerShell -AllowPrerelease -Force

PackageManagement\Install-Package : The version '1.7.68' of the module 'PnP.PowerShell' being installed is not catalog
signed. Ensure that the version '1.7.68' of the module 'PnP.PowerShell' has the catalog file 'PnP.PowerShell.cat' and
signed with the same publisher 'CN=Microsoft Corporation

**Comment by miguelisidoro** [comment]
Hi,

I was able to set the ThumbnailURL with image with size 400x301 with the latest version of PnP.PowerShell (Pre-release version).

But the PreviewImageURL (shown when you click on "Details" before applying site template) is not shown.

I am using an image with size 1161x1100.

$SharePointAdminURL = "https://mytenant-admin.sharepoint.com"
$ClientId = ""
$ClientSecret = ""
$SiteScriptTitle = "Project Site Template"
$SiteDesignTitle = "Project Site Template"
$SiteScriptDescription = "Site Template to use for project sites"
$SiteDesignDescription = "Site Template to use for project sites"
$CurrentPath = Get-Location
$PreviewImageURL = "https://mytenant.sharepoint.com/SiteAssets/ProjectSite.png"
$ThumbnailUrl = "https://mytenant.sharepoint.com/SiteAssets/ProjectSite_Thumb.png"
Write-Host "CurrentPath: $CurrentPath"
$SiteScriptPath = "$CurrentPath\SiteProjeto.json"
Write-Host "SiteScriptPath: $SiteScriptPath"
$SiteScripJsonContent = Get-Content $SiteScriptPath -Raw
Write-Host "SiteScripJsonContent: $SiteScripJsonContent"
Connect-PnPOnline -URL $SharePointAdminURL -ClientId $ClientId -ClientSecret $ClientSecret

$sitescript = Add-PnPSiteScript -Title $SiteScriptTitle -Description $SiteScriptDescription -Content $SiteScripJsonContent
Add-PnPSiteDesign -Title $SiteDesignTitle -SiteScriptIds $sitescript.Id -Description $SiteDesignDescription -WebTemplate TeamSite -PreviewImageURL $PreviewImageURL -ThumbnailUrl $ThumbnailUrl

Any recommendation?

Any

**Comment by KoenZomers** [comment]
Not sure what you mean to be honest, are you talking about the logo not showing up in the "Select a template" such as the Microsoft logo here in my case?

![image](https://user-images.githubusercontent.com/5940670/135873029-29e53113-aa85-442e-96a5-a692395d550b.png)

**Comment by miguelisidoro** [comment]
Hello @KoenZomers no.

The ThumbnailURL is displayed correctly.

![image](https://user-images.githubusercontent.com/5429152/135927901-8d0bfc7b-b132-49fb-8f5c-5bc2119b7fdb.png)

I was able to set it using the latest Prerelease version of he PnP.PowerShell module.

What is not working is the PreviewImageURL.

![image](https://user-images.githubusercontent.com/5429152/135928012-104476cf-1e74-46ec-b001-e29e5bfc32d7.png)

I am using version 1.7.64 of the PnP.PowerShell module.

Thanks
Miguel

**Comment by KoenZomers** [comment]
Interesting. I wonder if that even can be set. Could you try doing so using the SharePoint Online Management Module? If that works we can fix it in PnP as well, if it doesn't work through that either, its a server side issue which would require a support ticket with Microsoft

**Comment by KoenZomers** [comment]
@miguelisidoro Let me try and get a hold of the PM on this feature if it's even intended to have a picture show up at that place. I have my doubts. She did mention there's still quite a bit of work in progress on the site templates functionality and they are aware of known issues with it at the moment.
