### ISSUE TITLE
[BUG] Add-PnPSiteDesign error with WebTemplate GrouplessTeamSite

### ISSUE THREAD

**Issue by miguelisidoro** [pnp/powershell#1202]
### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

Hi,

I am using PnP.PowerShell and the cmdlet Add-PnPSiteDesign in the following way:

Add-PnPSiteDesign -Title $SiteDesignTitle -SiteScriptIds $sitescript.Id -Description $SiteDesignDescription **-WebTemplate GrouplessTeamSite** -PreviewImageURL $PreviewImageURL

The GrouplessTeamSite is not recognized and it throws an error saying:

Cannot bind parameter 'WebTemplate'. Cannot convert value "GrouplessTeamSite" to type
"PnP.PowerShell.Commands.Enums.SiteWebTemplate". Error: "Unable to match the identifier name GrouplessTeamSite to a
valid enumerator name

Reference doc I used:
https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpsitedesign?view=sharepoint-ps

At https://github.com/pnp/powershell/blob/dev/src/Commands/Enums/SiteWebTemplate.cs, we can see that the GrouplessTeamSite seems to really exist but still the error is thrown. 

What do you suggest to apply a site design to Team sites with no Office 365 Groups?

Please also take a look at the doc at https://github.com/pnp/powershell/blob/dev/documentation/Add-PnPSiteDesign.md which has some errors, mainly in the description of the parameters and specially in the "Accepted Values" section.

Thanks

**Comment by KoenZomers** [comment]
Works fine here. Not sure why it doesn't for you.

![image](https://user-images.githubusercontent.com/5940670/135775441-b0873291-7ee6-4b43-8c0b-89915d29e778.png)

I've been making quite a few changes to the site designs and scripts cmdlets tonight and filed them as PRs so someone else in the team can buddy check my changes. I'd recommend waiting for them to be merged and then trying again with the latest prerelease to see if the problem persists for you.

**Comment by miguelisidoro** [comment]
Hi,

Is this a new version of the PnP.PowerShell?
When will it be avaiable?

Thanks

**Comment by veronicageek** [comment]
@miguelisidoro - We have a major version (e.g.: `1.7.0`) and prereleases every nights (e.g.: `1.7.64`). So when a PR is merged, you need to wait the **day after** and update the module with `-AllowPrerelease` to test if the fix worked.

**Comment by KoenZomers** [comment]
@miguelisidoro Tomorrows build should contain most of the changes I've done around those cmdlet. Try it again tomorrow to get the latest prerelase please.

**Comment by miguelisidoro** [comment]
Ok with the latest Prerelease, it works thanks.
