### ISSUE TITLE
[BUG] Set-PnPListItem in batch mode sets different time than not using batching

### ISSUE THREAD

**Issue by marschallphilipp** [pnp/powershell#1211]
### Reporting an Issue or Missing Feature
Setting time value in batch mode leads to changed time

### Expected behavior 
Time value set on list item should be the same, not depending if using -Batch feature or not

### Actual behavior 
When setting a time value on Modified or Created column the value stored is depending on if -Batch feature is used or not.
When using the Set-PNPItem cmdlet only the time stored is correct (UTC time value is stored and the time zone converted value is shown in UI).
When using the -Batch parameter, the stored value seem to correspond to UTC minus TimeZone offset value. 
My time zone is "Berlin" and locale is Germany.

### Steps to reproduce behavior
```
$Values = @{
    "Modified" = $($targetItem.FieldValues.Modified.ToUniversalTime())
    "Created" = $($targetItem.FieldValues.Created.ToUniversalTime())
    "Author" = "author@domain.net"
    "Editor" = "editor@domain.net"
}
Set-PnPListItem -Identity $targetItem.ID -Values $Values -List $TargetLibrary
```
After this code the time is set correctly...

```
$NewBatch = New-PnPBatch
Set-PnPListItem -Identity $targetItem.ID -Values $Values -List $TargetLibrary -Batch $NewBatch -UpdateType UpdateOverwriteVersion
Invoke-PnPBatch -Batch $NewBatch -Details -StopOnException -Connection $TargetConnection
```
After this code the time is not correct...

### What is the version of the Cmdlet module you are running?
1.7 (Module installed in ISE)

### Which operating system/environment are you running PnP PowerShell on?
- [ x ] Windows 10
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
@marschallphilipp - can you please try again with the latest PnP PowerShell ? Preferably with the nightly build and let us know ? There were some improvements made to the date time handling which should help I hope :)

**Comment by gautamdsheth** [comment]
In the batch command, can you try it without `UpdateOverwriteVersion` and check  ?  Looks like this is by design
