### ISSUE TITLE
Issue with Set-PnPDefaultColumnValues and folders with special characters

### ISSUE THREAD

**Issue by eprach** [pnp/powershell#1214]
### Reporting an Issue or Missing Feature
Set default taxonomy value on a folder when its name contains accented characters (like "é", "è", "à", "'") not working

### Expected behavior
The default taxonomy value is set on the folder with or without accented characters.

### Actual behavior
When trying to set a default value for a taxonomy field on a folder with accented characters, nothing happens and no error message.

### Steps to reproduce behavior
`Connect-PnPOnline https://xxxxx.sharepoint.com/sites/site1/ -UseWebLogin
$defaultTermValue = "TermSet|TermGroup|Term" 
$DocumentListName = "MyDocLib" 
Set-PnPDefaultColumnValues -List $DocumentsListName -Field "MyTaxField" -Value $defaultTermValue -Folder "MyFolderWithAccentéé"`

Check default value and nothing as changed. No error message. It works well with folder name without accent.

I though this has been fixed in release 1.7.61 according to this [issue](https://github.com/pnp/powershell/issues/784). But it looks like it is not the case. I tested on 2 different machines, same result.

### What is the version of the Cmdlet module you are running?
1.7.68

### Which operating system/environment are you running PnP PowerShell on?
Windows 10

**Comment by gautamdsheth** [comment]
Can you check with the latest version ? It works at my end , maybe be I am missing something.

Followed that steps that you mentioned and also did `Get-PnPDefaultColumnValues` , it returns the correct data.

**Comment by gautamdsheth** [comment]
Closing this due to lack of response.
