### ISSUE TITLE
[BUG] The system cannot find the file specified

### ISSUE THREAD

**Issue by renatoromao** [pnp/powershell#122]
### Reporting an Issue or Missing Feature
Bug

### Expected behavior 
Connect-PnPOnline with Url, ClientId, Tenant, CertificateBase64Enconded, CertificatePassword and ReturnConnection works when we run the Azure Function (PowerShell Core 7.0).

### Actual behavior 
I am getting an exception error: The system cannot find the file specified.  Message : The system cannot find the file specified.
But If I restart the Azure function, works some minutes and after stop again.

### Steps to reproduce behavior
I reproduce the same as this post #80 said, we are working together on it. The unique difference that I did is the environment and also the -ReturnConnection property.

$conn = Connect-PnPOnline -Url "https://$SPO_TENANT.sharepoint.com$SiteUrl" -ClientId $AUTH_ID -Tenant "$SPO_TENANT.onmicrosoft.com" -CertificateBase64Encoded $CERTIFICATE_BASE64_ENCODED -CertificatePassword (ConvertTo-SecureString -AsPlainText $AUTH_SECRET -Force) -ReturnConnection;

### What is the version of the Cmdlet module you are running?
I already tried 0.3.26-nightly and 0.3.28-nightly.
'PnP.PowerShell' is the unique requirement of Azure Function.

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [x] Azure Functions
- [x] PowerShell Core 7.0
- [ ] Other : please specify

**Comment by renatoromao** [comment]
EXCEPTION: The system cannot find the file specified. Exception : Type : Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException TargetSite : Name : ProcessRecord DeclaringType : PnP.PowerShell.Commands.Base.ConnectOnline MemberType : Method Module : PnP.PowerShell.dll StackTrace : at PnP.PowerShell.Commands.Base.ConnectOnline.ProcessRecord() in D:\a\powershell\powershell\src\Commands\Base\ConnectOnline.cs:line 293 at System.Management.Automation.Cmdlet.DoProcessRecord() at System.Management.Automation.CommandProcessor.ProcessRecord() Message : The system cannot find the file specified. Data : System.Collections.ListDictionaryInternal Source : PnP.PowerShell HResult : -2147024894 CategoryInfo : NotSpecified: (:) [Connect-PnPOnline], WindowsCryptographicException FullyQualifiedErrorId : Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException,PnP.PowerShell.Commands.Base.ConnectOnline InvocationInfo : MyCommand : Connect-PnPOnline ScriptLineNumber : 32 OffsetInLine : 17 HistoryId : 1 ScriptName : C:\home\site\wwwroot\utils\connection.ps1 Line : Connect-PnPOnline -Url "https://$SPO_TENANT.sharepoint.com$SiteUrl" -ClientId $AUTH_ID -Tenant "$SPO_TENANT.onmicrosoft.com" -CertificateBase64Encoded $CERTIFICATE_BASE64_ENCODED -CertificatePassword (ConvertTo-SecureString -AsPlainText $AUTH_SECRET -Force); PositionMessage : At C:\home\site\wwwroot\utils\connection.ps1:32 char:17 + … Connect-PnPOnline -Url "https://$SPO_TENANT.sharepoint.co … + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ PSScriptRoot : C:\home\site\wwwroot\utils PSCommandPath : C:\home\site\wwwroot\utils\connection.ps1 InvocationName : Connect-PnPOnline CommandOrigin : Internal ScriptStackTrace : at ConnectSPOnline<Process>, C:\home\site\wwwroot\utils\connection.ps1: line 32 at <ScriptBlock>, C:\home\site\wwwroot\fxApprovalWorkflow\run.ps1: line 26 PipelineIterationInfo :

**Comment by erwinvanhunen** [comment]
Can you try uploading the certificate and not use the Base64 version but use the - Thumbprint parameter? We actually changed the Connect-PnPOnline cmdlet to not support the base64 encoded cert anymore (this will be out tomorrow) . See https://pnp.github.io/powershell/articles/AzureFunctions.html for info on how to use a pfx in a function.

SharePoint btw returns a file not found exception (confusingly enough) when it cannot find the site.

**Comment by renatoromao** [comment]
Hi @erwinvanhunen ,

Thanks for helping me! :)

Now, it's working using the 0.3.26 version and I added _WEBSITE_LOAD_USER_PROFILE=1_  setting to the Azure Function.
I saw this article: https://stackoverflow.com/questions/62787147/the-system-cannot-find-the-file-specified-azure-key-vault-certificat

Regarding your topic, can I continue using this version with a Certificate + Key Vault instead of updating my version to use thumbprint?
I already tried to use thumbprint, sometimes I can't connect to SharePoint site collection too.

**Comment by erwinvanhunen** [comment]
You can, as we just reintroduced the CertificateBase64Encoded parameter again on Connect-PnPOnline. It will be available in 0.3.38-nightly.

We support connecting using a certificate as either a file, or through the thumbprint option where it will access the certificate in the provided Certificate Management Store (which works in an Azure Function, but you have to do an extra configuration step in your function app, see [here for more info](https://pnp.github.io/powershell/articles/azurefunctions.html#decide-how-you-want-to-authenticate-in-your-powershell-function), or by using a base64 encoded certificate.

**Comment by joelfmrodrigues** [comment]
@erwinvanhunen sorry to comment on a closed issue, but your comments got me a bit confused on what to use.
I was using base64 and getting that from a certificate in KeyVault. Then switched to use thumbprint and a certificate on the function app as base64 was being removed. But as base64 was re-added, can I assume that there are no plans currently to drop that?
The base64 approach allows me to create a slightly better solution (in my opinion) as I have the certificate uploaded only to KeyVault, and we can specify a restrict access to the keyvault.

**Comment by erwinvanhunen** [comment]
You're right. We reintroduced the parameter as it turned out quite some people where using it in combination with the keyvault. It will be supported.

**Comment by joelfmrodrigues** [comment]
@erwinvanhunen Thank you for confirming!
@renatoromao we are safe to carry on :)
