### ISSUE TITLE
[BUG] Invoke-PnPSiteTemplate always applies template to rootsite

### ISSUE THREAD

**Issue by olemp** [pnp/powershell#1224]
### Reporting an Issue or Missing Feature
I'm reporting a bug/issue.

### Expected behavior 
When connected to contoso.sharepoint.com/sites/a/b I except my resources to be provisioned to that specific web when using `Invoke-PnPSiteTemplate`.

### Actual behavior 
The resources are provisioned to the root site, not the subsite I'm connected to.

### Steps to reproduce behavior
1. Connect to a subsite
2. Invoke a template using `Invoke-PnPSiteTemplate`

### What is the version of the Cmdlet module you are running?
1.7.71

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
Closing as no response.

**Comment by olemp** [comment]
> @olemp - No problem on my side with `1.8.14` (MacOS too but shouldn't make any difference)
> 
> Can you update the module, try on a different subsite (make sure you're connected to that subsite by run `Get-PnPList` after), or even try small pieces with handlers.

I backported to 1.7.0 and it worked. I was on the nightly prerelease.
