### ISSUE TITLE
[FEATURE] Connect-PnPOnline -ReturnConnection - Add Status Code

### ISSUE THREAD

**Issue by robertcaretta** [pnp/powershell#1233]
**Is your feature request related to a problem? Please describe.**
Must wrap connection with try catch to determine if the connection attempt is successful. 

**Describe the solution you'd like**
It would be helpful if this command would return a status code of 200, 404, etc.
$conn = Connect-PnPOnline -ReturnConnection

**Describe alternatives you've considered**
Yes, I wrap the Connect-PnPOnline command in a try catch block

**Additional context**
I can also pass invalid URLs to Connect-PnPOnline and it does NOT throw an error. It seems to connect like other valid URLs. Context checking is also invalid.

![2021-10-08_14-43-31](https://user-images.githubusercontent.com/1613085/136616983-281a8254-4962-412f-9843-a004eedc43f3.png)

![2021-10-08_14-45-08](https://user-images.githubusercontent.com/1613085/136616991-73c10ee9-eb6d-4173-99dd-9d96d73afaa3.png)

**Comment by KoenZomers** [comment]
Fair point. Indeed only when you actually start doing something after connecting, it would let you know the site does not exist. We'll discuss it in the team if we can and want to change this and if so how.

**Comment by gautamdsheth** [comment]
Closing due to lack of response. The feature has been implemented, please try with the latest code, it will work.
