### ISSUE TITLE
[BUG] Set-PnPPageTextPart Is causing updated text web parts to be collapsed/collapsible 

### ISSUE THREAD

**Issue by rmbw74** [pnp/powershell#1234]
### Reporting an Issue or Missing Feature
When updating a sharepoint online site page, using the Set-PnPPageTextPart cmdlt in an Azure function

### Expected behavior 
The text for the webpart should be updated without any unexpected changes to the section or text webpart itself

### Actual behavior 
The section the text web part is in becomes "Collapsible" and is collapsed when the page is opened. 
### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

```
Connect-PnPOnline -Url $siteUrl -ClientId $clientId -ClientSecret $clientSecret
$newPage = Get-PnPClientSidePage $targetLanguage/$pageName

$textControls = $newPage.Controls | Where-Object {$_.Type.Name -eq "PageText"}
foreach ($textControl in $textControls)
{
    Set-PnPPageTextPart -Page $newPage -InstanceId $textControl.InstanceId -Text "Updated Text shouldnt be collapsed" 
}

```
### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
Not sure how to retrieve this with an Azure Function. The function is using 1.* of pnp poweshell 
### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [X] Azure Functions
- [ ] Other : please specify
![2021-10-08 16_18_24-Window](https://user-images.githubusercontent.com/15833201/136625870-f7b4f9a0-4774-4071-a305-f66458b22487.png)
![2021-10-08 16_14_52-Window](https://user-images.githubusercontent.com/15833201/136625877-9daad9d3-2b5e-4642-bb61-e0c0fc568875.png)

**Comment by veronicageek** [comment]
Reproduced (without Azure Functions) on `1.8.2`.

**Comment by himani-chi** [comment]
Hello. Is there any update on this issue?

**Comment by rmbw74** [comment]
@himani-chi not that I'm aware of, I basically forced the use of the previous version of PnP as a workaround.

**Comment by jansenbe** [comment]
@rmbw74 / @himani-chi  / @veronicageek : this should be fixed in the next nightly build

**Comment by gautamdsheth** [comment]
Closing the issue as it has been fixed , please update to the latest nightly builds.
