### ISSUE TITLE
[BUG]Connect-PnPOnline has a memory leak

### ISSUE THREAD

**Issue by Ambergahill** [pnp/powershell#1247]
### Expected behavior 
I should be able to run Connect-PnPOnline thousands of times in a row for different SPO URLs without a System.OutOfMemoryException.

### Actual behavior 
After about 900 to 1,000 times of calling Connect-PnPOnline, I get a System.OutOfMemoryException.

### Steps to reproduce behavior
-Create a loop that iterates through 1,000+ valid SPO URLs. (You may be able to cycle through repeat URLs if you don't have 1,000)
-Connect-PnpOnline to each one of the URLs. For me, I am using certificatePath -ClientId -CertificatePassword along with -Tenant and -Url properties.
-Your loop doesn't have to do anything else, but connect. I also tried using Disconnect-PnPOnline afterwards with no luck. Based off of this article (https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/disconnect-pnponline?view=sharepoint-ps), that shouldn't be needed anyway.

### What is the version of the Cmdlet module you are running?
1.7.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [X] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Hi @Ambergahill - can you please try with the latest PnP PowerShell 1.8.0 ? There were some auth related changes , maybe it can help you.

**Comment by veronicageek** [comment]
@Ambergahill - Please try with the latest version `1.9.0` and reopen if the issue persists.

**Comment by gbordier** [comment]
I'm still seing this with pnp version 1.9.0  running standard mcr powershell linux container  (psh v7.2.1  / Linux 5.4.81-microsoft-standard #1 SMP )  looping through sharepoint sites only using connect-pnponline with a certificate as credential.

**Comment by Ambergahill** [comment]
Thank you @gbordier. I am also still seeing the issue in 1.9.0. @veronicageek , please reopen the the issue.

**Comment by gbordier** [comment]
simple repro without even changing the URL (**does not repro on windows**)

$cert=@"
MIIJ ------ Base64 encoded Pfx Content Here -------- EtNO
"@


$tenant="xxxx"
$AppID="AppID for AAD app with PNP rigts"

new-object System.Security.Cryptography.X509Certificates.X509Certificate2 -ArgumentList @([System.Convert]::FromBase64String( $cert),"")

for($i=0;$i -lt 100000 ; $i++) {
Connect-PnPOnline -Url "https://$tenant-admin.sharepoint.com"  -CertificateBase64Encoded $s -ClientId $AppID -Tenant $tenant.onmicrosoft.com
if ($i % 1000 -eq 0) {
write-host $i
}
}

**Comment by gbordier** [comment]
Looks like the issue might be in the Authentication Manager . I get the same mem usage and eventually OOM (especially VIRT growing up to 64GB) I have repro this with certificate, secret and accesstoken . I have dumps to share if usefull

**Comment by gbordier** [comment]
looks like I can narrow this down to the Telemetry part. 
 Telemetry does not get disabled only with PNPPOWERSHELL_DISABLETELEMETRY=true because of a logic bug in InitializeTelemetry (we need the .pnppowershelltelemetry in the users home folder present and empty  to really disable telemetry)
I'll be submiting a PR for this.

the leak seems to be in the Telemetry activation code I'll try to narrow it further down.

**Comment by gbordier** [comment]
@veronicageek  can someone have a look on the InitializeTelemetry method, should the ApplicationInsights member be static to avoid creating one for each connect-pnponline command issued ?

**Comment by veronicageek** [comment]
I'll tag @gautamdsheth and @KoenZomers if they have any insights

**Comment by gbordier** [comment]
> 

it looks like it is a known issue with TelemetryClient that it should be implemented as a singleton, but I would welcome insights before submitting such a change : ) ref : https://briancaos.wordpress.com/2020/05/07/c-azure-telemetryclient-will-leak-memory-if-not-implemented-as-a-singleton/

**Comment by gautamdsheth** [comment]
@gbordier  - thanks for looking into this. Looks like you are right, could you please submit a PR, we can check the implementation, much appreciated :)

**Comment by gautamdsheth** [comment]
Closing this issue as the PR has been merged.  You can get it via the latest nightly builds.
Feel free to submit a separate PR to improve the app insights TelemetryClient. 
Thanks again @gbordier   for investigation and submitting the PR, much appreciated 🙏😊

**Comment by gbordier** [comment]
the merged PR was about help disabling telemetry with the env variable but not implementing the singleton pattern for TelemetryClient I believe. I would keep this one open for now.

**Comment by gautamdsheth** [comment]
Yeah go ahead

**Comment by KoenZomers** [comment]
Sure, go for it. Please ensure that your dev fork is up to date with our dev fork as I submitted changes to that same code yesterday. Otherwise we might end in in a code merge disaster.
