### ISSUE TITLE
[BUG] Copy-PnPItemProxy

### ISSUE THREAD

**Issue by gpdhillon** [pnp/powershell#1257]
### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
1.8.0

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Azure Automation Accounts

- [ ] Other : please specify

This code works fine with version 1.7.0 but started throwing an error below with 1.8.0

Error Details

Copy-Item : The term 'Copy-PnPItemProxy' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At line:32 char:1 + Copy-Item -Path "spo:.\DropOffLibrary\$($dropOffSubFolderName)" -Dest ... + ~~~~~~~~~ + CategoryInfo : ObjectNotFound: (Copy-PnPItemProxy:String) [], CommandNotFoundException + FullyQualifiedErrorId : CommandNotFoundException

**Comment by veronicageek** [comment]
Same as issue #915

**Comment by gautamdsheth** [comment]
hi @gpdhillon , have added a fix for this issue.
It will be available in tomorrow's nightly.
Thanks for raising this issue !
