### ISSUE TITLE
[BUG] Connect-PnPOnline : The underlying connection was closed: An unexpected error occurred on a send.

### ISSUE THREAD

**Issue by tristian2** [pnp/powershell#1261]
### Reporting an Issue or Missing Feature
Connect-PnPOnline : The underlying connection was closed: An unexpected error occurred on a send.

This is on some code that has been working fine.  I must admin I am running huge tasks on a tenancy so perhaps throttling is taking place?

### Expected behavior 
a connection to my tenancy

### Actual behavior 
`Get-PnPHubSiteChild : The underlying connection was closed: An unexpected error `occurred on a send.
`At C:\checkhub.ps1:xxx char:1
`+ Get-PnPHubSiteChild -Identity $siteCollection -Connection $conn
`+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`   + CategoryInfo          : WriteError: (:) [Get-PnPHubSiteChild], WebException
`    + FullyQualifiedErrorId : `EXCEPTION,SharePointPnP.PowerShell.Commands.Admin.GetHubSiteChild
`Get-PnPHubSite : The underlying connection was closed: An unexpected error occurred `on a send.
`At C:\checkhub.ps1:xxx char:1
`+ Get-PnPHubSite -Identity $siteCollection
`

### What is the version of the Cmdlet module you are running?

ModuleType Version    Name                                                                                                          
---------- -------    ----                                                                                                              
Manifest   1.6.0      PnP.PowerShell               
Manifest   1.5.0      PnP.PowerShell 

- [* ] Windows
- [ ] Linux
- [ *] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
Closing as no response.
