### ISSUE TITLE
[BUG] Release notes generation seems to be brokem

### ISSUE THREAD

**Issue by kilasuit** [pnp/powershell#1298]
### Reporting an Issue or Missing Feature
Missing items in 1.8.0 release notes

### Actual behavior 
1.8.0 contains the following PR #1122 but this is not included at all in the [release notes](https://github.com/pnp/powershell/releases/tag/v1.8.0) but is included in the list of commits pulled in the PR #1232 that makes up the release.

### Expected behavior 
Release notes should show info on all PRs merged in as part of that release
Also it would be incredibly useful to add a bot that updates the PR's when they have been added to a release like you can see in this PR - https://github.com/PowerShell/PowerShell/pull/16198#issuecomment-949017318 as this makes it so much easier to track if a code change has made it into a release than reading back from the release notes.

**Comment by KoenZomers** [comment]
Fair point @kilasuit. I've added it to our list to discuss during one of our next team meetings how to deal with this.

**Comment by gautamdsheth** [comment]
Hi @kilasuit , thank you for the feedback.
We have started adding PR information in our changelogs from 1.10 onwards.
So, am closing this enhancement request.
