### ISSUE TITLE
[FEATURE] Get-PnPTeamsTeam Filter Parameter

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#1301]
**Is your feature request related to a problem? Please describe.**
This is a feature requrest

**Describe the solution you'd like**
It would be awesome to have an ability to run something like ```Get-PnPTeamsTeam -Filter "Name -like ""*Team*"""``` pretty much the same you can do with [```Get-ADUser```](https://docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=windowsserver2019-ps#example-2--get-a-filtered-list-of-users) or [```Get-ADGroup```](https://docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=windowsserver2019-ps#example-3--get-a-group-and-filter-the-results)

**Describe alternatives you've considered**
In case of relatively small number of objects the one might want to get all objects first and then filter the list with ```Where-Object```
```
$teams = Get-PnPTeamsTeam
$teams | where { $_.Name -match "Team" }
```
However, on the large amount of items PnP would throw an error:
![image](https://user-images.githubusercontent.com/5260172/138947401-828aa2c0-620c-420f-95da-6516b1d1d812.png)

**Additional context**
```
Name              : PnP.PowerShell
Path              : C:\Program Files\PowerShell\Modules\PnP.PowerShell\1.8.18\PnP.PowerShell.psd1
Description       : Microsoft 365 Patterns and Practices PowerShell Cmdlets
ModuleType        : Manifest
Version           : 1.8.18
PreRelease        : nightly
NestedModules     : {PnP.PowerShell}
ExportedFunctions : 
ExportedCmdlets   : {Add-PnPAlert, Add-PnPApp, Add-PnPApplicationCustomizer, Add-PnPAzureADGroupMember…}
ExportedVariables : WebRequestCounter
ExportedAliases   : {Add-PnPClientSidePageSection, Add-PnPClientSideText, Add-PnPClientSideWebPart, Export-PnPClientSidePage…}

```

**Comment by gautamdsheth** [comment]
Closing this as it has been fixed by #2467.

This cmdlet uses Graph API underneath, so you can set the filter conditions as mentioned here:

https://learn.microsoft.com/en-us/graph/aad-advanced-queries?tabs=http#group-properties
