### ISSUE TITLE
PNP template -ClientSidePage actions not deploying with Azure Automation Runbook

### ISSUE THREAD

**Issue by Bart2s4** [pnp/powershell#1305]
I have since 2 weeks a strange issue, where a template which was deployed without any issues, suddenly is generating the following error:

**Method not found: 'System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1<Boolean> Enumerator.MoveNextAsync()'.**

However when i try to simulate the issue on my windows powershell environment i cannot replicate the problem.

It is very simple to test:

Create a template locally and modify the home.aspx with webparts

use connect-PnPonline to connect to your template.
use Get-PnPSiteTemplate -Out <yourtemplatename>.pnp -IncludeSiteGroups -PersistBrandingFiles -Force

After generating upload the file to azure storage

Next  create a runbook and use PnP.Powershell 1.7.0 ( i know there is a new version, but this version 1.7.0 worked before without issues.

Execute the script in the testpane:

Invoke-PnPSiteTemplate -Path $templatePath -ClearNavigation
 where $templatePath is the location of the generated PNP template. 

I then have the error mentioned above

I cannot figure out why this is only happening in the azure runbook and not in my test environment locally.

**Comment by 2source4-DevAdmin** [comment]
@veronicageek i did not delete any template, i was browsing github and wanted to comment on an issue, but could then also make a new issue. If you want me to  create the issue, according to the template, then it is fine to recreate the issue, but since 21 days no one repsonded, i guess the problem is not that urgent. Yet Microsoft suggest me to report it in Github, which i did.

**Comment by veronicageek** [comment]
@Bart2s4 
> since 21 days no one repsonded, i guess the problem is not that urgent.

This is a community driven repo, meaning we also have day jobs and we do this on our personal time. We aim to work on issues as soon as we can but there's no SLA.

> Yet Microsoft suggest me to report it in Github

Yes because PnP.PowerShell is not a repo managed by Microsoft, but by the Community.

**Comment by veronicageek** [comment]
@Bart2s4 - Can you try with the latest version `1.9.0`, and also without the Runbook (with the same `1.9.0`) and feedback please.

**Comment by veronicageek** [comment]
Closing as no response.
