### ISSUE TITLE
[BUG] PnPConnection.Context.ClientTag does not accept AppName exceeding certain string length

### ISSUE THREAD

**Issue by sathya-bhat** [pnp/powershell#1313]
### Reporting an Issue or Missing Feature
PnPConnection.Context.ClientTag does not accept AppName greater than certain(?) length.

### Expected behavior 
PnPConnection.Context.ClientTag should accept AppName length upto what may be specified on Azure portal. The format of Client tag is specified as UserAgent in

https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online#how-to-decorate-your-http-traffic-to-avoid-throttling

### Actual behavior 
Exception setting "ClientTag": "Specified argument was out of the range of valid values.

### Steps to reproduce behavior

```
$conn = Connect-PnpOnline -url 'https://<etnant>-admin.sharepoint.com' -ClientId <appid> -ClientSecret <appsecret> -ReturnConnection

$AppUserAgent = 'ISV|MyCompany|MyCompanySharepointOnlineDataApplication/1.0'
$conn.Context.ClientTag= $AppUserAgent # FAILS

Exception setting "ClientTag": "Specified argument was out of the range of valid values.
Parameter name: value"
At line:1 char:1
+ $conn.Context.ClientTag= $AppUserAgent # FAILS
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting

$AppUserAgent = 'ISV|MyCompany|PnPCmdlet/1.0'
$conn.Context.ClientTag= $AppUserAgent # SUCCEEDS

$AppUserAgent = 'ISV|MyCompany|PnPCmdlet Test/1.0'
$conn.Context.ClientTag= $AppUserAgent # SUCCEEDS
```

### What is the version of the Cmdlet module you are running?
1.7.0

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [x ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
The maximum supported length for ClientTag is 32 characters. So, would suggest that you trim the char length to 32 characters or less.

Unfortunately, we can't do anything about this because you are directly manipulating the ClientContext object from CSOM, so it will require you to trim the char length in your code. PnP internally handles this, so it doesn't throw error.
