### ISSUE TITLE
[BUG] - Delete items using batch parameter

### ISSUE THREAD

**Issue by a1mery** [pnp/powershell#1320]
### Reporting an Issue or Missing Feature
Issue when deleting list items using batch parameter

### Expected behavior 
It is possible to delete multiple list items using batch parameter

### Actual behavior 
When trying to use the batch parameter to delete multiple items the script throws the following error : 
`An item with the same key has already been added.`

### Steps to reproduce behavior
```
$itemsToDelete = Get-PnPListItem -List $targetList
$deletingBatch = New-PnPBatch
$itemsToDelete | ForEach-Object{Remove-PnPListItem -List $targetList -Identity $_.Id -Batch $deletingBatch}
Invoke-PnPBatch -Batch $deletingBatch
```

### What is the version of the Cmdlet module you are running?
1.8.25-nightly

The script works fine with the 1.8.0 version

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [x] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@a1mery 

> The script works fine with the 1.8.0 version

Does it work fine on its own (without Azure Functions) with `1.8.25`?
Or was it working fine with the Azure Function using `1.8.0` and now you get the error with Azure functions only?

**Comment by a1mery** [comment]
I have the same error when running the script on its own.
The error occurs when running the last cmdlet : `Invoke-PnPBatch -Batch $deletingBatch`

**Comment by gautamdsheth** [comment]
Hey @a1mery - can you give it a try with the latest nightly build ? 

Looks like we managed to fix it:

![image](https://user-images.githubusercontent.com/8832018/146558271-00992e1e-04d4-4861-82f8-1bb781c2b9af.png)

**Comment by gautamdsheth** [comment]
Hi @a1mery , closing this issue. We have surely fixed it, can confirm :) 
Please feel free to reopen it if it happens with the latest version :)

**Comment by a1mery** [comment]
Sorry for the delayed answer.
I have tried with the latest version and its works fine ! Thank you very much :)
