### ISSUE TITLE
[BUG] Set-PnPSearchConfiguration Error 'Bad request while trying to reach endpoint POST Call to Setting Type Bulk'

### ISSUE THREAD

**Issue by Laetterman** [pnp/powershell#1328]
Hi

Today I had to re-use a script in which also Search Configurations are uploaded to Tenant or Site level. 2 weeks ago the script ran fine and today I have the error below... (nothing changed onb Script side :-()

Did MS changed the API (PnPPowershell has to be updaded) or is that a bug on MS side?
(i have tested with 1.8.0 and 1.8.31 nightly build)

Regards and thanks for your help
Marc

### Expected behavior 
Upload of Search Configuration to Tenant or Site level. 

### Actual behavior 
Endpoint error
![image](https://user-images.githubusercontent.com/38464361/140768868-606ac82e-8a8b-4d2c-b853-d398cc9590fc.png)

### Steps to reproduce behavior
Info: worked 2 weeks ago. Nothing changed in the config file (xml).

$searchConfiguration = Get-Content -Path "./assets/configs/MOBI_Cloud_Rednet_SearchConfig.TENNANTLEVEL.xml" -Raw
Set-PnPSearchConfiguration -Configuration $searchConfiguration -Scope Subscription

### What is the version of the Cmdlet module you are running?
tested on 1.8.0 and 1.8.31 nightly build

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows

**Comment by gautamdsheth** [comment]
@Laetterman - is the issue still occurring ? 
Looks like we can't do anything here if it suddenly stopped working. We haven't updated anything in the cmdlet.
Maybe an issue on Microsoft's end ??

**Comment by roberAlb** [comment]
Happening for us in one tenant as well, tested with PnP PowerShell 1.7.58 and PnP Framework 1.7.74. It's strange that it's not happening as the same way in all tenants.

**Comment by Laetterman** [comment]
Hi @gautamdsheth @roberAlb 

It looks like it is an Issue on MS side for some tenants. They seem to have changed something on the search settings schema / xml. We have it on one of 4 tenants. 
There I have exported the search settings and compared with ones from other tenants and noticed that some GUID and schema IDs are 00000-000000-000000-00000 (or similar :-)) or 0. After manipulating the XML specifically for that single tenant I have a workarond now...

**Comment by gautamdsheth** [comment]
Hi @wobba , maybe you know something about this ?
Please let us know if we need to change anything in the PnP cmdlets, happy to help and work on it !

**Comment by wobba** [comment]
1. Can you try to try upload the same xml via SharePoint UX?
2. If it fails in the UX -and I assume it should, file a support case

And I have suspicions why it fails, but it shouldn't really. And yes, changing the guid will resolve it.

One question, are you trying to upload the xml as before, or are you also fetching a new XML which you then try to upload? To compare if the new XML differs from the old.

**Comment by gautamdsheth** [comment]
Thanks @wobba for the response..
@Laetterman - as Mikael mentioned, please raise the issue with Microsoft support if the issue happens using the UI as well.
