### ISSUE TITLE
[BUG] Stuck on connecting to pnponline when clicking form button

### ISSUE THREAD

**Issue by fug4zi** [pnp/powershell#1329]
I try to connect to pnponline after i click a button in the form, but the form is freezing when it's connecting to pnponline.

### Expected behavior 
"Before Connect" is written in the console. 
Connecting to pnponline
"After Connect" is written in the console.
The form will be closed.

### Actual behavior 
"Before Connect" is written in the console. 
The form window is freezing.
Nothing happens anymore

### Steps to reproduce behavior
```
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

$form = New-Object System.Windows.Forms.Form
$form.AutoSize = $true

$btn = New-Object System.Windows.Forms.Button
$btn.Location = New-Object System.Drawing.Point(10,10)
$btn.Size = New-Object System.Drawing.Size(200,30)
$btn.Text = "Push me"
$btn.Add_Click({
    Write-Host "Before Connect"
    Connect-PnPOnline -Url "https://xx.sharepoint.com/xxx" -UseWebLogin
    Write-Host "After Connect"
    $form.Close()
})
$form.Controls.Add($btn)

$form.ShowDialog()
$form.Dispose()
pause
```

### What is the version of the Cmdlet module you are running?
PnP.PowerShell v1.8.0              

### Which operating system/environment are you running PnP PowerShell on?
- [ x ] Windows

**Comment by veronicageek** [comment]
@fug4zi - Closing as this isn't related to PnP PowerShell. `Connect-PnPOnline` works fine and we can't manage other dependencies.

**Comment by mikenikitin** [comment]
Any info on what this issue is actually related to? I am having the same issue and not quite sure what to do. Thanks!

**Comment by EngieNathan** [comment]
This should not be closed in my opinion. I am struggling with the same issue. Is there some kind of conflict between the Windows Forms Object and the PNPOnline Object?

**Comment by HiroshiIseki** [comment]
I'm having the same issue. but with version 3.23.2007.1 of SharePointPnPPowerShellOnline this does not happen.
