### ISSUE TITLE
[BUG] Looking for Microsoft.SharePoint.PowerShell does not exists. Can you use Microsoft.Online.SharePoint.PowerShell?

### ISSUE THREAD

**Issue by DECBuzz** [pnp/powershell#1341]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets
Connect to SharePoint Online

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.
Error looking for Microsoft.SharePoint.PowerShell that does not exist on my system and cannot find in PSGallery

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)
Connect-PnPonline $_.url

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
1.8

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@DECBuzz - I don't understand what your issue is? `Connect-PnPOnline` works fine.

**Comment by DECBuzz** [comment]
When I use:

PS C:\WINDOWS\system32> Install-Module Microsoft.SharePoint.PowerShell
PackageManagement\Install-Package : No match was found for the specified search criteria and module name
'Microsoft.SharePoint.PowerShell'. Try Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

You may have it on your system already. I only found Microsoft.Online.SharePoint.PowerShell.

Regards,

Danny Causey

**Comment by veronicageek** [comment]
You are trying to install the SharePoint Management Shell (from Microsoft), not the PnP.PowerShell module (this repo).
If you want to install the PnP PowerShell module, please refer to our [documentation](https://pnp.github.io/powershell/articles/installation.html).

To install the **SharePoint Management Shell**, it's in the PSGallery: https://www.powershellgallery.com/packages/Microsoft.Online.SharePoint.PowerShell/16.0.21811.12000,

Or use `Install-Module -Name Microsoft.Online.SharePoint.PowerShell`

Closing as there no issue.
