### ISSUE TITLE
[BUG] - Can you update the current release of PNP for Sync-PnPSharePointUserProfilesFromAzureActiveDirectory 

### ISSUE THREAD

**Issue by tig3r57** [pnp/powershell#1342]
Hello,

An issue has been solved regarding the command Sync-PnPSharePointUserProfilesFromAzureActiveDirectory on the version 1.8.8 and we strongly need to have this command updated on the current release of PNP.Powershell.

Thank you in advance,

Best regards,

**Comment by gautamdsheth** [comment]
Hello,
Cant you use the nightly builds ?

**Comment by gautamdsheth** [comment]
We currently have no release plans at the moment.
Please use the nightly builds.
