### ISSUE TITLE
[BUG] Set-PnPSite -DisableCompanyWideSharingLinks "Value" does not work independently

### ISSUE THREAD

**Issue by carlgrzywacz** [pnp/powershell#1343]
### Reporting an Issue or Missing Feature
Running the following cmdlets does not update the DisableCompanyWideSharingLinks property for a given site
Set-PnPSite -DisableCompanyWideSharingLinks "NotDisabled"
Set-PnPSite -DisableCompanyWideSharingLinks "Disabled"

### Expected behavior 
The DisableCompanyWideSharingLinks property should be updated to the specified value.

### Actual behavior 
The cmdlet executes immediately and nothing happens.

### Steps to reproduce behavior
Connect-PnPOnline -URL $SiteURL -Interactive
Get-PnPSite -Includes DisableCompanyWideSharingLinks | Select DisableCompanyWideSharingLinks
Set-PnPSite -DisableCompanyWideSharingLinks "NotDisabled";
Get-PnPSite -Includes DisableCompanyWideSharingLinks | Select DisableCompanyWideSharingLinks

### What is the version of the Cmdlet module you are running?
1.8.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows

### Workaround:
Interestingly, i found that setting a second property like DisableFlows will set both properties, even if the value of DisableFlows doesn't change.
Get-PnPSite -Includes DisableCompanyWideSharingLinks, DisableFlows |Select DisableCompanyWideSharingLinks, DisableFlows 
Set-PnPSite -DisableCompanyWideSharingLinks "NotDisabled" -DisableFlows $true
Get-PnPSite -Includes DisableCompanyWideSharingLinks, DisableFlows |Select DisableCompanyWideSharingLinks, DisableFlows 

![image](https://user-images.githubusercontent.com/6900913/141483455-4c18a3d8-29f9-42a8-9ca6-b340383f57aa.png)

**Comment by gautamdsheth** [comment]
Hi @carlgrzywacz , have merged a PR that fixes this. 
It will be available from tomorrow's nightly builds. You can use it using the `Install-Module PnP.PowerShell -AllowPrerelease` command.
Thanks for opening the issue :)
