### ISSUE TITLE
[FEATURE] Get child term at all levels in Taxonomy Term store

### ISSUE THREAD

**Issue by dhiabedoui** [pnp/powershell#1354]
**Is your feature request related to a problem? Please describe.**
Get-Term works only till the first term (level 1), this require a change to the cmdlet 

Exemple :
Store : 
- Group
--Termset
---Level1_Term
-----Level2_Term

Get-PnPTerm -Identity Level1_Term -TermSet $termSetFonc.Name -TermGroup $group -> Works
Get-PnPTerm -Identity Level2_Term -TermSet $termSetFonc.Name -TermGroup $group -> Don't Works

**Solution :**
This request to update actual behaivor of Get-PnPTerm so it returns term at any level

**Alternatives :**

There is a workaround of this problem by using the parent item's context but it's not optimal :

$ParentTerm=Get-PnPTerm -Identity $ParentName -TermSet $termSet -TermGroup $group
$ctx = $ParentTerm.Context  
$ctx.Load($ParentTerm.Terms)
$ctx.ExecuteQuery()
Then filter on parent's terms : $TermLevel2 =$ParentTerm.Terms | Where-Object Name -eq $TermName

To get a level 3 term we should reproduce the same process.

**Comment by gautamdsheth** [comment]
Hi, we have added a new parameter `-IncludeChildTerms` , this will retrieve the child terms from all levels.

**Comment by vojtahanzal** [comment]
@gautamdsheth  Great. Thanks! 
Even the -IncludeChildTerms parameter does not work at all. 
It does NOT return any data :(
