### ISSUE TITLE
[BUG] Remove-PnpFile does not support -WhatIf parameter as stated in documentation

### ISSUE THREAD

**Issue by bsimser** [pnp/powershell#1356]
### Reporting an Issue or Missing Feature
Documentation says you can use -WhatIf as a parameter but produces an error if used. This might just be a documentation error as the WhatIf parameter is listed in the parameters section but is not included in the syntax section, although it might be covered under <CommonParameters>.

### Expected behavior 
Accept the -WhatIf parameter and shows what would happen if the cmdlet runs.

### Actual behavior 
If you try to use it you get the error message:

Remove-PnPFile : A parameter cannot be found that matches parameter named 'WhatIf'.

### Steps to reproduce behavior
Execute the cmdlet against any file using the -WhatIf parameter.

### What is the version of the Cmdlet module you are running?
1.8.0

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by LeonArmston** [comment]
@bsimser - good catch! It no longer appears to be in the code and is not mentioned in the rest of the documentation for the command so I assume its a mistake. I have raised a pull request https://github.com/pnp/powershell/pull/1420 to fix it.

**Comment by KoenZomers** [comment]
PR #1420 has been merged in which the documentation has been updated.
