### ISSUE TITLE
Add support for WebTemplate=69 in Add-PnPSiteDesign

### ISSUE THREAD

**Issue by h00g** [pnp/powershell#1358]
**Is your feature request related to a problem? Please describe.**
https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/customize-default-site-design describes the Tean channel WebTemplate and states the value to be 69. The v1.8.0 PnP.PowerShell module does not support this template.

The error thrown when doing **Add-PnSiteDesign** with -WebTemplate 69 is pretty to the point on what's missing.
`Add-PnPSiteDesign: Cannot bind parameter 'WebTemplate'. Cannot convert value "69" to type "PnP.PowerShell.Commands.Enums.SiteWebTemplate" due to enumeration values that are not valid. Specify one of the following enumeration values and try again. The possible enumeration values are "GrouplessTeamSite,TeamSite,CommunicationSite".`

**Describe the solution you'd like**
The SiteWebTemplate enum ought to be updated to include 69 for a private team channel.

**Describe alternatives you've considered**
Microsoft SPO Management Shell allows WebTemplate 69 but I had to revert back to Powershell 5.1 to be able to successfully connect-SPOservice.

**Comment by h00g** [comment]
FYI, WebTemplate=69 is used for the SharePoint site with limited functionality (eg no content type support) used when a private team channel is created.

**Comment by KoenZomers** [comment]
Fixed through https://github.com/pnp/powershell/pull/1369
