### ISSUE TITLE
[FEATURE] Populate ContentType when using Get-PnPListItem

### ISSUE THREAD

**Issue by joshtransient** [pnp/powershell#1360]
**Is your feature request related to a problem? Please describe.**
When I run Get-PnPListItem, the ContentType property is not populated, and I have to run Get-PnPProperty to retrieve it.

**Describe the solution you'd like**
I would like the ContentType property to contain data about the list item's content type when I run Get-PnPListItem.

**Describe alternatives you've considered**
My workaround involves storing the output of Get-PnPContentType in a variable, then getting a list item's content type ID through FieldValues and matching it up, e.g.
````
$list = Get-PnPList -Identity Documents
$listTypes = Get-PnPContentType -List $list
$items = Get-PnPListItem -List $list
foreach($item in $items) {
  [PSCustomObject]@{
    Path = $item['FileRef']
    Type = $listTypes.Where({ $_.Id.StringValue -eq $item['ContentTypeId'].StringValue }).Name
  }
}
````

Or, there is just making the direct REST call (don't shame me for using ArrayList):
````
$list = Get-PnPList -Identity Documents
$allItems = [System.Collections.ArrayList]::new()
$currentPageUrl = "/_api/Web/Lists(guid'{0}')/Items?`$select=FileRef&`$expand=ContentType" -f $list.id.Guid

do {
  $items = Invoke-PnPSPRestMethod -Method Get -Url $currentPageUrl
  $null = $allItems.AddRange(@($items.value))

  $currentPageUrl = $items.'odata.nextLink'
} while(-not [string]::IsNullOrEmpty($currentPageUrl))
````

**Additional context**
Pretty please.

**Comment by LeonArmston** [comment]
Hi @joshtransient 

If you use ContentTypeId to do the match rather than name you can do it without doing any further calls by going into **$item.FieldValues**

$list = Get-PnPList -Identity "Documents"

$item = Get-PnPListItem -List $list -Id 1

$item.FieldValues.ContentTypeId

If you want to get the Name then you already have the name values and their match ID in $listTypes so you could use that for matching.

**Comment by gautamdsheth** [comment]
Correct me if I am wrong, but it should be possible if you specify it in `ViewFields` like here:

https://pnp.github.io/powershell/cmdlets/Get-PnPListItem.html#example-6

![image](https://user-images.githubusercontent.com/8832018/167363873-2b94faaa-7077-4479-a174-fde08b4c2f4d.png)


Here, in the ViewFields, you can specify `ContentType` and `ContentTypeId` and it should work as far as I know
