### ISSUE TITLE
[BUG] Apply-PnPTenantTemplate doc should be removed

### ISSUE THREAD

**Issue by sympmarc** [pnp/powershell#1364]
### Reporting an Issue or Missing Feature

It looks like `Apply-PnPTenantTemplate` has ben replaced with `Invoke-PnPTenantTemplate`, but the [doc for Apply-PnPTenantTemplate](https://pnp.github.io/powershell/cmdlets/Apply-PnPTenantTemplate.html) is still in the repo. Should it be removed?

**Comment by veronicageek** [comment]
Hi @sympmarc - Thanks for raising this. We have a process and automation for the documentation (they are also published on docs.microsoft) but we are discussing all internally to find the best way to have all in sync.

**Comment by sympmarc** [comment]
While you're here... :)

Are there any real examples available for `Invoke-PnPTenantTemplate`? Everything I've found pretty much assumes you just magically have all the right pieces.

**Comment by veronicageek** [comment]
> Everything I've found pretty much assumes you just magically have all the right pieces

Not sure what you mean? Before applying / invoking your template you need to have it. I don't think it's "magic". I'm sure there are a few blogs out there describing the process on how to get and apply your templates (probably still referencing the `Apply-` but still).

Unless you're after something specific you'd like us to include in the documentation.

**Comment by KoenZomers** [comment]
Thanks @sympmarc, documentation indeed needed to be removed. It has been scheduled for deletion and will be processed in tonight's run.

**Comment by veronicageek** [comment]
Closing then.

**Comment by sympmarc** [comment]
Great, thanks.

@veronicageek, I was asking about the Tenant Template docs, but I understand that's out of the purview of this repo. I'll get it sorted on my end and hopefully propose some improvements!
