### ISSUE TITLE
[BUG] Majority of *-Tenant* commands are not working when using in a tenant with Vanity Url

### ISSUE THREAD

**Issue by bhishma** [pnp/powershell#137]
### Reporting an Issue or Missing Feature
Issue: Get-PnPTenantSite/Get-PnPTenantId/Get-PnPTenant/Set-PnPTenantSite are not working as expected. The error message shows wrong tenant url (Should have beeen https://adminms.DOMAIN.com but shows https://adminms-admin.DOMAIN.com).

### Expected behavior 
Expected values returned  (get) or values updated (set)

### Actual behavior 
Get-PnPTenantSite : AADSTS500011: The resource principal named https://adminms-admin.DOMAIN.com was not
found in the tenant named DOMAIN.com. This can happen if the application has not been installed by the
administrator of the tenant or consented to by any user in the tenant. You might have sent your
authentication request to the wrong tenant.
Trace ID: 13cebd1c-79a4-4e89-b88b-9b8001429700
Correlation ID: 3aae7184-b741-4382-a780-466ceb56b9a0
Timestamp: 2021-01-19 23:29:28Z

### Steps to reproduce behavior
```
Import-Module PnP.PowerShell
Connect-PnPOnline -Url https://adminms.DOMAIN.com -Credentials $Cred
$sites=Get-PnpTenantSite
```
### What is the version of the Cmdlet module you are running?
```
ModuleType Version Name
---------- ------- ----
Manifest 1.1.0   PnP.PowerShell
```
### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
Hi!

Please provide the -TenantAdminUrl property on Connect-PnPOnline for this. E.g.

Connect-PnPOnline -Url [yoursite] -Credentials $creds -TenantAdminUrl [yourtenantadminurl]

**Comment by bhishma** [comment]
Thank you. That worked! 
SharePointPnPPowerShellOnline used to work without providing the -TenantAdminUrl property. Is this going to be updated in the future release?

**Comment by erwinvanhunen** [comment]
Actually that should never have worked with the legacy version either without the parameter.... so I'm a bit puzzled. The code behind the scenes is effectively pretty much the same in both the legacy version and the new powershell module? 

The challenge is that we cannot find out through an API call what the URL of the tenant admin site is. We simply assume that if the parameter is not specified that the url is https://[tenant]-admin.sharepoint.[topleveldomain]. E.g. we break up the url and add -admin to it. Unfortunately there is no other way for us to figure out what the tenant admin url is, hence we introduced (years ago already...) the -TenantAdminUrl parameter.

**Comment by erwinvanhunen** [comment]
To get a full understanding: do you connect with Connect-PnPOnline to 'normal' site, or do you connect to the tenant admin site?

**Comment by bhishma** [comment]
I connect to tenant admin site to execute admin level codes (eg. Get-PnPTenantSite etc) and it used to work with old version.

**Comment by erwinvanhunen** [comment]
Okay, there we have it. We changed the detection code in PnP PS to figure out if we're in a SPO Tenant Admin site. I'll see if we can fix that.

**Comment by erwinvanhunen** [comment]
A fix will be available in the 1.1.2-nightly release which you will be able to install as of tomorrow using

```powershell
Update-Module -Name PnP.PowerShell -AllowPrerelease
```

**Comment by bhishma** [comment]
You're awesome. Thank you!

**Comment by plagooms** [comment]
hello, i am having same issue with Get-PnPTenantSite using our vanity URL.  I connect to tenant admin site.

PS C:\temp\Test> $s = Get-PnPTenantSite -Identity $SiteId -Detailed -Connection $ctxt
Get-PnPTenantSite : AADSTS500011: The resource principal named https://admin-admin.company.com was not found in the tenant named company. 
This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You 
might have sent your authentication request to the wrong tenant.
Trace ID: 2c2d6b11-3774-4b9f-8cc1-7e0d31fe4500
Correlation ID: 4396a26b-efa1-4d7d-b609-9a25c4876f59
Timestamp: 2022-11-18 10:27:49Z
At line:1 char:6
+ $s = Get-PnPTenantSite -Identity $SiteId -Detailed -Connection $ctxt
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPTenantSite], MsalServiceException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.GetTenantSite

PS C:\temp\Test> 
PS C:\temp\Test> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      22000  832
