### ISSUE TITLE
[BUG] Using New-PnPSite inside Azure Automation Runbook -Owners are not recognized

### ISSUE THREAD

**Issue by ResolutionsEichert** [pnp/powershell#1373]
### Reporting an Issue or Missing Feature
When I am using the cmdlet New-PnPSite on my local environment and I am specifying an owner with New-PnPSite -Owners "email@address.com" it's working fine on my local machine however the command is ignored in Powershell-Runbook Automation on Azure

### Expected behavior 
User is added to the owners

### Actual behavior 
No output site is being created but the owner is not specified

### Steps to reproduce behavior
$newSite = New-PnPSite -Type TeamSite -Alias $ProjectNumber -Title "$($ProjectNumber) - $($Title)" -Owners $user.Email -Verbose

### What is the version of the Cmdlet module you are running?
1.8.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [x] Azure Functions
- [ ] Other : please specify

**Comment by ResolutionsEichert** [comment]
I found a workaround that solves the permission issues with the SharePoint site but not with the associated O365-Group.

I altered the script to add the user to the associatedownersgroup, so script now looks like this:

~~~~~~~~~

$site = New-PnPSite .....

Connect-PnPOnline $site 

$owners = Get-PnPGroup -AssociatedOwnersGroup

Add-PnPGroupMember -LoginName $user.LoginName -Identity $owners

~~~~~~~~~

So this workaround is only valid for SharePoint but not for the group that it's connected to.

**Comment by CreativeAcer** [comment]
@ResolutionsEichert Your workaround can also work for the Connected Group by using the following:

Get-PnPMicrosoft365Group
and
Add-PnPMicrosoft365GroupOwner / Add-PnPMicrosoft365GroupMember

**Comment by gautamdsheth** [comment]
Hi @ResolutionsEichert , can you please try with the latest 1.9.0 version, check and let us know ? Also, looks like Azure automation has a update with the release of PowerShell 7.1 support ? Maybe you try it there ?

**Comment by ncoschrdr** [comment]
Hi, I'm pulling my hair out since I'm facing the exact same issue, I only tested it with PS 5.1 so far but (at least for me) the issue still persists in 1.9.0 in my Runbook. On my local machine I also use 1.9.0 and it works without issues.

**Comment by gautamdsheth** [comment]
Closing the issue then , thanks for checking and getting back to us 😊
