### ISSUE TITLE
[BUG] Move-PnPFile -IgnoreVersionHistory

### ISSUE THREAD

**Issue by Bryand13** [pnp/powershell#1376]
Hello all,

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

Cmdlet "Move-PnPFile -IgnoreVersionHistory" is not working as expected.

### Expected behavior 
When using "Move-PnPFile -IgnoreVersionHistory" i expect to see in the target site only the last version for the file moved.

### Actual behavior 
When using "Move-PnPFile -IgnoreVersionHistory" it moves all version history for one file.

*The actual behaviour was also confirmed by Microsoft Premier Support.

### Steps to reproduce behavior
Move-PnPFile -SourceUrl "/teams/Site1/Move/1 - copia (4).txt" -TargetUrl "/teams/Site2/Moved/" -IgnoreVersionHistory

### What is the version of the Cmdlet module you are running?
Using 1.8.46-nightly  PnP.PowerShell but its not working since the 1.8.0 version.

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
Similar to my issue #1246 but opposite way

**Comment by veronicageek** [comment]
Reproduced on version `1.9.5`.

**Comment by veronicageek** [comment]
@Bryand13 - Can you try again with the nightly release? (Today is `1.10.64`)

**Comment by Bryand13** [comment]
Yes i can. I'll let you know something ASAP. Thank you @veronicageek.

**Comment by Bryand13** [comment]
Hello @veronicageek,

I did the test today and unfortunatelly i had no luck. The version history is still moved to the target site.

Command used: Move-PnPFile -SourceUrl "/teams/site1/Librera_4/file.txt" -TargetUrl "/teams/site2/Moving" -IgnoreVersionHistory

Module version: 1.11.0  PnP.PowerShell installed on machine.

Regards.

**Comment by veronicageek** [comment]
Still an issue in `1.12.79` (history moved).

**Comment by veronicageek** [comment]
@Bryand13 - A new version of CSOM has been released last week (which we are consuming), can you please update to the latest release 2.1.x however you will **need PS `7.2` or later** to benefit from it.

PS5 support has been dropped in the new release.
