### ISSUE TITLE
[BUG] - Incorrect Term Group name and GUID in exported xml

### ISSUE THREAD

**Issue by BipulRaman** [pnp/powershell#1383]
### Expected behavior 
Incorrect Term Group name and GUID in exported xml for a site collection
Example: <pnp:TermGroup Name="{sitecollectiontermgroupname}" ID="00000000-0000-0000-0000-000000000000"

### Expected behavior 
Example: <pnp:TermGroup Name="TestGroup" ID="....

### Steps to reproduce behavior
Connect-PnPOnline -Url $Url -Tenant $TenantId -ClientId $ClientId -Thumbprint $ThumbprintId
Export-PnPTermGroupToXml -Out output.xml -Force
Disconnect-PnPOnline
Note: Url should be a site collection url

### What is the version of the Cmdlet module you are running?
1.8.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows

**Comment by veronicageek** [comment]
@BipulRaman - Can you update to the latest version and feedback please. 
I tested on `1.9.5` (nightly release) and I'm not able to reproduce your issue.

**Comment by BipulRaman** [comment]
@veronicageek This is still not working. I was using 1.9.11 Nighly build. Exporting wrong results for SiteCollection Term-store. 
Note: The issue is specific to Site Collection Term-store.

**Comment by veronicageek** [comment]
@BipulRaman 
- Have you tried on a different Site Collection? Or is it for all Site Collections the same problem? 
- Are all the Term Group Names & IDs wrong, or random?
- Could you (if possible) try on another tenant?

**Comment by veronicageek** [comment]
Closing as no response.
