### ISSUE TITLE
Connect-PnPOnline Interactive MacOS Safari cannot connect to localhost

### ISSUE THREAD

**Issue by gingemonster** [pnp/powershell#1385]
When running on MacOs Mojave 10.14.6:

`Connect-PnPOnline -Url https://myorg.sharepoint.com/sites/mysite -Interactive`

### Expected behavior 
On windows the login opens in my browser, I follow the normal login flow and I get a page (from powershells localhost website) confirming I have logged in and can close the tab

### Actual behavior 
After I have followed the login flow (we use lastpass for office365 2fa) Safari is unable to open the localhost website powershell should be running to collect the login response:

![image](https://user-images.githubusercontent.com/703352/143567265-fbab8634-5c04-4bc4-a7ed-ae86f8067b9d.png)

Powershell then shows:

![image](https://user-images.githubusercontent.com/703352/143567336-63265d42-809c-482d-b722-743f0cf825d6.png)

### Steps to reproduce behavior

1. Open powershell core on MacOs
2. Run `Connect-PnPOnline -Url https://myorg.sharepoint.com/sites/mysite -Interactive`
3. Follow normal login flow until safari errors loading localhost

### What is the version of the Cmdlet module you are running?

1.8.0 

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [X] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gingemonster** [comment]
Interesting... I copied the web address from safari and opened in chrome and it worked as expected

**Comment by veronicageek** [comment]
I have no issue with Safari and PnP.PowerShell `1.8.50` (latest nightly release). I'm also on MacOS Monterey, so I'd first suggest you update everything you can but I'm afraid we won't be able to help much. 

![image](https://user-images.githubusercontent.com/25181757/143688115-3efb8154-f811-4594-8df7-2cf7b47c3d87.png)

**Comment by veronicageek** [comment]
Closing as no response.
