### ISSUE TITLE
[BUG] Add-PnPDataRowsToSiteTemplate: User cannot be found.

### ISSUE THREAD

**Issue by somesh-bhalerao** [pnp/powershell#1387]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
This is an issue.

### Expected behavior 
I am running command Add-PnPDataRowsToSiteTemplate, which I was able to execute successfully on the lists where list item has inherited permissions from parent. (No unique permissions on list items)

Where lists items had its own permissions and some of the users login may be disabled as they left the company, the command gives error.

If the user is not found during export, command should skip those entries of user permissions and export rest of the data.

### Actual behavior 
When I execute this command on a specific lists where permissions are managed on each lists item, it fails. (As some users disabled/removed from AAD)

I doubt that on some of the list items, the command is trying to validate users and as some of the users had left the company, powershell /  Add-PnPDataRowsToSiteTemplate do not find valid user and it throws an error and it stops complete export of the list.

I tried this command with and without using switch -IncludeSecurity, but the behaviour is same.

![Add-PnPDataRowsToSiteTemplate-Error](https://user-images.githubusercontent.com/33805667/143593317-6f5370c1-4f8c-426d-a8fe-68301d988dc3.png)

### Steps to reproduce behavior

Connect-PnPOnline -Url "https://dummy.sharepoint.com/sites/Test1" 

#2 - Export the source lists
Export-PnPListToSiteTemplate -Out "C:\Delete\RR\myLists.xml" -List "Sample01", "Sample02", "Sample03", "R---- R-------"

#3 - Export the list data for the specified lists
Add-PnPDataRowsToSiteTemplate -Path "C:\Delete\RR\myLists.xml" -List "Sample01"
Add-PnPDataRowsToSiteTemplate -Path "C:\Delete\RR\myLists.xml" -List "Sample02"
Add-PnPDataRowsToSiteTemplate -Path "C:\Delete\RR\myLists.xml" -List "Sample03"
Add-PnPDataRowsToSiteTemplate -Path "C:\Delete\RR\myLists.xml" -List "R---- R-------"

### What is the version of the Cmdlet module you are running?
1.7.0

### Which operating system/environment are you running PnP PowerShell on?
- Windows

**Comment by somesh-bhalerao** [comment]
Would be thankful if someone look into it.

**Comment by Rtoribiog** [comment]
same error in my side when i export a list with user field inside and audience

**Comment by gautamdsheth** [comment]
Hi, have fixed the issue related to this. 
It will be available from tomorrow's nightly.
Thanks for raising the issue :)

**Comment by somesh-bhalerao** [comment]
Thank You
