### ISSUE TITLE
[BUG] Connect-PnPOnline without -Interactive breaks transcrption

### ISSUE THREAD

**Issue by saltzimania** [pnp/powershell#1388]
### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

We are using start-transcription for logging purposes.  When we 

### Expected behavior 
We expect start-transcript to capture all output into the transcript file.

### Actual behavior 
Transcription stops at Connect-PnPOnline -Url https://tenant.sharepoint.com/
However, transcription behaves as expected if we use -Interactive
Error message at the end of the script is:
Stop-Transcript : An error occurred stopping transcription: The host is not currently transcribing.

### 
**Script:**
```
Start-Transcript
Write-Host "Test Output 1"
Connect-PnPOnline -Url https://tenant.sharepoint.com/
Write-Host "Test Output 2"
Stop-Transcript
```
**Console Output:**
```
PS C:\Users\user> c:\Users\user\Desktop\TranscriptTest.ps1
Transcript started, output file is C:\Users\user\Documents\PowerShell_transcript.S-07-21.pZKVnSLn.20211126120339.txt
Test Output 1
Enter your credentials
User: user@domain.com
Password for user user@domain.com: ********************
Test Output 2
Stop-Transcript : An error occurred stopping transcription: The host is not currently transcribing.
At C:\Users\user\Desktop\TranscriptTest.ps1:5 char:1
+ Stop-Transcript
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Stop-Transcript], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.StopTranscriptCommand
```
**Transcript:**
```
**********************
Windows PowerShell transcript start
Start time: 20211126120339
Username: DOMAIN\user
RunAs User: DOMAIN\user
Configuration Name: 
Machine: hostname (Microsoft Windows NT 10.0.17763.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\user\.vscode\extensions\ms-vscode.powershell-2021.10.2\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2021.10.2' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\user\.vscode\extensions\ms-vscode.powershell-2021.10.2\modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2021.10.2 <=====
' -LogLevel 'Normal' -LogPath 'c:\Users\user\.vscode\extensions\ms-vscode.powershell-2021.10.2\logs\1637953368-53b4e9c1-7fc8-47d6-a7e9-df61d918e4981637953363140\EditorServices.log' -SessionDetailsPath 'c:\Users\user\.vscode\extensions\ms-vscode.powershell-2021.10.2\sessions\PSES-VSCode-24616-599382' -FeatureFlags @() 
Process ID: 16672
PSVersion: 5.1.17763.2183
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.17763.2183
BuildVersion: 10.0.17763.2183
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Test Output 1
**********************
Windows PowerShell transcript end
End time: 20211126120341
**********************
```
### What is the version of the Cmdlet module you are running?
1.8.0

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@saltzimania - Tried your code snippet and no issue on my side with PnP.PowerShell `1.8.0` (without `-Interactive`). However, is your user account MFA enabled?

![image](https://user-images.githubusercontent.com/25181757/145014580-d403995b-668a-4eb6-b8d4-7a8947ecdec7.png)

![image](https://user-images.githubusercontent.com/25181757/145014625-32dea9b0-456c-449c-9b4c-46050bacbb2b.png)

**Comment by saltzimania** [comment]
Hi @veronicageek, sorry I haven't had chance to look at this again yet.  Since you mention MFA, the account in this case was not enrolled for MFA, but it was signing in ADFS via my client's on-prem environment so maybe that's the issue.  When I get a chance I'll try to duplicate with a cloud-only Azure AD account.

Thanks!

**Comment by veronicageek** [comment]
Thanks @saltzimania - The account I used for my testing was not MFA enabled so at least, it works this way.
Closing the issue for now, please reopen if the problem persists.
