### ISSUE TITLE
[BUG] ConvertTo-PnPPage fails because it exceeds the list view threshold

### ISSUE THREAD

**Issue by eepyaich** [pnp/powershell#1395]
### Reporting an Issue or Missing Feature
When calling "ConvertTo-PnPPage" on a site which already has > 5000 pages, I receive an error "The attempted operation is prohibited because it exceeds the list view threshold.".

It's worth noting that I'm still able to create Wiki pages on this site using Add-PnPWikiPage - it's just the convert operation which fails.

### Expected behavior 
I'd expect the conversion operation to succeed.

### Actual behavior 
Conversion operation fails, with error:

<img width="408" alt="image" src="https://user-images.githubusercontent.com/6351761/143909022-76579f9c-1d2f-4c19-b0dc-9edbdb0760b6.png">

### Steps to reproduce behavior
1. Use Add-PnPWikiPage to add a page to a site that already contains > 5000 pages in the SitePages library
2. Try ConvertTo-PnPPage to convert Wiki page to modern page.  Command returns error.

### What is the version of the Cmdlet module you are running?
1.8.0

### Which operating system/environment are you running PnP PowerShell on?
Windows

- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Hi @eepyaich , can you please try with the latest 1.9.0 version, check and let us know ?

**Comment by eepyaich** [comment]
Will do - it might take a day or so (I need to recreate a suitable environment).

Out of interest, do you think this could be fixed, or is this just the first step before investigating it further?

**Comment by eepyaich** [comment]
A colleague tried to reproduce the original issue using the 1.9.0 PnP and reports that this does now appear to be fixed.  Thanks!

**Comment by eepyaich** [comment]
Apologies - that was a false positive.  Having double checked myself, it appears the bug is still present (my colleague hadn't realised the full symptoms, so mistakenly thought it was resolved).

So - to confirm, this does still appear to be a bug in 1.9.0.

**Comment by veronicageek** [comment]
@eepyaich - Can you please update to the latest release 2.1.x however you will need **PS 7.2 or later** to benefit from all the bug fixes and improvements.

PS5 support has been dropped in the new release.

Feel free to reopen if the issue persists. Thanks.
