### ISSUE TITLE
[BUG] Get-PnPSiteTemplate Cannot Output file (and -OutputInstance returns null variable)

### ISSUE THREAD

**Issue by BrennanAldridge** [pnp/powershell#140]
### Reporting an Issue or Missing Feature
I am using PnP.PowerShell versions 1.1.0 (on Windows 10). The **Get-PnPSiteTemplate** function is returning and access denied error. I have tried in VS Code, Windows PowerShell (5.1), SharePoint Management Shell. I am running all applications as an administrator and attempting to save the file to a non-root path.

**Command**:
Get-PnPSiteTemplate -Out template.xml

**Error**:
Get-PnPSiteTemplate : {"odata.error":{"code":"-2147024891,
System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied. You do not have permission to
perform this action or access this resource."}}}
ServerErrorTraceCorrelationId: 5229a39f-d03c-b000-76e2-211d0c89ba14
At line:1 char:1
+ Get-PnPSiteTemplate -Out template.xml
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPSiteTemplate], Exception
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Site.GetSiteTemplate

AI tried a workaround to output to a variable, but the output is null:
$var = Get-PnPSiteTemplate -OutputInstance

**Comment by erwinvanhunen** [comment]
The error message is coming from the SharePoint server. So in this case the engine tries to access an artifact/resource in your site to which you don't have access it seems. You can turn on the tracelog to get more detailed information on where exactly it goes wrong:

```powershell
Set-PnPTraceLog -On -LogFile c:\path\log.txt
Get-PnPSiteTemplate
Set-PnPTraceLog -Off
```

**Comment by BrennanAldridge** [comment]
Thank you for the quick response @erwinvanhunen. I should add I am connecting to a Modern Team site with site collection admin credentials. Not sure what I wouldn't have access to... but I'll add the above tracing steps and see if I can provide additional info.

**Comment by BrennanAldridge** [comment]
Hi @erwinvanhunen. This is the error provided in the log. It still looks to me like an issue writing the output file:
[PnP.Framework]	[0]	[Error]	File template.pnp not found in directory . Exception = Could not find file 'C:\temp\template.pnp'.	0ms

I specified -out c:\temp\template.pnp parameter...

Please advise. Thank you very much in advance!

**Comment by BrennanAldridge** [comment]
Hi @erwinvanhunen. I looked at the current code vs. the legacy version (which used to work when I used it several months ago.

Legacy Version
![image](https://user-images.githubusercontent.com/45017512/105206306-d6b6bc80-5b0b-11eb-8be4-a8fa3c91dc83.png)

Current Version
![image](https://user-images.githubusercontent.com/45017512/105206397-f221c780-5b0b-11eb-99c8-bdf02838c180.png)

Considering the object returned with -OutputInstance is null, I'm also wondering if the template that is trying to be saved is also null, and thus is throwing the error that it cannot write a null object as output.

The template output is initialized as null on line 365... so perhaps it is never getting set on line 418 (372 in my screenshot above)... which would mean some sort of unhandle error in the TokenRetrieval.GetAccessTokenAsync(resource, scope)???

FWIW I am authenticating using the following:
Connect-PnPOnline -Url https://domain.sharepoint.com/teams/sitecollection/ -UseWebLogin

**Comment by erwinvanhunen** [comment]
We have found an issue with the backend code that is affecting this potentially. It only occurs when using `-UseWebLogin`, as we need to resolve the URL to acquire certain tokens and in that URL resolving part it went wrong. The result is that you will not have a template to save, which might explain your issues. We might release a 1.2 today.

**Comment by BrennanAldridge** [comment]
Thank you @erwinvanhunen! Very much appreciated!

**Comment by BrennanAldridge** [comment]
I can confirm that the 1.1.2-nightly build resolves this issue.

Based on the output ov 1.1.2 vs 1.1.0, the 1.1.0 version stopped collection process when it encountered a list with spaces (e.g., /Shared%20Documents/).
