### ISSUE TITLE
[FEATURE] Way to set unique permissions on Site pages and Files in a library please

### ISSUE THREAD

**Issue by metkhoo** [pnp/powershell#1406]
**Is your feature request related to a problem? Please describe.**
I know we can set unique permissions on FOLDERS,  SITES, and LIST ITEMS but I can't see any way of setting unqiue permissions for FILES in folder or PAGES in Site pages.

**Describe the solution you'd like**
It would be good to have a 
Set-PnPFilePermission and/or Set-PnPPagePermission that would solve it

**Describe alternatives you've considered**
I am flummoxed as to how to actually achieve this in any way using the existing PnP Cmdlets.

**Additional context**

**Comment by LeonArmston** [comment]
Wouldn't you just use [Set-PnPListItem](https://github.com/pnp/powershell/blob/dev/documentation/Set-PnPListItemPermission.md) as after all pages are just items in the Site Pages list?

**Comment by metkhoo** [comment]
Hi Leon,  
That would be my approach if I wanted all the pages with the same permissions.  I want only ONE of the pages to have unique permissions and all the rest to have different permissions.
I did think up a possible solution to create FOLDERS in the SitePages library and then use the Set-PnPFolderPermission on that folder but it seems a bit of a "hack" to me...
Thanks for responding though.

**Comment by LeonArmston** [comment]
> Hi Leon, That would be my approach if I wanted all the pages with the same permissions. I want only ONE of the pages to have unique permissions and all the rest to have different permissions. I did think up a possible solution to create FOLDERS in the SitePages library and then use the Set-PnPFolderPermission on that folder but it seems a bit of a "hack" to me... Thanks for responding though.

Not sure I totally understand what you are try to do but **Set-PnPListItemPermission** only applies the permissions to a single item - (so just a page for you). I showed you **Get-PnPListItem** so you could get easily get the ID of the page you want to apply unique permissions to. Once you have the page ID i.e. 5 then add it to the **Set-PnPListItemPermission** command to run that command on a specific page.

**Comment by metkhoo** [comment]
Hi again,
Are you suggesting that Get-PnPListItem actually works for Site Pages and Files too and is not restricted to custom lists? Never tried that to be honest because the examples for Set-PnPListItemPermission showed Identity with an integer which led me to believe it was just related to "List items" and not to Site Pages or Files in a document library.  That is a good shout! I'll try it out.  Many thanks again.

**Comment by metkhoo** [comment]
Can I recommend then that **Set-PnPListItemPermission** should then be renamed to be **Set-PnPItemPermisson** or at least the examples show use of this with files in Document Libraries.  The help text for the cmdlet is a bit misleading.

**Comment by metkhoo** [comment]
Again many thanks

**Comment by metkhoo** [comment]
Yep working!  Never knew that Files in libraries also had a sequential number.  Thanks Leon
