### ISSUE TITLE
[BUG] Get-PnPMicrosoft365Group - ResourceBehaviorOptions empty for non-Team connected M365 Groups

### ISSUE THREAD

**Issue by Nibushi** [pnp/powershell#1422]
### Reporting an Issue or Missing Feature
I am not sure whether this is a bug or by design.

When running Get-PnPMicrosoft365Group for Teams connected Groups the ResourceBehaviorOptions are populated to show things like:
ResourceBehaviorOptions       : {HideGroupInOutlook, SubscribeMembersToCalendarEventsDisabled, WelcomeEmailDisabled}

Running the same command against non-Teams connected M365 Groups these properties are not shown:
ResourceBehaviorOptions       : {}

### Expected behavior 
Regardless of whether the Group is connected to a Team it should return the ResourceBehaviorOptions. These properties are shown in the Admin UI regardless of whether the Group is connected to a Team or not.

Looking to see these properties:
![image](https://user-images.githubusercontent.com/6292273/145019825-8d7f1f74-8839-45d4-b829-6b7be287ef2f.png)

### Actual behavior 
Non-Team connected Groups do not return the properties which are visible in the UI

### Steps to reproduce behavior
$group = Get-PnPMicrosoft365Group -Identity "Group Name/GUID"
$group | fl *

### What is the version of the Cmdlet module you are running?
v1.8.0

### Which operating system/environment are you running PnP PowerShell on?
- [ x ] Windows

**Comment by LeonArmston** [comment]
Not sure if its a fault with the underlying MS Graph API call to /Groups but ResourceBehaviourOptions is not populated at all.

![image](https://user-images.githubusercontent.com/12968962/145392173-cdad3a6d-d896-405b-b2de-4cea2274e2ca.png)

When you access a Team you go the Graph API endpoint /teams and this does return ResourceBehaviourOptions. Unfortunately we can only access Team enabled Groups with this endpoint.

**Comment by gautamdsheth** [comment]
Thanks @LeonArmston  for the investigation.
Yeah, looks like an issue with Graph API. 
Going to close this issue and would suggest that you raise this with Microsoft
