### ISSUE TITLE
Copy-PnPFile fails with no error when copying a file between document libraries with different versioning settings[BUG]

### ISSUE THREAD

**Issue by jeremyhagan** [pnp/powershell#1423]
### Reporting an Issue or Missing Feature
I have two document libraries and am trying to copy a file between them.
**Source library settings:** Require Content Approval and Major and Minor versions
**Destination library settings:** DO NOT require content approval and Major versions only

### Expected behavior 
When using Copy-PnpFile, the file should be copied or an error should occur

### Actual behavior 
The file is not copied and no error is returned. 

If the -IgnoreVersionHistory switch is used, the file is copied correctly.

### Steps to reproduce behavior

1. Set up two document libraries with source and destination Version Settings as documented above.
2. Create a file in the source directory and then approve the document so that it is published as a major version
3. Use the following code to copy the file:
`Copy-PnPFile -SourceUrl "Shared Documents/company.docx" -TargetUrl "/sites/otherproject/Shared Documents"`

### What is the version of the Cmdlet module you are running?
1.8.0

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [X ] Other : Azure Automation

**Comment by gautamdsheth** [comment]
Hi @jeremyhagan , can you try again with the latest 1.9.0 version ? Was not able to reproduce it with the above steps. The file got copied over without any error

**Comment by veronicageek** [comment]
Closing as no response.
