### ISSUE TITLE
[BUG] Add-PnPPageWebPart Image web part. Image doesn't display until after editing and saving the page

### ISSUE THREAD

**Issue by rzempo** [pnp/powershell#1424]
### Reporting an Issue or Missing Feature
When you use this command Add-PnPPageWebPart to add an Image web part to a page, the web part gets added but the Image doesn't display until after editing and saving the page

### Expected behavior 
Add-PnPPageWebPart adds an Image web part to a page and the you can see the web part in the page without having to edit and save first

### Actual behavior 
Add-PnPPageWebPart adds an Image web part to a page, the web part gets added but the Image doesn't display until after editing and saving the page

### Steps to reproduce behavior
$site = '[site url]'
$pageTitle = "[page title]"
$imageUrl = "[image url in this site]"
$wpProps = @{imageSource=$imageUrl;imgWidth=975;imgHeight=625}

Connect-PnPOnline -Url $site -Interactive
Add-PnPPageWebPart -Page $pageTitle -DefaultWebPartType Image -WebPartProperties $wpProps -Section 1 -Column 1 -Order 2
Disconnect-PnPOnline 

### What is the version of the Cmdlet module you are running?
1.8.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@rzempo - Is this on a new page? On the `home.aspx`? or a page that has been edited/saved before?

I'm not _entirely_ sure if your issue is an expected behavior like in `Get-PnPClientSidePage` where we've mentioned this in the [documentation](https://pnp.github.io/powershell/cmdlets/Get-PnPClientSidePage.html):

>This command allows the retrieval of a modern sitepage along with its properties and contents on it. Note that for a newly created modern site, the Columns and Sections of the Home.aspx page will not be filled according to the actual site page contents. This is because the underlying CanvasContent1 will not be populated until the homepage has been edited and published. The reason for this behavior is to allow for the default homepage to be able to be updated by Microsoft as long as it hasn't been modified. For any other site page or after editing and publishing the homepage, this command will return the correct columns and sections as they are positioned on the site page.

But maybe @gautamdsheth or @KoenZomers may know?

**Comment by veronicageek** [comment]
Closing as no response.

**Comment by rzempo** [comment]
Hi @veronicageek, Yes, newly created page. Not home.aspx. Result is the same if the page is newly created or if it has been edited/saved before.

**Comment by GuMaFF** [comment]
Hi, I can confirm that I have the exact same issue. I am creating a new page with Add-PnPPage then when using Add-PnPPageWebPart the webpart (with an image) is added nicley but I then need to manually edit/save/publish the page again for it to be visible

**Comment by rohit404404** [comment]
Facing same issue. Had to manually edit page and publish
