### ISSUE TITLE
[FEATURE] Add Text web part with Image web parts inside the Text web part

### ISSUE THREAD

**Issue by rzempo** [pnp/powershell#1425]
**Is your feature request related to a problem? Please describe.**
Manually you can add Image web parts inside a single Text web part. I.e., some text, image1, some more text, image2, etc., everything inside a single Text web part like the image below
![144035390-fc52ff80-dc58-4578-a6d7-3f499cc23bcf](https://user-images.githubusercontent.com/20348540/145203764-378040c4-8f55-4b13-b3b1-9a588f0373e1.png)
Dynamically I can add Text web parts, and Image web parts but they are individual web parts in the page using Add-PnPPageTextPart and Add-PnPPageWebPart, which is likely to go over the 20 web parts per page limit recommendation (https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-portal-limits?view=o365-worldwide)

**Describe the solution you'd like**
I would like to dynamically be able to add Image web parts inside a Text web part using using similar commands to Add-PnPPageTextPart or Add-PnPPageWebPart. Potentially the images be part of the properties of the Add-PnPPageTextPart command.

**Describe alternatives you've considered**
Use Add-PnPPageTextPart and Add-PnPPageWebPart to individually add web parts accordingly 

**Additional context**
-

**Comment by smumalo** [comment]
In pnp core this is made possible by "GetInlineImageAsync" inside the "https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core/Model/SharePoint/Pages/Internal/Page.cs" 

(just for info)

**Comment by khamphou** [comment]
hello

i am interested in this feature too for **pnp powershel**l.
le me know once it is added in your roadmap and released.

thank you.

**Comment by rohitblue28** [comment]
We need this feature ASAP.

**Comment by dora-popova** [comment]
This would be a vital feature necessary for any meaningful bespoke migration effort, it would be great if it is implemented as part of pnp.
