### ISSUE TITLE
[BUG] Get-PnPTeamsTab - 

### ISSUE THREAD

**Issue by ITAndy23** [pnp/powershell#1427]
I need to get the specific app information on per tab. Sometimes using the Get-PnPTeamsApp and fetching "Wiki" isn't good enough as they could rename the tab. 

### Reporting an Issue or Missing Feature
**Get-PnPTeamsTab** returns array with objects that has properties for **TeamsApp** and **TeamsAppId** which are always blank. 

### Expected behavior 
I would expect **TeamsApp** and **TeamsAppId** would have values like **DisplayName** and **Id**, for example.

### Actual behavior 
What's occurring is **TeamsApp** and **TeamsAppId** are empty
![image](https://user-images.githubusercontent.com/5934563/145257075-5321df02-4047-4791-ac09-50227c43dee1.png)

### Steps to reproduce behavior
`Get-PnPTeamsTab -Team $Team.DisplayName -Channel $Channel`

### What is the version of the Cmdlet module you are running?
1.4.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by LeonArmston** [comment]
Can confirm it is not populating TeamsApp and TeamsAppId through PowerShell

![image](https://user-images.githubusercontent.com/12968962/145387850-df2a487a-7739-4188-85c8-fec02ced0b10.png)

If you do the query using Graph (see below) and use ?$expand=teamsApp it will then return the teamsApp details which are ordinarily not returned by default.

```
GET https://graph.microsoft.com/v1.0/teams/{id}/channels/{id}/tabs/{id}?$expand=teamsApp
```

![image](https://user-images.githubusercontent.com/12968962/145387600-4438a0a4-4557-4b25-9645-cd3594b52ede.png)

**Comment by veronicageek** [comment]
@jansenbe - FYI

**Comment by gautamdsheth** [comment]
@LeonArmston , @veronicageek - looks like a PnP PowerShell issue, will look into this :)

**Comment by gautamdsheth** [comment]
@ITAndy23 - have sent a PR to fix this. 
Once **approved and merged,** the `TeamsApp` object will be populated with properties like `Id ,DisplayName , ExternalId and DistributionMethod ` if available.

So, you can then use it as :
```
$tab = Get-PnPTeamsTab -Team "TestLCID" -Channel "General" -Identity 8257990e-df53-4018-8d6a-2a5dc17d0bbf
$tab.TeamsApp.Id
$tab.TeamsApp.DisplayName
```

something like below:

![image](https://user-images.githubusercontent.com/8832018/146554280-283be5ce-754c-484f-b2c2-76830a46abbf.png)
