### ISSUE TITLE
[BUG] ConvertTo-PnPPage : CSOM service exception

### ISSUE THREAD

**Issue by aaronzyAlpha** [pnp/powershell#1443]
### Reporting an Issue or Missing Feature
ConvertTo-PnPPage is throwing an error when I try to transform classic pages through PowerShell

### Expected behavior 
Transform the classic page to modern page

### Actual behavior 
![image](https://user-images.githubusercontent.com/45278392/145881940-fd33d52a-fe23-40f6-a3f4-f4dfc7d04235.png)

### Steps to reproduce behavior
1. Connect-PnPOnline -Url _https://[tenant].sharepoint.com/[SubSite]
2. ConvertTo-PnPPage -Identity "demo.aspx" -Overwrite
3. Error.

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
![image](https://user-images.githubusercontent.com/45278392/145882528-3cf2f959-e453-4859-93dd-1e42119eb80b.png)

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows

###After running Get-PnPException, see log below
![image](https://user-images.githubusercontent.com/45278392/145882811-a8b9f5b1-277b-44ae-9c58-0108353f745a.png)

**Comment by gautamdsheth** [comment]
@aaronzyAlpha - can you please with the latest version 1.9.0 and let us know ??

**Comment by veronicageek** [comment]
Closing as no response.
