### ISSUE TITLE
[BUG] isHubSite doesn't work when you use Get-PnpTenantSite without a URL

### ISSUE THREAD

**Issue by Ambergahill** [pnp/powershell#1449]
###Bug
This is related to https://github.com/pnp/powershell/issues/151, but different. If I run (Get-PnpTenantSite -URL http://blahblahblah).IsHubSite, it works correctly.

However, if I run $sites = Get-PnpTenantSite -Detailed, then iterate through each site with something like $sites | select URL, isHubSite, it will always return false.

I can't run Get-PnpTenantSite on every URL because we have over 50,000 and it takes forever. Thanks!

### Expected behavior 
isHubSite should work if you pass a URL into Get-PnpTenantSite or not

### Actual behavior 
isHubSite is always false with Get-PnpTenantSite without a URL

### Steps to reproduce behavior
run $sites = Get-PnpTenantSite -Detailed, then iterate through each site with something like $sites | select URL, isHubSite, it will always return false.

### What is the version of the Cmdlet module you are running?
1.8.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [X] Azure Functions
- [ ] Other : can repro in both windows and azure function

**Comment by gautamdsheth** [comment]
Hi this a SharePoint bug. Unfortunately, we can't do anything about this because the response itself is incorrect.
Please raise an issue with Microsoft support mentioning that `GetSitePropertiesFromSharePointByFilters` method from CSOM is returning incorrect data.

You can repro it in pure CSOM as well using the below code snippet:

```
List<SiteProperty> AllSiteVals = new List<SiteProperty>();
var tenant = new Tenant(ctx);
SPOSitePropertiesEnumerable props = null;

while (props == null || props.NextStartIndexFromSharePoint != null)
{

    SPOSitePropertiesEnumerableFilter filter = new SPOSitePropertiesEnumerableFilter()
    {
        IncludePersonalSite = PersonalSiteFilter.Include,  //use PersonalSiteFilter.UseServerDefault to exclude
        StartIndex = props == null ? null : props.NextStartIndexFromSharePoint,
        IncludeDetail = true
    };
    props = tenant.GetSitePropertiesFromSharePointByFilters(filter);

    tenant.Context.Load(props);
    tenant.Context.ExecuteQuery();

    foreach (var prop in props)
    {
        // do your stuff here
        // AllSiteVals.Add(props);
    }
}
```

Will be closing this issue.
If and when Microsoft fixes this issue, it will be automatically fixed in PnP PowerShell as we always use the latest CSOM SDK.
