### ISSUE TITLE
Remove-PNPPage -Recycle Parameter not found

### ISSUE THREAD

**Issue by adidelot** [pnp/powershell#1455]
Using this against SharePoint Online:
`
$page = Get-PnPPage -Identity "help.aspx"
`
`
Remove-PnPPage -Identity $page -Recycle
`
Error Thrown: Remove-PnPPage : A parameter cannot be found that matches parameter name 'Recycle'.

However, the -Recycle Parameter works fine with Remove-PNPFile.

**Comment by gautamdsheth** [comment]
Please dont delete the Issue template , makes it very difficult for us to understand it.

About this command, please use the latest PnP PowerShell nightly build, we added it couple of days back, so it is not available in the major version.

You can install the nightly build by following the docs here:

https://pnp.github.io/powershell/articles/installation.html
