### ISSUE TITLE
[FEATURE] Ability to publish content types

### ISSUE THREAD

**Issue by MDGH2021** [pnp/powershell#1456]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to publish SharePoint in 365 content types with Powershell. [Changes coming to Content type sync coming in January 2021](https://admin.microsoft.com/AdminPortal/home?#/MessageCenter/:/messages/MC295852) will make this very helpful.

**Describe the solution you'd like**
Method to publish a content type given we can create them with Add-PnPContentType and are expected to use Add-PnpContentTypesfromContentTypeHub to sync in the future. 

**Describe alternatives you've considered**
[This](https://social.technet.microsoft.com/Forums/sharepoint/en-US/cfb804fa-6cd1-4030-8bc6-3cf5ce6f90e2/how-can-you-publish-a-content-type-from-csom-on-sharepoint-online) is the only method I have found to programmatically publish content types for SharePoint in 365, it does not work with MFA. 

**Additional context**

**Comment by gautamdsheth** [comment]
Hi @MDGH2021 , we have added this cmdlet `Add-PnPContentTypesFromContentTypeHub`.

You can use that to publish your content types. 

https://pnp.github.io/powershell/cmdlets/Add-PnPContentTypesFromContentTypeHub.html

**Comment by MDGH2021** [comment]
> Hi @MDGH2021 , we have added this cmdlet `Add-PnPContentTypesFromContentTypeHub`.
> 
> You can use that to publish your content types.
> 
> https://pnp.github.io/powershell/cmdlets/Add-PnPContentTypesFromContentTypeHub.html

I tested this and it did not work. The content type was not published, it was also not added to the site. As well, I received the same error documented here: https://github.com/pnp/powershell/issues/1080

In that thread it is mentioned that despite receiving the error, the content type was still added to their site. It seems in the case of an unpublished content type it will not add.

**Comment by MDGH2021** [comment]
The documentation for the cmdlet is also contrary to your statement

**Adds published content types from content type hub site to current site.** 

**This will add the content types with the ids '0x0101' and '0x01' to the current site. Latest published version of these content types will be synced if they were already present in the current site.**

**Comment by gautamdsheth** [comment]
My bad , yeah the docs are correct.

you can push a CT from the hub to another site using that cmdlet. 

As for the original question, yeah we don’t have a specific CSOM or REST method for this , so unfortunately can’t implement it.

The social technet link that you posted contains.a hacky workaround which isn’t possible using current PnP authentication methods.
