### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by in8sanjc** [pnp/powershell#1458]
**PnP Search WebParts** 

PnP Search webparts are not in responsive design on large screens resolution

**Expected behavior**
These PnP Search webparts should be responsive design on large screens, and there should not be blank space on large 
screen resolution

**Actual behavior**
There are lot of blank space in right side of page in the large screen with PnP Search Webparts

**Steps to reproduce behavior**
 
![Issue](https://user-images.githubusercontent.com/61194822/146524900-f89e3fe3-9b4f-4754-939a-a4ef54c17bf9.JPG)

**What is the version of the PnP Web parts**
SPFx package version: 3.13

**Comment by gautamdsheth** [comment]
Hi @in8sanjc , please create the issue in this repository :

https://github.com/microsoft-search/pnp-modern-search/issues

This repo is for PnP PowerShell related issues

**Comment by in8sanjc** [comment]
Closing this and will create in right place for PnP Modern Search Community.
