### ISSUE TITLE
Move-PnpFile resulting in Access Denied

### ISSUE THREAD

**Issue by wil16098** [pnp/powershell#1461]
### Discussed in https://github.com/pnp/powershell/discussions/1447

<div type='discussions-op-text'>

<sup>Originally posted by **wil16098** December 14, 2021</sup>
Hello. Thank you for your hard work on this project. (especially @veronicageek - love the youtube channel). I am encountering the following errors when attempting to move the contents of a departed users OneDrive to a site library called 'PriorUsersOneDrive'. Each folder in PriorUsersOneDrive is named for the MailNickname of the user. Example: /sites/PriorUsersOneDrive/testuser if the email is testuser@mydomain.com. 
I am able to connect just fine. I can Find-PnPFile in both sites just fine. I can Add-PnPFile to both sites just fine. I am a Global Admin and Site Collection Admin for both sites and have added code to (I hope) reinforce that ($GlobalAdminEmail entered previously and MFA authenticating just fine). I am using PnP.Powershell (1.8.0). Here is my code. I am pretty confident I don't need all the connect statements, but was trying to make 100% sure I was hitting the right spot, and removing that bit doesn't help.
I have also included my resulting output and thank you in advance for any assistance on why I am receiving this access denied error. I am 100% certain it is user error on my part and appreciate any insights in advance :):

```    
    #SharePoint Online via SPO and PnP
        Connect-SPOService -Url https://$ClientOrg-admin.sharepoint.com
        Connect-PnPOnline -Url https://$ClientOrg.sharepoint.com -Interactive
    #Create the user's (name=email handle) folder in the Prior User's OneDrive Document Library using PnP.PowerShell (if it does not already exist)
        $PUODSite=Get-SPOSite -Identity https://$ClientOrg.sharepoint.com/sites/PriorUsersOneDrive
        Connect-PnPOnline -Url $PUODSite.Url -Interactive
        Resolve-PnPFolder -SiteRelativePath "Shared Documents/$($AADUserID.MailNickName)"
    #Make sure the GlobalAdmin is a Site Collection Admin, allowing you to do operations on the user's OneDrive
        $SourceAccount= Get-PnPUserProfileProperty -Account $userUPN
        $DestinationFolder= "sites/PriorUsersOneDrive/Shared Documents/$($AADUserID.MailNickName)"
        Set-SPOUser -Site $SourceAccount.PersonalUrl -LoginName $GlobalAdminEmail -IsSiteCollectionAdmin $true
        Set-SPOUser -Site $PUODSite.Url -LoginName $GlobalAdminEmail -IsSiteCollectionAdmin $true
    #Move the user's OneDrive files to the newly created Prior Users OneDrive folder named for them after connecting to the user's OneDrive folder        
        Connect-PnPOnline -Url $SourceAccount.PersonalUrl -Interactive
        Move-PnPFile -SourceUrl $SourceAccount.PersonalUrl -TargetUrl $DestinationFolder -AllowSchemaMismatch -AllowSmallerVersionLimitOnDestination -Force -Overwrite
```

Error text:
```
Move-PnPFile : Access denied.
At line:12 char:9
+         Move-PnPFile -SourceUrl $SourceAccount.PersonalUrl -TargetUrl ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Move-PnPFile], ServerUnauthorizedAccessException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Files.MoveFile
```
Again, finding and adding is working just fine:
```
Find-PnPFile -Folder $SourceAccount.PersonalUrl -match *.docx
Name                  Type Items/Size Last Modified         
----                  ---- ---------- -------------         
Test Document 1 .docx File            12/14/2021 10:54:17 PM
Document.docx         File            12/14/2021 10:51:33 PM
Test Document 2.docx  File            12/14/2021 10:54:40 PM
Test Document 3.docx  File            12/14/2021 10:54:55 PM

PS C:\WINDOWS\system32> Add-PnPFolder -Name "Folder1" -Folder "Documents"
Name    Type   Items/Size Last Modified        
----    ----   ---------- -------------        
Folder1 Folder          0 12/15/2021 3:42:39 AM
```
Both of the above were run against the user's current OneDrive successfully</div>

**Comment by wil16098** [comment]
I believe I have determined that what I am trying to do (move files and folders directly from a user's OneDrive to a company SharePoint site) cannot work using Move-PnPFile. 

TLDR - Move-PnPFile cannot support two separate connections at the same time. For this use case, two separate connections are required. One Connection for the user's OneDrive and one connection for the target SharePoint site. Therefore, a straight transfer between a user's OneDrive for Business and a company SharePoint site using Move-PnPFile is not possible. 
My current anticipated workaround will be to grab all the Source objects using a connection A, store locally, then upload to the Target using a different Connection B.

**I am upgrading this thread to an Issue to see if I can get verification or a better workaround.**

The OneDrive for Business folder exists at https://$ClientOrg-my.sharepoint.com/personal/testuser_clientdomain_com/Documents
The Target exists at https://$ClientOrg.sharepoint.com/sites/PriorUsersOneDrive/testuser

Those two domains appear to require two separate connections. So the following, using two separate connections, one for each command, works:
```
$siteA = Connect-PnPOnline -ReturnConnection -Url $SourceAccount.PersonalUrl -Interactive
$siteB = Connect-PnPOnline -ReturnConnection -Url $DestinationFolder -Interactive
Get-PnPListItem -List "Documents" -Connection $siteA
Get-PnPListItem -List "Documents" -Connection $siteB
```
However, Move-PnpFile has and uses only one connection parameter. Therefore, depending on which connection you are using, you will get 'access denied' or '404 not found', etc. based on the connection used. I believe this is because they are different domains:
clientorg-my.sharepoint.com
vs
clientorg.sharepoint.com
and Move-PnPFile will not take an entire url spelled out for each parameter and/or a connection to both domains.
So this does not work:
```
Connect-PnPOnline -Url $SourceAccount.PersonalUrl -Interactive
Move-PnPFile -SourceUrl "/sites/PriorUsersOneDrive/Shared Documents" -TargetUrl "/sites/Test/Shared Documents/TestXfer/testuser"
```
But this does:
```
Connect-PnPOnline -Url $PUODSite.Url -Interactive
Move-PnPFile -SourceUrl "/sites/PriorUsersOneDrive/Shared Documents" -TargetUrl "/sites/Test/Shared Documents/TestXfer/testuser"
```
I would very much love to have someone confirm my suspicion is correct, confirm the proposed workaround is correct, or tell me an elegant way to solve this puzzle. @veronicageek or anyone?
Microsoft is doing it in 'one step' via the GUI, so i am hoping there is a way :)

**Comment by veronicageek** [comment]
Thanks @wil16098 for the comments about the channel 🙂

With regards to to your issue, indeed I believe this can't be done at the moment with PnP. But have a look at the following discussion (with code snippet) which might help: https://github.com/pnp/powershell/discussions/620#discussioncomment-717269
