### ISSUE TITLE
[BUG]  Sync-PnPSharePointUserProfilesFromAzureActiveDirectory does not run in Azure Runbook

### ISSUE THREAD

**Issue by aThuemmel** [pnp/powershell#1465]
### Reporting an Issue or Missing Feature
An issue about  Sync-PnPSharePointUserProfilesFromAzureActiveDirectory cmdlet

### Expected behavior 
I run a simple cmdlet/script in Local PowerShell, there it runs without a problem. The exat same script in the azure runbook throws an error. In Local PowerShell it works fine, json file is generated and the properties are succesfully synced. ADBulKImport shows the Job. Running on Azure does not even create the job.

### Actual behavior 
I get the error: 
`Sync-PnPSharePointUserProfilesFromAzureActiveDirectory : An item with the same key has already been added. At line:54 char:1 + Sync-PnPSharePointUserProfilesFromAzureActiveDirectory -UserProfilePr ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : WriteError: (:) [Sync-PnPSharePo...ActiveDirectory], ArgumentException + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.UserProfiles.SyncSharePointUserProfilesFromAzureActiveDirectory`

### Steps to reproduce behavior
Register an Azure App, connect to pnp by certificate and run the Sync-PnPSharePointUserProfilesFromAzureActiveDirectory cmdlet

### What is the version of the Cmdlet module you are running?
1.8.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [X] Azure Cloud Shell
- [ ] Azure Functions

Local works fine:
![image](https://user-images.githubusercontent.com/43062820/146929045-ac17cd87-fba7-4185-b504-1ca9e6e5fd20.png)
![image](https://user-images.githubusercontent.com/43062820/146929138-717cb496-e686-4514-af09-198be4e59eda.png)

Copy´n Pasted the exact same script to azure runbook:
![image](https://user-images.githubusercontent.com/43062820/146929432-d7c8b775-f761-4d18-a020-d9c5d8d53687.png)
![image](https://user-images.githubusercontent.com/43062820/146929934-73dbd5d3-85d3-4ee0-98cd-9177f56ba365.png)

I already tried to use a different Document Library -> not successful
I reduced the properties to a single one -> not successful

But there is not much i can change or try, because its not really a script, it is just this single command.

**Comment by gautamdsheth** [comment]
Can you try it as below and store it in a variable and let us know ?

$value = Sync-PnPSharePointUserProfilesFromAzureActiveDirectory 

Closing it because it works locally, so we can’t do anything else. 

Not an issue with PnP module but maybe a quirk with Azure automation.

**Comment by aThuemmel** [comment]
To write it in an variable has not resolved the issue. I updated the Module du the newest build (i think 1.9.0.0) and imported the Module in the Preview Runtime Version 7.1, also recreated the runbook with the runtime version 7.1. Now it works like a charm.
