### ISSUE TITLE
Add-SPOOrgAssetsLibrary Getting "Access Denied"

### ISSUE THREAD

**Issue by Ukiman1014** [pnp/powershell#1466]
### Discussed in https://github.com/pnp/powershell/discussions/1454

<div type='discussions-op-text'>

<sup>Originally posted by **Ukiman1014** December 16, 2021</sup>
We are trying to set up Organizational Assets but cannot get the command to add a library to complete.  

`Connect-SPOService -Url "https://COMPANY-admin.sharepoint.com" Add-SPOOrgAssetsLibrary -LibraryURL https://COMPANY.sharepoint.com/sites/LIBRARY_URL -ThumbnailURL https://COMPANY.sharepoint.com/sites/JPG_IMAGE_URL -OrgAssetType ImageDocumentLibrary`

- Executing user is a global admin
- User has full control to the site and library
- "Everyone except external users" has read access to the library
- User can successfully execute `Set-SPOTenantCdnEnabled -CdnType Private -Enable $true`, so it does not seem to be an error enabling a private CDN.

* Our SharePoint is NOT open to external access.  Might this have something to do with it?  I wouldn't think so, if it only uses a private CDN.

How can we troubleshoot exactly what's causing "access denied"?

Res
![OrgAssetsError](https://user-images.githubusercontent.com/22643106/146415831-7ca0f066-438c-45f2-bd02-2ef392560e30.png)
t</div>

**Comment by gautamdsheth** [comment]
Hi seems like a tenant specific issue, please keep it open in discussion section since you are asking a question. 

Secondly, you are using SPO management shell, this is a module for PnP related stuff.

**Comment by Ukiman1014** [comment]
Okay, thank you.  I first went to Microsoft but they said they don't support the open source SharePoint shells and directed me here.  Sorry about the PnP post - I'm just not that familiar with this.

**Comment by gautamdsheth** [comment]
Hi no worries!

They are obviously wrong on this.
Would suggest that you reopen the ticket.
Tell them that the issue is happening in SPO management shell. It is a first party application and supported by Microsoft. They also have SLA. It is not open source.

PnP is open source , driven by volunteers and not supported by Microsoft support.

**Comment by Ukiman1014** [comment]
Thank you for the clarification!  I'll go ahead and reopen the ticket 👍🏻.
