### ISSUE TITLE
[BUG] - `Set-PnPSearchConfiguration` never updates existing managed properties

### ISSUE THREAD

**Issue by NikCharlebois** [pnp/powershell#1467]
Looks like this may have fell through the cracks:
https://github.com/pnp/PnP-PowerShell/issues/2986

Calling the Set-PnPSearchConfiguration cmdlet never updates existing managed properties. It doesn't give any errors, just doesn't update. We are trying to change, for example, the Searchable value on an existing property from true to false.

### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
Try to update an existing Search Managed Property with Set-PnPSearchConfiguration

### Actual behavior 
Nothing gets updated

### Steps to reproduce behavior
Run Set-PnpSearchConfiguration and try to update a managed property

### What is the version of the Cmdlet module you are running?
1.8.0

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Hi @NikCharlebois , can you try reproduce the issue by manually uploading the xml in the search admin center ? 

If so, would suggest that you open a ticket with Microsoft support since that would be an issue with the API itself and not the cmdlet.

check this issue : 

https://github.com/pnp/powershell/issues/1328

**Comment by NikCharlebois** [comment]
It does on other tenants. Looks like the problem for the tenant in question was due to its SearchConfig list at the admin center level having been deleted somehow.
