### ISSUE TITLE
[BUG] Set-PnPWebTheme failing for custom themes

### ISSUE THREAD

**Issue by TheInvoker** [pnp/powershell#1473]
### Reporting an Issue or Missing Feature
Getting 403 forbidden when running Set-PnPWebTheme with a custom theme.

### Expected behavior 
Should change the theme to a custom one.

### Actual behavior 
Gets an error message. It works with an out of the box theme though like this
`Set-PnPWebTheme -Theme "Teal"`

### Steps to reproduce behavior
`Set-PnPWebTheme -Theme "My Theme"`

```
Set-PnPWebTheme : The remote server returned an error: (403) Forbidden.
At C:\GitHub\Templates\test.ps1:20 char:1
+ Set-PnPWebTheme -Theme "My Theme"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPWebTheme], WebException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Branding.SetWebTheme
```

### What is the version of the Cmdlet module you are running?
1.9.0

### Which operating system/environment are you running PnP PowerShell on?
Windows 10

**Comment by gautamdsheth** [comment]
Hi you need to connect to the SharePoint admin site collection for this cmdlet to run.

So, it needs to be 

connect-PnPonline https:// < tenant-admin >.sharepoint.com 

and then execute the set-PnPwebtheme cmdlet

you need to be a SharePoint/Tenant admin for this to run.

Not a issue with the module, closing it

**Comment by TheInvoker** [comment]
If I connect to the admin center, then how do I apply the theme to a specific site collection like this?

https:// < tenant-admin >.sharepoint.com/sites/mysite

**Comment by gautamdsheth** [comment]
#Parameters
$AdminCenterURL = "https://tenant-admin.sharepoint.com"
$SiteURL = "https://tenant.sharepoint.com/sites/marketing"
$ThemeName = "My Theme"
  
#Connect to Admin Center
Connect-PnPOnline -Url $AdminCenterURL
  
#Apply Theme to Web
Set-PnPWebTheme -Theme $ThemeName -WebUrl $SiteURL

**Comment by TheInvoker** [comment]
How come with out of the box themes like Teal, you don't need to be connected to the admin center?

**Comment by gautamdsheth** [comment]
You will have to ask Microsoft product group on why they designed it this way for programmatically applying themes.

**Comment by TheInvoker** [comment]
I see. But in an earlier version of pnp powershell, I could set the theme to a custom one using pnp powershell. Did Microsoft change it afterwards?
