### ISSUE TITLE
[BUG] Unable to execute connect-pnponline command using azure kudu powershell tool or azure webjobs

### ISSUE THREAD

**Issue by kaushalbcactus** [pnp/powershell#1479]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

### Reporting an Issue or Missing Feature
I am unable to connect pnponline in azure environment.
I installed modules folder and referenced it using import statement but still getting error

The Win32 internal error "The handle is invalid" 0x6
PS C:\home\Modules> occurred while setting character attributes for the console output buffer.
Contact Microsoft Customer Support Services.

Below are set of code/steps which i tried to execute

### Expected behavior 
Connect and return context of sharepoint site 

### Actual behavior 
Below Error
![image](https://user-images.githubusercontent.com/49706885/147661825-7050ce2a-d6cc-4447-99c3-cfb9d6f0047a.png)

### Steps to reproduce behavior
1. Login to Azure portal and create azure function app
2. Create function with app 
3. Go to azure function app and then development tools => then go to open kudu tool of azure
2. Copied SharePointPnPPowerShellOnline modules folder to modules folder in azure c:\home
2. executed below commands
`$MyModulePath="D:\home\Modules\SharePointPnPPowerShellOnline"
$env:PSModulePath = $env:PSModulePath + "$([System.IO.Path]::PathSeparator)$MyModulePath"`

3. Import-Module SharePointPnPPowerShellOnline
4. Then executed below commands:-
     `$emailId = 'ABC'     
      $password =  'XYZ'   
      $SecurePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
      $Cred = New-Object -TypeName System.Management.Automation.PSCredential -argumentlist $emailId, $SecurePassword
    #Connect to PNP Online
    Connect-PnPOnline -Url $SiteURL -Credentials $Cred`
5. Error when executing last command. i.e. `Connect-PnPOnline` -Url $SiteURL -Credentials $Cred`
### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
3.29.2101.0

![image](https://user-images.githubusercontent.com/49706885/147664243-01f10f9e-f237-4f1b-998d-87622721161c.png)

### Which operating system/environment are you running PnP PowerShell on?
- [Yes ] Azure Functions

**Comment by gautamdsheth** [comment]
Hi, SharePointPnPPowerShellOnline module is deprecated now, it will not work in Azure functions especially the newer versions.

Basically you need to create an Azure AD app first and rest of it is pretty much the same.

This repo is for the newer PnP.PowerShell module. Please read these article on how to migrate to this newer module and make the changes accordingly.

https://pnp.github.io/powershell/articles/upgrading.html

https://pnp.github.io/powershell/articles/azurefunctions.html

https://pnp.github.io/powershell/articles/authentication.html
