### ISSUE TITLE
[BUG] Stored Credentials don't work with PowerShell 7

### ISSUE THREAD

**Issue by ToddKlindt** [pnp/powershell#1482]
### Reporting an Issue or Missing Feature
Neither Connect-PnPOnline or Get-PnPStoredCredential are able to retrieve credentials from the Windows Credential Store.
### Expected behavior 
I expect those cmdlets to retrieve credentials when used with PowerShell 7.

### Actual behavior 
![image](https://user-images.githubusercontent.com/2659747/147831126-4135dc60-85a3-471f-a4ab-2c2e86a71f8e.png)

### Steps to reproduce behavior
1) Verify a stored credential exists either in Windows PowerShell 5 or the Credential Manager control panel applet.
2) Try to retrieve those credentials with either Get-PnPStoredCredential or Connect-PnPOnline in PowerShell 7.

### What is the version of the Cmdlet module you are running?
1.9.0 and Windows 11, though I see this problem on Windows 10 also.

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Strange, cant repro it on Win 10. Code behind this hasn't changed at all since the beginning. Don't have Win 11 , not sure what's going on here ☹

**Comment by veronicageek** [comment]
@ToddKlindt @gautamdsheth 

I have tested on Win11 and MacOS with PowerShell Core `7.2.1` and have no issue (perso tenant or MSFT Demo tenant).
Maybe try to remove those creds and re-add them.

![image](https://user-images.githubusercontent.com/25181757/147835607-b9f8985f-e835-4416-9b6b-905289ac8c86.png)

![image](https://user-images.githubusercontent.com/25181757/147835611-ade74fab-b8c5-48da-9c98-4ee3dbf2a9a7.png)

![image](https://user-images.githubusercontent.com/25181757/147835718-484483f8-fae0-4684-b6bb-323ad33244ac.png)
