### ISSUE TITLE
Invoke-PnPSiteTemplate throws error

### ISSUE THREAD

**Issue by in8sunpa** [pnp/powershell#1486]
### Discussed in https://github.com/pnp/powershell/discussions/1485

<div type='discussions-op-text'>

<sup>Originally posted by **in8sunpa** January  3, 2022</sup>
Executing Invoke-PnpSiteTemplates to provision a site gives below warnings:

WARNING: Provisioning of the navigation node failed, retrying for : Claims
WARNING: Provisioning of the navigation node failed, retrying for : Others

</div>

**Comment by veronicageek** [comment]
Please open an issue by filling the template.
