### ISSUE TITLE
[BUG] Get-PnPFolderItem not allowing "Type" to be returned

### ISSUE THREAD

**Issue by GP-BCN** [pnp/powershell#1490]
Hi,

We have recently been writing some PowerShell scripts to loop around SharePoint libraries, folders and documents to pull out any that have unique permissions, and write those out to a file.  To get around the the 5000 item limit we are using the Get-PnPFolderItem commandlet in recursive mode.

### Expected behaviour 
After setting an $items array, the item itself returns a property of "Type" (i.e. File or Folder) that should be addressable and written to screen or file.

### Actual behaviour 
Writing out $item.Type within a foreach loop fails to return the text "File" or "Folder".

### Steps to reproduce behaviour

1. Create an $items object
2. Set that object using Get-PnPFolderItem
3. Use a foreach loop to loop around each $item in $items
4. Write to host, $item.Type

Sample code as follows:

`$items = Get-PnPFolderItem -FolderSiteRelativeUrl "TestLibrary" -Recursive -ItemType All`
`foreach ($item in $items) {`
`  Write-Host "Type = $($item.Type)"`
`}`

If you use the following, you can see that "Type" is a part of the object:

`$items = Get-PnPFolderItem -FolderSiteRelativeUrl "TestLibrary" -Recursive -ItemType All`
`Write-Output $items`
`}`

We have tried $item.Type, $item.ItemType, $item.FileSystemObjectType, and none have returned what we would expect.  Instead we just get blank/null returned.  Am not sure if this is a bug or we are using the wrong property name.  Any help/advice would be much appreciated.

### What is the version of the Cmdlet module you are running?
1.9.0

### Operating system
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

### Environment
- [x] Office 365/SharePoint Online
- [ ] SharePoint 2016
- [ ] SharePoint 2013

**Comment by LeonArmston** [comment]
Hi

I think this is how I would do it - you need to access the $item.TypedObject.TypedObject property

```powershell
$items = Get-PnPFolderItem -FolderSiteRelativeUrl "Shared Documents" -Recursive -ItemType All
foreach ($item in $items) {
    Write-Host "Type = $($item.TypedObject.TypedObject)"
    Write-Host "Replace String: "$($item.TypedObject.TypedObject -replace "Microsoft.SharePoint.Client.","")
}
```
![image](https://user-images.githubusercontent.com/12968962/148367885-bb857d09-ce88-4104-ab1d-55ada9b9edf4.png)

Which then gives Microsoft.SharePoint.Client.File or Microsoft.SharePoint.Client.Folder - you could then do a replace to remove Microsoft.SharePoint.Client. from the string to get File or Folder.

I'd hazard a guess the PnP Cmdlets do something similar in the background - but happy to be proven wrong...

**Comment by GP-BCN** [comment]
Thanks @LeonArmston that worked.  Not sure why the commandlet isn't doing that, but, your workaround has achieved the desired result 👍
