### ISSUE TITLE
[BUG] Parameter Folder not working for Sync-PnPSharePointUserProfilesFromAzureActiveDirectory

### ISSUE THREAD

**Issue by EA12** [pnp/powershell#1495]
### Expected behavior 
The Cmdlet Sync-PnPSharePointUserProfilesFromAzureActiveDirectory should work with the parameter -folder

### Actual behavior 
The Cmdlet shows following error:
Folder User Profile Sync to upload the user profile update file to does not exist on SharePoint Online in the site https://ourtenant.sharepoint.com/

The [documentation](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/sync-pnpsharepointuserprofilesfromazureactivedirectory?view=sharepoint-ps) says it should be the site relative name of the folder or library of the connected site. I tried also with -Folder "/User Profile Sync" and got the same error.

Additional finding: If I do not use the folder parameter, I get following error message:
Folder /Shared Documents to upload the user profile update file to does not exist on SharePoint Online in the site https://ourtenant.sharepoint.com/

Please note, that this is a german site, so the library name is "Freigegebene Dokumente"

### Steps to reproduce behavior
Create a library called "User Profile Sync" at the root site of the tenant.
Connect to PnP-Online to the tenant
Determine users by `$users = Get-PnPAzureADUser`
Call `Sync-PnPSharePointUserProfilesFromAzureActiveDirectory -WhatIf -Users $users -Folder "User Profile Sync" -UserProfilePropertyMapping @{"..."}`

UserProfilePropertyMapping has been shortend here.

### What is the version of the Cmdlet module you are running?
1.9.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [x ] Other : App Registration with Service Principle, using in Azure RunBook

**Comment by EA12** [comment]
I had a look into the code.
You can find hard coded default folder which is not aware of languages in class
`SyncSharePointUserProfilesFromAzureActiveDirectory : PnPSharePointCmdlet`

`[Parameter]
	public string Folder = "Shared Documents";`

The MoveNext method from this struct
`private struct <SyncFromAzureActiveDirectory>d__0 : IAsyncStateMachine`

has following code which is raising the mentiond error:

string text = ClientObjectExtensions.EnsureProperty<Web, string>(clientContext.get_Web(), 
    (Expression<Func<Web, string>>)((Web w) => w.get_ServerRelativeUrl()));

if (!sharePointFolder.ToLower().StartsWith(text)) {
    sharePointFolder = UrlUtility.Combine(text, sharePointFolder);
}
if (!FileFolderExtensions.DoesFolderExists(clientContext.get_Web(), sharePointFolder)) {
    throw new InvalidOperationException("Folder " + sharePointFolder +
     " to upload the user profile update file to does not exist on SharePoint Online in the site " + clientContext.get_Url());
}

So, in my case variable text should be just a slash "/"
As my Folder-parameter value was just "User Profile Sync", it should be combined to "/User Profile Service"

But this has not happend, because the variable sharePointFolder in the error message has no slash.
DoesFolderExists then expects a serverRelativeFolderUrl. - Boom!
`public static bool DoesFolderExists(this Web web, string serverRelativeFolderUrl)
`
So it seems that w.get_ServerRelativeUrl() does not return a slash when we are talking about the root site of the tenant.

Is my analysis correct, or am I missing something.
Can you please fix this? - Thanks a lot, Ronny

**Comment by EA12** [comment]
Somebody from the contributors? - Please help

**Comment by KoenZomers** [comment]
Thanks guys for reporting this. Let me try to understand where things go wrong here.

**Comment by KoenZomers** [comment]
I cannot fully reproduce the issue being described here. Possibly because since reporting there have been updates to the cmdlet already. I can confirm that if you omit `-Folder`, it will assume a library `Shared Documents` to exist. If you are using a non English site collection, this may be named differently. From code we have no easy, reliable way to find out about the localized name of the default document library. I have updated the documentation on this cmdlet to provide further details around the -Folder parameter. Every test I've done passing in a custom document library or folder inside any document library works here.

@EA12, @schneika, please take the latest PnP PowerShell version using `Install-Module PnP.PowerShell -AllowPreRelease -Force` and try this again to see if it works well for you now. If it still does not, please provide further steps how to reproduce this.

**Comment by EA12** [comment]
Hi Koen,
thanks for coming back.
Currently, I am in a discussion with the security teams of my customer to install the mentioned pre-release version of PnP.PowerShell (for the moment, they do not allow this). I will post my findings as soon as I can.

Regarding: Localized "Shared Documents"-Library:
As there is no method to determine this, you could write your own.
You could have a static method to return the localized shared librray name with a parameter reflecting the current localeid from RegionalSettings.LocaleId of the current web from Microsoft.SharePoint.Client.dll.

e.g.
    `public static string GetLocalizedNameOfSharedLibrary(uint localeId)
      {
            string retval = "";

            switch (localeId)
	        {
                case 1031:
                {
                    retval = "Gemeinsame Dokumente";
                    break;
                }
                case 1033:
                {
                    retval = "Shared Library";
                    break;
                }
                case 1029:
                {
                    retval = "Společné dokumenty";
                    break;
                }
		        default:
                    retval = "Shared Library";
                    break;
	        }

            return retval;
        }`

Regards, Ronny

**Comment by KoenZomers** [comment]
Thanks for sharing your thoughts. That could work, although I'm not sure if in the end that will a very elegant solution. We would need a way to ensure we cover all languages. Microsoft is going to support around 89 languages by the end of this year, so that may be quite a task. I believe some languages stick with the English naming, too. It would also require an extra API call to check for the language setting. Not sure if all of this is worth the effort, to be honest. What would there be against providing a folder manually using the `-Folder` attribute?

**Comment by EA12** [comment]
I totally agree.
Nothing against the -Folder parameter as long as it works :)
Do you know when the mentioned fix will be available in a release (not pre release)?

**Comment by EA12** [comment]
In the meantime, I was allowed to install the latest pre-release to Azure which I did and which succeeded: 1.9.59 ist installed and assigned to the related automation account

![image](https://user-images.githubusercontent.com/22025808/156218860-2764bf04-c877-4455-a954-c9ac33aa6e8d.png)

CmdLet "Sync-PnPSharePointUserProfilesFromAzureActiveDirectory" **still not working** with or without folder parameter.
I double checked the requirements from [here](https://docs.microsoft.com/de-de/powershell/module/sharepoint-pnp/sync-pnpsharepointuserprofilesfromazureactivedirectory?view=sharepoint-ps).
Especically User Profile property settings and Tenant Full Control ACS permission.

When using -Folder UserProfileSync
I get: Folder /sites/1-Z-UPS/UserProfileSync to upload the user profile update file to does not exist on SharePoint Online in the site https://mytenant.sharepoint.com/sites/1-Z-UPS

When using no folder parameter I get: Folder /sites/1-Z-UPS/Shared Documents to upload the user profile update file to does not exist on SharePoint Online in the site https://mytenant.sharepoint.com/sites/1-Z-UPS

So, this ist still not fixed, not even in this pre-release.
Could you please assist? - We are stuck with syncing. - Thanks, Ronny

**Comment by KoenZomers** [comment]
> Any news about the release? Until now I am still not allowed to install a pre release and I got stuck with syncing.

We've received multiple reports of the `New-PnPTeamsTeam` cmdlet not working well anymore in the latest prerelease, but none of us are able to reproduce it. Since it's a cmdlet which is used a lot, we need to try to figure it out before we can do a new release.

> So, this ist still not fixed, not even in this pre-release.

This one falls under the same category, it works fine here. There must be a specific condition which causes this. Let me try once again to see if I can reproduce this. The variables I'm aware of that play a role for you now are it being a German site collection and the sitecollection name using dashes. If there's anything else that you think could play a role, please share.

**Comment by KoenZomers** [comment]
I'm still not able to reproduce the issue. Works fine locally with the latest prerelease version and works fine in an Azure Runbook using stable version 1.9.0. I'm using this script in the Azure Runbook:

```powershell
$certificate = Get-AutomationCertificate -Name "certificate"
$clientId = Get-AutomationVariable -Name "ClientId"
$tenantName = Get-AutomationVariable -Name "TenantName"
$pfxPassword = Get-AutomationVariable -Name "PfxPassword"
$base64Cert = [System.Convert]::ToBase64String($certificate.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Pkcs12))

Connect-PnPOnline -Url https://$tenantName.sharepoint.com/sites/1-Z-UPS -ClientId $clientId -CertificateBase64Encoded $base64Cert -Tenant "$tenantName.onmicrosoft.com"

$users = Get-PnPAzureADUser
Sync-PnPSharePointUserProfilesFromAzureActiveDirectory -Users $users -WhatIf -UserProfilePropertyMapping @{"Id"="Id"} -Folder "UserProfileSync"
```

![image](https://user-images.githubusercontent.com/5940670/156262652-07715215-304d-4618-831d-1ac2f9fee13b.png)

Sitecollection has been created in German. The default document library is available under `/sites/1-Z-UPS/Freigegebene%20Dokumente/Forms/AllItems.aspx`

What can you spot that you are doing different that may cause it not to work for you?

**Comment by EA12** [comment]
Hi Koen,

first of all, thank you very much for your outstanding support.
For somehow reason, the security department rejected the Sites.ReadWrite.All permission from the app registration. That was causing the previous mentioned error.
After the security approved the consent again, I got it to work.
I am using this script

```
$serviePrincipalName = 'ZZZ-SPOScript'
$servicePrincipalConnection=Get-AutomationConnection -Name $serviePrincipalName
$clientId = $servicePrincipalConnection.ApplicationID 
$tenantName = "ourtenant"

Connect-PnPOnline -Url "https://ourtenant.sharepoint.com/sites/1-Z-UPS" -ClientId $clientId -Thumbprint $servicePrincipalConnection.CertificateThumbprint -Tenant "$tenantName.onmicrosoft.com"
$users = Get-PnPAzureADUser -Select "Id,mail,UserPrincipalName,companyName,extension_b8fc35d8e8ec45e689d332303177957a_ZZZ_townCode,extension_b8fc35d8e8ec45e689d332303177957a_ZZZ_costNumber,extension_b8fc35d8e8ec45e689d332303177957a_employeeID,extension_b8fc35d8e8ec45e689d332303177957a_employeeNumber,extension_b8fc35d8e8ec45e689d332303177957a_ZZZ_title,extension_b8fc35d8e8ec45e689d332303177957a_ZZZ_office,extension_b8fc35d8e8ec45e689d332303177957a_extensionAttribute6,extension_b8fc35d8e8ec45e689d332303177957a_extensionAttribute7" | Where-Object { $_.AdditionalProperties["extension_b8fc35d8e8ec45e689d332303177957a_ZZZ_townCode"] -ne $null } 
Sync-PnPSharePointUserProfilesFromAzureActiveDirectory -Folder "UserProfileSync" -WhatIf -Users $users -UserProfilePropertyMapping @{"ZZZ-TownCode"="extension_b8fc35d8e8ec45e689d332303177957a_ZZZ_townCode";"ZZZ-CostNumber"="extension_b8fc35d8e8ec45e689d332303177957a_ZZZ_costNumber";"employeeID"="extension_b8fc35d8e8ec45e689d332303177957a_employeeID";"employeeNumber"="extension_b8fc35d8e8ec45e689d332303177957a_employeeNumber";"ZZZ-Title"="extension_b8fc35d8e8ec45e689d332303177957a_ZZZ_title";"ZZZ-Office"="extension_b8fc35d8e8ec45e689d332303177957a_ZZZ_office";"extensionAttribute6"="extension_b8fc35d8e8ec45e689d332303177957a_extensionAttribute6";"extensionAttribute7"="extension_b8fc35d8e8ec45e689d332303177957a_extensionAttribute7";"Company"="companyName"}  
 
```

Thanks, Ronny
