### ISSUE TITLE
[BUG] Get-PnPMicrosoft365Group (No Parameters) retrieves non-MS365 groups

### ISSUE THREAD

**Issue by Chris-CMing** [pnp/powershell#1496]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
When executing a blank request (Get-PnPMicrosoft365Group), both MS365 and non-MS365 groups are returned.

In the code behind the Powershell command in use is ~~~Identity.GetGroup~~

### Expected behavior 
Only MS365 groups should be returned.

### Actual behavior 
All groups are returned.

### Steps to reproduce behavior
Get-PnPMicrosoft365Group

### What is the version of the Cmdlet module you are running?
1.9.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
hi this issue has been fixed now !
Please try with the latest nightly which will be available from tomorrow !
