### ISSUE TITLE
Missing function for fetching group members using msal token[BUG]

### ISSUE THREAD

**Issue by kaushalbcactus** [pnp/powershell#1500]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

### Reporting an Issue or Missing Feature
Missing or unable to find function to fetch group members using MSAL token and  'Get-AzureADGroupMembers' does not work since  it works for aad graph access only and not on msal graph access.

### Expected behavior 
Should have function to fetch groupmembers using msal token.

### Actual behavior 
Unable to fetch members of group and failed with error....i will share error screenshot soon

### Steps to reproduce behavior
`$azureAplicationId = "xxx"
        $azureTenantId = "xxx"
        $azurePassword = ConvertTo-SecureString "xxx" -AsPlainText -Force
        $psCred = New-Object System.Management.Automation.PSCredential($azureAplicationId , $azurePassword)
        Connect-AzAccount -Credential $psCred -Tenant $azureTenantId -ServicePrincipal

        $context = [Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureRmProfileProvider]::Instance.Profile.DefaultContext
        $aadToken = [Microsoft.Azure.Commands.Common.Authentication.AzureSession]::Instance.AuthenticationFactory.Authenticate($context.Account, $context.Environment, $context.Tenant.Id.ToString(), $null, [Microsoft.Azure.Commands.Common.Authentication.ShowDialog]::Never, $null, "https://graph.windows.net").AccessToken
        $connectionDetails = @{
            'TenantId'     = 'xxx'
            'ClientId'     = 'xxx'
            'ClientSecret' = 'xxx' | ConvertTo-SecureString -AsPlainText -Force
        }

        $mstoken = Get-MsalToken @connectionDetails
        Connect-AzureAD -AadAccessToken $aadToken -MsAccessToken $mstoken.AccessToken -AccountId $context.Account.Id -TenantId $context.tenant.id;
        $group = Get-AzureADMSGroup -Filter "Mail eq 'xxx'" # where xxx is group email id
        $groupMembers += Get-AzureADGroupMember -ObjectId $group.Id `

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

1.9.0

### Which operating system/environment are you running PnP PowerShell on?
- [ yes] Windows
- [ yes] Azure Functions

**Comment by kaushalbcactus** [comment]
@veronicageek ` $groupMembers += Get-AzureADGroupMember -ObjectId $group.Id ` is cmdlet of pnp which i verified from https://github.com/pnp/powershell/tree/master/src/Commands/AzureAD

**Comment by veronicageek** [comment]
The cmdlets have the `-PnP` prefix. Not knowing your error message, have you tried with the `Get-PnPAzureADGroupMember`?

Documentation of all PnP cmdlets: https://github.com/pnp/powershell/tree/dev/documentation

**Comment by kaushalbcactus** [comment]
No I didnt tried it yet....since I was using Get-AzureADGroupMember and unaware of PNP version ....I am not at my workplace so I will update here tomorrow if this resolves my issue.....thanks for suggestion

so can you please also suggest if 'Get-AzureADGroupMember' is deprecated?

**Comment by veronicageek** [comment]
@kaushalbcactus - The `Get-AzureADGroupMember` is not deprecated but is **not** part of the PnP PowerShell module (this repo). I could see in your snippet that you were connecting to the AzureAD module, hence my question about not seeing any PnP cmdlets in your issue.

So if you have a problem with the `Get-AzureADGroupMember` (Microsoft AzureAD module), you should open an issue in the Microsoft repos: https://github.com/AzureAD?language=powershell

I think you've mistaken repos.

**Comment by kaushalbcactus** [comment]
Hi Veronica,

I tried connecting pnp to my azure tenant with registered app client id and client secret but when I used GetPNPAzureADGroup it is throwing below error

![image](https://user-images.githubusercontent.com/49706885/149085429-6d79ba4d-a429-4cff-95fc-cf88a5c65b18.png)

Code:-
Connect-PnPOnline -Url $env:siteurl  -Realm 'xxx(TenantID)' -ClientId 'xxx' -ClientSecret 'xxx' 
Get-PnPAzureADGroup

**Comment by kaushalbcactus** [comment]
Hi @veronicageek 

I changed my implementation to PnPazureadgroup and worked. 
Thanks for your input. Appreciate your help.
