### ISSUE TITLE
[BUG] Sync-PnPSharePointUserProfilesFromAzureActiveDirectory cannot handle special signs like Ü,Ä,Ö

### ISSUE THREAD

**Issue by aThuemmel** [pnp/powershell#1501]
### Reporting an Issue or Missing Feature
Special Signs like you have in Nürnberg (-> ü)  show up in the userprofile as wrong encoding.
### Expected behavior 
The cmdlet itself works without an error.

### Actual behavior 
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/43062820/148788606-3f35cb32-8770-4e7a-8559-7d6739f53103.png)

Special Signs like ß,Ü,ü,Ö,ö etc. do not work (but in germany they are so often used).

### Steps to reproduce behavior
$connection = Connect-PnPOnline -Url $spourl -Tenant *****onmicrosoft.com -ClientId "**************" -thumbprint "**************"

$sync = Sync-PnPSharePointUserProfilesFromAzureActiveDirectory -UserProfilePropertyMapping @{"Street"="StreetAddress";"Company"="CompanyName";"Location"="City";"ZIP-Code"="PostalCode";"CellPhone"="Mobile";"Pager"="extension_3d7216cb6e624d74b9c87434f80aea59_pager";"Fax"="FacsimileTelephoneNumber";"Division"="extension_3d7216cb6e624d74b9c87434f80aea59_division"} -Folder "User Profile Sync" 

### What is the version of the Cmdlet module you are running?
1.9.0.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [X] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

I executed this in my own Shell and in Azure runbook. Both executions get the same result.

Maybe integrate a paramater to assign an encoding, i think utf-8 should do it. 
![2022-01-10 16_10_37-UTF-8 – Wikipedia](https://user-images.githubusercontent.com/43062820/148789146-1d15f50d-f7bc-4fed-8d3e-e9f7c524af15.png)

**Comment by EA12** [comment]
May be it helps, if you tell your Shell to do so? - [See ](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parameters_default_values?view=powershell-7.2)

`$PSDefaultParameterValues['*:Encoding']='utf8'`

**Comment by aThuemmel** [comment]
I think the way from Azure AD into that json file is corrrect, because in  the json file everything is written corrrect. Transfer into the user prrofile is what ais not working correctly.

**Comment by EA12** [comment]
Are you able to donwload the json file from the library?
Get-pnpfile -Url "/User Profile Sync/userprofilesyncdata-20220111101720-guidWithoutHyphens.json"
Is the output OK?
Is the output OK if you download the file manually and view it in Notepad++ ?

**Comment by EA12** [comment]
BTW: I wonder that the -Folder parameter seems to work for you. I was without luck. See [here](https://github.com/pnp/powershell/issues/1495)

**Comment by aThuemmel** [comment]
Output in Chrome, Edge and Notepad++ (if UTF-8 is selected, which is default on my side) is correct. Of course if i switch to code to ANSI it looks like this

`"Location":"NÃ¼rnberg"`

**Comment by aThuemmel** [comment]
Because it is not really a folder, ment is a document library.

**Comment by EA12** [comment]
Regarding -Folder parameter: Yes, of course it is a library in my case ("User Profile Sync")

**Comment by aThuemmel** [comment]
Can this be fixed by a update? I dont see the possibility for me to manually fix it while synchronising. Only workaroundn i can think is to go through all profiles and update wrong entries by another script (which then have to run also daily)

**Comment by schneika** [comment]
We observe the same behavior. The Sync-PnPSharePointUserProfilesFromAzureActiveDirectory Commandlet is not working with national Charakters. No proper UTF8-Encoding.

**Comment by KoenZomers** [comment]
Thanks guys for reporitng this. Let me try to reproduce it on my end.

**Comment by KoenZomers** [comment]
I can reproduce it. Let me see how this can be fixed.

**Comment by KoenZomers** [comment]
Fixed! Will be available in the prerelease version of PnP PowerShell of February 15, 2022 at 3 AM Central European Time onwards.

PR reference https://github.com/pnp/powershell/pull/1634
