### ISSUE TITLE
[BUG] (Get-PnPTenantSite).IsHubSite always returns False.

### ISSUE THREAD

**Issue by DmitryVorobyov** [pnp/powershell#151]
### Reporting an Issue or Missing Feature
(Get-PnPTenantSite -Url _(some url)_).IsHubSite always returns False.

### Expected behavior 
(Get-PnPTenantSite -Url _(some url)_).IsHubSite should return True for hub sites

### Actual behavior 
(Get-PnPTenantSite -Url _(some url)_).IsHubSite always returns False (screenshot attached)

![HubSite-False](https://user-images.githubusercontent.com/10333583/105558859-a9216d00-5cdd-11eb-882e-123367b981ec.PNG)
.
### Steps to reproduce behavior
1. Register a hub site
2. Run the code below:

$adminUrl = _(SPO Admin site URL)_
$hubSiteUrl = _(URL of a hub site)_
Connect-PnPOnline -Url $adminUrl -UseWebLogin
$hubSite = Get-PnPTenantSite -Url $hubSiteUrl -ErrorAction Stop

3. Check value for $hubSite.IsHubSite

### What is the version of the Cmdlet module you are running?
1.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
Good catch. It has been fixed and it will be available in the nightly release with version 1.2.5-nightly.

**Comment by markoslavik** [comment]
i had this issue, maybe it is fixed and i have an old version. However, i got around it by  pushing all the hubs into a hashtable and then just using the contains function with the url of the site e.g.
#create hashtable to contain all hubsites
$leHubs = @{}

$justHubs = Get-PnPHubSite

foreach($hub in $justHubs)
{
    $key = $hub.ID
    $value = $hub.SiteUrl

    $leHubs.add( $key, $value )
}

$SiteCollections = Get-PnPTenantSite | Where -Property Template -NotIn ("SRCHCEN#0", "SPSMSITEHOST#0", "APPCATALOG#0", "POINTPUBLISHINGHUB#0", "EDISC#0", "STS#-1")

#Loop through each site collection
ForEach($Site in $SiteCollections)
{

    Write-host $Site.URL "`t" $Site.HubSiteId "`t" $leHubs.ContainsValue($Site.Url)
}

 hope that helps
