### ISSUE TITLE
[BUG] Add-PnPSiteCollectionAdmin cannot add gloal admin as site collection administrator

### ISSUE THREAD

**Issue by Ralmenar** [pnp/powershell#152]
Hello, despite I'm logged in with a SharePoint Global Admin, I'm not able to add him as site collection administrator in any of the tenant sites. I can add him using the web portal but not via PowerShell with Add-PnPSiteCollectionAdmin cmdlet.

### **Steps to reproduce:**

- Connect to a site collection with a gloabal admin where you are not member or owner:
         `Connect-PnPOnline -Url "https://yourtenant.sharepoint.com/sites/<yoursite>"`
- Add this global admin as site collection admin
        ` Add-PnPSiteCollectionAdmin -Owners "globaladminemail@yourtenant.onmicrosoft.com"`
- Following error is thrown: _Exception occurred while trying to add the user: "You need to be a site collection administrator to set
this property.". User will be skipped._

**Comment by ToddKlindt** [comment]
Try Set-PnPTenantSite instead.

**Comment by Ralmenar** [comment]
Thanks @ToddKlindt this works perfect as a workaround, but still makes no sense to me that is possible to achieve this with one cmdlet and not with the other. Will use Set-PnPTenantSite for now.

**Comment by ToddKlindt** [comment]
> Thanks @ToddKlindt this works perfect as a workaround, but still makes no sense to me that is possible to achieve this with one cmdlet and not with the other. Will use Set-PnPTenantSite for now.

They each use different permissions. Think about how in the SharePoint Admin center UI a SharePoint Global Admin can create a site collection, but they can't edit Site owners. A SharePoint Global Admin also can't browse a site collection unless they add themselves as an Admin to it. This is the PowerShell version of that experience.

**Comment by erwinvanhunen** [comment]
Exactly what @ToddKlindt  describes. The Add-PnPSiteCollectionAdmin allows current administrators, without access to tenant level settings, to add another site collection administrator. If the user executing the cmdlet is not a site collection admin for that specific site yet it will fail with the exception shown. That's expected behavior of how the cmdlet has been designed and follows the experience when doing it manually from the web ui.
