### ISSUE TITLE
Copyright symbol issue with Add-PnPNavigationNode

### ISSUE THREAD

**Issue by MedinaFab** [pnp/powershell#1524]
### Reporting an Issue
The copyright symbol is showing with extra characters [Â] in the site footer when I run the command mentioned below. 

### Expected behavior 
Title 
--  
© 2009 - 2022 Phibro Animal Health Corporation. All rights reserved.

### Actual behavior 

Title 
--  
Â© 2009 - 2022 Phibro Animal Health Corporation. All rights reserved.

### Steps to reproduce behavior
```
$scriptWinLogin = (Get-Secret -Name myPnPSPSecret)
$siteUrl = "https://pahc.sharepoint.com/sites/TCPOrderForm"
try {
    $connSP = Connect-PnPOnline -Url $siteUrl -Credentials $scriptWinLogin -ReturnConnection -ErrorAction Stop
}
catch {
    Write-Host "Failed to connect to list" -ForegroundColor Red
    exit
}

Add-PnPNavigationNode -Title "© 2009 - 2022 Phibro Animal Health Corporation. All rights reserved." -Url "http://linkless.header/" -Location "Footer"

```

### What is the version of the Cmdlet module you are running?
1.9.0 | PnP.PowerShell

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@MedinaFab - That's strange, I can't reproduce your issue with `1.9.0`.

- Are you using a Site with a different language (than English)?
- Could you try on another site? (and also English if you're currently not)

![image](https://user-images.githubusercontent.com/25181757/149584400-fbefcad7-e8cc-4d5d-b4e7-19396f96e71f.png)

![image](https://user-images.githubusercontent.com/25181757/149584445-e83c85fc-b6b2-4f59-9573-f83fa174fca0.png)

**Comment by MedinaFab** [comment]
@veronicageek - Now fixed. Since I see you tried a different PowerShell application (not sure if called IDE), I tried Windows PowerShell ISE. The site is English. I am using Visual Studio Code 1.63.2 (windows) and has that invalid character in output after running the command. I guess something funny is happening with Visual Studio Code or could be some extension that is causing in my VSCode.
