### ISSUE TITLE
[BUG] Set-PnPTenantSite Does not Respect SharingCapability Change

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#1525]
### Reporting an Issue or Missing Feature
I am reporting a bug

### Expected behavior 
```SharingCapability``` should get changed regardless of it being executed alone or together with other `Set-PnPTenantSite``` parameters.

### Actual behavior 
It looks like ```Set-PnPTenantSite``` does not respect ```SharingCapability``` when executed along with other parameters:
![image](https://user-images.githubusercontent.com/5260172/149463105-c965e6f6-d7b9-4ac4-9067-2e27cf517774.png)
Red - ```SharingCapability``` has been executed in presence of other parameters. No changes applied.
Green - ```SharingCapability``` has been run alone. Changes applied as expected
### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

### What is the version of the Cmdlet module you are running?

Name    : PnP.PowerShell
Version : 1.9.14

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Hi, found the issue and fixed it.
Can you please try it via tomorrow's nightly and let us know ? Feel free to reopen it if the issue still persists !
Thanks !

**Comment by YuriySamorodov** [comment]
Appreciate it Gautam. Confirmed resolved in the module ```PnP.PowerShell 1.9.17```
