### ISSUE TITLE
[BUG] ConvertTo-PnPPage hangs if wiki page contains the string "$$0"

### ISSUE THREAD

**Issue by eepyaich** [pnp/powershell#1539]
### Reporting an Issue or Missing Feature
In converting a bunch of Wiki pages to modern format, I noticed that the ConvertTo-PnPPage operation would completely hang on some pages.  The hang was complete - no error or timeout - with the only being to kill the entire PowerShell session (even CTRL+C didn't work).

Through some investigation, I narrowed the problem down to the three character string $$0 which was in some of our pages.  Having this in the wiki page would cause the problem.  Note that changing this to $0 was OK - it was the particular combination $$0 which caused the issue.

### Expected behavior 
Conversion from Wiki to modern page should continue without error.

### Actual behavior 
Operation completely hung the powershell session.  No modern page was created in SharePoint.

### Steps to reproduce behavior
1 - Create Wiki page (or edit an existing wiki page) that contains the text $$0
2 - Run ConvertTo-PnPPage on that page

### What is the version of the Cmdlet module you are running?
1.9.0

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
hi @eepyaich , can you please try with the latest version ? 

Looks like the issue has been fixed via this PR.

https://github.com/pnp/pnpframework/pull/777

**Comment by gautamdsheth** [comment]
Closing due to lack of response
