### ISSUE TITLE
Set-PnPPage -Identity "MyPage" -CommentsEnabled:$false does nothing

### ISSUE THREAD

**Issue by JaeEmAre67** [pnp/powershell#1540]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting
Set-PnPPage -Identity "MyPage" -CommentsEnabled:$false does nothing

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets
The page to be updated and if comments were originally enabled they are now disabled

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.
The page isn't changed and comments are still enabled

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)
```
$siteUrl = Read-Host "`r`nEnter the full URL of the site you want to disable comments for (https://portal.....)"

Connect-PnPOnline -Url $siteUrl;
Set-PnPSite -CommentsOnSitePagesDisabled:$true;

$allwebs = @()
$allwebs += Get-PnPWeb
$allwebs += Get-PnPSubWebs -Recurse

foreach ($web in $allwebs) {
    Connect-PnPOnline $web.Url;
    Set-PnPSite -CommentsOnSitePagesDisabled:$true
    $pagesLib = Get-PnPList -Identity "SitePages"
    if ($null -ne $pagesLib) {
        $allPages = Get-PnPListItem -List $pagesLib.Title
        if ($allPages.Count -gt 0) {
            foreach ($page in $allPages) {
                Set-PnPPage -Identity $page["FileLeafRef"] -CommentsEnabled:$false;
            }
        }
    }
}
```

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
1.7.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@JaeEmAre67 - I've tested with `1.9.22` nightly and have no issue disabling the comments. As @gautamdsheth said, please update the module.

![image](https://user-images.githubusercontent.com/25181757/150655119-73b5f233-e521-4550-99a7-88ea71fb3a96.png)
