### ISSUE TITLE
[BUG] Add-PNPFolder format-default : The collection has not been initialized. It has not been requested...

### ISSUE THREAD

**Issue by SPDEVGUY** [pnp/powershell#1546]
### Notice
Bug description:

Using Add-PnPFolder sometimes (not always) seems to result in the following message and full termination of the running script in the middle of processing:

```
format-default : The collection has not been initialized. It has not been requested or the request has not been
executed. It may need to be explicitly requested.
    + CategoryInfo          : NotSpecified: (:) [format-default], CollectionNotInitializedException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.CollectionNotInitializedException,Microsoft.PowerShell.Commands.FormatDefaultCommand
```

The code being run is:
```
#Target folder is populated from a CSV and this chunk of code runs within it. CSV is responsible for creating folder structure inside a document library.

        Connect-PNPOnline -url $siteUrl -interactive
        $destinationListFolder = "Shared Documents"
        $targetFolder = "legal/1. figures enterprise (refine_adv metak_icci)/Changes to Adv Metak's Business Purpose"

        "Ensuring $targetFolder exists..."
	$folderTree = $targetFolder.split('/')
	$parent = $destinationListFolder
	foreach($folder in $folderTree) {
		
		$fixed = $folder.trim()
		$fixed = $fixed.replace('~','_').replace('"','_').replace('#','_').replace('%','_').replace('&','_').replace('*','_').replace(':','_')
		$fixed = $fixed.replace('<','_').replace('>','_').replace('?','_').replace('/','_').replace('\','_').replace('{','_').replace('}','_')
		$fixed = $fixed.replace('|','_').replace('.','_')
		
		"Make $fixed in $parent..."
		Add-PNPFolder -Name $fixed -Folder $parent -EA 0
		$parent += "/" + $fixed
	}
```

The powershell window output is:
Ensuring legal/1. figures enterprise (refine_adv metak_icci)/Changes to Adv Metak's Business Purpose exists...
Make legal in Shared Documents...
Make 1_ figures enterprise (refine_adv metak_icci) in Shared Documents/legal...
Make Changes to Adv Metak's Business Purpose in Shared Documents/legal/figures enterprise (refine_adv metak_icci)..
.
format-default : The collection has not been initialized. It has not been requested or the request has not been
executed. It may need to be explicitly requested.
    + CategoryInfo          : NotSpecified: (:) [format-default], CollectionNotInitializedException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.CollectionNotInitializedException,Microsoft.PowerShell.Comma
   nds.FormatDefaultCommand

### Reporting an Issue or Missing Feature
Issue with the command

### Expected behavior 
throw useful error or not have an error

### Actual behavior 
Throws error randomly, works sometimes then doesn't

### Steps to reproduce behavior
1. Create a teams site in SPO, with a standard "Documents" library with the url path "Shared Documents" (out of the box)
2. Run above script in a powershell script, potentially loop it with a few different paths.

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

1.9.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by SPDEVGUY** [comment]
I should also note that running:

Add-PNPFolder -Name "Changes to Adv Metak's Business Purpose" -Folder "Shared Documents/legal/1. figures enterprise (refine_adv metak_icci)"

Works fine even though that input had previously made the script fail.

**Comment by SPDEVGUY** [comment]
Adding a start-sleep 1 to the loop seems to have helped it

**Comment by gautamdsheth** [comment]
The solution to this is you need to store the result and assign it to a variable like this:

```
$createdFolder = Add-PNPFolder -Name $fixed -Folder $parent -EA 0
```

You can read more on this stuff here:

https://sympmarc.com/2020/04/24/an-inconvenient-powershell-error-format-default-the-collection-has-not-been-initialized/

https://github.com/pnp/PnP-PowerShell/issues/722

**Comment by SPDEVGUY** [comment]
The experience is kind of wonky.  Is there an EnsureFolder exists or something that would ensure whole heirarchy of folders?

```
$folderTree = $targetFolder.split('/')
	$parentUrl = $destinationListFolder
	$parent = $null
	foreach($folder in $folderTree) {
		$fixed = $folder.trim()
		
		"Make $fixed in $parentUrl..."
		if($parent -ne $null) {
			#If folder exists it errors and returns null.
			$parent = Add-PNPFolder -Name $fixed -Folder $parent -EA 0 
		} else {
			#If folder exists it errors and returns null.
			$parent = Add-PNPFolder -Name $fixed -Folder $parentUrl -EA 0
		}
		
		$parentUrl += "/" + $fixed
		
	}
```
