### ISSUE TITLE
[BUG] SetComplianceTag has incorrect response 

### ISSUE THREAD

**Issue by prattay56** [pnp/powershell#1547]
Issue with **pnp.powershell** 

No Issue with **SharePointPnPPowerShellOnline**

Documentation:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.client.listitem.setcompliancetag?view=sharepoint-csom
Issue description:
Unable to set compliance tag.

Error:
```
PS C:\Users\amand> Get-PnPListItem -List $listcol -Id 1

Id    Title                                              GUID
--    -----                                              ----
1     A week in the life                                 1405224c-0b60-4737-808a-1335c0d9a7f3


PS C:\Users\amand> $items = Get-PnPListItem -List $listcol -Id 12
PS C:\Users\amand> $items.SetComplianceTag("", $false, $false, $false, $false)
Cannot find an overload for "SetComplianceTag" and the argument count: "5".
At line:1 char:1
+ $items.SetComplianceTag("", $false, $false, $false, $false)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

```
However, if we use the legacy SharePointPnPPowerShellOnline module, the same script works just fine. 

It clearly is a Bug.

**Comment by prattay56** [comment]
![image](https://user-images.githubusercontent.com/74849664/150609923-77dc591e-e8b5-4299-991e-05c7d236896f.png)

**Comment by prattay56** [comment]
The script that I use to remove the Retention Tags.
```

$site = "https://contoso.sharepoint.com"
Connect-PnPOnline -Url $site -UseWebLogin

$Id = 52,53

$list = Get-PnPList -Identity "Shared Documents"
foreach ($item in $id) {
    
    $i = Get-PnPListItem -List $list -Id $item
    Write-Host "Fixing list " $list.Title, $list.Id
    $i.SetComplianceTag("", $false, $false, $false, $false)
    $i.Update()
    Invoke-PnPQuery
}
```

**Comment by gautamdsheth** [comment]
You can need to modify your code as below:

```
$item.SetComplianceTag("", $false, $false, $false, $false, $false);
```

It requires 6 parameters not 5. We are using a different version of CSOM here.

Also, since you are using PnP PowerShell, you can use it as below as well:

```
Set-PnPListItem -Identity 1 -List "List"  -ClearLabel
```

**Comment by prattay56** [comment]
Thank you for the update. Both worked out for me.

**Comment by Jherschel7** [comment]
Thank you @gautamdsheth, the -ClearLabel worked great for a script where I needed to remove the label.  Setting the label to blank or null did not work.
