### ISSUE TITLE
[BUG] Get-PnPUserOneDriveQuota reporting license maximum quota instead of actual quota

### ISSUE THREAD

**Issue by adzero** [pnp/powershell#1554]
### Reporting an Issue
`Get-PnPUserOneDriveQuota` returns a value that is not equal to actual applied quota. Problem still occurs after using `Set-PnPUserOneDriveQuota`.

### Expected behavior 
The command should return the same quota as the one applied, displayed in administration center or returned by `Get-SPOSite` command. 

### Actual behavior 
The value returned seems to be the maximum quota allowed by the user's license. 

Here's an example getting one user quota and the actual quota applied to underlying SharePoint site collection. 

![image](https://user-images.githubusercontent.com/7522988/150989163-eff251e1-3608-4c28-803c-859f5dc11879.png)

### Steps to reproduce behavior

```
$user = "someone@tenantdomain"
$TenantSPOAdminUrl = "https://tenant-admin.sharepoint.com"
$credentials = Get-Credential -Message "SPO admin account"
Connect-SPOService -Url $TenantSPOAdminUrl -Credential $credentials
Connect-PnPOnline -Url $TenantSPOAdminUrl -Credentials $credentials
(Get-PnPUserOneDriveQuota -Account $user | Select-Object -ExpandProperty Value)/(1024*1024)
Get-SPOSite -Identity ((Get-PnPUserProfileProperty -Account $user).personalurl -replace "/$","") | Select-Object -ExpandProperty StorageQuota
```

### What is the version of the Cmdlet module you are running?
Using 1.9.0 version of the module

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
Indeed, seems it's not reporting the correct value.

FYI - @gautamdsheth @KoenZomers

**Comment by KoenZomers** [comment]
I cannot seem to reproduce it here. Works fine for me using the code shared in this issue. @veronicageek were you able to reproduce this issue?

**Comment by veronicageek** [comment]
Kind of. I didn't have the (default) 1TB in return, but for a user where I've set 20GB quota, it was giving me 5GB... 🤷🏻‍♀️

**Comment by KoenZomers** [comment]
I tried it against two accounts where I have the maximum value of 5 TB set and it reported back exactly that and exactly the same value through both SPO Mgmt Shell and PnP Posh.

**Comment by veronicageek** [comment]
Yes but can you set the quota to something else (i.e.: 20GB) and try again?

**Comment by veronicageek** [comment]
Still happening with `1.10.0`
