### ISSUE TITLE
[BUG] Add-PnPPageWebPart Image web part. Image doesn't display until after editing and saving the page

### ISSUE THREAD

**Issue by schieleingrid** [pnp/powershell#1560]
Not sure if this is the correct process, but I found an bug that exactly describes my problem #1424 and it was closed due to no response. As the bug can't be reopened, i've created this new issue.

### Reporting an Issue or Missing Feature
When you use Add-PnPPageWebPart to add an Image web part to a page, the web part gets added but the Image doesn't display until after editing and saving the page

### Expected behavior 
Add-PnPPageWebPart adds an Image web part to a page and the you can see the web part in the page without having to edit and save first

### Actual behavior 
Add-PnPPageWebPart adds an Image web part to a page, the web part gets added but the Image doesn't display until after editing and saving the page

### Steps to reproduce behavior
`$imgProps = @{imageSource="https://xxx.sharepoint.com/sites/test/SiteAssets/_SiteLogo/Homepage_Logo.jpg"}`
`$imgWebPart = Add-PnPPageWebPart -Page Home1 -DefaultWebPartType "Image" -Section 1 -Column 1 -WebPartProperties $imgProps`

### What is the version of the Cmdlet module you are running?
1.9.0 , 1.8.0 and 1.7.0

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

###Additional infomation
I've checked the suggestion of @veronicageek if this error occurs due to special home.aspx behaviour, but it doesn't.

**Comment by schieleingrid** [comment]
I've done some tests and it seems that the reason why the image isn't displayed is, that the serverProcessedContent of the webPartData must be set to show the image. This happens actually when saving the page, not when adding the webpart via cmdlet.

So i've tried this
`$imgProps = @{}
$imgProps.serverProcessedContent = @{}
$imgProps.serverProcessedContent.imageSources=@{imageSource= "https://xxx.sharepoint.com/sites/$($currSiteInfo.siteName)/SiteAssets/_SiteLogo/Homepage_Logo.jpg"}
$imgProps.serverProcessedContent.customMetadata=@{imageSource=@{}}
$imgProps.serverProcessedContent.customMetadata.imageSource.siteId= "7c0808b4-c285-4c72-9818-e088e132e3c1"
$imgProps.serverProcessedContent.customMetadata.imageSource.webId= "3d6460bc-89c5-4f32-831d-b32ecda1ce7d"
$imgProps.serverProcessedContent.customMetadata.imageSource.listId= "c3712fa1-eddb-4cb6-b135-4cbb7ad23438"
$imgProps.serverProcessedContent.customMetadata.imageSource.uniqueId= "921796E7-88B6-43D0-B217-9B6FED3E8FE8"
$imgProps.serverProcessedContent.customMetadata.imageSource.imgWidth= 1000
$imgProps.serverProcessedContent.customMetadata.imageSource.imgHeight= 550
$imgProps.imageSourceType= 2
$imgProps.captionText= ""
$imgProps.altText= ""
$imgProps.linkUrl= ""
$imgProps.overlayText= ""
$imgProps.fileName= ""
$imgProps.siteId= "7c0808b4-c285-4c72-9818-e088e132e3c1"
$imgProps.webId= "3d6460bc-89c5-4f32-831d-b32ecda1ce7d"
$imgProps.listId= "c3712fa1-eddb-4cb6-b135-4cbb7ad23438"
$imgProps.uniqueId= "921796E7-88B6-43D0-B217-9B6FED3E8FE8"
$imgProps.imgWidth= 1000
$imgProps.imgHeight= 550
$imgProps.alignment= "Center"
$imgProps.fixAspectRatio= $false

Add-PnPPageWebPart -Page $tmpPageName -DefaultWebPartType "Image" -Section 1 -Column 1 -WebPartProperties $imgProps`

And the image is shown right after adding without saving the page manually.

**Comment by schieleingrid** [comment]
No, this Script do not solve the issue as the Webpart does not work properly anymore.

**Comment by gautamdsheth** [comment]
hi @schieleingrid , we have added a cmdlet , `Add-PnPPageImageWebPart` which is available from tomorrow's nightly build and the next major release whenever that happens.
