### ISSUE TITLE
[FEATURE] Copy-PnPList - Documentation for source and destination tenants

### ISSUE THREAD

**Issue by robertcaretta** [pnp/powershell#1561]
**Is your feature request related to a problem? Please describe.**
Just looking for some additional documentation examples. [ I was advised to post this here](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/issues/137). 

**Describe the solution you'd like**
Can this cmdlet work between tenants? For example TEST and PROD.
Can you provide an example of how that would work?

**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/issues/137

**Comment by veronicageek** [comment]
Hi @robertcaretta - That's a good question. But it won't work as the copy needs to happen on the same tenant. In your scenario, you'll have to export the list as a provisioning template and then apply the template on another tenant.

I'll also update the documentation.

**Comment by robertcaretta** [comment]
Thank you for the clarification. Any details you can provide in the
documentation would be really appreciated.
