### ISSUE TITLE
[BUG] SharePointApplicationPermissions 'Sites.Selected' fails in USGovernmentHigh national cloud

### ISSUE THREAD

**Issue by milesgratz** [pnp/powershell#1579]
1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? 

> No

2. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** 

> Unlikely to be an issue with PnP.PowerShell but rather inconsistencies with PnP.PowerShell cmdlets and national cloud ecosystem. 

3. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** 

> Same as #2.

### Reporting an Issue or Missing Feature

> SharePointApplicationPermissions 'Sites.Selected' fails in USGovernmentHigh national cloud

### Expected behavior 

> Consent flow completes successfully. 

### Actual behavior 

> 
> You failed to provide consent.
> 
> Error details: error invalid_request error_description:AADSTS65006: Resource '00000003-0000-0ff1-ce00-000000000000' had no entitlements matching required permissions configured on the required resource access for client 'ca6c7002-b2e8-4f70-847b-c85c413e57ef'. Requested permission IDs: '20d37865-089c-4dee-8c41-6967602d4ac8'. This is a problem with one or more invalid permission ids on the client RRA configuration or the resource entitlement configuration. Trace ID: {redacted} Correlation ID: {redacted} Timestamp: 2022-01-30 19:34:30Z

![image](https://user-images.githubusercontent.com/17114534/151714911-14cf264b-1a2d-4bc5-a927-f3c8878728a5.png)

This is how it appears in the Azure AD app registration: 

![image](https://user-images.githubusercontent.com/17114534/151715086-32ade5ce-519c-409d-b55f-4244bac673b4.png)

### Steps to reproduce behavior

Attempt to use Sites.Selected on a national cloud, specifically USGovernmentHigh

### What is the version of the Cmdlet module you are running?

1.9.30 (and 1.9.24) 

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
@milesgratz - Is this permission available from the UI in your tenant ?

**Comment by milesgratz** [comment]
@gautamdsheth Microsoft Graph permissions (Sites.Selected) are exposed in UI. This would be the CSOM option. Although I haven't been able to get any scenario (Graph vs CSOM) with Sites.Selected working with USGovernmentHigh. 

I am following the guidance here: 
- https://pnp.github.io/powershell/articles/authentication.html#authentication-to-gcc-or-national-cloud-environments
- https://www.leonarmston.com/2021/03/testing-out-the-new-microsoft-graph-sharepoint-specific-site-collection-app-permissions-with-pnp-powershell/
- https://www.leonarmston.com/2022/01/pnp-powershell-csom-now-works-with-sharepoint-sites-selected-permission-using-azure-ad-app/

When I try to use the proper Sites.Selected via the Graph permissions: 

```
$params = @{
   AppId = '0aa61360-851d-435b-9f5c-eb057e1d5be7'
   DisplayName = 'PnPPowerShell-SitesSelected'
   Site = 'https://example.sharepoint.us/teams/SitesSelected'
   Permissions = 'Write'
}
Grant-PnPAzureADAppSitePermission @params
```
This fails with:
```
{"error":{"code":"BadRequest","message":"Resource not found for the segment 'permissions'.","innerError":{"date":"2022-01-31T14:50:13","request-id":"{redacted}","client-request-id":"{redacted}"}}}
```

My last resort is to try manually in the Graph API using this site: https://ashiqf.com/2021/03/15/how-to-use-microsoft-graph-sharepoint-sites-selected-application-permission-in-a-azure-ad-application-for-more-granular-control/ 

Either way, if anyone has been able to use Sites.Selected correctly in GCCH I would love to know how they are doing it.

**Comment by milesgratz** [comment]
Looks like ```https://graph.microsoft.us/sites/{siteId}/permissions/``` doesn't exist in GCCH. Ugh. 

### [USGovernmentHigh] ```graph.microsoft.us/sites/{siteId}/permissions/```

![image](https://user-images.githubusercontent.com/17114534/151898889-a102c13f-fea2-4cb0-b32f-100acb7aea53.png)
![image](https://user-images.githubusercontent.com/17114534/151897652-2112edde-924d-4bda-9c93-affff0fafe58.png)

### [Commercial] ```graph.microsoft.com/sites/{siteId}/permissions/```

![image](https://user-images.githubusercontent.com/17114534/151898587-1163eccd-998f-44b9-8c2d-9402b7cfff2d.png)

**Comment by LeonArmston** [comment]
> Looks like `https://graph.microsoft.us/sites/{siteId}/permissions/` doesn't exist in GCCH. Ugh.
> 
> ### [USGovernmentHigh] `graph.microsoft.us/sites/{siteId}/permissions/`
> ![image](https://user-images.githubusercontent.com/17114534/151898889-a102c13f-fea2-4cb0-b32f-100acb7aea53.png) ![image](https://user-images.githubusercontent.com/17114534/151897652-2112edde-924d-4bda-9c93-affff0fafe58.png)
> 
> ### [Commercial] `graph.microsoft.com/sites/{siteId}/permissions/`
> ![image](https://user-images.githubusercontent.com/17114534/151898587-1163eccd-998f-44b9-8c2d-9402b7cfff2d.png)

Hi @milesgratz 

Sorry for the late response - although looks like you may have found the problem the Sites Permission endpoint not working in GCCH. I guess it should (https://docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&tabs=http) so maybe one to log with MS support.

**Comment by milesgratz** [comment]
Thanks @LeonArmston. I just opened a case. Not holding my breath. This project is also at the mercy of national cloud limitations (so no worries - you guys are great) - but if anyone from the MSFT USGov product group is listening, it would be really great if we could stop exposing features in Azure that won't work and we have to reverse-engineer why it doesn't.

**Comment by veronicageek** [comment]
Closing as nothing we can do unfortunately.

**Comment by milesgratz** [comment]
**Official update from Microsoft Support this morning:** 

> I was able to confirm with engineering that this feature is not currently available in GCCH at this time and unfortunately there is not ETA.  I would continue to check the typical channels and/or roadmap for any future updates as they are released.

**Comment by westleyMS** [comment]
Documentation shows it is supported in all environments now, just to update this thread-
https://learn.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&tabs=http
