### ISSUE TITLE
Distributing the Module as a Docker Image

### ISSUE THREAD

**Issue by shurick81** [pnp/powershell#1580]
**Is your feature request related to a problem? Please describe.**

As a developer working with a multitude of projects where PnP.Powershell is used, I would like to be able to quickly run the module without the need of actually installing the module in the host environment so that I have isolated and repeatable experience of using the module for multiple different project.

**Describe the solution you'd like**

Every time when a new version of the PnP.PowerShell module is released, we could

1. build a new a new version of the Docker image with the module installed. 

I tried the following Dockerfile locally and it works quite fine for me so far:

```docker
FROM mcr.microsoft.com/powershell:7.2.1-alpine-3.14-20211215

RUN pwsh -c "Install-Module -Name PnP.PowerShell -RequiredVersion 1.9.0 -Force"
```

2. do some testing of the new module version working inside a container
3. publish the image to https://hub.docker.com/u/m365pnp

**Describe alternatives you've considered**

Alternatively we could just come up with a small guide/demo/webinar that shows how to build and use a local image, since there is no published one.

**Additional context**

We wanted to consider this improvement when the module GA is close enough, but then this issue was forgotten I believe:
https://github.com/pnp/powershell/issues/11

**Comment by KoenZomers** [comment]
@shurick81 I have no such experience myself to be able to set this up. Would you be able to do this?

**Comment by shurick81** [comment]
@KoenZomers yes, I would love to do it. First of all we could discuss some more specific use cases here in this thread and then I could come up with a PR.

**Comment by KoenZomers** [comment]
Nice. I think you mention one yourself already in your start post. I could envision having a docker image per version perhaps to test things in a specific version? Not a docker guy here so not sure if that makes sense.

**Comment by shurick81** [comment]
I suggest that if we go with docker image, we need to extend the use cases.

1. to quickly run the module without the need of actually installing the module in the host environment so that I have isolated and repeatable experience of using the module for multiple different projects
2. to access local host directories through using volumes on a docker container
3. to use image for running jobs in such pipeline engines like Azure DevOps (maybe in GitLab also)

What do you think?

**Comment by shurick81** [comment]
Here's a preliminary result:
1. nightly releases example: https://hub.docker.com/repository/docker/asapozhkov/pnp-powershell
2. Build and publish nightly releases: https://github.com/alexsapozhkov/powershell/tree/dev/docker
3. Build and publish via Github Actions: https://github.com/alexsapozhkov/powershell/actions/workflows/nightlyrelease.yml

**Comment by shurick81** [comment]
I can see that in the m365pnp organization in Docker Hub, there are already a few images:

* m365pnp/spfx
* m365pnp/cli-microsoft365

Do you think it is fine if we name the image m365pnp/powershell?

**Comment by shurick81** [comment]
Do we need this container runnable on ARM platform?

**Comment by shurick81** [comment]
Here's how you could currently try it out:

```
docker run --rm -it asapozhkov/powershell pwsh -c "Get-Module PnP.PowerShell -ListAvailable"
```

Also tested (in Linux at least) that it is possible to manipulate with files on the host using commands in a container:

```
docker run --rm -it -v $(pwd):/home/powershell asapozhkov/powershell pwsh -c "cd /home/powershell; Get-ChildItem"
docker run --rm -it -v $(pwd):/home/powershell asapozhkov/powershell pwsh -c "cd /home/powershell; Set-Content test test"
```

**Comment by shurick81** [comment]
Here's the commit so far: https://github.com/pnp/powershell/compare/dev...alexsapozhkov:dev

**Comment by shurick81** [comment]
PR: #1794

**Comment by shurick81** [comment]
I guess we are done here?

**Comment by KoenZomers** [comment]
Yep seems like it :) Thanks for your efforts!
