### ISSUE TITLE
[BUG] New-PnPTeamsTeam: Resource 'users' does not exist or one of its queried reference-property objects are not present.

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#1585]
### Reporting an Issue or Missing Feature
This is a bug

### Expected behavior 
```New-PnPTeamsTeam``` with  ```-Members``` -and/or `-Owner` should create a team in Teams

### Actual behavior 
```New-PnPTeamsTeam``` would give an error below in presence of `-Owners` and/or `-Members`:

> New-PnPTeamsTeam: Resource 'users' does not exist or one of its queried reference-property objects are not present.

The error appears if members are inside an array or are enumerated by colon.
![image](https://user-images.githubusercontent.com/5260172/152107385-e0aa5ac7-246c-459b-aa10-fdf76c6c6688.png)

### Steps to reproduce behavior
`Connect-PnPonline ;`
`'Team.Name' | %{ New-PnPTeamsTeam -DisplayName $_ -MailNickName $_ -Owners owner@conoso.com -Visibility Private -Members @('user1@contoso.com','user2@contoso.com' ) }`

### What is the version of the Cmdlet module you are running?
```
Name    : PnP.PowerShell
Version : 1.9.33
```
### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Do the users exist in AAD ? Are you entering the correct UPNs ?

**Comment by YuriySamorodov** [comment]
Yes, they do exist and I have double checked that. It errored out even when I specified just an owners (a single person there)

**Comment by gautamdsheth** [comment]
Good catch @YuriySamorodov , fixed it !
Will be available from tomorrow's nightly.
Thank you.
