### ISSUE TITLE
[BUG] Get-PnPTeamsTeam: Bad Gateway

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#1586]
### Reporting an Issue or Missing Feature
This is a bug

### Expected behavior 
`$teams = Get-PnPTeamsTeam` should get all teams and save them all in the variable

### Actual behavior 
`$teams = Get-PnPTeamsTeam` gives an error `Bad Gateway`
![image](https://user-images.githubusercontent.com/5260172/152110157-78d7420f-4f67-4785-962b-c04f69c6bd42.png)

### Steps to reproduce behavior
```
Connect-PnPOnline
$teams = Get-PnPTeamsTeam
```

### What is the version of the Cmdlet module you are running?
```
Name    : PnP.PowerShell
Version : 1.9.33
```
### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Maybe a temporary issue ? Can you check with a different tenant if possible ? We haven't changed anything related to this command

**Comment by YuriySamorodov** [comment]
Yeah, looks like a glitch... Sorry!
