### ISSUE TITLE
[BUG] Remove-PnPTenantDeletedSite: Invalid URI: The format of the URI could not be determined.

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#1587]
### Reporting an Issue or Missing Feature
I would consider this a bug
Consider the following scenario:
```
$site = $site = Get-PnPTenantDeletedSite https://contoso.sharepoint.com/sites/deleted-site
Remove-PnPTenantDeletedSite -Identity "$($site.SiteId)"
```

### Expected behavior 
`Remove-PnPTenantDeletedSite` should permanently delete the site.

### Actual behavior 
`Remove-PnPTenantDeletedSite` throws an error:

> Remove-PnPTenantDeletedSite: Invalid URI: The format of the URI could not be determined

![image](https://user-images.githubusercontent.com/5260172/152118674-8db4e1a5-0ab1-42f4-b262-8a487f718e6f.png)

### Steps to reproduce behavior
```
$site = $site = Get-PnPTenantDeletedSite https://contoso.sharepoint.com/sites/deleted-site
Remove-PnPTenantDeletedSite -Identity "$($site.SiteId)"
```

### What is the version of the Cmdlet module you are running?
```
Name    : PnP.PowerShell
Version : 1.9.33
```
### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Hi, this is not a bug. 
This expects the URL of the site and you are passing the Site ID which will not work

**Comment by YuriySamorodov** [comment]
Got it. Appreciate it @gautamdsheth !
