### ISSUE TITLE
[FEATURE] Remove-PnPTenantDeletedSite  Should Accept URL from the Property

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#1588]
**Is your feature request related to a problem? Please describe.**
Consider the following scenario (notice no quotes)
```
$site = $site = Get-PnPTenantDeletedSite https://contoso.sharepoint.com/sites/deleted-site
Remove-PnPTenantDeletedSite -Identity $($site.SiteId) 
```
In this case I get an error below:

> Remove-PnPTenantDeletedSite: Cannot bind parameter 'Identity'. Cannot convert the "dbfc75a2-455d-4dff-95ba-46938909cc4d" value of type "System.Guid" to type "PnP.PowerShell.Commands.Base.PipeBinds.SPOSitePipeBind".

**Describe the solution you'd like**
It would be great to have an option to run `Remove-PnPTenantDeletedSite` without specifying a property of an object in quotes.

**Describe alternatives you've considered**
It runs no problem if I put identity in quotes:
```
$site = $site = Get-PnPTenantDeletedSite https://contoso.sharepoint.com/sites/deleted-site
Remove-PnPTenantDeletedSite -Identity "$($site.SiteId)"
```

**Additional context**
![image](https://user-images.githubusercontent.com/5260172/152120303-3435351b-18bd-4ede-85a6-c220852e59aa.png)

**Comment by gautamdsheth** [comment]
Is this still the case ? Can you please check with latest nightly and let us know ? We changed some stuff around this cmdlet

**Comment by YuriySamorodov** [comment]
Hi @gautamdsheth , this woks perfectly now, appreciate quick turnaround. You are the best!
