### ISSUE TITLE
[FEATURE] Remove-PnPTenantDeletedSite Identity Value From Pipeline 

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#1589]
**Is your feature request related to a problem? Please describe.**
It's sad you cannot run `Remove-PnPTenantDeletedSite` the way below:
```
Get-PnPTenantDeletedSite https://contoso.sharepoint.com/sites/test | Remove-PnPTenantDeletedSite
```
Currently the above command throws an error:

> Remove-PnPTenantDeletedSite: The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.

**Describe the solution you'd like**
Please allow `Remove-PnPTenantDeletedSite` take Identity value from pipeline
https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/parameter-attribute-declaration?view=powershell-7.2

**Describe alternatives you've considered**
```
$site = Get-PnPTenantDeletedSite https://contoso.sharepoint.com/sites/test
Remove-PnPTenantDeletedSite -Identity "$($site.SiteId)"
```

**Additional context**
![image](https://user-images.githubusercontent.com/5260172/152121250-78abd3b1-85fa-43b9-9998-6fbc50b81596.png)

**Comment by KoenZomers** [comment]
Resolved in https://github.com/pnp/powershell/pull/1596
