### ISSUE TITLE
[BUG] Convert-PnPFolderToSiteTemplate rename source folders like 'Shared Documents' to 'Shared_Documents' breaking the import

### ISSUE THREAD

**Issue by Nathaire** [pnp/powershell#1590]
### Reporting an Issue
Convert-PnPFolderToSiteTemplate renames source folders having a space in their name, which break the xml template included in the pnp file (see https://github.com/pnp/powershell/blob/8df54e351875d70881b193578a58bb64c7d9910d/src/Commands/Provisioning/Site/ConvertFolderToSiteTemplate.cs#L108)

### Expected behavior 
Executing Invoke-PnPSiteTemplate with the newly created package upload all files correctly as if using template XML instead of template PNP file.

### Actual behavior 
Executing Invoke-PnPSiteTemplate throw an exception when it tries to upload one of the documents

![image](https://user-images.githubusercontent.com/8290006/152168959-0208fcf7-a52f-4258-a214-cd478818bbaf.png)

when TraceLog are activated, we can found this:
`pwsh Error: 0 : 2022-02-02 14:57:26.6095	[PnP.Framework]	[0]	[Error]	File Wikipedia.docx not found in directory Shared Documents. Exception = Unable to find the specified file.	0ms	`

### Steps to reproduce behavior
- Create new Communication site
- Upload a document to the 'Shared Documents' library
- Edit home page and add a 'Link' WebPart targetting the newly added document
- Open Powershell console
- Connect to the newly created site
- Execute following code
```
Get-PnPSiteTemplate -Out export.xml -IncludeAllPages -PersistBrandingFiles
Convert-PnPFolderToSiteTemplate -Out export.pnp
Invoke-PnPSiteTemplate -Path .\export.pnp
```

Error will be thrown when the engine tries to load the file uploaded in the 'Shared Document'

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 1.9.0

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows

**Comment by Nathaire** [comment]
Error still present with PnP.Powershell 1.10

**Comment by veronicageek** [comment]
@Nathaire - Can you please update to the latest release 2.1.x however you will need **PS 7.2 or later** to benefit from all the bug fixes and improvements.

PS5 support has been dropped in the new release.

Feel free to reopen if the issue persists. Thanks.
