### ISSUE TITLE
[BUG] Get-PnPPlannerTask : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by jsmartbnl** [pnp/powershell#1592]
### Reporting an Issue or Missing Feature
Get-PnPPlannerTask

### Expected behavior 
Get-PnPPlannerTask should return tasks in the specified plan.

### Actual behavior 
Get-PnPPlannerTask : Object reference not set to an instance of an object.
At line:1 char:1
![image](https://user-images.githubusercontent.com/12417890/152199756-2f59b07b-d68b-4c1c-89e0-22a3a9af7a54.png)

### Steps to reproduce behavior

1. Connect to PnPOnline with the -Interactive parameter to enable graph API support.
2. Get a list of plans in a group.
3. Get a list of tasks in a plan by plan ID.

### What is the version of the Cmdlet module you are running?
1.9.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@jsmartbnl - I have tried on a commercial tenant and have no problem. I'll tag the issue as a GCC, but unfortunately, I don't think we have access to such a tenant. I'd recommend you open a support case with Microsoft directly to have confirmation.

![image](https://user-images.githubusercontent.com/25181757/152236731-56d074f4-d1b8-49c2-861c-6b10a4454ecc.png)

Closing for now, but feel free to reopen when you have confirmation and we can troubleshoot further.
