### ISSUE TITLE
[BUG] TaxonomyFieldTypeMulti Multiple values as term paths causes "Object reference not set to an instance of an object" on set-pnplistitem

### ISSUE THREAD

**Issue by SPDEVGUY** [pnp/powershell#1595]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 

The following code should expectantly set the "Topics" field which is a multi value managed metadata column to "EHS" and "Metals".
The  Documents library has a taxonomy field named "Topics" added to it, and several sub-folders.  This code is just trying to set metadata on the first available file within a folder named "SubFolderA"

```
Connect-PNPOnline -url $siteUrl -interactive

$destinationListFolder = "Shared Documents"
$destinationListName = "Documents"
$targetFolder = "SubFolderA"
$topicMmsArray = @("Records|Topics|EHS","Records|Topics|Metals")



#Ensure taxonomy paths
import-pnptaxonomy -Terms $values -lcid 1033

$folder = Get-PNPFolder -url  "$($destinationListFolder)\$($targetFolder)"
$files = Get-PnPFolderItem -ItemType File -FolderSiteRelativeUrl "$($destinationListFolder)\$($targetFolder)" -recursive
$list = get-pnplist $destinationListName

$file = $files[0]
$file.ServerRelativeUrl 
$fileListItem = Get-PNPFile -url $file.ServerRelativeUrl -AsListItem	
		
$values = @{"Topics"=$topicMmsArray}

#Verify inputs aren't null
$values
$list
$fileListItem.Id

#Throws null
Set-PnPListItem -List $list -Identity $fileListItem.Id -Values $values -UpdateType "SystemUpdate"

File list item should now have the value.

```

I can't get into debugging but maybe the issue is here?

https://github.com/pnp/powershell/blob/092eb0d694faa618f5df95a1f89c4443c538ffaf/src/Commands/Utilities/ListItemHelper.cs#L124

It doesn't seem to make it to the "You are trying to set multiple values in a single value field. Skipping values for field" error if I set the field to only allow one value, so it isn't reaching that code to check for the possibility of multiple field values.

### Actual behavior 
```
Set-PnPListItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Set-PnPListItem -List $list -Identity $fileListItem.Id -Values $value ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPListItem], NullReferenceException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Lists.SetListItem
```
If I change the code to use each of the values one at a time the code works and sets the value accordingly and the item receives the metadata properly for each value used, it only has problems if it is passed in an array of values.

### Steps to reproduce behavior
see above.

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```).

1.9.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Hi am unable to reproduce the issue.
Could be something in your code ? 
Maybe try it like with hardcoded values :

```
$topicMmsArray = @("Records|Topics|EHS","Records|Topics|Metals")
$values = @{"Topics"=$topicMmsArray}
Set-PnPListItem -List "DocLib" -Identity 1 -Values $values -UpdateType "SystemUpdate"

```

**Comment by SPDEVGUY** [comment]
```
PS C:\users\user\Documents> $folder = Get-PNPFolder -url  "Shared Documents/SubFolderA/SubFolderB"
PS C:\users\user\Documents> $files = Get-PnPFolderItem -ItemType File -FolderSiteRelativeUrl "Shared Documents/SubFolderA/SubFolderB" -recursive
PS C:\users\user\Documents> $list = get-pnplist "Documents"
PS C:\users\user\Documents> $file = $files[0]
PS C:\users\user\Documents> $file.Exists
True
PS C:\users\user\Documents> $file.name
Redacted (Signed).pdf
PS C:\users\user\Documents> $fileListItem = Get-PNPFile -url $file.ServerRelativeUrl -AsListItem
PS C:\users\user\Documents> Set-PnPListItem -List $list -Identity $fileListItem.Id -Values $values -UpdateType "SystemUpdate"
Set-PnPListItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Set-PnPListItem -List $list -Identity $fileListItem.Id -Values $value ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPListItem], NullReferenceException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Lists.SetListItem
PS C:\users\user\Documents> $values

Name                           Value
----                           -----
Company                        Records|Companies|Moa Nickel
DocumentType                   Records|Document Type|Minutes
Topic                          {Records|Topics|EHS, Records|Topics|EH&S}


PS C:\users\user\Documents> $list

Title     Id                                   Url
-----     --                                   ---
Documents 573b4f4e-dda5-43af-840c-389c9ea8aab9 /sites/Records/Shared Documents


PS C:\users\user\Documents> $fileListItem.Id
653
PS C:\users\user\Documents> $values["Topic"].gettype()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     String[]                                 System.Array


PS C:\users\user\Documents> $topicMmsArray = @("Records|Topics|EHS","Records|Topics|Metals")
PS C:\users\user\Documents> $values = @{"Topic"=$topicMmsArray}
PS C:\users\user\Documents> $values

Name                           Value
----                           -----
Topic                          {Records|Topics|EHS, Records|Topics|Metals}


PS C:\users\user\Documents> Set-PnPListItem -List $list -Identity $fileListItem.Id -Values $values -UpdateType "SystemUpdate"
Set-PnPListItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Set-PnPListItem -List $list -Identity $fileListItem.Id -Values $value ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPListItem], NullReferenceException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Lists.SetListItem


PS C:\users\user\Documents> $list = get-pnplist "Documents" -Includes "Fields"
PS C:\users\user\Documents> $list.fields | ?{$_.Title -eq "Topic"}

Title InternalName Id
----- ------------ --
Topic Topic        59c0142d-cdda-4ce6-9bb7-a00d5edea4fa


PS C:\users\user\Documents> $f = $list.fields | ?{$_.Title -eq "Topic"}
PS C:\users\user\Documents> $f.AllowMultipleValues
False
PS C:\users\user\Documents> $f.TypeAsString
TaxonomyFieldType

PS C:\users\user\Documents> $topicMmsArray = @("Records|Topics|EHS")
PS C:\users\user\Documents> $values = @{"Topic"=$topicMmsArray}
PS C:\users\user\Documents> Set-PnPListItem -List $list -Identity $fileListItem.Id -Values $values -UpdateType "SystemUpdate"
WARNING: You are trying to set multiple values in a single value field. Skipping values for field "{field.InternalName}"

Id    Title                                              GUID
--    -----                                              ----
653                                                      9b9d8314-55db-47c3-85d7-b95fd998558d

PS C:\users\user\Documents> $values = @{"Topic"="Records|Topics|EHS"}
PS C:\users\user\Documents> Set-PnPListItem -List $list -Identity $fileListItem.Id -Values $values -UpdateType "SystemUpdate"

Id    Title                                              GUID
--    -----                                              ----
653                                                      9b9d8314-55db-47c3-85d7-b95fd998558d

PS C:\users\user\Documents> $values = @{"Topic"="Records|Topics|Metals"}
PS C:\users\user\Documents> Set-PnPListItem -List $list -Identity $fileListItem.Id -Values $values -UpdateType "SystemUpdate"

Id    Title                                              GUID
--    -----                                              ----
653                                                      9b9d8314-55db-47c3-85d7-b95fd998558d
```


Small side note:
https://github.com/pnp/powershell/blob/4fb56798ddf34d88f6b2b7a33c74ef73210952e9/src/Commands/Utilities/ListItemHelper.cs#L152
Seems to be missing the "$" prefix for the field insertion

This is the selected metadata field tag on the column settings for Topic on the Documents library.
![image](https://user-images.githubusercontent.com/3208188/153059691-adaecb29-0d6d-434a-983c-a0a225458d5b.png)

The previous code on the bug submission contained the method of adding the topics to the taxonomy store.

From the above you can see everything going in has values, and it works fine when setting each value individually, just when an array goes in it seems to fail

**Comment by SPDEVGUY** [comment]
PS > $PSversionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.4583
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.4583
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by SPDEVGUY** [comment]
It displays this warning:
WARNING: You are trying to set multiple values in a single value field. Skipping values for field "{field.InternalName}"

When you pass an array in with only one value (expected), but will crash out with an object null if that array has more than one value within it.

(Also, just incase, I set the field to single value only to try and get it to throw that message for testing to see how far it gets into the code, I'm not trying to set multiple values on a single value field and having it explode and asking why =P)

**Comment by SPDEVGUY** [comment]
```
PS C:\users\user\Documents> $values["Topic"] = @("Records|Topics|EHS")
PS C:\users\user\Documents> Set-PnPListItem -List $list -Identity $fileListItem.Id -Values $values -UpdateType "SystemUpdate"

Id    Title                                              GUID
--    -----                                              ----
653                                                      9b9d8314-55db-47c3-85d7-b95fd998558f


PS C:\users\user\Documents> $values["Topic"] = @("Records|Topics|EHS","Records|Topics|Effluent Charges")
PS C:\users\user\Documents> Set-PnPListItem -List $list -Identity $fileListItem.Id -Values $values -UpdateType "SystemUpdate"

Id    Title                                              GUID
--    -----                                              ----
653                                                      9b9d8314-55db-47c3-85d7-b95fd998558f


PS C:\users\user\Documents> $values["Topic"] = @("Records|Topics|EHS", "Records|Topics|EH&S")
PS C:\users\user\Documents> Set-PnPListItem -List $list -Identity $fileListItem.Id -Values $values -UpdateType "SystemUpdate"
Set-PnPListItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Set-PnPListItem -List $list -Identity $fileListItem.Id -Values $value ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPListItem], NullReferenceException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Lists.SetListItem
```
![image](https://user-images.githubusercontent.com/3208188/153691641-67c0586f-738c-4c04-bdb9-5d301910dde1.png)

It appears to have problems with the Ampersand (&) in a metadata field value name.  

I think that is the source of the bug.

```
PS C:\users\user\Documents> $values["Topic"] = @("Records|Topics|EH&S")
PS C:\users\user\Documents> Set-PnPListItem -List $list -Identity $fileListItem.Id -Values $values -UpdateType "SystemUpdate"
Set-PnPListItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Set-PnPListItem -List $list -Identity $fileListItem.Id -Values $value ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPListItem], NullReferenceException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Lists.SetListItem
```

https://github.com/pnp/powershell/blob/4fb56798ddf34d88f6b2b7a33c74ef73210952e9/src/Commands/Utilities/ListItemHelper.cs#L124

taxonomyItem = clonedContext.Site.GetTaxonomyItemByPath(arrayItem as string); //Likely returning null
Then:
terms.Add(new KeyValuePair<Guid, string>(taxonomyItem.Id, taxonomyItem.Name));  //Throws null if used, as it wasn't checked to actually exist.

So I think that is it... this ticket actually contains 3 bugs:

- The warning doesn't show the field name, the token in the text doesn't resolve because it isn't using $"{fieldName}"
- When you have a term path with an Ampersand it fails to resolve
- If the set function receives a non-existent term field by string path it doesn't check for null and report that it wasn't found.

@gautamdsheth

**Comment by gautamdsheth** [comment]
Awesome observation , have sent a PR to fix this issue. It will now warn users.
Also, seems to be encoding issue in your code related to term name.

It needs to be `TestGroup|MyTopics|EH＆S` instead of `TestGroup|MyTopics|EH&S` .  Notice that the ampersand symbol is a bit different.
Not sure why SharePoint store `&` symbol a bit differently, but entering it like that works. 

Also, you can go to that specific term in termstore and copy the default label value to test:

![image](https://user-images.githubusercontent.com/8832018/168671603-9a03e504-39ce-4873-b5b7-a4e997cb1579.png)

**Comment by gautamdsheth** [comment]
hi @SPDEVGUY , have managed to fix the issue.
It will be available in tomorrow's nightly build, thanks for spotting it and raising it here :)
