### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by NPrice99** [pnp/powershell#16]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
Should work without any issues

### Actual behavior 
Please describe what you see instead. Please provide samples of HTML output or screenshots
![image](https://user-images.githubusercontent.com/8484048/96917836-45e72b00-14a1-11eb-9368-fff1ec893f3e.png)

### Steps to reproduce behavior

![image](https://user-images.githubusercontent.com/8484048/96917900-5c8d8200-14a1-11eb-8bec-ed51d5853c9a.png)

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name sharepointpnppowershell* -ListAvailable```)
![image](https://user-images.githubusercontent.com/8484048/96918041-965e8880-14a1-11eb-9062-b4a66e704ab0.png)

**Comment by erwinvanhunen** [comment]
I don't really regard this is a bug. It's functionality from PowerShell Get which is the module that does the installation. One cannot have multiple modules installed that provide the same cmdlet names. And in this case I assume you have the Legacy version installed too I assume.

Uninstall that one first with `Uninstall-Module -Name SharePointPnPPowerShellOnline -AllVersions -Force`
and then install the new module.

**Comment by NPrice99** [comment]
UNinstall fails with the same issue 👍 
![image](https://user-images.githubusercontent.com/8484048/97028441-0cbbc300-1554-11eb-8a8c-9c2e7e8f731e.png)
