### ISSUE TITLE
[BUG] New-PnPUPABulkImportJob: not processing custom User Profile property (Get-PnPUPABulkImportStatus status stuck in processing)

### ISSUE THREAD

**Issue by Maurikrm** [pnp/powershell#1602]
### Reporting an Issue or Missing Feature
Using the New-PnPUPABulkImportJob doesn't process the custom User Profile property from the json file. Checking the import state with Get-PnPUPABulkImportStatus -shows "processing". The User Profile property in SharePoint Online isn't updated either.

### Expected behavior 
An updated custom property in the users User Profile property

### Actual behavior 
![image](https://user-images.githubusercontent.com/28625462/152515871-3aaba1ae-be5e-43af-838f-e5ca71e9127b.png)

### Steps to reproduce behavior
$UserName = "<account>@<tenant>.onmicrosoft.com"
$PassWord = "<password>" | ConvertTo-SecureString -AsPlainText
$SPOCredential = New-Object System.Management.Automation.PSCredential ($UserName, $PassWord)

Connect-PnPOnline -Url https://tenant>.sharepoint.com/sites/<sitecollection> -Credentials $SPOCredential -ReturnConnection
New-PnPUPABulkImportJob -Url "https://<tenant>.sharepoint.com/sites/<sitecollection>/Shared documents/ProfileSample.json" -IdProperty "idname" -UserProfilePropertyMapping @{"customproperty"="CustomProperty"}

### What is the version of the Cmdlet module you are running?
PnP.Powershell 1.9.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
What kind of custom property is that ? 

String based, multi-value properties and taxonomy based properties are not supported by the API. This is the limitation of the API.

https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/bulk-user-profile-update-api-for-sharepoint-online#frequently-asked-questions

**Comment by Maurikrm** [comment]
I am trying to import a integer property with a length of 9 characters
