### ISSUE TITLE
[BUG] - Invoke-PnPBatch: Cannot convert a primitive value to the expected type 'Edm.String'. See the inner exception for more details.

### ISSUE THREAD

**Issue by Luukv93** [pnp/powershell#1609]
### Reporting an Issue or Missing Feature
I try to invoke integer values into a Sharepoint list column of data type "Number" or "Integer" (I tried both). Using Invoke-PnPBatch batching i receive an error: `Invoke-PnPBatch: Cannot convert a primitive value to the expected type 'Edm.String'. See the inner exception for more details.`. When not using batching the operation succeeds and all integer numbers get inserted into the list.

### Expected behavior 
I expect the batch to be inserted into the sharepoint list. When invoking the values without batching they do get inserted into the sharepoint list.

### Actual behavior 
I receive an error: `Invoke-PnPBatch: Cannot convert a primitive value to the expected type 'Edm.String'. See the inner exception for more details.`

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)
`
New-PnpList -Title $SharepointListName -Template GenericList -OnQuickLaunch -Url Lists/$SharepointListName

Add-PnpField -List $SharepointListName -DisplayName $SharePointColumn -InternalName $SharePointColumn -Type Number -AddToDefaultView

$SysIds = 
@"
[
  {
    "Sys_id": 39345
  },
  {
    "Sys_id": 24238
  },
  {
    "Sys_id": 49065
  },
  {
    "Sys_id": 39347
  },
  {
    "Sys_id": 49066
  },
  {
    "Sys_id": 39348
  },
  {
    "Sys_id": 39349
  },
  {
    "Sys_id": 49067
  },
  {
    "Sys_id": 24239
  },
  {
    "Sys_id": 49068
  },
  {
    "Sys_id": 39350
  }
]
"@

$SysJson = $SysIds | ConvertTo-Json | ConvertFrom-Json
$SharePointListName = "Test"
$PnpListName = (Get-PnPList $SharepointListName)
$UploadBatch = New-PnPBatch

$SysJson | ForEach-Object {
  $SysHash = @{}
  $SysRow = $_
  $SysRow.psobject.properties | ForEach-Object{$SysHash[$_.Name] = $_.Value}
  Add-PnpListItem -List $PnpListName -Values $SysHash -Batch $UploadBatch

}

Invoke-PnPBatch -Batch $UploadBatch -StopOnException`
### What is the version of the Cmdlet module you are running?
PnP.PowerShell 1.9.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by NuriDurmus** [comment]
I had the same problem but I could only solve this issue using toString() method for values

**Comment by NuriDurmus** [comment]
@gautamdsheth unfortunately same error

**Comment by LastGunslinger** [comment]
This is still very much an issue in version 1.10.0, which I don't understand because the SharePoint API has not changed in years. Updating a number field is an issue that has already been solved, but I'm always uncomfortable using batching in the PnP.PowerShell library because of strange serialization issues like this and #678.

**Comment by gautamdsheth** [comment]
Hi, have managed to fix the issue, it will be available in tomorrow's nightly !
Thanks for spotting the issue and raising it here :)

**Comment by OASISfr** [comment]
Hi, i have the same issue in version 3.3.0

My data to update is a double.

I am french and my PSculture is fr-FR and the solution which work is to convert the value into string with culture EN-US because the separator in french is comma an not dot.

My code :

$batch = New-PnPBatch
foreach($row in ($rows | select -first 200)) {
    Set-PnPListItem -List "List Name" -Identity $row.Id -Values @{DoubleValue=$row.DoubleValue.ToString(([cultureinfo]"en-us"))} -Batch $batch 
}
Invoke-PnPBatch -Batch $batch
