### ISSUE TITLE
[BUG] Set-PnPTenantSite -NoScriptSite alias for -DenyAddAndCustomizePages not valid

### ISSUE THREAD

**Issue by rmillener** [pnp/powershell#161]
### Expected behavior 
Running the following should work
`Set-PnPTenantSite -Url $siteUrl -NoScriptSite:$false`

### Actual behavior 
An error is returned
`Set-PnPTenantSite : Parameter set cannot be resolved using the specified named parameters.`

### What is the version of the Cmdlet module you are running?
1.2.4-nightly

### Which operating system/environment are you running PnP PowerShell on?
- [ x ] Windows

If this is intended, [the example](https://github.com/pnp/powershell/blob/4e8bc03ed3976c4bccb826da1f0892777f11fc6d/documentation/Set-PnPTenantSite.md#example-5) needs updating.

**Comment by erwinvanhunen** [comment]
The NoScriptSite parameter is not present on Set-PnPTenantSite, which explains the error you are getting. You have to use the Set-PnPSite cmdlet instead. The difference is that Set-PnPTenantSite the PnP version of Set-SPOSite and thus matches the parameters of Set-SPOSite. The Set-PnPTenantSite also works on tenant admin level where is Set-PnPSite works directly towards the site itself.
