### ISSUE TITLE
[FEATURE] New cmdlet Get-PnPFlowRun - see runs of a particular Flow

### ISSUE THREAD

**Issue by LeonArmston** [pnp/powershell#1610]
**Is your feature request related to a problem? Please describe.**
Suggestion for a new PnP PowerShell cmdlet (Get-PnPFlowRun) that they already have in the M365 CLI to see runs of a specific Flow.

- https://github.com/pnp/cli-microsoft365/blob/main/src/m365/flow/commands/run/run-list.ts
- https://github.com/pnp/cli-microsoft365/blob/main/docs/docs/cmd/flow/run/run-list.md

**Describe the solution you'd like**
A PnP PowerShell cmdlet to see Flow Runs for a specific Flow.

**Describe alternatives you've considered**
Use M365 CLI

**Additional context**

Thanks

**Comment by robertcaretta** [comment]
Interested in this. Does this work for a power platform tenant admin? Or do you need to be added as an "owner" of a flow before you can see this information?

**Comment by milanholemans** [comment]
Nice idea! I will try to implement this.

**Comment by gautamdsheth** [comment]
@LeonArmston , @robertcaretta - am closing this feature request !

@milanholemans submitted a PR which has been merged and the cmdlet `Get-PnPFlowRun` will be available in tomorrow's nightly :)

**Comment by LeonArmston** [comment]
Thanks - this great news!

Excellent work @milanholemans - this is awesome!

**Comment by sp00kyDD** [comment]
Great cmdlet, but how can I get status of a specific flow or only retrieve failed flows?

**Comment by milanholemans** [comment]
Hi @sp00kyDD, when you read the `Properties/Status` property you can check if the flow run is running, failed, or cancelled.

```powershell
$run = Get-PnPFlowRun -Environment $environment -Flow $flow -Identity $id
Write-Host $run.Properties.Status # Prints Succeeded, Running, Failed, or Cancelled
```

**Comment by sp00kyDD** [comment]
> Hi @sp00kyDD, when you read the `Properties/Status` property you can check if the flow run is running, failed, or cancelled.
> 
> ```powershell
> $run = Get-PnPFlowRun -Environment $environment -Flow $flow -Identity $id
> Write-Host $run.Properties.Status # Prints Succeeded, Running, Failed, or Cancelled
> ```

@milanholemans Thank you! Works like a charm. Didn't know that.

**Comment by sp00kyDD** [comment]
Can I somehow filter upfront with Get-PnPFlowRun for failed flow runs?
Or do I need to retrieve all flow runs first and filter afterwards over Properties.Status for failed ones?

**Comment by milanholemans** [comment]
I'm afraid that there's no filter possibility in PnP.PowerShell.

**Comment by sp00kyDD** [comment]
> I'm afraid that there's no filter possibility in PnP.PowerShell.

Could this be a new feature request?
