### ISSUE TITLE
Docs bug - Remove-PnPContentTypeFrocumentSet in TOC

### ISSUE THREAD

**Issue by sympmarc** [pnp/powershell#1628]
### Reporting an Issue or Missing Feature
In the left nav for the cmdlets at https://pnp.github.io/powershell/, the cmdlet `Remove-PnPContentTypeFromDocumentSet` is spelled `Remove-PnPContentTypeFrocumentSet`. I'd do a PR for it, but I can't figure out where it comes from. Let me know for the next time!

**Comment by KoenZomers** [comment]
Well noticed @sympmarc. I also cannot figure out where it is coming from. Let me discuss it within the team.

**Comment by erwinvanhunen** [comment]
Good catch indeed Marc (aka as Hawkeye)! We found the cause to be an issue in how we generated the TOC for the site. We fixed this and reran the code to generate the site. All good now.
