### ISSUE TITLE
[BUG] Get-PnPTerm -Identity <name> does not work

### ISSUE THREAD

**Issue by dbahnms** [pnp/powershell#1629]
An error occurs by using Get-PnPTerm -Identity <name> -TermSet $global:TermSet -TermGroup $global:TermGroup.
The reason for using it is to optimize the performance to avoid getting all records from Termset.
Guid isn´t available. It´s used for an synchronisation job between 2 systems (SharePoint isn´t the leading system). 

### Expected behavior 
Get record by name. Working like described here:
https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpterm?view=sharepoint-ps

### Actual behavior 
<img width="496" alt="image" src="https://user-images.githubusercontent.com/84786547/153872835-68980163-6e99-484e-bef8-ba0bfa2742cd.png">

### Steps to reproduce behavior
Get-PnPTerm -TermSet $global:TermSet -TermGroup $global:TermGroup # works but all record sets
Get-PnPTerm -Identity 0c917f22-064f-4574-9a29-4bd0e23829fc -TermSet $global:TermSet -TermGroup $global:TermGroup # works but ID necessary
Get-PnPTerm -Identity $title -TermSet $global:TermSet -TermGroup $global:TermGroup # error

### What is the version of the Cmdlet module you are running?
<img width="678" alt="image" src="https://user-images.githubusercontent.com/84786547/153873250-eb1beba6-b606-4d3c-98ed-172e741a6bca.png">

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Hi , cant seem to reproduce the issue with 1.9.0 release :

![image](https://user-images.githubusercontent.com/8832018/155305216-8782d350-a87e-4fd3-b282-7fed2af109c4.png)

Can you try with another term or a different tenant maybe ? Also, could be an issue with the term itself ?

**Comment by dbahnms** [comment]
It´s my mistake. "-Recursive" is the keyword. If you search for terms which are not at first level, you will gain the error above (null expected but error occurs).
