### ISSUE TITLE
[BUG]PnP PowerShell errors occurring in Azure Automation

### ISSUE THREAD

**Issue by ShuheiIwama** [pnp/powershell#163]
Hello,
When I process the following PnP PowerShell with Azure Automation, sometimes an error occurs.
There are two types of errors, and we don't know under what conditions they are differentiated.
It seems to happen when I run Azure Automation at the same time, does anyone know the cause of this? Is this a bug?

**Environment**

- Azure Automation Runbook PowerShell
- SharePointPnPPowerShellOnline 3.26.2010.0

**Script**
line
_108 $Web = Get-PnPWeb -Includes RegionalSettings.TimeZones
109 $NewTimeZone = $Web.RegionalSettings.TimeZones | Where {$_.Description -eq $TimeZone}
110 [int]$NewTimeZoneId = $NewTimeZone.Id_

*$TimeZone contains values such as "(UTC-12:00) International Date Line West".

**Error Description Pattern 1**
_Get-PnPWeb : The 'subQuery' argument is invalid. At line:108 char:8 + $Web = Get-PnPWeb -Includes RegionalSettings.TimeZones + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : WriteError: (:) [Get-PnPWeb], ArgumentException + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.GetWeb_

**Error Description Pattern 2**
_Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Int32". At line:110 char:1 + [int]$NewTimeZoneId = $NewTimeZone.Id + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : MetadataError: (:) [], ArgumentTransformationMetadataException + FullyQualifiedErrorId : RuntimeException_

I'm looking forward to working with you.
Thanks.

**Comment by erwinvanhunen** [comment]
This is a hard one to figure out. Does this error only occur when running in an Azure Automation Runbook?

**Comment by ShuheiIwama** [comment]
> This is a hard one to figure out. Does this error only occur when running in an Azure Automation Runbook?

Yes, only Azure Automation Runbook.
As shown in the following image, an error occurs when the Runbook is executed concurrently.
![image](https://user-images.githubusercontent.com/77622455/105697944-9199ec80-5f48-11eb-8490-7d99bea20664.png)
![image](https://user-images.githubusercontent.com/77622455/105697990-9fe80880-5f48-11eb-8625-4e54e2352a0c.png)

This script is used to get the "timezoneID" from the time zone string such as "(UTC-12:00) International Date Line West".
Is it a script problem? Or session problem?

**Comment by erwinvanhunen** [comment]
I'm more thinking of a session problem. The snippet you shared is as such okay. Question: the $TimeZone variable, how to acquire that one? Is it hardcoded provided? There is a Get-PnPTimeZoneId cmdlet which can help to figure out Ids of a timezone. 

```powershell
$timezone = Get-PnPTimeZoneId -Match "international date line west"
Write-Host $timezone.Id
```

**Comment by ShuheiIwama** [comment]
> Question: the $TimeZone variable, how do you acquire that one? Is it hardcoded provided?

The $TimeZone variable is provided in hardcode. Since the hard code is in the form of "(UTC-05:00) Eastern Time (US and Canada)", I think it is difficult to use Get-PnPTimeZoneId.

Is there any other way to get the time zone ID other than Get-PnPTimeZoneId?
If it is a session issue, is there any way to work around it?

**Comment by erwinvanhunen** [comment]
The thing is that we -assume- it's a session issue. But not 100% sure. There can be some threading conflicts, but it's hard to reproduce. The issue 100% only occurs when running the script in parallel? As such all the code we use is thread safe and should not produce any issues when running multi-threaded. You could try though to rewrite your code a bit. If that works we know a bit better where to look for:

```powershell
$Context = Get-PnPContext
$Web = Get-PnPWeb
$Context.Load($Web.RegionalSettings.TimeZones)
Invoke-PnPQuery
$NewTimeZone = $Web.RegionalSettings.TimeZones | Where {$.Description -eq $TimeZone}
[int]$NewTimeZoneId = $NewTimeZone.Id
```

Just to make sure: do you run this for several webs? And do you retrieve the timezones for every web? As that is not needed. The TimeZoneId is -always- the same. So you could create a lookup table or something instead that matches your search strings. E.g. regardless of the site or tenant, if the timezone is `(UTC-12:00) International Date Line West` then the id is -always- 39.

Alternatively you can do some scripting 'magic'. If your $TimeZone variable always contains something like `(UTC-12:00) International Date Line West`, then you can consider using this:

```powershell
$LookupValue = $TimeZone.Split(") ")[1] # notice the space after the )
$NewTimeZoneId = (Get-PnPTimeZoneId -Match $LookupValue).Id
```

The snippet above -only- works if the TimeZone string is formatted as in the example. E.g. I split the string and then use the second part to lookup the ID using Get-PnPTimeZoneId. No server calls needed then.
