### ISSUE TITLE
Get-PnPTenantSite -Filter "Template -ne 'GROUP#0'"

### ISSUE THREAD

**Issue by NGseb** [pnp/powershell#164]
**Is your feature request related to a problem? Please describe.**
yes, i need to retreive all sites that do not belong to modern sites (excluding template GROUP#0 is the closest i've found)

**Describe the solution you'd like**
have the template property usable 

**Describe alternatives you've considered**
using SPO or deprecated PNP.

**Comment by erwinvanhunen** [comment]
As such this is not really an issue but more a question .Please post these in the discussion section of this repository.

But to get you up and running

```powershell
$templates = @("GROUP#0","SITEPAGEPUBLISHING#0","APPCATALOG#0","TEAMCHANNEL#0","SRCHCEN#0")
Get-PnPTenantSite | ?{!$templates.Contains($_.Template)}
```

You might have to adjust the templates list more in your case. The list of templates that designates a modern site or a site you cannot upgrade (yet) can change anytime, so there is no 'easy' way to retrieve these sites.
