### ISSUE TITLE
 [BUG] Issue with Move-PnPFile in the same library

### ISSUE THREAD

**Issue by gautamdsheth** [pnp/powershell#165]
## Reporting an Issue or Missing Feature
Getting exception while moving files in the same library to a different folder.

### Expected behavior 
I should be able to move the file in the same library but in a different folder without error

### Actual behavior 
Getting this error:

`Move-PnPFile : The remote server returned an error: (500) Internal Server Error.`

After executing `Get-PnPException`, I get this detail:

```
Message          : The remote server returned an error: (500) Internal Server Error.
Stacktrace       :    at System.Net.HttpWebRequest.GetResponse()
                      at Microsoft.SharePoint.Client.SPWebRequestExecutor.Execute()
                      at Microsoft.SharePoint.Client.Web.WebUrlFromFolderUrlDirect(ClientContext context, Uri folderFullUrl)
                      at PnP.PowerShell.Commands.Files.MoveFile.ExecuteCmdlet()
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()
```

### Steps to reproduce behavior
```
$sourceUrl = "/sites/customTest/SitePages/page1.aspx"
$targetUrl = "/sites/customTest/SitePages/AnotherFolder/page2.aspx"
Move-PnPFile -SourceUrl $sourceUrl -TargetUrl $targetUrl -Overwrite -Force
```

### What is the version of the Cmdlet module you are running?
1.2.4-nightly

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
Thanks Gautam. Fixed and it will be available in the next nightly build.

**Comment by gautamdsheth** [comment]
@erwinvanhunen - Thank you :)
