### ISSUE TITLE
PNP Module should show an error if the site is not valid

### ISSUE THREAD

**Issue by farismalaeb** [pnp/powershell#1652]
When connecting to a SharePoint site with a wrong URL, the module is not returning any error and it looks like the connection was success. 
````Connect-PnPOnline -Url 'https://Mytendnance.sharepoint.com/NotExistSite' -Credentials $Username````
there won't be any error that the site does not exist. instead, all the other cmdlets such as Get-PNPList return an error that does not reflect the original issue.

It will be good to for the PNP module to check if the site is actually exist

**Comment by farismalaeb** [comment]
On PowerShell 7 its seems to be working fine, but 5.1 ISE not.

**Comment by KoenZomers** [comment]
Understood @farismalaeb . PR https://github.com/pnp/powershell/pull/1924 will add an optional `-ValidateConnection` to `Connect-PnPOnline` which will allow you to do this.

**Comment by gautamdsheth** [comment]
Thanks for raising the issue.
Closing this as the PR is now merged, please use the latest nightly build available tomorrow where the fix will be available !
