### ISSUE TITLE
Issues with installing Provider Hosted SharePoint APP using PNP PS[BUG]

### ISSUE THREAD

**Issue by pavanasknani** [pnp/powershell#1657]
The issue with installing SharePoint Hosted APP using below  PNP Script  

Connect-PnPOnline -url $SiteURL -ClientID $ClientID  -ClientSecret $ClientSecret

Install-PnPApp -Identity $RERHostedAppId.

Behavior : 
 - After executing the script, the app starts installing in SP Site, but it takes a long time to install, hence a time-out error occurs.
 - It gets installed instantly on clicking retry.

Note: Above script works properly, if we install SPFX App in place of Hosted App or use -UseWebLogin or interactive in place of client and secret.

It's a provider hosted app
How did you get app-only token?  => appregnew
Uploaded in tenant app catalog.
![AppInstallIssue1](https://user-images.githubusercontent.com/45825267/155982688-d1d9335a-167a-417a-8d7e-e2b22737fd6e.jpg)
![AppInstallIssue2](https://user-images.githubusercontent.com/45825267/155982695-40928935-15b4-4d96-8645-c4ba319dffd4.jpg)
![AppInstallIssue](https://user-images.githubusercontent.com/45825267/155982698-1e0e9541-97f2-4417-92c8-d75b2fcad034.jpg)

**Comment by akrijnen** [comment]
I can confirm this issue. I registered by App in the App Registrations in Azure. Added permissions with appinv.aspx for /content/tenant with FullControl. Always runs in a time out.

**Comment by gautamdsheth** [comment]
Instead of the appinv.aspx which is now kinda deprecated , can you please use the standard Azure AD permissions and try ? You can create a new Azure AD with `Register-PnPAzureADApp` cmdlet and assign permissions and then use certificates to authenticate:

https://pnp.github.io/powershell/cmdlets/Register-PnPAzureADApp.html

**Comment by veronicageek** [comment]
Closing as no response.
