### ISSUE TITLE
[FEATURE] Remove-PnPField - Batch Removal Using Array

### ISSUE THREAD

**Issue by robertcaretta** [pnp/powershell#1661]
**Is your feature request related to a problem? Please describe.**
Would it be possible to add the ability to send an array of site columns to be removed in one command?

**Describe the solution you'd like**
Remove multiple site columns in one command. 

Example 1:
Remove-PnPField -Identity "Speakers","Stereo","Headphones"

Example 2:
$fields = @("Speakers","Stereo","Headphones")
Remove-PnPField -Identity $fields

**Describe alternatives you've considered**
Using the command as it is and looping over each site column to be removed.

**Additional context**
N/A.

**Comment by gautamdsheth** [comment]
hi @robertcaretta , have added batch parameter to `Remove-PnPField` cmdlet. It will be available in tomorrow's nightly as well as next major version when we release it.

Thanks for adding this feature request !
