### ISSUE TITLE
[BUG] Cannot use Get-PnPProperty to get properties of Teams Tabs

### ISSUE THREAD

**Issue by ToddKlindt** [pnp/powershell#1669]
### Reporting an Issue or Missing Feature
Cannot use Get-PnPProperty to get properties of Teams Tabs

### Expected behavior 
I should be able to hydrate the properties of a Teams Tabs with Get-PnPProperty

### Actual behavior 
I get this sad error message.
![image](https://user-images.githubusercontent.com/2659747/156466184-4ff18964-f3c8-479b-85eb-501fb3663af2.png)
It says, "Get-PnPProperty : Cannot bind parameter 'ClientObject'. Cannot convert the
"PnP.PowerShell.Commands.Model.Teams.TeamTab" value of type
"PnP.PowerShell.Commands.Model.Teams.TeamTab" to type "Microsoft.SharePoint.Client.ClientObject"."

Then it tells me I'm ugly and no one likes me. 

### Steps to reproduce behavior
Connect-PnPOnline -Url https://m365x995492-admin.sharepoint.com
Get-PnPTeamsTab -Team "SOC Team" -Channel "General" | Tee-Object -Variable c
Get-PnPProperty -ClientObject $c[0] -Property TeamsApp

### What is the version of the Cmdlet module you are running?
1.9.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
@ToddKlindt - this is by design. It is designed to work with SharePoint CSOM only.

If you look at the source code, we check whether the CSOM property is available or not , and load it if required.

https://github.com/pnp/powershell/blob/e06c687263f07f3d2908970a2cac42ece6f71d46/src/Commands/Base/GetProperty.cs#L34

**Comment by ToddKlindt** [comment]
Okay, I'll buy that. :) Is there an alternative method for me to get the TeamsApp property for a Teams Tab? I know I can get it with the Graph SDK, but that module is a mess. I avoid it if possible.

**Comment by gautamdsheth** [comment]
You can get it using this commands:

```
$tabs = Get-PnPTeamsTab -Team "<team -name>" -Channel "<channel-name>"
$teamsTabData = Get-PnPTeamsTab -Identity $tabs[0].Id -Team "<team -name>" -Channel "<channel-name>"
$teamsData.TeamsApp
```

There are also other properties exposed, you can check them :

![image](https://user-images.githubusercontent.com/8832018/156888720-5231c39f-3473-4565-9eb9-7347f42cddd2.png)

**Comment by ToddKlindt** [comment]
That got me where I needed to go. Thanks @gautamdsheth .
