### ISSUE TITLE
Copying files with % or # needs to be encoded to be used with Copy-PnPFile / CreateCopyJob

### ISSUE THREAD

**Issue by pbjorklund** [pnp/powershell#167]
**Is your feature request related to a problem? Please describe.**
When copying a file with % or # in the filename the targetUrl needs to be encoded to work with Copy-PnPFile/CreateCopyJob

```Copy-PnPFile -SourceUrl $encodedFileRef -TargetUrl $newTargetFolderUrl -OverwriteIfAlreadyExists -Force -NoWait```
**Describe the solution you'd like**

Encode site/lib/file URIs like below

```
Function UrlEncodePath($path) {
    $fileRefParts = $path -split '/'
    $x = $fileRefParts | % { [uri]::EscapeDataString($_) }
    $encodedFileRef = $x -join "/"
    return $encodedFileRef
}
```
It would be interesting if the library itself managed to resolve this for users so they don't have to go through the confusion I did.

Btw, on https://docs.microsoft.com/en-us/sharepoint/dev/apis/spod-copy-move-api it says _SharePoint & OneDrive Copy and Move API replaces the CreateCopyJob API. The CreateCopyJob API has been deprecated._. I can't for the life of me figure out if that means that the CreateCopyJob that PnP uses is deprecated or not... :)

**Comment by erwinvanhunen** [comment]
The documentation is a bit confusing, indeed, regarding that API. We're using the SPO REST API behind the scenes as you might have noticed and that is fully supported.

Regarding the special characters: We've updated the code to do the work for you, e.g. no need to use the manual encoding anymore. The encoding is only needed for a check we do internally, the actual copy job itself does not require an encoded string. It will be avialable on 1.2.5-nightly.

**Comment by pbjorklund** [comment]
Sweet!
