### ISSUE TITLE
[BUG] Update-PnPApp and Get-PnPApp is not working for SharePoint 2019

### ISSUE THREAD

**Issue by chandaniprajapati** [pnp/powershell#1671]
### Reporting an Issue

This is a bug.

### Expected behavior 
It should work with SP2019 as well.

### Actual behavior 

While using `Get-PnPApp` and `Update-PnPApp` in SP2019, I am getting below error,

![image](https://user-images.githubusercontent.com/52065929/156761083-2a37cce2-87fc-4109-8396-76afb19a5a5f.png)

![image](https://user-images.githubusercontent.com/52065929/156756569-6176e307-279e-47ec-83e4-709a4d8cdc1f.png)

The user is already a site collection admin. And those commands are working fine with SP Online but not working with SP2019.

### Steps to reproduce behavior

```
$SiteUrl = "OnPrem Site Collection URL"
$AppID = "GUID"
Connect-PnPOnline -Url $SiteUrl -Credentials (Get-Credential)
Get-PnPApp
Update-PnPApp -Identity $AppID 
```

### What is the version of the Cmdlet module you are running?

![image](https://user-images.githubusercontent.com/52065929/156757873-52022ca4-518b-4afc-ab44-3e5c0d5dcf87.png)

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@chandaniprajapati - The module installed on your machine is the old one which supported SP on-prem + SPO but is now deprecated and not maintained anymore. PnP PowerShell (this repo) is only supporting SharePoint Online, so unfortunately we'll have to close the issue.

**Comment by chandaniprajapati** [comment]
@veronicageek - Thanks for the quick response.
