### ISSUE TITLE
[BUG] Both ConvertTo-PnPPage and ConvertTo-PnPClientSidePage in Docs

### ISSUE THREAD

**Issue by sympmarc** [pnp/powershell#1676]
### Reporting an Issue or Missing Feature

Both [ConvertTo-PnPClientSidePage](https://pnp.github.io/powershell/cmdlets/ConvertTo-PnPClientSidePage.html) and [ConvertTo-PnPPage](https://pnp.github.io/powershell/cmdlets/ConvertTo-PnPPage.html) exist in the docs. From what I can tell, `ConvertTo-PnPPage` is the current cmdlet. When I tried to use `ConvertTo-PnPClientSidePage`, each time I tried to call it, the old version of the library (`SharePointPnPPowerShellOnline`) was loaded (I have them both installed on my machine to do different things). This caused other parts of my script to break, causing me to think I was doing something wrong.

### Expected behavior 

I think only `ConvertTo-PnPPage` should be in the current docs.

### Actual behavior 
Both cmdlets are there.

**Comment by gautamdsheth** [comment]
Thanks @sympmarc for spotting it, have deleted the page. It should be gone by tomorrow :)

**Comment by rohit404404** [comment]
![image](https://user-images.githubusercontent.com/3784144/208851090-2cfc583b-ff77-490c-99c7-0f5ac452798f.png)

I still see this here. Are we saying "ConvertTo-PnPClientSidePage" is deprecated?

https://pnp.github.io/powershell/cmdlets/ConvertTo-PnPClientSidePage.html
