### ISSUE TITLE
[BUG] Set-PnPSite -Classification fails with ParameterBindingException

### ISSUE THREAD

**Issue by 216rick** [pnp/powershell#169]
Error received when trying to set site classification. 

### Expected behavior 
Site classification set to specified classification.

### Actual behavior 
Set-PnPSite : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Set-PnPSite -Classification "Open"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-PnPSite], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,PnP.PowerShell.Commands.Site.SetSite
 Parameter set cannot be resolved using the specified named parameters.

### Steps to reproduce behavior
Connect-PnPOnline <site url> -UseWebLogin
Set-PnPSite -Classification "Open"

### What is the version of the Cmdlet module you are running?
1.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
Thank you for reporting this! We fixed it and it will be available in release 1.2.6-nightly tomorrow.
