### ISSUE TITLE
Sync-PnPSharePointUserProfilesFromAzureActiveDirectory cannot handle backslash

### ISSUE THREAD

**Issue by EA12** [pnp/powershell#1692]
### Reporting an Issue 
**Bad JSON escape sequence \w**

### Expected behavior 
User Profiles with a backslash in field values should be synced.

### Actual behavior 
The CmdLet is reporting an issue: **Bad JSON escape sequence \w**

### Steps to reproduce behavior
Prepare a user profile, having e.g. a value of "Bauleiter Baulogistik (m\w\d)"  in field Title.
Execute the CmdLet
The JSON-File will be exported to the given library and the Job will start.
The job will fail and the error file has the mentioned error.

### What is the version of the Cmdlet module you are running?
1.9.59
Runtime-Version: 5.1

![image](https://user-images.githubusercontent.com/22025808/158158405-877a5c32-5a33-48fd-99bb-00bac397d236.png)

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [x] Azure Functions
- [ ] Other : please specify

**Comment by KoenZomers** [comment]
Managed to reproduce the issue and fix it. Running a test build now.

**Comment by KoenZomers** [comment]
Merged. Should be resolved in the next nightly build in a couple of hours. Thanks for reporting @EA12

**Comment by EA12** [comment]
Wonderful. Thanks for the quick response.
