### ISSUE TITLE
CustomScriptSafeDomains.Create returns "Cannot convert the "Microsoft.SharePoint.Client.ScriptSafeDomainEntityData"

### ISSUE THREAD

**Issue by djsladi** [pnp/powershell#1694]
### Reporting an Issue or Missing Feature
Error when trying to set HTML field security using latest PnP & SharePoint Online Management Shell

### Expected behavior 
Domain should be added to HTML field list

### Actual behavior 
![image](https://user-images.githubusercontent.com/39775012/158382144-97ba3264-bf76-4cd2-bfa9-7dfb314d9f9b.png)

```
Cannot convert argument "parameters", with value: "Microsoft.SharePoint.Client.ScriptSafeDomainEntityData", for "Create
" to type "Microsoft.SharePoint.Client.ScriptSafeDomainEntityData": "Cannot convert the "Microsoft.SharePoint.Client.Sc
riptSafeDomainEntityData" value of type "Microsoft.SharePoint.Client.ScriptSafeDomainEntityData" to type "Microsoft.Sha
rePoint.Client.ScriptSafeDomainEntityData"."
```

### Steps to reproduce behavior
`$Domain = [Microsoft.SharePoint.Client.ScriptSafeDomainEntityData]::new()`
`$Domain.DomainName = "test.com"`
`Connect-PnPOnline -Url $siteColl -Interactive`
`$site = Get-PnPSite -Includes CustomScriptSafeDomains`
`$site.CustomScriptSafeDomains.Create($Domain)`

### What is the version of the Cmdlet module you are running?
1.9.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Seems to work fine at my end, can you please try with the latest 1.10 version as well and check ? 

You also need to execute `Invoke-PnPQuery` after `$site.CustomScriptSafeDomains.Create($Domain)` to add this to the field security list.

**Comment by djsladi** [comment]
![image](https://user-images.githubusercontent.com/39775012/173780461-6ac32129-7d93-47f5-b962-de5f81e89b92.png)

No, it's not working... :-(

> Seems to work fine at my end, can you please try with the latest 1.10 version as well and check ?
> 
> You also need to execute `Invoke-PnPQuery` after `$site.CustomScriptSafeDomains.Create($Domain)` to add this to the field security list.

**Comment by katjones23** [comment]
I'm receiving the same error today with the same syntax @djsladi has, though it worked fine yesterday.

**Comment by katjones23** [comment]
I have a work around that appears to be working consistently at this time:

```
$Site = Get-PnPSite -Includes CustomScriptSafeDomains 

$object = [PSCustomObject]@{
       DomainName = <#Domain name goes here#>
}

$Site.CustomScriptSafeDomains.Create($object)
```

**Comment by djsladi** [comment]
> I have a work around that appears to be working consistently at this time:
> 
> ```
> $Site = Get-PnPSite -Includes CustomScriptSafeDomains 
> 
> $object = [PSCustomObject]@{
>        DomainName = <#Domain name goes here#>
> }
> 
> $Site.CustomScriptSafeDomains.Create($object)
> ```

This one did the trick, thank you very much! :-)
