### ISSUE TITLE
Get-PnPFile not releasing local file resource when loading file on Mac

### ISSUE THREAD

**Issue by gingemonster** [pnp/powershell#1700]
PSVersion 7.2.1
PSEdition Core
OS: macOS Catalina

### Issue
Using Get-PnPFile to download a file to the local disk causes file access issues when later used in Add-PnPFileToSiteTemplate throwing error "The process cannot access the file 'filename' because it us being used by another process".

At a guess on MacOS the stream that was used to create the file is not getting closed / recycled.

Working fine on windows, not working on Mac

### How to replicate

```
# get temporary files path
$TemplatePath = [System.IO.Path]::GetTempPath()

# connect to sharepoint site
Connect-PnPOnline -Url https://yourdomain/sites/yourexistingsite -Interactive -LaunchBrowser

# download site template
Get-PnPSiteTemplate -Out $TemplatePath + '/mysitetemplate.xml' -IncludeAllClientSidePages -PersistBrandingFiles -PersistPublishingFiles -IncludeNativePublishingFiles -Force

# download a file that exists on you site to the local disk
Get-PnPFile -ServerRelativeUrl '/sites/yourexistingsite/your document library/yourfile.txt' -Path $TemplatePath -FileName yourfile.txt -AsFile

# try and add file to site template
Add-PnPFileToSiteTemplate -Path $TemplatePath + '/mysitetemplate.xml' -Source $TemplatePath + '/yourfile.txt' -Folder '/your document library' -FileLevel Published
```

This last Add-PnpFileToSiteTemplate should now throw an error "The process cannot access the file 'yourfile.txt' because it us being used by another process"

**Comment by veronicageek** [comment]
Closing as duplicate with #1529
