### ISSUE TITLE
[BUG] Cannot Connect-PnPOnline when MFA uses PKI/client certificates

### ISSUE THREAD

**Issue by mikevasiloff** [pnp/powershell#1706]
### Reporting an Issue
Regardless if `-UseWebLogin` or `-Interactive` is used, when MFA is used **and** requires selection of a PKI/client certificate, the pop-up browser window never shows the certificate selection window.

### Expected behavior 
When connecting to a tenant that requires PKI/client certificate to authenticate, accessing in a normal browser correctly displays a PKI/client certificate selection window and facilitates successful authentication.  This same behavior is what's expected of the PowerShell module.

### Actual behavior 
Using the PowerShell module, although the pop-up browser window does _initially_ seem to work as it loads the authentication page, when it comes to selecting a PKI/client certificate it never actually shows the certificate selection window and the spinning icon just freezes.  You can click on "Sign in with other options" but that just returns you to the screen where you had to click to sign in with a PKI/client certificate.  All you can do then is just close the authentication pop up window which of course fails to connect to the site.
![image](https://user-images.githubusercontent.com/8918397/159006627-a81323bc-3471-4679-bc3f-e709bd3ff390.png)

### Steps to reproduce behavior
`Connect-PnPOnline https://dod365.sharepoint-mil.us -UseWebLogin`

At the sign-in prompt, when asked for an email address enter: _some.user@mail.mil_
When redirected to the sign-in prompt, click on the "Sign in with CAC/PIV" link below the sign-in button.
![image](https://user-images.githubusercontent.com/8918397/159007189-71ddcc1d-1b85-4cc2-8de2-9dc56b9f0b51.png)

What _should_ happen is that a client certificate (smart card) selection window is displayed, but nothing happens.

### What is the version of the Cmdlet module you are running?
1.9.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

### Potential fix
What we've found is that if you change the default value for `scriptErrorsSuppressed` to `false` in the [GetWebLoginClientContext function](https://github.com/pnp/powershell/blob/dev/src/Commands/Utilities/BrowserHelper.cs#L27), then the pop-up browser window **is** able to show the PKI/client certificate selection.  But it is unclear why this parameter was set to `true` in the first place.
![image](https://user-images.githubusercontent.com/8918397/159007950-860ffdc1-56e0-4af9-bc20-6852c876fc4d.png)

**Comment by KoenZomers** [comment]
I've traced it down to this line where the issue lies with `-Interactive`:

https://github.com/pnp/powershell/blob/2f6acf1762147e09bd319934aca281f39ab8f6b5/src/Commands/Utilities/BrowserHelper.cs#L194

I can update this one to become false as well. I forgot how you tested this last time. Are you able to build your own PnP PowerShell build off of my branch to test it or did one of us provide you with a downloadable build?

**Comment by mikevasiloff** [comment]
Oh snap, thanks @KoenZomers for that quick find! Last time I did my own build to test it and could try to do the same for this as well.  I'll report back, might be a few days unfortunately.  If that ends up being the fix, do you want me to go ahead and submit another pull request for it?

**Comment by mikevasiloff** [comment]
@KoenZomers using your _Issue1706_ build from the referenced PR I was able to confirm the issue is resolved!
Using the `-Interactive` parameter now correctly prompts for a client certificate.  Thank you for tracking this down.
