### ISSUE TITLE
[BUG] Get-PnPSiteTemplate: -Configuration option is ignored

### ISSUE THREAD

**Issue by Swampen** [pnp/powershell#171]
Not sure if this is belongs here or to Provisioning Engine, but I try here first.

### Reporting an Issue or Missing Feature
When using `Get-PnPSiteTemplate` with `-Configuration` option, the configuration is ignored

### Expected behavior 
config.json:
```json
{
    "$schema":"https://aka.ms/sppnp-extract-configuration-schema",
    "handlers": [
        "Lists"
    ]
}
```
```powershell
Get-PnPSiteTemplate -Configuration .\config.json -Out .\template.xml
```
Result:
A xml document containing lists only will be exported.

### Actual behavior 
Same exact behavior as: 
```powershell
Get-PnPSiteTemplate -Out .\template.xml
```

### Steps to reproduce behavior
```powershell
Connect-PnPOnline <site>
Get-PnPSiteTemplate -Configuration .\config.json -Out .\template.xml
```

### What is the version of the Cmdlet module you are running?
1.2.4-nightly

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
Hi! This was actually an issue in the underlying PnP Framework. We fixed it and the fix will be available in the upcoming nightly build of PnP PowerShell : 1.2.6-nightly.
