### ISSUE TITLE
[BUG] SiteAlias parameter being ingored on `New-PnPSite` when using `Alias`

### ISSUE THREAD

**Issue by aglakshmi** [pnp/powershell#1712]
SiteAlias parameter of New-PnPSite is not working as expected. When I run the command as below 

New-PnPSite -Type TeamSite -Title 'Team Contoso' -Alias contoso -SiteAlias contoso-site

It is not creating the site with the URL mentioned in the SiteAlias parameter as specified in the documentation (https://pnp.github.io/powershell/cmdlets/New-PnPSite.html#example-10). Instead it creates the site using Alias parameter.

**Comment by veronicageek** [comment]
@aglakshmi - Please DO NOT delete the template when creating an issue. Answering the questions helps troubleshooting faster.

I can't reproduce your issue and I'm using `1.9.78` (nightly release). What version of the module are you using? Feel free to share screenshots if needed.

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/25181757/159723768-47130fa5-ad8c-4545-ace7-f3bb6a87892c.png">

<img width="658" alt="image" src="https://user-images.githubusercontent.com/25181757/159723855-bca4eb6d-cf7b-4db6-a01d-7af6b6881c7d.png">

**Comment by aglakshmi** [comment]
Hi Veronique,
Thank you for your quick response. 
I am using version 1.9.77

![image](https://user-images.githubusercontent.com/31091285/159774103-c377399f-9a3f-463e-9389-a19774c94a76.png)

When execute the following
Please the screenshot as below,

![image](https://user-images.githubusercontent.com/31091285/159772993-f7bb460f-a987-482c-aae0-807e31be822c.png)


![image](https://user-images.githubusercontent.com/31091285/159773520-88400df4-e3c5-4e1f-8b4f-07be12d053a0.png)


![image](https://user-images.githubusercontent.com/31091285/159773764-6f0d31e3-ebd2-44d3-8623-2150d3e0feac.png)


![image](https://user-images.githubusercontent.com/31091285/159773978-8e3cd14d-4837-4131-a0bd-57e641ca0aba.png)

**Comment by veronicageek** [comment]
OK, can I ask you to at least update to `1.9.78` like I used, or the nightly release from today (`1.9.79`) in case something had changed between the releases.

**Comment by aglakshmi** [comment]
Hi Veronique,
Still no luck. I tried with 1.9.78-nightly version, but the behaviour is still same. Just to note I cannot see the version 1.9.79, so couldn't try with this version.

![image](https://user-images.githubusercontent.com/31091285/160033661-1fb2fcf0-bc59-427d-ac6f-ed3821444c17.png)


![image](https://user-images.githubusercontent.com/31091285/160033670-c4b269a7-58cd-4d88-818c-d0904a868d06.png)

**Comment by aglakshmi** [comment]
Hi Veronique,
I have tried even with 1.9.82, but nothing changed. I tried on 2 different tenant, one from my local PC and another using automation script. Both behaving the same way. I mean it is just ignoring SiteAlias parameter. 
Do you have any suggestion?

**Comment by veronicageek** [comment]
That's very strange. Let see if @gautamdsheth or @KoenZomers can try on their side and what behaviour they observe.

**Comment by gautamdsheth** [comment]
hi @aglakshmi , are you using App-only context to provision the modern team site and your Azure AD app has necessary Graph+SharePoint permissions ?

**Comment by veronicageek** [comment]
Closing as no response.
