### ISSUE TITLE
[BUG]  Get-PnPListItem with PageSize not releasing / reusing memory

### ISSUE THREAD

**Issue by JazBInKC** [pnp/powershell#1716]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature

Working with a tenant with MILLIONS of files that need to be copied to NTFS and then kept updated as they transition FROM O365 SharePoint.

I have a separate script for seeding data that walks the file folder structure of their libraries and copies (Get-PnPFile) the data to the NTFS target. It works, but it's slow. To keep the NTFS target current I need to quickly run through ALL the files and add new or updated files. I am able to use Get-PnPListItem as a means to grab 1000's of files / folders and quickly dispatch those that are unchanged.

The issue is with every page processed (I'm pulling 5000 items) approximately 128MB of memory is consumed and only a small fraction released before the next page is 'loaded'. By the time I've hit 500,000 items, memory consumption is at 12-13GB.  Memory consumption occurs with each Page pulled (breakpoint at the script block verifies this).

I've included **[System.GC]::GetTotalMemory($true) | out-null** in the Function called ProcessItems (so once per 5000 items processed), but it doesn't seem to make any significant difference

### Expected behavior 

Get-PnPListItem should release or reuse memory allocated for each Page loaded.

### Actual behavior 

Memory consumption per 5000 item Page of approximately 90-128 MB.  Only a portion is released.  By the time 500,000 items have been pulled system memory usage is a 12-13GB,

### Steps to reproduce behavior

Get-PnPListItem -List $listUrl -PageSize $PageSize -ScriptBlock {Param($items) ShowProgress $items; ProcessItems $items -ErrorAction Continue; $items.Context.ExecuteQuery()}) | Out-Null

### What is the version of the Cmdlet module you are running?

PnP.PowerShell v1.9.0
PowerShell v5.1

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows (Server 2016)
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by JazBInKC** [comment]
Please correct me if I wrong, but I believe this is the underlying code:
_

> do
>                 {
>                     var listItems = list.GetItems(query);
>                     ClientContext.Load(listItems);
>                     ClientContext.ExecuteQueryRetry();
> 
>                     WriteObject(listItems, true);
> 
>                     if (ScriptBlock != null)
>                     {
> 						ScriptBlock.Invoke(listItems);
> 					}
> 
> 					query.ListItemCollectionPosition = listItems.ListItemCollectionPosition;
>                 } while (query.ListItemCollectionPosition != null);

_

Doesn't **var listItems = list.GetItems(query);** effectively create a new instance (or a new memory allocation) of **listItems** with every iteration? And, if so, shouldn't the code either a) declare the variable outside the loop or b) Dispose listItems after saving **listItems.ListItemCollectionPosition**?

**Comment by JazBInKC** [comment]
Bueller?

**Comment by JazBInKC** [comment]
Behavior Unchanged with PS 7.2.2

**Comment by JazBInKC** [comment]
Almost 3 weeks - is anyone going to look at this?

**Comment by gautamdsheth** [comment]
What are you doing in the script block ? Looking at the code , I couldn't make out. I saw ExecuteQuery inside that block, maybe you can try to not do that if its not necessary ? 
Also, how about changing the page size to something less like maybe 2000 or 3000 and trying ?

**Comment by veronicageek** [comment]
> Almost 3 weeks - is anyone going to look at this?

@JazBInKC - This is a Community driven module/repo. While we aim to do our best, there's no SLA.

**Comment by JazBInKC** [comment]
> What are you doing in the script block ? Looking at the code , I couldn't make out. I saw ExecuteQuery inside that block, maybe you can try to not do that if its not necessary ?
> Also, how about changing the page size to something less like maybe 2000 or 3000 and trying ?

That's the current underlying c-sharp code.  And yes, I've tried smaller page sizes.  It takes a smaller bite, but it doesn't help me as I'm still looking at millions of files (1000's of pages) - so the memory issue is a considerable problem.  

My point was the var listItems = list.GetItems(query); is creating a new instance of listItems and the old instance is not released from memory until the do loop ends.   Could it look like this?:

                `do
                {
                    var listItems = list.GetItems(query);
                    ClientContext.Load(listItems);
                    ClientContext.ExecuteQueryRetry();

                    WriteObject(listItems, true);

                    if (ScriptBlock != null)
                    {
						ScriptBlock.Invoke(listItems);
					}

					query.ListItemCollectionPosition = listItems.ListItemCollectionPosition;
                    listItems.Dispose();
                } while (query.ListItemCollectionPosition != null);`

with the forced release of **listItems**?

Your input appreciated.

jbw

**Comment by gautamdsheth** [comment]
My suggestion would be to use CAML query here.
Since you have like a million items, maybe you can create query to retrieve items in chunks.

Something like this, pseudo code:

`Get-PnPListItem -List $listUrl -Query "ID > 1 and ID < 10000" -PageSize $PageSize -ScriptBlock {Param($items) ShowProgress $items; ProcessItems $items -ErrorAction Continue; $items.Context.ExecuteQuery()}) | Out-Null`

Divide 1 million into chunks of say 20000 and then for every 20k items, execute the above query, with ID > 1 and ID < 20K and then ID > 20k and ID <40k and so on. Hope that helps.

**Comment by JazBInKC** [comment]
> My suggestion would be to use CAML query here. Since you have like a million items, maybe you can create query to retrieve items in chunks.
> 
> Something like this, pseudo code:
> 
> `Get-PnPListItem -List $listUrl -Query "ID > 1 and ID < 10000" -PageSize $PageSize -ScriptBlock {Param($items) ShowProgress $items; ProcessItems $items -ErrorAction Continue; $items.Context.ExecuteQuery()}) | Out-Null`
> 
> Divide 1 million into chunks of say 20000 and then for every 20k items, execute the above query, with ID > 1 and ID < 20K and then ID > 20k and ID <40k and so on. Hope that helps.

Isn't that what PageSize does?  I'm getting the 'chunks' but I'm losing ram (90 - 128MB per chunk / page).  And the memory leak is the issue.  The actual processing is working just as I intended.  The $items.Context.ExecuteQuery() has been removed from my code, it was an attempt to initiate Garbage Collection (didn't make a difference).  I'm avoiding a 'query' as it would be executed against millions (5 to 15 million) of files - I'd rather just process the random stream of files / folders in whatever order given.

Your help appreciated

jbw

**Comment by gautamdsheth** [comment]
The reason I suggested that is that when you execute get-Pnplistitem again in for loop , the previous object would be get disposed. 

This way , I am hoping you won’t run into memory issue. 

Please let me know how it goes , maybe try with a smaller range.

**Comment by gautamdsheth** [comment]
Also when you use caml query, the payload retrieved is also less if you specify the viewfields that you need. By default, it gets a lot of data back which you won’t need, but if viewfields are specified only those columns are returned. 

This will also help you in memory consumption.

**Comment by JazBInKC** [comment]
Follow-up:  I am able to use the CAML query with my existing code, but using ID batches poses it's own issues.   It would be nice if we could just resolve the memory leak in the GetListItem.cs file.  Problematic for me to do so as the run environment is not my work environment - testing would be difficult.   I do appreciate the help!

jbw

**Comment by gautamdsheth** [comment]
@JazBInKC - curious to know what issue you faced when using ID with batches, can you elaborate on that ? The problem with `GetListItem` method is that it comes from CSOM SDK and we can't fix it since Microsoft owns that.

The approach of using ID with batches is better IMHO due to the fact that ID column itself is indexed.

**Comment by JazBInKC** [comment]
Gautam –

I’m working against very large lists.  Running batches daily to keep up with new and changed files that are then replicated in NTFS.  I am unable to use Get-ListItem -PageSize because of a memory leak (that I’ve reported).  5 million plus items / 5000 is a lot of pages, each page consumes 90MB – you can see where this is going.

So, I’m looping Get-ListItem using a query that increases the lower and upper ID’s by 4999 every cycle (1 – 5000, 5001 – 10000, and so on).  That works (memory is released with each iteration), but I’m having to guess at the upper limit of my processing with (Get-List $List).ItemCount x 2 as it appears as though SharePoint is assigning IDs by 2’s.  I can’t limit by item count because in spite of the given value I don’t typically get that number in processing (it’s usually off by a few hundred).

It seems like a no-brainer that max- or next- Index values should be programmatically available.  I can survive the way I working now, it’s just inelegant (and uncertain).

Thanks!

jbw


***@***.***<https://ihs911.com/>
James Wood​​
Support Services ‑ Solution Specialist
,
Integrated Health Systems
e: ***@***.******@***.***>
 |
w: www.ihs911.com<https://ihs911.com/>

​IT support GOT YOU DOWN? Ask me about our Pulse IT support solution!
Amazing Support….Amazing Response!

**Comment by JazBInKC** [comment]
> [@JazBInKC](https://github.com/JazBInKC)<https://github.com/JazBInKC> - curious to know what issue you faced when using ID with batches, can you elaborate on that ? The problem with GetListItem method is that it comes from CSOM SDK and we can't fix it since Microsoft owns that.

Issues have been ascertaining the actual top ID (where to stop).  I have something that's working for now, but I feel like I'm not really touching everything.  Moreover, for my purposes (and because of the huge number of files and folders affected / created / moved daily by the client), I'd rather walk the directory structure.  

I still don't understand why the **$listItem** var can't be Disposed inside the do..while loop in the underlying C# code.  Seems like that would release (or reuse) allocated RAM.

Thanks!
