### ISSUE TITLE
[BUG] Add-PnPTeamsTab -Type pdf

### ISSUE THREAD

**Issue by BlaaaBlaaaBlaaa** [pnp/powershell#1719]
### Reporting an Issue or Missing Feature
Adding a new MS Teams Tab with "Add-PnPTeamsTab" and Type PDF is not working as expected. The new Tab is created but the file is not placed correctly.

### Expected behavior 
Tab gets added and PDF opens when clicking on the tab.

### Actual behavior 
Tab gets added but file is not available with error "This item might not exist or is no longer available". See screenshot below.

### Steps to reproduce behavior
Add-PnPTeamsTab -Team "Test005" -Channel "General" -DisplayName "PDF" -Type pdf -ContentUrl "https://XXXXXXX.sharepoint.com/teams/Test005/Shared%20Documents/General/test.pdf" -EntityId null

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 1.9.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

Screenshots:
Creating with Add-PnPTeamsTab:
![pdf_error](https://user-images.githubusercontent.com/38289435/159856953-5fc80d91-6ea1-490b-8264-4c0138ccf2fe.png)

After creating the file can be selected manually which shows that the file should be fine:
![pdf_selection](https://user-images.githubusercontent.com/38289435/159856967-d09e2757-2b42-4e23-b997-1b46c678ead1.png)

Working fine after manual selecting the file:
![pdf_manual](https://user-images.githubusercontent.com/38289435/159856978-094bb196-16ea-4bc7-980c-d481aff07832.png)

Working as expected when using a .docx instead of .pdf
![docx](https://user-images.githubusercontent.com/38289435/159856986-722c6341-9f27-4f0a-9c20-66266d8baf03.png)

**Comment by veronicageek** [comment]
@BlaaaBlaaaBlaaa - Just remove the `%20` from the `/Shared%20Documents` URL and it will work fine.

![image](https://user-images.githubusercontent.com/25181757/160238673-8eaf7a88-428f-4b6d-ad9a-1077867e5edf.png)

![image](https://user-images.githubusercontent.com/25181757/160238688-bf084ded-1c8b-4f5c-93c0-d3428e477fee.png)

**Comment by BlaaaBlaaaBlaaa** [comment]
Hi,

Unfortunately this still seems not to be working:

`Add-PnPTeamsTab -Team $($DisplayName) -Channel "General" -DisplayName "Code of Conduct" -Type PDF -ContentUrl "https://XXXXX.sharepoint.com/teams/$($DisplayName)/Shared Documents/General/$($PDF_CoC_file)" -EntityId "null"`

![image](https://user-images.githubusercontent.com/38289435/161248103-0038d4ab-5d01-40c4-8eae-86dc5fecc95f.png)

Any other idea? Only difference I can see is in the URL with "teams" vs "sites"
