### ISSUE TITLE
[FEATURE] Allow caller to set custom HTTP Accept header value in the Invoke-PnPSPRestMethod cmdlet

### ISSUE THREAD

**Issue by joerodgers** [pnp/powershell#1723]
These two calls fail:

```
Invoke-PnPSPRestMethod -Method GET -Url "https://contoso-admin.sharepoint.com/_api/v2.0/sites/4B6B5FC7-4313-4DA3-BAF5-00A11ED30800" -Raw

Invoke-RestMethod -Method  GET  -Uri "https://contoso-admin.sharepoint.com/_api/v2.0/sites/4B6B5FC7-4313-4DA3-BAF5-00A11ED30800" -Headers @{ accept = "application/json; odata=nometadata"; Authorization = "Bearer eyJ0....." }
```

This call command works:
```
Invoke-RestMethod -Method  GET  -Uri "https://contoso-admin.sharepoint.com/_api/v2.0/sites/4B6B5FC7-4313-4DA3-BAF5-0A11ED30800" -Headers @{ accept = "application/json"; Authorization = "Bearer eyJ0....." }
```
The difference between the is the value for the accept header.  PnPSPRestMethod includes the odata=nometadata, which causes several SharePoint Online REST API endpoint to fail with: 

`Invoke-PnPSPRestMethod : {"error":{"code":"invalidRequest","message":"Invalid request"}}`

Allowing the caller to override the default headers would allow devs to use the _api/v2.0 and $batch endpoints with Invoke-PnPSPRestMethod.

Reference: https://github.com/pnp/powershell/blob/dev/src/Commands/Base/InvokeSPRestMethod.cs#L55

**Comment by gautamdsheth** [comment]
Hi @joerodgers , have added an additional parameter `Accept` to allow you to specify custom values there.
It will be available from tomorrow's nightly and later builds :)

**Comment by joymon** [comment]
Is there any way to include custom headers in Invoke-PnPSPRestMethod? I am trying to add the below header to check a workaround.
SPHome-ClientType: SharePointIOS

**Comment by stevebeauge** [comment]
Faced same issue today. Not having access to the headers is blocking. In my case I wanted to update a list item (Set-PNPListItem isn't working for an unknown reason).

Calling manually the update endpoint requires to pass `If-Match:*` in the headers.

The only workaround I found was to move from 

```powershell
            $updateListItemApiUrl = "/_api/web/lists/getbyId(guid'$($list.Id)')/items($($item.Id))"
            $body = @{
                'Title'  = $label
            }
            Invoke-PnPSPRestMethod -Method PATCH `
                 -Url $updateListItemApiUrl `
                 -Content $body `
                 -ContentType "application/json;odata=nometadata" `
                 -Accept "application/json;odata=nometadata" `
```

to

```powershell
            $updateListItemApiUrl = "/_api/web/lists/getbyId(guid'$($list.Id)')/items($($item.Id))"
            $body = @{
                'Title'  = $label
            }
            $token = Get-PnPAccessToken -ResourceTypeName SharePoint
            $web = Get-PnPWeb
            Invoke-RestMethod -Method PATCH `
                -Uri ($web.Url + $updateListItemApiUrl) `
                -ContentType "application/json;odata=nometadata" `
                -Body ($body | ConvertTo-Json -Depth 100) `
                -Headers @{
                "Authorization" = "Bearer $($token)"
                "Accept"        = "application/json;odata=nometadata"
                "Content-Type"  = "application/json;odata=nometadata"
                "If-Match"      = "*"
            }
```
