### ISSUE TITLE
[BUG] Export-PnPTaxonomy -TermStoreName does not work for On-Prem

### ISSUE THREAD

**Issue by hkv-888** [pnp/powershell#1726]
### Reporting an Issue or Missing Feature
When executing Export-PnPTaxonomy -Path [filepath] -IncludeID -TermStoreName [Name of TermStore] results in an error when running this in an on-prem farm. Running the cmdlet without the -TermStoreName parameter works just fine. Using the SharePointPnPPowerShell2019 and SharePointPnPPowerShell2016 modules.

### Expected behavior 
Cmdlet should output a file with all term groups in the specified Managed Metadata Service Application.

### Actual behavior 
Getting the following error
Export-PnPTaxonomy : Value cannot be null.
Parameter name: source
At line:1 char:1
+ Export-PnPTaxonomy -Path 'C:\Temp\out.csv' -IncludeID -Force -TermSto ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Export-PnPTaxonomy], ArgumentNullException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Taxonomy.ExportTaxonomy

<img width="641" alt="image" src="https://user-images.githubusercontent.com/72223420/160185701-6983417d-579b-4018-bbd7-ef99e9cb86e4.png">

### Steps to reproduce behavior
Connect to an on-prem SP Farm and run the following cmdlet.
Export-PnPTaxonomy -Path [filepath] -IncludeID -TermStoreName [Name of TermStore] 

### What is the version of the Cmdlet module you are running?
SharePointPnPPowerShell2016 3.29.2101.0

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@hkv-888 - You are using the old module (SharePointPnPPowerShell*) which is not maintained anymore unfortunately. We don't have the capacity/resources for both modules, and we now only support SharePoint Online.
