### ISSUE TITLE
[FEATURE] Get-PnpListItem order

### ISSUE THREAD

**Issue by xaviv** [pnp/powershell#1727]
**Is your feature request related to a problem? Please describe.**
Get-PnpFileItem cannot be used with large lists, and Get-PnpListItem with PageSize and ScriptBlock must be used, but items are returned by id ascending order.

**Describe the solution you'd like**
It might be useful to set an order (asc or desc) by a column

**Comment by gautamdsheth** [comment]
This is already possible using CAML query.

You can specify the the `-Query` parameter and use the query  something like below:

`<View><Query><OrderBy><FieldRef Name="ID" Ascending="FALSE"/></OrderBy></Query></View>`

You can change the clause as you wish and it will return it in that order 

Closing this feature request
