### ISSUE TITLE
[BUG] Misleading documentation for cmdlets

### ISSUE THREAD

**Issue by wilecoyotegenius** [pnp/powershell#174]
Documentation on https://pnp.github.io/powershell/ site is in some places misleading. There are pages that describe syntax from previous versions of cmdlets without mentioning this in any way. This leads to confusion.

Example: 
For Connect-PnPOnline cmdlet there are two pages
- https://pnp.github.io/powershell/cmdlets/released/Connect-PnPOnline.html - describing syntax from SharePointPnPPowerShellOnline 
- https://pnp.github.io/powershell/cmdlets/Connect-PnPOnline.html - describing syntax from current PnP.PowerShell version

### Expected behavior 
I would expect at least an indication of PnP.Powershell versions that support particular syntax on the page (i.e.: "SharePointPnPPowerShellOnline only" or "PnP.PowerShell only)

### Steps to reproduce behavior
Just go to pages from bug description and compare content

### What is the version of the Cmdlet module you are running?
1.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
The /released version of the html is not linked to anymore from the site, it's a leftover from earlier builds. The documentation in the /released/connect-pnponline.html  does not apply to SharePointPnPPowerShellOnline but to an earlier build of the PnP PowerShell (the new module). Having said that, we will clear up the older structure as it might still be indexed by search engines.
