### ISSUE TITLE
[BUG] Get-PnPFile errors on groups of .TXT files (every 3rd file)

### ISSUE THREAD

**Issue by JazBInKC** [pnp/powershell#1745]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Get-PnPFile has an issue with .TXT files

Running code developed to migrate files from O365 to NTFS several months ago.  Recently, I've noticed as I've re-run the code to capture new and changed files that whenever the code runs across a series of .TXT files to be added (written) to the NTFS target or when an existing file needs updating, I will see an error with every 3rd file.  The moment the file type changes (to .pdf, for example), the process (write or update) continues without error or interruption.

### Expected behavior 
I expect Get-PnPFile to work without error (or a least provide a better error messages).  Certainly I don;t expect it to treat a .TXT file differently than any other file type.

### Actual behavior 
This happens under 1.9.0 and 1.10.0 - have I my process running on several servers (not all at once).   This happens with new .TXT files and / or updates.  The top image shows the pattern of failure with .txt files.  The second image shows how a change in file type modifies the result.

![image](https://user-images.githubusercontent.com/96395010/161658862-c801c0ff-3e68-4663-9332-fa159a4915dc.png)

![image](https://user-images.githubusercontent.com/96395010/161661901-8dcb56c0-406d-4ac8-9c9c-a159fec1b36c.png)

### Steps to reproduce behavior
if (Test-Path -LiteralPath $targetpath) {
            #$listItem = $file.ListItemAllFields            
            $targetfile = Get-ChildItem -LiteralPath $targetpath -ErrorAction SilentlyContinue
            if ($targetfile.LastWriteTimeUTC -lt $modified) {
                write-host "Updating:" $targetpath -ForegroundColor Cyan
                Get-PnPFile -ServerRelativeUrl $file.ServerRelativeUrl -Path $destinationfolder -FileName $filename -AsFile -Force
                if (Test-Path -LiteralPath $targetpath) {
                    (Get-Item -LiteralPath $targetpath).LastWriteTime = $modified
                    $acl = Get-Acl -LiteralPath $targetpath
                    $acl.SetOwner([System.Security.Principal.NTAccount] "Domain Admins")
                    Set-Acl -LiteralPath $targetpath -AclObject $acl
                    if ($targetpath.length -ge 262) {
                        Write-Host $targetpath "Exceeds 260 character Path/Filename limit - Long Path Enabled:" $LongPathEnabled -ForegroundColor Yellow            
                    }
                }
                else {
                    Write-Host "Error Updating File: $targetpath" -ForegroundColor Red -BackgroundColor Black
                }
            }
            else {
                write-host "Skipping:" $targetpath -ForegroundColor White
            }
}
### What is the version of the Cmdlet module you are running?
1.9.0 and 1.10.0 
PS 5.1

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows Server 2016
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by JazBInKC** [comment]
Updated PowerShell to 7.2.2.  Seems to have reduced the frequency of the errors.

**Comment by gautamdsheth** [comment]
Is it still happening consistently ? Can't seem to reproduce this one

**Comment by JazBInKC** [comment]
> Is it still happening consistently ? Can't seem to reproduce this one.
> 
> Maybe what you can do is that when this error occurs, use `Get-PnPException` and then post the message here, maybe that can help us.

Since updating to PnP.PowerShell 1.10.0 + and PS 7.2.2 the timeouts have stopped causing errors - I still get delays from time to time.  This seems to be an artifact of PnP.PowerShell versions after Sharepoint.PnP and PS 5.1
