### ISSUE TITLE
[BUG] Add-PnPUserToGroup (Likely Documentation Issue)

### ISSUE THREAD

**Issue by DGDC** [pnp/powershell#1753]
### Reporting an Issue or Missing Feature
Add-PnPUserToGroup

### Expected behavior 
I expect the cmdlet to exist since it is listed in the documentation- https://pnp.github.io/powershell/cmdlets/Add-PnPUserToGroup.html

It is not listed in https://github.com/pnp/powershell/tree/dev/documentation#L1

I suspect Add-PnPUserToGroup was superseded by Add-PnPGroupMember and the documentation was not fully updated.

### Actual behavior 
Add-PnPUserToGroup: The term 'Add-PnPUserToGroup' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

### Steps to reproduce behavior
Attempt to invoke Add-PnPUserToGroup

### What is the version of the Cmdlet module you are running?
1.10.0

### Which operating system/environment are you running PnP PowerShell on?
- [ X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by LeonArmston** [comment]
```
I suspect Add-PnPUserToGroup was superseded by Add-PnPGroupMember and the documentation was not fully updated.
```
You are correct!

My guess is its problem with the auto generation of the PnP PowerShell command web pages for [pnp.github.io/powershell](https://pnp.github.io/powershell) as there is no Add-PnPUserToGroup page in the repo [Documentation folder](https://github.com/pnp/powershell/tree/dev/documentation) like I would expect.

Add-PnPUserToGroup is not listed on the cmdlets menu on https://pnp.github.io/powershell but is available if you go direct to https://pnp.github.io/powershell/cmdlets/Add-PnPUserToGroup.html so perhaps the old page needs to be deleted?

@KoenZomers or @gautamdsheth

**Comment by LeonArmston** [comment]
It is located in a branch called gh-pages (link below)

https://github.com/pnp/powershell/blob/gh-pages/cmdlets/Add-PnPUserToGroup.html

**Comment by gautamdsheth** [comment]
Have manually deleted the page , will be removed by tomorrow.
Thanks for spotting it !

**Comment by Nazul** [comment]
In https://pnp.github.io/powershell/articles/upgrading.html there's a list of cmdlets that were deprecated, and this one is not listed there. It should be added too.
