### ISSUE TITLE
[BUG] Connect-PnPOnline "GetContextAsync() called without an ACS token generator" error in -Interactive after -UseWebLogin

### ISSUE THREAD

**Issue by fowl2** [pnp/powershell#1760]
After running `Connect-PnPOnline` with the `-UseWebLogin` parameter, `Connect-PnPOnline` with the `-Interactive` parameter will return an error.

``` powershell
$siteUrl = "https://xxx.sharepoint.com/"
Connect-PnPOnline -Url $siteUrl -UseWebLogin
Connect-PnPOnline -Url $siteUrl -Interactive

```

```
Connect-PnPOnline : GetContextAsync() called without an ACS token generator. Use GetACSAppOnlyContext() or GetAccessTokenContext() 
instead or specify in AuthenticationManager constructor the authentication parameters
At line:1 char:1
+ Connect-PnPOnline -Url https://xxx.sharepoint.com/  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-PnPOnline], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,PnP.PowerShell.Commands.Base.ConnectOnline
```

```
Message          : GetContextAsync() called without an ACS token generator. Use GetACSAppOnlyContext() or GetAccessTokenContext() 
                   instead or specify in AuthenticationManager constructor the authentication parameters
Stacktrace       :    at PnP.Framework.AuthenticationManager.<GetContextAsync>d__59.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at PnP.Framework.AuthenticationManager.GetContext(String siteUrl, CancellationToken cancellationToken)
                      at PnP.PowerShell.Commands.Base.PnPConnection.CreateWithInteractiveLogin(Uri uri, String clientId, String 
                   tenantAdminUrl, Boolean launchBrowser, AzureEnvironment azureEnvironment, CancellationTokenSource 
                   cancellationTokenSource, Boolean forceAuthentication, String tenant)
                      at PnP.PowerShell.Commands.Base.ConnectOnline.ConnectInteractive()
                      at PnP.PowerShell.Commands.Base.ConnectOnline.Connect(CancellationToken& cancellationToken)
                      at PnP.PowerShell.Commands.Base.ConnectOnline.ProcessRecord()
                      at System.Management.Automation.CommandProcessor.ProcessRecord()
```

### What is the version of the Cmdlet module you are running?
1.10.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows

**Comment by veronicageek** [comment]
@fowl2 - Although I can reproduce when using `-UseWebLogin` first and then `-Interactive` (meaning there's no issue when doing the opposite), is there a particular reason why you want to connect with both one after the other?

**Comment by fowl2** [comment]
I mean, you use the first, get a warning asking you to use the second instead and when you try it doesn't work - it's not a great impression.

**Comment by dustingolding** [comment]
Have you tried using -ForceAuthentication?

**Comment by veronicageek** [comment]
@fowl2 - This is not for use one after the other. It's one OR the other, and the warning explains why using `-Interactive` is the way forward.

**Comment by fowl2** [comment]
> Have you tried using -ForceAuthentication?

Can verify this does seem to be a working an alternative to restarting the whole PowerShell session.

> @fowl2 - This is not for use one after the other. It's one OR the other, and the warning explains why using `-Interactive` is the way forward.

Hmm, maybe I've been unclear. If both `-Interactive` and `-UseWebLogin` are specified a different error - `Parameter set cannot be resolved using the specified named parameters.` - is produced as expected and points to the specific problem (if slightly obtusely, but this is the standard PowerShell message).

I understand that `-Interactive` is the recommended method going forward (although it is not universally better - it allows switching accounts more easily, but conversely adds an extra step when keeping the same account).

Consider the scenario where an existing user used to `-UseWebLogin` is updating a script to use `-Interactive` and is unable to due to this errorr.

**Comment by rodneyviana** [comment]
First time you use -Interactive you have to make sure the PowerShell Module is registered via Register-PnPManagementShell, thus the use of UseWebLogin the first time. This is how I came across the bug and I resolved by Disconnect-PnPOnline then using Connect-PnPOnline -Interactive. In MHO this is a bug because unless I had seen this discussion I would have tried so many different things but the Disconnect-PnPOnline or -ForceAuthentication. Maybe just giving a better error message would suffice

**Comment by pratik161989** [comment]
I have managed to fix this issue. You need to use certificate based authentication for this. It is very unfortunate from Microsoft that they have not mentioned it anywhere.

Connect-PnPOnline -Url $siteUrl -Tenant $tenantId -ClientId $clientId -Thumbprint $thumbprint
