### ISSUE TITLE
[BUG] Unable to create linkless header using Add-PnPNavigationNode

### ISSUE THREAD

**Issue by pmcopeland** [pnp/powershell#1777]
### Reporting an Issue or Missing Feature
Unable to create a linkless header using "-Url 'http://linkless.header' with Add-PnPNavigationNode.

### Expected behavior 
According to [Example 6](https://pnp.github.io/powershell/cmdlets/Add-PnPNavigationNode.html#example-6) in the cmdlet documentation, passing in the URL 'http://linkless.header' should create a header without a hyperlink. 

### Actual behavior 
The navigation node generate hyperlinks to 'http://linkless.header'

### Steps to reproduce behavior
Add-PnPNavigationNode -Title $Header -Location "QuickLaunch" -Url 'http://linkless.header'

### What is the version of the Cmdlet module you are running?
1.7.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@pmcopeland - That's because you need to add the `/` at the end too: `-Url 'http://linkless.header/'`
I'll amend the documentation.

**Comment by pmcopeland** [comment]
@veronicageek I tried with that / as well. It still results in a hyperlink.

**Comment by veronicageek** [comment]
I've just tried with `1.10.0` and had problem. Please update your module as you're using `1.7.0`

**Comment by pmcopeland** [comment]
I have uninstalled PnPPowershell completely and installed 1.10.0. I am still seeing this behavior. Please let me know if there is anything else I can try.

**Comment by pmcopeland** [comment]
Hi @veronicageek,
Sorry to circle back on an old item. I've discovered the underlying issue, and why both of us were getting different results. If creating a linkless header on a site collection designated as a hub or assigned to a hub the `-Url 'http://linkless.header/'` parameter does not create a linkless header. I'm not sure exactly why but changing hub association changed the behavior of this cmdlet.
