### ISSUE TITLE
[BUG] Error when running ConvertTo-PNPPage on a classic page with Image under /_layouts

### ISSUE THREAD

**Issue by remcodegroot** [pnp/powershell#1779]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

### Reporting an Issue
I'm trying to convert classic to modern pages using ConvertTo-PNPPage\

### Expected behavior 
A succesful conversion of the classic page to a modern page.

### Actual behavior 
ConvertTo-PnPPage fails with "Page does not exist" if an image is on the page that is not in a library. (Like the default : /sites/<name>/_layouts/images/homepageSamplePhoto.jpg).  When you download this image and place it in a library and modify the link on the classic page to point to /sites/<name>/_layouts/SiteAssets/homepageSamplePhoto.jpg then  the migration succcedes.

An error log with verbose logging in the attachment. 

I have tried to exclude SharePointPnP.Modernization.WikiImagePart from the webpart mapping and to use -SkipDefaultUrlRewriting .  Both did not help.

### Steps to reproduce behavior
ConvertTo-PnPPage -Identity "Home1" -Overwrite -LogVerbose -LogType File  -WebPartMappingFile .\webpartmapping.xml 

or

ConvertTo-PnPPage -Identity "Home1" -Overwrite -LogVerbose -LogType File  -WebPartMappingFile .\webpartmapping.xml -SkipDefaultUrlRewriting

### What is the version of the Cmdlet module you are running?
1.10.0

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

[Page-Transformation-Report-20-4-2022-10-40-12.md](https://github.com/pnp/powershell/files/8519841/Page-Transformation-Report-20-4-2022-10-40-12.md)

**Comment by remcodegroot** [comment]
Found what the cause is: It is caused by the Function  ImageLookup({ServerRelativeFileName}) 
Since for these files no library is found the function crashes. It would be enough if a place holder could be placed or even if the image was skipped.

**Comment by veronicageek** [comment]
@remcodegroot - Can you please update to the latest release 2.1.x however you will need **PS 7.2 or later** to benefit from all the bug fixes and improvements.

PS5 support has been dropped in the new release.

Feel free to reopen if the issue persists. Thanks!
