### ISSUE TITLE
[BUG] Apply-PnPProvisioningTemplate : The term 'Apply-PnPProvisioningTemplate' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by DmitryVorobyov** [pnp/powershell#179]
### Reporting an Issue or Missing Feature
Bug: Apply-PnPProvisioningTemplate : is not recognized as the name of a cmdlet

### Expected behavior 
Apply-PnPProvisioningTemplate should apply the specified template to the site

### Actual behavior 
An error message is displayed: "Apply-PnPProvisioningTemplate : The term 'Apply-PnPProvisioningTemplate' is not recognized as the name of a cmdlet" (screenshot attached)

### Steps to reproduce behavior
1. Prepare a provisioning template (e.g. "template.xml")

2. Run Connect-PnPOnline -Url (site url) 
    Note: provided screenshot uses _Connect-PnPOnline - Url (url) -UseWebLogin_. The behavior does not change if using alternative login methods (e.g. _Connect-PnPOnline -Url (url) -PnPManagementShell_)

3. Run _Apply-PnPProvisioningTemplate -Path "template.xml"_

### What is the version of the Cmdlet module you are running?
1.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

![Apply-PnPProvisioningTemplate error](https://user-images.githubusercontent.com/10333583/105877133-a371a300-5fcd-11eb-95b1-a74739ac16ca.PNG)

**Comment by jansenbe** [comment]
Use `Invoke-PnPSiteTemplate` instead

**Comment by sdooodly** [comment]
@jansenbe This works, thank you!
