### ISSUE TITLE
TargetInvocationException when trying to Get-PNPListItem

### ISSUE THREAD

**Issue by Tom-CK** [pnp/powershell#1797]
### Reporting an Issue
Running  Get-PNPListItem -List "MyListName"  always returns a "TargetInvorationException". Tried it with several lists.

### Steps to reproduce behavior
Get-PNPListItem -List "MyListName"

### What is the version of the Cmdlet module you are running?
1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows

No matter what I try, I can not "Get-PNPListItem" to work. I always get an exception.

The CMDLet used to work before and I swear I did not make any changes.

Tried to update PNP.PowerShell to 1.10.0 - same exception.
Rolled backe to 1.5.0 - same result.

Here is the result of "Get-PNPException" (in german):

![image](https://user-images.githubusercontent.com/77489598/164725300-8ff99a23-6afd-40a9-b79f-ce6e45833b6f.png)

![image](https://user-images.githubusercontent.com/77489598/164725489-1575dad8-96ef-4669-8bc5-f3c22cdddb51.png)

Please help .....

**Comment by veronicageek** [comment]
@Tom-CK - No issue on my side with `1.10.0`. It must have been at a point in time.

![image](https://user-images.githubusercontent.com/25181757/164988046-31049fd0-171a-4cef-8167-55f0f21fb73a.png)

**Comment by Tom-CK** [comment]
Doing some further investigation and testing resulted in:

- Exception is thrown when using PNP.PowerShell 1.5 AND 1.10
- Exception is thrown running scripts on different machines and also in Azure Runbooks
- Seems like exception is thrown ONLY when connecting to sharepoint sites in a specific tenant

Get-PNPListItem works fine when I try to query sites in another tenant, but it seems like the exception is thrown when querying any list in any sharepoint site of that specific tenant.

What could be a reason for

- Connect-PNPOnline is working without exception
- Get-PNPList globally throws excpetion
- Get-PNPListItem globally throws exception on any list

just in one specific tenant ?

**Comment by gautamdsheth** [comment]
Hi, did you try with this flag and then try ?? 

https://www.koskila.net/literally-breaking-changes-to-app-authentication-on-sharepoint-%F0%9F%98%B5/

Remember, AppId and Appsecret based auth is now kinda deprecated and not recommended , so would suggest that you switch to Azure AD based auth.

**Comment by Tom-CK** [comment]
> Hi, did you try with this flag and then try ??
> 
> https://www.koskila.net/literally-breaking-changes-to-app-authentication-on-sharepoint-%F0%9F%98%B5/
> 
> Remember, AppId and Appsecret based auth is now kinda deprecated and not recommended , so would suggest that you switch to Azure AD based auth.

Unfortunately I am not an Administrator and I can not try this.
We are just on the way to change to Azure AD based auth, let's see if this solves the problem.

**Comment by gautamdsheth** [comment]
Closing this due to lack of response.

`Get-PnPListItem` is one of the most widely used cmdlets, its most likely a configuration issue in the tenant. 
As mentioned above, the ACS mode has been deprecated and the Azure AD auth is the way to go .
Please reopen the issue if it still persists.
