### ISSUE TITLE
Samples Update in lieu of Security Changes like MFA and Device Login

### ISSUE THREAD

**Issue by bigpix2000** [pnp/powershell#18]
Most of the documented examples show using Credentials inline which fail in MFA situations or require manual interaction which defeats the purpose of scripting for DevOps processes.  Is there guidance on a definitive pattern for connections and accesses and then we could potentially help update the old samples (some look like they go back to 2016!) to work in the "modern" world?

**Comment by veronicageek** [comment]
Hi @bigpix2000 🙂 

"_Then we could potentially help update the old samples (some look like they go back to 2016!)_" - Can you give me a link to what you're referring to? 

Cheers

**Comment by bigpix2000** [comment]
As a note, looking at other open issues around, this may potentially be a "duplicate" of all of those as my original thought was to consolidate the fix and based on seeing some of them go through the motions, it does not, unfortunately, look like there is a single fix for them :(  I will close this ticket and watch the others which I have already subscribed to or inserted myself into. Thanks! Happy New Year!
