### ISSUE TITLE
[FEATURE] Site Creation - Default TimeZone

### ISSUE THREAD

**Issue by tasgray** [pnp/powershell#1803]
**Is your feature request related to a problem? Please describe.**
There is no obvious way to set the default timezone for new sharepoint sites other than in the admin UI. Accessing this programmatically would be a great help.
![image](https://user-images.githubusercontent.com/5292389/164910755-d2d7212c-0ca7-44ba-8d5a-f097c9eb4e32.png)

**Describe the solution you'd like**
A pnp cmdlet which can get/set this value

**Describe alternatives you've considered**
The only way to access this information is through a rest API endpoint which appears to be for internal use only. https://m365x50428579-admin.sharepoint.com/_api/SPOInternalUseOnly.TenantAdminSettings. I can see this url is used in the CLI for Microsoft 365 to target another setting. Perhaps this can be utilised?

**Additional context**
N/A

**Comment by RobinDijkstra** [comment]
It would be nice to have a cmdlet for that. For now, I use the following in my scripts:

Connect-PnPOnline -Url $siteUrl -Interactive
$web = Get-PnPWeb -Includes RegionalSettings.TimeZones    
$timezone = $web.RegionalSettings.TimeZones | where-object { $_.Description -like "*amsterdam*" }
$web.RegionalSettings.TimeZone = $timezone
$web.Update()
Invoke-PnpQuery

Hope this helps.
