### ISSUE TITLE
[BUG] Unable to create Team with Application ID and certificate

### ISSUE THREAD

**Issue by svermaak** [pnp/powershell#1807]
### Reporting an Issue or Missing Feature
Unable to create Team with Application ID and certificate

### Expected behavior 
Team created for M365 group

### Actual behavior
New-PnPTeamsTeam: No Team found with Group id: 6a************************ea
or no output
![image](https://user-images.githubusercontent.com/12259728/165238307-38e45df5-2855-4969-96b2-2c9654ed624e.png)
![image](https://user-images.githubusercontent.com/12259728/165238672-9353c052-917f-49af-8e77-33b78663893e.png)

### What is the version of the Cmdlet module you are running?
Latest

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [x] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Is it happening consistently ??  Can you try with a different groups or maybe on a different tenant maybe ?

**Comment by svermaak** [comment]
I tried different owner and different group, same result

**Comment by svermaak** [comment]
It fails here
![image](https://user-images.githubusercontent.com/12259728/165400090-f7f7fa20-9356-4480-980b-89a733941734.png)

![image](https://user-images.githubusercontent.com/12259728/165399992-7e9584a4-8673-4251-bab5-834dd01e9a3e.png)

**Comment by veronicageek** [comment]
Closing as no response.

**Comment by KoenZomers** [comment]
Should be fixed through https://github.com/pnp/powershell/pull/3351
