### ISSUE TITLE
AddContentTypesFromContentTypeHub unused variable site

### ISSUE THREAD

**Issue by mdissel** [pnp/powershell#1809]
- variable site is not used

https://github.com/pnp/powershell/blob/dc800cc3dae20695ad86c915449ebb0472c019c6/src/Commands/ContentTypes/AddContentTypesFromContentTypeHub.cs#L20

- loading of sub necessary?

https://github.com/pnp/powershell/blob/dc800cc3dae20695ad86c915449ebb0472c019c6/src/Commands/ContentTypes/AddContentTypesFromContentTypeHub.cs#L23

**Comment by veronicageek** [comment]
@mdissel Whats your request here?

**Comment by mdissel** [comment]
If you specify the variable Site in the command, it's not used and the contenttype is always deployed to the current ClientContext.

**Comment by gautamdsheth** [comment]
Thanks @mdissel for spotting it, have fixed it.
It will be available in tomorrow's nightly and later on in a major version
