### ISSUE TITLE
[BUG] Get-help Register-PnPManagementShellAccess -Online doesn't point to the right url

### ISSUE THREAD

**Issue by mmascolino** [pnp/powershell#181]
### Reporting an Issue or Missing Feature
Running 
`Get-Help Register-PnPManagementShellAccess -Online`
doesn't launch the browser to the right help page.  This appears systemic across all PnP cmdlets.

### Expected behavior 
A browser launched at this url:
https://pnp.github.io/powershell/cmdlets/Register-PnPManagementShellAccess.html

### Actual behavior 
The browser gets launched here:
https://pnp.github.io/powershell/cmdlets/register-pnpmanagementshellaccess

which lacks the .html suffix and the cmdlet is not proper cased.

### Steps to reproduce behavior
`Get-Help Register-PnPManagementShellAccess -Online`

### What is the version of the Cmdlet module you are running?
1.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
Good point! Actually, this will affect every cmdlet. I'll work on a fix.

**Comment by erwinvanhunen** [comment]
everything has been updated and the changes will be there in 1.2.6-nightly.
