### ISSUE TITLE
[BUG] Multiple calls to Set-PnPDefaultColumnValues issue when using sub-folders

### ISSUE THREAD

**Issue by shuenSL** [pnp/powershell#1811]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Unable to set default column values in a library sub-folder for multiple fields. ** This is the same issue as reported in https://github.com/pnp/PnP-Sites-Core/issues/1827 **.

There are 2 fields that I need to set the column default value of a subfolder in a document library. I ran the following commands
Set-PnPDefaultColumnValues -List "Documents" -Folder "Folder A/Folder B/ABC Burger" -Field "ProjectNumber" -Value "12345"
Set-PnPDefaultColumnValues -List "Documents" -Folder "Folder A/Folder B/ABC Burger" -Field "ProjectName" -Value "Project Awesome"

### Expected behavior 
When I upload a document to the subfolder Folder A/Folder B/ABC Burger, the document should automatically be tagged with ProjectNumber: 12345 and ProjectName: Project Awesome.

### Actual behavior 
The uploaded document only has the ProjectName set, but not ProjectNumber. The last command override any previously set value for other columns.

### Steps to reproduce behavior
1. Add column ProjectNumber (text) and ProjectName (text) to Documents library
1. Create a folder hierarchy of Folder A > Folder B > ABC Burger
2. Run the following commands
Set-PnPDefaultColumnValues -List "Documents" -Folder "Folder A/Folder B/ABC Burger" -Field "ProjectNumber" -Value "12345"
Set-PnPDefaultColumnValues -List "Documents" -Folder "Folder A/Folder B/ABC Burger" -Field "ProjectName" -Value "Project Awesome"
3. Upload a document to the ABC Burger sub folder

### What is the version of the Cmdlet module you are running?
1.10

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows

**Comment by shuenSL** [comment]
Looks like starting the path with a forward slash resolves the issue. For example: 
Set-PnPDefaultColumnValues -List "Documents" -Folder "/Folder A/Folder B/ABC Burger" -Field "ProjectNumber" -Value "12345"
Set-PnPDefaultColumnValues -List "Documents" -Folder "/Folder A/Folder B/ABC Burger" -Field "ProjectName" -Value "Project Awesome"

**Comment by gautamdsheth** [comment]
Yeah, that should work , also "/" is the default value if you dont specify the folder
