### ISSUE TITLE
[BUG] Add-PnPContentTypesFromContentTypeHub in Private Channel Sites

### ISSUE THREAD

**Issue by sparkitect** [pnp/powershell#1818]
### Notice
The whole stroy: https://github.com/pnp/powershell/discussions/1770

### Reporting an Issue or Missing Feature
Reporting an Issue

### Expected behavior 
The cmdlet funtions the same for Private Channel sites as for Team and Communication sites.

### Actual behavior 
![image](https://user-images.githubusercontent.com/9206808/165849421-d10c37fd-70a0-4283-bc86-146e97bbc23c.png)

### Steps to reproduce behavior
1. Create and Publish a Content Type from the Gallery which includes a Managed Metadata column.
2. Create a new Private Channel in Teams
3. Connect-PnPOnline to new Private Channel site using its URL
4. Attempt to run cmdlet w/ ID of Content Type created in step 1

### What is the version of the Cmdlet module you are running?
1.10.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Will be closing this issue as it is something to do with CSOM itself.
Have updated the docs to reflect this workaround.

**Comment by joshfontaine136** [comment]
Hello, what would be the 'Identity' ID? Would it be the ID of the parent site?
