### ISSUE TITLE
[BUG] Get-PnPSite Bandwitdth Hits Visits Always Zero

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#182]
### Reporting an Issue or Missing Feature
I am reporting a bug

### Expected behavior 
I was expecting to get some real figures in **Hits** and **Visits** when running `Get-PnPSite -Includes Usage`, 

```
$site = $site = Get-PnPSite -Connection $siteConnection -includes Usage
$site.Usage | fl *

Bandwidth             : 123
DiscussionStorage     : 0
Hits                  : 5435543
Storage               : 9682221
StoragePercentageUsed : 0.00180345419794321
Visits                : 53253
TypeId                : {7ec28504-35f9-4fcf-a09f-401024417292}
```

### Actual behavior 
I am getting  zeros for every `Usage` property except `Storage` when running `Get-PnPSite -Includes Usage`
![image](https://user-images.githubusercontent.com/5260172/105906409-b4a1ca80-6034-11eb-8fb2-9dd01a43f942.png)

### Steps to reproduce behavior
```
Connect-PnPOnline
$site = Get-PnPSite -Connection $siteConnection -includes RootWeb, Usage
$site.Usage | fl *
```
### What is the version of the Cmdlet module you are running?
```
Get-Module PnP.PowerShell -ListAvailable | fl Name, Version, PreRelease

Name    : PnP.PowerShell
Version : 1.2.4
```

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
That's unfortunately nothing we can do about. The properties are being returned as it from the server, it is not something we calculate or specifically receive.  It's basically part of the Site object of CSOM and that is what the cmdlet returns. If you feel that this object should return usable data I would recommend you to create an entry at https://sharepoint.uservoice.com

**Comment by YuriySamorodov** [comment]
Hi @erwinvanhunen ,
Yeah, that what I was thinking about but decided to double check with you.
Thanks again for your dedication and support. Your help is priceless.

**Comment by YuriySamorodov** [comment]
Please upvote on UserVoice =)
https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/42558580--bug-get-pnpsite-bandwitdth-hits-visits-always-ze
