### ISSUE TITLE
[BUG] Get-PnPTeamsTeam invalid giphyContentRating

### ISSUE THREAD

**Issue by milanholemans** [pnp/powershell#1826]
### Reporting an Issue or Missing Feature
When a team's `fun stuff` settings are set to `giphy: allow all content`, you are unable to get this team via `Get-PnPTeamsTeam`.

![image](https://user-images.githubusercontent.com/11723921/166294511-8a04fcaf-4ba6-445b-b44f-190b1c24cbd3.png)

### Expected behavior 
Being able to retrieve the team via `Get-PnPTeamsTeam`

### Actual behavior 
`null` value is returned.

### Steps to reproduce behavior
1. Pick a random team
2. Via the GUI settings, set `fun stuff` to `allow all content` (there is a possibility you don't see this option because it's restricted by the Teams admin center).
3. Use `Get-PnPTeamsTeam -Identity <guid>`

### What is the version of the Cmdlet module you are running?
1.10.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

### Extra
I found out that this is the actual value returned by Graph: 
![image](https://user-images.githubusercontent.com/11723921/166295506-048cb222-f870-44d4-8e5a-476d67e5aaa1.png)

However only `strict` and `moderate` is defined within the code.
https://github.com/pnp/powershell/blob/b0bcff86a7686ff81e7750d1a425ae7883d9fb17/src/Commands/Model/Teams/TeamFunSettings.cs#L41-L45

Because of this, the JSON parse to C# object fails and `null` is returned. I wanted to add `unknownFutureValue` as extra value, but this value cannot be used by other commands (e.g. `Set-PnPTeamsTeam`, `New-PnPTeamsTeam`). When trying to update a team with this value I do get following error:
![image](https://user-images.githubusercontent.com/11723921/166296569-556808fd-0911-4234-bdb9-cac5ad147cd7.png)

What do you think about this? How can we best resolve this?

**Comment by gautamdsheth** [comment]
Well, if its not supported by Graph APIs themselves not sure what we could here.
Maybe once they update the endpoints themselves to return actual proper values , we would be able to change it to a proper enum value.

**Comment by milanholemans** [comment]
Yes, I don't think it's a huge issue, I think 99% of all teams use strict or moderate. It's sad that the GUI supports this, but Graph doesn't.
We could create a separate enum for the Get cmdlet and another for the Set & New. However maybe this is a bit overkill.

**Comment by gautamdsheth** [comment]
Yeah, that would be an overkill. Let's not do it .Once they release a proper enum value we can add that here. Adding a value a different from the one Graph team releases will introduce some breaking changes , will require some backward compatibility code and all that. Lets wait for Graph team to release it.
