### ISSUE TITLE
[sharepoint2019/server subscription onpremise]

### ISSUE THREAD

**Issue by agonzalezm** [pnp/powershell#1828]
What is the reason this doesnt work for sharepoint 2019 or server subscription?  What should we use to connect to them and get all changelog activity and all folders/permissions ?

**Comment by veronicageek** [comment]
We don't support SharePoint onprem anymore and the old module is archived. This is a Community driven module and we do not have the capacity/resources to support every platform. You can use the built in cmdlets or CSOM.
