### ISSUE TITLE
Cannot use Add-PnPFile when authenticating using app creds.[BUG]

### ISSUE THREAD

**Issue by rogers14k** [pnp/powershell#1829]
### Reporting an Issue or Missing Feature
Im unable to run Add-PnPFile -Path $output -Folder $splib when authenticating using app creds.

### Expected behavior 
The file uploads to the respected folder.

### Actual behavior 
 I am getting error: Add-PnPFile : The remote server returned an error: (401) Unauthorized.

### Steps to reproduce behavior
Create an app in Azure (See attachment for api permissions given. Theyve all been tested and work when testing in Graph Explorer)
Also "Enable the following mobile and desktop flows:" is enabled (Saw this in another thread as being disabled could be an issue)

Connect-PnPOnline -ClientId XXXX -Thumbprint XXXX -Tenant "XXXX.onmicrosoft.com" -Url "https://XXXX.sharepoint.com/sites/XXXX"
$output = './app_role_assignments.csv'
$splib = "Shared Documents\O365 Reports"
Add-PnPFile -Path $output -Folder $splib

***Please note that when authenticating to PnP with my admin account, the exact script works just fine. The reason for the change is we want these reports to run in a runbook and not store user creds***

### What is the version of the Cmdlet module you are running?
1.10.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Azure Cloud Shell
- [ ] Azure Functions

![Screen Shot 2022-05-03 at 11 39 16 AM](https://user-images.githubusercontent.com/64924757/166489167-8094c694-60d6-4c2d-bd0d-72c0786dd697.png)

**Comment by gautamdsheth** [comment]
Hi you need to grant permissions for SharePoint resource for this cmdlet as it depends on SharePoint APIs for execution

![image](https://user-images.githubusercontent.com/8832018/166883822-b804ef0a-425c-4d3f-98da-19bbf656567f.png)

from here;

![image](https://user-images.githubusercontent.com/8832018/166883890-b1af7ea5-5c7e-4675-a3fd-c985e3cf4382.png)


and permissions:

![image](https://user-images.githubusercontent.com/8832018/166884046-11af4c48-d79d-4feb-9f05-960f6875fe96.png)

**Comment by rogers14k** [comment]
> Hi you need to grant permissions for SharePoint resource for this cmdlet as it depends on SharePoint APIs for execution
> 
> ![image](https://user-images.githubusercontent.com/8832018/166883822-b804ef0a-425c-4d3f-98da-19bbf656567f.png)
> 
> from here;
> 
> ![image](https://user-images.githubusercontent.com/8832018/166883890-b1af7ea5-5c7e-4675-a3fd-c985e3cf4382.png)
> 
> and permissions:
> 
> ![image](https://user-images.githubusercontent.com/8832018/166884046-11af4c48-d79d-4feb-9f05-960f6875fe96.png)

Thank you it worked! I was so convinced the MS Graph APIs were the right ones that I forgot SharePoint has seperate APIs.
