### ISSUE TITLE
[BUG] Update-Module PnP.PowerShell Wouldn't Remove Older Version

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#183]
### Reporting an Issue or Missing Feature
Most likely wrong place to post a bug or something, so I am asking a **question**

### Expected behavior 
`Update-Module PnP.PowerShell` should replace old module version with a new one.

### Actual behavior 
When executing `Update-Module PnP.PowerShell -AllowClobber` it would keep an older version along with a new one acting similarily to `Install-Module -Force`:
![image](https://user-images.githubusercontent.com/5260172/105928016-3524f300-6056-11eb-9e8e-def8a9a7341d.png)

### Steps to reproduce behavior
```
Get-Module PnP.PowerShell -ListAvailable
Update-Module PnP.PowerShell -AllowPreRelease -Confirm:$false -Force -Scope AllUsers
```
### What is the version of the Cmdlet module you are running?
```
Name    : PnP.PowerShell
Path    : C:\Users\Samorodov\Documents\PowerShell\Modules\PnP.PowerShell\1.2.5\PnP.PowerShell.psd1
Version : 1.2.5

Name    : PnP.PowerShell
Path    : C:\Users\Samorodov\Documents\PowerShell\Modules\PnP.PowerShell\1.2.4\PnP.PowerShell.psd1
Version : 1.2.4
```

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by ToddKlindt** [comment]
I don't think I've ever seen Update-Module remove older versions when installing a new version. By default the newest version will be imported when you reference the module, so it's not a problem. If you want to clean the old ones out, run `Uninstall-Module PnP.PowerShell -AllVersions -Force` before running Install-Module.
