### ISSUE TITLE
Enable-PnPFeature not working with App Auth (Client ID and Secret)

### ISSUE THREAD

**Issue by alexc-MSFT** [pnp/powershell#1830]
When using the Enable-PnPFeature cmdlet to enable features they do not get enabled/activated if you are using app auth i.e. specifying a clientid and clientsecret. 

In my case I am testing with the Document Sets and Document ID Service ones:

b50e3104-6812-424f-a011-cc90e6327318
c85e5759-f323-4efb-b548-443d2216efb5

I am running this code in Azure Automation using the latest PnP PowerShell (1.10.0).

If I test on my machine with the -interactive flag and authenticating as a user then the features get applied correctly.

Is this normal behaviour?

Thanks

**Comment by BaronSparky** [comment]
Hi Alex,

What was the full syntax of the line you used?

I have just tried, using app auth against a site:
```
Enable-PnPFeature -Identity b50e3104-6812-424f-a011-cc90e6327318
Enable-PnPFeature -Identity c85e5759-f323-4efb-b548-443d2216efb5
```

and noted that the Site Collection features were not activated.

I then tried, from the same session:
```
Enable-PnPFeature -Identity b50e3104-6812-424f-a011-cc90e6327318 -Scope Site
Enable-PnPFeature -Identity c85e5759-f323-4efb-b548-443d2216efb5 -Scope Site
```

and they were both activated.

**Comment by alexc-MSFT** [comment]
Hey @BaronSparky ,

I've used the second cmdlets with the Scope set to Site and they do not activate. Worth noting I am not using a certificate though just an Id and a Secret, therefore I'm wondering if this is by design if you don't use a certificate?

Cheers

**Comment by alexc-MSFT** [comment]
Just found out it works when using CSOM once connected with PnP so I'm going to go that route for now 😀

**Comment by veronicageek** [comment]
@alexc-MSFT - I've tested with ClientID + ClientSecret + `-Scope Site` and I can activate both features (doesn't work without the `-Site` parameter). Also note that your second GUID (c85e5759-f323-4efb-b548-443d2216efb5) is for Disposition Approval Workflow. The correct GUID for Document Sets is `3bae86a2-776d-499d-9db8-fa4cdc7884f8`
