### ISSUE TITLE
[BUG] Sync-PnPSharePointUserProfilesFromAzureActiveDirectory: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by staehelir** [pnp/powershell#1837]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
When I run `Sync-PnPSharePointUserProfilesFromAzureActiveDirectory -UserProfilePropertyMapping @{"xxxInitials"="extensionAttribute4"} -Folder $Library` I get the error `Sync-PnPSharePointUserProfilesFromAzureActiveDirectory: Object reference not set to an instance of an object.`

### Expected behavior 
To run this command without an error.

### Actual behavior 
![image](https://user-images.githubusercontent.com/49301523/166932036-0cbe693f-7bfd-46c7-8969-10b182cafaf6.png)

### Steps to reproduce behavior
Step by step according to https://pnp.github.io/powershell/cmdlets/Sync-PnPSharePointUserProfilesFromAzureActiveDirectory.html with required permissions.

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
![image](https://user-images.githubusercontent.com/49301523/166932982-65670323-c671-406e-a64f-bc69a39b1d42.png)

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [x ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by staehelir** [comment]
Get-PnPException

Message          : Object reference not set to an instance of an object.
Stacktrace       :    at PnP.PowerShell.Commands.UserProfiles.SyncSharePointUserProfilesFromAzureActiveDirectory.ExecuteCmdlet() in c:\build\src\Commands\UserProfiles\SyncSharePointUserProfilesFromAzur
                   eActiveDirectory.cs:line 83
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in c:\build\src\Commands\Base\PnPSharePointCmdlet.cs:line 60
ScriptLineNumber : 13

**Comment by gautamdsheth** [comment]
hi @staehelir , can you please try with the latest nightly build and let us know ? 
There were some improvements we did to this cmdlet and maybe that might help with this issue ?

**Comment by KoenZomers** [comment]
Few things to try to get to the bottom of this:

1. Did it actually upload a file to your "User Profile Sync" doclib containing the mapping?
2. If you add -WhatIf to your sync execution line, does the same error also occur?
3. If you do not provide a -Folder, does the same error also occur?
4. Is the site collection in English?
5. Extension attributes in AAD are typically referenced by the client id of the application they are created within. See the documentation you're linking to. Are you sure this is correct what you're doing?
6. What if you provide a different mapping for i.e. your Initials field in SPO to map it from the surname AAD property, just to test this, does the same error also occur?

**Comment by KoenZomers** [comment]
@staehelir any feedback on the above questions?

**Comment by KoenZomers** [comment]
Closing this as no further feedback received.
