### ISSUE TITLE
[FEATURE] New cmdlet Set-PnPTeamsChannelUser

### ISSUE THREAD

**Issue by milanholemans** [pnp/powershell#1841]
After the creation of `Add-PnPTeamsChannelUser`, `Get-PnPTeamsChannelUser` and `Remove-PnPTeamsChannelUser`, we miss the last CRUD cmdlet: `Set-PnPTeamsChannelUser`.

This cmdlet can update the role of a user in a private channel. Valid roles: Owner, Member.

**Describe the solution you'd like**
`Set-PnPTeamsChannelUser -Team "My Team" -Channel "My Channel" -Identity john.doe@contoso.com -Role Owner`

**Describe alternatives you've considered**
Remove the user first by using `Remove-PnPTeamsChannelMember` and then readd the user using `Add-PnPTeamsChannelMember`.

**Additional context**
Cmdlet parameters:

| Parameter | Required | Description |
| --- | --- | --- |
| Team | Yes | Specify the group id, mailNickname or display name of the team to use. |
| Channel | Yes | Specify id or name of the channel to use. |
| Identity | Yes | Specify membership id, UPN or user ID of the channel member. |
| Role | Yes | Specify the role of the user. Valid roles: Owner, Member. |

**Comment by milanholemans** [comment]
I'm willing to work on this one.

**Comment by gautamdsheth** [comment]
Go for it !! All yours 😊🙏🔥
