### ISSUE TITLE
[BUG] Get-PnPSitePolicy doesn't return the policies on recently created sites or if the policy has been created recently even when the Site policy is showing in UI

### ISSUE THREAD

**Issue by kares94** [pnp/powershell#1842]
### Reporting an Issue or Missing Feature
Get-PnPSitePolicy doesn't return the policies on recently created sites or if the policy has been created recently even when the Site policy is showing in UI

### Expected behavior 
When executing Get-PnPSitePolicy -AllAvailable, the list of available policies should match the ones from the SharePoint UI
![image](https://user-images.githubusercontent.com/8974644/167120115-63c6c76a-b5f6-4914-973e-7eee6915fca8.png)

### Actual behavior 
If the site has been created recently or the policy has been created recently, the policy is not being returned by Get-PnPSitePolicy
![image](https://user-images.githubusercontent.com/8974644/167119590-1c1f3d56-0d8c-42c1-983e-13255c6e7642.png)

### Steps to reproduce behavior
Case 1
1. Create a new Site policy in the https://{tenant}.sharepoint.com/sites/contentTypeHub and publish it
2. Execute PowerShell script from below for a site

Case 2
1. Create a new site
2. Execute PowerShell script from below for this new site (the policy should have been created before)

```
$SiteUrl = "https://{tenant}.sharepoint.com/sites/{site}"
Connect-PnPOnline -Url $SiteUrl -Interactive
$AllPolicies = Get-PnPSitePolicy -AllAvailable
Write-Host "Policies: " $AllPolicies
Disconnect-PnPOnline
```

### What is the version of the Cmdlet module you are running?
Manifest 1.10.0 PnP.PowerShell

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [x ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@kares94 - I've tested both scenarios (new site or new policy on existing site) and have no problem when testing within a couple of minutes. Also try in your script with `$AllPolicies.Name`

![image](https://user-images.githubusercontent.com/25181757/167270312-af5bd509-803f-4277-ace9-423ec597d2f2.png)

**Comment by kares94** [comment]
Hi @veronicageek - Thanks for your help! I have tested what you suggested and for some reason Get-PnPSitePolicy doesn't show policies from the ContentTypeHub as you can see in the images below (working with Windows PowerShell ISE). 

I have just created a new Site Policy directly on the site and it is displayed by Get-PnPSitePolicy, meanwhile the other Site Policy, which was created on the https://{tenant}.sharepoint.com/sites/contentTypeHub, doesn't show.

![image](https://user-images.githubusercontent.com/8974644/167353180-773b649f-8793-4446-852a-4eb10d9b23e8.png)

![image](https://user-images.githubusercontent.com/8974644/167353141-39508b0c-459f-49b3-9d8f-6ac2f859eeb7.png)

Also, both policies work in the Sites Closure and Deletion.

![image](https://user-images.githubusercontent.com/8974644/167353604-ff2ef282-f70c-4cb6-ad0c-8855250d0351.png)

**Comment by canberranet** [comment]
I am having this exact issue also

**Comment by michaellumbuku** [comment]
Any resolution to this issue?

**Comment by michaellumbuku** [comment]
Any resolution to this? Im having the same issue

**Comment by canberranet** [comment]
We ended up using
`Set-SPOSite -Identity $SiteURL -LockState "ReadOnly"`
You will get an annoying banner saying the site is under maintenance

**Comment by PeterdenHarder** [comment]
FYI the command Get-PnPSitePolicy is working when you first call 
Add-PnPContentTypesFromContentTypeHub -ContentTypes [GUID] -Site [SiteURL]
cheers

**Comment by veronicageek** [comment]
@kares94 - Can you please update to the latest release `2.1.x` however you **will need PS 7.2 or later** to benefit from all the bug fixes and improvements.

PS5 support has been dropped in the new and future releases.

Feel free to reopen if the issue persists. Thanks.

**Comment by bydimiro** [comment]
I am trying to use get-pnplistpolicy with a policy published in content hub, but it isn´t showing.
I have PS7.5
