### ISSUE TITLE
[BUG]  Connect-PnPOnline throws Win32.Registry exception when running inside a docker container using Powershell-Core and Linux OS

### ISSUE THREAD

**Issue by ahychu84** [pnp/powershell#1846]
### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting
I'm trying to build a site collection using powerscript shells. These scripts work fine when run in Windows but when running them in powershell-core, it throws an exception when running Connect-PnPOnline command.

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets
Succesfully connects to sharepoint site

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.
When attempting to connect to sharepoint online site using Connect-PnPOnline, throws the following Connect-PnPOnline: The type initializer for 'Microsoft.Win32.Registry' threw an exception.

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)
Dockerfile

FROM mcr.microsoft.com/powershell:latest
RUN pwsh -c "Install-Module -Name PnP.PowerShell -F"
CMD pwsh

Connect-PnPOnline -Url "sharepointsite" -Credential (Get-Credential)

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
1.10.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [X] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by shurick81** [comment]
Hi, in Linux, could you try this:

```
docker run --rm -it m365pnp/powershell pwsh -c "\$securedPassword = ConvertTo-SecureString 's;eiufuisGw3()' -AsPlainText -Force; \$adminAccountCredential = New-Object System.Management.Automation.PSCredential( 'shurick81@pnppowershelltest00.onmicrosoft.com', \$securedPassword ); Connect-PnPOnline -Url https://pnppowershelltest00.sharepoint.com -Credentials \$adminAccountCredential; Get-PnPList"
```

**Comment by ahychu84** [comment]
@shurick81 That is exactly how our we are trying to connect. These commands all run fine when using the a windows docker image

**Comment by shurick81** [comment]
Great, have you tried running it in a linux container (m365pnp/powershell) and against this pnppowershelltest00 tenant?

**Comment by ahychu84** [comment]
@shurick81 That works fine, The only difference I'm seeing is the base image. I'm currently using mcr.microsoft.com/powershell:latest. I will try rebuilding my docker image using m365pnp/powershell and get back to you.

Thanks!

**Comment by shurick81** [comment]
Great, let's find out what variables this issue correlates with:
- tenant
- authentication type
- image
- linux/Windows

etc., whatever you have suspicion about

**Comment by ahychu84** [comment]
@shurick81 Found the issue, we actually had some old modules that were being imported when our script was running. I didn't notice it initially since the connect never worked and I never tried it just baseline. Sorry for the trouble!

**Comment by shurick81** [comment]
no trouble, good luck!
