### ISSUE TITLE
Invoke-PnPSiteTemplate - the field was found invalid

### ISSUE THREAD

**Issue by alexc-MSFT** [pnp/powershell#1851]
### Reporting an Issue or Missing Feature
Reporting an Issue

### Expected behavior 
I am trying to apply a site template using Invoke-PnPSiteTemplate, I expect the template to be applied.  

### Actual behavior 
This cmdlet fails with a 'the field was found invalid' error. I am experiencing this issue on two of my customers machines yet on my machine it works completely fine using the same template. I have inspected the template in detail and cannot find any field that would cause this issue.

I fully appreciate that I should also raise this in the pnpframework repo however that repo has tons of issues which are unresolved and have been left stagnant so I am worried this will never be fixed. 

`WARNING: ListInstance Style Library is a Style Library of a site with NoScript enabled and will be skipped
Failed to configure the SharePoint site {0} The field was found invalid:
At C:\Users\adm_e606495\Desktop\New folder\Source\Scripts\deploy.ps1:671 char:9
+ throw('Failed to configure the SharePoint site {0}', $_.Excep ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : OperationStopped: (System.Object[]:Object[]) [], RuntimeException
+ FullyQualifiedErrorId : Failed to configure the SharePoint site {0} The field was found invalid:`

Worth noting this cmdlet is being run from inside my own script, the same error happens outside of it. 

### Steps to reproduce behavior
Invoke-PnPSiteTemplate -Path "C:\template.xml" -ClearNavigation

### What is the version of the Cmdlet module you are running?
1.10.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@alexc-MSFT 

> I am experiencing this issue on two of my customers machines yet on my machine it works completely fine using the same template.

Then we can agree that the cmdlet works and there's something on your customers' environments that is giving you issue? 

Not sure what we can do here. So I'll transfer this as a discussion.
