### ISSUE TITLE
Additional Scripts for SharePoint Syntex

### ISSUE THREAD

**Issue by divya-akula** [pnp/powershell#1858]
A model deletion via powershell scrfipt is not available , right now I have to delete the model usage and models from UI manually , it gets tedious when you are importing and exporting and notice something didnt work as it is supposed to. For others like Entity mapping or content type usage, we do not have any provision in UI or script to check once the model is created

**Describe the solution you'd like**
Remove--pnpSyntexModel <pnpId>

   Should delete the pnp model usage and model based on Id or name
   
 Get-pnpSyntexEntityMappings -Model <ModelID/ModelName> -Name <EName>

 Should retrieve the entity of the specified model and the column name ,it is mapped to.

Get-pnpSyntexModelContentType -Model <ModelId/ModelName>

Should retrieve the content type associated with the model

**Describe alternatives you've considered**
Unfortunately I do not see any alternatives for this.

**Additional context**
N/A

**Comment by LeonArmston** [comment]
Hi @divya-akula 

Does [Unpublish-PnPSyntexModel.md](https://github.com/pnp/powershell/blob/dev/documentation/Unpublish-PnPSyntexModel.md) or are you talking about deleting the model from the content center?

What I believe you need to do to delete the model from the content center - Syntex makes extensive use of Content Types and most of the info is contained as properties in the .classifier file in the model library.

- Delete the Syntex model (SyntexModel.classifier) fromthe Models Library (/Model) in your content center using Remove-PnPFile
- Remove matching Content Type using Remove-PnPContentType.md

Thanks

**Comment by divya-akula** [comment]
Thanks @LeonArmston  this helps
