### ISSUE TITLE
[BUG] Add-PnPListItem : A possible object cycle was detected which is not supported. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 0.

### ISSUE THREAD

**Issue by jolscr** [pnp/powershell#1861]
### Reporting an Issue or Missing Feature
When I use Add-PnPListItem with batch parameter, I receive an error.
If I remove this parameter, it works.

### Expected behavior 
Execute this cmdline with Batch parameter without issue
`Add-PnPListItem -List $NameListInventory -Connection $ConnectionSiteInventory -Batch $batchAdd -Values @{...} `

### Actual behavior 
Add-PnPListItem : A possible object cycle was detected which is not supported. This can either be due to a cycle or if
the object depth is larger than the maximum allowed depth of 0.

At D:\ScriptsPS\Schedule\Teams-ADM-O365\TeamsInventory\TeamsInventory.ps1:418 char:32
 ... PListItem = Add-PnPListItem -List $NameListInventory -Connection $Con ...
 CategoryInfo          : WriteError: (:) [Add-PnPListItem], JsonException
 FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Lists.AddListItem

### Steps to reproduce behavior
`$OutputAddSOPnPListItem = Add-PnPListItem -List $NameListInventory -Connection $ConnectionSiteInventory -Batch $batchAdd -Values @{
						"Title" = $Team.DisplayName; 
						"Description" = $Team.Description;
						"MailNickname" = $Team.MailNickName;
						"GroupId" = $TeamGroupID;
						"Visibility" = $Team.Visibility;
						"Archived" = $Team.Archived;
						"AllowGiphy" = $Team.AllowGiphy;
						"GiphyContentRating" = $Team.GiphyContentRating.toString();
						"AllowStickersAndMemes" = $Team.AllowStickersAndMemes;
						"AllowCustomMemes" = $Team.AllowCustomMemes;
						"AllowGuestCreateUpdateChannels" = $Team.AllowGuestCreateUpdateChannels;
						"AllowGuestDeleteChannels" = $Team.AllowGuestDeleteChannels;
						"AllowCreateUpdateChannels" = $Team.AllowCreateUpdateChannels;
						"AllowDeleteChannels" = $Team.AllowDeleteChannels;
						"AllowAddRemoveApps" = $Team.AllowAddRemoveApps;
						"AllowCreateUpdateRemoveTabs" = $Team.AllowCreateUpdateRemoveTabs;
						"AllowCreateUpdateRemoveConnector" = $Team.AllowCreateUpdateRemoveConnectors;
						"AllowUserEditMessages" = $Team.AllowUserEditMessages;
						"AllowUserDeleteMessages" = $Team.AllowUserDeleteMessages;
						"AllowOwnerDeleteMessages" = $Team.AllowOwnerDeleteMessages;
						"AllowTeamMentions" = $Team.AllowTeamMentions;
						"AllowChannelMentions" = $Team.AllowChannelMentions;
						"ShowInTeamsSearchAndSuggestions" = $Team.ShowInTeamsSearchAndSuggestions;
						"Owner" = $Owners.User;
						"OwnerCount" = $Owners.count;
						"MemberCount" = $Members.count;
						"Guest" = $Guest;
						"GuestCount" = $Guests.count;
						"UrlSharePoint" = $UrlSharePoint;
						"HiddenFromAddressListsEnabled" = $HiddenFromAddressListsEnabled;
						"HiddenFromExchangeClientsEnabled" = $HiddenFromExchangeClientsEnabled;
						"SharedChannelCount" = $SharedChannelCount;
						"PrivateChannelCount" = $PrivateChannelCount;
						"StandardChannelCount" = $StandardChannelCount;
						"PrivateChannelOwnerCount" = $PrivateChannelOwnerCount;
						"PrivateChannelOwnerLT2" = $PrivateChannelOwnerLT2;
						"Confidentialite" = $PropertyBagSitel_Confidentiality;
						"Entite" = $PropertyBagSitel_Entite;
						"DescriptionInit" = $PropertyBagSitel_DescriptionInit;
						"DisplayNameInit" = $PropertyBagSitel_DisplayNameInit;
						"OwnerInit" = $OwnerInit;
						"Supprime" = $False;
						"WhenCreated" = $UnifiedGroup.WhenCreated;
						"Historiquedeschangements" = "$DateAujourdhui : Premier Import"
					}`

### What is the version of the Cmdlet module you are running?
Using PnP.PowerShell module version 1.10

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Hi, have managed to fix the issue, it will be available in tomorrow's nightly !
Thanks for spotting the issue and raising it here :)
