### ISSUE TITLE
[BUG] Set-PnPTenantSite throing error The property or field 'ServerLibraryVersion' has not been initialized.

### ISSUE THREAD

**Issue by Souptak** [pnp/powershell#1862]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Set-PnPTenantSite throing error The property or field 'ServerLibraryVersion' has not been initialized.
This is occuring in one Geo location only in a Multi-Geo tenant.

### Expected behavior 
Set-PnPTenantSite -Identity "SiteURL" -DenyAddAndCustomizePages:$false 
This command should enable custom scripting in Site URL.

### Actual behavior 
Set-PnPTenantSite -Identity "SiteURL" -DenyAddAndCustomizePages:$false is throwing error -
Set-PnPTenantSite : The property or field 'ServerLibraryVersion' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.

### Steps to reproduce behavior
Set-PnPTenantSite -Identity "SiteURL" -DenyAddAndCustomizePages:$false 

### What is the version of the Cmdlet module you are running?
1.10.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by milanholemans** [comment]
Hi @Souptak can you please fill in the issue template? This makes it easier to triage and solve your issue.
Also try to use a more meaningful title please.

**Comment by Souptak** [comment]
> Hi @Souptak can you please fill in the issue template? This makes it easier to triage and solve your issue. Also try to use a more meaningful title please.

Updated, thanks

**Comment by veronicageek** [comment]
@Souptak - Perhaps this error was at a point in time. Can you update to the latest and feel free to reopen if the issue persists. Thanks

(_Note: if you're using PS 5.1 --> use `1.12.80-nightly`_)
