### ISSUE TITLE
[BUG] Get-PnPAppAuthAccessToken and Get-PnPGraphAccessToken return the same value

### ISSUE THREAD

**Issue by joshtransient** [pnp/powershell#187]
### Reporting an Issue or Missing Feature
When using a ClientId and ClientSecret (don't certificate-shame me) for an Azure app registration that has both Graph and SPO permissions, Get-PnPGraphAccessToken return the same value as Get-PnPAppAuthAccessToken

### Expected behavior 
Get-PnPGraphAccessToken should return a token scoped to the Graph audience.

### Actual behavior 
Get-PnPGraphAccessToken returns the same token as Get-PnPAppAuthAccessToken, which is scoped to the SPO audience.

### Steps to reproduce behavior
Set up an Azure app registration with one Graph permission and one SharePoint permission, then:
```
Connect-PnPOnline -ClientId <id> -ClientSecret <secret>
$appToken = Get-PnPAppAuthAccessToken
$graphToken = Get-PnPGraphAccessToken
$appToken -eq $graphToken
```

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 1.2.0
PowerShell 5.1 and 7.1.0

### Which operating system/environment are you running PnP PowerShell on?
(have not tested outside of)
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
I'm a bit confused... Using the access token we retrieve using clientid and clientsecret is an ACS token, never being able to access the graph, nor will we be able to acquire token using those values for the Graph. Has this been working for you? Notice that in the later nightly releases we output a message stating that the cmdlet cannot be used with ACS based auth.

Acquiring a token using clientid and secret through Azure AD OAuth will also not be able to access SharePoint, for that one needs a clientid and certificate (not shaming you! :-)), hence that we only allow to acquire an access token with clientid/secret using SharePoint ACS (e.g. legacy auth)

**Comment by joshtransient** [comment]
I'm not using ACS IDs/secrets. I created an Azure app, went to API Permissions > Add a permission > SharePoint > Sites.FullControl.All. On the same page, I went to Add a permission > Microsoft Graph > GroupMember.Read.All and User.Read.All. Also granted admin consent.

Then, went to appinv.aspx on the site in question and registered the Azure app. Never had a problem running `Invoke-RestMethod` against it like that.

**Comment by joshtransient** [comment]
Sure enough, installed 1.2.6-preview, and was secret-shamed (lol). Works as expected when I provide `-Thumbprint`.

**Comment by erwinvanhunen** [comment]
If you want to include the secret in your script, you can also use a base64 version of your Pfx file and provide the -CertifcateBase64Encoded parameter instead of -Certificate or -Thumbprint.

```powershell
$bytes = Get-Content ./yourpfxfile.pfx -AsByteStream
$base64 = [Convert]::ToBase64String($bytes)
Connect-PnPOnline -Url [url] -ClientId [clientid] -CertificateBase64Encoded $base64
```

Nevertheless it's risky obviously to put the secret/certificate itself inside a script.
