### ISSUE TITLE
[BUG] Get-PnPTeamsChannel | select DisplayName Return Nothing

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#1872]
### Reporting an Issue or Missing Feature
I am reporting a bug

### Expected behavior 
`Get-PnPTeamsChannel | select DisplayName` should return a DisplyaName

### Actual behavior 
`Get-PnPTeamsChannel | select DisplayName` returns nothing` returns nothing
`Get-PnPTeamsChannel | select -expand DisplayName` throws an error

![image](https://user-images.githubusercontent.com/5260172/168695371-04963f0b-67ed-449b-9a9a-167f33295227.png)

### Steps to reproduce behavior
```
Connect-PnPOnline -url <centralAdmin>
Get-PnPTeamsChannel -Team TeamName | select DisplayName
Get-PnPTeamsChannel -Team TeamName | select -expand DisplayName
```

### What is the version of the Cmdlet module you are running?
```
Name    : 0mPnP.PowerShell
Version : 1.10.25
```

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by svermaak** [comment]
Does this work?
`(Get-PnPTeamsChannel -Team "TeamName ")[0] | Select DisplayName`

**Comment by YuriySamorodov** [comment]
Hey @svermaak , thank you. Yes `(Get-PnPTeamsChannel -Team "TeamName ")[0] | Select DisplayName` works.
Another workaround would be saving result to the variable and calling that variable. However, in case you do a quick lookup it does not always a convenient way.

**Comment by svermaak** [comment]
The test was to confirm my suspicion. Your Team has more than one channel so Get-PnPTeamsChannel | select DisplayName will not work

**Comment by YuriySamorodov** [comment]
Well... That sounds like a bug anyway. At least this is a discrepancy from other PowerShell modules.
It does not throw any errors when you do `Get-ADUser | select name` .

**Comment by svermaak** [comment]
Get-PnPTeamsChannel -Team "TeamName" | Select-ExpandProperty DisplayName

**Comment by svermaak** [comment]
Gotha, makes sense

**Comment by svermaak** [comment]
For what it's worth, this works
`Get-PnPTeamsChannel -Team "Team" | % { $_.DisplayName }`

**Comment by svermaak** [comment]
This worked for me
`(Get-PnPTeamsChannel -Team "Teams") | Select DisplayName`

**Comment by gautamdsheth** [comment]
Fixed, will be available in tomorrow's nightly :)
