### ISSUE TITLE
[FEATURE] Add SPO Site URL to Get-PnPTeamsChannel

### ISSUE THREAD

**Issue by svermaak** [pnp/powershell#1873]
**Is your feature request related to a problem? Please describe.**
I want to run Get-PnPTeamsChannel -Team "TEST" and get back not only the Team URL, but also the SPO URL

**Describe the solution you'd like**
Added property to Get-PnPTeamsChannel

**Describe alternatives you've considered**
There's not alternative other that Graph API

**Additional context**
![image](https://user-images.githubusercontent.com/12259728/168728886-22869327-e57e-4d2e-a352-03a4d6b08352.png)

**Comment by milanholemans** [comment]
Hi @svermaak 

This is currently in development. When #1799 completes, you'll be able to retrieve the URL where the channel files are stored.

**Comment by gautamdsheth** [comment]
Closing this, please use `Get-PnPTeamsChannelFilesFolder` cmdlet which will get you the SharePoint folder URL of the teams channel. Unfortunately, we dont get the SharePoint site url for channels in Graph. To get SP site URL, you can use `Get-PnPTeamsTeam` which will get you the the `webUrl` as well.
It is available in the latest nightly build.
