### ISSUE TITLE
Invoke-PnPSPRestMethod cause error when retrieve list items which containts Number column 

### ISSUE THREAD

**Issue by dvselva** [pnp/powershell#1877]
i am trying this commanlet (Invoke-PnPSPRestMethod) from Azure functions, Widnows powershell  for calling SP REST API. for ex when i call this like below, it throws error when select contains Number type column and it has value.

$output = Invoke-PnPSPRestMethod -Url "/_api/web/lists/GetByTitle('xxxx')/items?`$select=Id,Title,numberColumn"

### Reporting an Issue or Missing Feature

Issue

### Expected behavior 
It should return all the field values from Select clause.

### Actual behavior 
Throws error
Invoke-PnPSPRestMethod : One of the identified items was in an invalid format.

![image](https://user-images.githubusercontent.com/21048891/169367080-48f08e21-6e3b-4316-96cf-80b8d5e6a6a4.png)

### Steps to reproduce behavior
Create simple list with number column  and add few items and make sure number column have  values

### What is the version of the Cmdlet module you are running?
Invoke-PnPSPRestMethod

command i am executing
$output = Invoke-PnPSPRestMethod -Url "/_api/web/lists/GetByTitle('xxxx')/items?`$select=Id,Title,numberColumn"

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [x ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
@dvselva - this issue has been fixed. It will be available in tomorrow's nightly build as well as the next major version.

Thanks @4ndri for identifying and fixing the fix :)

**Comment by dvselva** [comment]
@4ndri, @gautamdsheth , Thanks so much. i tried this nightly and it works now. Thanks so much for your time and help
