### ISSUE TITLE
[BUG] Set-PnPListPermission not throwing exception if list does not exist 

### ISSUE THREAD

**Issue by jolscr** [pnp/powershell#1882]
### Reporting an Issue or Missing Feature
Set-PnPListPermission not throwing exception if list doesn't exist.

### Expected behavior 
If list doesn't exist, I want to receive an erreur to catch it with a try-catch.

### Actual behavior 
The code continues to run and permission is not given.

### Steps to reproduce behavior
Parameters User and Role is good in my case and permission is given if the list exist.

Set-PnPListPermission -Identity "/Lists/listNameDontExist" -User $IdentityObject -AddRole $role -Connection $ConnectionSite

### What is the version of the Cmdlet module you are running?
1.10.0     PnP.PowerShell

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Are you use, am not able to reproduce it ?  
Also, the identity parameter is for the List Item ID not for the name of the list
It always throws error if the list doesnt exist:

![image](https://user-images.githubusercontent.com/8832018/169666934-20b77ac5-4499-4c16-903e-bcbaf0e1a4b0.png)

**Comment by jolscr** [comment]
You use not the same cmdlet. On list not on listitem. :)

**Comment by gautamdsheth** [comment]
@jolscr -yep my bad , sorry. Thanks for pointing that out . Have a sent a PR to fix it 😊

**Comment by gautamdsheth** [comment]
@jolscr  - have fixed it, will be available in tomorrows nightly build. 
Thanks for spotting and raising the issue !
