### ISSUE TITLE
[BUG] New-PnPTeamsTeam: Failed to find users with user principal name 

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#1899]
### Reporting an Issue or Missing Feature
I am reporting a bug

### Expected behavior 
`New-PnPTeamsTeam` should not throw any errors when `-Owners` or `-Members` parameters are specified.

### Actual behavior 
When  `-Owners` or `-Members` parameters are specified `New-PnPTeamsTeam` gives an error 

> Failed to find users with user principal name

![image](https://user-images.githubusercontent.com/5260172/170122420-234c302a-2fc2-4b24-9f3c-9bd19db49689.png)

### Steps to reproduce behavior
```
Connect-PnPOnline
New-PnPTeamsTeam -DisplayName Team -MailNickName Team  -Owners Owner@contoso.com -Visibility Private -Members Member1@contoso.com, Member2@contoso.com
```

### What is the version of the Cmdlet module you are running?
```
Name    : PnP.PowerShell
Version : 1.10.28
```

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by 4ndri** [comment]
I had the same bug. this happened if the casing of the UPN was wrong. as a workaround you can use the userId instead of UPN.

But I think this issue has just now been fixed by MSGraph. @YuriySamorodov can you confirm that it's working now?

**Comment by YuriySamorodov** [comment]
Thanks @4ndri ,
I can confirm UPNs are correct. Moreover, `Add-PnPTeamsUser` accepts the same UPN addresses no problem.
Nevertheless, the issue is indeed resolved now. Just wondering, if you have a corresponding ticket from MSGraph? It would be beneficial to  mention it there for future reference and tracking.

Appreciate quick turnaround!

**Comment by 4ndri** [comment]
I'm sorry, I don't have any ticket or other reference. I was working on this problem and tried in graph explorer and suddenly it worked.

**Comment by YuriySamorodov** [comment]
Oh, wow! Sounds like a miracle. =) Thanks again, @4ndri . I guess we are good to go!
