### ISSUE TITLE
Receiving AADSTS50196: The server terminated an operation because it encountered a client request loop.

### ISSUE THREAD

**Issue by TroyHannon** [pnp/powershell#190]
I am using PnP.PowerShell v1.2.0 and I am looping through many websites on our O365 tenant and doing work.  On each look I call Connect-PnPOnline -Url $teamURL -Credentials $PSCredentials

On about the 20th iteration the script fails with:
AADSTS50196: The server terminated an operation because it encountered a client request loop. Please contact your app vendor. 

I did get around this by using one $PSCredentials for the first 15 or so sites and then switched to another credential for the remaining 15 or so.

I found that you fixed a similar issue in 0.3.27-nightly:  https://www.gitmemory.com/issue/pnp/powershell/81/754803648

Thank you,
Troy Hannon

**Comment by erwinvanhunen** [comment]
that's interesting. We actually are reusing the token cache behind the scenes, which would/should prevent the MSAL request to go out and fetch a new token. As long as the token is valid. The moment the token expires the MSAL code will retrieve a new token. All that works seamless as such. If you switch to other credentials we invalidate the token cache, and effectively you're starting from scratch again. 

I'm wondering if it is actually the connect-pnponline itself that is causing the issue? I just ran 100 connects in a loop and have no issues whatsoever. What are you doing in the loop? In broad terms that is. It could be that there is a scenario where the cmdlet will acquire an accesstoken, regardless of the token cache.

**Comment by TroyHannon** [comment]
Sure,

I use Resolve-PnPFolder to confirm the folder I am looking for exists
Use Get-PnPFolderItem to get the files I need to move to the sit from my C: drive folder (about 5-10 files)
Use Move-PnPFile to mov ethe file to the site
Use Get-PnPFolderItem to get the archive folder
Use Remove-PnPFile to delete files older than 14 days old
Disconnect-PnPOnline



Troy Hannon
Programmer/Analyst | Workforce Applications | Technology
CarMax
(804) 747-0422 x3165

[cid:image001.png@01D6F4C5.AD51EB50]


 ** PRIVATE & CONFIDENTIAL**
This electronic message contains confidential information intended for the use of the individual or entity that is the intended recipient. If you are not the designated recipient, please be aware that any dissemination, distribution, or copying of this communication is strictly prohibited. If you have received this electronic transmission in error, please notify the sender and delete the material from any computer on which it exists. Thank you.

**Comment by erwinvanhunen** [comment]
Thank you. I will check out what's happening in the internals of those cmdlets.

**Comment by erwinvanhunen** [comment]
Found it. It's the `Disconnect-PnPOnline`. That cmdlet will completely 'reset' the environment, e.g. clear the token cache too. That means that every new connect will have to request the token again from scratch. The cache is in memory and will only life during the lifetime of the PowerShell session, but when you issue `Disconnect-PnPOnline` we clear it out. 

Effectively you do not have to disconnect to build up a new connection. E.g. drop the Disconnect-PnPOnline from your script and you should not the message anymore. I'll update the documentation for the cmdlet to state someting about it.

**Comment by TroyHannon** [comment]
Great!  I can do that, thank you so much!

Troy Hannon
Programmer/Analyst | Workforce Applications | Technology
CarMax
(804) 747-0422 x3165

[cid:image001.png@01D6F4CA.867F0210]


 ** PRIVATE & CONFIDENTIAL**
This electronic message contains confidential information intended for the use of the individual or entity that is the intended recipient. If you are not the designated recipient, please be aware that any dissemination, distribution, or copying of this communication is strictly prohibited. If you have received this electronic transmission in error, please notify the sender and delete the material from any computer on which it exists. Thank you.

**Comment by erwinvanhunen** [comment]
I'll close this issue, but if it still occurs, do not hesitate to create a new issue, optionally referring to this issue with id #190
