### ISSUE TITLE
[BUG] - `Set-PnPListItem` does not work in batch mode

### ISSUE THREAD

**Issue by linus1984** [pnp/powershell#1901]
https://pnp.github.io/powershell/cmdlets/Set-PnPListItem.html?q=set-pnplistitem
### Code

$values=@{}
$values["Territory"]="EMEA"
$batch = New-PnPBatch

for($i=0;$i -lt 5;$i++)
{
     Set-PnPListItem -List "SalesList" -Identity $i -Values $values -Batch $batch
}
Invoke-PnPBatch -Batch $batch

### Reporting an Issue
Set-PnPListItem does not work in batch mode.
Funny, Add-PnPListItem works as expected in batch mode.

### Expected behavior 
All 5 items should be added to the list in batch mode.

When I execute above code without the Batch parameter (not batch mode) then it works as expected.

### Actual behavior 
Set-PnPListItem -List "SalesList" -Identity $i -Values $value …
Cannot find item with Identity PnP.PowerShell.Commands.Base.PipeBinds.ListItemPipeBind

### Steps to reproduce behavior
Follow batch example on https://pnp.github.io/powershell/cmdlets/Set-PnPListItem.html?q=set-pnplistitem

### What is the version of the Cmdlet module you are running?
PowerShell 7.2.4
PnP.PowerShell 1.10.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
hi @linus1984 , ID cannot be 0 for a SharePoint list item. Its value is always greater than or equal to 1.
So, it is throwing the correct error. 
You need to modify the code to start from ID 1 and then loop over

**Comment by gautamdsheth** [comment]
Hi @linus1984 , realized it was a mistake in the docs as well.

So, have updated the docs to start the loop from 1 instead of 0.

The above statement stands, so SharePoint list items will always begin with ID 1 and then values greater than that.
