### ISSUE TITLE
Can you confirm if 200mb is still the max size? 

### ISSUE THREAD

**Issue by jcandresen** [pnp/powershell#1913]
https://pnp.github.io/powershell/cmdlets/Copy-PnPFile.html indicates 200mb is the max size but the reference listed on the site shows https://docs.microsoft.com/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#moving-and-copying-across-sites says "Each file must be less than 15 GB"

Can you confirm that the max size is still 200mb? 

Sorry if I'm missing something obvious, I'm new to this.

**Comment by KoenZomers** [comment]
@jcandresen, for this cmdlet, PnP PowerShell is directly using the same API as SharePoint uses when using it through the web interface. Therefore the 15 GB limit applies. Just tested it with a 6 GB file and it worked well. I've updated the documentation to remove the 200 mb remark.

Thanks for spotting this!
