### ISSUE TITLE
[BUG]: The request uses too many resources." when executing "Invoke-PnPSiteTemplate"

### ISSUE THREAD

**Issue by VictorAvila83** [pnp/powershell#1928]
### Reporting an Issue or Missing Feature
The request uses too many resources." when executing "Invoke-PnPSiteTemplate

### Description
I use PnP PowerShell to provision my portals in SharePoint Online.

One such portal is deployed with Github Actions (CI/CD) across different site collections (same Tenant). This portal has subsites that are also provisioned with PnP PowerShell, which have been deployed without problems in DEV (3 subsites) and CERT (5 subsites), but in PRE (20 subsites) it ran without problems the first time but when I want to do an update I get the following error 'The request uses too many resources.' when trying to run the command "Invoke-PnPSiteTemplate"

Script that runs at the site collection level:
Invoke-PnPSiteTemplate -Path Templates/Provisioning_Level01.xml -ErrorAction Stop

Error in PRE:
image

Provisioning_Level01.xml:
[Provisioning_Level01.zip](https://github.com/pnp/pnpframework/files/8816018/Provisioning_Level01.zip)

However, if the following XML is provisioned there is no error (in all environments).
[Provisioning_Branding.zip](https://github.com/pnp/pnpframework/files/8816106/Provisioning_Branding.zip)

This same XML (Provisioning_Level01.xml) is provisioned in DEV and CERT without problem, we only found two differences between these environments:

PRE has 20 subsites (subsite provisioning scripts run without errors in all environments, the script running at the site collection level is the one giving the error in PRE).
PRE was created two weeks ago, unlike DEV and CERT which were created at the beginning of the year (I don't know if there is something different in the new site collections).

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [x] Linux

**Comment by gautamdsheth** [comment]
Closing this issue since it is already created in the correct PnP Framework repository:

https://github.com/pnp/pnpframework/issues/672
