### ISSUE TITLE
Use PNP.PowerShell to query MS Lists in private Teams channels

### ISSUE THREAD

**Issue by MarcelHeek** [pnp/powershell#1931]
### Reporting an Issue or Missing Feature
I am experiencing the issue that when using PNP.PowerShell I am unable to read/write against MS Lists (a.k.a Sharepoint lists) store in MS Team sites in private channels

### Expected behavior 
Be able to use cmdlets like Get-PNPList and Get-PNPListItem to interact with lists

### Actual behavior 
When retrieving a list from a private channel inside a Teams sharepoint site I receive the following error
![image](https://user-images.githubusercontent.com/84451910/171618338-1f42eedc-3b2a-4a5c-8bb5-2cb20e6cf5d5.png)

I use an Azure AD service principal which is granted (Admin consent) the sites.selected API permission and the FC permission were granted using Graph API call to the MS Teams SPO site AND the (sub)-site for the private channel. 

If I query the SPO list directy using Graph API calls I can retrieve the list and the items in the list. With the PNP.PowerShell cmdlets however not. Connecting to the SPO site with Connect-PnPOnline works just fine.

### Steps to reproduce behavior
`Connect-PnPOnline -Url $SpoSiteUri -ClientID $SpoClientID -CertificateBase64Encoded $base64EncodedCertificate -CertificatePassword $secureString -Tenant "<tenant>.onmicrosoft.com" -ReturnConnection -Verbose`

`$assignmentsList = Get-PNPList -Identity $polAssignmentListName` 

When I perform the same steps but use my current credentials this works just fine. With a Service Principal with granted API permissions however not.

### What is the version of the Cmdlet module you are running?
1.10.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

Hope there is a simple solution or this gets fixed somehow.

**Comment by MarcelHeek** [comment]
Additional comment : whether I connect to the private channel site or the MS teams site using Connect-PnPOnline, I keep hitting the issue with get-PnPList(item). Also Get-PnPSite fails. It looks like tese cmdlets fail as soon as there is a private channel in the Team.

**Comment by gautamdsheth** [comment]
You need to provide SharePoint resource permissions to your Azure AD app because we are using CSOM under the hood and not Graph endpoints, so SharePoint also has Sites.Selected permission and then it will start working.

![image](https://user-images.githubusercontent.com/8832018/171876492-439342f6-9c34-4b1a-b9dc-bf2caaf3e183.png)

**Comment by gautamdsheth** [comment]
Hi @MarcelHeek , any update on this ?? As mentioned here, you need to provide SharePoint permissions to your Azure AD application as we use SharePoint CSOM/REST APIs underneath to do the list operations

**Comment by MarcelHeek** [comment]
@gautamdsheth 
Great, that works like a charm. Thanks for pointing me in the right direction.
