### ISSUE TITLE
[FEATURE] Add extra parameters for `Set-PnPPlannerTask` cmdlet

### ISSUE THREAD

**Issue by milanholemans** [pnp/powershell#1937]
**Is your feature request related to a problem? Please describe.**
Currently you can only specify a small set of the Planner task options.
We could add:
* Priority (Number 1-10)
* Description

**Describe the solution you'd like**
Something like:
```powershell
Set-PnPPlannerTask -TaskId "abdef" -PercentComplete 50 -Priority 7 -StartDate "2022-06-05" -DueDate "2022-06-07" -Description "Lorem ipsum dolor sit amet"
```

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by milanholemans** [comment]
I'm willing to work on this one.

**Comment by gautamdsheth** [comment]
Go for it 👍😍🙏
