### ISSUE TITLE
[Documentation] What cmdlets allow PnPBatching?

### ISSUE THREAD

**Issue by sympmarc** [pnp/powershell#1939]
This is a documentation question, really.

In the doc [Batching in PnP PowerShell](https://pnp.github.io/powershell/articles/batching) in the last section, it says:

```
Cmdlets that support batching
As of release **1.7.63-nightly** the following cmdlets support batching:

[Add-PnPListItem](https://pnp.github.io/documentation/Add-PnPListItem.md)
[Set-PnPListItem](https://pnp.github.io/documentation/Set-PnPListItem.md)
[Remove-PnPListItem](https://pnp.github.io/documentation/Remove-PnPListItem.md)
[Publish-PnPSyntexModel](https://pnp.github.io/documentation/Publish-PnPSyntexModel.md)
[Unpublish-PnPSyntexModel](https://pnp.github.io/documentation/Unpublish-PnPSyntexModel.md)
[Request-PnPSyntexClassifyAndExtract](https://pnp.github.io/documentation/Request-PnPSyntexClassifyAndExtract.md)
```

First off, those links aren't valid.

I'm wondering what cmdlets support batching today and whether there's any convention we could include in the docs to make it obvious. For example, looking at `Add-PnPListItem` and `Set-PnPListItem`, there is a Batching section and some examples.

I'm happy to help update things if I know what to update!

**Comment by gautamdsheth** [comment]
Thanks Mark for sending the PR to update the docs.
The cmdlets which support batching today are the same ones that are in the docs, no change there.

We dont have any convention as such for batching , but if you have something on your mind to improve , please update it docs, happy to merge it :) 

The syntax for other cmdlets is the same as we have for `Add/Set-PnPListItem`, so the following would work for the Syntex cmdlets as well 

```
$batch = New-PnPBatch 
Unpublish-PnPSyntexModel -Model "Invoice model" -TargetSiteUrl "https://contoso.sharepoint.com/sites/finance" -TargetWebServerRelativeUrl "/sites/finance" -TargetLibraryServerRelativeUrl "/sites/finance/shared%20documents" -Batch $batch

Unpublish-PnPSyntexModel -Model "Invoice model 2" -TargetSiteUrl "https://contoso.sharepoint.com/sites/finance-eur" -TargetWebServerRelativeUrl "/sites/finance-eur" -TargetLibraryServerRelativeUrl "/sites/finance-eur/shared%20documents" -Batch $batch
Invoke-PnPBatch -Batch $batch
```

**Comment by gautamdsheth** [comment]
Yeah would be good to add a badge or something for that.

About, batching we plan to add more batching for other cmdlets, but its not something of a fixed goal and also kinda depends on the PnP Core SDK.

We added batching for these cmdlets because the support for that was available in the PnP Core SDK, no other reason.
Adding batching support to other cmdlets might require some breaking changes, so not 100% if we want to add that in v1 , but maybe sometime in future.

**Comment by sympmarc** [comment]
I'm going to whip up a badge and add it to all the relevant pages. Gotta start somewhere.

**Comment by sympmarc** [comment]
Are the .md files like [Add-PnPListItem](https://github.com/pnp/powershell/blob/dev/documentation/Add-PnPListItem.md) still autogenerated? Are changes I make to them going to "stick"?

**Comment by gautamdsheth** [comment]
Yes, the changes are going to stick when you make the changes to the .md files. They are handwritten and not autogenerated.

**Comment by sympmarc** [comment]
Can we reopen this? I screwed up the paths for the badges and will fix. It worked on my machine! :)

**Comment by KoenZomers** [comment]
Works here as well in the PR, but I indeed see in the eventual article it doesn't work.

Not sure if those snippets would be possible. @gautamdsheth, you an idea how that works by chance?

**Comment by sympmarc** [comment]
It's always really hard to get the paths right between the local copy and the published copy. If you get it right in one place, it's broken in the other!

If there's no quick answer on doing an include, I'll just embed directly, as I did before.

**Comment by KoenZomers** [comment]
Go for that indeed, road of least resistance for now :)

**Comment by sympmarc** [comment]
PR Ready - fingers crossed.

**Comment by sympmarc** [comment]
Dang it. I still don't have it right. Sorry I keep screwing it up.
