### ISSUE TITLE
[BUG] Get-PnPSharingForNonOwnersOfSite and Disable-PnPSharingForNonOwnersOfSite not run in Site admin context

### ISSUE THREAD

**Issue by JaroslawDabrowskiSBP** [pnp/powershell#1948]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
Command Get-PnPSharingForNonOwnersOfSite should properly work in Site administrator context. 

### Actual behavior 
Curently when run command Get-PnPSharingForNonOwnersOfSite as a site administrator (not like as Sharepoint tenant admin) i receive bellow exception

Get-PnPSharingForNonOwnersOfSite : Attempted to perform an unauthorized operation.
At line:1 char:1
+ Get-PnPSharingForNonOwnersOfSite
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPSharingForNonOwnersOfSite], ServerUnauthorizedAccessException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Site.GetSharingForNonOwnersOfSite

### Steps to reproduce behavior
Login as a site administrator
Get-PnPSharingForNonOwnersOfSite
Get-PnPSharingForNonOwnersOfSite : Attempted to perform an unauthorized operation.
At line:1 char:1
+ Get-PnPSharingForNonOwnersOfSite
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPSharingForNonOwnersOfSite], ServerUnauthorizedAccessException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Site.GetSharingForNonOwnersOfSite

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

ModuleType Version    Name                  
---------- -------    ----                              
Manifest   1.10.0     PnP.PowerShell

### Which operating system/environment are you running PnP PowerShell on?
- Windows

**Comment by gautamdsheth** [comment]
@JaroslawDabrowskiSBP  - this is by design, we can't do anything about it because this is how the API works. You need to be a SharePoint tenant admin to execute this command.
