### ISSUE TITLE
[FEATURE] Any plans to move from System.Windows.Forms.WebBrowser IE to Edge so WebView2?

### ISSUE THREAD

**Issue by TiloGit** [pnp/powershell#1955]
https://github.com/pnp/powershell/blob/4abb65e194b815c44ffd45974b154e415a6fdb39/src/Commands/Utilities/BrowserHelper.cs#L45

Just wondering if there are any plans to use WebView2 (using Edge) instead of IE engine with "System.Windows.Forms.WebBrowser" for the login popup.

**Comment by KoenZomers** [comment]
@TiloGit no such plans at this moment. Could you elaborate about the gains if we would do this?

**Comment by TiloGit** [comment]
Hi @KoenZomers  I was using it on a Win Server and went thru the pain to add the various URLs needed for a O365 SP login to the IE Trusted Sites. (so the login pop up works) 
I tried to use Edge but notice that this can only be change in the code. 

IE will be out of support but the WebBrowser engine seems to be excluded form this. 

maybe as of today not much gain it seems ...

**Comment by KoenZomers** [comment]
Have you considered using `Connect-PnPOnline -DeviceLogin`? With that you can just perform the authentication from any (other) device so you don't have to whitelist anything on your server.

**Comment by TiloGit** [comment]
Thanks @KoenZomers  but DeviceLogin only works with Azure AD App.  I use UseWebLogin to avoid the Azure AD App. (yes I'm aware of the limitation of UseWebLogin over Azure AD App)

**Comment by KoenZomers** [comment]
Copy that. Since there is no real advantage of trying to switch to WebView2, for now, looking at our issue list and limited resources, I'm tempted to mark this as a nofix for now. Are you okay with this?

**Comment by TiloGit** [comment]
fair enough. We warm this up closer to the support end of IE WebBrowser engine.

**Comment by henrik0805** [comment]
Have experienced that login using "BrowserHelper.GetWebLoginClientContext" is sometimes not possible. The usual pop-up that would otherwise show the login-in window shows a message that the Internet Explorer is no longer supported, suggesting to use Edge instead. 
I think this only applies to Windows 11, and only sometimes...?? Most of my users are not yet on Windows 11, but I am a little concerned...
