### ISSUE TITLE
Add-PnPTeamsChannel does not create folder in SharePoint

### ISSUE THREAD

**Issue by maeni70** [pnp/powershell#1961]
### Discussed in https://github.com/pnp/powershell/discussions/1515

<div type='discussions-op-text'>

<sup>Originally posted by **Leif-Frederiksen** January 12, 2022</sup>
I have an issue where I use Add-PnPTeamsChannel to create a number of channelse on a Team.
Problem is, that only some of the channels are reflected by folders on the corresponding SharePoint site, and the rest are created as channels in Teams, but have no corresponding folder in SharePoint.

Anyone else having this experience and/or suggestions to resolve this?</div>

**Comment by gautamdsheth** [comment]
You need to use `Get-PnPTeamsChannelFilesFolder` cmdlet to create the folder.

https://pnp.github.io/powershell/cmdlets/Get-PnPTeamsChannelFilesFolder.html

It is available in the latest nightly builds and in the next major release .

**Comment by maeni70** [comment]
Thanks. But how to create the FilesFolder for the channel if it is missing? Is there any cmdlet for that (e.g. Add-PnPTeamsChannelFilesFolder)? I guess, it is not just enough to create the missing folder in corresponding Documents library without corresponding channel knowing about it - for testing I tried it manually but without success.

**Comment by gautamdsheth** [comment]
You need to use `Add-PnPTeamsChannel` first  to create the channel and then use the `Get-PnPFilesFolder` which will trigger the folder creation. This is how Graph API works

**Comment by maeni70** [comment]
@gautamdsheth Thanks for your feedback. After updating to latest build some functionality from PnP.PowerShell in my script is broken. I will create an issue for that.

**Comment by maeni70** [comment]
@gautamdsheth There is a typo in the examples (https://pnp.github.io/powershell/cmdlets/Get-PnPTeamsChannelFilesFolder.html). Parameter for specifying channel should be "Channel" and not "Identity".

**Comment by maeni70** [comment]
Hi @gautamdsheth

Sorry for taking your valuable time, but I cannot make it work with Get-PnPTeamsChannelFilesFolder cmdlet.

There is a registered app with following API permissions (for app not delegated, used by the provisioning script with certificate for authentication):
Files.ReadWrite.All
Group.ReadWrite.All
User.ReadWrite.All
Sites.FullControl.All (SharePoint)

This command is run in a loop (with specified timeout), ignoring "Folder location for this channel is not ready yet" error (in catch):
$filesFolder = Get-PnPTeamsChannelFilesFolder -Team $team -Channel $channelName -ErrorAction Stop

However, corresponding folder is never created. Do you have an idea, why this might not happen? Does it even work in context of a registered app (without an assigned Office 365 license)?

Thanks,
Roger

**Comment by maeni70** [comment]
There is a general issue when enabling MS Teams for a site, which contains spaces (%20) in URL. I guess the spaces are stripped when creating sites in SharePoint UI, however, it is possible with PowerShell. This should be prevented when creating a new site, especially if it is connected to a 365 group. Just mentioning here, if someone experiences the same issues as I did.
