### ISSUE TITLE
ConvertTo-PnPPage works on test tenant but does not work on production environment.

### ISSUE THREAD

**Issue by virender-gupta1** [pnp/powershell#1970]
ConvertTo-PnPPage powershell command works perfectly on test tenant but does not work on prod environment. I have tried different versions of pnp module i.e 1.10.x, 1.10.x nightly, 1.3.0, 1.4.0

Every time it throws below error

ConvertTo-PnPPage : Could not find file 'PnP.Framework.resources'.
At C:\Dentsu\NEON\Migrate_Pages_Prod.ps1:21 char:20
+ ...  $newPage = ConvertTo-PnPPage -PublishingPage -Identity $page.FieldVa ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [ConvertTo-PnPPage], FileNotFoundException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Pages.ConvertToClientSidePage

**Comment by gautamdsheth** [comment]
Can you try using PowerShell 7 and check and let us know ?

**Comment by KoenZomers** [comment]
Closing due to no response received
