### ISSUE TITLE
UpdateSiteClassification: Settings parameter is ignored

### ISSUE THREAD

**Issue by PowershellScripts** [pnp/powershell#1971]
https://github.com/pnp/powershell/blob/e06c687263f07f3d2908970a2cac42ece6f71d46/src/Commands/Site/UpdateSiteClassification.cs#L18

I might be completely wrong here, but is anything done with the value passed through Settings parameter?

Maybe something like this could be added on line 29. It's not tested, and the formatting is done using spaces, not tab (pls don't kill), but maybe you find it useful.

        protected override void ExecuteCmdlet()
        {
            try
            {
                   var settings = PnP.Framework.Graph.SiteClassificationsUtility.GetSiteClassificationsSettings(AccessToken);

                   if (Settings.HasValue)
                   {
                        settings = Settings;
                    }
                    if (!Settings.HasValue)
                    {
                        settings = SetSiteClassification(settings);
                    }
            }
            
            if (settings.Classifications.Contains(settings.DefaultClassification))
                    {
                        PnP.Framework.Graph.SiteClassificationsUtility.UpdateSiteClassificationsSettings(AccessToken, settings);
                    }
                    else
                    {
                        WriteError(new ErrorRecord(new InvalidOperationException("You are trying to set the default classification to a value that is not available in the list of possible values."), "SITECLASSIFICATION_DEFAULTVALUE_INVALID", ErrorCategory.InvalidArgument, null));
                    }
        }
        
        
        private SiteClassificationsSettings SetSiteClassification( SiteClassificationsSettings settings)
        {
                if (ParameterSpecified(nameof(Classifications)))
                {
                    if (settings.Classifications != Classifications)
                    {
                        settings.Classifications = Classifications;
                    }
                }
                if (ParameterSpecified(nameof(DefaultClassification)))
                {
                    if (settings.Classifications.Contains(DefaultClassification))
                    {
                        if (settings.DefaultClassification != DefaultClassification)
                        {
                            settings.DefaultClassification = DefaultClassification;
                            changed = true;
                        }
                    }
                }
                if (ParameterSpecified(nameof(UsageGuidelinesUrl)))
                {
                    if (settings.UsageGuidelinesUrl != UsageGuidelinesUrl)
                    {
                        settings.UsageGuidelinesUrl = UsageGuidelinesUrl;
                        changed = true;
                    }
                }
               return settings;
         }

**Comment by gautamdsheth** [comment]
Thanks @PowershellScripts , have fixed the issue and it will be available in tomorrow's nightly
