### ISSUE TITLE
[BUG]Date column errors when using Batch and Add-PnPListItem

### ISSUE THREAD

**Issue by Rothrock42** [pnp/powershell#1974]
### Reporting an Issue or Missing Feature
Batch adding list items fails when the item includes date columns

### Expected behavior 
Expect the list items to be created as they are when not using batch

### Actual behavior 
Every date column throws an error similar to this "There was an exception while writing field reviewdate. Verify you're using the correct InternalName value for the fiel…" I've checked the internal names and they are correct and if I remove the batch feature the items are created.

### Steps to reproduce behavior
Using code from https://pnp.github.io/script-samples/spo-import-csv-data-to-existing-sharepoint-list/README.html?tabs=pnpps If I remove `-Batch $batch` from the `Add-PnPListItem` line the code works fine and adds the items. When I use the batch it fails. I'm running this on a sample csv of 10 rows.

```
    Write-Output " Items will be added using batch mode"
    Write-Output " Initiate batch" 
    $batch = New-PnPBatch
    $rows.ForEach({
            # convert to hash
            $values = $_ | ArrayToHash
            Add-PnPListItem -List $ListName -Values $values -Batch $batch
        })

   Write-Output " Invoke batch" 
   Invoke-PnPBatch -Batch $batch -Details
   Write-Output " Batch invoked"
```

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 1.10.0 and PowerShell 7.2.3

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
@Rothrock42 - can you please try with the latest nightly build and let us know ? We fixed a few issues around batch item adding and updating.

**Comment by Rothrock42** [comment]
@gautamdsheth Thanks for looking into it. Here is what I did. Uninstalled 1.10.0, installed 1.10.48-nightly, tried with -Batch and got the same errors for all my date columns, commented out the -Batch, reran and the code worked just fine. So I don't think this has been addressed yet.

**Comment by Rothrock42** [comment]
A coworker wasn't having issues with -Batch and date columns. He was importing a different file that had dates in a different format. Mine were formatted like "4/13/2021 12:00:00 AM" and his "2014-06-30". When I added some `ParseExact` and `ToString()` I was able to get the non-batch and batch versions to both work.

So not sure if this still qualifies as a bug? It seems strange to me that batch and non-batch versions of the same data would behave differently.

**Comment by gautamdsheth** [comment]
Yeah, would consider it as not a bug :) 

Batch uses the REST API to add list items, so the date fields need to be valid date/time string or date object like [DateTime] whereas the non-batched approach is based on the slower CSOM methods, so maybe internally they are able to handle this issue.
