### ISSUE TITLE
PnPTenantSite properties are different when getting all sites vs one site.

### ISSUE THREAD

**Issue by bhishma** [pnp/powershell#198]
### Reporting an Issue or Missing Feature
an issue: PnPTenantSite properties are different when getting all sites vs one site.

### Expected behavior 
Consistent naming

### Actual behavior 
When I get all sites `$allSites=Get-PnPTenantSite` and iterate through all sites vs. `$aSite=Get-PnPTenantSite -Url <urlToSite>`, there seem to be differences in Properties.
`$allSites[0]|select *` results in about 72 properties whereas `$aSite|select *` results in 54. More importantly, Property names are different. It causes confusion while checking/setting storage.

All Sites|One Site
------|----------
StorageMaximumLevel|StorageQuota
StorageUsage|StorageUsageCurrent
StorageWarningLevel|StorageQuotaWarningLevel

### Steps to reproduce behavior
```
$allSites=Get-PnPTenantSite
$allSites[0]|select *
```

```
$aSite=Get-PnPTenantSite -Url <urlToSite>
$aSite|Select *
```

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 1.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
Correct! That's an oversight from our end. It will be fixed in 1.2.10-nightly which will be available on the 1st of February.

**Comment by bhishma** [comment]
Thank you. Properties are consistent now (v1.2.10) while getting one vs all. However, still different in getting and setting. We get 
```
StorageQuota                                Property   long StorageQuota {get;set;}
StorageQuotaType                            Property   string StorageQuotaType {get;set;}
StorageQuotaWarningLevel                    Property   long StorageQuotaWarningLevel {get;set;}
StorageUsageCurrent                         Property   long StorageUsageCurrent {get;set;}
```
but we set differently.
` Set-PnPTenantSite -StorageMaximumLevel "" -StorageWarningLevel ""`
Is it possible to make those consistent or alias them?

**Comment by bhishma** [comment]
@erwinvanhunen, do you think it makes sense to add alias so that it is same property name while getting and setting?

**Comment by erwinvanhunen** [comment]
We synced up (added more parameters too) the functionality with the Set-SPOSite cmdlet now.
