### ISSUE TITLE
[BUG] Unable to Create the Catalog Site using Register-PnPAppCatalogSite command

### ISSUE THREAD

**Issue by IAMBasantPandey** [pnp/powershell#199]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
This is an issue

### Expected behavior 
It will create the catalog site with no error

### Actual behavior 
Error 
```
WARNING: Notice that this cmdlet can take considerate time to finish executing.
Register-PnPAppCatalogSite : Unknown Error
At line:1 char:1
+ Register-PnPAppCatalogSite -Url "https://x.sharepoint.com/si ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Register-PnPAppCatalogSite], ServerException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Apps.RegisterAppCatalogSite

```
Register-PnPAppCatalogSite -Url $Url -Owner "x@x.onmicrosoft.com" -TimeZoneId 4 -Force
![image](https://user-images.githubusercontent.com/54974327/106454798-4edc9500-64b1-11eb-88ad-c23da9ba90a0.png)

### Steps to reproduce behavior

Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

1. Connect to Connect-PnPOnline -Url $Url -Credential $cred (using admin tenant with full permission to the user)
2. Register-PnPAppCatalogSite -Url $Url -Owner "x@x.onmicrosoft.com" -TimeZoneId 4 -Force

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

![image](https://user-images.githubusercontent.com/54974327/106454657-1b9a0600-64b1-11eb-877d-1d7ce6cf1672.png)

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
We noticed a bug in the underlying code when trying to create an appcatalog site. We fixed this bug in the upcoming nightly release: 1.2.11-nightly which will be out tomorrow.
