### ISSUE TITLE
[BUG] Cannot work with classic web part, classic wiki, or modern pages on STS#0 sites

### ISSUE THREAD

**Issue by joshtransient** [pnp/powershell#200]
### Reporting an Issue or Missing Feature
On a site using template STS#0, for a sample classic page named "classic.aspx", running:
- `ConvertTo-PnPPage -Identity 'classic.aspx'` errors with "Could not find file 'PnP.Framework.resources'"
- `Get-PnPPage -Identity 'classic'` errors with "Page 'classic.aspx' does not exist", and same error message for classic and wiki pages

Additionally:
- `Get-PnPListItem -List 'SitePages'` and `Get-PnPListItem -List 'Site Pages'` return nothing, despite there being pages in the library
- `$pagesFolder = Get-PnPFolder -Url 'SitePages' -Includes Files` results in `$pagesFolder.ItemCount` equal to the total number pages in the library, but `$pagesFolder.Files` will not have any objects, and `$pagesFolder.Files.Count` will be 0

Ran out of ideas trying to query the Site Pages library, and didn't bother trying any of the page-related `Add-*` cmdlets.

### Expected behavior
Cmdlets should work similarly to how they work on sites that aren't using the STS#0 template

### Actual behavior
Aforementioned

### Steps to reproduce behavior
Aforementioned

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 1.2.0
Windows PowerShell 5.1 and PowerShell 7.1.0

### Which operating system/environment are you running PnP PowerShell on?
Have not tested outside of Windows
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
Hi,

I just checked the exact scenario you're describing with version 1.2.0 but do not run into problems:

![image](https://user-images.githubusercontent.com/7666381/106470230-8abb2e80-64a0-11eb-8aba-eedb391e2202.png)

Notice that if you do not specify any other parameters on ConvertTo-PnPPage the file name be prefixed with "Migrated_".

Also, the other issues you describe work here as intended:

![image](https://user-images.githubusercontent.com/7666381/106470551-e71e4e00-64a0-11eb-8a10-63623c2e5ab7.png)

Especially the error messages that it cannot find the resources trigger me to think that something is wrong with the installation. Have you tried to uninstall it all and reinstall it?

```powershell
Uninstall-Module -Name PnP.PowerShell -AllVersions -Force
Install-Module -Name PnP.PowerShell
```

As  last question: which way of connecting do you use? -UseWebLogin / -Credentials / -ClientId-Certificate?

**Comment by joshtransient** [comment]
Plot thickens:
- Primary machine had 1.2.0 installed through Microsoft365DSC. I uninstalled that module and all dependencies, then re-installed PnP.PowerShell. Same results
- Secondary machine never had PnP.PowerShell installed, but had the same issues
- Created a brand new STS#0 site with no modifications, and all my reported issues still occur on both machines when trying to query SitePages or convert home.aspx

More info:
- I'm installing as admin, with scope AllUsers
- My connect string is `Connect-PnPOnline -Url https://...` with no other arguments, just site collection admin's username and password, no MFA or web login

**Comment by erwinvanhunen** [comment]
Could you provide a fiddler trace and email it to bjansen@microsoft.com? Bert and I will look into it then.

**Comment by erwinvanhunen** [comment]
We received it, thank you, and we will have a look into it.

**Comment by erwinvanhunen** [comment]
Hi Josh,

We checked the trace, and the token that is being sent with every request seems to lack permission scopes. We're missing some  scopes in the token when compared to a token that I get when I connect to my own tenant. We see you're using the PnP ManagementShell multi-tenant application. Could you consider removing that one from your Azure AD and registering it from scratch? Maybe something went wrong during the initial registration? 

Please consider using the latest nightly build PnP PowerShell as we changed the way we authenticate (we now use the interactive flow vs the device code flow)

**Comment by erwinvanhunen** [comment]
@joshtransient : any update?

**Comment by joshtransient** [comment]
I deleted the enterprise app and recreated it with `Register-PnPManagementShellAccess`. The `Get-PnPListItem` and `Get-PnPFolder` examples are now working, but `Get-PnPPage` still can't find the page, and `ConvertTo-PnPPage` now throws this:
"The collection type 'System.Collections.Generic.Dictionary`2[System.Guid,System.String]' is not supported"

**Comment by jansenbe** [comment]
@joshtransient : `Get-PnPPage` only works for modern pages, so not sure if you're loading a modern one or not? The error you mention has been fixed already, you can either use a nightly build or wait for a the next official release

**Comment by joshtransient** [comment]
Finally had some time to test with 1.3.0, and everything looks great. Thanks, everyone.

**Comment by SpliceVW** [comment]
Hmm - I am still able to reproduce this issue, still get the message  `Could not find file 'PnP.Framework.resources`. I've:
- Tried removing the module and reinstalling
- Tested with 1.3.0 and 1.3.5-nightly
- Tried from a fresh machine
- Have deleted the enterprise app and re-registered using `Register-PnPManagementShellAccess`
- Have tested by prompting for credentials and using the `-interactive` flag

@erwinvanhunen can I provide you a Fiddler trace?

**Comment by dkguru** [comment]
Same issue here, even after upgrading PMP shell and switching machine. Our site is migrated from 13 to 16 to online -- in case that is part of the issue?

**Comment by jwiersem** [comment]
I have the same issue
ConvertTo-PnPPage : Could not find file 'PnP.Framework.resources'.
Install module like this:
Install-Module -Name PnP.PowerShell -Scope CurrentUser -AllowClobber

**Comment by jwiersem** [comment]
@joshtransient : Can you reopen this issue?

**Comment by joshtransient** [comment]
Re-opening for the previous two folks who are also experiencing it

**Comment by jansenbe** [comment]
@dkguru / @jimmyHang / @jwiersem / @SpliceVW : Which version of PowerShell is being  used? Does this still repro when using the latest version? (tip add -Verbose to the connect-pnponline so see the version actually used).

**Comment by jwiersem** [comment]
@jansenbe I used the prerelease version of 15 days ago. I dont have IT installed now because im using the old module

**Comment by jansenbe** [comment]
@dkguru / @JimmyHang / @jwiersem / @SpliceVW : we made a change to specify the NeutralResourcesLanguage in the PnP Framework assembly (like we already did in PnP Core SDK). Hope this helps with this issue. Please retry with tomorrow's nightly and let us know

**Comment by jwiersem** [comment]
@dkguru @jimmyhang @SpliceVW Did you check the fix? Im a little hesistant because I dont want to break my setup that is currently working with the old module

**Comment by SpliceVW** [comment]
Not yet, I had moved on to other tasks but I'll try this out tomorrow.

**Comment by JimmyHang** [comment]
I tried this the other, it didn't help same error. For my current project I've downgraded to the "old" pnp and conversion worked..;)

**Comment by sthorley** [comment]
I have installed the latest stable pnp-powershell and am having this issue.

**Comment by hmacinto** [comment]
I have installed the latest stable PnP.PowerShell (v1.5.0) and am having the same issue.  Trying to run the following command, connecting to an on-prem SharePoint 2013 site:
Connect-PnPOnline $sourceSite -TransformationOnPrem -CurrentCredentials -ReturnConnection
Export-PnPPageMapping -CustomPageLayoutMapping -Folder c:\temp -Overwrite
Error:
Export-PnPPageMapping : Could not find file 'PnP.Framework.resources'

**Comment by jwiersem** [comment]
Any progress on reproducing the issue?

**Comment by ma-cu** [comment]
Hello, I also encountered this issue. Do we already have a resolution for this ? 

#724

**Comment by calebmil** [comment]
@jansenbe We are having similar issues for a new admin who is trying to run our transformation scripts.  Use case:

Developer and I both are able to run the scripts successfully.  We have both been working with PnP and recently upgraded to PnP.Framework.

A new admin who had not previously used PowerShell or PnP installed both and gets the "Could not find PnP.resources" when trying to run the same script.  It fails at the line where we call:

ConvertTo-PnPPage -PublishingPage -Identity $page.FieldValues["ID"] -Overwrite -TargetWebUrl $targetSiteUrl -PageLayoutMapping $pageLayoutlocation -WebPartMappingFile $WebPartMappingLocation

**Comment by calebmil** [comment]
> @jansenbe We are having similar issues for a new admin who is trying to run our transformation scripts. Use case:
> 
> Developer and I both are able to run the scripts successfully. We have both been working with PnP and recently upgraded to PnP.Framework.
> 
> A new admin who had not previously used PowerShell or PnP installed both and gets the "Could not find PnP.resources" when trying to run the same script. It fails at the line where we call:
> 
> ConvertTo-PnPPage -PublishingPage -Identity $page.FieldValues["ID"] -Overwrite -TargetWebUrl $targetSiteUrl -PageLayoutMapping $pageLayoutlocation -WebPartMappingFile $WebPartMappingLocation

@jansenbe Update on this use case:  Turns out the new admin was not properly placed in the Site Collection Admins group associated with the source and target sites.  Placing them in that group got rid of this error message.

That having been said, the error reported had no bearing on the root cause.  Perhaps there should be a check for appropriate permissions for the current user inside of ConvertTo-PnPPage with a more useful exception being thrown instead of "Could not find PnP.resources"

**Comment by jwiersem** [comment]
@calebmil : Are you certain that the site collection admin permissions were the issue? I have the issue and my account is SC admin in the source sp2013 location and tenant admin and SC admin in the target location.

**Comment by sohailmerchant** [comment]
@jansenbe I ran into the same issue earlier.  I was connecting it using the `-interactive` parameter.  I got the same error.  

I then connected it using `-UseWebLogin` and it worked fine.  So it seems there is something wrong with -interactive parameter not connecting to the site correctly.  I am using the latest version of PnP.PowerShell 1.9.0

Might be helpful to others.
