### ISSUE TITLE
[BUG] Unable to connect to SharePoint Site under MacOS and Linux

### ISSUE THREAD

**Issue by SewardC** [pnp/powershell#2016]
### Reporting an Issue or Missing Feature
When running `Connect-PnPOnline -Url $Site -Credentials $Cred` on both MacOS and Linux machine, I received the following error
`Error: Unsupported User Type 'Unknown'. Please see https://aka.ms/msal-net-up.` I was able to connect to the same site through a windows machine. 

### Expected behavior 
I would expect the connection established successfully.

### Actual behavior 
The command throws an error instead during the connection command.

### Steps to reproduce behavior
Under an MacOS or Linux machine that has Powershell installed
After setting up $SiteUrl and $Cred, run the following script
`Connect-PnPOnline -Url $Site -Credentials Cred`

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
1.10.0 on both operating systems

### Which operating system/environment are you running PnP PowerShell on?
- [x] Linux (CentOS 7)
- [x] MacOS

**Comment by SewardC** [comment]
Hi Koen,

I am passing in the credentials through the following command
$Cred = Get-Credential

I tried updating to the latest prerelease and the same exception persists.

The following modules are available under both machines after running the following command
Get-Module -ListAvailable
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/8310249/174895914-201f12a4-312a-4354-8ec9-ca386430ef19.png">

The mean of -DeviceLogin works well in both OS that I mentioned.

**Comment by KoenZomers** [comment]
@veronicageek Can you try reproducing this issue on your mac?

**Comment by veronicageek** [comment]
@KoenZomers @SewardC - No issue on my side either on MacOS

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/25181757/174976050-c01f0e1c-cc9f-488a-a156-cfe55db27ce7.png">

**Comment by SewardC** [comment]
@KoenZomers @veronicageek Thank you to you both. I get to realize that username from $Cred was not the LDAP ID but full email address after rethinking about how -DeviceLogin works and now it works.
