### ISSUE TITLE
[FEATURE] Set-PnPListItem without values/always Update()

### ISSUE THREAD

**Issue by fowl2** [pnp/powershell#2018]
**Is your feature request related to a problem? Please describe.**
Often when developing or troubleshooting issues I need to trigger an (remote) event receiver, workflow, flow or webhook without changing any field values. 

Currently `Set-PnPListItem` will not call the appropriate *`Update()` method if no field values or content type are specified or null/empty. I'm not sure if this is intentional, but it's a nice slight optimization if eg. the `Values` `Hashtable` is empty - the number of .

**Describe the solution you'd like**
Addition of a new parameter like `-AlwaysUpdate`, `-Force`, `-AllowEmpty`, etc.

**Describe alternatives you've considered**
1. Always *`Update()` if no other parameters are specified. Might be a bit subtle that `Set-PnPListItem` and `Set-PnPListItem -Values @{}` are different.
2. Always *`Update()` if `UpdateType` is specified.
3. Any of the above, but add a parameter to do in the inverse - ie. `-SkipUnchanged` (name to be bikesheeded).
4. A new cmdlet like `Touch-PnPListItem`. Discoverability might be an issue as `Touch` isn't on the [approved verbs list](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands) 
5. Some combination of above.

**Additional context**
I'd be happy to implement this feature.

--------

Other notes:
1. It's not clear what `Set-PnPListItem -List $list -Identity $id -ContentType:$null` means, but it doesn't currently cause an error - just basically the same thing as `Get-PnPListItem -List $list -Id $id`.
2. According to the approved verbs list apparently `Update` is apparently not recommended for this cmdlet either - it should be `Edit`. Not sure I agree with that, but maybe I'm just used to it now.

**Comment by gautamdsheth** [comment]
@fowl2 - I guess we can add a `-Force` additional parameter for this. That would make it consistent with other cmdlets.

**Comment by gautamdsheth** [comment]
closing it as PR has been merged.
