### ISSUE TITLE
Add-PnPTenantTheme & Get-PnPTenantTheme is not working with Vanity Admin URL

### ISSUE THREAD

**Issue by spcodehelp** [pnp/powershell#2029]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by spcodehelp** [comment]
We are trying to apply new Theme in our tenant and getting error due to Vanity Admin URL..can someone help?

**Comment by Marweis** [comment]
These commands seem to automatically append "-admin", however when a tenant is setup with a vanity url, the admin url may not have this format. Example: https://admin.company.com instead of https://company-admin.sharepoint.com.  It would be great it if this could be modified to allow for passing a custom admin url parameter.

**Comment by KoenZomers** [comment]
Let me have a look how this can be changed. Challenging part here is that we don't have access to such a tenant ourselves to test this, but let me see what I can find and do.

**Comment by Marweis** [comment]
Hi @KoenZomers, Thank you for looking into this!  Yes, Connect-PnPOnline was used first to connect to the correct vanity admin url. Other PnP commands work properly.

**Comment by KoenZomers** [comment]
I now see the actual issue is around Add-PnPTenantTheme and Get-PnPTenantTheme. Please ensure when you file a new issue, you enter the details of what you're doing and trying in the startpost. That helps us to better understand your scenario. I'll have a look at specifically these cmdlets to see why these could be behaving differently.

**Comment by Marweis** [comment]
The Set command is also likely impacted. Thanks for your help on this!

**Comment by KoenZomers** [comment]
It looks like it could be all cmdlets inheriting from PnPAdminCmdlet that would not work well with vanity domain tenants.

**Comment by KoenZomers** [comment]
Can you show me exactly with which line you connect? Of course you can substitute the identifiable components for dummy values. The combination of parameters you're using is most important here.

**Comment by Marweis** [comment]
<#Log in to your tenant #>
Connect-PnPOnline "https://admin.company.com/ " -Interactive

<# Get all custom themes that are available in the tenant #>
Get-PnPTenantTheme

Returns error: 
"The remote name could not be resolved" 'admin-admin.company.com'

**Comment by KoenZomers** [comment]
I think I may have found the bug already. You would need to use `Connect-PnPOnline -Url https://admin.company.com -TenantAdminUrl https://admin.company.com. What does that yield for you on the current version?

**Comment by Marweis** [comment]
We will test and post back soon.

**Comment by KoenZomers** [comment]
Indeed, be sure you test it with the nightly build @spcodehelp. Use `Install-Module PnP.PowerShell -AllowPrerelease -Force -AllowClobber` and you MUST use PowerShell 7, not PowerShell 5.

**Comment by KoenZomers** [comment]
You can also run your connect then using -Verbose to show if its connecting to the proper Admin URL
