### ISSUE TITLE
[BUG] ConvertTo-PnPPage: The collection type 'System.Collections.Generic.Dictionary...' is not supported.

### ISSUE THREAD

**Issue by DmitryVorobyov** [pnp/powershell#203]
### Reporting an Issue or Missing Feature
BUG: ConvertTo-PnPPage not working when trying to convert a publishing page.

Error message: 

_ConvertTo-PnPPage : The collection type 'System.Collections.Generic.Dictionary`2[System.UInt32,System.String]' is not supported._

### Expected behavior 
Expected to convert a Publishing page to a modern page on another site. Started to eventually remove parameters until only the mandatory values remained (the error persisted): 

`ConvertTo-PnPPage -PublishingPage $isPublishingPage -Library $list -Identity $page.FieldValues["FileLeafRef"]`

### Actual behavior 

![image](https://user-images.githubusercontent.com/10333583/106517943-2bace800-64a7-11eb-913e-63f1baa1160a.png)

### Steps to reproduce behavior

```
Connect-PnPOnline -Url $sourceSiteUrl -UseWebLogin
$pages = Get-PnPListItem -List $list -Connection $source | ? {$pageNames.Contains($_.FieldValues["FileLeafRef"])}

foreach($page in $pages) 
{
      ConvertTo-PnPPage -PublishingPage $isPublishingPage -Library "Pages" -Identity $page.FieldValues["FileLeafRef"]
}
```

### What is the version of the Cmdlet module you are running?
1.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
Please upgrade to the latest nightly build. We have made fixes for that in a build later than 1.2.0.  We plan to release 1.3.0 either later this week or early next week which also will contain the fix.

**Comment by DmitryVorobyov** [comment]
Thank you @erwinvanhunen! :)

**Comment by PrasadMadhavan** [comment]
Thanks. I had the same error. It's gone after upgrading to version 1.3.0. However, I get an error like below while trying to use this command ConvertTo-PnPPage -Identity "sourcepage.aspx"  -PublishingPage -TargetWebUrl "https://xxxxx.sharepoint.com/sites/modernuat/EmployeeResources"

Error message is shown below.  I have site collection admin access on both Source and destination site collection.  Multifactor authentication is enabled and I have  used -useWebLogin for authentication.  I don't have permission to access SP Tenant Admin pages.   Can you please advise?  Appreciate your help. 

ConvertTo-PnPPage : {"odata.error":{"code":"-2147024891,
System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied. You do not have permission to
perform this action or access this resource."}}}
ServerErrorTraceCorrelationId: 7b43aa9f-9027-b000-bfd5-6bcf98bf8299
At line:1 char:1
+ ConvertTo-PnPPage -Identity "5--Design-and-build.aspx"  -PublishingPa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [ConvertTo-PnPPage], Exception
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Pages.ConvertToClientSidePage

**Comment by sparkitect** [comment]
> Thanks. I had the same error. It's gone after upgrading to version 1.3.0. However, I get an error like below while trying to use this command 
You may want to open your own issue for this, if you haven't already @PrasadMadhavan.
