### ISSUE TITLE
[BUG] Rename-PnPFolder - Not available for on-prem 2019

### ISSUE THREAD

**Issue by nicole-ge** [pnp/powershell#2039]
Rename-PnPFolder - Not available for on-prem 2019

I have install Today Pnp on sharepoint 2019 onprem. And this important function is missing

**Comment by veronicageek** [comment]
@nicole-ge - This module doesn't support SharePoint on-prem anymore. You could _eventually_ try with the [old module](https://github.com/pnp/pnp-powershell) but it's archived and not maintained anymore.
