### ISSUE TITLE
[BUG] Missing Tenant properties ExternalUserExpirationRequired and ExternalUserExpireInDays

### ISSUE THREAD

**Issue by mpiederiet** [pnp/powershell#2055]
### Reporting an Issue or Missing Feature
Get-PnpTenant and Set-PnpTenant are missing two properties from ITenantProperties: ExternalUserExpirationRequired and ExternalUserExpireInDays

https://pnp.github.io/pnpcore/api/PnP.Core.Admin.Model.SharePoint.ITenantProperties.html#collapsible-PnP_Core_Admin_Model_SharePoint_ITenantProperties_ExternalUserExpirationRequired
https://pnp.github.io/pnpcore/api/PnP.Core.Admin.Model.SharePoint.ITenantProperties.html#collapsible-PnP_Core_Admin_Model_SharePoint_ITenantProperties_ExternalUserExpireInDays

### Expected behavior 
I would expect those cmdlets to expose the mentioned properties

### Actual behavior 
It is not possible to retrieve/change the mentioned properties

### Steps to reproduce behavior
Import-Module Pnp.PowerShell
Get-PnpTenant
Set-PnpTenant -ExternalUserExpirationRequired --> ERROR
Set-PnpTenant -ExternalUserExpireInDays --> ERROR

### What is the version of the Cmdlet module you are running?
1.10.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Thanks for raising this request, has been merged and will be available in tomorrow's nightly

**Comment by mpiederiet** [comment]
Thanks @gautamdsheth for the quick response. I can confirm that the properties now exist for Set-PnpTenant in nightly build 1.10.65, however still miss the properties in Get-PnPTenant:

**PowerShell Module version:**
```
get-module pnp.powershell

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   1.10.65    nightly    PnP.PowerShell                      {Add-PnPAlert, Add-PnPApp, Add-PnPApplicationCustomizer, Add-PnPAvailableSiteClassification, Add-PnPAzureADGroupMember, Add-PnPAzureADGrou…
```

**Set-PnpTenant:**
```
help set-pnptenant -Parameter External*

-ExternalServicesEnabled <Boolean>
    Enables external services for a tenant. External services are defined as services that are not in the Office 365 datacenters.

    The valid values are: True (default) - External services are enabled for the tenant. False - External services that are outside of the Office 365 datacenters cannot interact with SharePoint.

    Required?                    false
    Position?                    named
    Default value                None
    Accept pipeline input?       False
    Accept wildcard characters?  false


-ExternalUserExpirationRequired <Boolean>
    When set to true, it will set enable expiration date for external users.

    Required?                    false
    Position?                    named
    Default value                None
    Accept pipeline input?       False
    Accept wildcard characters?  false


-ExternalUserExpireInDays <Int>
    When a value is set, it means that the access of the external user will expire in those many number of days.

    Required?                    false
    Position?                    named
    Default value                None
    Accept pipeline input?       False
    Accept wildcard characters?  false

```

**Get-PnPTenant:**
```
Get-PnPTenant | Select-Object external* | Format-List * -Force

ExternalServicesEnabled : True
```
**<< ExternalUserExpirationRequired and ExternalUserExpireInDays are still missing >>**

**Comment by gautamdsheth** [comment]
Sorry, my bad, will be available tomorrow, missed it !
