### ISSUE TITLE
-UseWebLogin not working

### ISSUE THREAD

**Issue by ashlingcha** [pnp/powershell#206]
Hi there, 
I have version 3.29.2101.0 and I'm trying to connect to my site but due to multifactor authentication I used the -UseWebLogin although this doesn't seem to work. I've looked into this online and seems that it's no longer supported in newer versions, but am yet to find the workaround?

Regards, 
Ashling

**Comment by ToddKlindt** [comment]
Are you connecting to SharePoint Online? If so, you should replace the SharePointPnPPowerShellOnline with the new PnP.PowerShell module. The current stable version is 1.2.0 and it has the -UseWebLogin parameter. The newest nightly build, 1.2.12-nightly, can be installed with the -AllowPrerelease. The authentication experience has gotten a lot of attention, so if the stable version doesn't work for you it's worth trying the nightly build.

**Comment by pbjorklund** [comment]
I had to switch to -Interactive instead of UseWebLogin in nightlies for it to work iwth MFA.

**Comment by erwinvanhunen** [comment]
-Interactive is absolutely recommended over -UseWebLogin.

**Comment by ToddKlindt** [comment]
> -Interactive is absolutely recommended over -UseWebLogin.

Good to know. I'll stop suggesting -UseWebLogin. :)

**Comment by erwinvanhunen** [comment]
Notice that -Interactive is currently only available in the nightlies
