### ISSUE TITLE
[BUG] Add-PnPListItem fails with "A possible object cycle was detected..." when setting fields in batch mode

### ISSUE THREAD

**Issue by HeKr09** [pnp/powershell#2068]
### Reporting an Issue or Missing Feature
I want to add list items by batch with Add-PnPListItem. I have seen errors mentioned in issue #1890 and #1109.
Unfortunately I do not use dates so maybe I am doing it the wrong way. If I add list items without batch everything is fine.

### Expected behavior 
Adding list items within batch.

### Actual behavior 
![error](https://user-images.githubusercontent.com/43664126/176886344-e941a4ed-8cae-445a-8a02-83ec93f03a92.png)
The error occurs right at the Add-PnPListitem **not** at Invoke-PnPBatch

### Steps to reproduce behavior
I use the following script.
```
$importContent = Import-Csv -Path $PathOfCsvFile -Delimiter ";" -Encoding utf8
$itemsLO = Get-PnPListItem -List "License Overview" -Fields "Id","RequestedCompany","ContractNumber1","LicenseLookup","Start"
$batch = New-PnPBatch
foreach($importItem in $importContent)
{
    $foundItemLO = $itemsLO | Where-Object { $_["RequestedCompany"].LookupId -eq $importItem.RequestedCompanyID -and $_["ContractNumber1"].LookupId -eq $importItem.ContractNumberID -and $_["LicenseLookup"].LookupId -eq $importItem.LicenseID }
    if($null -eq $foundItemLO -or $foundItemLO.Count -eq 0)
    {
        Write-Verbose "Adding new item"
        Add-PnPListItem -List "License Overview" -ContentType "CT License Overview" -Batch $batch -Values @{
            "Title"="License Overview";
            "ContractNumber1"=$importItem.ContractNumberID -as [int];
            "RequestedCompany"=$importItem.RequestedCompanyID -as [int];
            "LicenseLookup"=$importItem.LicenseID -as [int];
            "Start"= $importItem.Start -as [int];
        } | Out-Null
    }
}
Invoke-PnPBatch -Batch $batch
```
The structure of the csv is:
```
"ContractNumberID";"LicenseID";"RequestedCompanyID";"Start"
"2";"163";"47";"17"
```

### What is the version of the Cmdlet module you are running?
1.10.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Did you update to the latest nightly build and test it ?

**Comment by HeKr09** [comment]
This worked.
