### ISSUE TITLE
[BUG] Site LockState  always returns $null

### ISSUE THREAD

**Issue by admaddy** [pnp/powershell#207]
### Reporting an Issue or Missing Feature
`Get-PnPTenantSite -Url $siteUrl -Detailed 
`does not return the correct information for the LockState property. 
It always return $null, where as the site is set to ReadOnly, it should return "ReadOnly"
It does work in PowerShell 5.1 with the old PnP module, it does not work anymore with PnP.PowerShell.  

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

$x.LockState would be "ReadOnly" instead of $null

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.
`LockState is $null
`
### Steps to reproduce behavior

```
# first set a site in ReadOnly state.

$siteUrl = "https://<your sharepoint site here>"
$tenantUrl = "<your tenant site here>"
$con = Connect-PnPOnline -Url $siteUrl -Credentials $cred -ReturnConnection
Set-PnPSite -LockState "ReadOnly" -Connection $con

#  wait some time to be sure it was set, and check to see if it is readonly

$conTenant = Connect-PnPOnline -Url $tenantUrl -Credentials $cred -ReturnConnection
$siteInfo = Get-PnPTenantSite -Url $siteUrl -Detailed -Connection $conTenant
$siteInfo.LockState

# as an extra: run the second part again in PS5.1 with the Old PnP module, and it returns "ReadOnly" as expected

```
### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
1.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
Please update to the latest nightly release, as we've fixed this issue there.

```
Update-Module -Name PnP.PowerShell -AllowPrerelease
```
