### ISSUE TITLE
[BUG] -  Unregister-PnPHubSite : Sequence contains more than one matching element

### ISSUE THREAD

**Issue by reinoutD** [pnp/powershell#2072]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
An issue with Unregister-PnPHubSite

### Expected behavior 
Expected is that the hubsite is unregistered as an Hub 

### Actual behavior 
After running: Unregister-PnPHubSite -Site "https://[OurTenant].sharepoint.com/sites/Hubsite"
Powershell gives back: Unregister-PnPHubSite : Sequence contains more than one matching element

### Steps to reproduce behavior
`Unregister-PnPHubSite -Site "https://Tenant.sharepoint.com/sites/hubsite"`

There are two sites which contains the name of the hubsite: 
- https://[OurTenant].sharepoint.com/sites/Hubsite - which is the actual hubsite
- https://[OurTenant].sharepoint.com/sites/teamHubsite -which is a MS teamsite (called teamHubsite)

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
pnp.powershell - v. 1.10.0  

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@reinoutD - I cannot reproduce your error. I've followed your repro steps, and I can unregister a particular hubsite even if both have the same name. I'm using `v.1.11.0`, can you please update and try again?

![image](https://user-images.githubusercontent.com/25181757/177017016-5acd7ebf-a72f-4ad7-a722-6d9069cc047b.png)
