### ISSUE TITLE
Set-PnPTeamsChannel - is it possible to make it default visible for all members

### ISSUE THREAD

**Issue by JimmyHang** [pnp/powershell#208]
**Is your feature request related to a problem? Please describe.**
We are using PnP to manage our Teams deployment, and our users asks for a way to set Teams channels default visible for all members. Right now Teams owners can do so in Teams channel settings but it's a bit troublesome on hundreds of Teams.

**Describe the solution you'd like**
A switch in Teams PnP PowerShell allowing us to set channel visibility for all members of the Team.

**Comment by erwinvanhunen** [comment]
That was a minor change. Added in release 1.2.13-nightly which will be available tomorrow.

**Comment by JimmyHang** [comment]
wow, thank you so much @erwinvanhunen, :)
