### ISSUE TITLE
[BUG] Connect-PNPOnline not using cached credentials when passing SiteURL via variable

### ISSUE THREAD

**Issue by Luquos** [pnp/powershell#2080]
### Reporting an Issue or Missing Feature
Connect-PNPOnline is not using cached credentials from a previous connection (for example to the tenant admin site) for siteURLs specified via variable.

### Expected behavior 
Expected behaviour is for the cmdlet to use cached credentials.

### Actual behavior 
Cmdlet requesting interactive login again even after login has been conducted previously.

For example, having run: 
$TenantAdminURL = "https://<x>-admin.sharepoint.com"
Connect-PnPOnline -Url $TenantAdminURL -Interactive 

$siteURL =  "https://<x>.sharepoint.com/sites/<y>"
$SiteConn = Connect-PnPOnline -Url $siteurl -Interactive 

Is requesting two authentications rather than the one previously, however,

$TenantAdminURL = "https://<x>-admin.sharepoint.com"
Connect-PnPOnline -Url $TenantAdminURL -Interactive 
 
$SiteConn = Connect-PnPOnline -Url "https://<x>.sharepoint.com/sites/<y>" -Interactive 

Is producing a single authentication as expected.

### What is the version of the Cmdlet module you are running?
1.11.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows

**Comment by KoenZomers** [comment]
I cannot reproduce the issue with the sample you provide, but there has been a change in 1.11 in this area which I think is what you're running into. How it used to work before 1.11 was that when you would disconnect using Disconnect-PnPOnline explicitly, and then connect again using Connect-PnPOnline, it would take your credentials from the previous connect and silently log you on. This was marked as a bug as you're disconnecting for a reason. If you now Disconnect-PnPOnline, it will flush your previous connection and cached credentials and tokens. This now allows you to connect again, potentially with different credentials or an entirely different authentication method. If you don't want to enter credentials again while switching between connecting between different site collections and/or SharePoint Online Admin, simply do not Disconnect-PnPOnline. In this case the cached credentials will be used to make the new connection. I just tested that here and that's working fine.

**Comment by Luquos** [comment]
Ah, that makes a lot of sense, I was disconnecting between sites, I understand where the error was now. Thank you so much for the response, sorry to waste your time here!

**Comment by Luquos** [comment]
Oh, for sure, this change is definitely better in the long-term and fixing it in-situ is proving to be very easy. Thank you for all the help as ever!
