### ISSUE TITLE
Connection parameter seems to be ignored

### ISSUE THREAD

**Issue by PowershellScripts** [pnp/powershell#2086]
https://github.com/pnp/powershell/blob/932f4760ff9aee5a7ef300d2bbee533118fd9a01/src/Commands/Site/SetSite.cs#L105

It doesn't matter what connection is specified in the -Connection parameter. The cmdlet executes for the currently connected site.

**Comment by veronicageek** [comment]
@PowershellScripts - When you open an issue, please use/fill the template provided, that'll help everyone. Thank you.
