### ISSUE TITLE
[BUG] Connect-PnpOnline Giving issues in Azure Function

### ISSUE THREAD

**Issue by lokeshsharma47** [pnp/powershell#2087]
Connect-PnpOnline command was working fine in a Azure function since 3 months and now giving error .

Result: ERROR: The current connection holds no SharePoint context. Please use one of the Connect-PnPOnline commands which uses the -Url argument to connect.

Exception             : 
    Type       : System.InvalidOperationException
    TargetSite : 
        Name          : BeginProcessing
        DeclaringType : PnP.PowerShell.Commands.PnPSharePointCmdlet
        MemberType    : Method
        Module        : PnP.PowerShell.dll
    StackTrace : 
   at PnP.PowerShell.Commands.PnPSharePointCmdlet.BeginProcessing() in c:\build\src\Commands\Base\PnPSharePointCmdlet.cs:line 101
   at PnP.PowerShell.Commands.PnPWebCmdlet.BeginProcessing() in c:\build\src\Commands\Base\PnPWebCmdlet.cs:line 78
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin()
    Message    : The current connection holds no SharePoint context. Please use one of the Connect-PnPOnline commands which uses the -Url argument to connect.
    Source     : PnP.PowerShell
    HResult    : -2146233079
CategoryInfo          : NotSpecified: (:) [Add-PnPListItem], InvalidOperationException
FullyQualifiedErrorId : System.InvalidOperationException,PnP.PowerShell.Commands.Lists.AddListItem
InvocationInfo        : 
    MyCommand        : Add-PnPListItem
    ScriptLineNumber : 916
    OffsetInLine     : 20
    HistoryId        : 1
    ScriptName       : C:\home\site\wwwroot\SPProv-QueueTrigger-Dev\run.ps1
    Line             : $logItem = Add-PnPListItem -List "Logs" -Values @{"Title" = $code; "Message" = $errorsJSON; "Application" = "ProvisioningAutomation"; "TypeRef" = $provType }
                       
    PositionMessage  : At C:\home\site\wwwroot\SPProv-QueueTrigger-Dev\run.ps1:916 char:20
                       + …  $logItem = Add-PnPListItem -List "Logs" -Values @{"Title" = $code; " …
                       +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\home\site\wwwroot\SPProv-QueueTrigger-Dev
    PSCommandPath    : C:\home\site\wwwroot\SPProv-QueueTrigger-Dev\run.ps1
    InvocationName   : Add-PnPListItem
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, C:\home\site\wwwroot\SPProv-QueueTrigger-Dev\run.ps1: line 916

Exception: The current connection holds no SharePoint context. Please use one of the Connect-PnPOnline commands which uses the -Url argument to connect.
Stack:    at PnP.PowerShell.Commands.PnPSharePointCmdlet.BeginProcessing() in c:\build\src\Commands\Base\PnPSharePointCmdlet.cs:line 101
   at PnP.PowerShell.Commands.PnPWebCmdlet.BeginProcessing() in c:\build\src\Commands\Base\PnPWebCmdlet.cs:line 78
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin()

**Comment by MZ86SP** [comment]
Hi,

sounds like the issue here: https://github.com/pnp/powershell/issues/2071

**Comment by KoenZomers** [comment]
@MZ86SP Thanks for adding the reference!

@lokeshsharma47 Please have a look at #2071 as it indeed seems related.

**Comment by lokeshsharma47** [comment]
Thanks ,,, its resolved
