### ISSUE TITLE
Copy-PnPFile - Access Denied error when copying between Site Collections

### ISSUE THREAD

**Issue by alexc-MSFT** [pnp/powershell#210]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Reporting an issue

### Expected behavior 
I am using the Copy-PnPFile cmdlet to copy a folder from a Doc Lib in one Site Collection to the Shared Documents library in another site collection. As tested with older versions of the SharePointPnPPowerShellOnline module - this works fine.

### Actual behavior 
A System.UnauthorizedAccessException message is displayed stating Acccess denied. The account I am using is an admin of both Site Collections and there are no broken permission inheritance at play here.

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

`Connect-PnPOnline -Url "https://contoso.sharepoint.com/sites/example" -UseWebLogin

Copy-PnPFile -SourceUrl "TemplateDocs/Folder1" -TargetUrl "/sites/anothersite/Shared Documents"
'

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

1.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by alexc-MSFT** [comment]
It's perhaps worth noting that in version 3.29.2101.0 of the SharePointPnPPowerShellOnline module, this cmdlet is also broken but with an error stating the Source is null.

**Comment by erwinvanhunen** [comment]
The reason you're seeing this error message in the new module is that you're using cookie based auth. Behind the scenes we call a REST endpoint on the site to use the CopyMove api, and we assumed that an OAuth2 connection was built up. I just fixed that now and merged that fix. The fix will be available in the nightly build: 1.2.13-nightly which will come out tomorrow (2021-02-04), we build it around 04.00 AM European Time during the night. 

Nevertheless, if possible, consider another authentication method than -UseWebLogin as that one is regarded as 'legacy'. In the nightly builds newer than 1.2 we offer an '-Interactive' option which supports MFA using the Interactive OAuth2 flow. It does require you to register either your own Azure AD App entry or use the multi-tenant one available from PnP :

Register-PnPManagementShellAccess

**Comment by alexc-MSFT** [comment]
@erwinvanhunen nice one thank. UseWebLogin was purely running it on my machine. Most of my code uses an App Registration.

Thanks for the heads up on the -Interactive option though!
