### ISSUE TITLE
[BUG] [Documentation] Set-PnPApplicationCustomizer ClientSideComponentProperties 

### ISSUE THREAD

**Issue by wuxiaojun514** [pnp/powershell#2109]
### Reporting a wrong example in Documentation
The problem is on [Set-PnPApplicationCustomizer.md](https://github.com/pnp/powershell/blob/dev/documentation/Set-PnPApplicationCustomizer.md)
I want to know how to use this command to set **ClientSideComponentProperties**, then I tried the [exmple-2](https://github.com/pnp/powershell/blob/dev/documentation/Set-PnPApplicationCustomizer.md#example-2)
![image](https://user-images.githubusercontent.com/29603048/177975190-39302a63-7714-4f47-b1ca-d05a178a6121.png)

However this example command misses double quotation mark in the end so I cannot run this command
![image](https://user-images.githubusercontent.com/29603048/177973335-b49cf986-e859-4525-9e21-d6a7342fd5b2.png)
I added **"** in the end , then I can execute this command
![image](https://user-images.githubusercontent.com/29603048/177973644-539fc95e-2146-43a7-8c43-18b8d0b9486c.png)

Hope someone can fix it in the documentation.

### Steps to reproduce behavior
Just copy the example-2 command and execute it.

### What is the version of the Cmdlet module you are running?
 1.11.0                PnP.PowerShell

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
Thanks @wuxiaojun514 - I have now updated the documentation.
