### ISSUE TITLE
[BUG] Get-PnPSiteDesign: The current connection holds no SharePoint context. 

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/powershell#2123]
This just started after I installed 1.11.0 !!  works OK in version 1.10.0 
### Expected behavior 
All the commands with -PnPSiteDesign  and -PnPSiteScript worked fine with connection to {tenant}-admin.sharepoint.com

### Actual behavior 

All site design commands error:
```
Get-PnPSiteDesign: The current connection holds no SharePoint context. Please use one of the Connect-PnPOnline commands which uses the -Url argument to connect.
```
### Steps to reproduce behavior
```
$adminSiteUrl= "https://ecgmcdev-admin.sharepoint.com/"
Connect-PnPOnline -Url $rootUrl  -ClientId $ClientId -CertificatePath $certPath -CertificatePassword $CertPass  -Tenant $tenant -ReturnConnection #-TenantAdminUrl $adminSiteUrl 
Get-PNPSiteDesign
```
### What is the version of the Cmdlet module you are running?
```
Get-Module -Name "PnP.PowerShell" -ListAvailable
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   1.11.0                PnP.PowerShell                      Core,Desk {Add-PnPAdaptiveScopeProperty, Add-PnPPropertyBagValue, Add-PnPSiteClassification, Copy-PnPFolder…}
```

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
 
Thank you I will downgrade to 1.10.0 now

**Comment by KoenZomers** [comment]
@Ofer-Gal please see the discussion in https://github.com/pnp/powershell/issues/2071 as to why this is and how you can easily fix it on your end.

**Comment by Ofer-Gal** [comment]
That makes sense.
Thank you

**Comment by josy1024** [comment]
to make it clear, this code change worked for `me:`

```powershell
#with 1.10.0 module 
    $pnpconnection = Connect-PnPOnline -Url $sitecollectionurl -UseWebLogin -ReturnConnection

#with 1.11.0 module works in 1.10 and 1.11
    Connect-PnPOnline -Url $sitecollectionurl -UseWebLogin
    $pnpconnection = Get-PnPConnection
```

then use Get-PnPListItem with -connection $pnpconnection parameter.
