### ISSUE TITLE
Import-PnPTermGroupFromXml: Template is not valid

### ISSUE THREAD

**Issue by rtorres-br** [pnp/powershell#2133]
### Reporting an Issue
When trying to import a XML file or string to Term Store using Import-PnPTermGroupFromXml -path "XML file", the following error occur:

Import-PnPTermGroupFromXml: Template is not valid

It does not matter if the XML used has just been exported using Export-PnPTermGroupToXml.

The first line of the XML is:
<pnp:TermGroups xmlns:pnp="http://schemas.dev.office.com/PnP/2021/03/ProvisioningSchema">

### Expected behavior 
XML being imported.

### Actual behavior 
Import-PnPTermGroupFromXml -path "XML file" generates the error:
Import-PnPTermGroupFromXml: Template is not valid

Sometimes, after installing a new version of PNP.Powershell library, it works without issue, but if you restart the computer or closes and reopen Powershell, the error appears and don't go away anymore. It does not matter if you run Powershell as Administrator.

### Steps to reproduce behavior
Get a valid Term Group XML (It does not matter if the XML used has just been exported using Export-PnPTermGroupToXml).
Connect to Sharepoint Office 365 site
Use: Import-PnPTermGroupFromXml -path "XML file"

### What is the version of the Cmdlet module you are running?
PnP.Powershell 1.10 and 1.11.0 to 1.11.11-nightly
(not tested with other versions)

### Which operating system/environment are you running PnP PowerShell on?
The platform used to run the command was:
Office 365 Sharepoint Term Store
Windows 10 (21H2)
Powershell 7.2.5

The same XML and the same command, if used with Powershell 5.1 work fine.

**Comment by prawnz** [comment]
I have the same issue as well.. 
Powershell 7.2.6 with PnP.Powershell 1.11

**Comment by gautamdsheth** [comment]
hi @prawnz , @rtorres-br - have fixed the issue. Was quite weird that it worked in PS 5 and not in PS 7.

It will be available from tomorrow's nightly and in the next major version

**Comment by prawnz** [comment]
Thanks @gautamdsheth
