### ISSUE TITLE
Add-PnPListItem failing with "property or field 'Id' has not been initialized"

### ISSUE THREAD

**Issue by sravanthiGITHUB** [pnp/powershell#2141]
### Discussed in https://github.com/pnp/powershell/discussions/2140

<div type='discussions-op-text'>

<sup>Originally posted by **sravanthiGITHUB** July 13, 2022</sup>
We have written a PnP-PowerShell script that creates and updates list items. Intermittently, the script fails with an error at the Add-PnPListItem cmdlet: "The property or field 'Id' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested."
![powershellscripterror](https://user-images.githubusercontent.com/109225932/178748953-a03a0c32-fa86-40cf-841f-b90fa0847671.jpg)
</div>

**Comment by veronicageek** [comment]
@sravanthiGITHUB - Please open an issue by filling the template so we can the maximum information to try help you. Thanks.
