### ISSUE TITLE
[BUG] Using -TaxonomyItemId for a new site column which links to a term in a hierarchical term set

### ISSUE THREAD

**Issue by paylord** [pnp/powershell#2152]
### Reporting an Issue or Missing Feature
It is possible for a taxonomy site column to point to a term in a hierarchical term set rather than to a term set.  The command works correctly if using TermSetPath.  eg:

Add-PnPTaxonomyField -DisplayName 'New Field -InternalName 'NewField' -Group 'FieldGroup' -TermSetPath 'GroupName|SetName|TermName'

I am guessing, somewhere in the underlying code, it makes an assumption that TaxonomyItemId is for a term set and does not attempt to get a term?

### Expected behavior 
I would expect to be able to use the Add-PnPTaxonomyField with the -TaxonomyItemId property with the GUID of a hierarchical term.

### Actual behavior 
Error message:
Add-PnPTaxonomyField : Object reference not set to an instance of an object on the server. The object is associated with method GetTermSet.

### Steps to reproduce behavior
Add-PnPTaxonomyField -DisplayName 'New Field -InternalName 'NewField' -Group 'FieldGroup' -TaxonomyItemId $guid
(Where $guid relates to a hierarchical term as opposed to a term set)

### What is the version of the Cmdlet module you are running?
1.11.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows

**Comment by gautamdsheth** [comment]
hi @paylord , this issue has been fixed.
Will be available from tomorrow's nightly build and of course whenever we release a new major version.

**Comment by paylord** [comment]
@gautamdsheth  - awesome thank you :)
