### ISSUE TITLE
Unable to send mail outside my organisation i.e. not recieving mail in external domain like gmail.com

### ISSUE THREAD

**Issue by kaushalbcactus** [pnp/powershell#2154]
### Reporting an Issue or Missing Feature
I am unable to send email outside my organisation even if I am using my organisation id and password as mentioned in example

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

### Actual behavior 
Mail to be triggered to both internal and external users like abc@gmail.com

### Steps to reproduce behavior
Send-PnPMail -To "xyz@gmail.com" -Subject "Test" -Body "Test" -From 'abc@organisation.com' -Password 'xxx'

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
1.10.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Azure Functions

**Comment by gautamdsheth** [comment]
Hi, this is not supported by SharePoint itself. You can only send mails to authenticated users in SharePoint/Azure AD.
Would suggest you use a third party provider for such a thing.
Check the link here:

https://sharepoint.stackexchange.com/a/280529/8068
