### ISSUE TITLE
Expose IsLoopEnabled as part of the *-PnPTenant cmdlets

### ISSUE THREAD

**Issue by NikCharlebois** [pnp/powershell#2189]
**Is your feature request related to a problem? Please describe.**
We want to be able to manage Loop components from M365DSC and this would require the underlying PnP components to expose this setting.

**Describe the solution you'd like**
Expose the IsLoopEnabled parameter via the Get & Set -PNPTenant cmdlets.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gautamdsheth** [comment]
hi @NikCharlebois , thanks for the feature request.
We have implemented and merged it in the code. It will be available in tomorrow's nightly and the next major release.
