### ISSUE TITLE
Add-PnPListItem and Set-PnPListItem failing with "property or field 'Id' has not been initialized [BUG]

### ISSUE THREAD

**Issue by sravanthiGITHUB** [pnp/powershell#2190]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

We have written a PnP-PowerShell script that creates and updates list items. Intermittently, the script fails with an error at the Add-PnPListItem and Set-PnPListItem cmdlet: "The property or field 'Id' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested."

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

We expect the creation and updation of list items to execute without any warnings and terminating the script altogether. 

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

For Add-PnPListItem, we get the below error randomly in the loop and script stops executing.
But for Set-PnpListitem, we get the error but script does not terminate instead the command does not set the field values.
![powershellscripterror](https://user-images.githubusercontent.com/109225932/180642413-a3a8e578-fc12-49ab-bdf0-2d71a1386ad0.jpg)

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)
<img width="908" alt="pnpCodeSample" src="https://user-images.githubusercontent.com/109225932/180642683-8a777bd5-8c4f-4aeb-bcf0-b4003859d9f8.png">

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

We are importing below in the beginning of the script.
<img width="904" alt="RegionalImports" src="https://user-images.githubusercontent.com/109225932/180642623-bec24359-f057-4431-a1b3-2fcd0126a204.png">

### Which operating system/environment are you running PnP PowerShell on?
- [Yes] **Windows**
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@sravanthiGITHUB - On your last screenshot, if I'm not mistaken you're using the [old PnP module](https://github.com/pnp/pnp-powershell) (i.e.: `3.29`) which is deprecated and not maintained anymore. Please use the PnP.PowerShell module (this repo), and reopen if the issue persists. Thanks

If you've never use the new module, here is the documentation to get you started:
https://pnp.github.io/powershell/articles/installation.html
