### ISSUE TITLE
[BUG] New-PnPSite using -HubSite parameter returns System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by Nazul** [pnp/powershell#2195]
### Issue
Using:
`New-PnPSite -Type CommunicationSite -Title '<SiteTitle>' -Url 'https://<tenant>.sharepoint.com/sites/<siteAlias>' -Description '<Description>' -Lcid '1033' -HubSiteId '<Guid>' -Connection $connectionVariable`

Fails with this exception:
`New-PnPSite: {"error":{"code":"-2147024891, System.UnauthorizedAccessException","message":"Attempted to perform an unauthorized operation."}}`

However, by doing this:
```
$newSite = New-PnPSite -Type CommunicationSite -Title '<SiteTitle>' -Url 'https://<tenant>.sharepoint.com/sites/<siteAlias>' -Description '<Description>' -Lcid '1033' -Connection $connectionVariable
Add-PnPHubSiteAssociation -Site $newSite -HubSite '<HubSiteUrl>' -Connection $connectionVariable
```
Works without error.

This fails running it locally using both, Windows PowerShell 5.1, PowerShell 7.2 and also using Azure Functions (Windows, runtime 4 with PowerShell 7.0, 64-bit).

### Expected behavior 
`New-PnPSite` with `-HubSite` parameter creates a new site associated with the matching hub site.

### Actual behavior 
Fails with this exception:
`New-PnPSite: {"error":{"code":"-2147024891, System.UnauthorizedAccessException","message":"Attempted to perform an unauthorized operation."}}`

### Steps to reproduce behavior
1. Create a new connection to SharePoint admin, using a SharePoint administrator account, via `$connectionVariable = Connect-PnPOnline -Credentials $credential -Url https://<tenant>-admin.sharepoint.com -ReturnConnection`
2. Use `New-PnPSite` with `-HubSite` parameter trying to create a new site that will be associated with an existing hub site
3. Exception is received, and site is not created

### What is the version of the Cmdlet module you are running?
PnP.PowerShell version 1.11.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [X] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Closing this due to lack of response. 
Also, we are unable to reproduce the issue, checked it locally and it works. 
Please recheck the permissions again.

**Comment by AndreSchiemann** [comment]
Hello @gautamdsheth 
I am experiencing the exact same issue on my side and found this bug ticket via Google.
Is it possible to reopen this bug in order to have one ticket for the issue?

Thanks,
André

**Comment by mmmarkk01** [comment]
I am getting the same error on this. With the only difference that I am running on Azure Automation

**Comment by MrRCG5** [comment]
I am experiencing the same issue:
```
New-PnPSite -Type TeamSiteWithoutMicrosoft365Group -Title $siteTitle -Url $siteFullUrl -SiteDesignId $siteDesign -HubSiteId $siteHubSiteId -Connection $adminSiteConnection -Wait -ErrorAction Stop
New-PnPSite : {"error":{"code":"-2147024891, System.UnauthorizedAccessException","message":"Attempted to perform an unauthorized operation."}}
```
This works:
`New-PnPSite -Type TeamSiteWithoutMicrosoft365Group -Title $siteTitle -Url $siteFullUrl -SiteDesignId $siteDesign -Connection $adminSiteConnection -Wait -ErrorAction Stop`
