### ISSUE TITLE
[BUG] Connect-PnPOnline from Azure Function

### ISSUE THREAD

**Issue by NaffOff** [pnp/powershell#22]
### Reporting an Issue or Missing Feature
When connecting "Connect-PnPOnline" from Azure Function on PowerShell Core 7 an error is thrown 

``Connect-PnPOnline -Url $env:SPO_Url -ClientId $env:SPO_AppId -ClientSecret $env:SPO_AppSecret`` 
The type initializer for 'Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.CoreEventSource' threw an exception.

### Expected behavior 
Connection successful - context available 

### Actual behavior 
``Connect-PnPOnline -Url $env:SPO_Url -ClientId $env:SPO_AppId -ClientSecret $env:SPO_AppSecret`` 
The type initializer for 'Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.CoreEventSource' threw an exception.

### Steps to reproduce behavior
Create a new Azure Function with Application Insights enabled
Runtime version ~3
PowerShell Core 7
Platform x64
requirements.psd1 ``@{ 'PnP.PowerShell' = "0.1.31-nightly" }``
Create a function and exec ``Connect-PnPOnline -Url [URL] -ClientId [AppId] -ClientSecret [AppSecret`]``

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 0.1.31

**Comment by adriennn** [comment]
Seeing the same error when trying to connect with -_CertificateBase64Encoded_ , tried with PnP.PowerShell 0.1.33, 0.1.23, 0.1.10.

**Comment by erwinvanhunen** [comment]
It seems to be related to a conflict between the telemetry code that Microsoft uses in Azure functions. It's a bit of a complex story, but as PnP PowerShell also uses this, there can be situations where different versions of the same underlying library code can cause conflicts. We will have to investigate this one.

**Comment by MikkoKoskinen** [comment]
Struggling with the same problem. The interesting thing is that I have two different tenant where I'm testing this. Both of them are using  PnP.PowerShell 0.1.19 version. The connection is working in one tenant but not in the other one.

**Comment by Surry44** [comment]
Any workarounds people have found to this so we can use Connect-PnPOnline in Azure Functions running PowerShell Core and Runtime V3? Thanks

**Comment by Surry44** [comment]
OK - so I found running: Disable-PnPPowerShellTelemetry -Force first before connecting allows connection to succeed. I appreciate having this disabled wont be desirable from a statistics and usage gathering perspective but it does seem to allow connection to succeed.

**Comment by NaffOff** [comment]
It seems to be working again - tested on 3 different tenants.

Great work guys!
