### ISSUE TITLE
[BUG] Get-PnPSiteCollectionAppCatalog returns 'Object reference not set to an instance of an object'

### ISSUE THREAD

**Issue by jessierobbins** [pnp/powershell#2200]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Reporting an Issue 

### Expected behavior 
The list of Site Collection app catalogs

### Actual behavior 
'Object reference not set to an instance of an object'
![image](https://user-images.githubusercontent.com/4707069/181257595-4ffad199-bb0b-4596-84e3-26e2df7879fe.png)

### Steps to reproduce behavior
Connect-PnPOnline -url https://###-admin.sharepoint.com -Interactive
Get-PnPSiteCollectionAppCatalog

### What is the version of the Cmdlet module you are running?
1.11.0 (Have confirmed this works as expected in 1.10.0)

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by ryder-cayden** [comment]
We are also running into the same issue.

It seems Line 69 of https://github.com/pnp/powershell/blob/dev/src/Commands/Admin/GetSiteCollectionAppCatalog.cs is causing this when the SiteID of the not existent site collection is being passed. This happens when a site collection has been deleted and for some reason it does not get cleared up in the Site Collection App Catalog list(Lists/SiteCollectionAppCatalogs/AllItems.aspx) in the Tenant App Catalog:
`                        appCatalogLocalModel.AbsoluteUrl = Tenant.GetSitePropertiesById(appCatalogLocalModel.SiteID.Value, false).Url;
                        results.Add(appCatalogLocalModel);`
I'm guessing there should be check if the Tenant.GetSitePropertiesById returns null:
`                        var tenantSite = Tenant.GetSitePropertiesById(appCatalogLocalModel.SiteID.Value, false);

                        if(tenantSite != null)
                        {
                            appCatalogLocalModel.AbsoluteUrl = tenantSite.Url;
                            results.Add(appCatalogLocalModel);
                        }
                        else
                        {
                            WriteVerbose($"Site collection App Catalog at {appCatalogLocalModel.AbsoluteUrl} does not exists");
                        } `

**Comment by milanholemans** [comment]
> We are also running into the same issue.
> 
> It seems Line 69 of https://github.com/pnp/powershell/blob/dev/src/Commands/Admin/GetSiteCollectionAppCatalog.cs is causing this when the SiteID of a non-existing site collection is being passed. This happens when a site collection has been deleted and for some reason it does not get cleared up in the Site Collection App Catalog list(Lists/SiteCollectionAppCatalogs/AllItems.aspx) in the Tenant App Catalog: `appCatalogLocalModel.AbsoluteUrl = Tenant.GetSitePropertiesById(appCatalogLocalModel.SiteID.Value, false).Url; results.Add(appCatalogLocalModel);` I'm guessing there should be check if the Tenant.GetSitePropertiesById returns null: `var tenantSite = Tenant.GetSitePropertiesById(appCatalogLocalModel.SiteID.Value, false);
> 
> if(tenantSite != null) { appCatalogLocalModel.AbsoluteUrl = tenantSite.Url; results.Add(appCatalogLocalModel); } else { WriteVerbose($"Site collection App Catalog at {appCatalogLocalModel.AbsoluteUrl} does not exists"); }`

This was indeed the case. `Tenant.GetSitePropertiesById` returns `null` for some deleted sites. I wrote a fix for this so it now takes this into account.

Thank you for the clarification @ryder-cayden!
