### ISSUE TITLE
[BUG] Update-Module for Current User (not an admin on machine)

### ISSUE THREAD

**Issue by sparkitect** [pnp/powershell#2206]
### Reporting an **Issue**
✔ Please confirm what it is that your reporting 

### Expected behavior 
Able to update module in current user scope when not an admin on machine.

### Actual behavior 
Prompted to add specific, named parameter to cmdlet.
Add specific, named parameter to cmdlet.
Told specific, named parameter doesn't exist.
am ded
![image](https://user-images.githubusercontent.com/9206808/181608493-700d3d21-c969-4b0a-989d-9635f6f8a2c2.png)

### Steps to reproduce behavior
see screenshot

### What is the version of the Cmdlet module you are running?
1.10.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@sparkitect - I have no issue using the `-Scope CurrentUser`. Is the module already installed on your machine?

**Comment by sparkitect** [comment]
Yes, the module is definitely installed and I am able to use it most(ly) effectively.

However, it seems the (customer-provided, citrix accessed, virtual) machine has an older version of PowerShellGet installed, and since I am not an admin, I will be unable to update it myself.

Thanks for responding, @veronicageek!

**Comment by ToddKlindt** [comment]
If you use Install-Module instead will it recognize the -Scope parameter?

**Comment by sparkitect** [comment]
> If you use Install-Module instead will it recognize the -Scope parameter?

Yes, that worked. Thank you, @ToddKlindt❕

**Comment by veronicageek** [comment]
@sparkitect 

> However, it seems the (customer-provided, citrix accessed, virtual) machine has an older version of PowerShellGet installed, and since I am not an admin, I will be unable to update it myself

Can you please try on your own machine and not on your customer's one? Again I have no problem with those cmdlets.
If this is not working only on your customer's environment, there won't be much we can do.

**Comment by sparkitect** [comment]
No porblems on my machine, so I'll chalk it up to the older version of PowerShellGet.
I will aslo ask the customer's IT to update the maching for me.

Thanks again for your help, @ToddKlindt❕
