### ISSUE TITLE
[BUG]Set-PnPTermGroup

### ISSUE THREAD

**Issue by jasmeeners** [pnp/powershell#2231]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Set-PnPTermGroup gives an error "Group not found" when invoked

### Expected behavior 
Set-PnPTermGroup -I "My Term Group 1" -Name "new name"

or 

Set-PnPTermGroup -I "4ecafedb-141f-4bd0-b1cc-430046f26f9f"  -Name "new name"

should change the name of "My Term Group 1" 

I have verified that the term group exists using Get-PnPTermGroup -I "My Term Group 1" 

Name                           Id                                  
----                           --                                  
My Term Group 1                4ecafedb-141f-4bd0-b1cc-430046f26f9f

### Actual behavior 
 set-pnptermgroup -I "My Term Group 1"  -Name "new name"

set-pnptermgroup : Group not found
At line:1 char:1
+ set-pnptermgroup -I "My Term Group 1"  -Name "new name"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPTermGroup], PSArgumentException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Taxonomy.SetTermGroup

### Steps to reproduce behavior
$myurl = "https://xxxxx.sharepoint.com"
$con = Connect-PnPOnline -Url $myurl -Interactive

Get-PnPTermGroup -I "My Term Group 1" 
 set-pnptermgroup -I "My Term Group 1"  -Name "new name"

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

ModuleType Version    Name                                ExportedCommands                                                                                                                                                           
---------- -------    ----                                ----------------                                                                                                                                                           
Manifest   1.11.0     PnP.PowerShell                      {Add-PnPAdaptiveScopeProperty, Add-PnPPropertyBagValue, Add-PnPSiteClassification, Copy-PnPFolder...}                                                                      
Manifest   1.10.0     PnP.PowerShell                      {Add-PnPAdaptiveScopeProperty, Add-PnPPropertyBagValue, Copy-PnPFolder, Export-PnPClientSidePage...}                                                                       
Manifest   1.5.0      PnP.PowerShell                      {Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add-PnPClientSideText, Add-PnPClientSideWebPart...}    

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by milanholemans** [comment]
Hi @jasmeeners 

I found the issue and made a fix for it. You'll have to wait for a maintainer to review the PR before the fix is available in the next dev release.

**Comment by jasmeeners** [comment]
That is awesome thanks!

How do I know when new release is available and how do I get it ?

Thanks

**Comment by milanholemans** [comment]
Hi @jasmeeners 

The PR is made is https://github.com/pnp/powershell/pull/2232 as you can see, it has satus `open` right now. When it has the status `Merged` or `Closed` it means that it has been completed. Once the PR has been completed, it will be available in the nightly build of PS. You can download this the day after it has been approved by running the command below
```powershell
Install-Module -Name PnP.PowerShell -AllowPrerelease -SkipPublisherCheck -AllowClobber
```

**Comment by jasmeeners** [comment]
Hi Milan;

I have another question, hopefully you can help with.

I am trying to learn the pnp powershell cmdlets that I need for some work I am doing.

The ONLY source of documentation I can find is the documentation available through GitHub, and the odd bit of sample code.

https://pnp.github.io/powershell/cmdlets/Set-PnPTermGroup.html

however, I find that it is not very comprehensive in many cases.

For example, parameters are not explained sufficiently, or examples using those parameters are not given.

I have searched all over the internet, but I cannot find a more comprehensive set of technical documentation on these cmdlets, which makes learning how to use them a “trial and error” exercise.

CAN YOU RECOMMEND a more comprehensive source of documentation or approach to understanding how cmdlets work?

Much appreciated!!!

**Comment by jasmeeners** [comment]
Hi Milan;


Here is a specific example of some of the confusion I run into:

If I want to get a list of all the termgroups on the site collection term store what do I specify for the -TermStore parameter

Get-PnPTermGroup -TermStore <what to specify for site collection term groups?>


If I enter:
Get-PnPTermGroup

I get both gobal term groups and the site collection term group

get-pnptermgroup

Name                           Id
----                           --
Global Term Group Automated1   d4e266cf-5220-400d-8590-6dc3a1653de5
My Term Group 1                4ecafedb-141f-4bd0-b1cc-430046f26f9f
My Term Group 2                c55a1916-41cb-4105-b847-fda1bf98fb43
My Term Group n                47e6a747-9081-4323-88b8-58afc0709be1
People                         3e0f5e84-0ca3-4126-a9d9-f88d7f54da1f
Search Dictionaries            d87b6a37-c801-4a36-9046-6296d4779c87
Site Collection - x7lzk.sha... c7b52189-85df-4263-8b4e-1ee909983415
System                         398bee06-8566-4706-94f4-c68b81c7c321
TermGroup1                     faeb38dd-8c5e-4919-8986-e0fc2114e1fc


If I specify the global term store I get the same results!

get-pnptermgroup -TermStore “Taxonomy_fZyfmbKZzg0YX3AVeh4FVA==”

Name                           Id
----                           --
Global Term Group Automated1   d4e266cf-5220-400d-8590-6dc3a1653de5
My Term Group 1                4ecafedb-141f-4bd0-b1cc-430046f26f9f
My Term Group 2                c55a1916-41cb-4105-b847-fda1bf98fb43
My Term Group n                47e6a747-9081-4323-88b8-58afc0709be1
People                         3e0f5e84-0ca3-4126-a9d9-f88d7f54da1f
Search Dictionaries            d87b6a37-c801-4a36-9046-6296d4779c87
Site Collection - x7lzk.sha... c7b52189-85df-4263-8b4e-1ee909983415
System                         398bee06-8566-4706-94f4-c68b81c7c321
TermGroup1                     faeb38dd-8c5e-4919-8986-e0fc2114e1fc


Documentation says


    -TermStore <TaxonomyTermStorePipeBind>
        Term store to use; if not specified the default term store is used.

What is the “default term store” ?

What is an example of a term store as a parameter?

Can you specify the site collection term store? If so - Where do you get that value from?

Very confusing!

Thanks






From: Steve ***@***.***>
Sent: Saturday, August 6, 2022 3:39 PM
To: ***@***.***>
Subject: RE: [pnp/powershell] [BUG]Set-PnPTermGroup (Issue #2231)

Hi Milan;

I have another question, hopefully you can help with.

I am trying to learn the pnp powershell cmdlets that I need for some work I am doing.

The ONLY source of documentation I can find is the documentation available through GitHub, and the odd bit of sample code.

https://pnp.github.io/powershell/cmdlets/Set-PnPTermGroup.html

however, I find that it is not very comprehensive in many cases.

For example, parameters are not explained sufficiently, or examples using those parameters are not given.

I have searched all over the internet, but I cannot find a more comprehensive set of technical documentation on these cmdlets, which makes learning how to use them a “trial and error” exercise.

CAN YOU RECOMMEND a more comprehensive source of documentation or approach to understanding how cmdlets work?

Much appreciated!!!

**Comment by milanholemans** [comment]
Hi @jasmeeners 

> The ONLY source of documentation I can find is the documentation available through GitHub, and the odd bit of sample code.

This is correct. The link you posted is the only official documentation, as far as I know there's no other documentation available. I agree that sometimes it might be hard to comprehend, but in that case you can ask for more info here or you can update the documentation yourself.
It will always be a little trial & error until you get what you want.

> If I want to get a list of all the termgroups on the site collection term store what do I specify for the -TermStore parameter

I'm not entirely sure why the `-TermStore` parameter is there, however when I connect to a specific site, I do get site term groups.
Hope this solves your issue.

![image](https://user-images.githubusercontent.com/11723921/183266945-36eefb1b-51df-42d4-af47-02e71e54cde2.png)


```powershell
Connect-PnPOnline https://tenant.sharepoint.com/site/project-x
Get-PnPTermGroup
```

**Comment by jasmeeners** [comment]
I was thinking that the -TermStore Parameter allowed you to specify either a site specific term store, or the global term store and only return those term groups. But it is not clear from the documentation what the actual purpose of the parameter is for.

I was just trying to understand what the parameter actually does

Thanks!

**Comment by gautamdsheth** [comment]
hi @jasmeeners , the issue has been fixed by @milanholemans !
It will be available from tomorrow's nightly and the next major version.

Thank you for raising the issue and thanks Milan for providing the fix.
