### ISSUE TITLE
[BUG] Set-PnPTenantSite parameter set cannot be resolved using -Url with -NoScriptSite:$false

### ISSUE THREAD

**Issue by cdragosf** [pnp/powershell#224]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
Successfully enable script support for the site in the -Url parameter.

### Actual behavior 
Error message, "Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided."

Same behavior on both Windows PowerShell and Azure Functions V3 with PS 7.0 runtime.

![image](https://user-images.githubusercontent.com/19550972/107078461-a864fc80-67ee-11eb-802a-b0f5b003bced.png)

### Steps to reproduce behavior
Set-PnPTenantSite -Url $mySiteUrl -NoScriptSite:$false 

### What is the version of the Cmdlet module you are running?
![image](https://user-images.githubusercontent.com/19550972/107078191-3ee4ee00-67ee-11eb-9819-0bf0aa24e42d.png)

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [X] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
You need to use it as below, the previous implementation has changed :

Set-PnPSite -Identity https://mytenant.sharepoint.com/sites/test -DenyAddAndCustomizePages $false

**Comment by cdragosf** [comment]
> You need to use it as below, the previous implementation has changed :
> 
> Set-PnPSite -Identity https://mytenant.sharepoint.com/sites/test -DenyAddAndCustomizePages $false

I'll give it a try. 👍

**Comment by ToddKlindt** [comment]
We're looking at two different cmdlets here, Set-PnPTenantSite and Set-PnPSite. You use the former when your Connect-PnPOnline URL is the Admin site. You use the latter when your Connect-PnPOnline URL is the site itself. 
Set-PnPTenantSite doesn't have a NoScriptSite parameter in either the stable 1.2.0 or the 1.2.14-nightly build. It does have a DenyAddAndCustomizePages parameter which is another way of doing the same thing. That parameter is a Switch, meaning it's False unless you pass it, then it's True. If for some reason you want to manually specific False on a Switch (as opposed to just omitting it) you do it like this: -DenyAddAndCustomizePages:$false
Set-PnPSite (both1.2.0 and 1.2.14-nightly) has a NoScriptSite parameter. It is also a Switch. To make it True, simply pass -NoScriptSite. To make it False , omit it, or pass -NoScriptSite:$false. In the majority of cases there's no reason to pass a Switch with $false. Just not adding it makes it False.

**Comment by cdragosf** [comment]
> We're looking at two different cmdlets here, Set-PnPTenantSite and Set-PnPSite. You use the former when your Connect-PnPOnline URL is the Admin site. You use the latter when your Connect-PnPOnline URL is the site itself.
> Set-PnPTenantSite doesn't have a NoScriptSite parameter in either the stable 1.2.0 or the 1.2.14-nightly build. It does have a DenyAddAndCustomizePages parameter which is another way of doing the same thing. That parameter is a Switch, meaning it's False unless you pass it, then it's True. If for some reason you want to manually specific False on a Switch (as opposed to just omitting it) you do it like this: -DenyAddAndCustomizePages:$false
> Set-PnPSite (both1.2.0 and 1.2.14-nightly) has a NoScriptSite parameter. It is also a Switch. To make it True, simply pass -NoScriptSite. To make it False , omit it, or pass -NoScriptSite:$false. In the majority of cases there's no reason to pass a Switch with $false. Just not adding it makes it False.

Copy pasted from the documentation:

![image](https://user-images.githubusercontent.com/19550972/107091256-c556fb00-6801-11eb-8760-b470c1a00813.png)

[https://github.com/pnp/powershell/blob/dev/documentation/Set-PnPTenantSite.md#example-5](url)

**Comment by ToddKlindt** [comment]
The link to the example didn't work for me, but I did confirm that is example #5. In that case the -NoScriptSite:$false syntax makes sense as you're flipping the bit at the site.

**Comment by KoenZomers** [comment]
Well noticed @cdragosf! I've fixed the inconsistency between the documentation and the cmdlet in PR https://github.com/pnp/powershell/pull/309. It will update the sample in the documentation to use -DenyAddAndCustomizePages and add the alias to the cmdlet to still support -NoScriptSite for backwards compatbility.

**Comment by KoenZomers** [comment]
Closing this issue assuming this will resolve it. If not after the PR is merged and the new nightly build came out, feel free to reopen.
