### ISSUE TITLE
Set-PnPGroupPermissions stoped working today 

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/powershell#2244]
Up until this morning I ran scripts using 
```
Set-PnPGroupPermissions -Identity $visitorsGroup.Title  -List "DPC Documents" -AddRole @('Contribute') -Connection $projConn
```
With no problem 
today the same statement shows error:
```
Set-PnPGroupPermissions : Method not found: 'System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1<Boolean> 
Enumerator.MoveNextAsync()'.
At line:1 char:1
+ Set-PnPGroupPermissions -Identity $visitorsGroup.Title  -List "DPC Do ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPGroupPermissions], MissingMethodException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Principals.SetGroupPermissions
```

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

What can cause it?

**Comment by Ofer-Gal** [comment]
No

**Comment by CallumCrowley** [comment]
I would recommend rolling back to 1.10 in the short term, while this problem is reproduced and fixed.

**Comment by gautamdsheth** [comment]
hi @Ofer-Gal , we havent changed anything from our end here, are you able to reproduce this issue on different tenants ? Looking at the error, seems like some other module is causing a conflict, so maybe you can try with loading just PnP PowerShell in your PS session and try ?

**Comment by gautamdsheth** [comment]
Closing this due to lack of response. 
We haven't made any changes as such to the cmdlet.

**Comment by mvanders** [comment]
I discovered the same issue :-s

The error:
Set-PnPGroupPermissions : Method not found: 'System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1<Boolean> 
Enumerator.MoveNextAsync()'.
At line:372 char:9
+         Set-PnPGroupPermissions -Identity $DeputiesGroupName -List "S ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Set-PnPGroupPermissions], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.Principals.SetGroupPermissions

**Comment by mvanders** [comment]
Why isn't anybody responding? For us, this is urgent, as it is part of an automation script!

**Comment by CallumCrowley** [comment]
@mvanders this issue has been closed for over a year and also references an old version of PnP.PowerShell

Please create a new issue with all the relevant information.
