### ISSUE TITLE
[FEATURE] Be able to create Shared Channels

### ISSUE THREAD

**Issue by McoreD** [pnp/powershell#2247]
**Is your feature request related to a problem? Please describe.**

Hi all,
We have automated creation of Standard and Private Channels using the templates below:

   <pnp:Channels>
        
        <pnp:Channel DisplayName="Communications"
          Description=""
          IsFavoriteByDefault="false" />
       <pnp:Channel DisplayName="Develop"
          Description=""
          IsFavoriteByDefault="false" />
        <pnp:Channel DisplayName="Meetings"
          Description=""
          IsFavoriteByDefault="false" />
        <pnp:Channel DisplayName="Program"
          Description=""
          IsFavoriteByDefault="false" />

        
        <pnp:Channel DisplayName="Commercial"
          Description=""
          IsFavoriteByDefault="false"
          Private="true" />
        <pnp:Channel DisplayName="Contract"
          Description=""
          IsFavoriteByDefault="false"
          Private="true" />
        <pnp:Channel DisplayName="Procurement"
          Description=""
          IsFavoriteByDefault="false"
          Private="true" />
        <pnp:Channel DisplayName="Evaluation"
          Description=""
          IsFavoriteByDefault="false"
          Private="true" />
      </pnp:Channels>

**Describe the solution you'd like**
Similarly, it would be great to automate the creation of Shared Channels in Teams.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by milanholemans** [comment]
Hi @McoreD 

The provisioning engine is not something that located in PnP.PowerShell. This engine is in the PnP Framework repo (https://github.com/pnp/pnpframework). I suggest that you create your issue over there. Once it is implemented, you'll be able to use this in PnP.PowerShell as well.

**Comment by McoreD** [comment]
Thanks @milanholemans,

I created the issue over there as advised. Much appreciated!

**Comment by McoreD** [comment]
FYI, this is the issue over there: https://github.com/pnp/PnP-Provisioning-Schema/issues/591
