### ISSUE TITLE
[BUG] Add-PnPTeamsTab using -ContentUrl parameter error

### ISSUE THREAD

**Issue by cdragosf** [pnp/powershell#225]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
Set the new tab in the specified Teams and Channel.

### Actual behavior 
Getting error: " Add-PnPTeamsTab: A parameter cannot be found that matches parameter name 'ContentUrl'. "
Same behavior on Windows PowerShell and Azure Functions V3 with PS7.0 runtime.
### Steps to reproduce behavior
![image](https://user-images.githubusercontent.com/19550972/107084592-8cb22400-67f7-11eb-9926-75b6c57cea5e.png)

### What is the version of the Cmdlet module you are running?

![image](https://user-images.githubusercontent.com/19550972/107084246-18778080-67f7-11eb-8471-117f168e40e2.png)

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [X] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
Hi @cdragosf - I tried with v1.2.15 and had no issue. Can you update and try again?

![image](https://user-images.githubusercontent.com/25181757/107126978-f9d2c180-68aa-11eb-84ef-f7d64a5b7964.png)

**Comment by cdragosf** [comment]
> Hi @cdragosf - I tried with v1.2.15 and had no issue. Can you update and try again?
> 
> ![image](https://user-images.githubusercontent.com/25181757/107126978-f9d2c180-68aa-11eb-84ef-f7d64a5b7964.png)

You are using -Type WebSite and i am using -Type SharePointPageAndList. That was my solution for this problem, using -Type WebSite, but it should work with the other type too.

Thanks for your answer.

**Comment by erwinvanhunen** [comment]
We do not provide the ContentUrl parameter when you specify the type as 'SharePointPageAndList' as tabs of this type cannot be 'preconfigured'. The ContentUrl is a 'dynamic' parameter and will only be valid for tabtypes that support it. 

You can add a tab of this type (without specifying the content url), but configuration has to happen afterwards by navigating to the tab. E.g. you cannot provide a link to to a SharePoint Page or List using this tab type. The alternative is, as Veronique mentioned, to create a tab of type Web.

See https://docs.microsoft.com/en-us/graph/teams-configuring-builtin-tabs#sharepoint-page-and-list-tabs for more information about what can be set for the different tab types.

**Comment by OAmezDroz** [comment]
The problem is that the Web type tab does not offer the same capabilities as the sharepoint tab.
For example not being able to open a pdf file or accessing the power automate flows.

**Comment by nikolasph** [comment]
Additionally the web type tab cannot render SharePoint Websites. 

This is not closed according or said differently should be a feature request to enable dynamic content for the SharePointPageAndList Type.
