### ISSUE TITLE
[BUG] Cannot assign SharingCapability with Set-PnPTenantSite to private Teams-Group

### ISSUE THREAD

**Issue by EA12** [pnp/powershell#2250]
### Reporting an Issue 

Cannot assign -SharingCapability ExistingExternalUserSharingOnly to existing teams as global admin via command Set-PnPTenantSite

### Expected behavior 
The SharingCapability should be assigned to the Teams-Group.

### Actual behavior 
CmdLet returns no information. If we validate, we see  SharingCapability = Disabled
`Get-PnPTenantSite -Identity https://xxx.sharepoint.com/sites/ITSCM | Select SharingCapability`

### Steps to reproduce behavior
Org settings for SharingCapability is set to ExistingExternalUserSharingOnly
Have a private Teams-Group with SharingCapability = Disabled
Connect to PnPOnline as global admin and be a owner of the teams group. 
`Connect-PnPOnline $AdminSiteURL`  

Assign the sharing
`Set-PnPTenantSite -Identity https://xxx.sharepoint.com/sites/ITSCM -SharingCapability ExistingExternalUserSharingOnly`
CmdLet returns no information.

Run `Get-PnPTenantSite -Identity https://xxx.sharepoint.com/sites/ITSCM | Select SharingCapability`
It is still showing Disabled

### What is the version of the Cmdlet module you are running?
1.11.0

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by EA12** [comment]
@veronicageek - Are you sure, you had the same conditions, as I have?

**Comment by Studermarc** [comment]
@EA12 this might be related to your tenant setting. Could you double check what is configured on the tenant level? Site collections cannot have a Sharing Setting of higher level than what's configured on the tenant level. If it's disabled there, this would explain why you are not able to change it on a given site collection.

**Comment by EA12** [comment]
@veronicageek @Studermarc ,

I double checked the settings:
You see that the settings from the tenant level is ExistingExternalUserSharingOnly.
When I set this setting to the teams site, there is no complaint, but if I get the setting again, i can see that it was not persisted.:

![image](https://user-images.githubusercontent.com/22025808/187856841-37b7ef3a-cd8a-4d04-8a45-cdec06e6e78f.png)

Could it be, that a assigned Label (Yellow) does not allow to change this setting?

**Comment by Studermarc** [comment]
@EA12 Yes, if not the tenant setting restricting you, it should be an applied policy through label. Those can restrict guest access as well. Are any applied to the site?

**Comment by EA12** [comment]
@Studermarc Yes, we just verified it and that was the case. My bad, Sorry.
