### ISSUE TITLE
Import-Csv fails if -Delimiter ";" used and CSV file contains a comma

### ISSUE THREAD

**Issue by jasmeeners** [pnp/powershell#2259]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

Import-Csv fails if -Delimiter ";" is used with a CSV file that contains a comma
even if columns are enclosed in single or double quotations

sample.csv

Title;Template;OnQuickLaunch
Audits;DocumentLibrary;Y
Budgeting, Corporate;DocumentLibrary;Y
"Budgeting, Corporate";DocumentLibrary;Y
'Budgeting, Corporate';DocumentLibrary;Y

$data = Import-Csv -Path "sample.csv" -Delimiter ':'
$data

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

Title                                              Template                  onQuickLaunch
--------------------                         -------------              ----------------
Audits                                            DocumentLibrary     Y
Budgeting, Corporate                    DocumentLibrary     Y
Budgeting, Corporate                    DocumentLibrary     Y
Budgeting, Corporate                    DocumentLibrary     Y

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

Title                                              Template                  onQuickLaunch
--------------------                         -------------              ----------------
Audits                                            DocumentLibrary     Y
Budgeting, Corporate;DocumentLibrary;Y
Budgeting, Corporate;DocumentLibrary;Y
Budgeting, Corporate;DocumentLibrary;Y

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

sample.csv

Title;Template;OnQuickLaunch
Audits;DocumentLibrary;Y
Budgeting, Corporate;DocumentLibrary;Y
"Budgeting, Corporate";DocumentLibrary;Y
'Budgeting, Corporate';DocumentLibrary;Y

$data = Import-Csv -Path "sample.csv" -Delimiter ':'
$data

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

ModuleType Version    Name                                ExportedCommands                                                                                                                                                           
---------- -------    ----                                ----------------                                                                                                                                                           
Manifest   1.11.0     PnP.PowerShell                      {Add-PnPAdaptiveScopeProperty, Add-PnPPropertyBagValue, Add-PnPSiteClassification, Copy-PnPFolder...}                                                                      
Manifest   1.10.0     PnP.PowerShell                      {Add-PnPAdaptiveScopeProperty, Add-PnPPropertyBagValue, Copy-PnPFolder, Export-PnPClientSidePage...}                                                                       
Manifest   1.5.0      PnP.PowerShell                      {Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add-PnPClientSideText, Add-PnPClientSideWebPart...}              

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by CallumCrowley** [comment]
@jasmeeners the [Import-Csv](https://docs.microsoft.com/powershell/module/microsoft.powershell.utility/import-csv?view=powershell-7.2) is not part of the PnP.PowerShell module and is actually part of the Microsoft.PowerShell.Utility module.

**Comment by jasmeeners** [comment]
thanks. 
I use it extensively with pnp.powershell to load data. is there a way to report it as a bug with that team? could you point me to their site?
much appreciated!

**Comment by CallumCrowley** [comment]
You could either create a question on [Microsoft Answers](https://answers.microsoft.com) or if you think there is a documentation error, you could log a bug against the [PowerShell documentation via GitHub](https://github.com/MicrosoftDocs/PowerShell-Docs).

**Comment by gautamdsheth** [comment]
Hi @jasmeeners , as @CallumCrowley mentioned, this command belongs to a different repository (check the above comment).
We will be closing the issue here and would request you to raise the question on Microsoft answers site or PowerShell docs (check above comment for links)
