### ISSUE TITLE
[FEATURE] - Invoke-PnPSiteTemplate - Errors should include some contextual info

### ISSUE THREAD

**Issue by jimmywim** [pnp/powershell#2261]
If a Site Template (PNP XML) fails to deploy, it often simply yields the error from the server.

**Describe the solution you'd like**
It would be great if the error output showed which Handler, and which element it was processing when an error was thrown. This would save time troubleshooting issues with templates

**Comment by BaronSparky** [comment]
Do you use `Set-PnPTraceLog -On -Level Debug` ?

This might give you some of the information you need.

**Comment by gautamdsheth** [comment]
@jimmywim - did you try the above suggestion by @BaronSparky ? It is the standard way to check errors in each handler

**Comment by gautamdsheth** [comment]
Closing this due to lack of response.
