### ISSUE TITLE
New-PnPMicrosoft365Group - securityEnabled 

### ISSUE THREAD

**Issue by fowl2** [pnp/powershell#2267]
I noticed that `New-PnPMicrosoft365Group` sets `securityEnabled` unconditionally to `false`. 

https://github.com/pnp/powershell/blob/7f50e43daf03a302490c71d642ecb0b9d879e5db/src/Commands/Microsoft365Groups/NewMicrosoft365Group.cs#L95

This seems in contradiction to the [docs](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http#request-body), which seem to indicate it should be `true`?

Property | Type | Description
-- | -- | --
securityEnabled | Boolean | Set to true for security-enabled groups, including Microsoft 365 groups. Required. Note: Groups created using the Microsoft Azure portal always have securityEnabled initially set to true.

site note: any objection to a PR adding `MailEnabled`, `SecurityEnabled`, `PreferredDataLocation`, `PreferredLanguage`, etc. as parameters?

**Comment by gautamdsheth** [comment]
Closing this , since you submitted a PR 😊

**Comment by fowl2** [comment]
Well the PR didn't change the behavior. :) 

So my question about if it's the correct default is unanswered. Maybe it's more a doc question?
