### ISSUE TITLE
[BUG] Inconsistent DenyAddAndCustomizePages and DenAndAddCustomizePages parameters

### ISSUE THREAD

**Issue by ToddKlindt** [pnp/powershell#227]
### Reporting an Issue or Missing Feature
Set-PnPSite  has a parameter -DenyAndAddCustomizePages ("And" then "Add")

### Expected behavior 
It should be "Add" then "And" per [Microsoft's documentation](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/dn174826(v=office.15)).

### Actual behavior 
The property name is wrong.

### Steps to reproduce behavior
Type "Set-PnPSite -D<tab>

### What is the version of the Cmdlet module you are running?
1.2.0 and 1.2.16

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
Fixed and merged. Thanks Gautam! It will be there tomorrow.
