### ISSUE TITLE
[FEATURE] - Adding `-DraftVersionVisibility` parameter to `Set-PnPList` cmdlet

### ISSUE THREAD

**Issue by jasmeeners** [pnp/powershell#2282]
**Is your feature request related to a problem? Please describe.**

Set-PnPList
there is no parameter to set the "DraftVersionVisibility"
to set this property you must use the sharepoint GUI
allowable values are:
Reader
Author
Approver

**Describe the solution you'd like**
Set-PnPList  -DraftVersionVisibility [Reader | Author | Approver] ...

**Describe alternatives you've considered**
Is there currently a way of solving your problem with existing cmdlets? Optionally through the use of other PowerShell Modules (for instance by using the Microsoft Graph cmdlets or the Microsoft SPO Management Shell)

I don't know of anyway to set this property with existing cmdlets

**Additional context**

**Comment by milanholemans** [comment]
Hi @jasmeeners 

Thank you for suggesting this enhancement. I made a PR to add this functionality to the cmdlet. I chose the name `DraftItemSecurity` since this name is also used in the UI. When a maintainer completes the PR, this option will be available in the nightly release the day after.

**Comment by jasmeeners** [comment]
That is awesome!!!! Thanks very much!

**Comment by jasmeeners** [comment]
Hi Milan;

I tried to install the latest nightly build using the instructions here:

https://www.powershellgallery.com/packages/PnP.PowerShell/1.11.59-nightly

Install-Module -Name PnP.PowerShell -AllowPrerelease

And I got an error

Install-Module : A parameter cannot be found that matches parameter name 'AllowPrerelease'

Could you tell me how to install the latest nightly build?

Thanks!

-steve

**Comment by jasmeeners** [comment]
Hi Milan;

I also tried this:
Install-Module -Name Pnp.PowerShell -RequiredVersion 1.11.59-nightly  -AllowPrerelease

And got this error:

Install-Module : Cannot process argument transformation on parameter 'RequiredVersion'. Cannot convert value "1.11.59-nightly" to type "System.Version". Error: "Input string was not in a correct format."


So not sure how to install the latest nightly build.

Could you let me know

Thanks

-steve

**Comment by milanholemans** [comment]
Hi @jasmeeners 

According to the documentation, the correct cmdlet is:
```powershell
Install-Module -Name PnP.PowerShell -AllowPrerelease -SkipPublisherCheck -AllowClobber
```

https://pnp.github.io/powershell

**Comment by milanholemans** [comment]
I think the easiest way is to first uninstall the alpha release, and then install the beta release. At least this works for me: 
```powershell
Uninstall-Module -Name PnP.PowerShell
Install-Module -Name PnP.PowerShell -AllowPrerelease -SkipPublisherCheck -AllowClobber
```

**Comment by jasmeeners** [comment]
Thanks for all your help.

For some reason I still get the error when I do that

***@***.***

**Comment by milanholemans** [comment]
Hi @jasmeeners 

Have you tried this solution?
https://www.easy365manager.com/install-module-a-parameter-cannot-be-found-that-matches-parameter-name-allowprerelease

**Comment by jasmeeners** [comment]
Hi Milan;

I ran the instructions from the CMD prompt as administrator and that seemed to work (not ISE)

But now I seem to have two versions of PNP.Powershell installed

Name           Version
----           -------
PnP.PowerShell 1.11.59
PnP.PowerShell 1.5.0

How do you know which one is being used? Or how do you switch between them?

Thanks for your patience

-steve

**Comment by milanholemans** [comment]
I'd uninstall the v1.5.0 to avoid conflicts.

```powershell
Uninstall-Module -Name PnP.PowerShell -RequiredVersion 1.5.0
```

Should do the trick.

**Comment by jasmeeners** [comment]
Thanks!

**Comment by jasmeeners** [comment]
Thanks Milan for the quick rely.

When I run that command I get:

Install-Module : A parameter cannot be found that matches parameter name 'AllowPrerelease'.

Am I doing something wrong??

Thanks

-steve

**Comment by jasmeeners** [comment]
I am using 5.1 does that matter??

Thanks

-steve

**Comment by milanholemans** [comment]
Can you try running

```powershell
Update-Module PowerShellGet -Force
```

first?
