### ISSUE TITLE
[BUG] Resolve-PnPFolder: The attempted operation is prohibited because it exceeds the list view threshold.

### ISSUE THREAD

**Issue by svermaak** [pnp/powershell#2286]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
Folders created

### Actual behavior 
![image](https://user-images.githubusercontent.com/12259728/187095979-fb230c83-5513-480d-80f6-cade9ced9ec4.png)

### Steps to reproduce behavior
$retainRootFolder = Resolve-PnPFolder -SiteRelativePath "Shared Documents/aaaaa" -Connection $retainLocationConnection
against a site with 5000+ items

### What is the version of the Cmdlet module you are running?
Latest

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [x] Azure Functions
- [ ] Other : please specify

**Comment by LeonArmston** [comment]
Ah I noticed this was happening at the end of last year! Was a PnP Framework issue - wonder if this bug has been re-introduced?
Here is the issue #1438 and @gautamdsheth  fixed it!

**Comment by veronicageek** [comment]
Please update to the latest release `2.1.x` where there have been multiple bug fixes and improvements, however you will need PS 7.2 or later as PS 5 is not supported anymore.

Feel free to reopen if the issue persists.

**Comment by Joe-Pel** [comment]
I have just upgraded to PowerShell 7.4 and PNP 2.2 and I am still getting the error. This is the code that gets the error
 Resolve-PnPFolder  "Shared Documents/2040000675" if it is there it has only a few files and no folders.

**Comment by svermaak** [comment]
This is still reproducible and I have submitted a fix in #5411.

Root cause: Resolve-PnPFolder delegates to PnP Framework's EnsureFolderPath, which checks every path segment by loading the entire Folders collection of the parent folder and iterating it. That collection load is a list query, so as soon as any folder in the path sits in a scope holding more than 5000 items, SharePoint rejects it with the list view threshold error.

The fix resolves the path with GetFolderByServerRelativePath (direct addressing, loading only Exists) and creates missing segments with Folders.AddUsingPath, so no folder or item collection is ever enumerated and the list view threshold no longer applies. As a bonus the common case of an already existing folder now takes a single round trip instead of one query per path segment.
