### ISSUE TITLE
Set-PnPTeamsChannel -IsavoriteByDefault $true is not working

### ISSUE THREAD

**Issue by JimmyHang** [pnp/powershell#229]
### Reporting an Issue
Hi All, 

I'm using the new (Set-PnPTeamsChannel -IsFavoriteByDefault $true), to mark old channel as Favorite, and it seems nothing happens. the channel status didn't get updated. 

### Expected behavior 
Expected the channel to be set as Favorite.

This works fine when I use "Add-PnPTeamsChannel -IsFavoriteByDefault $true)

### Actual behavior 
![image](https://user-images.githubusercontent.com/18226765/107196027-61dfef80-69f2-11eb-9d5d-e2de935e2601.png)

### Steps to reproduce behavior
Try the new: Set-PnPTeamsChannel -Team "MyTeam" -Channel "MyChannel" -IsFavoriteByDefault $true

### What is the version of the Cmdlet module you are running?
1.2.13 PnP.PowerShell
1.2.7 PnP.PowerShell

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows

**Comment by erwinvanhunen** [comment]
Thanks Gautam!
