### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by NPrice99** [pnp/powershell#2296]
### Reporting an Issue or Missing Feature
Error 400 when using Connect-PnPOnline (no parameters)

Add-PnPField return Error 400 Bad Request  -Add-PnPField -DisplayName <param> -InternalName <param> -Group <param> -Type <param> -List <param>

### Expected behavior 
Connect and Create the field

### Actual behavior 
Error 400 Bad Request  returned when typing in Add-PnPField -DisplayName <param> -InternalName <param> -Group <param> -Type <param> -List <param>

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

### What is the version of the Cmdlet module you are running?
 executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable``` returns nothing

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@NPrice99 - You might not write the `-Url` parameter explicitly but you'll still need the URL itself. I've tested the `Add-PnPField` cmdlet as well and there's no issue

**Comment by CallumCrowley** [comment]
Please provide steps to reproduce your issue e.g. your script may be providing invalid values which are being rejected by SharePoint but it's difficult to rule this out without further information.

**Comment by gautamdsheth** [comment]
Based on the twitter discussion we had , would suggest that you reinstall PnP PowerShell in PS 7 and uninstall the old version and try , looks like some DLL conflict issue.

**Comment by NPrice99** [comment]
I will try that

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
