### ISSUE TITLE
[BUG] - connect-pnponline with -accessToken and -url, doesn't create context(current connection holds no SharePoint context)

### ISSUE THREAD

**Issue by syedmdanish** [pnp/powershell#23]
### Reporting an Issue 
I am trying to run the command **Connect-PnPOnline -Url $siteUrl -AccessToken $accessToken** in Powershell and function App both with a valid access token but when I call any SharePoint pnp command after the connection I keep getting the Issue:  _The current connection holds no SharePoint context. Please use one of the Connect-PnPOnline commands which uses the -Url argument to connect._ 

### Expected behavior 
As the command Connect-PnPOnline is called with valid URl and accesstoken I should be able to call any Get-PnP* commands for the site successfully.

### Actual behavior 
Any sharepoint PnP commands for the site (Url used in the Connect-PnPOnline ) fails with the Issue _**The current connection holds no SharePoint context. Please use one of the Connect-PnPOnline commands which uses the -Url argument to connect.**_ 

### Steps to reproduce behavior
1. Getting the AccessToken in the function app using the code below :
        $ClientApplicationBuilder = [Microsoft.Identity.Client.PublicClientApplicationBuilder]::Create($clientId)
        [void]$ClientApplicationBuilder.WithAuthority($authority)
        [void]$ClientApplicationBuilder.WithRedirectUri($redirectUri)
        $appBuilder = $ClientApplicationBuilder.Build()

        [Microsoft.Identity.Client.AuthenticationResult] $authenticationResult  = $null
        $SecurePassword = $(ConvertTo-Securestring $Password -asplaintext -force)
        $AquireTokenParameters = $appBuilder.AcquireTokenByUsernamePassword($scopes, $username, $securePassword)
        $authenticationResult = $AquireTokenParameters.ExecuteAsync().GetAwaiter().GetResult()
        $accessToken = $authenticationResult.AccessToken

 2.Executing **Connect-PnPOnline -Url $siteUrl -AccessToken $accessToken** and then calling any Get-PnP* command for the site 
    like $site = Get-PnPSite -Includes RootWeb

### What is the version of the Cmdlet module you are running?
I have tried with versions 0.1.25, 0.1.30 and latest one 0.2.2 but getting the same Issue.
![Connect-PnPOnline_Issue](https://user-images.githubusercontent.com/63002267/98638025-50357000-234f-11eb-967c-7fcca40256ea.png)

**Comment by bigpix2000** [comment]
cc: @patrick-rodgers if you have any suggestions on who we can tag on this?  thanks!

**Comment by erwinvanhunen** [comment]
Hi, thank you for reporting this. We'll have a look in this specific case. We noticed that you're using MSAL to acquire an access token, which is the same we're using internally in PnP PowerShell. For that reason we made a small change that will allow you to authenticate like this:

```powershell
Connect-PnPOnline -Url https://yourtenant.sharepoint.com -Credentials (Get-Credential) -ClientId <yourclientid>
```

Nevertheless we will check out where it goes wrong with the -AccessToken parameter.

**Comment by erwinvanhunen** [comment]
We fixed this in the upcoming nightly build, version 0.2.17. Please install this version when available tomorrw and please try again. I will close this issue now but do not hesitate to create a new one if required.

**Comment by syedmdanish** [comment]
@erwinvanhunen - Thanks for looking into the Issue. It works fine now.

**Comment by riccardogalaxy76** [comment]
Hi @erwinvanhunen I don't know if this is the right place, but by googling I landed on this site. I am using SharePointPnPPowerShellOnline version 3.29.2101, and I log in with token. But when I try to run the Get-PnPSubWebs command I get the same error as @syedmdanish 
Could you help me ?
