### ISSUE TITLE
[BUG]  Copy-PnPList Destination URL doesn't work 

### ISSUE THREAD

**Issue by poneilcsgp** [pnp/powershell#2309]
### Reporting an Issue or Missing Feature
When attempting to use Copy-PnPList with -DestinationWebUrl parameter, the lists still get created in the Source list's web, instead of the destination.     I've run the command with -WhatIf and -Verbose and those logs show that it *should* create in the intended destination, but when I run without the -WhatIf it seems to ignore the -DestinationWebUrl parameter (and creates in the source web instead).

### Expected behavior 
I would expect that the list would be created in the web assocaited with the -DestinationWebUrl parameter.

### Actual behavior 
The new lists are created in the Source Web, DestinationWebUrl appears to be ignored.

### Steps to reproduce behavior
Copy-PnPList -Identity "MyList" -DestinationWebUrl  "https://mytenant.sharepoint.com/sites/sourceListSite" -Title "NewList"

### What is the version of the Cmdlet module you are running?
1.11.0

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by poneilcsgp** [comment]
FWIW, I'm wrapping the CopyList in a simple function that just logs info.  The Write-host command shows the correct $DestinationWebUrl.

function Add-ListFromExistingList{
    param(
        [Parameter(Mandatory=$true)] [string] $NewListName,
        [Parameter(Mandatory=$true)] $ListToCopy,
        [Parameter(Mandatory=$true)] $DestinationWebUrl
    )
    Write-Host "Creating list: $newListName from $($ListToCopy.Title) on $DestinationWebUrl"
    Copy-PnPList -Identity $listToCopy  -DestinationWebUrl $DestinationWebUrl -Title $newListName -Verbose 
}

![image](https://user-images.githubusercontent.com/104784418/187995003-ae80e909-ef98-4315-b9a7-44cb60f04431.png)

The error message is informing that the list already exists on the source site, no lists are ever created on the destination site.

**Comment by veronicageek** [comment]
@gautamdsheth @KoenZomers - I've tried different scenarios and there's definitely something weird with the `Copy-PnPList` cmdlet.

**Comment by gautamdsheth** [comment]
hi @poneilcsgp , @veronicageek ,  we identified the issue and managed to fix it.
Have merged the necessary code and it will be available from tomorrow's nightly as well as the next major release
