### ISSUE TITLE
[BUG] small bugs in documentation

### ISSUE THREAD

**Issue by Adam-it** [pnp/powershell#2316]
### Reporting an Issue or Missing Feature
I found small issues in couple of docs file. Nothing big 👍

### Expected behavior 
👉 in file https://github.com/pnp/powershell/blob/dev/documentation/Add-PnPPageWebPart.md we have wrongly formatted md (missing space) in title `#Add-PnPPageWebPart` should be `# Add-PnPPageWebPart`

👉 in file https://github.com/pnp/powershell/blob/dev/documentation/Get-PnPListItemComment.md the title is `Get-PnPListItem` should be `Get-PnPListItemComment`

👉 in file https://github.com/pnp/powershell/blob/dev/documentation/Set-PnPSiteScriptPackage.md the title is `Set-PnPSiteScript` should be `Set-PnPSiteScriptPackage`

### Actual behavior 
described above 👆

### Steps to reproduce behavior
... hmm.. enter the doc file and see I guess 😉

### What is the version of the Cmdlet module you are running?
latest 

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows

**Comment by Adam-it** [comment]
if that's fine with you I am more than glad to fix those and open a PR 🙂

**Comment by gautamdsheth** [comment]
hi @Adam-it , good catch ! Yes, please. Feel free to open a PR , thank you 😊

**Comment by Adam-it** [comment]
> hi @Adam-it , good catch ! Yes, please. Feel free to open a PR , thank you 😊

Great 🤩 
Will do 💪
Thanks 👍

**Comment by Adam-it** [comment]
also along the way I found that one doc file is missing .md format. I will fix it as well 
![image](https://user-images.githubusercontent.com/58668583/188425486-2899196f-ed2c-4f61-969b-4a7b32ece474.png)
