### ISSUE TITLE
Set-PnPSearchConfiguration: Internal Server Error importing search properties that were working recently

### ISSUE THREAD

**Issue by benjacernuda** [pnp/powershell#2323]
### Notice
Hi

I have executed the script to import search managed properties in the Search Schema. We have use the same file 2 weeks ago in different tenants and worked without any problems but now we are getting an Internal Server Error

This happens in all of our tenants.

There was an advisory in the Health Centre and we thought that the problem would be fixed when the service was restored (https://github.com/pnp/powershell/issues/2310) but that hasn't been the case. Is this still happening to you @gautamdsheth? The advisory is solved but we are still having the Internal Server Error

We are using PnP.PowerShell 1.11.0. With the same version the script worked some weeks ago.

We have tried this workaround but still having the error
https://github.com/pnp/powershell/issues/1328

Not sure if you have noticed this @wobba or you are aware of some recent changes in the Search schema

Many thanks for your help

### Expected behavior 
The script run without errors and at the end the search managed properties are created in the Search Schema

### Actual behavior 
![image](https://user-images.githubusercontent.com/13738880/188634134-6400f6a9-5440-4bba-aca8-17a610501b01.png)

### Steps to reproduce behavior
Execute et-PnPSearchConfiguration with a import file that was working before

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 1.11.0.

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by helderem** [comment]
We have the same problem in our tenant with the old SharePointPnPPowerShellOnline module we are still using.

**Comment by heinrich-ulbricht** [comment]
Since we are also having the same problem I got here. But the issue @wobba mentions ("SPFX Footer Extension does not work with fat footers") is not related to search. So now I'm confused. Is the API issue supposed to be fixed?

**Comment by wobba** [comment]
@heinrich-ulbricht I did you a favor and updated my link with the missing digit. Have a nice weekend 🙂

**Comment by heinrich-ulbricht** [comment]
@wobba I like the digit, thank you. :)
