### ISSUE TITLE
[BUG] New-PNPTeamsteam fails with AppID auth

### ISSUE THREAD

**Issue by ErikPoirrierSec** [pnp/powershell#2324]
### Reporting an Issue or Missing Feature
New-PNPTeamsteam trying to create a teams via PNP, utilizing connect-pnponline -AppID authentication fails

This is 100% reproducible:
1. connect-pnponline using AppID authentication
2. execute new-pnpteamsteam
3. experience error "unable to resolve user"

It is trying to create a team with the "-owner" and also the AppID account (initiator), since it cannot resolve the AppID as a Azure AD user it fails. 
When running this commandlet with 'connect-pnponline -interactive' it works fine because the user running the commandlet is a Azure Ad user, and can be resolved to add 2 owners to the team, -owner and the initiator.

Resolution: Do not try to add the AppID as a owner to the team creation process, which in that case would be the "initiator" 

Thanks

**Comment by Studermarc** [comment]
This behaviour is by design in my opinion. As you said, azure ad principals cannot be added as users. The -Owners parameters accepts a list of users, not a mix of users and app principals. 
Furthermore, when creating a Team Instance (or more broadly a Microsoft 365 Group) in an App Context, you must specify at least one user as the owner of the Team / M365 Group. This restriction is also Documented by Microsoft in the Microsoft Graph documentation.

**Comment by ErikPoirrierSec** [comment]
The behavior should match what creating a O365 group pnp commandelt does programmatically, it will only use the -owners to assign ownership of the request O365 group and not try to add the initiator's account along with it. This works for creating the O365 group and SPO creation process (ie does not insert the app azure ad principal as a co-owner).

**Comment by ErikPoirrierSec** [comment]
Updated the bug report, the wrinkle is its trying to force add the initiator as a co-owner to the Team, we don’t want that, and that does not happen for O365 group or SPO creation within the same commandlet.

Erik Poirrier – SharePoint Consultant SME
Email: ***@***.******@***.***>
Mobile: 651-802-3949
[Securian Financial]
Securian Financial Group, Inc.
securian.com

From: Marc Studer ***@***.***>
Sent: Thursday, September 8, 2022 4:38 PM
To: pnp/powershell ***@***.***>
Cc: Poirrier, Erik [C] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [pnp/powershell] [BUG] New-PNPTeamsteam fails with AppID auth (Issue #2324)

[External Content] This message is from an external source. Please exercise caution when opening attachments or links.
________________________________

This behaviour is by design in my opinion. As you said, azure ad principals cannot be added as users. The -Owners parameters accepts a list of users, not a mix of users and app principals.
Furthermore, when creating a Team Instance (or more broadly a Microsoft 365 Group) in an App Context, you must specify at least one user as the owner of the Team / M365 Group. This restriction is also Documented by Microsoft in the Microsoft Graph documentation.

**Comment by Studermarc** [comment]
I'll test it out when I got some free minutes tomorrow. Will get back to you if I see the same behaviour. I usually create a groupe and then promote it to a teams

**Comment by Studermarc** [comment]
I've tested the Cmdlet with App Permissions and cannot reproduce this issue. Only the Owner I specify gets added as owner to the Team, there are no "attempts" in adding the App Service Principal as an owner as well. 

I've alse taken a deeper look into the codebase: The "New-PnPTeamsTeam Cmdlet firstly creates a Group, then Promotes that Group to a Team. So nothing special here.

Could you share your Script? There must be a small issue somewhere.

**Comment by ErikPoirrierSec** [comment]
After re-testing it is working now, may have been a issue on our tenant. Thanks close bug!
