### ISSUE TITLE
[BUG]Change TimeZone with Invoke-PnpQuery has no effect

### ISSUE THREAD

**Issue by crasyI** [pnp/powershell#2329]
### Reporting an Issue or Missing Feature
Default TimeZone Change is impossible, not for the main site asswell for all other sub sites.
Same Code with Changing the LocaleId works !

### Expected behavior 
In that case of the sample Code:
old      TZ: 4
target TZ: 13
real     TZ: 13

### Actual behavior 
In that case of the sample Code:
old     TZ: 4
target TZ: 13
real    TZ: 4    _**<= the change dosent happen**_

### Steps to reproduce behavior
```
# set varas
$TenantName = 'yourTenant'
$SPOAdminSiteUrl = "https://$($TenantName)-admin.sharepoint.com"
$TimeZone  = 13  # == new TimeZone ID

# connect
$PNPCon = Connect-PnPOnline -Url "https://$($TenantName).sharepoint.com" -UseWebLogin -ForceAuthentication -ReturnConnection -WarningAction Ignore

# get a list of all timezones
$web = Get-PnPWeb -Includes RegionalSettings.TimeZones -Connection $PNPCon

# read as is / old DefaultTimeZone
$TimeZoneSetting = Invoke-PnPSPRestMethod -url "$($SPOAdminSiteUrl)/_api/SPOInternalUseOnly.TenantAdminSettings?`$select=TenantDefaultTimeZoneId" -Connection $PNPCon
$TimeZoneNOW = $web.RegionalSettings.TimeZones | Where {$_.ID -eq $TimeZoneSetting.TenantDefaultTimeZoneId.Value}

# get target / new TimeTone as TimeZone Object
$newTimeZone = $web.RegionalSettings.TimeZones | ?{ $_.ID -eq $TimeZone }

# set new TimeZone and LocalId
$web.RegionalSettings.TimeZone = $newTimeZone
$web.RegionalSettings.LocaleId = 1031
$web.Update()
Invoke-PnpQuery -Connection $PNPCon

# reread TimeZone Setting
$TimeZoneSetting = Invoke-PnPSPRestMethod -url "$($SPOAdminSiteUrl)/_api/SPOInternalUseOnly.TenantAdminSettings?`$select=TenantDefaultTimeZoneId" -Connection $PNPCon

# check output
Write-Host "old    TZ: $($TimeZoneNOW.id)"
Write-Host "target TZ: $($newTimeZone.id)"
Write-Host "reload TZ: $($TimeZoneSetting.TenantDefaultTimeZoneId.Value)"
```

### What is the version of the Cmdlet module you are running?
1.11.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

### Note:
We have MFA active and up to now i have no registred App, i have to activate my SP Admin Role each time, und also we hat a bunch of tenants.
If i would know how to set that Setting with Invoke-PnPSPRestMethod i would choose that but i dont get that how too :(
I tried do change the TimeZone also with "$web.RegionalSettings.TimeZone.SetId( $newTimeZone.Id )" and it dosent work also.

**Comment by Studermarc** [comment]
You should target the site collection where you actually changed the value (root site collection in this case), instead of the admin site collection.
This line looks wrong to me:

# reread TimeZone Setting
$TimeZoneSetting = Invoke-PnPSPRestMethod -url "$($SPOAdminSiteUrl)/_api/SPOInternalUseOnly.TenantAdminSettings?`$select=TenantDefaultTimeZoneId" -Connection $PNPCon

**Comment by Studermarc** [comment]
When you re-read the timezones setting for the site where you have changed it, you need to recall the web object to get the updated values. Can you please try calling get-pnpweb again?

**Comment by crasyI** [comment]
You mean like this ?
```
# set new TimeZone
$web.RegionalSettings.TimeZone = $newTimeZone
$web.RegionalSettings.LocaleId = 1031
$web.Update()
Invoke-PnpQuery -Connection $PNPCon

# reread TimeZone Setting
#$TimeZoneSetting = Invoke-PnPSPRestMethod -url "$($SPOAdminSiteUrl)/_api/SPOInternalUseOnly.TenantAdminSettings?`$select=TenantDefaultTimeZoneId" -Connection $PNPCon
$web = Get-PnPWeb -Includes RegionalSettings.TimeZones -Connection $PNPCon
$reloadedTimeZone = $web.RegionalSettings.TimeZone
```

Its funny, the Output is (in case, wana set from 4 to 13)
old    TZ: 4
target TZ: 13
reload TZ: 13

BUT ! if i look in the Site creation settings on the SP Admin Site, the TimeZone is still at 4.
And if i restart the Script, the Output is the same.

Also wenn i use the same Code with like a loop through all Sites of the tenant und call inside, eG:
```
foreach( $site in $SitesCollections )
{
    $sitePnpCon = Connect-PnPOnline -Url $site.url -UseWebLogin -ReturnConnection -WarningAction Ignore
    $subweb = Get-PnPSubWeb -IncludeRootWeb -Includes RegionalSettings,RegionalSettings.TimeZone,RegionalSettings.LocaleId -Connection $sitePnpCon
    
    #$subweb.RegionalSettings.TimeZone = $newTimeZone  <= produce an error:
    #     Exception setting "TimeZone": "The object is used in the context different from the one associated with the object."
    $subweb.RegionalSettings.TimeZone.SetId( $newTimeZone.Id )
    $subweb.RegionalSettings.LocaleId = $LocalId
    
    $subweb.Update()
    Invoke-PnpQuery -Connection $sitePnpCon -Verbose -Debug
}
```

It is the same behavior, LocalID changes take effect, TimeZone not.

**Comment by Studermarc** [comment]
You are assigning the TimeZone Object of another Context to the "subweb" Object -> This isn't allowed in CSOM.
You need to modify the current Object, or create a new one with the same Context instead.

If I understood your requirement correctly, you would like to change the default TimeZone on the Admin Site Collection so that new Site Collections have the correct TimeZone (this can easily be done through the UI ;) ). And then also modify all current existing Site Collections with the desired TimeZone ?

**Comment by Studermarc** [comment]
@crasyI 

You can use following Script to get started ;) it works like a charm for me. 

``` powershell
$AllSiteUrl = @(
    #A List of All Site Urls
)

$TimeZoneId = 13

ForEach($SiteUrl in $AllSiteUrls){

    #Connect to the Site Collection with PnP PowerShell (use the method you see fit, I'm using an AD App with Certificate)
    $ConnectionParameters = @{
        "ClientId"   = "" #Removed for obvious reasons
        "Thumbprint" = "" #Removed for obvious reasons
        "Tenant"     = $TenantDomain
        "Url"        = $SiteUrl
    }
    $SiteConnection = Connect-PnPOnline @ConnectionParameters -ReturnConnection

    #Get the Web
    $Web = Get-PnPWeb -Includes RegionalSettings.TimeZones -Connection $SiteConnection

    #Get the desired Timezone from the Current Web Object
    $Timezone  = $Web.RegionalSettings.TimeZones | Where-Object {$_.Id -eq $TimeZoneId}
    <#
        Use the following line to get an overview of all available TimeZones
        $Web.RegionalSettings.TimeZones | Format-Table

        or

        $Web.RegionalSettings.TimeZones | Out-Gridview
    #>

    #Set the desired Timezone
    $Web.RegionalSettings.TimeZone = $Timezone
    $Web.Update()
    Invoke-PnPQuery -Connection $SiteConnection

    #Read WebObject Again
    $Web = Get-PnPWeb -Includes RegionalSettings.TimeZones -Connection $SiteConnection

    If($Web.RegionalSettings.TimeZone.Id -eq 13){
        Write-Host "Timezone Updated for Site Collection:`t $SiteUrl" -ForegroundColor "Green"
    }Else{
        Write-Host "Failed to Update Timezone for Site Collection:`t $SiteUrl" -ForegroundColor "Yellow"
    }
}
```
If you want to Update on the Admin Site Collection through PowerShell as well, just include the Site Collection Url in the List

**Comment by crasyI** [comment]
> You are assigning the TimeZone Object of another Context to the "subweb" Object -> This isn't allowed in CSOM. You need to modify the current Object, or create a new one with the same Context instead.
> 
> If I understood your requirement correctly, you would like to change the default TimeZone on the Admin Site Collection so that new Site Collections have the correct TimeZone (**this can easily be done through the UI ;)** ). And then also modify all current existing Site Collections with the desired TimeZone ?

That the UI dosen't work wasn't my Bug Report ;)
Yes, I could use it, and yes I did, but Bug is Bug.
And easily is realtive, if you have a bunch of tenants.

**Comment by crasyI** [comment]
> @crasyI
> 
> You can use following Script to get started ;) it works like a charm for me.
> 
> ```powershell
> $AllSiteUrl = @(
>     #A List of All Site Urls
> )
> 
> $TimeZoneId = 13
> 
> ForEach($SiteUrl in $AllSiteUrls){
> 
>     #Connect to the Site Collection with PnP PowerShell (use the method you see fit, I'm using an AD App with Certificate)
>     $ConnectionParameters = @{
>         "ClientId"   = "" #Removed for obvious reasons
>         "Thumbprint" = "" #Removed for obvious reasons
>         "Tenant"     = $TenantDomain
>         "Url"        = $SiteUrl
>     }
>     $SiteConnection = Connect-PnPOnline @ConnectionParameters -ReturnConnection
> 
>     #Get the Web
>     $Web = Get-PnPWeb -Includes RegionalSettings.TimeZones -Connection $SiteConnection
> 
>     #Get the desired Timezone from the Current Web Object
>     $Timezone  = $Web.RegionalSettings.TimeZones | Where-Object {$_.Id -eq $TimeZoneId}
>     <#
>         Use the following line to get an overview of all available TimeZones
>         $Web.RegionalSettings.TimeZones | Format-Table
> 
>         or
> 
>         $Web.RegionalSettings.TimeZones | Out-Gridview
>     #>
> 
>     #Set the desired Timezone
>     $Web.RegionalSettings.TimeZone = $Timezone
>     $Web.Update()
>     Invoke-PnPQuery -Connection $SiteConnection
> 
>     #Read WebObject Again
>     $Web = Get-PnPWeb -Includes RegionalSettings.TimeZones -Connection $SiteConnection
> 
>     If($Web.RegionalSettings.TimeZone.Id -eq 13){
>         Write-Host "Timezone Updated for Site Collection:`t $SiteUrl" -ForegroundColor "Green"
>     }Else{
>         Write-Host "Failed to Update Timezone for Site Collection:`t $SiteUrl" -ForegroundColor "Yellow"
>     }
> }
> ```
> 
> If you want to Update on the Admin Site Collection through PowerShell as well, just include the Site Collection Url in the List

Oh damn, i just use an Object and dindnt thought there is any reference like that.
I will try, and give feedback ...

**Comment by crasyI** [comment]
@Studermarc 

Hi, sorry for my late comment, but i had got some error like "403 forbidden" (because of insufficent rights), and some other ones because i used the objects wrong ...
But i could use your example, to a for me good solution and now it dose work as i expected.

My mistake was, to get the timezone object once and use it in the loop for all sites.

A little Hint:
in your example, is an error (it should be "RegionalSettings.TimeZone" not "RegionalSettings.TimeZones") =>
```
    #Read WebObject Again
    $Web = Get-PnPWeb -Includes RegionalSettings.TimeZone**s** -Connection $SiteConnection
```
here you load the wrong attribut, so will the check
```
If($Web.RegionalSettings.TimeZone.Id -eq 13){
```
not realy compare the correct values ;)


Many Thanks for your support and  your time :) 👍

**Comment by Studermarc** [comment]
Thanks for the Hints ;) I've edited the Script accordingly, except for that part:

``` powershell
If($Web.RegionalSettings.TimeZone.Id -eq 13){
....
}
```

The "TimeZone" Object contains the current set Timezone, whereas the "TimeZone**s**" Object, contains a list of all the available TimeZones

In this comparison, we actually want to check if the set TimeZone is equal to the TimeZone Id specified at the begining of the script.
