### ISSUE TITLE
[BUG] Connect-PnPOnline - User tried to log in to a device from a platform (Unknown) that's not supported

### ISSUE THREAD

**Issue by arjenbloemsma** [pnp/powershell#234]
### Reporting an Issue or Missing Feature
When using Connect-PnPOnline in Azure Functions or in the Cloud Shell a message is shown stating that this is not a supported environment.

### Expected behavior 
I expect to be able to use Connect-PnPOnline in Azure Functions or in the Cloud Shell

### Actual behavior 
When running the cmdlet in an Azure Function or the CloudShell I see this message:

`
Connect-PnPOnline: AADSTS50005: User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Accesspolicy. Supported device platforms are: iOS, Android, Mac, and Windows flavors.
`

<img width="1418" alt="Screenshot 2021-02-08 at 17 38 56" src="https://user-images.githubusercontent.com/8061052/107251809-097e1180-6a35-11eb-9654-62e0e299cb71.png">

### Steps to reproduce behavior
- Go to the Azure Portal
- Open a Cloud Shell 
- Install PnP Module via `Install-Module -Name PnP.PowerShell`
- Try to connect to a SharePoint Online site

### What is the version of the Cmdlet module you are running?
1.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [x] Azure Cloud Shell
- [x] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
Hi Arjen,

This is unfortunately nothing we can fix for you. Your tenant has been configured to not allow connections other than the listed platforms it seems:

https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices

**Comment by arjenbloemsma** [comment]
Hi Erwin,

Thanks for clarifying that, in that case I will contact the security admin of our tenant.

Kind regards,

Arjen
