### ISSUE TITLE
[BUG] New-PnPMicrosoft365Group creating mail as @{domain}.onmicrosoft.com

### ISSUE THREAD

**Issue by ProductivityCollaboration** [pnp/powershell#2343]
### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

New-PnPMicrosoft365Group is creating the primary (and only) mail property of a new Office 365 group as GroupName@{domain}.onmicrosoft.com.

New-UnifiedGroup had a parmeter called "EmailAddresses" so you could set the mail of a group to GroupName@domain.com

New-PnPMicrosoft365Group is missing a feature to allow users to set the SMTP email address of a newly created Microsoft Office 365 group

No other cmdlet in PnP module lets you modify this property.
 
### Expected behavior 
The mail property to be GroupName@domain.com

### Actual behavior 
The mail property is coming out as GroupName@domain.onmicrosoft.com

### Steps to reproduce behavior

1. Run the following, replace the variables with names relevent to your tenant
`New-PnPMicrosoft365Group -DisplayName $displayName -Description $description -MailNickname $nickname`
2. Go to the admin centre, find the newly created group and view the general information.
3. Under mail it will show the primary email address as GroupName@{domain}.onmicrosoft.com

### What is the version of the Cmdlet module you are running?
1.10.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

<img width="413" alt="pnpsite" src="https://user-images.githubusercontent.com/50707752/189937368-99e4ecdb-bb84-4573-9d99-f175535fd587.png">

**Comment by CallumCrowley** [comment]
@ProductivityCollaboration seems like the groups endpoint (Microsoft Graph API) endpoint which this cmdlet uses, doesn't have an option to explicitly state the SMTP address you would like for the M365 group:

[Create group](https://docs.microsoft.com/graph/api/group-post-groups?view=graph-rest-1.0&tabs=go#request-body)

This actually mirrors the experience in the UI, where it seems to default to the onmicrosoft.com address when creating a Microsoft 365 group from the Office admin UI or the Azure AD portal:

![image](https://user-images.githubusercontent.com/58050310/190126884-41130a86-12ae-43b2-8c06-42eb30028897.png)

![image](https://user-images.githubusercontent.com/58050310/190127224-399ca437-d0ee-41ad-9540-f89392e3a4d3.png)

Microsoft's advice is to use the Exchange Online PowerShell library:

[Choose the domain to use when creating Microsoft 365 groups](https://docs.microsoft.com/microsoft-365/solutions/choose-domain-to-create-groups?view=o365-worldwide)

**Comment by ProductivityCollaboration** [comment]
Hi Callum. Thanks for the reply. Looking closer you are correct, it is just doing what it is programmed to do. 

It seems the best way to get around this (in my instance) would be to set the default domain by creating an EAP. It is a shame there is no way to get to the mail property of the Group with PnP. Thanks
