### ISSUE TITLE
[BUG] New-PnPMicrosoft365Group Throws Error in PreRelease 1.11.74

### ISSUE THREAD

**Issue by Studermarc** [pnp/powershell#2346]
### Reporting an Issue or Missing Feature
New-PnPMicrosoft365Group Cmdlet fails in the new PreRelease with -ErrorAction = "Stop"

### Expected behavior 
A new Microsoft 365 Group is created

### Actual behavior 
An Error is thrown

Looking at the codebase, the Error gets thrown when it first checks, if a Microsoft 365 Group with the same alias exists (because none is found, which is to be excepted):
- when executing this line: https://github.com/pnp/powershell/blob/5dad6d2da09db89a8bca2d292f35ebb4bdd9f248/src/Commands/Microsoft365Groups/NewMicrosoft365Group.cs#L86
- which executes this method: https://github.com/pnp/powershell/blob/5dad6d2da09db89a8bca2d292f35ebb4bdd9f248/src/Commands/Utilities/Microsoft365GroupsUtility.cs#L118

I believe the error thrown when no teams is found should be suppressed, as we actually check for its non-existance, and not the oposite:
https://github.com/pnp/powershell/blob/5dad6d2da09db89a8bca2d292f35ebb4bdd9f248/src/Commands/Microsoft365Groups/NewMicrosoft365Group.cs#L86

The Error is thrown due to the changes made to the Error Handling Behaviour: https://github.com/pnp/powershell/pull/2288#issue-1353993680

### Steps to reproduce behavior
1. Run the following Code
``` powershell
New-PnPMicrosoft365Group -DisplayName "TestNewGroup" -Description "TestNewGroup" -MailNickname "TestNewGroup" -Connection $AdminConnection
```
2. Observe the Error:
``` powershell
New-PnPMicrosoft365Group: No Microsoft 365 group found with id, display name or mail nickname 'TestNewGroup'
```

### What is the version of the Cmdlet module you are running?
1.11.74

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Hi @Studermarc , good catch.
Have managed to fix it. The fix will be available in tomorrow's nightly.

Please let me know if the issue still persists.

**Comment by Studermarc** [comment]
Awesome many thanks 👍
