### ISSUE TITLE
[FEATURE] Set template for SharePoint Alerts Daily Digest when using Add-PnPAlert

### ISSUE THREAD

**Issue by bijns** [pnp/powershell#2355]
**Is your feature request related to a problem? Please describe.**
Add-PnPAlert -Title "Daily overview" -List "Shared Documents" -User "i:0#.f|membership|$($ensureuser.UserPrincipalName)" -Frequency Daily -ChangeType All -Time (Get-Date -Hour 11 -Minute 00 -Second 00).ToUniversalTime()

Results in broken links for every single document that has a space in it's path. Both filename and libraryname will cause this issue.

**Describe the solution you'd like**
I would like an extra parameter for Add-PnPAlert to set the email template to use.

**Describe alternatives you've considered**
The only alternative I have found that works is using CSOM: 

```
$Alert = New-Object Microsoft.SharePoint.Client.AlertCreationInformation
$Alert.List = $List
$Alert.User = $User	
$Alert.Title = "Daily overview"
$Alert.AlertFrequency = [Microsoft.SharePoint.Client.AlertFrequency]::Daily
$Alert.AlertType = [Microsoft.SharePoint.Client.AlertType]::List
$Alert.DeliveryChannels = [Microsoft.SharePoint.Client.AlertDeliveryChannel]::Email
$Alert.Status = [Microsoft.SharePoint.Client.AlertStatus]::On
$Alert.EventType = [Microsoft.SharePoint.Client.AlertEventType]::All
$Alert.Filter = "0"
$Alert.AlertTime = (Get-Date -Hour 11 -Minute 00 -Second 00).ToUniversalTime()
$Alert.AlertTemplateName = "SPAlertTemplateType.DocumentLibrary"
$AlertGuid = $User.Alerts.Add($Alert)
$User.Update()
$Ctx.ExecuteQuery()
```

However, I can't use CSOM on Azure when using an app-only scenario.

**Comment by gautamdsheth** [comment]
hi @bijns , thanks for the feature request.

Have merged code so that you can specify AlertTemplate name as well.
It will be available in tomorrow's nightly as well as the next major release whenever it happens
