### ISSUE TITLE
[FEATURE] Add-PnPAzureADGroupMember - unable to add a security group as security group members

### ISSUE THREAD

**Issue by ThomasContini** [pnp/powershell#2359]
### Reporting an Issue or Missing Feature
- [x] Issue on `Add-PnPAzureADGroupMember` cmdlet

### Expected behavior
Having two security groups
- "security group",  UPN: 8058e142-de48-4526-a14e-6bd99ea169af
- "nested security group", UPN: 7133f330-0102-4a08-8a87-262176ecc900

When using:
```ps
Add-PnPAzureADGroupMember -Identity "8058e142-de48-4526-a14e-6bd99ea169af" -Users "7133f330-0102-4a08-8a87-262176ecc900"
```
It should add "nested security group" as member of the main group called "security group" (Maybe it's not a Feature yet?).

### Actual behavior
The group "nested security group" **is not added** as a "security group" member.

Currently the cmdlet seems not working for adding security groups as AD group members (Works fine when trying to add users).
Nothing is prompted after calling it, no errors (I double checked by using `Get-PnPException`).

### Steps to reproduce behavior
- Create two security groups in AAD
- get their objectId and try to add one as member of the other one with `Add-PnPAzureADGroupMember`
- Nothing happens

### What is the version of the Cmdlet module you are running?
1.11.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [x] Azure Functions

**Comment by ThomasContini** [comment]
Hello guys,
Do you have any updates about a possible ETA for this feature?

**Comment by gautamdsheth** [comment]
Have added a PR which fixes this. It will be available in tomorrow's nightly build as well as the next major version whenever we release it.

Thanks for raising this feature request.
