### ISSUE TITLE
[BUG] Set-PnPTenant parameter doesn't match -Force

### ISSUE THREAD

**Issue by LastElf** [pnp/powershell#2366]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
Set-PnPTenant -Force should run without a confirmation

### Actual behavior 
```Set-PnPTenant : A parameter cannot be found that matches parameter name 'Force'.```

Running without -Force does work. Have tested on another workstation same module version, same issue. I have also confirmed that -Force is available as a param in SetTenant.cs for 1.11.0 as per #1668 

### Steps to reproduce behavior
```Set-PnPTenant -OrphanedPersonalSitesRetentionPeriod 3650 -Force```

### What is the version of the Cmdlet module you are running?
1.11.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by IzzyBizzy45** [comment]
Confirmed issue with the nightly release as well
![image](https://user-images.githubusercontent.com/28319523/191432680-9b83ddab-3b53-4d87-b63d-e09396b3c2f0.png)

Am using PowerShell V7

**Comment by gautamdsheth** [comment]
hi @LastElf , thanks for raising this issue. It has now been fixed and will be available in tomorrow's nightly release as well as the next major version whenever that releases.
