### ISSUE TITLE
Sharepoint Powershell Authentication issue with Azure USGov Tenant

### ISSUE THREAD

**Issue by Brijeshoo7** [pnp/powershell#2391]
Register-PnPManagementShellAccess -AzureEnvironment USGovernment 

Not showing any pop up window for authentication in powershell. 

![image](https://user-images.githubusercontent.com/88958817/192960021-55910496-128f-4278-a70e-c5f541a7d563.png)

It stuck with running script status always.

**Comment by gautamdsheth** [comment]
Closing it as it is a duplicate of : https://github.com/pnp/powershell/issues/1180
