### ISSUE TITLE
Add-PnPTeamsChannel with parameter -ChannelType Shared do not work

### ISSUE THREAD

**Issue by HanzeUniversity** [pnp/powershell#2412]
Hi, 

I run with the latest version of PnP. I test the Add-PnPTeamsChannel command on different Windows machines, but on all workstations/servers I receive the message: 
Add-PnPTeamsChannel : A parameter cannot be found that matches parameter name 'ChannelType'.

I follow exact your artikel on: https://pnp.github.io/powershell/cmdlets/Add-PnPTeamsChannel.html
SYNTAX: 
Add-PnPTeamsChannel -Team <TeamsTeamPipeBind> -DisplayName <String> -ChannelType Shared -OwnerUPN <String> [-Description <String>] [-IsFavoriteByDefault <Boolean>]

**See my steps below:**

PS C:\WINDOWS\system32> Get-InstalledModule -Name "PnP.PowerShell"

Version    Name                                Repository           Description                                                                                                                                                                                                
1.11.0     PnP.PowerShell                      PSGallery            Microsoft 365 Patterns and Practices PowerShell Cmdlets                                                             

PS C:\WINDOWS\system32> Add-PnPTeamsChannel -Team "TestPnPTeam01" -DisplayName "Shared Channel 01" -ChannelType Shared -OwnerUPN "xxxx@xxxx.nl"

Add-PnPTeamsChannel : A parameter cannot be found that matches parameter name 'ChannelType'.
At line:1 char:81
+ ... TestPnPTeam01" -DisplayName "Shared Channel 01" -ChannelType Shared  ...
+
    + CategoryInfo          : InvalidArgument: (:) [Add-PnPTeamsChannel], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,PnP.PowerShell.Commands.Graph.AddTeamsChannel
 

PS C:\WINDOWS\system32>

**Comment by gautamdsheth** [comment]
hi @HanzeUniversity , this is available in the latest nightly builds. It will be available as part of 1.12.0 release as well, but for now to use it you need to install nightly version

You need to install it this way:

`Install-Module PnP.PowerShell -AllowPrerelease`

**Comment by HanzeUniversity** [comment]
@gautamdsheth 
Thank you for your solution. I try also the nightly build to install, but I receive this error message:
C:\WINDOWS\system32> Install-Module PnP.PowerShell -AllowPrerelease
Install-Module : A parameter cannot be found that matches parameter name 'AllowPrerelease'.
At line:1 char:31

**Comment by gautamdsheth** [comment]
You can check this link:

https://www.easy365manager.com/install-module-a-parameter-cannot-be-found-that-matches-parameter-name-allowprerelease/

**Comment by HanzeUniversity** [comment]
@gautamdsheth Thanks for the info.
I run the command Install-Module -Name PnP.PowerShell -AllowPrerelease -SkipPublisherCheck -AllowClobber -Force and have now the latest nightly version. But after I run the command Add-PnPTeamsChannel I receive the message: UnknownError

PS C:\WINDOWS\system32> Get-InstalledModule -Name "PnP.PowerShell"

Version              Name                                Repository           Description                                                                                                                                                                                       
1.11.92-nightly      PnP.PowerShell                      PSGallery            Microsoft 365 Patterns and Practices PowerShell Cmdlets                                                   

PS C:\WINDOWS\system32> Add-PnPTeamsChannel -Team d097fbc5-7146-4cd4-99fa-3e9fdaf7ae57 -DisplayName "Shared Channel 01" -ChannelType Shared -OwnerUPN xxxx@xxxx.nl"
Add-PnPTeamsChannel : UnknownError
At line:1 char:1
+ Add-PnPTeamsChannel -Team d097fbc5-7146-4cd4-99fa-3e9fdaf7ae57 -Displ ...
    + CategoryInfo          : InvalidOperation: (:) [Add-PnPTeamsChannel], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.Graph.AddTeamsChannel
