### ISSUE TITLE
`Set-PnPSite` : Parameter set cannot be resolved using the specified named parameters

### ISSUE THREAD

**Issue by schetti92** [pnp/powershell#2413]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Error received when trying to set site SensitivityLabel

### Expected behavior 
Site sensitivitylabele set to specified Label.

### Actual behavior 
Set-PnPSite : Parameter set cannot be resolved using the specified named parameters.
At line:21 char:1
+ Set-PnPSite -SensitivityLabel "b36be018-97e3-4ef7-91d1-726309951abc"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-PnPSite], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,PnP.PowerShell.Commands.Site.SetSite

Parameter set cannot be resolved using the specified named parameters

### Steps to reproduce behavior
Set-PnPSite -SensitivityLabel "b36be018-97e3-4ef7-91d1-726309951abc"

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
 1.11.0

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
hi @schetti92 , can you please try with the latest nightly builds and let us know ? Unable to reproduce this.

**Comment by gautamdsheth** [comment]
Closing this due to lack of response.
As mentioned, please use the latest nightly build using `Install-module PnP.PowerShell -AllowPrerelease` command and then try it.
