### ISSUE TITLE
[BUG] Sync-PnPSharePointUserProfilesFromAzureActiveDirectory fails with custom Azure AD property

### ISSUE THREAD

**Issue by JMTeamway** [pnp/powershell#2435]
### Reporting an Issue or Missing Feature
I am executing the following command to sync one custom property from Azure AD profile to Sharepoint profile :
`Sync-PnPSharePointUserProfilesFromAzureActiveDirectory -UserProfilePropertyMapping @{"Mut-IpPhone"="extension_6a0e2ef7f60e4959a5b417230e8a1875_ipPhone"} -Folder "Documents partages/SynchroSpAzureAd"  -Users $users -Wait -Verbose`

The command fails.

### Expected behavior 
The json configuration file is generated and the sync job is launched

### Actual behavior 
This command fails with the following message :
`COMMENTAIRES : Using provided user collection containing 1 user
COMMENTAIRES : Creating mapping file, uploading it to SharePoint Online to folder 'Documents partages/SynchroSpAzureAd' and executing sync job
Sync-PnPSharePointUserProfilesFromAzureActiveDirectory : Failed to create sync job. Ensure you're providing users to sync and that the mapping is correct.
Au caractère Ligne:1 : 1
+ Sync-PnPSharePointUserProfilesFromAzureActiveDirectory -UserProfilePr ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Sync-PnPSharePo...ActiveDirectory], PSInvalidOperationException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.UserProfiles.SyncSharePointUserProfilesFromAzureActiveDirectory
`

### My investigations
The connection and rights are OK.
The **Mut-IpPhone** Sharepoint field exists
The same command with **DisplayName** Azure AD Field as source works perfectly
The **extension_6a0e2ef7f60e4959a5b417230e8a1875_ipPhone** AzureAd field exists and was retrieved using the following command :
`Get-AzureADUser -ObjectId a[...]@[...].fr| select -ExpandProperty ExtensionProperty`

An exception is thrown by the command at this point : https://github.com/pnp/powershell/blob/10d6ba6e5ae07c4ac6dd796d80eff7124f173619/src/Commands/UserProfiles/SyncSharePointUserProfilesFromAzureActiveDirectory.cs#L99

The error happens in the **SyncFromAzureActiveDirectory** function of the **SharePointUserProfileSync** class.
I am sure I go beyond this point : https://github.com/pnp/powershell/blob/e816dc17e4f9da8b5752281b55a9e155db2ecec8/src/Commands/Utilities/SharePointUserProfileSync.cs#L42

I suspect this command to retrieve a null value, but I am not able to debug this code : https://github.com/pnp/powershell/blob/e816dc17e4f9da8b5752281b55a9e155db2ecec8/src/Commands/Utilities/SharePointUserProfileSync.cs#L53

### Steps to reproduce behavior
Create a custom field in Azure AD user profile
Create a custom field in Sharepoint user profile
Launch the command with appropriate parameters to sync those 2 fields

### What is the version of the Cmdlet module you are running?
1.11.0

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@JMTeamway - Can you please update to the latest release 2.1.x however you will need **PS 7.2 or later** to benefit from all the bug fixes and improvements, and let us know.

PS5 support has been dropped in the new release.

**Comment by veronicageek** [comment]
Closing as no response.

**Comment by TheNorth514** [comment]
Hi,

I got the same problem even after upgrading to PnP PS 2.1.1 and PS 7.3.4.
I enabled the trace but it's empty without anything.

Could you please investigate ?

Thank you
