### ISSUE TITLE
[FEATURE] Enhance the Set-PnPContentType commandlet to be able to set Form Customizer properties 

### ISSUE THREAD

**Issue by martinlingstuyl** [pnp/powershell#2451]
**Describe the solution you'd like**
I'd like to be able to use Set-PnPContentType to configure SPFx form customizers

we could add extra options for all the things that you need:
- DisplayFormClientSideComponentId
- DisplayFormClientSideComponentProperties
- NewFormClientSideComponentId
- NewFormClientSideComponentProperties
- EditFormClientSideComponentId
- EditFormClientSideComponentProperties

Maybe we could add an additional set of convenience options as well, to update ALL the values in one go:
- FormClientSideComponentId
- FormClientSideComponentProperties

**Describe alternatives you've considered**
Of course, we can use CSOM to do it. But using Set-PnpContentType is quicker.

**Example**

Connect the default item content type to a form customizer:

```powershell
Set-PnPContentType -Identity 0x01 -NewFormClientSideComponentId "eeaf0028-726a-4c85-a931-13cfb83b0b8f" -EditFormClientSideComponentId "eeaf0028-726a-4c85-a931-13cfb83b0b8f" -DisplayFormClientSideComponentId "eeaf0028-726a-4c85-a931-13cfb83b0b8f"
```

Connect the default item content type to a form customizer with properties:

```powershell
Set-PnPContentType -Identity 0x01 -NewFormClientSideComponentId "eeaf0028-726a-4c85-a931-13cfb83b0b8f" -EditFormClientSideComponentId "eeaf0028-726a-4c85-a931-13cfb83b0b8f" -DisplayFormClientSideComponentId "eeaf0028-726a-4c85-a931-13cfb83b0b8f" -NewFormClientSideComponentProperties '{ "someProp": "Some value"}' -DisplayFormClientSideComponentProperties '{ "someProp": "Some value"}' -EditFormClientSideComponentProperties '{ "someProp": "Some value"}'
```

**Comment by martinlingstuyl** [comment]
If you like the idea you can assign me if you want. 🤙

**Comment by gautamdsheth** [comment]
All yours @martinlingstuyl 😊🙏
