### ISSUE TITLE
[FEATURE] Allow Set-PnPSite and Set-PnPTenantSite to Enable Members to Share

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#2471]
**Is your feature request related to a problem? Please describe.**

It would not let me specify any value, either `True` or `False` when running ``Set-PnPSite -DisableSharingForNonOwners``. However the command completes correctly, when specifying `DisableSharingForNonOwners`

![image](https://user-images.githubusercontent.com/5260172/196019026-aa73e7ed-33e5-459a-9606-4ffad2965322.png)

The following construct will also give errors:
```
Connect-PnPSite -Url $Url
$site = Get-PnPSite -Includes RootWeb
$ctx = Get-PnPContext
$ctx.Load($ctx.RootWeb.MembersCanShare)
```
![image](https://user-images.githubusercontent.com/5260172/196018922-3127b23b-6426-4457-a0e7-7828906eaea7.png)

`Set-PnPTenantSite` does not seem to accept any parameters for `DisableSharingForNonOwners`

![image](https://user-images.githubusercontent.com/5260172/196019071-5e811846-4c9c-4233-b75f-f97432936505.png)

When changing these settings using a browser ( Gear Icon > Site Permissions > Change how members can share) it allows three different options:

![image](https://user-images.githubusercontent.com/5260172/196019150-c50d382f-0bd9-40ea-8b0a-0dbbe766f093.png)

**Describe the solution you'd like**

Ideally, I would like to be able to be able to get the same options as we get on the web:

- Site and items is enabled both for owners and users with edit permissions
- Site owners can share everything, and members with edit permissions can share files and folders
- Sharing is allows for site owners only

**Describe alternatives you've considered**

Seems like the web is the only option as of October 2022

**Comment by gautamdsheth** [comment]
Hi @YuriySamorodov, it is a switch parameter, so you can set values as `Set-PnPSite -DisableSharingForNonOwners:$false` or `Set-PnPSite -DisableSharingForNonOwners:$true`

It is available for `Web` object, so you can try it as:

```
$web= get-pnpweb -Includes MembersCanShare
$web.MembersCanShare = $true // $false
$web.Update()
Invoke-pnpquery
```
