### ISSUE TITLE
[FEATURE] Complete examples for Add-PNPTeamsTab

### ISSUE THREAD

**Issue by glasserre** [pnp/powershell#2476]
Hello.
In documentation of [Add-PNPTeamsTab](https://pnp.github.io/powershell/cmdlets/Add-PnPTeamsTab.html), only 2 examples are displayed.

An example for each type will be welcome and appreciate in order to avoid confusions.

Regards.

**Comment by gautamdsheth** [comment]
Closing this now. 
Starting tomorrow, we have added a total of 5 examples of using different types of Teams Tab.
