### ISSUE TITLE
Unable to Get Site Description when calling Get-PnPTenantSite

### ISSUE THREAD

**Issue by hsamdani12** [pnp/powershell#2494]
### Reporting an Issue or Missing Feature
When calling Get-PnPTenantSite for all the sites in the tenant, am unable to retrieve the Description.
I'm able to get the URL and Title.
I've tried the option with Select -Property * as well as -Detailed

### Expected behavior 
It should provide the Site Description detail when running Get-PnPTenantSite

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

### Steps to reproduce behavior

#$siteCollections = Get-PnPTenantSite | Select -Property *
$siteCollections = Get-PnPTenantSite -Detailed | Select URL,Title, Description

### What is the version of the Cmdlet module you are running?
1.11

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows

**Comment by veronicageek** [comment]
@hsamdani12 - Unfortunately this is a limitation of the API, and you'd need to specify the `-Identity` to get the value.
Closing as we can't do anything.
