### ISSUE TITLE
Documentation: Remove-PnPAzureADAppSitePermission

### ISSUE THREAD

**Issue by joetechin** [pnp/powershell#2500]
Hi,

When searching for cmdlets, the following cmdlet shows up in the list: Remove-PnPAzureADAppSitePermission
But when reading the documentation it says REVOKE-PnPAzureADAppSitePermission.

To clarify: Revoke-PnPAzureADAppSitePermission is the correct one which exists and is used.

Other occurrences of remove instead of revoke: 
1. Name in list 
2. Url : https://pnp.github.io/powershell/cmdlets/Remove-PnPAzureADAppSitePermission.html
3. Markdown file name and url reference in markdown file

**Comment by veronicageek** [comment]
@joetechin - Thanks for pointing this out. I have made the changes and the documentation will be updated soon 👍🏻
