### ISSUE TITLE
[BUG] Add-PnPPage: Gives 'Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.CoreEventSource' exception

### ISSUE THREAD

**Issue by aakashbhardwaj619** [pnp/powershell#251]
### Reporting an Issue or Missing Feature
Using the `Add-PnPPage` cmdlet to add a new site page gives the below error:
```
Add-PnPPage : The type initializer for 'Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.CoreEventSource' threw an exception.
At line:4 char:1
+ Add-PnPPage -Name "Test" -LayoutType Home
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Add-PnPPage], TypeInitializationException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Pages.AddPage
```

### Expected behavior 
The command should create a new page with the title `Test`

### Actual behavior 
Getting the below mentioned error
<img width="663" alt="Add-PnPPageBug" src="https://user-images.githubusercontent.com/33526902/107514051-1fbfd500-6bcf-11eb-9d65-8fb2382886a3.PNG">

### Steps to reproduce behavior
Install `PnP.PowerShell` and run the below script replacing `$url` value with a site url in the tenant
```
$url="https://m365x237356.sharepoint.com/sites/benefits"
Connect-PnPOnline -Url $url
Add-PnPPage -Name "Test" -LayoutType Home
```

### What is the version of the Cmdlet module you are running?
1.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Looks like you are using PS 5, can you try doing the same the using PS 7 if possible ? It has a different way to loading the DLLs and handling these conflicts.

**Comment by aakashbhardwaj619** [comment]
Thanks, @gautamdsheth! It works with PS 7 👍
