### ISSUE TITLE
[FEATURE] Add-PnPNavigationNode Set the option "Open in new tab" on navigation links

### ISSUE THREAD

**Issue by ChredP** [pnp/powershell#2519]
**Is your feature request related to a problem? Please describe.**
As of October 2022 Microsoft has added the option "Open in new tab" to navigation links.
Today this is not possible to configure with PNP Powershell.

**Describe the solution you'd like**
Add-PnPNavigationNode should have an extra property of type bool called something like "OpenInNewTab"
This should also be supported in Get-PnPSiteTemplate and Invoke-PnPSiteTemplate

**Describe alternatives you've considered**
As far as I know there is no alternative to this

**Additional context**
Relevant [Microsoft 365 roadmap](https://www.microsoft.com/en-my/microsoft-365/roadmap?filters=&searchterms=93318)

**Comment by RubenHerrera86** [comment]
Hello,

I just found this question, Do you know if there is something avaliable in pnp provisioning  to set up a node to be open in a new tab? since this is available on Oct 2022

**Comment by UrsWedershoven** [comment]
This would be a great enhancement, also in the context of provisioning templates. There exists a property "external", but I do not get, what that does.

**Comment by lovnish87** [comment]
Are there any changes for this requirement or it still is not considered yet ?
Microsoft has been recommending to use PnP PowerShell for developments and scripts however still its missing many parameters.

**Comment by lovnish87** [comment]
Looking forward for this to be included.

**Comment by MelvisBass** [comment]
I'm having the similar results as fm-kotwicki, no errors but Open in a new tab is not checked when I edit via GUI
![image](https://github.com/pnp/powershell/assets/137214349/bec1a666-a313-4381-a54d-7117e1670bad)
