### ISSUE TITLE
[FEATURE] Get-PnPMicrosoft365Group ExpirationDate

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#2521]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
It would be great to make ```Get-PnPMicrosoft365Group``` return ```ExpirationDate``` the same way ```Get-UnifiedGroup``` does:
![image](https://user-images.githubusercontent.com/5260172/199678756-6f34ec23-9423-4661-a0d6-ea3007b498ac.png)
```Get-PnPMicrosoft365Group``` does not seem to return these details. It has just ```RenewedDateTime``` instead.
![image](https://user-images.githubusercontent.com/5260172/199679226-fced9a87-b010-417d-b3f2-fec975c68870.png)

**Describe alternatives you've considered**
As of November 3rd, 2022 we have to use ```Get-UnifiedGroup``` to get ```ExpirationDate```

**Additional context**
```
Name    : PnP.PowerShell
Version : 1.11.123
```

**Comment by gautamdsheth** [comment]
In 1.12, we have added `Get-PnPMicrosoft365ExpiringGroup`, maybe that can help you ? It fetches you expiring groups.

https://pnp.github.io/powershell/cmdlets/Get-PnPMicrosoft365ExpiringGroup.html

**Comment by veronicageek** [comment]
Closing as no response.
