### ISSUE TITLE
[FEATURE]Any plans to move from System.Windows.Forms.WebBrowser IE to Edge so WebView2?

### ISSUE THREAD

**Issue by henrik0805** [pnp/powershell#2525]
Reopening #1955 

Have experienced that login using "BrowserHelper.GetWebLoginClientContext" is sometimes not possible. The usual pop-up that would otherwise show the login-in window shows a message that the Internet Explorer is no longer supported, suggesting to use Edge instead.
I think this only applies to Windows 11, and only sometimes...??

**Comment by gautamdsheth** [comment]
Not following this, what exactly do you want here ?

**Comment by gautamdsheth** [comment]
Ok ignore the above comment, just checked the issue.

This Weblogin thing is not something we want to improve. The future way is to use Azure AD authentication. Weblogin is not a secure way and doesn't work with other M365 stuff like Teams, Planner etc. It is legacy method which works by opening a browser, capturing cookies and using them to authenticate.

We will at some point get rid of weblogin , so no plans to improve it in the future. Sorry.

**Comment by MartinLaplante** [comment]
We have a specific issue where 3rd party authentication uses Javascript promise in the login dialog, a feature that IE does not support.
