### ISSUE TITLE
[FEATURE] Add ApplicationId as an alisa to ClientId to match Azure App Registration and Service Principal Object Model

### ISSUE THREAD

**Issue by MSIH** [pnp/powershell#2530]
PnP methods use the parameter ClientId to reference the Azure AD Application ID

To improve use and readability, the parameter should be changed to ApplicationId. 

Existing methods should have ApplicationId as an alias for ClientId

New Methods should use ApplicationId and alias ClientId

**Comment by gautamdsheth** [comment]
@MSIH - which cmdlets are you referring to? Can you please specify?

**Comment by schneiderbiNIH** [comment]
for example Connect-PnPOnline

$clientId = "GET IT FROM APP REGISTRATION PAGE"
$thumbprint = "RETURNED WHEN RUNNING New-PnPAzureCertificate"
$tenantId = "GET IT FROM APP REGISTRATION PAGE"

$connectionsParams = @{
    ClientId = $clientId 
    Thumbprint = $thumbprint 
    Tenant = $tenantId
}

$spoUrl = "https://tenant.sharepoint.com"
Connect-PnPOnline -Url $spoUrl @connectionsParams

**Comment by schneiderbiNIH** [comment]
this search show you all of them

https://github.com/pnp/powershell/search?q=clientid

**Comment by schneiderbiNIH** [comment]
If you look at the graph of the app registration or service principal, there is no clientid field! the unique ID for the app registration is the ApplicationId
