### ISSUE TITLE
[BUG] Add-PnPPageTextPart remove CR/LF in multiline text variables

### ISSUE THREAD

**Issue by CSARTSABCA** [pnp/powershell#2544]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
When using in powershell Add-PnPPageTextPart -Page $myPage -Text $mymultilinevariable, the webpart is correctly created but the multiline variable becomes a single line variable

### Expected behavior 
That a multiline variable remains multiline in the text part.

### Actual behavior 
the text part remove all CR/LF, so the multiline variable becomes a single line variable

### Steps to reproduce behavior
see above

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
ModuleType Version    Name                                ExportedCommands                                                                
---------- -------    ----                                ----------------                                                                
Manifest   1.11.126   PnP.PowerShell                      {Add-PnPAdaptiveScopeProperty, Add-PnPPropertyBagValue, Add-PnPSiteClassifica...
Manifest   1.10.55    PnP.PowerShell                      {Add-PnPAdaptiveScopeProperty, Add-PnPPropertyBagValue, Copy-PnPFolder, Expor...
Manifest   1.10.47    PnP.PowerShell                      {Add-PnPAdaptiveScopeProperty, Add-PnPPropertyBagValue, Copy-PnPFolder, Expor...
Manifest   1.7.15     PnP.PowerShell                      {Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add-PnPClientSideText, ...

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands                                                                
---------- -------    ----                                ----------------                                                                
Manifest   1.3.15     PnP.PowerShell                      {Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add-PnPClientSideText, ...

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
What do you mean by multiline variable ?? Not following the issue here, can you please elaborate.

The input that is required is a string for the text webpart.

**Comment by CSARTSABCA** [comment]
Hi
When you have a powershell string, it can be in 1 line or in multiple lines. It is still a string.

For example, create a string :
$test = “myfirst line (<type enter>)
>> mysecond line”

The result of $test will be :
Myfirstline
Mysecondline

But when I used it into “Add-PnPPageTextWebPart”, the result is :
Myfirstline Mysecondline

It should be possible that a text in a text webpart spread on multiple lines, doesn’t it ?
CS

**Comment by gautamdsheth** [comment]
hi @CSARTSABCA , the server-side API I think trims out the blank empty spaces.
You need to specify the new line like you would do that in HTML.
Usually, we can use `<p></p>` or `<br />` to specify text in new lines. You can use that.

**Comment by CSARTSABCA** [comment]
Thanks, it is working with a <br> tag.
