### ISSUE TITLE
Set-PnPSearchSettings : The property or field 'SearchScope' has not been initialized

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/powershell#255]
### Reporting an Issue or Missing Feature
When I use:
`Set-PnPSearchSettings -Connection $dpcConn -SearchBoxPlaceholderText "Search All Over" -SearchScope Tenant -SearchBoxInNavBar AllPages`
There is no error but the "Search All Over" is showing only at the home page of the connected site any other list page shows "Search this list"

If I add "-Scope Site" thinking this will make it show all over the site collection.
I get the error:
`Set-PnPSearchSettings : The property or field 'SearchScope' has not been initialized. It has not been requested or the request has not been executed. It may 
need to be explicitly requested.`

### Expected behavior 
No error when using -Scope Site and the same SearchScope on all pages in the site.

### Actual behavior 
`Set-PnPSearchSettings : The property or field 'SearchScope' has not been initialized. It has not been requested or the request has not been executed. It may 
need to be explicitly requested.`
### Steps to reproduce behavior
`Clear-Host
$ClientId = "999"
$tenant = "999"
$dpcUrl ="https://mycompany.sharepoint.com/sites/dpc"
$certPath = "C:\Users\me\mydev.pfx"
$dpcConn = Connect-PnPOnline  -Url $dpcUrl -ClientId $ClientId -CertificatePath $certPath -CertificatePassword (ConvertTo-SecureString -AsPlainText 'password' -Force)  -Tenant $tenant -ReturnConnection
Set-PnPSearchSettings -Connection $dpcConn -SearchScope Tenant -Scope Site  -SearchBoxPlaceholderText "Search All Over" -SearchBoxInNavBar AllPages
Write-host "Done!"`
### What is the version of the Cmdlet module you are running?
1.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
Thank you for reporting this. The issue has been fixed in release 1.3.0 which came out today.

**Comment by Ofer-Gal** [comment]
Thanks
