### ISSUE TITLE
Method not found exception for cmdlet Get-PnPClientSidePage

### ISSUE THREAD

**Issue by ani2020** [pnp/powershell#2560]
### Expected behavior 
Get Page object

### Actual behavior 
Get an exception

>Get-PnPClientSidePage : Method not found: 'System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1<Boolean>
>Enumerator.MoveNextAsync()'.
>At line:1 char:9
>\+ $page = Get-PnPClientSidePage -Identity $pp
>\+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   \+ CategoryInfo          : InvalidOperation: (:) [Get-PnPPage], PSInvalidOperationException
>    \+ FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.Pages.GetPage

### Steps to reproduce behavior
Import-Module PnP.PowerShell
Connect-PnPOnline -URL "SomeValidURL" -UseWebLogin
$pp = "test.aspx"
$page = Get-PnpClientSidePage -Identity $pp

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
>\$> Get-Module PnP.PowerShell -ListAvailable |select Name, version

>Name           Version
>\----           -------
>PnP.PowerShell 1.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows 11

**Comment by Studermarc** [comment]
The Cmdlet "Get-PnPClientSidePage" has been renamed to "Get-PnPPage" a couple versions back. 

Check the docs here: [https://pnp.github.io/powershell/cmdlets/Get-PnPPage.html](https://pnp.github.io/powershell/cmdlets/Get-PnPPage.html)

**Comment by ani2020** [comment]
> The Cmdlet "Get-PnPClientSidePage" has been renamed to "Get-PnPPage" a couple versions back.
> 
> Check the docs here: https://pnp.github.io/powershell/cmdlets/Get-PnPPage.html

Yes, I read that and even tried Get-PnPPage (See original description) and I am getting the same error.

**Comment by veronicageek** [comment]
@ani2020 - I have no issue with those cmdlets (tested on 1.12.6). Maybe it was at a point in time, please try again.

![image](https://user-images.githubusercontent.com/25181757/202404269-be89109a-179b-4812-b6b0-d5686f98350e.png)

**Comment by veronicageek** [comment]
Closing as no response.
