### ISSUE TITLE
[BUG] Get-PnPAccessToken not working in 1.12

### ISSUE THREAD

**Issue by gabbsmo** [pnp/powershell#2561]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
Access token in output

### Actual behavior 
`Get-PnPAccessToken: Unable to retrieve access token`

### Steps to reproduce behavior
```
Update-Module *
Connect-PnPOnline -Url *** -ClientId *** -Tenant *** -Thumbprint ***
Get-PnPAcccessToken
```

### What is the version of the Cmdlet module you are running?
1.12.0. Seems to work with 1.11.0.

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [x] Azure Functions
- [ ] Other : please specify

**Comment by gabbsmo** [comment]
Thanks. Will try that. If this is a change that the maintainers want, then it should be in a semver number that allows for breaking changes.

Changed my Azure Function dependency from 1.* to 1.11.0.

**Comment by Nazul** [comment]
I had the same issue and it was fixed with the ResourceTypeName parameter as recommended.

**Comment by gautamdsheth** [comment]
Yeah, is a regression. Sorry about that, will fix it via the above PR.

**Comment by Studermarc** [comment]
@gautamdsheth Thanks a lot! Truly appreciate everything you're doing for PnP.Powershell
