### ISSUE TITLE
[BUG] Set-PnPListItem -UpdateType UpdateOverwriteVersion changes modified date/time

### ISSUE THREAD

**Issue by tkyssmz** [pnp/powershell#2563]
### Reporting an Issue or Missing Feature
The behavior of Set-PnPListItem seems to have changed between 1.11.0 and 1.12.0, regarding -UpdateType UpdateOverwriteVersion.
I'm afraid it could be a bug.

### Expected behavior 
If you specify Modified field value with -UpdateType UpdateOverwriteVersion option, the specified date/time is set to the item.

### Actual behavior 
The current date/time is set to the item in Modified field.

### Steps to reproduce behavior
As below. (Sorry for the locale.)

===== PnP.PowerShell 1.11.0 =====

PS C:\Users\pc1> $item = Get-PnPListItem -List SDCSSD2 -Id 10
PS C:\Users\pc1> $item.FieldValues.Modified

2014年9月2日 6:00:00

PS C:\Users\pc1> $values = @{ Modified=[datetime]'2016/03/05' }
PS C:\Users\pc1> $updatedItem = Set-PnPListItem -List SDCSSD2 -Identity 10 -Values $values -UpdateType SystemUpdate
PS C:\Users\pc1> $item2 = Get-PnPListItem -List SDCSSD2 -Id 10
PS C:\Users\pc1> $item2.FieldValues.Modified

2014年9月2日 6:00:00

PS C:\Users\pc1> $updatedItem = Set-PnPListItem -List SDCSSD2 -Identity 10 -Values $values -UpdateType UpdateOverwriteVersion
PS C:\Users\pc1> $item3 = Get-PnPListItem -List SDCSSD2 -Id 10
PS C:\Users\pc1> $item3.FieldValues.Modified

2016年3月4日 15:00:00

PS C:\Users\pc1>

===== PnP.PowerShell 1.12.0 ===== (on different pc)

PS C:\Users\pc2> $item = Get-PnPListItem -List SDCSSD2 -Id 10
PS C:\Users\pc2> $item.FieldValues.Modified

2016年3月4日 15:00:00

PS C:\Users\pc2> $values = @{ Modified=[datetime]'2020/10/19' }
PS C:\Users\pc2> $updatedItem = Set-PnPListItem -List SDCSSD2 -Identity 10 -Values $values -UpdateType SystemUpdate
PS C:\Users\pc2> $item2 = Get-PnPListItem -List SDCSSD2 -Id 10
PS C:\Users\pc2> $item2.FieldValues.Modified

2016年3月4日 15:00:00

PS C:\Users\pc2> $updatedItem = Set-PnPListItem -List SDCSSD2 -Identity 10 -Values $values -UpdateType UpdateOverwriteVersion
PS C:\Users\pc2> $item3 = Get-PnPListItem -List SDCSSD2 -Id 10
PS C:\Users\pc2> $item3.FieldValues.Modified

**2022年11月17日 9:49:51**

PS C:\Users\pc2>

=====

### What is the version of the Cmdlet module you are running?
1.12.0
(1.11.0 didn't have this issue.)

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by KoenZomers** [comment]
@tkyssmz I have checked the code changes done between 1.11 and 1.12 with this regard and cannot detect anything that changed that could play a role in this. I ran some tests myself and indeed with `-UpdateType UpdateOverwriteVersion` it changes the Modified date and time, but that seems the [expected result](https://thesharepoint2010.wordpress.com/2012/09/26/update-systemupdate-and-updateoverwriteversion-splistitem/#:~:text=UpdateOverwriteVersion()). Also in your examples above you also show that on both machines UpdateOverwriteVersion updates the Modified date/time stamp, so I'm missing the point where you say it worked differently in 1.11 as opposed to 1.12. Can you clarify?

**Comment by tkyssmz** [comment]
@KoenZomers , Thank you for your response.
The difference is that 1.11 changes Modified as specified by $values, but 1.12 changes Modified to the current time ignoring $values.

**Comment by tkyssmz** [comment]
I hope someone could look into this issue.

**Comment by gautamdsheth** [comment]
@tkyssmz - can't repro this. Tried with both 1.11 and 1.12 and both the times, the values are correctly set. The modified/created values are set to the values that are provided.

**Comment by tkyssmz** [comment]
Thank you for trying, @gautamdsheth 
But this happens on two of my PCs (one is physical, the other is cloud virtual desktop), and on my colleague's.
Could the locale setting have any impact on this issue? Ours is Japanese (Windows 10).

**Comment by gautamdsheth** [comment]
@tkyssmz - not sure. Can you try in some other locale ? Maybe try in another site collection or another tenant and check ? Also, maybe try it as `$values = @{ Modified='2020/10/19' }` remove the `datetime` typecast and check ?

**Comment by RoWa2006** [comment]
I encountered the same issue as @tkyssmz 
in V1.11, "Modified"  is set to the date I specify. 
In V1.12, "Modified"  is set to the (current) date/time the Set-PnPListItem cmd ran
locale setting is ENG/US

**Comment by tkyssmz** [comment]
I'm relieved to know that the issue is reproduced in another locale.
Thank you, @RoWa2006 .

**Comment by jnhrv** [comment]
Hi,

I have the same issue in PnP v1.12

Want to set _Modified_ date to a custom date but the date is overwritten by currentDate.

`
$values = @{Modified="2020/10/19"}
  
#Connect to PnP Online
Connect-PnPOnline -Url $SiteURL -Interactive
   
#Get the File from SharePoint
$File = Get-PnPFile -Url $SiteRelativeURL -AsListItem
   
#Update document properties
Set-PnPListItem -List $ListName -Identity $File.Id -Values $values -UpdateType UpdateOverwriteVersion
`

**Comment by gautamdsheth** [comment]
@jnhrv / @tkyssmz / @RoWa2006 - sorry still can't repro unfortunately. 

Can you please try the latest nightly builds and test it ? Do note, the latest nightly builds will work only on PowerShell 7.2.x or later version of PowerShell

![image](https://user-images.githubusercontent.com/8832018/218114192-628dd5f1-9fe6-4d59-942b-6fe0be69cc69.png)

and in the UI 

![image](https://user-images.githubusercontent.com/8832018/218114320-5e55e2f9-889b-4900-8c57-78e214e41a40.png)

**Comment by tkyssmz** [comment]
My colleague and I have tried and seen that 2.0.14-nightly shows the correct behavior regarding Modified property.
Thank you for the fix, @gautamdsheth 

Will the fix be available also on PS 5.1 when it is officially released?

**Comment by gautamdsheth** [comment]
hi @tkyssmz , we haven't changed anything here. Most likely it will be something the CSOM which has fixed it. 

The next major version will only work on PS 7.2 or later versions of PowerShell.

Thanks for getting back to us and confirming, will close this issue.

**Comment by tkyssmz** [comment]
> we haven't changed anything here. Most likely it will be something the CSOM which has fixed it.

Could you please elaborate on this?
PnP 1.12 on PS7 do have this issue, but PnP 2.0.14 on PS7 doesn't.
There should be some change regarding Set-PnPListItem between two PnP versions...
Is CSOM included in PnP package??

@gautamdsheth

**Comment by TracyGH** [comment]
I tried using the latest nightly build (2.0.25) and am still experiencing the same issue. 

Is there somewhere we should open a CSOM issue?

**Comment by jnhrv** [comment]
I just upgraded to PS 7.3 and installed  PNP module version 2.0.46-nightly.
This works perfectly now
`Set-PnPListItem -List $ListName -Identity $Item.Id -Values $values -UpdateType UpdateOverwriteVersion`

**Comment by SPT-Seb** [comment]
FYI I'm in 2.12 version / Powershell 7.4.3 ->same issue.

**Comment by ToddDoesCode** [comment]
Issue is still present in pnp 3.1.0 on PowerShell 7.5.4

`$values = @{`
`Created = $ParsedCreateDate`
`Modified = $ParsedModDate`
`Author = $CreateUser`
`Editor = $ModUser`
`}`
`Set-PnPListItem -List ($RelativePath | Split-Path) -Identity $File.Id -Values $values -Force -UpdateType UpdateOverwriteVersion | Out-Null`

All values above are set as expected except Modified

**Comment by loicyannou** [comment]
PowerShell 7.5.4 (Visual Studio Code)
PnP.PowerShell module 3.1.0

I even can't update the _Created_ field
I've tested with several syntaxes but the field remains unchanged
Is there any syntax to use for this _DateTime_ field, please ?

```
$values = @{ "Created" = "03/13/2015 14:16" }
Set-PnPListItem -List $ListName -Identity $Id -Values $values -Force -UpdateType UpdateOverwriteVersion
```
