### ISSUE TITLE
[BUG] Provisioning Template removing the navigation since 1.12

### ISSUE THREAD

**Issue by BaronSparky** [pnp/powershell#2564]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
Application of a tenant template to not interfere with local navigation. 

### Actual behavior 
I have been using the same XML based tenant template for 6 months, to provision standard SPO team sites. After updating to PnP.PowerShell 1.12.0, from 1.11.0, this morning, in my Azure function hosted solution, I am seeing newly provisioned sites, from the template that I have been using for some months, is removing the local navigation.
![image](https://user-images.githubusercontent.com/11838512/202484159-2bc82f07-1c91-424e-a49b-c255f41ffb84.png)

The template does not have the `<pnp:Navigation />` node included.

### Steps to reproduce behavior
I have a PnPTenant XML template with the structure of:
![image](https://user-images.githubusercontent.com/11838512/202481927-b60eae41-c356-403c-8b98-168b2dd38f36.png)

I execute the template, with parameters built, via:
`Invoke-PnPTenantTemplate -Connection $provSiteConnection -Path "[filepath]" -Parameters $templateParameters -ErrorAction Stop`

### What is the version of the Cmdlet module you are running?
PnP.PowerShell V1.12.0 (PowerShell Version: 7.0)

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by Studermarc** [comment]
Hi @BaronSparky ,

This isn't a Bug. The Navigation isn't removed, only hidden. Why? because it is defined to be hidden in the template:

![image](https://user-images.githubusercontent.com/31045631/225760328-c3df664e-03f3-4e8b-936f-3494c57917e9.png)

-> Not a Bug, working as intended.

**Comment by BaronSparky** [comment]
@Studermarc you are right. Missed that setting. Thanks
