### ISSUE TITLE
[BUG] Issue with Get-PnPTenantSite on vanity URL domain

### ISSUE THREAD

**Issue by plagooms** [pnp/powershell#2567]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

### Reporting an Issue or Missing Feature
i am having same issue similar to a fixed bug https://github.com/pnp/powershell/issues/137
cmdlet i am using is Get-PnPTenantSite. we are using vanity URL for our tenant site and admin URL.

### Expected behavior 
No error when executing cmdlet Get-PnpTenantSite

### Actual behavior 
PS C:\temp\Test> $s = Get-PnPTenantSite -Identity $SiteId -Detailed -Connection $ctxt
Get-PnPTenantSite : AADSTS500011: The resource principal named https://admin-admin.domain.com was not found in the tenant named Domain. 
This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You 
might have sent your authentication request to the wrong tenant.
Trace ID: 2c2d6b11-3774-4b9f-8cc1-7e0d31fe4500
Correlation ID: 4396a26b-efa1-4d7d-b609-9a25c4876f59
Timestamp: 2022-11-18 10:27:49Z
At line:1 char:6
+ $s = Get-PnPTenantSite -Identity $SiteId -Detailed -Connection $ctxt
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPTenantSite], MsalServiceException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.GetTenantSite

### Steps to reproduce behavior
Run this cmdlet
 $s = Get-PnPTenantSite -Identity $SiteId -Detailed -Connection $ctxt

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

PS C:\temp\Test>  Get-Module -Name "PnP.PowerShell" -ListAvailable
    Directory: C:\Program Files\WindowsPowerShell\Modules
ModuleType Version    Name                                ExportedCommands                                                                      
---------- -------    ----                                ----------------                                                                      
Manifest   1.11.0     PnP.PowerShell                      {Add-PnPAdaptiveScopeProperty, Add-PnPPropertyBagValue, Add-PnPSiteClassification,

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows

**Comment by plagooms** [comment]
Apologies on delayed reply... @KoenZomers  - this is how we connect:
Connect-PnPOnline -Url $AdminUrl -Interactive -ErrorAction SilentlyContinue

$AdminURL = admin.domain.com (vanity URL)

The issue here is that cmdlet expect the URL format to be something like:
https://tenantname-admin.domain.com/
where tenantname-admin is the expected format for non-vanity URL

In our case, appending "-admin" will not work as our admin URL when accessed via admin portal does not have "-admin".

I tried this one - Connect-PnPOnline -Url domain.com -Interactive -TenantAdminUrl https://admin.domain.com, it is not working for us and below is the error:

Connect-PnPOnline : Invalid URI: The format of the URI could not be determined.
At line:1 char:1
+ Connect-PnPOnline -Url domain.com -Interactive -TenantAdminUrl https://admin.domain.com
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-PnPOnline], UriFormatException
    + FullyQualifiedErrorId : System.UriFormatException,PnP.PowerShell.Commands.Base.ConnectOnline

**Comment by KoenZomers** [comment]
Same with the latest nightly build? The error you get doesn't really make sense in this case. Can you try and see if it makes a difference if you do:

`Connect-PnPOnline -Url https://vanity.domain.com -Interactive -TenantAdminUrl https://admin.domain.com`

OfCourse replacing this with your actual domains? Please take careful notice in the notation of slashes etc.  

In case of vanity domain tenants, you will ALWAYS need to specify -TenandAdminUrl in your connect.

If that still yields the same error, would you mind e-mailing me the exact Connect you use with the proper domain names in it so I can see what happens behind the scenes (koen@zomers.eu)? I don't need a login account, just want to see what it does when trying to connect.

Does the error you show occur before or after entering your credentials?

**Comment by KoenZomers** [comment]
Closing due to no response received
