### ISSUE TITLE
[FEATURE] dynamic content for teams tab provisioning SharePointPageAndList

### ISSUE THREAD

**Issue by nikolasph** [pnp/powershell#2571]
**Is your feature request related to a problem? Please describe.**
Yes - see this bug report: https://github.com/pnp/powershell/issues/225

**Describe the solution you'd like**
Enable dynamic content for the given tab type in order to preconfigure the website to render in the tab. 

**Describe alternatives you've considered**
Is there currently a way of solving your problem with existing cmdlets? Optionally through the use of other PowerShell Modules (for instance by using the Microsoft Graph cmdlets or the Microsoft SPO Management Shell)
Alternative is only to develop a own teams tab which then needs to go through the process of compliance and publishing to the organization using teams admin center. A lot of work for something deadly needed. 

**Additional context**
Nope :)

**Comment by SaidUK19** [comment]
I have faced the same issue today, was trying to push a script to create sharepoint tab to more than 2k teams but it didnt work.
Adding it as a website and passing the sharepoint link as a URL doesn't load the page when you navigate into the newly created tab. :(
Would love to have the option of using type sharepoint and providing a URL into it.
