### ISSUE TITLE
Invalid Filter Clause - Get-PnPMicrosoft365Group

### ISSUE THREAD

**Issue by alexinnes** [pnp/powershell#2576]
When trying to retrieve a Microsoft 365 group via the Get-PnPMicrosoft365Group command and the MS Group has a & symbol in the name it throws the error "Invalid filter clause":
```
Get-PnPMicrosoft365Group -Identity "Test & site"
Get-PnPMicrosoft365Group: Invalid filter clause
```

![image](https://user-images.githubusercontent.com/1482061/203768858-17789a9a-a489-43af-8295-e3b4d09b7a05.png)

**Comment by Gatario** [comment]
Hello,
You have to encode the name with System.Web.HttpUtility


``Get-PnPMicrosoft365Group -Identity ([System.Web.HttpUtility]::UrlEncode("Test & Site"))``
Source : https://blog.sperre.org/2022/02/22/urlencode-parameters.html

**Comment by gautamdsheth** [comment]
Thanks @Gatario for providing the solution.

@alexinnes - as mentioned in the above comment, you need to encode the string before passing the value to the cmdlet. The PowerShell module doesn't encode it.
