### ISSUE TITLE
[BUG] Invoke-PnPSPRestMethod not working with PATCH method

### ISSUE THREAD

**Issue by GuopingSun** [pnp/powershell#2583]
### Reporting an Issue or Missing Feature
Issue: We are trying to use Invoke-PnPSPRestMethod to update Site name for group connected SharePoint sites, but this doesn't work in this specific API call. 

### Expected behavior 
The response should be 204 No Content.

### Actual behavior 
This throws the following error:
Invoke-PnPSPRestMethod : {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.ClientServiceException","message":{"lang":"en-US","value":"The HTTP method 'Patch' cannot be used to access the resource 'Update'. The operation type of the resource is specified as 'Default'. Please use correct HTTP method to invoke the resource."}}}

### Steps to reproduce behavior
Please use the following script to reproduce (replace the placeholders):
$SiteCollectionUrl = "xxx"
$OfficeUnifiedGroupId = "xxx"
$SiteTitle = "xxx"

$url = "/_api/SP.Directory.DirectorySession/Group('" + $OfficeUnifiedGroupId + "')"
$body = @{
            __metadata = @{
                type="SP.Directory.Group";
            };
               displayName= $SiteTitle;
}
Connect-PnPOnline -Url $SiteCollectionUrl -Interactive
Invoke-PnPSPRestMethod -Url $url -Method Patch -Content $body -ContentType "application/json;odata=verbose" -Raw

### What is the version of the Cmdlet module you are running?
1.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by KoenZomers** [comment]
@GuopingSun it works fine here with exactly the script sample you provide. Could there be something on your network connection interfering? Or perhaps a temporary glitch on the server side causing this? Can you run a Fiddler trace and see what happens over the wire when you execute this script?

**Comment by GuopingSun** [comment]
@KoenZomers I just tested again. It's still throwing that same error, but it works fine when fiddler is running. Do you have any idea why this works with fiddler?

**Comment by KoenZomers** [comment]
Not sure. Only think I can think of is that your machine could be using a proxy that messes with the traffic? When enabling Fiddler, that will function as the proxy on your machine instead.

**Comment by veronicageek** [comment]
Closing as it might be related to the local environment and couldn't be reproduced.
