### ISSUE TITLE
[FEATURE]Support for RateLimit headers to avoid soft throttling

### ISSUE THREAD

**Issue by AndersRask** [pnp/powershell#2611]
When doing requests against the REST api, it is a best practice to read RateLimit headers to avoid soft throttling (429) and higher throughput (as you dont have to wait 120 seconds)

As https://github.com/pnp/pnpcore/discussions/1026#discussioncomment-4097926 in over in PnP.Core, there now is support for avoiding soft throttling by regulating request frequency in that framework

It would be a most welcome feature in PnP.PowerShell if we would have support for RateLimit, so we easier could adjust the request load on the endpoints before we get throttled, and not when we already get 429's

It could be implemented as something you could enable (like on pnp.core) context or connection wide

@jansenbe has an excellent video on the subject here
https://www.youtube.com/watch?v=vnBW66ncs80

**Comment by AndersRask** [comment]
@KoenZomers @erwinvanhunen  any thoughs on putting this feature in the backlog?
Since PnP.Framework takes care of the response objects, it is hard to take RateLimit into account for users of the PnP.PowerShell module (we only see requests when a http related error occurs).
Hence it would make a lot of sense to implement that RateLimit was handled too :)

An added bonus would be that endpoints on tenants would be hit less, when people use this module

**Comment by gautamdsheth** [comment]
hi @AndersRask , definitely in the plans. Soo much to do, soo little time :)

**Comment by AndersRask** [comment]
@gautamdsheth i talked to Erwin and Bert at the CollabSummit, and it sounded like we were getting closer to having RateLimit support in this module. Any news?
I think both the tenant and the users would benefit from this - and Microsoft as they have to do less Throttling support tickets :-D

**Comment by AndersRask** [comment]
@jansenbe this is the feature request for rate limit support on retry handler. It would make sense (maybe) to point it to your pnpcore or to expand pnpframework with this feature.
The problem is that retry handler swallows all http responses so you don't know of you're even getting throttled or not, or receiving rate-limit headers.
IMO this is essential feature for the handler and at the same point let's us treat the endpoints better

**Comment by AndersRask** [comment]
The half yearly BUMP of this issue - in my oppinion this is what makes PnP not usable for many production scenarios, as Rate Limit support is so vital with limited ressources available

**Comment by erwinvanhunen** [comment]
@AndersRask : it took a while, but we're actively working on it as we speak. It goes a bit further than just PnP PowerShell as we need to implement it in the PnP Framework CSOM handling, the SPO Rest calls and the Graph Rest calls we're doing. The work will happen both in the PnP Framework and the PnP Core SDK. The moment we're done on that side we can relatively easily add support for it in PnP PS.

**Comment by gautamdsheth** [comment]
@AndersRask - this has been implemented and is available in the nightly builds. 

Closing this , do let us know how it works !

Thanks for pushing this :)
