### ISSUE TITLE
[BUG] Set-PnPSearchSettings -SearchBoxPlaceholderText does not work with Vanity domains

### ISSUE THREAD

**Issue by mikelee1313** [pnp/powershell#2613]
### Reporting an Issue or Missing Feature
Set-PnPSearchSettings -SearchBoxPlaceholderText  "Text" does not work with Vanity domains. It appears to be appending the "-admin" at the end of the URL. Vanity domains do not conform to this standard.

### Expected behavior 
Executing" Set-PnPSearchSettings -SearchBoxPlaceholderText 'Text' " should locate the correct Admin URL and does not fail with AADSTS500011 error.

### Actual behavior 

![image](https://user-images.githubusercontent.com/62190454/205936807-ae75068a-cf43-4fa5-bed2-62d4859bda15.png)

The following dialog appears as it's assuming the "tenant-admin.domain.com" URL convention, however, this is incorrect as our organization uses a vanity URL for the admin center.

![image](https://user-images.githubusercontent.com/62190454/205936835-9c31749a-6cea-4511-8d72-b86503669a58.png)

### Steps to reproduce behavior

1. Connect to SPO with pnp

![image](https://user-images.githubusercontent.com/62190454/205937070-4aafda03-33f6-4116-a9df-61af7c93336b.png)

2. Run Set-PnPSearchSettings -SearchBoxPlaceholderText "Search Here"

### What is the version of the Cmdlet module you are running?
1.10.50

![image](https://user-images.githubusercontent.com/62190454/205937028-c19c3430-3874-4a53-ba55-ee4fcea5ddfd.png)

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows

**Comment by gautamdsheth** [comment]
When using vanity domains, you need to specify `-TenantAdminUrl` with the value of your tenant admin site collection in the `Connect-PnPOnline` cmdlet

Can you try that and then execute this `Set-PnPSearchSettings` command ?

**Comment by mikelee1313** [comment]
I will test this this week and update the bug. Thank you!

**Comment by KoenZomers** [comment]
I managed to track it down to an hardcoded -admin definition in PnP Framework: https://github.com/pnp/pnpframework/blob/3d6154e7cf596eb7f7ddcdf8863d5ecf1a25ef24/src/lib/PnP.Framework/AuthenticationManager.cs#L1523 . Trying to see how we can fix this.

**Comment by KoenZomers** [comment]
@mikelee1313 Thanks for reporting this issue. It will be fixed once the above two referenced PRs have been merged. Once they are, the next calendar day you can use `Update-Module PnP.PowerShell -AllowPrerelease` to update to a version that would include the fix.

**Comment by gautamdsheth** [comment]
Has been fixed now, will be available via tomorrow's nightly build and the next major version whenever it is going to be released

**Comment by mikelee1313** [comment]
Thank you!!!
