### ISSUE TITLE
[BUG] New-PnPAzureCertificate: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by carolinedpena** [pnp/powershell#2614]
### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets
Generation of certificate(s)

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.
<img width="755" alt="Screenshot 2022-12-06 at 11 50 55 AM" src="https://user-images.githubusercontent.com/47426769/205973142-3aa2aaa7-2f07-4796-92d3-fc5549342710.png">

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)
`$cert=New-PnPAzureCertificate -OutPfx pnp.pfx -OutCert pnp.cer -CertificatePassword (ConvertTo-SecureString -String "password" -AsPlainText -Force)`
`New-PnPAzureCertificate -OutPfx pnp.pfx -OutCert pnp.cer -CertificatePassword (ConvertTo-SecureString -String "password" -AsPlainText -Force)`

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

Currently using 1.12.26 nightly release:
<img width="763" alt="Screenshot 2022-12-06 at 11 53 16 AM" src="https://user-images.githubusercontent.com/47426769/205973595-4b991b65-e699-4034-b7f6-414338ddca04.png">

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [X] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by KoenZomers** [comment]
@carolinedpena It seems to fail on trying to write the certificate to disk. I don't have a Mac so cannot try this out. Can you try specifying a full path to where it should write the certificates to and see if that makes a difference?

**Comment by carolinedpena** [comment]
@KoenZomers - specifying the full path results in the same error message:
![image](https://user-images.githubusercontent.com/47426769/206502479-a0436917-8ef1-4142-808b-28ee104b9efd.png)

**Comment by ollimenzel** [comment]
I have the same issue on my Mac

**Comment by veronicageek** [comment]
Most likely because MacOS uses **forward slashes** for paths (not back slashes). And although it throws an error on the second line (with the forward slashes), it still creates the certs in the correct folder, but the first line (back slashes doesn't at all).

![image](https://user-images.githubusercontent.com/25181757/219440275-1c3e7d2e-a383-4cba-a0f9-3700612ba2f5.png)

Closing for now. Feel free to reopen if the certs are not created.
