### ISSUE TITLE
[BUG] `Add-PnPRoleDefinition` doesn't assign permissions correctly

### ISSUE THREAD

**Issue by etimp** [pnp/powershell#2619]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
I am running PnP PowerShell cmdlet Add-PnPRoleDefinition to create permission levels.and then assigning custom permission level to a SharePoint group. When I browse to a library, select an item, and click Manage Access, I see the name of the SharePoint group that has the custom permission level. However, the permissions of the group aren't displayed or displayed incorrectly, and users in that SharePoint group don't have expected access to the site, or they have too much access. This issue doesn't occur if I create the custom permission level manually through the Edit Permission Level UI with the exact same permissions selected. 

I can also fix the scripted permission level by opening it up in the GUI, and clicking submit without making any changes to the permissions selected.

### Expected behavior 
I expect the scripted permission levels to work the same as those created in the UI.

### Actual behavior 
The permission levels don't show correctly when looking at an item level, as well as the behavior doesn't match what is set in the permission level.

### Steps to reproduce behavior
Copy a permission level, and exclude items using add role definition 

#Create Custom View Only permission level (clone the 'Custom Contribute' default permissions)
    $CustContr = Get-PnPRoleDefinition -Identity "Custom Contribute"
    $addPnPRoleDefinitionCustView = @{
        Exclude     = 'AddListItems', 'EditListItems', 'DeleteListItems', 'ApproveItems', 'ManageAlerts', 'ManagePersonalViews'
        Description = "Custom: Can view pages, list items, and documents. Document types with server-side file handlers can be viewed in the browser but not downloaded."
        RoleName    = "Custom View Only"
        Clone       = $CustContr
    }
    Add-PnPRoleDefinition @addPnPRoleDefinitionCustView

Assign this role to a group, and test the behavior. 

### What is the version of the Cmdlet module you are running?
1.11.0, however this was happening on previous versions as well. We just discovered the bug after using this for about two years.

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
Closing. Please reopen if the issue persists with new releases.
