### ISSUE TITLE
[FEATURE] Pin Columns to the Filters Pane

### ISSUE THREAD

**Issue by hunandy14** [pnp/powershell#2620]
![howtopincolumnsdoclibrary8](https://user-images.githubusercontent.com/13827054/206473570-7d2091b0-38c9-461a-9cb9-ce2f28147ba8.png)

https://sharepointmaven.com/how-to-add-custom-metadata-columns-to-the-filters-pane-in-sharepoint-online/
Refer to step 5 of this webpage.

I'm not sure if it's already an existing feature, but I can't find it on google search.
Can add the [Pin Columns to the Filters Pane] function?

**Comment by KoenZomers** [comment]
Hi @hunandy14, this has been added in PR https://github.com/pnp/powershell/pull/2632. Once merged you can use `Set-PnPField -Identity "Internal name of field" -ShowInFiltersPane <Auto\Removed\Pinned>` to set it to the desired value.

**Comment by hunandy14** [comment]
Thank you very much, I will update the version tomorrow to try this function

**Comment by KoenZomers** [comment]
We need @gautamdsheth to buddy check my changes and merge the PR first :) Once that is done, after the first 2.30 AM Central European Time after the PR is merged, it will be available in the nightly build.
