### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TMVUpShare** [pnp/powershell#2624]
### Reporting an Issue or Missing Feature
I'm trying to get PnP Get-PnPSiteTemplate and Invoke-PnPSiteTemplate to work, but as all of you have described i run into this error. I can't downgrade to 7.0 so it looks as though i can't get this to work at all.

If i try to use Get-PnPSiteTemplate and save that file to SharePoint it dosen't create any files, if i try to save locally in my Function app it dosen't create any files. So that seems to not work at all. If i run it on my own machine it works as it should.

If i then try and run Invoke-PnPSiteTemplate it does actually look like it works but again it dosen't. It runs and do add the template to a site, but not all. The left menu dosen't get finished, pages don't get changes and so on. Again if i run it on my own machine it works.

So is it really the correct conclusion that PnP provisioning from a Azure function cannot work, and all we can do is wait on updates?

Is there any alternatives to PnP provisioning because i'm actually not that keen on using PnP seeing as it dosn't seem like a good idea to build business solutions on?

### Expected behavior 
Being able to both extract a template and add a template to a SharePoint site with PnP provisioning

### Actual behavior 
ERROR: Could not load type 'Microsoft.Extensions.Logging.Abstractions.Internal.NullScope' from assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

And no files are being created and when adding a template to a site it dosen't add all as it does when running it on my own machine.

### Steps to reproduce behavior
Create an Azure functions app version 4.0 and set it to use PowerShell 7.2
Add PnP.PowerShell 1.* to the requirements.psd1 file.
Create a basic function that just tries to execute Connect-PnPOnline. Ensure it logs error info.
Add either Get-PnPSiteTemplate or Invoke-PnPSiteTemplate to the script
Deploy the function to the cloud and execute via your API. (<app_url>/api/<func_name>)
Wait a bit for logs to save, then go to monitor log menu for that function.
View its logs and observe error.

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 1.*, PowerShell Core 7.2
I also tried with the nightly builds

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ x] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
Closing as duplicate with #2136. Please follow the thread there.
