### ISSUE TITLE
EnableAzureADB2BIntegration parameter for Set-PNPTenant and Get-PNPTenant

### ISSUE THREAD

**Issue by tasgray** [pnp/powershell#2628]
This is essentially a repeat of this issue but for the powershell project - [https://github.com/pnp/cli-microsoft365/issues/3110](https://github.com/pnp/cli-microsoft365/issues/3110)

Any chance that these parameters could be added?

Cheers

**Comment by KoenZomers** [comment]
Hi @tasgray. I've added the two in the PR referenced above to Set-PnPTenant. The Get-PnPTenant cmdlet already passes everything there is through CSOM to the output, so nothing we can add there.

**Comment by tasgray** [comment]
> Hi @tasgray. I've added the two in the PR referenced above to Set-PnPTenant. The Get-PnPTenant cmdlet already passes everything there is through CSOM to the output, so nothing we can add there.

Thanks @KoenZomers !!
