### ISSUE TITLE
New-PNPSite with PreferredDataLocation Error using Azure Automate- [BUG]

### ISSUE THREAD

**Issue by cystatto** [pnp/powershell#2629]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Error when executing New-PNPSite with -PreferredDataLocation GBR

### Expected behavior 
Expecting new site to be created within the Geo Location

### Actual behavior 
Creating new site
Creating site in Norway Geo Locaton (NOR)
Provisioning process has FAILED
New-PnPSite : {"error":{"code":"-2147024809, System.ArgumentException","message":"PreferredDataLocation"}}
At line:110 char:16
+ ...  $newsite = New-PnPSite -Type TeamSite -Title $siteTitle -Description ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-PnPSite], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.NewSite

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

$siteTitle = "Test Site"
$siteAlias = "TestSite"
$owner.Email = "Joe@Bloggs.com"
$GeoLocation = "NOR"

$newsite = New-PnPSite -Type TeamSite -Title $siteTitle -Alias $siteAlias -Owners $owner.Email -PreferredDataLocation $GeoLocation

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 1.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [X] Azure Functions
- [ ] Other : please specify

**Comment by nithin-kpr** [comment]
is this issue resolved in the latest version ?

**Comment by veronicageek** [comment]
@cystatto - Can you please update to the latest release 2.1.x however you will need **PS 7.2 or later** to benefit from all the bug fixes and improvements.

PS5 support has been dropped in the new release.

Feel free to reopen if the issue persists. Thanks!
