### ISSUE TITLE
All Documentation going to 404 [BUG]

### ISSUE THREAD

**Issue by kilicantplay** [pnp/powershell#263]
### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting
Unable to view documentation on https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets
Ability to view documentation at https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.
404 - content not found

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)
go to any cmdlet on https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp

![pnp-doc-404-2](https://user-images.githubusercontent.com/44168056/107779291-0e94d680-6d3d-11eb-81f9-337fca6db44f.JPG)
![pnp-doc-404-1](https://user-images.githubusercontent.com/44168056/107779294-0f2d6d00-6d3d-11eb-947b-f3474c80e590.JPG)

**Comment by erwinvanhunen** [comment]
Thank you for reporting this. We are aware of this and have been working throughout the day to restore it. It will take unfortunately longer. Updating content on docs.microsoft.com is unfortunately not a straight forward process.

In the meantime you can find the documentation at https://pnp.github.io/powershell, alternatively in PowerShell itself by issueing for instance:

```powershell
Get-Help Get-PnPList
```
