### ISSUE TITLE
[BUG] - Get-PnPFile - Files present in subsites are being corrupted when downloading using Get-PnPFile

### ISSUE THREAD

**Issue by vidyashankargs93** [pnp/powershell#2630]
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.

### Please confirm what it is that your reporting

“GET-PNP File” is not working as expected for files inside subsites if the subsites are not included in the Connect-PnPOnline command.
In our scenario, we are downloading multiple files from different SharePoint sites/subsites. We are using the below code - 
Example : Connect-PnPOnline -Url "https://www.abc.com/sites/SPOAA1239/" -UseWebLogin -WarningAction SilentlyContinue
Get-PnPFile  -Url "/sites/SPOAA1239/PnPSP/Shared Documents/test3.txt" -Path "C:\Users\ABC\Documents\" -Filename "test3.txt" -AsFile -Force

Here, when we use a subsite (PnPSP in above example), the above code results downloading a corrupt file.

This would work correctly if "**PnPSP**" is included in the ConnectPnPOnline command

In the earlier module i.e, SharepointPnPPowershellOnline V3.26.2010.0, Get-PNPFile action used to work as expected for scenarios where the "Connect-PnP Online" URL points to parent site and the "Get-PnPFile " -Url  points to relative path of the file. (Subsite\library\filename.ext)

### Expected behavior 
Either it should  result in an error or download the file correctly  for scenarios where the "Connect-PnP Online" URL points to parent site and the "Get-PnPFile " -Url  points to relative path of the file. (Subsite\library\filename.ext)

### Actual behavior 
A corrupt file is downloaded of a different size which cannot be used.
<img width="334" alt="image" src="https://user-images.githubusercontent.com/47060628/207038642-d3fa5ffb-4fbd-41fd-8d22-ce84817b115e.png">
Every time, we are seeing a file size of 116KB even though the actual file size is different. (The result was same for large files ~16 MB)
![image](https://user-images.githubusercontent.com/47060628/207043475-0e772a2a-7f72-42cb-95fa-9a78a1bc2b84.png)

### Steps to reproduce behavior
Connect-PnPOnline -Url "https://www.abc.com/sites/SPOAA1239/" -UseWebLogin -WarningAction SilentlyContinue
Get-PnPFile  -Url "/sites/SPOAA1239/PnPSP/Shared Documents/test3.txt" -Path "C:\Users\ABC\Documents\" -Filename "test3.txt" -AsFile -Force

( PnPSp is the subsite in SPOAA1239)

### What is the version of the Cmdlet module you are running?
1.11.0

### Which operating system/environment are you running PnP PowerShell on?
- [ Y ] Windows

**Comment by myatix** [comment]
Is there anyway to get this to work on an older version of PnP.PowerShell?

I have an Azure Function that I use Get-PnPFile to download the Template from a SharePoint Document Library. If I change my host.json file to use pnp.powershell 1.6.0 then I still get this issue?

Are there no work arounds to this issue, even for PowerShell Core 7.0?

**Comment by gautamdsheth** [comment]
This behavior is by design. The implementation behind this has changed quite a lot in this version of PnP PowerShell.

You will need to connect to individual subsites to retrieve files from them.
Connecting to each subsite using `Connect-PnPOnline` is just a matter of switching context. It doesn't ask for prompts again as long as your are in the same session.
