### ISSUE TITLE
Error provisioning document set from provisioning template instance

### ISSUE THREAD

**Issue by in-pv** [pnp/powershell#2635]
## Category

- [x] Bug

**This is an issue when using PowerShell 1.12.0 or Directly using PnP.Framework and PnP.Core 1.8.0 via C#**

We have a site we use as a template for provisioning new sites. The template site has various content types, columns etc. configured for when a certain type of site is required. One of the content types for the template site is a custom Document Set content type, Custom Document Set. After provisioning a new site using either, PnP.PowerShell or via the C# libraries we are unable to create a new Custom Document Set in the newly provisioned site.

**This is only an issue with PnP.PowerShell version 1.12.0 or PnP.Core 1.8.0. If I rollback PnP.PowerShell to 1.11.0 it all works fine and if I rollback to version 1.7.0 of the PnP.Core package in c# it all works fine as well. I had tried to just rollback to version 1.10.0 of the PnP.Framework and left PnP.Core as 1.8.0 but still had the error. When I rolled back to 1.7.0 of the PnP.Core package the error went away**

## Steps to reproduce

1. Create a new site collection and configure a new Document set content type with some custom columns
2. Add the content type to the default Document library
3. Use PnP.PowerShell or c# to get the template instance
4. Provision a new site collection and apply the template instance to the new site collection
5. Navigate to the newly provisioned site and Document library and attempt to create a new custom document set

I am receiving the below error page when doing this

![image](https://user-images.githubusercontent.com/89818679/207205114-20a21ed5-75fb-47c7-bd34-b000df7024b0.png)

## Expected behavior

After provisioning a new site based on the template site we are able to create new documents sets using the custom document set as per normal behavior and as per the template site

## Environment details (*development & target environment*)

- **SDK version**: 1.8.0
- **OS**: Windows 11 for PowerShell and Azure function runtime 4
- **SDK used in**: PowerShell script PnP.PowerShell 1.12.0 and azure function v4 and c# PnP.Framework 1.11.0 and PnP.Core 1.8.0
- **Framework**: .NET 6.0 for the function app
- **Browser(s)**: 
- **Tooling**: VS Code for the PowerShell and Visual Studio Professional 2022

*Thanks for your contribution! Sharing is caring.*

**Comment by in-pv** [comment]
Hi @jansenbe,

I can see you moved this issue to **pnp/powershel**, but this is reproducible when not using PowerShell. I have an azure function purely running C# and we experience the same behavior as stated in the original entry above.

What I @CamHowarthInForm meant to say above is that the NewFormUrl is getting set to **/_layouts/15/SPListForm.aspx?PageType=8** instead of **/_layouts/15/NewDocSet.aspx**

As far as we can see this is an issue when applying the template, regardless of whether we are using PowerShell or purely C#, as we can see that the NewForm URL is correct after getting the template instance but after we apply it to the site the NewForm URL is set **/_layouts/15/SPListForm.aspx?PageType=8** instead of **/_layouts/15/NewDocSet.aspx**.

**Comment by veronicageek** [comment]
@in-pv - Can you please update to the latest 2.1.x (if the issue is still there), however **PS 7.2 or later** is needed to benefit from all the bug fixes and improvements of that new release.

PS5 support has been dropped. 
Feel free to reopen in the appropriate repository if the issue persists. Thanks!

**Comment by joaquinajenjo** [comment]
Hi @veronicageek  I can confirm that this still occurs with the PnP PowerShell version 2.1.1. 

Can be reopened this issue or I have to create new one?

**Comment by veronicageek** [comment]
@in-pv - From your original description it seems this doesn't happen _only_ when using PnP PowerShell. Can you please open it in the appropriate repo (PnP Core or PnP Framework) which we are consuming. So when fixed, it'll also be in PnP PowerShell. Thank you.

**Comment by joaquinajenjo** [comment]
Ok. Thank You.

Meanwhile if someone has this issue can execute this patch to solve the error after applied the template (*replacing "MyDocSetContentTypeName" with your document set content type name)

$clientContext = Get-PnPContext
$targetContentType = Get-PnPContentType -Identity "**MyDocSetContentTypeName**"
$targetContentType.NewFormUrl = "_layouts/15/NewDocSet.aspx"
$targetContentType.Update(1)
$clientContext.ExecuteQuery()

**Comment by diver7** [comment]
> Ok. Thank You.
> 
> Meanwhile if someone has this issue can execute this patch to solve the error after applied the template (*replacing "MyDocSetContentTypeName" with your document set content type name)
> 
> $clientContext = Get-PnPContext $targetContentType = Get-PnPContentType -Identity "**MyDocSetContentTypeName**" $targetContentType.NewFormUrl = "_layouts/15/NewDocSet.aspx" $targetContentType.Update(1) $clientContext.ExecuteQuery()

@joaquinajenjo Thank you so much for posting this workaround/fix! You saved me many hours of troubleshooting.

**Comment by MelanieO365** [comment]
Still having this issue. How come this has not been fixed after all this time? Unable to clone a site with document sets without expensive third party tools...Frustrating
