### ISSUE TITLE
Get-PnPTenantSite: Missing Teams related properties (ex: IsTeamsConnected)

### ISSUE THREAD

**Issue by morgantechspace** [pnp/powershell#2636]
The Get-SPOSite cmdlet now supports the following Teams-related properties that are currently missing in the Get-PnPTenantSite cmdlet.

$Sites = Get-SPOSite
$Sites[0] | Select *Team* | FL

IsTeamsConnected        : False
IsTeamsChannelConnected : False
TeamsChannelType        : None

@wobba @alirobe @jackpoz @erwinvanhunen

**Comment by gautamdsheth** [comment]
hi @morgantechspace , have added these properties to be returned when using Get-PnPTenantSite cmdlet.
It will be available in tomorrow's nightly

**Comment by morgantechspace** [comment]
Thank you

**Comment by morgantechspace** [comment]
> hi @morgantechspace , have added these properties to be returned when using Get-PnPTenantSite cmdlet. It will be available in tomorrow's nightly

Thanks @gautamdsheth
