### ISSUE TITLE
Get-PnPTenantSite Errors With "File Not Found" When Using a URL for the Identity Parameter

### ISSUE THREAD

**Issue by shcrist** [pnp/powershell#2647]
### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

When executing Get-PnPTenantSite with the -Identity parameter as a site URL the action randomly fails with "File Not Found." Continued retries eventually results in the completion of the cmdlet. Using the -Filter parameter with the Url -eq <SiteUrl> returns the object. Running Get-PnPTenantSite with only the -Connection parameter returns all sites and included the site which fails with the -Identity parameter.

### Expected behavior 
The cmdlet should return the site object.
![image](https://user-images.githubusercontent.com/32545974/207365705-07d08cc7-9973-4a5d-bf27-8fc237a266ee.png)

### Actual behavior 
![image](https://user-images.githubusercontent.com/32545974/207366037-28a26420-b50c-4aab-83af-49a87678b561.png)

PnPLog Output:

powershell_ise.exe Error: 0 : 2022-12-13 13:15:55.6186	[PnP.Framework]	[0]	[Error]	ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerException: Cannot get site https://???.sharepoint.com/sites/TestCreate5.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__6.MoveNext()
ServerErrorCode: -1
ServerErrorTypeName: Microsoft.Online.SharePoint.Common.SpoNoSiteException
ServerErrorTraceCorrelationId: d7dc81a0-30b8-2000-e499-440b63f95009
ServerErrorValue: 
ServerErrorDetails: 
.	0ms	

### Steps to reproduce behavior
$HostUrl = "https://???-admin.sharepoint.com/"
$strURL = "https://???.sharepoint.com/sites/TestCreate5"

Connect-PnPOnline -Interactive  -Url $HostUrl | Out-Null
$ConnHost = Get-PnPConnection
Get-PnPTenantSite -Connection $ConnHost -Identity $strURL

### What is the version of the Cmdlet module you are running?
1.11.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by myatix** [comment]
I am also having this issue!

**Comment by shcrist** [comment]
No. It still happens. More frequently than I'm comfortable with.

**Comment by gautamdsheth** [comment]
@shcrist - does this happen for all sites or just some site collections or maybe just one specific site collection ? Seems like some server side issue. Can you also maybe try on another tenant as well if possible ?

**Comment by shcrist** [comment]
@gautamdsheth It happens for all sites, just not all of the time. I moved the solution to a DoD tenant and I'm seeing the same behavior. It was working fine until about two months ago. If it's the underlying CSOM creating the issue, then I have to wonder if there wasn't an update around that time. It's essentially made this functionality so unreliable that I can't use it.

**Comment by KoenZomers** [comment]
I ran this line here which effectively will do an -Identity call for each of the site collections in my tenant (OneDrives excluded) and none of them throws an error:

```
Get-PnPTenantSite | % { Get-PnPTenantSite -Identity $_.Url }
```

Does this issue still occur for you? There doesn't seem to be anything on the PnP PowerShell side wrong with this one. Perhaps it was a server issue, perhaps there was some corruption in the hidden lists within the SharePoint Online admin center? I believe  they've been doing some changes to those lists around that time. Perhaps those could have temporarily interfered with this?

**Comment by shcrist** [comment]
I'll give it a try tomorrow and see if I'm still seeing it.

Shaun Crist

Senior Consultant
SharePoint
Microsoft Federal
Office: 803 669-0074
***@***.******@***.***>
***@***.***  ***@***.*** ***@***.*** ***@***.*** ***@***.*** ***@***.***

**Comment by shcrist** [comment]
It seems to be working as expected again. The only thing I can figure is there was a problem with CSOM in the environment.
