### ISSUE TITLE
Get-PnPSubscribeSharePointNewsDigest sometimes returns an error

### ISSUE THREAD

**Issue by AndyDeltion** [pnp/powershell#2659]
### Reporting an Issue or Missing Feature
Get-PnPSubscribeSharePointNewsDigest sometimes returns an error

### Expected behavior 
Get-PnPSubscribeSharePointNewsDigest is expected to return a true or false value
![image](https://user-images.githubusercontent.com/119966178/208144973-7cffb9e5-fbad-44ab-8df2-421ff551c374.png)

### Actual behavior 
This error message appears for some users:
Get-PnPSubscribeSharePointNewsDigest : String does not contain a matching element
![image](https://user-images.githubusercontent.com/119966178/208144790-8bc114cb-2496-4485-b237-659d60d6019a.png)

### Steps to reproduce behavior
_Connect to site:
#Site Variables
$SiteURL = *************
     
 #Connect to PnP Online
Connect-PnPOnline -Url $SiteURL -Interactive

Get-PnPSubscribeSharePointNewsDigest -Account *user email*_

### What is the version of the Cmdlet module you are running?
ModuleType Version
Manifest       1.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows

**Comment by ykuijs** [comment]
Translated error is: `Get-PnPSubscribeSharePointNewsDigest : Sequence contains no matching element`

Verbose output shows this:
```
VERBOSE: Encoding user account admin@M365x76296972.onmicrosoft.com
VERBOSE: Retrieving user profile for i:0#.f|membership|admin@tenant.onmicrosoft.com
VERBOSE: Connecting to OneDrive for Business site at [https://tenant-my.sharepoint.com/personal/admin_tenant_onmicrosoft_com/](https://tenant-my.sharepoint.com/personal/admin_tenant_onmicrosoft_com/?xsdata=MDV8MDF8fDBjZDliNmNiYTcwZTQ2NjI1ZTA3MDhkYWQ3YTBmZDIxfDcyZjk4OGJmODZmMTQxYWY5MWFiMmQ3Y2QwMTFkYjQ3fDB8MHw2MzgwNTkzODM2Njc5MTMwOTh8VW5rbm93bnxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxNVFkzTURNME1UVTJOVGMxT0RzeE5qY3dNelF4TlRZMU56VTRPekU1T2pKa016QXlaR1k1TFdJNU5HSXRORFpqTVMwNVpqQXpMV1JpWkRWbU4yRTVZekl6TUY5aFpEUXpObU01TUMwM04yRXdMVFE1TmpVdFlqRXpaaTAwWlRrMU9UaG1ZemxtWXpaQWRXNXhMbWRpYkM1emNHRmpaWE09fDhiNGZkZmM2NjZkNTRhNGVmYzhhMDhkYWQ3YTBmZDIwfGIyM2U3MmEzYzExMzQ4MjE4YjNlYmJjODY2ZjAyYmEz&sdata=U016U1d3THJQMUdDTm9mUGFwUTlYc3puZ3cxa3FuZDNxa01TTWw0cE1rcz0%3D&ovuser=72f988bf-86f1-41af-91ab-2d7cd011db47%2Cykuijs%40microsoft.com)
VERBOSE: Retrieving notificationSubscriptionHiddenList list
```

When checking with Get-PnPList, I cannot find the notificationSubscriptionHiddenList list anywhere on accounts where the error is shown. I think the error is generated here: https://github.com/pnp/powershell/blob/d40f509776427c5099576e7f0cde495559e10c53/src/Commands/UserProfiles/GetSubscribeSharePointNewsDigest.cs#L39-L48

It looks like the settings are no longer stored here. Today I received a digest mail and did some further checking. The link at the bottom of the mail links to here: https://tenant.sharepoint.com/_layouts/15/sharepoint.aspx/emailNotificationSettings, where a setting "Digests of news posts you've missed" is found. Where toggling this setting, calls to this URL are made https://tenant-my.sharepoint.com/_api/v2.0/me/drive/root/subscriptions/email_unsubscribe_AutoNewsDigest

**Comment by KoenZomers** [comment]
Thanks for providing this info. It's a bit more complex than I hoped for to fix this. I'll try to fix this over the Christmas period.

**Comment by KoenZomers** [comment]
I spent quite some hours on trying to get this to work, but have to conclude it can no longer be done. The API behaves too weirdly and doesn't seem to be made to be called directly. The user interface also has changed again in the meantime. It's too unreliable. Sorry, this cannot be done. I will remove the cmdlet from PnP PowerShell to avoid confusion for others.

**Comment by KoenZomers** [comment]
Please file a Design Change Request with Microsoft and ask for a public API through Microsoft Graph to change this setting, if you really need this functionality. If your request will be honored, we can implement it again.
