### ISSUE TITLE
List Required Permissions[FEATURE]

### ISSUE THREAD

**Issue by riverrafter** [pnp/powershell#2660]
Would it be possible to add the Required Permissions for Get-PnPUser and Get-PnPGroup Documentation, similar to what is listed in GetPnPAzureADGroup? It seems more permissions are needed than just User.Read.All for example, so it would be nice to know exactly how much to give without a trial and error shotgun approach. Thank you.

**Comment by KoenZomers** [comment]
I like the idea @riverrafter but the challenge with this is that there is no such documentation available unfortunately. It would be case of trial and error to find out the minimal needed permissions, which is time consuming. If you happen to go through the exercise of doing this and find out about the minimal permissions, I'll be more than happy to add this information to the documentation so to help others. I cannot unfortunately proactively do this on all cmdlets.

**Comment by KoenZomers** [comment]
Closing as there are no further steps we can take with this for now.
