### ISSUE TITLE
Console logging not supported

### ISSUE THREAD

**Issue by erwinvanhunen** [pnp/powershell#267]
Slowly updating my PNPs script to use this Core version of PNP.

When I set my command
```ps
Set-PnPTraceLog -On -Level:Debug
```
I get the error message "WARNING: Console logging not supported"

Even trying the command
```ps
Set-PnPTraceLog -On -Level:Debug -WriteToConsole
```
I still get the error message.

Has this functionality been removed in the new version of PNP?

_Originally posted by @pmatthews05 in https://github.com/pnp/powershell/discussions/258_

**Comment by pmatthews05** [comment]
@erwinvanhunen thanks. Didn't realise there was a file logging option until you mentioned it to me in the discussion thread. 

Hope writing to the console isn't a limitation with .NET core, as it's very useful seeing the logs displayed on the screen in devops pipelines, and while developing when running Invoke-PnPSiteTemplate, especially if it falls over.

**Comment by erwinvanhunen** [comment]
We re-enabled console logging. It will be available in the 1.3.7-nightly build tomorrow.

**Comment by pmatthews05** [comment]
Thanks. I will test this Friday.

**Comment by pmatthews05** [comment]
Hi @erwinvanhunen a bit later than expected to reply. But I have tested this today and can see console results.

Thank you.
