### ISSUE TITLE
[BUG] Set-PnPWebHeader -HeaderBackgroundImageUrl Does not set the image

### ISSUE THREAD

**Issue by LucaSchildi** [pnp/powershell#2671]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.

Set-PnPWebHeader
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
Function itself
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

The command:
"Set-PnPWebHeader -HeaderBackgroundImageUrl "https://XXX.sharepoint.com/sites/GLOBAL_ASSETS/assets/Banner/XXX_banner.jpg" -HeaderLayout Extended"

![image](https://user-images.githubusercontent.com/44604808/208899327-b5261498-12e2-49a9-95f6-72da42af7cfd.png)

Does not set the corresponding background image. Instead the Header is extended and has "no" image which links to:
"https://XXX.sharepoint.com/_vti_bin/https%3a%2f%2fXXX.sharepoint.com%2fsites%2fGLOBAL_ASSETS%2fassets%2fBanner%2fXXX_banner.jpg"

Which would be correct except for the "_vti_bin". 

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

Expected the image to be set as header backgroup. The same command does for for the logo 

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

Does not set the corresponding background image. Instead the Header is extended and has "no" image which links to:
"https://XXX.sharepoint.com/_vti_bin/https%3a%2f%2fXXX.sharepoint.com%2fsites%2fGLOBAL_ASSETS%2fassets%2fBanner%2fXXX_banner.jpg"

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
1.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [x ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by KoenZomers** [comment]
The parameter takes a server relative image URL, not a full SharePoint URL as mentioned in the documentation:
https://pnp.github.io/powershell/cmdlets/Set-PnPWebHeader.html#-headerbackgroundimageurl

Can you try it again with a server relative URL path and see if that works for you?

**Comment by LucaSchildi** [comment]
Yes, it does work when the image file is on the same site i am applying the settings to. 

Might me a limitation of SharePoint Online then. Strange that it's supported for the Logo but not for the Background...
I don't know why one should use a global asset library then, but okay :D

**Comment by KoenZomers** [comment]
Agree, its a bit odd. Perhaps throw it into the [feedback bucket](https://feedbackportal.microsoft.com/feedback/forum/06735c62-321c-ec11-b6e7-0022481f8472) and see if it will be picked up?

**Comment by gmustafa007** [comment]
I am trying to set the header using Set-PnPWebHeader -HeaderBackgroundImageUrl but just could not make the image appear.

The image sits in the assets library of the same site I am applying the header to and the connected account has full access to the site/images. Verified that applying the image manually does work but not through this command. 

Any help will be appreciated. 

Get-PnPWebHeader result:
SiteLogoUrl              : https://somesite.sharepoint.com/sites/Site Create 23/SiteAssets/image62x62.jpg
HeaderLayout             : Extended
HeaderEmphasis           : None
HideTitleInHeader        : False
HeaderBackgroundImageUrl : /sites/Site Create 23/SiteAssets/header_v2.jpg
LogoAlignment            : Left
