### ISSUE TITLE
Broken link on documentation of Get-PnPSiteTemplate

### ISSUE THREAD

**Issue by rohit404404** [pnp/powershell#2675]
Handler parameter refers to docs link which is broken

[Get-PnPSiteTemplate](https://github.com/pnp/powershell/blob/dev/documentation/Get-PnPSiteTemplate.md#-handlers)

Broken Link => https://docs.microsoft.com/dotnet/api/officedevpnp.core.framework.provisioning.model.handlers

**Comment by gautamdsheth** [comment]
Can you please raise an issue here: https://github.com/SharePoint/sp-dev-docs ?

These docs are located in a separate repository which is owned by Microsoft. We can't fix it here.
