### ISSUE TITLE
[BUG] ListItemAllFields property is empty

### ISSUE THREAD

**Issue by openstepsmaarten** [pnp/powershell#2679]
### Reporting an Issue or Missing Feature
I no longer can get the metadata of a SharePoint folder or file by calling the property ListItemAllFields. The resulting list is empty.

### Expected behavior 
I was expecting at least the ID of the folder to be returned, along with the title and GUID.

### Actual behavior 
The properties ID. Title and GUID seem to be empty:

![afbeelding](https://user-images.githubusercontent.com/121292274/209326150-fab504c5-8e9e-4bc8-a805-061f75342419.png)

### Steps to reproduce behavior
`Connect-PnPOnline -url $url -Credentials $Credentials`
`$Folder = Resolve-PnPFolder -SiteRelativePath $PathToFolder`
`$Folder.ListItemAllFields`

### What is the version of the Cmdlet module you are running?
1.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
hi @openstepsmaarten , this is by design.
You will need to explicitly request/load the properties.

Something like this:

```
$Folder = Get-PnPFolder -Url $FolderServerRelativeURL -Includes ListItemAllFields
```
