### ISSUE TITLE
Set-PnPFolderPermission : File Not Found

### ISSUE THREAD

**Issue by wil16098** [pnp/powershell#2680]
### Discussed in https://github.com/pnp/powershell/discussions/2667

<div type='discussions-op-text'>

<sup>Originally posted by **wil16098** December 20, 2022</sup>
I appear to be correctly connected to the following services as a Global Administrator:
```
Connect-SPOService -Url https://$clientOrg-admin.sharepoint.com
Connect-PnPOnline -Url https://$clientOrg.sharepoint.com/sites/Files -Interactive
Connect-AzureAD
Connect-MicrosoftTeams
```

Get-PnPContext appears to show I am connected to the "Files" communication site correctly:
`Url                          : https://[tenantname].sharepoint.com/sites/files`

I am attempting the following command:
`Set-PnPFolderPermission -List "Advanced" -Identity "Training" -Group "Training Team" -AddRole "Edit"`

I get a "File Not Found" error:
```
Set-PnPFolderPermission : File Not Found.
At line:1 char:1
+ Set-PnPFolderPermission -List Advanced -Identity "Training" -Group "T ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Set-PnPFolderPermission], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.Files.SetFolderPermission
```

Get-PnPList  appears to show the Advanced Document Library is present:
```
Title                 Id                                   Url                                  
-----                 --                                   ---                                  
Advanced              2764a050-2316-41f4-4388-7a132643bcd1 /sites/Files/Advanced
```

Get-PnPFolder -List "Advanced"  #shows the folder "Training" and its subfolder are present:
```
Name                               Type   Items/Size Last Modified         
----                               ----   ---------- -------------         
Training                           Folder          1 12/20/2022 11:35:44 AM
Z - Training Admins                Folder          0 12/19/2022 11:26:40 AM
```

Get-PnPGroup does not list the MS Team "Training" (which does exist). This has me concerned but doesn't appear to match the error I am getting.
```
Id Title          LoginName     
-- -----          ---------     
5  Files Members  Files Members 
3  Files Owners   Files Owners  
4  Files Visitors Files Visitors
```

Any insights into this error and why I am getting this unexpected result appreciated. My Global Admin account is the primary owner of the Files site. 
</div>

**Comment by Countfox772** [comment]
I had the same error

**Comment by USCloud-EricWilborn** [comment]
Seeing the same issue occasionally with trying to add permissions to newly created SPO sites. Noticed that when we try to go to the URL specified as a parameter, the page loads in Edge with "?sw=bypass" appended to the URL on first load. After visiting the page we were able to permission via PnP calls. Can't find rhyme nor reason as to when/why "?sw=bypass" gets appended to the URL.

**Comment by veronicageek** [comment]
@wil16098 

`Get-PnPGroup does not list the MS Team "Training" (which does exist)`

You mention "MS Team",  but the`Get-PnPGroup` cmdlet will list the **SharePoint** groups. Is "Training" a SPO group? I'm confused between your groups or folders named "training".

**Comment by dantshin** [comment]
I am having the same error - but just last week, the same commands worked without fail (I checked my command history, to make sure I'm issuing the same exact command).
I am using site collection admin. Get-PnPFolder lists the folder I want to touch. I tried Set-PnPFolderPermission with another folder, with the same failure result.

**Comment by milosbabovic** [comment]
I have the same error right now.

**Comment by milosbabovic** [comment]
Solved by using "/" in Indentity string - instead of in-documentation mentioned "\".

**Comment by veronicageek** [comment]
Closing as no response from the author. 
@dantshin - If your problem persists, can you please open a **new** issue with your description/details. Thanks

**Comment by dantshin** [comment]
Problem is resolved now - I was successful in changing the folder permission (for a list that has folders) by ensuring the Identity included "Lists/[ListName]".
Perhaps the documentation can be updated with this specificity.

**Comment by wil16098** [comment]
> @wil16098
> 
> `Get-PnPGroup does not list the MS Team "Training" (which does exist)`
> 
> You mention "MS Team", but the`Get-PnPGroup` cmdlet will list the **SharePoint** groups. Is "Training" a SPO group? I'm confused between your groups or folders named "training".

@veronicageek  Thank you. I watched this like a hawk for the first month or so, changed my email address for github login, and promptly lost the incoming responses. I really appreciate the feedback!

To answer your question, one of our goals is to assign MS Teams members and members of Azure AD Security Groups to file and folder permissions in SharePoint, which is possible through the UI.

Currently, this does not seem to be working for me. This example using a SharePoint Group works:
`Set-PnPFolderPermission -List "$library" -Group "Files Visitors" -AddRole "Edit" -Identity "$library/$folder"`

But these examples using a MS Team and an Azure AD Group (respectively) do not:
```
Set-PnPFolderPermission -List "$library" -Group "$folder Team Members" -AddRole "Edit" -Identity "$library/$folder"
Set-PnPFolderPermission -List "$library" -Group "AADSG-$($folder)Admins" -AddRole "Edit" -Identity "$library/$folder"
```
Both the Team in question and the Azure AD Group in question exist. Both the Team and the Azure AD Group can be added and given permissions in the UI. Attempting to add via the example commands above gives an error. Example error:
```
Set-PnPFolderPermission : Group cannot be found.
At line:1 char:1
+ Set-PnPFolderPermission -List "$library" -Group "AADSG-$($folder)Admi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Set-PnPFolderPermission], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.Files.SetFolderPermission
```

Does that help clarify? From your comment, I take it only SharePoint Groups are allowed and MS Team and Azure AD Group permissions must be added manually? If there is a good way to accomplish this within a script, I would be pleased to have any hints :)

Regarding the File Not Found error that was the original question. I am open to feedback, but further experimentation left me with this:
Two issues to keep in mind:
1. When running a script, after the creation of a site or document library, put in a 30+-second pause. Sometimes, it is just lagging and hasn't fully created yet (ie - you can't add a DL to a Site if the Site hasn't had a few extra seconds to 'take'). Wondering if this is the source of @USCloud-EricWilborn's experience? 
2. The -Identity part of Set-PnPFolderPermission must contain both the list name and target folder name in the path. Thus:
`-Identity "$library/$folder"`
works, but:
`-Identity "$folder"`
does not. @dantshin noted this as well.

Those two enhancements appear to have solved my File Not Found error. Now just figuring out how to automate permissions for MS Teams and Azure AD Groups!
