### ISSUE TITLE
Development Containers for PnP.PowerShell Contributors

### ISSUE THREAD

**Issue by shurick81** [pnp/powershell#2683]
**Is your feature request related to a problem? Please describe.**
As a contributor of PnP.PowerShell codebase, I want to have defined Development Containers so I don't need to install any dependency locally on my development machine.

**Describe the solution you'd like**
.devcontainer defined

**Describe alternatives you've considered**
Definite way to preinstall all the prerequisites that needed for contributing to the product.

**Additional context**

**Comment by shurick81** [comment]
@gautamdsheth let's continue the discussion that we started in #2003?. First of all, thanks for the explanation. I still have a question however. I noticed that some of the contributor scenarios might need preinstalling some tools that contributor might want to use for committing with excellent quality. For example, docfx might be needed for building and testing pages before committing them to the code base: https://github.com/pnp/powershell/blob/dev/pages/Build-Site.ps1. The question is whether there are any other tools that a contributor might need? Maybe some testing frameworks like Pester, etc.? PlatyPS is needed for some cases? Anything else you might think of? Let's imagine that you just have a new Windows machine with Visual Studio Code and Git. What should a contributor install before we can say that this environment is ready for developing PnP.PowerShell module? Thanks in advance!

**Comment by gautamdsheth** [comment]
hi @shurick81 , so besides VS code , Git and PlatyPS, we will just require PowerShell 7.2.x or later. We dont require Pester, don't have many tests as such.

Having said that, we dont necessarily require Windows machine. It will run even on Ubuntu, Mac or some other linux machine as well.
