### ISSUE TITLE
Get-PnPList Error in Azure Function App, Error: No list found with id, title or url

### ISSUE THREAD

**Issue by myatix** [pnp/powershell#2690]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

### Reporting an Issue or Missing Feature
When I try to run the following code on my local machine I have no issue the list is returned but as soon as I put this code into a Function App I get the following error:

**Code runs without issue on local client:**
```
   $webUrl = "https://xxx.sharepoint.com/sites/Test2023"
   $templateSiteUrl = "https://xxx.sharepoint.com/sites/SPOSiteProvisioning"
   $siteDirList = "Site Directory"
    
   $webConnect = Connect-PnPOnline -Url $webUrl -Interactive
   $tplSiteConnect = Connect-PnPOnline -Url $templateSiteUrl -Interactive

    write-host -f Cyan "Logging Site information in Site Directory for" $webUrl
    $Web = Get-PnPWeb -Connection $webConnect
    write-output $web
    $list = Get-PnPList -identity $siteDirList -Connection $tplSiteConnect -ThrowExceptionIfListNotFound -ErrorAction Stop
    write-output $list
    if ($webUrl -ne $null) {
      $item = @{}
      $item = @{
          "Title" = $Web.Title;
          "URL" = $Web.URL;
          "SiteDescription" = $Web.Description;
      }
      Add-PnPListItem -List $list -Values $item -Connection $tplSiteConnect
  }
```

**Code fails in functionApp PowerShell Core 7.0**

```
    $siteDirList = "Site Directory"
    write-host -f Cyan "Logging Site information in Site Directory for" $webUrl
    $Web = Get-PnPWeb -Connection $webConnect
    write-host "Web Details:" $web.Title
    $list = Get-PnPList -identity $siteDirList -Connection $tplSiteConnect -ThrowExceptionIfListNotFound -ErrorAction Stop
    write-host "List details" $list
if ($webUrl -ne $null) {
    $item = @{}
    $item = @{
        "Title" = $Web.Title;
        "URL" = $Web.URL;
        "SiteDescription" = $Web.Description;
    }
    $addItem = Add-PnPListItem -List $list -Values $item -Connection $tplSiteConnect
}
```

### Expected behavior 
I would expect the Get-PnPList to return the list...

### Actual behavior 

 [Information]   INFORMATION: Error: No list found with id, title or url 'Site Directory'

### Steps to reproduce behavior

**Function App Config**

![image](https://user-images.githubusercontent.com/48433526/210233852-e9b657c6-a242-4947-aeca-803dcce60509.png)

Runtime version ~4

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 1.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [x] Azure Functions
- [ ] Other : please specify

**Comment by KoenZomers** [comment]
Since the last two versions we've made a change to the code where Connect-PnPOnline no longer returns an instance of the connection unless you explicitly add -ReturnConnection to your statement. I notice this line in your script:

```
   $webConnect = Connect-PnPOnline -Url $webUrl -Interactive
```

Here $webConnect should be NULL. Can you change it to the following and see if that resolves it for you:

```
   $webConnect = Connect-PnPOnline -Url $webUrl -Interactive -ReturnConnection
```

**Comment by BaronSparky** [comment]
Perhaps I am wrong, but can you even do an `-Interactive` connection from an Azure function?

I thought you would have to provide the credentials non-interactively, i.e. via an App Registration. or user details held in a KeyVault, etc.

**Comment by KoenZomers** [comment]
Very good point @BaronSparky, didn't even think about that. There is no interactivity possible in Azure Functions indeed. Try using a non interactive method instead.

**Comment by myatix** [comment]
> Perhaps I am wrong, but can you even do an `-Interactive` connection from an Azure function?
> 
> I thought you would have to provide the credentials non-interactively, i.e. via an App Registration. or user details held in a KeyVault, etc.

Thanks for the reply! Yes I am aware that “-interactive” only works on my local client as stated above. That was the working code that succeeded on the client!

My issue was that I hadn’t included the “-returnconnection“

Thanks again!
