### ISSUE TITLE
[BUG] - Export-PnPTermGroupToXml and Import-PnPTermGroupFromXml not working for pinned terms

### ISSUE THREAD

**Issue by natpdeee** [pnp/powershell#2691]
### Reporting an Issue or Missing Feature
Pinned terms are not being handled in the Export-PnPTermGroupToXml. It is working for reused terms, but not pinned terms.

### Expected behavior 
Pinned Terms are being pinned correctly.

### Actual behavior 
The terms are not being pinned correctly in the target term set.

### Steps to reproduce behavior
1. Create a Term Set and add a Term.
2. Create another Term Set and pinned the term from the step 1 to the current Terms
3. Export-PnPTermGroupToXml -Out test.xml 
4. Import-PnPTermGroupFromXml -Path .\test.xml

### What is the version of the Cmdlet module you are running?
1.11.102

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@natpdeee  - Can you please update to the latest release 2.1.x however you will need **PS 7.2 or later** to benefit from all the bug fixes and improvements, and let us know.

PS5 support has been dropped in the new release. Thanks

**Comment by veronicageek** [comment]
Closing as no response.

**Comment by natpdeee** [comment]
Hi @veronicageek ,

I am now using 2.1.64-nightly release in PS  7.3.4 and still got the same issue. Can you confirm whether IsPinned ([documentation](https://github.com/pnp/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2022-09.md#term)) is supported when Exporting and Importing term groups?

![image](https://github.com/pnp/powershell/assets/20945009/85522cc7-c4ec-4d8e-bcc5-7f2163fc5ea8)
