### ISSUE TITLE
Set-PnPTenantCdnEnabled : The method or operation is not implemented.

### ISSUE THREAD

**Issue by LouFarho** [pnp/powershell#270]
### Reporting an Issue or Missing Feature
Set-PnPTenantCdnEnabled : The method or operation is not implemented.

### Expected behavior 
CDN is set based on CDN Type 
Tried all three options Both and Private are broken

### Actual behavior 
Set-PnPTenantCdnEnabled : The method or operation is not implemented.
At C:\MyOneDrive\OneDrive\PowerShell\SPO\NPPD\TurnOnCDN.ps1:22 char:1
+ Set-PnPTenantCdnEnabled -CdnType Private -Enable $true
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPTenantCdnEnabled], ServerException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Admin.SetTenantCdnEnabled

In addition, the Get-PnPTenantCdnEnabled  for Private is broken

Get-PnPTenantCdnEnabled : The method or operation is not implemented.
At line:1 char:1
+ Get-PnPTenantCdnEnabled -CdnType Private
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPTenantCdnEnabled], ServerException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Admin.GetTenantCdnEnabled

### Steps to reproduce behavior
Set-PnPTenantCdnEnabled -CdnType Private -Enable $true
Set-PnPTenantCdnEnabled -CdnType Both -Enable $true

Get-PnPTenantCdnEnabled -CdnType Private

Public does work

### What is the version of the Cmdlet module you are running?
Name           Version
----           -------
PnP.PowerShell 1.3.0  

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
Hi! As I am not having any problems running the cmdlets as you stated, I have a few questions:

How do you connect with Connect-PnPOnline?
The account you use, does it have Tenant admin rights?

**Comment by LouFarho** [comment]
Hi Erwin,
I have tried the -Interactive and -UseWebLogin

I am connecting to the SharePoint Admin URL. The tenant is enforcing MFA.

Lou


C:\WINDOWS\system32> C:\MyOneDrive\OneDrive\PowerShell\SPO\TurnOnCDN.ps1
WARNING: Consider using -Interactive instead, which provides better functionality. See the documentation at https://pnp.github.io/powershell/cmdlets/connect-pnponline.html#interactive-login-for-mult
i-factor-authentication
Set-PnPTenantCdnEnabled : The method or operation is not implemented.
At C:\MyOneDrive\OneDrive\PowerShell\SPO\TurnOnCDN.ps1:22 char:1
+ Set-PnPTenantCdnEnabled -CdnType Private -Enable $true
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPTenantCdnEnabled], ServerException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Admin.SetTenantCdnEnabled

[/] C:\WINDOWS\system32> C:\MyOneDrive\OneDrive\PowerShell\SPO\TurnOnCDN.ps1
Set-PnPTenantCdnEnabled : The method or operation is not implemented.
At C:\MyOneDrive\OneDrive\PowerShell\SPO\TurnOnCDN.ps1:22 char:1
+ Set-PnPTenantCdnEnabled -CdnType Private -Enable $true
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPTenantCdnEnabled], ServerException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Admin.SetTenantCdnEnabled

[/] C:\WINDOWS\system32>

**Comment by erwinvanhunen** [comment]
With G3 Tenant you mean a tenant in the GCC cloud?

**Comment by erwinvanhunen** [comment]
Update: we found out what the reason is: a G3 tenant is indeed located in the GCC cloud and the Office 365 CDN is not supported in those environments, which would explain the error message you receive (see the first note on the page):

https://docs.microsoft.com/en-us/microsoft-365/enterprise/office-365-cdn-quickstart?view=o365-worldwide

There is unfortunately no way for us to recognize the type of tenant, this information is not being disclosed through the APIs we can call, and as a result there is no way to 'catch' this exception gracefully.

**Comment by erwinvanhunen** [comment]
I will close this issue as there is unfortunately nothing we can do to fix this.

**Comment by LouFarho** [comment]
Okay, thanks for the update!
