### ISSUE TITLE
[BUG] Typo in Send-PnPMail

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/powershell#2712]
Isn't it a typo that example 1 for Send-PnPMail is 

_Send-PnPMail -To address@tenant.sharepointonline.com -Subject test -Body test_

I guess it should have been 

Send-PnPMail -To address@tenant.onmicrosoft.com -Subject test -Body test   ??

**Comment by KoenZomers** [comment]
Correctly noticed @kasperbolarsen . I've updated the documentation. Thanks!
