### ISSUE TITLE
Non-functional control of MS Teams using PNP.

### ISSUE THREAD

**Issue by MilanVolf** [pnp/powershell#2713]
### Discussed in https://github.com/pnp/powershell/discussions/2686

<div type='discussions-op-text'>

<sup>Originally posted by **MilanVolf** December 12, 2022</sup>
### Notice
Sometime after October, when I ran the script for the last time, MS Teams and PNP administration stopped working. When I log in using Connect-PnPOnline and using the "AccessToken" or "CertificatePath" certificate, I cannot use the commands related to controlling MS Teams. i always get the error: "UnknownError"

If I log in manually using PnPOnline and perhaps "DeviceLogin", the commands for MS Teams administration work as before. Unfortunately, this style of administration cannot be automated, as the admin always has to enter login information.

Other than that, there was no change in my environment, both in the configuration of the MS environment and the change in the script.

Thank you for your help.

### Reporting an Issue or Missing Feature
Issue
I don't know if this is a bug or a major change.

### Expected behavior 
Token or certificate credentials to work again for the MS Teams service.

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

### Steps to reproduce behavior
ERROR:
```
Connect-PnPOnline -Url "https://xxxxxxxx-admin.sharepoint.com/" -AccessToken $token
Get-PnPTeamsTeam

Get-PnPTeamsTeam : UnknownError
At line:1 char:1
+ Get-PnPTeamsTeam
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-PnPTeamsTeam], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.Graph.GetTeamsTeam

```

During testing I got this error once:
`Get-PnPTeamsTeam : Failed to execute backend request.`

Functional demo:
```
Connect-PnPOnline -Url "https://xxxxxxxx-admin.sharepoint.com/" -DeviceLogin
Get-PnPTeamsTeam

GroupId                              DisplayName      Visibility       IsArchived MailNickname
-------                              -----------      ----------       ---------- ------------
xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx ZS 1011          HiddenMembership True       ZS1011
xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx ZS 1012          HiddenMembership True       ZS1012
```

### What is the version of the Cmdlet module you are running?
1.12.0 and 1.11.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
</div>

**Comment by KoenZomers** [comment]
It works fine here. What method do you use to get the access token? Did you validate using i.e. https://jwt.ms that this token is for Microsoft Graph and contains the needed permissions?

**Comment by MilanVolf** [comment]
@KoenZomers 

Thanks for advice. this really helped me a lot.
The problem was with permissions. But paradoxically, not with insufficient, but that I had set it much more in Azure.
I deleted the current permission and set up just a few things to make it work according to the Teams documentation. Teams is currently working.

``
Get-PNPList
Get-PNPList : The remote server returned an error: (401) Unverified.
At line:1 char:1
+ Get-PNPList
+ ~~~~~~~~~~~
     + CategoryInfo : InvalidOperation: (:) [Get-PnPList], PSInvalidOperationException
     + FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.Lists.GetList
``

Now the permission for Get-PNPList broke for me, unfortunately the documentation is not very shareable and I have no idea what to set for it. Do you have any idea?

Thank you for your help.

**Comment by KoenZomers** [comment]
Interesting. There should not be a thing such as "too many permissions". Perhaps some of them weren't admin approved yet the first time?

**Comment by MilanVolf** [comment]
Everything was immediately and correctly approved after being added. I had about the maximum possible number of permissions set. AAD did not allow me to add more permissions. That was something around 400 pcs.

But according to the token probe address I had significantly less permissions than what was set in AAD.

So I deleted everything and set really used only. And everything started working. Even the address on the token verification showed the correct number of permissions.
