### ISSUE TITLE
Assembly Error When Connecting in Remote Session

### ISSUE THREAD

**Issue by JAK1047** [pnp/powershell#2715]
### Reporting an Issue or Missing Feature
Not sure if this is considered a framework issue or not. When connecting to a Remote Powershell session and trying to connect to our SPO admin URL via application authentication with a certificate I receive a missing assembly error. If I RDP directly to the server and run the same cmd it runs as expected. This is on Powershell 7.2.8 on Server Core 2022.

### Expected behavior 
Connection succeeds

### Actual behavior 
Could not load file or assembly 'PnP.PowerShell.ALC, Version=1.12.58.0, Culture=neutral, PublicKeyToken=null'. Uncaught exception during type initialization. (0x80131534)

![image](https://user-images.githubusercontent.com/29665481/211589623-d496c47f-fe35-4841-a96f-d4b47b4431be.png)

### Steps to reproduce behavior
```powershell
$Thumbprint = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
$ClientID = 'XXXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'
Connect-PnPOnline -Url 'contoso-admin.sharepoint.com' -Thumbprint $Thumbprint -ClientId $ClientID -Tenant 'contoso.com'
```

### What is the version of the Cmdlet module you are running?
![image](https://user-images.githubusercontent.com/29665481/211590285-d58be559-dad2-4ca2-9df1-58bb2a0113a8.png)
(I've also tried the latest non-nightly build)

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
hi @JAK1047 , can you please give it a try with the latest nightly builds and let us know ? We bumped quite a few dependencies , maybe will help in your environment ?

**Comment by JAK1047** [comment]
Yep looks like 2.0 updates things like the Microsoft.Identity.Client DLL to 4.50 from the 4.36 it had which solves the conflict loading. No longer got any errors.

**Comment by gautamdsheth** [comment]
Thanks for confirming and letting us know.

closing it as fixed
