### ISSUE TITLE
[FEATURE] Make Get-PnPMicrosoft365Group Return GAL

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#2722]
**Is your feature request related to a problem? Please describe.**
It would be great to have `Get-PnPMicrosoft365Group` return GAL visibility ('HiddenFromGlobalAddressListsEnabled' attribute)
 
**Describe the solution you'd like**
As of now `Set-PnPMicrosoft365Group` allows to manage GAL visibility for Unified groups with ` HiddenFromGlobalAddressLists` parameter, however, it seems there is no way to retrieve current state for GAL visibility with `Get-PnPMicrosoft365Group`

**Describe alternatives you've considered**
The only way I can think of is connecting to ExchangeOnlineManagemet module

**Additional context**
```
Name    : PnP.PowerShell
Version : 1.12.64
```

**Comment by KoenZomers** [comment]
Looks like the situation discussed here some time ago: https://github.com/pnp/powershell/discussions/1417

Just did a test and still it seems that only for Microsoft 365 Groups with a Team behind it, it will show the property in ResourceBehaviorOptions. When there's no Team behind it, it doesn't return it from Microsoft Graph. If Graph doesn't return it, I'm afraid there's nothing we can do about it. I would suggest raising a support ticket on this with Microsoft Support to get this addressed. If however you can find the property in a Graph response, i.e. using [Graph Explorer](https://aka.ms/ge), I'll be more than happy to see how we can get it in the response.

**Comment by gautamdsheth** [comment]
Closing this due to lack of response. Looks like an issue with the API itself , so not much we can do as well.
