### ISSUE TITLE
[BUG] ConvertTo-PnPClientSidePage is still available in site documentation 

### ISSUE THREAD

**Issue by michaelmaillot** [pnp/powershell#2723]
### Reporting an Issue or Missing Feature

Removed command is still documented.

### Expected behavior 

The module documentation still indicate that the command is available although it has been replaced by `ConvertTo-PnPPage`:

https://pnp.github.io/powershell/cmdlets/ConvertTo-PnPClientSidePage.html

### Actual behavior 

Command should not be available in the module documentation anymore, as it has been removed.

### Steps to reproduce behavior

N/A

### What is the version of the Cmdlet module you are running?

N/A

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [x] Other : N/A

This is an update to #1676 since it has been closed.

**Comment by KoenZomers** [comment]
Thanks for noticing and making us aware @michaelmaillot. I have removed the file.
