### ISSUE TITLE
[BUG] This site belongs to a Microsoft 365 group. To delete the site, you must delete the group

### ISSUE THREAD

**Issue by kbeeveer46** [pnp/powershell#2738]
### Reporting an Issue or Missing Feature

I'm trying to delete a site and all team sites, groups, inboxes etc. etc. associated with the site. These are the following commands I'm running in order. Everything works except for the second to last line when deleting a team site. It says there is a group associated with it but isn't that what the lines above are deleting? I verified that all the other deletes are working and the data is no longer there.  Am I missing some delete commands? Is there a more efficient way to do this? 

```
$group = Get-PnPMicrosoft365Group | Where Mail -eq "XXX@tenant.onmicrosoft.com"
Remove-PnPMicrosoft365Group -Identity $group.Id
Remove-PnPDeletedMicrosoft365Group -Identity $group.Id
Remove-PnPTenantSite -Url "https://tenant.sharepoint.com/teams/XXX" -Force -SkipRecycleBin
Remove-PnPTenantSite -Url "https://tenant.sharepoint.com/sites/XXX" -Force -SkipRecycleBin
```

```
Remove-PnPTenantSite : This site belongs to a Microsoft 365 group. To delete the site, you must delete the group.
At test.ps1:53 char:1
+ Remove-PnPTenantSite -Url "https://tenant.sharepoint.com/teams/XXX ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Remove-PnPTenantSite], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.RemoveSite
```

I looked online and someone said if you go to this URL you can see the group ID associated with the teams site 

`https://tenant.sharepoint.com/teams/XXX/_api/web/allproperties`

So I did that and found this in the result. It matches the ID that was deleted in my code that calls Remove-PnPMicrosoft365Group and Remove-PnPDeletedMicrosoft365Group. Is it possible the group delete hasn't been "registered" yet when I try to delete the teams site? I tried putting a 90 second delay between the group and teams site delete and I still got the error.

`<d:GroupId>3cb9a8ac-45d1-4587-9d1f-178032f1588d</d:GroupId>`

### What is the version of the Cmdlet module you are running?
It says I have 1.12.0 and 1.11.0 installed

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@kbeeveer46 - You are trying to remove 2 different sites. Are they both connected to a group? 

```
Remove-PnPTenantSite -Url "https://tenant.sharepoint.com/teams/XXX" -Force -SkipRecycleBin
Remove-PnPTenantSite -Url "https://tenant.sharepoint.com/sites/XXX" -Force -SkipRecycleBin
```

**Comment by kbeeveer46** [comment]
@veronicageek Yes, I'm trying to remove the team and communication sites. We're using SharePoint as a client portal and we create a communication site and office 365 group for each client. I'm not an expert, but I believe the teams site is created when the group is created. So, I'd like to delete the group, teams site, and communication site all with a single script. Every line that I pasted above seems to work fine and all the data is deleted except when trying to delete the teams site. 

I tried to Google how to view the group that is attached to a team site so I could figure out what group to delete and that's when I came across the link above which shows you the group id (I think). The group id that it showed me was the same group that was deleted in the first few lines of my script (it logs which group id it's about to delete in my code). I went into the Office 365 admin page and verified the group was deleted and also deleted from the "deleted/recycle bin" page.

When my script finished, the group and the communication site was deleted and deleted from recycle bin but the team site was left remaining because of the error telling me I needed to delete the group it's associated with. It's possible I'm not using the write commands to delete the data I'm trying to delete.

Also, The "XXX"s in my script are just placeholders for the real values. It's not meant indicate all those lines were using the same value for XXX in case that caused some confusion.

**Comment by veronicageek** [comment]
@kbeeveer46 - I tried all your commands above and don't have any problem deleting all in that order. I'm using v`1.12.6` (which is not even the latest). 

Could you install the latest nightly release and if you've already deleted the M365 Group (which seemed to have worked for you) then just run the `Remove-PnPTenantSite -Url "https://tenant.sharepoint.com/teams/XXX" -Force -SkipRecycleBin` command on it's own.

Let us know the outcome.

**Comment by kbeeveer46** [comment]
@veronicageek I tried the nightly build but no luck. Btw, I was unable to use the nightly build in Windows PowerShell ISE. I got the following error but I was able to run it in the PowerShell 7 terminal (but still got my original error). If you don't see anything wrong with my commands then it must be something on my end and this ticket can probably be closed.

```
Get-PnPMicrosoft365Group : Only HTTP/1.0 and HTTP/1.1 version requests are currently supported.
Parameter name: value
At Test.ps1:9 char:13
+ $groupPTC = Get-PnPMicrosoft365Group | Where Mail -eq "ClientPortal$( ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-PnPMicrosoft365Group], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.Microsoft365Groups.GetMicrosoft365Group
```

**Comment by kbeeveer46** [comment]
@veronicageek I came across this Microsoft Community post from November of this last year. Someone appears to be having the same issue using the same commands I am using. [https://techcommunity.microsoft.com/t5/sharepoint/delete-team-site-permanently-via-powershell/m-p/3684228](https://techcommunity.microsoft.com/t5/sharepoint/delete-team-site-permanently-via-powershell/m-p/3684228)

**Comment by veronicageek** [comment]
Hi @kbeeveer46, as I can't reproduce the issue maybe something happened on the tenant backend while executing those commands. I would suggest you open a support ticket with Microsoft if possible because unfortunately we won't be able to do anything.

**Comment by Srutututu** [comment]
@kbeeveer46 , in my case the solution was to just wait 3-5 minutes. Although the team/group was nowhere to be found through the UI, Azure was probably still be working on this in the background. Not great experience, but not PnPP fault I think.

![image](https://github.com/pnp/powershell/assets/47721846/9a9d1e2c-7800-49d1-a052-640219cedfb4)

**Comment by kbeeveer46** [comment]
@Srutututu You are correct. I could have sworn I waited several minutes in my tests but apparently not. When I waiting 5 minutes it worked.
