### ISSUE TITLE
[BUG] Duplicated version after Set-PnPListItem

### ISSUE THREAD

**Issue by AdiuTankT72** [pnp/powershell#2742]
### Expected behavior 
After updating a document by Set-SPListItem I would like to have a new draft version of a file with modified metadata information in version history

### Actual behavior 
I have 2 additional draft versions (eg. 1.1 and 1.2). The first contains updated metadata, the second is empty (in version history view). On 1.11.0 it creates a single version. After upgrading to 1.12.0 it creates two.

### Steps to reproduce behavior
Just use Set-SPListItem with UpdateType = Update

### What is the version of the Cmdlet module you are running?
1.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows

**Comment by KoenZomers** [comment]
I cannot reproduce this. When I run this line on a document in a document library:

``` powershell
Set-PnPListItem -List Documents -Id 1 -Values @{ Title="Test" } -UpdateType Update
```

It will only produce one new historical version:

![image](https://user-images.githubusercontent.com/5940670/215428265-5872ffab-a222-4078-9320-c7c67a1c1a58.png)

Can you try it with the latest nightly if that makes a difference for you? If not, can you share more context around the script you're running?

**Comment by gautamdsheth** [comment]
Closing as it is not reproducible and lack of response.

**Comment by kitzler-walli** [comment]
I'm facing the same issue - Set-PnPListItem should update three Peoplepicker fields and creates the update and then another empty version.
