### ISSUE TITLE
Add ability to set Primary Site Collection Admin to Set-PnPTenantSite

### ISSUE THREAD

**Issue by shcrist** [pnp/powershell#2743]
**Is your feature request related to a problem? Please describe.**
Yes. I cannot set the primary site collection admin on a site. Both Set-PnPTenantSite and Add-PnPSiteCollectionAdmin only allow for adding admins to the SCA group. There is no method to set the primary admin. 

**Describe the solution you'd like**
I would like the same functionality provided by the SPOService with Set-SPOSite -Identity $siteURL -Owner "User@domain.com"

**Describe alternatives you've considered**
I tried to update the Owner property on the site but it is read only. I also tried using the SPOService in conjunction with PowerShell PnP but they don't play together. So the only option I have right now is to do this action external to the rest of my script and use the SPOService to do so.

**Additional context**
An additional parameter of -PrimaryOwner that accepts either a user or M365 group and sets the Primary Admin to that value would be perfect.

**Comment by KoenZomers** [comment]
Functionality has been added to `Add-PnPSiteCollectionAdmin` by passing in the new flag `-MakePrimarySiteCollectionAdmin`. Will be available the day after PR https://github.com/pnp/powershell/pull/2750 has been merged.

**Comment by shcrist** [comment]
Awesome news! Thanks for the work and I'll keep an eye out for that release.

**Comment by gautamdsheth** [comment]
Feature has been , will be available in tomorrow's nightly build as well as the next major version whenever it is released
