### ISSUE TITLE
Copy-PnPFile error

### ISSUE THREAD

**Issue by JeroenWetzels85** [pnp/powershell#2746]
I try to copy files from one SharePoint library to a library in another site collection. Using the Copy-PnPFile-function.
Normally the files will be copied, but i'm now receiving the following error-message.

```
Copy-PnPFile : Currently only HTTP/1.0 and HTTP/1.1 version requests are supported. (this is translated by google)
Parameter name: value
+     Copy-PnPFile -SourceUrl "/sites/CAMS/SiteAssets/SP_Logo.png" -Tar ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Copy-PnPFile], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.Files.CopyFile
```

### Steps to reproduce behavior
I connect to the source site collection via:
   `Connect-PnPOnline -Url $url -Interactive`
And after that I execute the copy command
   `Copy-PnPFile -SourceUrl "/sites/CAMS/SiteAssets/SP_Logo.png" -TargetUrl "/sites/$accountNumber/SiteAssets" -Force`

### What is the version of the Cmdlet module you are running?
I've reproduced this behaviour with 1.12.70 and 1.12.73. In 1.12.25 everything works fine

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [x] Other : Azure Automation

**Comment by aglakshmi** [comment]
I am also getting the same error. Is there any solution for this?

**Comment by veronicageek** [comment]
The command itself works for me on `1.12.80`, but maybe @KoenZomers or @gautamdsheth have any ideas about the Azure part.

![image](https://user-images.githubusercontent.com/25181757/219434681-210dd0b2-e6b5-433f-bd83-f47f3a4c7a44.png)

**Comment by gautamdsheth** [comment]
Nope, can't reproduce it either.
Are you executing this in PowerShell 7.2.x or later ?  Maybe you can try the latest nightly and let us know ?

**Comment by veronicageek** [comment]
Closing as no response and can't be reproduced.
