### ISSUE TITLE
Get-PnPTenantSite cmdlet output variances [BUG]

### ISSUE THREAD

**Issue by alisalih1** [pnp/powershell#2758]
### Reporting an Issue
This is a bug. 

When using Get-PnPTenantSite cmdlet, if you target a specific Site Collection URL (with the "Detailed" and "Identity" parameter), the Property count and some Property Values seem to differ, versus using the same Get-PnPTenantSite cmdlet (with the "Detailed" parameter but **without** "Identity" parameter) to get all site collections in a tenant, and then outputting the array member properties for that same site. Please see below for the example usage and screenshots. 

The following Property Values seem to be different for the same cmdlet used for the same site collection: 

- AllowEditing
- BlockDownloadLinksFileType
- DisableAppViews
- DisableCompanyWideSharingLinks
- DisableFlows
- LimitedAccessFileType
- Owner 
- OwnerEmail 
- OwnerLoginName 
- OwnerName
- SandboxedCodeActivationCapability
- WebsCount

### Expected behavior 
Both use cases of the same cmdlet should yield the same property values for the same properties. 

### Actual behavior 
Different property values are observed. 

### Steps to reproduce behavior
Same Cmdlet two use cases:
1) Get-PnPTenantSite -Identity 'https://xxxxxxx.sharepoint.com/teams/MyTestTeam' -Detailed | format-list
vs.
2) $sites = Get-PnPTenantSite -Detailed
    $sites[11] | format-list  

Note: In the 2nd use case, the site[11] refers to the same site collection as in the 1st use case. 

### What is the version of the Cmdlet module you are running?
1.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by alisalih1** [comment]
This behavior shows in Microsoft’s SPO Management Shell  as well.

**Comment by gautamdsheth** [comment]
hi @alisalih1 , unfortunately this an issue `GetSitePropertiesFromSharePointByFilters` method of CSOM SDK that we use.

We cannot fix this issue as the SDK and the underlying API used is owned by Microsoft.
Would request you raise an issue with Microsoft via support channels.
Once it is fixed, it will automatically be available in PnP PowerShell as we always use the latest version of the SDK.
Will close the issue as we can't fix.
