### ISSUE TITLE
[FEATURE] "Add-PnPNavigationNode" -->  append in any order

### ISSUE THREAD

**Issue by hunandy14** [pnp/powershell#2759]
Hello, I would like to ask if it is possible to add the function of processing sequence.

`I need to add the navigation to the third one`, but I didn't find the relevant function after flipping through the text.

Can you help to add this feature?

<br><br><br>

> This may be ill-considered API interface, but I think I can accurately express my purpose through examples.

### Ex.1
Add-PnPNavigationNode -Title "Google" -Url "http://gootgle.com" -Location "QuickLaunch" `-AddToIndex 3`
### Or Ex.2
Set-PnPNavigationNode -Id 2001 `-ShiftToIndex 3`

<br><br><br>

ref
1. https://sharepoint.stackexchange.com/questions/259643/add-pnpnavigationnode-how-to-set-node-order

**Comment by gautamdsheth** [comment]
hi @hunandy14 , this has been added now with the latest releases of PnP PowerShell.

You can specify the `-PreviousNode` parameter and then it will append the new node after the specified node.

Checkout this [example](https://pnp.github.io/powershell/cmdlets/Add-PnPNavigationNode.html#example-7)

**Comment by hunandy14** [comment]
@gautamdsheth Thank you. it works!!

**Comment by mvanders** [comment]
And now it has been removed again??? -PreviousNode
