### ISSUE TITLE
GetSiteScript vs GetSiteScripts and Get-PnPSiteScripts

### ISSUE THREAD

**Issue by Pieter-Veenstra** [pnp/powershell#2773]
**Is your feature request related to a problem? Please describe.**

The REST API offers GetSiteScript**s** however there doesn't seem to be a GetSiteScript API available. Comparing this to Powershell, we have Get-PnPSiteScripts with the option to specify an Identity.

Looking at the code Powershell code seems to jump into Tenant.GetSiteScripts code or Tenant.GetSiteScript code. One of the differences is that Tenant.GetSiteScript collects the Content property containing the script. Tenant.GetSiteScripts doesn't collect the content.

I have need to collect a specific site script through the REST API. Throguh the REST API however I don't seem to be able to collect the Content of a script.

**Describe the solution you'd like**
Next to 
/_api/Microsoft.SharePoint.Utilities.WebTemplateExtensions.SiteScriptUtility.GetSiteScripts 
to collect all Site scripts without the Content property it would be great to also have the option to use 
/_api/Microsoft.SharePoint.Utilities.WebTemplateExtensions.SiteScriptUtility.GetSiteScript/{id}  
to collect a specific site script with the Content property included.

**Describe alternatives you've considered**
PnP PowerShell works but the REST API does not (or I haven't found the option). I could potentially do this from PowerShell but it would make the solution a lot more complicated.

**Additional context**
I'm calling this from a flow in Power Automate.

**Comment by gautamdsheth** [comment]
hey @Pieter-Veenstra , what exactly is the feature request ? Sorry didn't understand from the above comment. 

Do you want a RESR API which also returns the script content ?

**Comment by Pieter-Veenstra** [comment]
@gautamdsheth , yes that is exactly it. A REST API that returns the content of a specified site script.

**Comment by gautamdsheth** [comment]
hi @Pieter-Veenstra , we can't build the REST API. You will need to reach out to Microsoft PG and request them for this feature via UserVoice, Feedback Hub or something. In PnP PowerShell, we simply consume the available APIs via REST or CSOM and use them in the cmdlets.
