### ISSUE TITLE
[BUG] Invoke-PnPSPRestMethod - Pages API - Publish - The input does not contain any JSON tokens

### ISSUE THREAD

**Issue by SjoerdV** [pnp/powershell#2776]
### Reporting an Issue
Using the Pages api through SharePoint REST API v2, this command:
```powershell
Invoke-PnPSPRestMethod -Url "https://<tenant>.sharepoint.com/_api/v2.0/sites('<tenant>.sharepoint.com,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000')/pages/00000000-0000-0000-0000-000000000000/oneDrive.publish" -Method "POST" -ContentType "application/json" -Content @{} -ErrorAction Stop
```
(all guids replaced with empty guid)

returns:
```log
The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
```

### Expected behavior 
Publish the Modern Page

### Actual behavior 
Error message as depicted above. 

NOTE1: it does not matter if the 'Content' parameter is omitted
NOTE2: it does not matter if the Url suffix 'oneDrive.publish' is replaced with 'publish'
NOTE2: the exact same call passes without error through a direct Graph call using [EasyGraph](https://github.com/andlin03/EasyGraph) Module and Invoke-PnPGraphMethod:
```powershell
Invoke-PnPGraphMethod -Method POST -Url "beta/sites/<tenant>.sharepoint.com,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000/pages/00000000-0000-0000-0000-000000000000/publish" -ContentType "application/json" -ErrorAction Stop
```

### What is the version of the Cmdlet module you are running?
1.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [x] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Thanks @SjoerdV for raising the issue. 

Can you please tell us how to get actual GUID values ? Will try to reproduce and fix this :)

**Comment by SjoerdV** [comment]
> Thanks @SjoerdV for raising the issue.
> 
> Can you please tell us how to get actual GUID values ? Will try to reproduce and fix this :)

Sure @gautamdsheth 
make these GET calls to the following endpoints
```powershell
/sites?select=id,webUrl,displayName # resulting id = id of the site
/sites/$siteid/pages?select=id,title # use the 'id' of a site in the previous call, resulting id = id of the page
```

**Comment by gautamdsheth** [comment]
Thanks @SjoerdV for raising this issue, have fixed it.
Was an interesting edge case we missed.

The fixed version will be available in tomorrow's nightly build and the next major version.

**Comment by SjoerdV** [comment]
Thanks for solving @gautamdsheth !

**Comment by SjoerdV** [comment]
confirmed working with nightly 2.0.12 on pwsh 7.3.2.
