### ISSUE TITLE
Set-PnPSearchConfiguration isn't properly updating values for Managed Properties

### ISSUE THREAD

**Issue by NikCharlebois** [pnp/powershell#2803]
### Reporting an Issue or Missing Feature
Running:

```
Set-PnPSearchConfiguration -Scope 'Subscription' -Path 'C:\file.xml'
```

with the attached file doesn't update the Searchable property (and other boolean checkboxes values). It doesn't throw any error. This used to work a few weeks back, but now doesn't update anything anymore.

### Expected behavior 
Properties get updated

### Actual behavior 
Properties aren't updated.

### Steps to reproduce behavior
See description

### What is the version of the Cmdlet module you are running?
1.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
[nik (2).txt](https://github.com/pnp/powershell/files/10709829/nik.2.txt)

- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
@NikCharlebois - looks like a server side issue, we haven't changed anything in the cmdlet for quite a long time !

**Comment by nikegambhava** [comment]
@gautamdsheth  @NikCharlebois  i checked with Set-PnPSearchConfiguration  command its seems like that command is not Updating values for Managed Properties

**Comment by andikrueger** [comment]
@wobba Are you aware of any changes? It looks like there are some issues right now.  

- https://github.com/microsoft/Microsoft365DSC/issues/2900
- https://github.com/microsoft/Microsoft365DSC/issues/2880

**Comment by wobba** [comment]
Not aware and would log this as an API issue at https://github.com/SharePoint/sp-dev-docs/issues or log a support ticket with Microsoft.

**Comment by KoenZomers** [comment]
Nothing we can do from the PnP PowerShell side I'm afraid. Code hasn't been touched in over a year and communicates directly with CSOM: https://github.com/pnp/powershell/blob/866d1fed3a1a9054368e867061f44fe555ef0cb9/src/Commands/Search/SetSearchConfiguration.cs#L52

I also suggest opening a support ticket with Microsoft on this matter. Closing the issue here.
