### ISSUE TITLE
[BUG] Batching using New-PnPBatch fails with Could not load file or assembly

### ISSUE THREAD

**Issue by bGlasson** [pnp/powershell#2808]
### Reporting an Issue or Missing Feature
Batching using New-PnPBatch fails with code that _seems_  to follow examples, old working code and even ChatGPT 😅 . 

Powershell 7.3.2 and PnP.Powershell 1.12.0; uninstalling / reinstalling hasnt helped.

### Expected behavior 
expect batched PnPonline functions (e.g. Add-PnPListItem, Set-PnPListItem etc) to aggregate and execute

### Actual behavior 
Script fails immediately calling New-PnPBatch with error
`Could not load file or assembly 'Microsoft.Extensions.DependencyInjection, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.`

### Steps to reproduce behavior
run anything calling New-PnPBatch, e.g.:
```
Connect-PnPOnline -Url $SiteURL -UseWebLogin 

$batch = New-PnPBatch

foreach($i in 1..2)
{
Add-PnPListItem -List $ListName -Values @{
    "Title" = "batchtest doubles"
    } -Batch $batch
}
#run it
Invoke-PnPBatch -Batch $batch
```

### What is the version of the Cmdlet module you are running?
1.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@bGlasson - I have no issue running your script with `1.12.0`. can you please try again, maybe it was at a point in time. Reopen if the problem persist 🙂

![image](https://user-images.githubusercontent.com/25181757/219427044-dcb3d4f4-dc21-424a-b3ba-ba1cb58ad251.png)

**Comment by bGlasson** [comment]
Sadly issue is definitely still live on my machine. 
PowerShell 7.3.2 still behaves as above. 

PowerShell 5.1.3 fails immediately with the connect:
Connect-PnPOnline : The type initializer for 'Microsoft.SharePoint.Client.ClientContextExtensions' threw an exception.
+ Connect-PnPOnline -Url $SiteURL -UseWebLogin
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-PnPOnline], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException,PnP.PowerShell.Commands.Base.ConnectOnline

**Comment by bGlasson** [comment]
For clarity - would rather a working solution for 7.. but I need a _batched_ solution asap.... if I can solve 5.1x, that would at least get me working. Any help would be greatly appreciated.

**Comment by veronicageek** [comment]
Still no issue on PS5. 
As for the connection, please try using `-Interactive` instead of `-UseWebLogin` which is legacy authentication).

https://pnp.github.io/powershell/cmdlets/Connect-PnPOnline.html#example-9

![image](https://user-images.githubusercontent.com/25181757/219445960-40b684c8-7f45-453a-9bc7-8d5de20861d6.png)

**Comment by bGlasson** [comment]
first - REALLY appreciate the help, this is killing me 😅

Would not have expected auth method impact execution.  Have used `-UseWebLogin` because it plays nice with the SSO-only world I'm in..... was working (with batching etc) until very recently. Tried with `-Interactive,` got the same message:

Line |
  23 |  Connect-PnPOnline -Url $SiteURL -Interactive #-UseWebLogin
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not load file or assembly 'Microsoft.Extensions.DependencyInjection, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the     
     | file specified.

If I comment out the batching with `-Interactive `in 7, I get the error, script finishes and list is not updated. If I return to `-UseWebLogin` _without_ the batching, it works as expected, iterating through the updates.

full code with batching including comments etc below ($1,$2,$3 to protect modesty 😅), just incase there's something relevant:

```
$SiteURL = $1
$ListName = $2

#csv with changes you want to make
$csv1 = Import-CSV $3
$now = (get-date).ToString("yyyy-MM-ddThh:mm:ssZ")

#start the time-to-complete clock 
$startTime = Get-Date

 
#Connect to PnP Online
Connect-PnPOnline -Url $SiteURL -UseWebLogin 

# make a Batch of all changes to make from CSV file
$batch = New-PnPBatch
foreach($item in $csv1) 
{
  # Make change to SPO
Set-PnPListItem -List $ListName -Identity $item."Id" -Values @{
  
    # sharepoint field name = $item."NAME OF FIELD IN CSV"
    # multichoice fields need ($item."name of field").split(",")
    # date fields work with dd/mm/yyyy format input
    # single people pickers take email addresses
    # lookup fields need the list item Id from the lookup list not the value (e.g. 5 , not "lookupTitle1")

    #fields commented out if they're not required for now


    #"Contract" = $item."cjContractId"
    "cjDocTypeV2" = $item."cjDocTypeV2";
   # "cjDocFlagsV2" = ($item."cjDocFlagsV2").split(",");
    "cjComments" = $item."cjComments";
    "cjStatus" = $item."cjStatus";
    "cjStatusChanged" = $now;

   }-Batch $batch
   
  }
 
# Execute the batch all at once
  Invoke-PnPBatch -Batch $batch -Details

#stop the clock, calc time-to-complete tell me about it in console
$endTime = Get-Date
$totalTime = $endTime - $startTime
 
write-host "Total script run time: $($totalTime.Hours) hours, $($totalTime.Minutes) minutes, $($totalTime.Seconds) seconds" -ForegroundColor Cyan
```
![image](https://user-images.githubusercontent.com/114933082/219452985-b605cff1-a568-490b-812b-8fa62db691ac.png)
![image](https://user-images.githubusercontent.com/114933082/219453648-b5a62634-a03b-4f8f-bdfa-bb0fc0a45c19.png)

**Comment by veronicageek** [comment]
I've tried with `-UseWebLogin`, PS `7.3.2` and batching, and again no issue on my side. Maybe there's something on your system blocking somewhere, I'm not sure. If you can try to connect on another machine, or run your script with real values instead of a .csv / variables. But can't really help as everything is working on my side...

**Comment by bGlasson** [comment]
thanks for trying again

Have validated on 3 other machines and two other user accounts in my environment. Have also tried hardcoding everything (urls, list names, list items to change, list values to update) and restricting batch to a single item (they all fail the same). Am sure this was caused by a change on our side, but I don't know where to start challenging it. 

I'd _guess_ this is client side (windows patch? security config? m365 client patch?)... but I'm not certain it _couldn't_ be a network change or even SPO config. 

Was hoping someone could point out the embarrassing problem with my code or give me a list of a few things most likely to break it in this way .... that way I know which team to ask for help and I've got something more than "my code broke, was it you?" to start with 😅

`Could not load file or assembly 'Microsoft.Extensions.DependencyInjection, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60` <---- any comments / suggestions on this would be very very welcome 🥺

**Comment by bGlasson** [comment]
Wild shots in the dark... can you confirm if you're on same patch level? Most recent change for me were:
`KB5022303` installed (I'm on Win 22h2)
and 
.Net 4.8.09032 (release 533320) ... (check registry keys at `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full`) 

Some fixes for Microsoft.Extensions.DependencyInjection refernce underlying dependencies include .Net.... and only other lowish-fruit I can think of would be a windows patch :)

**Comment by veronicageek** [comment]
Yes, all the same - Win11 22H2

![image](https://user-images.githubusercontent.com/25181757/219663606-cbe674a3-ec58-4187-821f-19263fdec04b.png)

**Comment by bGlasson** [comment]
Thanks for confirming.... just to double check - you've got `KB5022303` installed on 22H2 too?

**Comment by veronicageek** [comment]
No I don't seem to have it installed.

**Comment by bGlasson** [comment]
If I can get permission to roll it back, I'll see if that's the cause. Thanks!
