### ISSUE TITLE
[BUG] Using ManagedIdentity with -UserAssignedManagedIdentityObjectId fails on Azure Automation

### ISSUE THREAD

**Issue by martinlingstuyl** [pnp/powershell#2812]
### Reporting an Issue or Missing Feature
When I connect to SharePoint in a PowerShell Runbook in Azure Automation, using a User Assigned Managed Identity, I'm getting the following error:

```powershell

Connect-PnPOnline -url $URL -ManagedIdentity -UserAssignedManagedIdentityObjectId $identityObjectId

{"Message":"No managed System identity was found for Automation account <account_guid>."}

```

I'm sure I have the right permissions in place though. So I checked the Source Code and did some testing with a manual setup for managed identity:

```powershell

function Get-AccessTokenUsingManagedIdentity($url) {
    $identityObjectId = Get-AutomationVariable -Name 'UserAssignedIdentityObjectId'
    $endpoint=$env:IDENTITY_ENDPOINT
    $header= $env:IDENTITY_HEADER
    $response = [System.Text.Encoding]::Default.GetString((Invoke-WebRequest -UseBasicParsing  -Uri "$($endpoint)?resource=$url&api-version=2019-08-01&principal_id=$identityObjectId" -Method 'GET' -Headers @{'X-IDENTITY-HEADER' = "$header"; 'Metadata' = 'True'}).RawContentStream.ToArray()) | ConvertFrom-Json
    return $response.access_token    
}

$token = Get-AccessTokenUsingManagedIdentity -url "https://contoso.sharepoint.com"
```

The code above uses the object ID of the managed identity, just like PnP PowerShell does. And it throws a bad request (400).
But if I move it to using the Client ID of the same Identity, it will succeed. 

eg replace `principal_id=$identityObjectId` with `client_id=$identityClientId`. 

Check the client_id parameter for reference:
https://learn.microsoft.com/en-us/azure/app-service/overview-managed-identity?tabs=portal%2Chttp#rest-endpoint-reference

It should both work of course. It's strange that it does not. 

My current workaround is to manually retrieve the token and connect using `Connect-PnPOnline -AccessToken`.

### What is the version of the Cmdlet module you are running?
1.12

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

### Proposal

I'm not sure how to fix the actual problem. But adding an extra parameter to the Connect-PnPOnline commandlet would be a good thing anyway: `UserAssignedManagedIdentityClientId` and allow to flow the code to use &client_id= in that scenario.

You can assign me to fix this.

**Comment by martinlingstuyl** [comment]
Hi @gautamdsheth, I've created a PR to add a good workaround for the issue. I'm not sure what's going on below the surface that the `principal_id` route is not working. But I'm thinking it would be good anyway to have both parameters so you can choose which direction to go.

Hope you agree on that.

**Comment by martinlingstuyl** [comment]
Ok, I just found what's going on.

The [documentation](https://learn.microsoft.com/en-us/azure/app-service/overview-managed-identity?tabs=portal%2Chttp#rest-endpoint-reference) mentions the following:

```text
(Optional) The principal ID of the user-assigned identity to be used. object_id is an alias that may be used instead. Cannot be used on a request that includes client_id, mi_res_id, or object_id. If all ID parameters (client_id, principal_id, object_id, and mi_res_id) are omitted, the system-assigned identity is used.
```

I tried out the above code with `object_id` instead of `principal_id`, and that works fine as well. 

So it appears that Azure Automation did not get the memo that `object_id` ought have been changed to `principal_id`.

Any ideas on how to proceed here aside from my existing PR? Should we rename `principal_id`, or add a fallback mechanism?

**Comment by KoenZomers** [comment]
Thanks for your investigation here. So basically you're saying Runbooks don't support object_id and require principal_id to be used, correctly understood? I think it would be good to add support for all three options for user managed identities: objectid, clientid and azure resource id. Doing so would still not fix the issue you're addressing here, correct? I can discuss this with the product team behind Runbooks if you confirm me to understand it correctly.

**Comment by martinlingstuyl** [comment]
> Runbooks don't support object_id and require principal_id to be used, correctly understood

Yes, but the other way around: they support object_id, but not principal_id

> I think it would be good to add support for all three options for user managed identities

Awesome, in that case I'll leave my PR open.

> I can discuss this with the product team behind Runbooks if you confirm me to understand it correctly.

Yes please, I already dropped it in the MVP Azure Distribution List, but I'm not sure if it gets to the right people.

**Comment by KoenZomers** [comment]
@martinlingstuyl Would you have an idea where the Azure Resource ID would surface?

<img width="426" alt="image" src="https://user-images.githubusercontent.com/5940670/219057057-b22b9265-8de7-4ce5-aa71-085c2f231107.png">

I can only find the Client ID and Object (principal) ID on a managed identity in Azure.

**Comment by KoenZomers** [comment]
Never mind, found it to be the Id property in Azure :)

**Comment by KoenZomers** [comment]
@martinlingstuyl I have added the resource ID option as well and created separate parametersets to avoid people using more than one of the three options and causing confusion on which one to be leading.

Back to the original issue, can't we just update this to get it fixed?
https://github.com/pnp/powershell/pull/2813/files#r1107262033

By far easier than convincing a PG that their implementation is wrong and waiting for a fixed rollout.

**Comment by martinlingstuyl** [comment]
> created separate parametersets to avoid people using more than one of the three options and causing confusion on which one to be leading

Ah, I see how you did that! I wanted to achieve the same, but I did not know how. But apparently it's very easy indeed.

> Back to the original issue, can't we just update this to get it fixed?

If it works, let's do that. 🤙 I didn't test it though. It would be very easy to check it out of course...
