### ISSUE TITLE
[BUG] Set-PnPDefaultColumnValues throws ServerUnauthorizedAccessException since last week

### ISSUE THREAD

**Issue by heinrich-ulbricht** [pnp/powershell#2814]
### Reporting an Issue or Missing Feature
Issue

`Set-PnPDefaultColumnValues` used to work until last week. Now it fails with `ServerUnauthorizedAccessException`.

Simple sample:

```
Get-PnPList "Dokumente" -Connection $con
Set-PnPDefaultColumnValues -List "Dokumente" -Field "Art" -Value "Test" -Connection $con
```

This is via application permissions.

### Expected behavior 
The default value should be set without error.

### Actual behavior 
`ServerUnauthorizedAccessException` and 
<img width="327" alt="image" src="https://user-images.githubusercontent.com/3469970/218502184-557ae9d4-3b28-4a6f-a949-595e7a57c3d1.png">

### Steps to reproduce behavior
For me its enough to run above code. Did not yet check with other sites. Wanted to raise this here to gather input.

### What is the version of the Cmdlet module you are running?
Latest `master` build.

Note that this problem also occurred in a provisioning template. Then I tested in PnP PowerShell. So it might be something either on the platform, or in my context of work. Don't know yet.

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by heinrich-ulbricht** [comment]
Just a thought: I read that setting the default values requires a high permission level (modify permissions). Our application has `SharePoint:Sites.FullControl.All`, but only `Graph:Sites.ReadWrite.All`.

Just spitballing here - could it be that certain requests are routed differently so that Graph permissions apply, not SharePoint permissions? Or something like that?

Because while digging deeper I found that not our provisioning template with default values is the problem. But adding an event receiver:
<img width="647" alt="image" src="https://user-images.githubusercontent.com/3469970/218508297-cc75debb-f04a-4d13-9663-924c76798dbc.png">

Does this also require higher permissions?

Still trying to figure out what is going on.

**Comment by heinrich-ulbricht** [comment]
Update: with `Sites.FullControl` app permissions in Graph and SharePoint it is still **not** possible to either set the default value for a field nor to invoke a site template provisioning a list, that tries to register the event receiver that handles setting default values.

**Comment by akarlsten** [comment]
We are experiencing a very similar issue, in our case we are using `Invoke-PnPSiteTemplate` to provision a newly created site (also created by the same Azure function) on a rather new Sharepoint tenant.

```
ERROR: Error applying default column values
...
InvocationInfo : MyCommand : Invoke-PnPSiteTemplate
ScriptLineNumber : 170
OffsetInLine : 1
HistoryId : 1
ScriptName : C:\home\site\wwwroot\NewInstance\run.ps1
Line : Invoke-PnPSiteTemplate -Path $instanceTemplatePath
PositionMessage : At C:\home\site\wwwroot\NewInstance\run.ps1:170
```

We connect using a service account and the following method: 
`Connect-PnPOnline -Url $Url -Credentials $cred -ClientId $PnPPermissonsApp -WarningAction Ignore`

We have also tried adjusting our app permissions, changing the site template, etc. Nothing seems to work.

What makes it even stranger is that the exact same function works perfectly fine in other Azure environments when ran against other Sharepoint tenants (even other newly created ones).
Additionally, manually running `Invoke-PnPSiteTemplate` with the same template and login method locally also works and doesn't cause the error.

In our case the function is still using PS 7.0 and the version ~3 function runtime as well as PnP.Powershell `1.10.0`, which is a bit on the older side, but as mentioned it still works fine elsewhere.

We are in the process of trying to upgrade to PS 7.2, runtime 4 and the latest nightly PnP.Powershell as outlined in #2136 but are having separate issues there (specifically still getting the dependency conflicts that have supposedly been resolved in that issue).

**Comment by jackpoz** [comment]
Same issue here happening on a tenant but working fine on another tenant, using Invoke-PnPSiteTemplate with the same template, using -DeviceLogin on both sites and with the same PnP version (even in the same PowerShell 7.3.1 instance).

Exception is throw when trying to add the event receiver.

Using PnP PowerShell f3007f2ea64f4ecd05412c4d75b331ef619ef224 (latest as of now) with PnP Framework https://github.com/pnp/pnpframework/commit/698166b9eb5a762e27449dee1b5b695683615e20 (latest as of now)

This has been reported at https://github.com/pnp/pnpframework/issues/838 too

**Comment by heinrich-ulbricht** [comment]
Ok so I'm not crazy after all. "Good" to see others having issues as well. Need this to get attention.

Totally unclear for me what's causing this. Seems like a tenant/API issue surfacing everywhere certain priviledged operations are run (via app auth?).

fyi @VesaJuvonen

**Comment by jackpoz** [comment]
My repro script to check if the tenant is affected:
```powershell
New-PnPList -Title "TestPnP" -Template DocumentLibrary
Set-PnPDefaultColumnValues -List "TestPnP" -Field "Title" -Value "Test"
```

If it throws "Set-PnPDefaultColumnValues: Error applying default column values" then the tenant has the issue

**Comment by patrikhellgren** [comment]
Here is a script that repros the issue using standard CSOM assemblies so no PnP.PowerShell involved except for getting web context:

```PowerShell
Connect-PnPOnline -Url $siteUrl -Interactive
$ctx = Get-PnPContext
$web = Get-PnPWeb
$srcList = $web.Lists.GetByTitle("Documents")
$ctx.load($srcList)
$ctx.executeQuery()
$eventReceivers = $srcList.EventReceivers
$ctx.Load($eventReceivers)
$ctx.ExecuteQuery()
$eventReceiverCreationInformation = New-Object Microsoft.SharePoint.Client.EventReceiverDefinitionCreationInformation
$eventReceiverCreationInformation.ReceiverName = "LocationBasedMetadataDefaultsReceiver ItemAdded"
$eventReceiverCreationInformation.SequenceNumber = 1000
$eventReceiverCreationInformation.ReceiverClass = "Microsoft.Office.DocumentManagement.LocationBasedMetadataDefaultsReceiver"
$eventReceiverCreationInformation.ReceiverAssembly = "Microsoft.Office.DocumentManagement, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c"
$eventReceiverCreationInformation.EventType = [Microsoft.SharePoint.Client.EventReceiverType]::ItemAdded
$eventReceiverCreationInformation.Synchronization = [Microsoft.SharePoint.Client.EventReceiverSynchronization]::Synchronous
$receiver = $eventReceivers.Add($eventReceiverCreationInformation)
$ctx.Load($receiver)
$ctx.ExecuteQuery()
```

This will throw an Unauthorized exception on the last ExecuteQuery in a tenant that has this issue while it works in others.

**Comment by gautamdsheth** [comment]
Hi looks like a Microsoft server-side issue. We haven’t changed anything from our side and as Patrick mentioned, it’s even occurring in pure CSOM code.

Will close the issue and suggest that you reach out to Microsoft via official support tickets and channels. We can’t do anything from this side here.

**Comment by heinrich-ulbricht** [comment]
It would be good to know if anybody already opened a ticket with Microsoft - @patrikhellgren @jackpoz @akarlsten ?

**Comment by patrikhellgren** [comment]
@heinrich-ulbricht I haven't done that yet.

**Comment by heinrich-ulbricht** [comment]
Another one: https://github.com/pnp/pnpframework/issues/846

**Comment by joelfmrodrigues** [comment]
I suggest people raise this as a support ticket with MS as soon as possible as it seems like a platform issue

**Comment by ssamnadda** [comment]
Upgrading to PnP.PowerShell 2.4.0 solved the issue for me.
