### ISSUE TITLE
[BUG] Documentation on connecting to SharePoint is incorrect

### ISSUE THREAD

**Issue by MartinHatchL365** [pnp/powershell#2815]
Pretty simple this one

The articles on "Connecting with PnP PowerShell" do not include the -CertificatePassword parameter
https://github.com/pnp/powershell/blob/dev/pages/articles/connecting.md 

This means anyone who is trying to connect using a PFX certificate (or Base64 encoding) may not realise (or forget) to include the password value

...

Note - The error when the password is NOT included is an equally helpful "The specified network password is not correct." 

A more specific "The password to access the certificate file was missing, please use the -CertificatePassword parameter" might also be a bit more helpful?

**Comment by KoenZomers** [comment]
Fair point @MartinHatchL365. Normally we would not be able to do much about it as changing the output to something that's more clear might break existing scripts which are handling that exact message and/or type of exception. With 2.0 of PnP PowerShell coming we can make breaking changes. I'm proposing to change it to this. Do you think this will be more useful?

![image](https://user-images.githubusercontent.com/5940670/219207544-510b9191-e41a-42b1-99ab-bbb43c361567.png)

I've also updated the documentation to make it clearer how to work with certificates having a password on them.

PR https://github.com/pnp/powershell/pull/2826 will merge these changes.

**Comment by gautamdsheth** [comment]
Closing this as it has been merged via #2826 , the docs will be updated tomorrow and the code will be available via tomorrow's nightly.

Thanks for raising the issue, much appreciated !
