### ISSUE TITLE
[BUG] Import-PnPTermGroupFromXml generating the error "Import-PnPTermGroupFromXml Template is not valid"

### ISSUE THREAD

**Issue by rtorres-br** [pnp/powershell#2816]
### Reporting an Issue or Missing Feature
Reporting an Issue

### Expected behavior 
Term Store term group being updated/imported by Import-PnPTermGroupFromXml.

### Actual behavior 
Import-PnPTermGroupFromXml generating the error "Import-PnPTermGroupFromXml Template is not valid" to every Provisioning Schema before 2022-09. 
<pnp:TermGroups xmlns:pnp="http://schemas.dev.office.com/PnP/2022/09/ProvisioningSchema">
It does not matter if you use the provisioning full line or not.

### Steps to reproduce behavior
Just try to import a term store XML with Import-PnPTermGroupFromXml with any Provisioning Schema prior to 2022-09
<pnp:TermGroups xmlns:pnp="http://schemas.dev.office.com/PnP/2022/09/ProvisioningSchema">
The line above is the only one that works.

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 1.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [X] Other : PowerShell 7.3.2

**Comment by gautamdsheth** [comment]
@rtorres-br - this is by design. It is not a bug. The cmdlet always require you to use the latest schema to update the terms.
