### ISSUE TITLE
[BUG] files created by users not visible to app and vise versa

### ISSUE THREAD

**Issue by gummby8** [pnp/powershell#2817]
### Reporting an Issue or Missing Feature
If I connect to sharepoint via interactive login and add a file I can see it on the sharepoint site

`Connect-PnPOnline -Url $Surl -Interactive`
`Add-PnPFile -Path c:\temp\check1.log -Folder "documents"`

If I connect with an application and thumbprint and add a file, the file is invisible in the web

`Connect-PnPOnline -Url $Surl -ClientId $cid -Thumbprint $thumb -Tenant $tenant`
`Add-PnPFile -Path c:\temp\check2.log -Folder "documents"`

using `Find-PnPFile -match *.log`
If I am connected with the app/thumb I can only see check2.log.
If I am connected with my user using interactive login I can only see check1.log

The app has "Full control" rights to the sharepoint site

### Expected behavior 
Files uploaded by either user or app should be visible to one another

### Actual behavior 
Files uploaded by the app are not visible to users, and files uploaded by users are not visible to the app. 

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

### What is the version of the Cmdlet module you are running?
1.12.0

### Which operating system/environment are you running PnP PowerShell on?
Windows

**Comment by KoenZomers** [comment]
I cannot reproduce it here. Could it have to do with that you're uploading to Documents instead of  Shared Documents? For any modern site, it should be Shared Documents and not Documents.

<img width="1724" alt="image" src="https://user-images.githubusercontent.com/5940670/219303358-65f728e6-6cbd-4b4b-9bf5-0deca3cf4607.png">

**Comment by gummby8** [comment]
Apologies. apparently this was caused by files being checked out. Once I removed file check out, the issue went away.
