### ISSUE TITLE
Outdated app only doc sample [BUG]

### ISSUE THREAD

**Issue by mmascolino** [pnp/powershell#2824]
The doc sample here:
https://github.com/pnp/powershell/tree/dev/samples/Graph.ConnectUsingAppPermissions

references  `Connect-PnPOnline -AppId '2994aca5-7ef4-4179-89ff-c1ce18fa052f' -AppSecret 'NvgASDFS4564fas' -AADDomain 'techmikael.onmicrosoft.com'`

None of those parameters are currently valid for [Connect-PnPOnline](https://pnp.github.io/powershell/cmdlets/Connect-PnPOnline.html)

**Comment by KoenZomers** [comment]
Thanks for making us aware @mmascolino . I have deleted the sample as it indeed has totally changed by now. Actual guidance around this topic can be found at https://pnp.github.io/powershell/articles/connecting.html#connect-by-using-your-own-azure-ad-application
