### ISSUE TITLE
Set-PnPDefaultColumnValues | Setting-up default values to multiple columns

### ISSUE THREAD

**Issue by dhanashree2307** [pnp/powershell#2829]
### Reporting an Issue or Missing Feature
We need to set default values of multiple site columns used in a folder for a document library using Set-PnPDefaultColumnValues command.

### Expected behavior 
Default values for all site columns are set

### Actual behavior 
Default value of a column mentioned in the last command is being set. Previous column default values are cleared out/blank.

### Steps to reproduce behavior
1. Run Set-PnPDefaultColumnValues command for multiple columns
   Set-PnPDefaultColumnValues -List $Library -Field $Column1 -Value $DefaultValueColumn1 -Folder $FolderUrl
   Set-PnPDefaultColumnValues -List $Library -Field $Column2 -Value $DefaultValueColumn2 -Folder $FolderUrl
   Set-PnPDefaultColumnValues -List $Library -Field $Column3 -Value $DefaultValueColumn3 -Folder $FolderUrl
2. For the example mentioned above, default value for only Column3 will be set.

### What is the version of the Cmdlet module you are running?
PnP.PowerShell Version - 1.12.0

### Which operating system/environment are you running PnP PowerShell on?
- Windows

**Comment by veronicageek** [comment]
@dhanashree2307 - I'm not able to reproduced and each default value is set correctly using the commands, as well as when adding documents to the libraries (value applied).

![image](https://user-images.githubusercontent.com/25181757/219424071-ea22e083-9121-4b8a-bac5-546abd4032d1.png)

![image](https://user-images.githubusercontent.com/25181757/219424178-7a8ba5fd-c4f2-42b2-9fff-e3e1b2af135b.png)

![image](https://user-images.githubusercontent.com/25181757/219424218-6f8e9e28-0a76-484d-9117-e48ad6bebec4.png)

![image](https://user-images.githubusercontent.com/25181757/219424258-7c445490-0f43-4aed-943d-b89a1ae0577b.png)

Can you please test directly with the values of your variables and feedback. Thanks.

**Comment by dhanashree2307** [comment]
@veronicageek values are visible in default column values settings but those are not pre-filled in metadata while creating new folder or a document.

Following is the piece of code that I have ran for setting default values -

<img width="100%" alt="image" src="https://user-images.githubusercontent.com/69456840/219566756-916f85e9-b084-4505-a442-95ab26452f2d.png">

**Do note the last default value set is for the column Country**

As mentioned in following screenshot, values are visible in default column value settings

<img width="100%" alt="image" src="https://user-images.githubusercontent.com/69456840/219566975-ad6ca276-b879-4801-8e1c-8ca90b9b2634.png">

When we try to create new folder/document or drag and drop a document inside specified folder, only column in last command (Country) gets updated. As per example given, values for MatterName and Segment is not pre-filled, where as value for Country is being set.

<img width="100%" alt="image" src="https://user-images.githubusercontent.com/69456840/219575999-013c2401-91f0-47b5-8547-13c6c215fcdf.png">

Is there any approach where we can set multiple default column values via PowerShell and when we drag and drop a file in the folder, all the default column values are set.

**Comment by veronicageek** [comment]
@dhanashree2307 - Thanks for all the details. I was indeed able to reproduce the issue.

Seems it's only taking the last `Set-PnPDefaultColumnValues`. If you move the commands around and the last is `MatterName`, then this is the one that'll be set when adding a document... Nothing to do with the type of column. Even tried with direct values instead of variables, and same problem.

FYI - @gautamdsheth @KoenZomers

**Comment by HaiyeWang0717** [comment]
I also ran into this issue. I have to run this command twice. Use folder name for the first time, and folder URL for the second time. This way temporarily solves the issue. But I believe this must be a bug.


           Set-PnPDefaultColumnValues -List $libraryName -Field $column1 -Value $value1 -Folder $FolderName
           Set-PnPDefaultColumnValues -List $libraryName -Field $column2 -Value $value2 -Folder $FolderName
           Set-PnPDefaultColumnValues -List $libraryName -Field $column3 -Value $value3 -Folder $FolderName


           Set-PnPDefaultColumnValues -List $libraryName -Field $column1 -Value $value1 -Folder $FolderServerRelativeURL
           Set-PnPDefaultColumnValues -List $libraryName -Field $column2 -Value $value2 -Folder $FolderServerRelativeURL
           Set-PnPDefaultColumnValues -List $libraryName -Field $column3 -Value $value3 -Folder $FolderServerRelativeURL

**Comment by veronicageek** [comment]
@dhanashree2307 - There's been a lot of improvements and bug fixes in the new release, so could you please update to the latest release `2.1.x` however you **will need PS 7.2 or later** to benefit from all the changes.

PS5 support has been dropped in the new release.

**Comment by veronicageek** [comment]
Closing as no response.
