### ISSUE TITLE
[BUG] New-PnPSite not working in Azure USGovernmentHigh Access token validation failure. Invalid audience.

### ISSUE THREAD

**Issue by jrudley** [pnp/powershell#2831]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

### Expected behavior 
new site created

### Actual behavior 
Error creating new site: 'Code: InvalidAuthenticationToken
Message: Access token validation failure. Invalid audience.

### Steps to reproduce behavior
connect in using app and certificate using default permissions. I added site full control application for graph as I believe application logins use graph only for site creation.
![image](https://user-images.githubusercontent.com/1934411/219759258-bd2040a0-6d97-4fb4-a7f9-39d6d434be5b.png)

`Connect-PnPOnline -Debug -AzureEnvironment USGovernmentHigh -ClientId 'xxxx' -Url 'https://contoso.sharepoint.us' -CertificatePassword $pass  -Tenant contoso.onmicrosoft.com -CertificatePath C:\contoso.pfx

$TenantSiteURL = "https://contoso.sharepoint.us" 
$HubSiteURL = "https://contoso.sharepoint.us/sites/contoso" 
$SiteCollectionAdmin1 = "contoso-admin@contoso.onmicrosoft.com" 
New-PnPSite -Verbose -debug -Type TeamSite -Title $NewSiteTitle -Alias $NewSiteAlias -Description $NewSiteDescription -Owners @($SiteCollectionAdmin1); 
`
### What is the version of the Cmdlet module you are running?
2.0.8-nightly

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by jrudley** [comment]
Just giving more examples. Using app auth:
New-PnPSite -Type TeamSite -Title 'Team Contoso' -Alias contoso
New-PnPSite: Code: InvalidAuthenticationToken
Message: Access token validation failure. Invalid audience

**Comment by jrudley** [comment]
I ran fiddler and saw it making its graph calls to graph.microsoft.com instead of graph.microsoft.us. Is there a way to tell it to use the correct endpoint? seems to ignore the -AzureEnvironment USGovernmentHigh switch

**Comment by gautamdsheth** [comment]
Yep, definitely a bug from our side. A temporary workaround would be to use a user account to connect to the tenant instead of the cert approach and then create a site. 
Will try to fix it, but can't provide ETA on that.

**Comment by gautamdsheth** [comment]
hi @jrudley , this issue has been fixed. It will now be available in tomorrow's nightly builds and the next major version whenever we release it.

Thanks for raising the issue
