### ISSUE TITLE
[BUG] Set-PnPDefaultColumnValues after call any folders with an ampersand that had a default value are lost

### ISSUE THREAD

**Issue by acou1304** [pnp/powershell#2843]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:
When the Set-PnPDefaultColumnValues command is run against a library, if that library has an '&' in one of the folder names, and that folder has a default value, the default value setting is lost after the command is executed. 

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

### Expected behavior 
Existing default column values should be unaffected.

### Actual behavior 
Other column values, particularly for folders with ampersands, their default value setting is lost.

### Steps to reproduce behavior
1. Create a library that has a content type with an MMS field
2. Within the library, create 3 folders - 'Folder A', 'Folder A & B' and 'Folder C'
![image](https://user-images.githubusercontent.com/5877069/221113885-d4ec4855-412b-44ab-907b-f633298fa2bd.png)

3. Set default values for MMS field for 'Folder A' and 'Folder A & B'
![image](https://user-images.githubusercontent.com/5877069/221114047-417b2621-6c82-4487-833d-babdb76314f5.png)
![image](https://user-images.githubusercontent.com/5877069/221114075-2ae1231f-c81b-40b0-9953-bdb2f53ff28a.png)
4. Run Set-PnPDefaultColumnValues to specify a default value for 'Folder C'
![image](https://user-images.githubusercontent.com/5877069/221114222-03c3ed90-8210-49f6-8c3d-ffcef2bf2f7b.png)
5. Review the results in SharePoint UI, noting that default column value for 'Folder A & B' thinks it exists (icon on left has green cog), but value missing.
![image](https://user-images.githubusercontent.com/5877069/221114381-24103e1f-4b49-4062-a72c-e0130cc19900.png)
![image](https://user-images.githubusercontent.com/5877069/221114423-e049bb3e-92b0-407e-8c72-21d19a352dd6.png)
![image](https://user-images.githubusercontent.com/5877069/221114454-d1eb7bc4-61af-4f20-8856-39b7e54a316d.png)

### What is the version of the Cmdlet module you are running? 
1.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@acou1304 - Can you please update to the latest release 2.1.x however you will need **PS 7.2 or later** to benefit from all the bug fixes and improvements, and let us know.

PS5 support has been dropped in the new release.

**Comment by veronicageek** [comment]
Closing as no response.

**Comment by Sheenie942** [comment]
I am experiencing this same issue with PS7.5 and PNP 3.1. Doesn't properly set when there is an ampersand in the Library Name
