### ISSUE TITLE
[BUG] -Apply-PnPProvisioningTemplate and Invoke -PnPProvisioningTemplate are not working 

### ISSUE THREAD

**Issue by KidCarson** [pnp/powershell#285]
Great Day,

I am attempting to apply a template to a SharePoint Online site, using the command - Apply-PnPProvisioningTemplate

I installed PnP Powershell version 1.20 and the following command is not working any more "Apply-PnPProvisioningTemplate" I receive an error when attempting to use the command in my script to apply Xml template to SPO site. 

 
### Reporting an Issue or Missing Feature
Apply-PnPProvisioningTemplate" command is not working. I receive the following error when attempting to use the command to apply Xml template to SPO site. I attempted to use the Invoke-PnPProvisioningTemplate and recieved the same error

"Apply-PnPProvisioningTemplate : The term 'Apply-PnPProvisioningTemplate' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At line:1 char:1 + Apply-PnPProvisioningTemplate + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : ObjectNotFound: (Apply-PnPProvisioningTemplate:String) [], CommandNotFoundException + FullyQualifiedErrorId : CommandNotFoundException"

### Expected behavior 
"Apply-PnPProvisioningTemplate with the correct file path ( example: Apply-PnPProvisioningTemplate -Path 'C:\spotemplates\testTemplate.xml') is supposed to use apply template to specified Sharepoint Online Site when ran

### Actual behavior 
When attempting to user either "Apply-PnPProvisioningTemplate" or "Invoke -PnPProvisioningTemplate" an error is recievedreceive error.

### Steps to reproduce behavior
1. Connect-PnPOnline -Url https://example-admin.sharepoint.com -UseWebLogin
2. New-PnPSite -Type TeamSite -Title 'Newtestsite42' -Alias "NewPMOtestsite42" -IsPublic
3. Apply-PnPProvisioningTemplate -Path 'C:\spotemplates\testTemplate.xml'

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 1.3.0, and SharePoint PnPPowerShellOnline 3.29.2101.0

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by joelfmrodrigues** [comment]
@KidCarson the commands are:
- Invoke-PnPSiteTemplate for SharePoint sites only
- Invoke-PnPTenantTemplate for tenant templates

**Comment by erwinvanhunen** [comment]
The cmdlet has been renamed since the 1.0  release. It's called now Invoke-PnPSiteTemplate. Same functionality, same parameters, different name. See the changelog at https://github.com/pnp/powershell/blob/dev/CHANGELOG.md for all the changes.
