### ISSUE TITLE
[BUG] New-PnPSite -SensitivityLabel

### ISSUE THREAD

**Issue by omega1119** [pnp/powershell#286]
Hi All,

apologies if this has been covered somewhere else, or if I have missed something entirely. In the old version of PnP Powershell before the migration to PnP.PowerShell, the New-PnPSite had a parameter -SensitivityLabel which is no longer present in PnP.PowerShell. Is this functionality somewhere else, or is it still going to be made available in the New-PnPSite command?

Thanks

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
It is still there. But you have to provide a -Type first. The parameters are dynamically determined based upon the type.

E.g. if you type

```
New-PnPSite -Type TeamSite 
```

Then you will be able to add -SensitivityLabel by using completion/tab. We will have to update the help files though. We'll work on that.

**Comment by omega1119** [comment]
@erwinvanhunen that works, thanks a lot!
