### ISSUE TITLE
[BUG] Incorrect documentation for Set-PnPPage

### ISSUE THREAD

**Issue by raytri** [pnp/powershell#2870]
### Reporting an Issue or Missing Feature
Incorrect documentation for **Set-PnPPage**
https://pnp.github.io/powershell/cmdlets/Set-PnPPage.html#-headerlayouttype

### Expected behavior 
The documentation should show the correct accepted values for **-HeaderLayoutType**: NoImage, ColorBlock, FullWidthImage, CutInShape

### Actual behavior 
The documentation shows incorrect accepted values:  None, Default, Custom

![image](https://user-images.githubusercontent.com/1403283/223270442-847d110b-f671-4258-9b47-a2bd5f103575.png)

### Steps to reproduce behavior

1. Go to https://pnp.github.io/powershell/cmdlets/Set-PnPPage.html#-headerlayouttype
2. Note the incorrect values listed
3. Try to use them with the cmdlet. Powershell will throw an error and provide a list of the correct values.

### What is the version of the Cmdlet module you are running?
1.3.0

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Has been fixed by @a1mery , will be available tomorrow !
