### ISSUE TITLE
Azure Automation userAssignedManagedIdentity - (401) Unauthorized [BUG] 

### ISSUE THREAD

**Issue by RoSchoe** [pnp/powershell#2882]
### Reporting an Issue or Missing Feature
Azure Automation and Connect-PnPOnline is not working with my configuration
#PS 7.1
#PNP 1.12.0

### Expected behavior 
Everything works like before with the run as account.

### Steps to reproduce behavior

I used Azure Automation with RunAsAccount with Connect-PnPOnline
$servicePrincipalConnection = Get-AutomationConnection -Name $G_ConnectionName 
$thumbprint = $servicePrincipalConnection.CertificateThumbprint
$appId = $servicePrincipalConnection.ApplicationId 
Connect-PnPOnline -Tenant $aadomain -ClientId $appId  -Thumbprint $thumbprint -Url $site
  

Now it is necessary to use the new way of managed identity. 

1. I created user managed identity (UMI)
2. With graph API and Powershell i added SharePoint Application Permission "Sites.FullControl.All" to the Enterprise App of this (UMI)
3. I added UMI to Identity (User Identity)

Now i run the code
$managedServiceObjektId = "c1594f68-NNN-NNNN-NNNN-4b53fde1ce49"
$tenantURL = "OUR_TENENTNAME.sharepoint.com"
Connect-PnPOnline -Url $tenantURL -ManagedIdentity -UserAssignedManagedIdentityObjectId $managedServiceObjektId
Get-PnPContext
Get-PnPSite

**Result**
I get 401 Unauthorized 
After 5 trials now i get   The request was canceled due to the configured HttpClient.Timeout of 100

**If i try:**
Connect-AzAccount -Identity -AccountId  $managedServiceObjektId
i get information about my UMI to console.

The Question is - did i miss sth. or is it not possible to work with managed identity like before

### What is the version of the Cmdlet module you are running?
#PS 7.1
#PNP 1.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Azure Automation

**Comment by gautamdsheth** [comment]
Can you please try with the latest nightly builds and let us know ? There have been some improvements to this authentication mode

**Comment by KoenZomers** [comment]
Works here with the latest nightly. There was an issue with this which was fixed 3 weeks ago in this PR: https://github.com/pnp/powershell/pull/2813. It did cause a timeout though, not an unauthorized, so please also double check that you have set your permissions correctly. Instructions on how to do this can be found here: https://pnp.github.io/powershell/articles/azurefunctions.html#enabling-the-managed-identity-for-an-azure-automation-runbook

**Comment by RoSchoe** [comment]
Is there a way to get the lastest nightly as upload-ready version for azure automation if i use the zip file i get "Cannot import the module of name powershell-2.0.41-nightly, as the module structure was invalid"

**Comment by RoSchoe** [comment]
@KoenZomers thanks for the link to the the documentation but it seems it is only for system managed identites not for user managed identities.

**Comment by KoenZomers** [comment]
> Is there a way to get the lastest nightly as upload-ready version for azure automation if i use the zip file i get "Cannot import the module of name powershell-2.0.41-nightly, as the module structure was invalid"

Yes, you can just add it as a ZIP file. What I do is just use `Save-Module PnP.PowerShell -AllowPrerelease -Path c:\temp\somefolder`. Once done, go into that folder and zip up all the files under the version folder inside this. Feed this to Azure Automation and it will work.

<img width="776" alt="image" src="https://user-images.githubusercontent.com/5940670/224639424-81b5b00c-52c9-46d6-935c-9abfdeed038c.png">

**Comment by KoenZomers** [comment]
> @KoenZomers thanks for the link to the the documentation but it seems it is only for system managed identites not for user managed identities.

User managed identities work in the same way. Just assign a user managed identity under Identity
<img width="630" alt="image" src="https://user-images.githubusercontent.com/5940670/224639806-460e0a6e-742e-4969-8940-a910cb23d863.png">

And then in your script connect like this:
<img width="757" alt="image" src="https://user-images.githubusercontent.com/5940670/224639657-e2806005-1f0b-4d3e-bf70-5d6194c577a5.png">

Works flawless here.

Make absolutely sure you do select PowerShell 7.2 (preview) for all of this to work though.

**Comment by gautamdsheth** [comment]
Thanks for testing it out and letting us know. 

We don’t have an ETA at the moment.

The new version will be 2.x
