### ISSUE TITLE
[BUG] Set-PnPListItem creates 2 versions

### ISSUE THREAD

**Issue by ehalsey** [pnp/powershell#2883]
### Reporting an Issue or Missing Feature
Calling the following creates 2 versions the latest not showing any property/field changes
`
Set-PnPListItem -Identity $itemIdToUpdate -List "AP Documents" -Connection $conn -Values @{"Title" = 'test from PnP PowerShell'} -UpdateType Update
`

### Expected behavior 
Only one version should be created.  The latest version should show the changes.

### Actual behavior 
Two versions created at the same time.
![Screenshot 2023-03-10 105124](https://user-images.githubusercontent.com/14900980/224401942-7e4f82c8-addc-4a69-839f-41ff3ab080b1.png)

### Steps to reproduce behavior
`
Set-PnPListItem -Identity $itemIdToUpdate -List "AP Documents" -Connection $conn -Values @{"Title" = 'test from PnP PowerShell'} -UpdateType Update
`

### What is the version of the Cmdlet module you are running?
1.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

Tested with PnP.Core 1.8.124-nightly and only one version was created.
`
            listItem["Title"] = "Item1 - Updated";
            await listItem.UpdateAsync();
`

**Comment by ehalsey** [comment]
Possibly related to #2742

**Comment by KoenZomers** [comment]
Sorry, still cannot reproduce it from my side:

![image](https://user-images.githubusercontent.com/5940670/224432834-32072563-c795-4ad0-82f8-b8b25821c5ce.png)

Can you show more of your script? Perhaps its related to something else happening before or after somehow?

**Comment by ehalsey** [comment]
Here's the script causing the issue.  Please confirm you are updating a Document Library's item.  I'll test against a list to see if there's a difference.
`
Import-Module PnP.PowerShell
$actoconn = Connect-PnPOnline -Url "https://actodev2.sharepoint.com/sites/bamertdev" -ReturnConnection -Interactive
Set-PnPListItem -Identity "2" -List "Documents" -Connection $actoconn -Values @{"Title" = 'Test Title 2'}
`

**Comment by KoenZomers** [comment]
Tried exactly the same and indeed applying it to the default document library in the site.

Could it possibly be that there are webhooks, Flows, Logic Apps or something else connected to your document library which might be doing something somehow?

**Comment by KoenZomers** [comment]
Can you try it with the latest nightly build to see if that makes a difference? I just noticed you're still on version 1.12.

```
Update-Module PnP.PowerShell -AllowPrerelease
```

Please also ensure you're using Powershell 7.2 or later, not PowerShell 5 which comes with Windows. You can check your version with

```
$PSVersionTable
```

**Comment by ehalsey** [comment]
There is a webhook on that library but just confirmed it is also happening on Documents and on a custom list w/out any webhooks. I will try the nightly and confirm PowerShell version.

**Comment by ehalsey** [comment]
Using PowerShell 7.3.3 and PnP.PowerShell 2.0.38 nightly resolved the issue.
