### ISSUE TITLE
[BUG] Invoke-PnPSPRestMethod ignores -Content when using the MERGE verb

### ISSUE THREAD

**Issue by joshtransient** [pnp/powershell#289]
### Expected behavior
A sample command of:
```
Invoke-PnPSPRestMethod -Method Merge -Url "/_api/Web/Lists(guid'63720396-f888-41b7-bb11-bd5005e8148e')" -Content '{ "MajorVersionLimit":100 }' -ContentType 'application/json;odata=nometadata'
```
...should silently succeed.

### Actual behavior
Results in the error message "The given key was not present in the dictionary." When running a 
[Fiddler trace](https://github.com/pnp/powershell/files/5990328/invoke-merge.zip), the TextView shows that no content was passed to the endpoint. For comparison, the first request in the linked SAZ was done with a standard `Invoke-RestMethod` using the same authentication token.

### Steps to reproduce behavior
Open Fiddler and run the aforementioned sample command using a valid GUID from a list or document library.

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 1.3.0
PowerShell 7.1.2

### Which operating system/environment are you running PnP PowerShell on?
(have not tested on other platforms)
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
Good catch! Indeed, refactoring the old cmdlet ot the new module introduced this bug. We'll work on a fix.

**Comment by erwinvanhunen** [comment]
Fix added, it will be avialable in tomorrow's nightly build
