### ISSUE TITLE
[BUG] Add-PnPFieldFromXml - creates "invisible" columns

### ISSUE THREAD

**Issue by Haulund-ATP** [pnp/powershell#2890]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
When calling Add-PnPFieldFromXml - with af column URL encoded with a space ("_x0020_") the column is not displayed under site columns nor at the site contenttype who is using it.
But, if you access it through the URL directly ("https://{YOURDOMAIN"}.sharepoint.com/sites/{SITENAME}/_layouts/15/FldEdit.aspx?Field=Access_x0020_updated") it is displayed.

### Expected behavior 
The site column is displayed.
### Actual behavior 
The column is "invisible" but can be seen directly. 

### Steps to reproduce behavior
Export contenttype with site column URL encoded with a space (" "/"_x0020_") in it. Then import it back on another site.

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

1.12.0 

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows

**Comment by veronicageek** [comment]
@Haulund-ATP - Can you please first update to the latest nightly. If you're still on PS5 it will be `1.12.80`, if you're using PS7 then just run `Update-Module PnP.PowerShell -AllowPrerelease` directly. Thanks

**Comment by Haulund-ATP** [comment]
Hi

I have now updated - and tried to use PowerShell 7

Still no luck

***@***.***

***@***.***

Venlig hilsen
Thomas Haulund-Aadorf - THHA


Fra: Veronique Lengelle ***@***.***>
Sendt: 13. marts 2023 18:08
Til: pnp/powershell ***@***.***>
Cc: Thomas Haulund-Aadorf - THHA ***@***.***>; Mention ***@***.***>
Emne: Re: [pnp/powershell] [BUG] Add-PnPFieldFromXml - creates "invisible" columns (Issue #2890)

You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

@Haulund-ATP<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHaulund-ATP&data=05%7C01%7CTHHA%40atp.dk%7Cdc34cc3abb024abd812e08db23e59161%7C6a54fe9ea8c14576909657b0f2d62cd5%7C0%7C0%7C638143241147583201%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Mkv5ytT7rZk5To6roZLalRFIrnE1VnL2sow%2FCGa2LTY%3D&reserved=0> - Can you please first update to the latest nightly. If you're still on PS5 it will be 1.12.80, if you're using PS7 then just run Update-Module PnP.PowerShell -AllowPrerelease directly. Thanks

-
