### ISSUE TITLE
Copy-PnPFile -SourceUrl $url -TargetUrl $urll -force will not preserve the version history

### ISSUE THREAD

**Issue by mvcsharepointdev** [pnp/powershell#2894]
Reporting an Issue 

### Expected behavior 
Since we did not specify `IgnoreVersionHistory` the version history should be preserved.

### Actual behavior 
The copied file will not have any version history

### Steps to reproduce behavior
I run this command >>which removed the .lock extension from a file and copy the renamed file:-

`#Get the previous Version's Label
 $VersionLabel = $Item.File.Versions[$Item.File.Versions.Count-1].VersionLabel
$url = $item.File.ServerRelativeUrl
Write-Host "$(Get-Date) - ($($Counter)/$($AllItems.Count)) - Restoring version $VersionLabel for $($Item.File.Name)"
$item.File.Versions.RestoreByLabel($VersionLabel)
Invoke-PnPQuery
			    
$restoedFile =  Get-PnPFile -Url $url 

$urll = $url.Replace(".lock","")
			    
Copy-PnPFile -SourceUrl $url -TargetUrl $urll -force

### What is the version of the Cmdlet module you are running?
ModuleType Version    Name                                ExportedCommands                                                                                                   
---------- -------    ----                                ----------------                                                                                                   
Manifest   1.12.0     PnP.PowerShell                      {Add-PnPAdaptiveScopeProperty, Add-PnPPropertyBagValue, Add-PnPSiteClassification, Copy-PnPFolder...}              
Manifest   1.11.0     PnP.PowerShell                      {Add-PnPAdaptiveScopeProperty, Add-PnPPropertyBagValue, Add-PnPSiteClassification, Copy-PnPFolder...}              
Manifest   1.6.0      PnP.PowerShell                      {Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add-PnPClientSideText, Add-PnPClientSideWebPart...}   

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows

**Comment by veronicageek** [comment]
@mvcsharepointdev - A new version of CSOM has been released last week (which we are consuming), can you please update to the latest release `2.1.x` however you will **need PS `7.2` or later** to benefit from it. 

PS5 support has been dropped in the new release.

**Comment by veronicageek** [comment]
Closing as no response.
