### ISSUE TITLE
No results with Sync-PnPSharePointUserProfilesFromAzureActiveDirectory

### ISSUE THREAD

**Issue by ruben1980** [pnp/powershell#2896]
### Reporting an Issue or Missing Feature
No result while running Sync-PnPSharePointUserProfilesFromAzureActiveDirectory. In the example below, I have removed the last name from a user profile in SharePoint Online. After successful synchronisation, this one remains empty.

### Expected behavior 
Same profile properties default or custom from AAD in SharePoint Online Profile Database

### Actual behaviour 
No results after the following confirmation, however JSON is created:

VERBOSE: Using provided user collection containing 1 user
VERBOSE: Creating mapping file, uploading it to SharePoint Online to folder 'sync' and executing sync job
VERBOSE: Job initiated with Id aa29a949-e7eb-43bd-9fb0-d23912841e94 and status Submitted for file https://###.sharepoint.com/sites/sync/sync/userprofilesyncdata-20230315101753-8c206c89d1134fc8a45d1f2ca6d68a07.json

### Steps to reproduce behavior

$prodsyncsite = 'https://###.sharepoint.com/sites/sync'
$adminurl = 'https://###-admin.sharepoint.com/'
Connect-PnPOnline -Url $adminurl -Interactive
$users = Get-PnPAzureADUser -identity username@###.##
Connect-PnPOnline -Url $prodsyncsite -Interactive

$sync = Sync-PnPSharePointUserProfilesFromAzureActiveDirectory -UserProfilePropertyMapping @{"LastName"="Surname"} -Users $users -Folder "sync" -Verbose

#Check status
Get-PnPUPABulkImportStatus -JobId $sync.JobId

### What is the version of the Cmdlet module you are running?
PnP 1.12.0
PS  7.3.2

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Hii, did you follow the instructions in the docs mentioned here ? 

https://pnp.github.io/powershell/cmdlets/Sync-PnPSharePointUserProfilesFromAzureActiveDirectory.html

It requires couple of Graph permissions as well as changes via the ACS page.

**Comment by veronicageek** [comment]
Closing as no response.
