### ISSUE TITLE
[FEATURE] - Add ability to simply manage the use of RequestDigest value in REST calls to ODSP 

### ISSUE THREAD

**Issue by joerodgers** [pnp/powershell#2898]
I would like a new cmdlet called Get-PnPRequestDigest to retrieve a fresh request digest value for use in custom REST calls to ODSP.  

Alternatively, having the ability to optionally include the X-REQUESTDIGEST header value using the existing Invoke-PnPSPRestMethod (maybe a -IncludeRequestDigestHeader switch) call would be a great enhancement.

**Describe the solution you'd like**
Would like one or both of the following enhancements:

a. Add a cmdlet like Get-PnPRequestDigest to retrieve a fresh request digest value to use in building manual REST calls

``` Powershell
    $digest = Get-PnPRequestDigest # <-- NEW REQUEST
    $token = Get-PnPAccessToken -ResourceTypeName SharePoint
    
    $headers = @{}
    $headers.Accept            = "application/json"
    $headers."Content-Type"    = "application/json"
    $headers.Authorization     = "Bearer $token"
    $headers."X-HTTP-Method"   = "MERGE"
    $headers."X-REQUESTDIGEST" = $digest

    Invoke-RestMethod `
        -Method  POST `
        -Uri     "$($Web.Url)/_api/web/RootFolder" `
        -Body    "{`"WelcomePage`":`"$path`"}" `
        -Headers $headers

```

b. Add an option switch to Invoke-PNPSPRestMethod to automatically include the X-REQUESTDIGEST request header.  These would likely also request a new optional parameter to set the X-HTTP-Method header value as well.

``` Powershell
Invoke-PnPSPRestMethod `
    -Method      POST `
    -Url         "/_api/web/RootFolder" `
    -Content     $json `
    -ContentType "application/json" `
    -IncludeRequestDigest `
    -XHTTPMethod "MERGE"
```

**Describe alternatives you've considered**

Used the following to retrieve the digest value and manually build and executed REST call using Invoke-RestMethod
``` Powershell
    $context = Get-PnpContext

    $digest = [Microsoft.SharePoint.Client.ClientContextExtensions]::GetRequestDigestAsync( $context ).GetAwaiter().GetResult()
```
**Additional context**
I needed to set the WelcomePage URL for a few thousand webs, had to use the GetRequestDigestAsync method and build my own REST headers to allow the POST to succeed.

**Comment by gautamdsheth** [comment]
Did you try this cmdlet ?? 

https://pnp.github.io/powershell/cmdlets/Set-PnPHomePage.html

**Comment by joerodgers** [comment]
No, but that's a huge unblock because of the -ResourceTypeName option not being available in my client's module version (1.7).

**Comment by gautamdsheth** [comment]
Also, there is `Invoke-PnPSPRestMethod` as well which by default adds the request digest to the requests.

Do you still require it ?

**Comment by gautamdsheth** [comment]
hi @joerodgers , am going to close this request since you no longer need it.

We already add `X-HTTP-Method` header when `MERGE` request is specified, I guess that would be enough.
