### ISSUE TITLE
[Question] Connect-PnPOnline only works with PnPManagementShell?

### ISSUE THREAD

**Issue by waaromikniet** [pnp/powershell#29]
Will this version of PnP-PowerShell only work with the PnPManagementShell? Or own custom App registration? 
For my organization tenants I  am not allowed to add the PnPManagementShell permissions to my account in Azure AD. 
So we just want to use an account that is SharePoint administrator.

**Comment by erwinvanhunen** [comment]
you can use custom app registrations, no problem at all.

**Comment by waaromikniet** [comment]
So an app registration or the PnPManagementShell is a must? Username password is no longer supported?
