### ISSUE TITLE
[BUG] Add-PnPSiteCollectionAdmin returns user not found

### ISSUE THREAD

**Issue by LouFarho** [pnp/powershell#291]
### Expected behavior 
Provide a string array of users to add as a site collection administrators after site creation.

### Actual behavior 
Add-PnPSiteCollectionAdmin -Owners $SiteAdministrators
WARNING: Unable to add user as it wasn't found. User will be skipped.
WARNING: Unable to add user as it wasn't found. User will be skipped.
WARNING: Unable to add user as it wasn't found. User will be skipped.

### The adim url was connected using the -Interactive prior
New-PnPTenantSite -Url $SiteURL -Owner $username -Title $SiteTitle -Template $Template -TimeZone $TimeZone -RemoveDeletedSite -Wait

### Pause to make sure everything is setup and propagated despite the -Wait
Start-Sleep -Seconds 30

$SiteAdministrators = @("user1@contoso.com", "user2@contoso.com", "user3@contoso.com")

### Tried this because of the error when using the above just in case.
$SiteAdministrators = @("i:0#.f|membership|user1@contoso.com", "i:0#.f|membership|user2@contoso.com", "i:0#.f|membership|user3@contoso.com")

Connect-PnPOnline -Url $SiteURL -Interactive
Add-PnPSiteCollectionAdmin -Owners $SiteAdministrators

### What is the version of the Cmdlet module you are running?
This is a G3 GCC tenant. The login running the script does have MFA. The current user was added as a site collection admin as part of the creation of the site. This script was running without issues using the old PnP module latest release. After updating to PnP.PowerShell various scripts have had to be modified. The users were added manually without issue. 

PnP.PowerShell 1.3.0  

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
It might be a bit unintuitive, given the cmdlet name (we'll see if we can come up with acceptable solution to fix this): but you need to add the user first to the site. The reason for that is that we try to find the user first inside the site and then we flip the 'IsSiteAdmin' property on that user. E.g. the user needs to be present in the site first.

This should work:

```powershell
$owners = Get-PnPGroup -AssociatedOwnerGroup
Add-PnPGroupMember -LoginName "user@domain.com" -Group $owners
Add-PnPSiteCollectionAdmin -Owners "i:0#.f|membership|user@domain.com"
```

Alternatively you can use (if you're a tenant admin), you do not need to connect to the tenant admin site as PnP PS will do that for you behind the scenes (notice, if your tenant admin site url is not https://[tenant]-admin.sharepoint.* you can specify the -TenantAdminUrl parameter during connect time)

```powershell
Set-PnPTenantSite -Owners user@domain.com
```

**Comment by erwinvanhunen** [comment]
I just merged a fix for the cmdlet. It will be available in tomorrow's nightly build.
