### ISSUE TITLE
Set-PnPUserProfileProperty with Managed Identity

### ISSUE THREAD

**Issue by dzejzipl** [pnp/powershell#2915]
Hey all,
I'm trying to use Set-PnPUserProfileProperty with Managed Identity using Azure Automation accounts.
I'm using code:
``` powershell
$urlOfSharepoint = "https://myTenant-admin.sharepoint.com"
Connect-PnPOnline -url $urlOfSharepoint -ManagedIdentity
Set-PnPUserProfileProperty -Account $UserAccount -PropertyName "myCustomValue" -Value "1111"
```
But receiving the error:
**This operation requires you to be managing your own data or have administrator privileges.**

My managed identity have permissions:

![Screenshot 2023-03-20 125813](https://user-images.githubusercontent.com/13648944/226332793-dcc22137-f226-4fcf-a44d-98bbdde6442b.png)

And... or now I'm stuck how to change custom properties in Sharepoint for all users using managed identity.

This code was working earlier on manual execution and global admin account.

Runtime version is 7.2
PNP.Powershell module is 1.12.0

**Comment by gautamdsheth** [comment]
This is an authentication issue on Microsoft's side of things.

Please follow the steps mentioned here:

https://github.com/pnp/powershell/issues/277#issuecomment-847950108

Bottom line here, is that you will need to change auth mechanism and use `ClientId+Secret` using ACS for setting properties in app-only authentication. 

Once Microsoft fixes the issue, the managed identity will start working for this cmdlet as well.

**Comment by dzejzipl** [comment]
Ah, so it's clear for now. I will use the managed identity for Graph queries and ACS for SharePoint changes.
Many thanks.
