### ISSUE TITLE
[FEATURE] Add Set-PnPMicrosoft365Group

### ISSUE THREAD

**Issue by svermaak** [pnp/powershell#2929]
**Is your feature request related to a problem? Please describe.**
New-PnPMicrosoft365Group has option for ResourceBehaviorOptions

**Describe the solution you'd like**
Can this ResourceBehaviorOptions, TeamResourceBehaviorOptions etc. parameter be added to Set-PnPMicrosoft365Group

**Describe alternatives you've considered**
I am using Exchange Management Shell

**Additional context**
Not sure where Set-PnPMicrosoft365GroupSettings comes into play

**Comment by KoenZomers** [comment]
Sure. Good idea. On it.

**Comment by KoenZomers** [comment]
Done
