### ISSUE TITLE
[ENHANCEMENT] Deprecate -BlockEdit and -BlockDeletion parameters on Set-PnPLabel

### ISSUE THREAD

**Issue by martinlingstuyl** [pnp/powershell#2932]
Using the commandlet [Set-PnPLabel](https://pnp.github.io/powershell/cmdlets/Set-PnPLabel.html) you can apply a default retention label to lists and libraries. While doing that you can use the `-BlockEdit` and `-BlockDeletion` parameters to configure label settings. 

However, this has been a concern for some time (because these settings allow you to override the retention label settings in Microsoft Purview) That's the reason they have been disabled in the CSOM and REST API's. Using them is ignored by Microsoft, Microsoft will simply look up the correct values for both properties and use them in the label application. 

You can test this by applying a record retention label as a default to a list or libary and specify $false as a value for BlockEdit and BlockDelete. (A record-type label should have the value `true` on both these parameters)
After applying the label you can retrieve the applied label settings. You'll see your falsy values have been ignored.

```posh
Set-PnPLabel -List "TestLibrary" -Label "Test Recordlabel" -BlockDeletion:$false -BlockEdit:$false
Get-PnPlabel -List "TestLibrary"
```

These properties should therefore be deprecated and removed from the codebase.

**Comment by martinlingstuyl** [comment]
Because this is a breaking change, is this something we should add to v2?

**Comment by gautamdsheth** [comment]
Hmm, if its disabled by CSOM/REST , maybe we can mark it as obsolete and point them to the correct cmdlet ? 

cc @KoenZomers

**Comment by martinlingstuyl** [comment]
Hi @gautamdsheth,

The commandlet should not be disabled itself. You can still set default retention labels on lists.
The only thing you can no longer do is customize the label settings by using `blockDelete` and `blockEdit` properties.

So these parameters are the only things that need to be deprecated.

**Comment by gautamdsheth** [comment]
Ahh ok, lets deprecate them then.
We can get rid of these params a bit later then sometime.

Would you like to submit a PR for that ?

**Comment by martinlingstuyl** [comment]
You can assign me

**Comment by gautamdsheth** [comment]
Do we have any purview related cmdlet for this in PnP PowerShell ? Maybe we can guide users to that ?

**Comment by martinlingstuyl** [comment]
I haven't found commandlets to manage Purview retention labels in PnP PowerShell. (We do have them in the CLI 😏)
What we do have in pnp powershell is the possibility to apply these retentionlabels to listitems.

**Comment by KoenZomers** [comment]
Correct, we don't have cmdlets yet to add/modify/remove Purview labels. I would very much welcome a PR on that if you have time @martinlingstuyl.

**Comment by martinlingstuyl** [comment]
That's okay, I've worked with it a lot so that should not be hard. I'll add it to my backlog. 🤙

**Comment by martinlingstuyl** [comment]
No promises on when though..

**Comment by gautamdsheth** [comment]
no worries @martinlingstuyl , thank you so much already for all your help 😊🙏

**Comment by gautamdsheth** [comment]
@martinlingstuyl  - what's the API that you use in the CLI for adding/modifying/remove Purview labels ? I might try to take a stab at it :)
