### ISSUE TITLE
[BUG] Diacritics / accents not working properly

### ISSUE THREAD

**Issue by SurinameClubcard** [pnp/powershell#2935]
### Reporting an Issue or Missing Feature
I'm trying to use diacritics (see https://en.wikipedia.org/wiki/Diacritic), sometimes called accents, in document library column titles, site column names and site column choices. However, they eventually do not render correctly. 

### Expected behavior 
Proper conversion of accents.

### Actual behavior 
E.g.,

```
Get-PnPField | Where {$_.InternalName -eq "SiteColumn"} | Remove-PnPField -Force
Add-PnPField -DisplayName "Site Cólumn" -InternalName "SiteColumn" -Type Choice -Choices "á","ë","ò"
```

becomes column name

![afbeelding](https://user-images.githubusercontent.com/1786575/227532922-ed6b5d3a-a5c4-44b6-be5f-317904604bbb.png)

with choices

![afbeelding](https://user-images.githubusercontent.com/1786575/227532987-c6a50b12-7b56-41ef-8835-cd0133d753ac.png)

### Steps to reproduce behavior
See above code example.

### What is the version of the Cmdlet module you are running?
Version 1.12.

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
hi @SurinameClubcard , can't reproduce this issue.

Tried the exact cmdlet that you mentioned and it added the values correctly:

<img width="194" alt="image" src="https://user-images.githubusercontent.com/8832018/230399162-2be1bda9-11d2-49bb-aac4-b17887c32129.png">


Can you please try with the latest version , 2.1.1 and let us know ? Do remember this requires PS 7.2 or later version to be installed on the machine. We have dropped PS 5.1 and ISE support in v2.1.1.

**Comment by SurinameClubcard** [comment]
Upgrading both PowerShell and the PnP module to the latest versions fixed this problem. Thanks and sorry for not trying this myself before opening this issue here.
