### ISSUE TITLE
[BUG] Add-PnPFile is uploading the files but not setting the -Values on some of the files during migration

### ISSUE THREAD

**Issue by potluri96** [pnp/powershell#2937]
### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

When using Add-PnPFile and setting -Values the files are getting uploaded in a Sharepoint library but some of the values are not getting set in the columns. This behavior is not throwing any errors.

### Expected behavior 

The file gets uploaded and the values are set in library columns 

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

The files are uploaded but the metadata is not updated on some of the files

### Steps to reproduce behavior

Uploading 10K files using add-pnpFile 

Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

1.12

### Which operating system/environment are you running PnP PowerShell on?
Windows

**Comment by gautamdsheth** [comment]
Can you please specify which values are not getting set ? 
Instead of 10k files, please try with a single file will help you reproduce it easier

**Comment by veronicageek** [comment]
@potluri96 - Can you please update to the latest release `2.1.x` however you **will need PS 7.2 or later** to benefit from all the bug fixes and improvements.

PS5 support has been dropped in the new release.

Feel free to reopen if the issue persists. Thanks.

**Comment by laurencecrummay-dol** [comment]
I am experiencing this issue, PS 7.4.3 & PNP 2.5.0

`Add-PnPFile -Path ".\66780.jpg" -Folder "Shared Documents" -Values @{"Modified" =[System.DateOnly]::Parse("12/12/2016"); "Title" = "dog" }`

Expected results would see the modified date set as shown, actual result shows the current date/time.

The Title attribute is set correctly

![image](https://github.com/user-attachments/assets/47d762d3-3040-40fe-8195-7d31f6e6d2ce)

**Comment by laurencecrummay-dol** [comment]
Tried the advice here 
https://github.com/pnp/powershell/discussions/1853

```
Line |
  17 |  $listItem = Get-PnPFile -Url $file_url -AsListItem
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The object specified does not belong to a list.
```
