### ISSUE TITLE
Using commands with Managed Identity connection are returning 401 "Sometimes" [BUG]

### ISSUE THREAD

**Issue by rogers14k** [pnp/powershell#2946]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: 

   Using Connect-PnPOnline -Url [Site] -ManagedIdentity

1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?**

   Not entirely sure. I sometimes am getting a 401 error when running any command.

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

   Sometimes receiving a 401 error when attempting to use any cmd after connecting to PnP using a managed identity inside 
   an Azure 
   Runbook.

   Connect-PnPOnline -Url [Site] -ManagedIdentity
   Get-PnPList

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

   An output of the list on the SharePoint site all the time and not sometimes.

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

   Get-PnPList: 
   Line |
      3 |  Get-Pnplist
        |  ~~~~~~~~~~~
        | The remote server returned an error: (401) Unauthorized.

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

   Followed instructions from https://pnp.github.io/powershell/articles/azureautomationrunbook.html and using the latest 
   prerelease/nightly build version. The app has Sites.ReadWrite.All and Sites.FullControl.All. I am using runtime 7.2 for both the module and runbook.**

### What is the version of the Cmdlet module you are running?

   2.0.53     nightly

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [X] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by KoenZomers** [comment]
I've actually also run into this a couple of times. Couldn't figure out what's causing the randomness in it. Could you run your Connect-PnPOnline with -Verbose and see if that helps any in trying to find out when it works and when it does not?

**Comment by rogers14k** [comment]
> I've actually also run into this a couple of times. Couldn't figure out what's causing the randomness in it. Could you run your Connect-PnPOnline with -Verbose and see if that helps any in trying to find out when it works and when it does not?

I just tested Connect-PnPOnline with -Verbose 10x and it connected fine each time. Last time I checked -Verbose shouldnt help with establishing a connection unless its somehow different with runbooks? Im pessimistic and think I just got lucky connecting to PnP each time.

**Comment by KoenZomers** [comment]
You're correct, it doesn't do anything different in the connection, it just logs a bit more around getting the token through, in this case, managed identities. Try it a few more times if you can at a different time. To me it felt like when it doesn't work, it doesn't for a while and when it does, it does for a while as well.

**Comment by gautamdsheth** [comment]
When it comes to runbooks, you should ideally store the output of the cmdlets in a variable , something like this:

```
$conn = Connect-PnPOnline
$list = Get-PnPList
````

Not sure why, but it usually helps

**Comment by KoenZomers** [comment]
There's technically really no explanation why that could make a difference :) But if you want to try it anyway, be sure to use $conn = Connect-PnPOnline **-ReturnConnection** and $list = Get-PnPList **-Connection $conn** or it will not do anything at all for sure :)

**Comment by KoenZomers** [comment]
> Do we need to configure the managed identity?

Nothing goes without configuration :)

Follow these steps:
https://pnp.github.io/powershell/articles/azureautomationrunbook.html#by-using-a-managed-identity

**Comment by ThierryPermentier** [comment]
What version of Powershell and Pnp.Powershell do you use to perform these steps? I got an error "System.Management.Automation, Version=7.2.0.0 not found" when using PnP.Powershell 2.0.55-nightly. I have instelled Powershell 7.3.3 under Windows.

**Comment by gautamdsheth** [comment]
Thanks @rogers14k , closing this as resolved
