### ISSUE TITLE
[BUG] Get-PnPMicrosoft365Group -Filter Parameter Invalid

### ISSUE THREAD

**Issue by shcrist** [pnp/powershell#2947]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
While the documentation describes a Filter parameter for advanced queries, the parameter does not appear to be available. 

### Expected behavior 
-Filter parameter allows for an advanced query.

### Actual behavior 
![image](https://user-images.githubusercontent.com/32545974/228312144-2239be7f-615e-4048-94b1-5208fd67f65e.png)

### Steps to reproduce behavior
Load PnP.PowerShell model
Attempt Get-PnPMicrosoft365Group -Filter [add a filter]

### What is the version of the Cmdlet module you are running?
![image](https://user-images.githubusercontent.com/32545974/228312528-f2028bb3-9577-407a-81e4-ffde4643c1a4.png)

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
Indeed - Tested OK with `1.12.80` but param is not available in `1.12.0`.

FYI - @gautamdsheth @KoenZomers

**Comment by KoenZomers** [comment]
Looks as expected then, no? It wasn't there in 1.12.0 but is available in a later version thus means it has been added after that release 🙂

**Comment by shcrist** [comment]
So it's in a minor version release, but not a major. Any idea when a new major release will be coming? They won't upgrade our platform until it's a major release. Appreciate the quick responses.

**Comment by KoenZomers** [comment]
We are currently aiming for next Friday. No absolute guarantees though. We need to get several people together to make it possible. Trying to align agendas at the moment.

**Comment by KoenZomers** [comment]
Closing issue as it works as designed.
