### ISSUE TITLE
[FEATURE] Set-PnPListItem -UpdateType option to create new version but not trigger flow

### ISSUE THREAD

**Issue by Patrick959** [pnp/powershell#2956]
**Is your feature request related to a problem? Please describe.**
I use powershell frequently to update lists with Power Automate flows.  There is no way to update the list item, create a new version (need for audit tracking) and NOT trigger the flow on the list from running.

**Describe the solution you'd like**
I new option for -UpdateType that creates a new version and does not trigger any flows

**Describe alternatives you've considered**
I currently work around this by setting a field that breaks out of the flow after trigger.  Not really the best solution

**Additional context**

**Comment by KoenZomers** [comment]
I don't believe there's technically a way to do such a thing today. You mention you break out of the flow after triggering. I guess you're using a condition action for that? You could consider using a Trigger Condition in your trigger instead, which would be much cleaner in this case.

<img width="303" alt="image" src="https://user-images.githubusercontent.com/5940670/229277657-e2c13bbb-2d72-4e1b-a58c-af140ca6ef7f.png">

You can find it under the three dots of your trigger and then go to Settings.
