### ISSUE TITLE
Connect-PnPOnline fails after updating PnP.PowerShell to v2.1.1

### ISSUE THREAD

**Issue by Subi-Sri** [pnp/powershell#2973]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting
As part of connecting to SharePoint to download files, I've been using "Connect-PnPOnline" and it was working fine, until I updated the "PnP.Powershell" library to v2.1.1
After the update the same PS script which ran successfully fails with the following error:

_**Error: The 'Connect-PnPOnline' command was found in the module 'PnP.PowerShell', but the module could not be loaded. For more information, run 'Import-Module PnP.PowerShell'.**_

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets
Connect-PnPOnline should be working as before

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.
Error: The 'Connect-PnPOnline' command was found in the module 'PnP.PowerShell', but the module could not be loaded. For more information, run 'Import-Module PnP.PowerShell'.

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)
Connect-PnPOnline -Url $url -Credentials $cred

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
v2.1.1

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by LiyuanWang123** [comment]
Had the same issue. For us, it is Add-PnPStoredCredential command and Import-Module does not solve it either. Also opened a discussion ticket here: https://github.com/pnp/powershell/discussions/2964

**Comment by veronicageek** [comment]
@Subi-Sri @LiyuanWang123 - v2.1.1 does not support PS5 nor the ISE, you need to use PS7.

If you are still using PS5, you can use v1.12.0 however bug fixes and improvements will only be done on the 2.x releases in the future.

**Comment by Subi-Sri** [comment]
@veronicageek We are using PS7 though.

**Comment by LycheeYum** [comment]
<img width="618" alt="image" src="https://user-images.githubusercontent.com/7239280/230154208-648768ab-75e8-455c-aa98-c00a28176b1a.png">

**Comment by LycheeYum** [comment]
Thank you!  Turns out I was on PowerShell 5 The $PSversionTable command is handy.  I assumed that I was on 7 since I ran the installer for it without issue.

This time I installed PS 7 from the Microsoft Store and all is well.

![image](https://user-images.githubusercontent.com/7239280/230221059-a659aebd-6a9c-446a-90c3-c6e18711ed87.png)

 Thanks again!
