### ISSUE TITLE
[BUG] - Unable to create teams using New-PnPTeamsTeam

### ISSUE THREAD

**Issue by harshdamaniahd** [pnp/powershell#2977]
Unable to create teams using New-PnPTeamsTeam. The pnp powershell version is 2.1.1
The Group is created, but the team never gets created.
When i user owner attribute , i get this error
```
New-PnPTeamsTeam: 
Line |
   5 |  $team = New-PnPTeamsTeam -DisplayName "write2" -Visibility Private  - …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Bad Request (400): /me request is only valid with delegated authentication flow.
```

I am using managed identity in azure runbook. Following permissions are given to managed identity
![image](https://user-images.githubusercontent.com/11780473/230043231-e678ae16-8e6d-440d-8265-bcdea2d3a36f.png)

When i create the team locally , it works

here is the code in runbook

```

$connection = Connect-pnponline -managedidentity -url "https://test-admin.sharepoint.com" -returnconnection;
Write-Output $connection
try
{
$team = New-PnPTeamsTeam -DisplayName "write3" -Visibility Private  -connection $connection -Owners "test@365909m365.onmicrosoft.com"
}
catch
{
    Write-Output $error
}


```

**Comment by gautamdsheth** [comment]
Looks like there is Graph API permissions changed, can you also please add `TeamMember.ReadWrite.All` application permission as well to the App and try ?

**Comment by harshdamaniahd** [comment]
> Looks like there is Graph API permissions changed, can you also please add `TeamMember.ReadWrite.All` application permission as well to the App and try ?
Yep i tried and same error 
![image](https://user-images.githubusercontent.com/11780473/230121819-dbccc7f9-743b-4234-86ab-55d7324268e5.png)

**Comment by harshdamaniahd** [comment]
> Ok that's strange, I got a specific error message asking me to add the `TeamMember.ReadWrite.All` permission.
> 
> In case of Managed identity, it sometimes takes quite a some time for the updated permissions to be reflected in the access token.
> 
> Thanks for letting us know, will close the issue now.

Unfortunately, I still get this error

```
New-PnPTeamsTeam: 
Line |
   5 |    $Team=New-PnPTeamsTeam -DisplayName "test24" -Visibility Private -c …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Bad Request (400): /me request is only valid with delegated authentication flow.
```

It only occurs when we user -Owners attribute,
`$team = New-PnPTeamsTeam -DisplayName "write3" -Visibility Private  -connection $connection -Owners "test@365909m365.onmicrosoft.com"`

**Comment by khha** [comment]
I have the same issue from an azure function under an managed identity. 

- When I try "New-PnPMicrosoft365Group" I got error "An error occurred while processing this request". 
- When I try "New-PnPTeamsTeam" I got the error "Bad Request (400): /me request is only valid with delegated authentication flow."

How to Teamify from an azure function under managed identity?
