### ISSUE TITLE
[FEATURE] New command "Move-PnPTerm"

### ISSUE THREAD

**Issue by dbahnms** [pnp/powershell#2978]
Currently we sync our organisation structure to sharepoint termstore.
If the structure (path) change, we have to delete terms and to create them on another path.
If we do that, a new ID for this term is created.
But this ID is used for tagging the department / company to our sharepoint sites.
Moving terms via GUI (global termstore) is possible but no powershell command is available for it.

Solution:
new command "Move-PnPTerm"

Alternatives:
Adding a Parameter to New-PnPTerm for a custom ID

I would be very grateful for other ideas. Thx.

**Comment by gautamdsheth** [comment]
Closing this as the PR been merged and the cmdlets are now available in the nightly builds !
