### ISSUE TITLE
[FEATURE] Change Register-PnPManagementShellAccess -ShowConsentUrl URL

### ISSUE THREAD

**Issue by ToddKlindt** [pnp/powershell#299]
**Is your feature request related to a problem? Please describe.**
When you run Register-PnPManagementShellAccess -ShowConsentUrl the Application Registration URL requires the Global Admin to find the TenantID.

**Describe the solution you'd like**
The same URL works with the tenant _name_, which the requestor can provide, saving the Global Admin the step of looking the Tenant ID up. Right now the cmdlet says to share  https://login.microsoftonline.com/{azure-tenant-id}/adminconsent?client_id=31359c7f-bd7e-475c-86db-fdb8c937548e I would like to change that to replace {azure-tenant-id} with tenantname.onmicrosoft.com, like this: https://login.microsoftonline.com/_tenantname.onmicrosoft.com_/adminconsent?client_id=31359c7f-bd7e-475c-86db-fdb8c937548e

**Describe alternatives you've considered**
The requestor can find the Tenant ID on their own, but it seems unnecessary if the Tenant name works too.

**Comment by gautamdsheth** [comment]
So maybe an additional parameter like TenantName would be ok ? Do note that not all tenants have [tenant-name].onmicrosoft.com names, some have .us , .de etc as well especially those in non commercial cloud environments

**Comment by ToddKlindt** [comment]
It's not a parameter, it's text that the command writes to the screen: 
![image](https://user-images.githubusercontent.com/2659747/108405109-5062c880-71e6-11eb-83ed-4ec2947c7b12.png)
I do understand better now why it says TenantID instead of tenant name given all the different TLDs.

**Comment by erwinvanhunen** [comment]
I've been thinking or rewriting it to {azure-tenant-id-or-domain} but not sure if that explains it better.

Alternatively we add an optional parameter to the parameter set that allows someone to run 

```powershell
Register-PnPManagementShellAccess -ShowConsentUrl -Tenant contoso.onmicrosoft.com
```

If specified no login is required.

**Comment by gautamdsheth** [comment]
@ToddKlindt  - closing this. Have improved the messaging a bit for consent URL to make it clearer. Some tenants wont have Azure subscription, so renamed it M365 tenant ID.
Also, if you specify the tenant name param, we don't start the auth flow, simply display the URL.
