### ISSUE TITLE
[BUG] PnP.PowerShell module doesn't work at the same time with other modules using Microsoft.Identity.Client

### ISSUE THREAD

**Issue by Nazul** [pnp/powershell#3010]
### Reporting an Issue or Missing Feature
Previous versions of PnP.PowerShell module supported Windows PowerShell 5.1, however, the latest versions (2.x) no longer support it, and we need to move to PowerShell 7.x. However, this module is not working correctly with other modules that also use Microsoft.Identity.Client due to version conflict. To be specific, with PowerApps.Administration.PowerShell.

### Expected behavior 
Any of the following examples should work:

Explicit loading, PnP first, then Power Apps admin
```
Import-Module PnP.PowerShell
Import-Module PowerApps.Administration.PowerShell
$cred = Get-Credential
Connect-PnPOnline -Credentials $cred -Url 'https://tenant-admin.sharepoint.com'
Add-PowerAppsAccount -Username $cred.Username -Password $cred.Password
```

Explicit loading, Power Apps admin first, then PnP
```
Import-Module PowerApps.Administration.PowerShell
Import-Module PnP.PowerShell
$cred = Get-Credential
Add-PowerAppsAccount -Username $cred.Username -Password $cred.Password
Connect-PnPOnline -Credentials $cred -Url 'https://tenant-admin.sharepoint.com'
```

Implicit loading, PnP first, then Power Apps admin
```
$cred = Get-Credential
Connect-PnPOnline -Credentials $cred -Url 'https://tenant-admin.sharepoint.com'
Add-PowerAppsAccount -Username $cred.Username -Password $cred.Password
```

Implicit loading, Power Apps admin first, then PnP
```
$cred = Get-Credential
Add-PowerAppsAccount -Username $cred.Username -Password $cred.Password
Connect-PnPOnline -Credentials $cred -Url 'https://tenant-admin.sharepoint.com'
```

### Actual behavior 
Unfortunately, the modules do not work correctly with PowerShell 7.x and the latest versions.

Explicit loading, PnP first, then Power Apps admin
![image](https://user-images.githubusercontent.com/6336180/231292619-251c5b1d-edf5-408a-9d96-be4906c7d3ab.png)

Explicit loading, Power Apps admin first, then PnP
![image](https://user-images.githubusercontent.com/6336180/231292767-e13bc265-1336-4a23-8632-3c1e16df3710.png)

Implicit loading, PnP first, then Power Apps admin
![image](https://user-images.githubusercontent.com/6336180/231292957-75880cd8-a3ae-4b97-9aac-6da11b05bb16.png)

Implicit loading, Power Apps admin first, then PnP
![image](https://user-images.githubusercontent.com/6336180/231293049-07bf41e1-6076-4ba4-b36a-56d5f9e5e765.png)

### Steps to reproduce behavior
1. Using PowerShell 7.x, install both PnP.PowerShell and PowerApps.Administration.PowerShell modules.
2. Optional: Explicitly import both modules
3. Try to connect to Power Apps and SharePoint. One will fail.

### What is the version of the Cmdlet module you are running?
2.1.1

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@Nazul - We have bumped a lot of our underlying dependencies in the 2.1.1 update as things either get deprecated or not worked on anymore **by Microsoft**. PnP PowerShell `1.12.0` is still available if you need PS5 or compatibility with other modules, while Microsoft updates their own modules.

But unfortunately, will have to close this because we have no control over other modules, and nothing we can really do.
