### ISSUE TITLE
EnableAzureADB2BIntegration in Get-PnPTenant

### ISSUE THREAD

**Issue by jflieben** [pnp/powershell#3018]
EnableAzureADB2BIntegration is currently only settable, not gettable (Get-PnPTenant vs Set-PnPTenant)

Would like to be able to check this setting as well

**Comment by KoenZomers** [comment]
Thanks @jflieben for your request. In the Get-PnPTenant cmdlet we are returning everything there is directly through CSOM. There's nothing we're holding back. This means at present there is no way to return this flag I'm afraid. The SharePoint Online Management Module also doesn't offer such a way:
https://learn.microsoft.com/en-us/sharepoint/sharepoint-azureb2b-integration

If you do happen to find out for an API that would expose this info, perhaps through Microsoft Graph, feel free to add it here and we'll be more than happy to look into possibilities to include it into PnP PowerShell.

**Comment by jflieben** [comment]
> Thanks @jflieben for your request. In the Get-PnPTenant cmdlet we are returning everything there is directly through CSOM. There's nothing we're holding back. This means at present there is no way to return this flag I'm afraid. The SharePoint Online Management Module also doesn't offer such a way: https://learn.microsoft.com/en-us/sharepoint/sharepoint-azureb2b-integration
> 
> If you do happen to find out for an API that would expose this info, perhaps through Microsoft Graph, feel free to add it here and we'll be more than happy to look into possibilities to include it into PnP PowerShell.

This blog says Get-SpoTenant does return it: https://office365itpros.com/2021/08/17/sharepoint-online-embraces-azure-b2b-collaboration-external-sharing/

**Comment by KoenZomers** [comment]
@jflieben I stand corrected. You are right. I've added it through PR #3022.

**Comment by jflieben** [comment]
awesome :)
