### ISSUE TITLE
[FEATURE] Connect-PnPOnline with AzureAD Workload Identity

### ISSUE THREAD

**Issue by PatrickSpies** [pnp/powershell#3029]
**Is your feature request related to a problem? Please describe.**
Our script is running within an aks-cluster. Currently we are using `Connect-PnPOnline` with `-CertificateBase64Encoded` and `-CertificatePassword` of an app-registration. To get rid of the manually maintained secrets (cert+password) we would like to use a user-assigned managed-identity and [AzureAD Workload Identity](https://azure.github.io/azure-workload-identity/docs/introduction.html).

When trying to use `Connect-PnPOnline` with `-ManagedIdentity` and `-UserAssignedManagedIdentityClientId` the login fails:
```
Connect-PnPOnline -Url "##### REDACTED #####" -ManagedIdentity -UserAssignedManagedIdentityClientId ##### REDACTED #####  -Verbose
VERBOSE: Connecting using Managed Identity
VERBOSE: Acquiring token for resource ##### REDACTED #####
VERBOSE: Using scope ##### REDACTED ##### for managed identity token coming from the passed in default resource
VERBOSE: Using identity endpoint:
VERBOSE: Using identity header:
VERBOSE: Using the user assigned managed identity with client ID: ##### REDACTED #####
VERBOSE: Sending token request to http://169.254.169.254/metadata/identity/oauth2/token?resource=##### REDACTED #####&api-version=2019-08-01&client_id=##### REDACTED #####
Connect-PnPOnline: clientID in request: ##### REDACTED #####, getting assigned identities for pod ##### REDACTED ##### in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors
```
 
From "Check MIC pod logs for identity assignment errors" it seems the deprecated [AAD Pod Identity](https://github.com/Azure/aad-pod-identity) is triggered..

**Describe the solution you'd like**
We would like to use `Connect-PnPOnline` with a user-assigned managed-identity and [AzureAD Workload Identity](https://azure.github.io/azure-workload-identity/docs/introduction.html), this should be feasible by using `Azure.Identity`.

**Describe alternatives you've considered**
We´ve tried to get a valid AccessToken (for `Connect-PnPOnline` with `-AccessToken`) from Module `Az.Accounts` (`Connect-AzAccount` and `Get-AzAccessToken`) but as mentioned [here](https://pnp.github.io/powershell/cmdlets/Connect-PnPOnline.html#-accesstoken) this is not recommended and we would have to handle expiring tokens manually which becomes more and more complex..

**Additional context**
_--_

**Comment by KoenZomers** [comment]
Hi @PatrickSpies . Are you able to test the fix that @gautamdsheth has prepared for you? Please let me know if it works so we can merge it.
