### ISSUE TITLE
Fix the minimum powershell version requirement in the PSD1 file

### ISSUE THREAD

**Issue by colombeen** [pnp/powershell#3048]
### Notice
Can't run PNP.PowerShell on Windows Powershell 5.1 because it seems like you dropped the support for it, but we can update the module to the latest version and then you don't even get a correct error why it's not working.

PSD1 can have a PowerShellVersion key with the minimum version required, which in turn would throw the correct error when trying to load the wrong version.

**Comment by colombeen** [comment]
Just bumped into this piece of info. With the key "CompatiblePSEditions" you can say that it only supports "Core"

**Comment by ColomJa** [comment]
Shouldn't this be like a 10 second fix?
We've automated the update process for all our modules and we had to create a special exception for the pnp.powershell module because of this problem.

**Comment by veronicageek** [comment]
@ColomJa - This is a community driven repo. Meaning we also have day jobs and possibly unforeseen events.
But please, feel free to contribute by submitting a PR, it'll be welcomed.

**Comment by gautamdsheth** [comment]
@colombeen / @veronicageek - sorry, it’s on me. We have release automation in a separate repo. 

We tried to fix it but ran into some issue a while back so didn’t go through with it. 

Will absolutely try to fix it in upcoming release.

**Comment by colombeen** [comment]
@gautamdsheth, any updates?

**Comment by gautamdsheth** [comment]
@colombeen - has been fixed with the latest 2.5.0 release, sorry it took so long.
