### ISSUE TITLE
[BUG] - Get-PnPListItem timeout if the List/Library contains Term Fields

### ISSUE THREAD

**Issue by peteopablo** [pnp/powershell#3059]
Description
### Reporting an Issue or Missing Feature
Get-PnPListItem runs in an Timeout if the List/Library contains Term Fields, which Termset have more than ~30000 Items.
Sometimes I get an Timeout, sometimes nothing.
- The List contains only 50000 elements
- Term FieldName: ecsArticleMMD
Runs in an Timeout or no result:
`$Items = Get-PnPListItem -List "/Lists/ArticleFolder" -PageSize 1000 -Fields Title, ecsArticleMMD`

If I run the request without Term Field, I get an result in a few seconds
`$Items = Get-PnPListItem -List "/Lists/ArticleFolder" -PageSize 1000 -Fields Title`

### Expected behavior 
Get all Items from the List, with MMD Fields.

### Actual behavior 
No Result or timeOut.

### Steps to reproduce behavior
- Create Termset with more than 30000 Terms
- Create List with more than 10000 Items, which includes a mmd field, which points on the previosly created termset
- connect to sharePoint "Connect-pnponline"
- retrieve Listitems
`$SPSiteURL = "https://TEST.sharepoint.com/sites/ABC"
Connect-PnPOnline -Url "$SPSiteURL" -Credentials "ABC" -ErrorAction Stop 
$Items = Get-PnPListItem -List "/Lists/ArticleFolder" -PageSize 1000 -Fields Title, ecsArticleMMD`

### What is the version of the Cmdlet module you are running?
1.12
1.11 (also testet)
1.10 (also testet)

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@peteopablo - Can you try with a smaller number items in the `-PageSize`. Also, if you are using **PS7**, can you please update the module to the latest (needs minimum PS 7.2 - doesn't support PS5 nor the ISE).

In all honestly, I doubt we'll be able to do testing with that number of items...

**Comment by gautamdsheth** [comment]
Closing this as we will not able to fix this issue and also due to lack of response.
Would suggest that you use a different mechanism like SharePoint search for retrieving large number of items instead of direct and heavy list queries.
