### ISSUE TITLE
[BUG] Connect-PnpOnline require an Azure AD app to be registred when using credentials

### ISSUE THREAD

**Issue by mgrosperrin** [pnp/powershell#3076]
### Expected behavior 
When using the cmdlet `Connect-PnPOnline` with credentials, I should not have to register/approve the PnP Management Shell application (or any other).

### Actual behavior 
When calling the cmdlet (`Connect-PnPOnline -Url https://mytenant.sharepoint.com -Credentials $credentials`) I received an error saying that I have create or approved the PnP Management Shell application.

### Steps to reproduce behavior
`Connect-PnPOnline -Url https://mytenant.sharepoint.com -Credentials $credentials`

### What is the version of the Cmdlet module you are running?
2.1.1

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [x] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@mgrosperrin - This is the way it has always worked since the module is cross platform. You can check here: https://pnp.github.io/powershell/articles/authentication.html

> PnP PowerShell allows you to authenticate with credentials to your tenant. However, due to changes in the underlying SDKs we require you first to register a Azure AD Application which will allow you to authenticate.

You can create your own App Registration and give it the appropriate permissions as well.

**Comment by mgrosperrin** [comment]
Hi @veronicageek,

Thanks for your answer.
However I have a few questions:

1. Regarding the code, the `ClientId` doesn't seems to be required:
When connecting with credentials, the method in the cmdlet used is `ConnectCredentials` (https://github.com/pnp/powershell/blob/7bcaa6e8202dc160cc590651f845798bfacf5e23/src/Commands/Base/ConnectOnline.cs#L547) that sets the clientId if not provided. After that it calls `PnPConnection.CreateWithCredentials` (https://github.com/pnp/powershell/blob/7bcaa6e8202dc160cc590651f845798bfacf5e23/src/Commands/Base/ConnectOnline.cs#L578) passing the clientId. However this method know how to deal without a clientId (https://github.com/pnp/powershell/blob/7bcaa6e8202dc160cc590651f845798bfacf5e23/src/Commands/Base/PnPConnection.cs#L450).
I try using a patched version of the module and it works correctly.

2. What do you mean by "give it the appropriate permissions"? As we connect via credentials, why should I give an Azure AD app any permissions? Doesn't the cmdlet/connection use the identity of the credential to perform the operations?

Thanks again for your answers.
Matthias

**Comment by veronicageek** [comment]
I will leave the C# code explanation to our devs @gautamdsheth or @KoenZomers
