### ISSUE TITLE
[BUG] Get-PnPMicrosoft365Group -IncludeSiteUrl provisions M365 group's SharePoint site

### ISSUE THREAD

**Issue by GuillaumeLaquerriere** [pnp/powershell#3077]
### Reporting an Issue or Missing Feature
If you create a Microsoft 365 group from the Outlook desktop client, its associated SharePoint site is NOT automatically provisioned.  (I've opened a case with Microsoft as it would seem this is a bug in and of itself since all other methods to create a M365 group DOES provision the group's associated SharePoint site, alas I was told its expected behavior and to submit a DCR to change it :eyeroll:).

The bug here is if you run `Get-PnPMicrosoft365Group -Identity <M365groupname>` it will return the group's properties (`SiteUrl` will be blank).  But if you run `Get-PnPMicrosoft365Group -Identity <M365groupname> -IncludeSiteUrl` (the added `-IncludeSiteUrl` parameter being the difference) it will create the M365 group's SharePoint site and populate the group's `SiteUrl` property with its SP site URL.

Submitting this as a bug since the cmdlet's `IncludeSiteUrl `parameter's documentation [https://pnp.github.io/powershell/cmdlets/Get-PnPMicrosoft365Group.html#-includesiteurl](https://pnp.github.io/powershell/cmdlets/Get-PnPMicrosoft365Group.html#-includesiteurl) only mentions "fetching" the site URL, and not creating the group's SP site if one doesn't already exist.

### Expected behavior 
I would expect running `Get-PnPMicrosoft365Group -Identity <M365groupname> -IncludeSiteUrl` gets/fetches the M365 group's SP site URL if one exists, and report blank/null if it doesn't.

### Actual behavior 
See first section for actual behavior details.

### Steps to reproduce behavior
Create Microsoft 365 group from Outlook desktop client.  Confirm group's SharePoint site doesn't exist via admin portal (Microsoft 365 admin center, SharePoint admin center, Azure AD) or by running `Get-PnPMicrosoft365Group -Identity <M365groupname>` and noting the `SiteUrl `property is blank.
Run `Get-PnPMicrosoft365Group -Identity <M365groupname> -IncludeSiteUrl` and you'll see the group's SP site gets created (can confirm via any admin portal or by running `Get-PnPMicrosoft365Group -Identity <M365groupname>` and noting the `SiteUrl `property now returns the group's SP site URL.

### What is the version of the Cmdlet module you are running?
2.1.1

### Which operating system/environment are you running PnP PowerShell on?
- Windows

**Comment by GuillaumeLaquerriere** [comment]
Hi @veronicageek,

I think a better way to phrase it is the `SiteUrl` switch initiates something in the service that kicks off the site provisioning process (similar to your test when you did **not** use PnP PowerShell-- the site doesn't exist until you click the link in the email, go to the Files tab of the group, etc-- there are multiple ways to initiate the group's site provisioning outside of PnP PowerShell).  

The reason for creating this bug issue is because when the `SiteUrl` switch is used with the Get-PnPMicrosoft365Group cmdlet on a group that doesn't already have a SharePoint site, the SharePoint site gets created.  This is counter-intuitive to every Get cmdlet in PowerShell-- it should only be retrieving information and never creating/writing/provisioning anything new.  Since I understand it may not be the cmdlet thats doing it directly (again, sounds like its initiating something in the SharePoint service thats doing it), I think adding a note to the https://pnp.github.io/powershell/cmdlets/Get-PnPMicrosoft365Group.html#-includesiteurl documentation should be considered.

**Comment by GuillaumeLaquerriere** [comment]
To be clear, the site does **not** get created when the M365 group is created via the Outlook desktop client.  You can wait days, weeks, months.  The site will not exist in any admin center, can't be retrieved via other PowerShell cmdlets, etc.  The site **only** gets created once _some action_ initiates its creation.  This action could be clicking the site link in the group creation email, going to the group's Files in Outlook, or running the Get-PnPMicrosoft365Group cmdlet with the SiteUrl switch.

**Comment by veronicageek** [comment]
> The site only gets created once some action initiates its creation. This action could be clicking the site link in the group creation email, going to the group's Files in Outlook, or running the Get-PnPMicrosoft365Group cmdlet with the SiteUrl switch

So then I don't see why this would be a PnP PowerShell issue, but I'll wait to hear @gautamdsheth or @KoenZomers's thoughts.
