### ISSUE TITLE
[BUG]  Is seems like Add-PnPFile -CheckinType MajorCheckIn doesn't work

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/powershell#3112]
I am running this:

for($i=0; $i -lt $majorVersionCount;$i++)
{
                $major = Add-PnPFile -Path $File -Folder $Folder -NewFileName $NewFileName  -CheckinType MajorCheckIn -Connection $conn
}               

against a library where minorversions is enabled. 

### Expected behavior 
I would expect $majorVersionCount new major versions to be created

### Actual behavior 
$majorVersionCount **minor** versions are created

I am currently handling this issue by adding this to the script after the Add-PnPFile command

Set-PnPFileCheckedOut -Url $major.ServerRelativeUrl  -Connection  $conn
Set-PnPFileCheckedIn -Url $major.ServerRelativeUrl -CheckinType MajorCheckIn -Comment "Major version created" -Connection $conn

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

### What is the version of the Cmdlet module you are running?
Version 2.1.1 

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by kasperbolarsen** [comment]
Hi Gautam :-)
I have tested again using the -CheckOut parameter, and it didn't have any effect. I wonder if it is related to the fact that minor versions are enabled on this library.

**Comment by gautamdsheth** [comment]
Can you share the library settings screenshot, i.e what settings are there for major/minor version and stuff ? Will try to reproduce this issue. Also, looks like you need to set require checkout in settings, otherwise it wont work AFAIK

**Comment by kasperbolarsen** [comment]
Hi Gautam

Version settings as requested :-)

OK, I see your point. I was expecting the checkout to be included in the CheckinType in such a way that  
Add-PnPFile -Path $File -Folder $Folder -NewFileName $NewFileName -CheckinType MajorCheckIn -Connection $conn would automatically checkout the existing file (if it existed). Would that expectation be unreasonable for a Add cmd?


![image](https://github.com/pnp/powershell/assets/20593570/116063c7-844b-4f4d-bcd6-73e003ad6c29)

**Comment by gautamdsheth** [comment]
Hey @kasperbolarsen :) 

I tested this scenario with the exact settings and am unable to reproduce it.
The cmdlet checkouts the file and then checks it in as a major version. 
Something in your script maybe ? 
Try with just the command itself instead of inside a loop or something ?

**Comment by kasperbolarsen** [comment]
@gautamdsheth 

try this and look at the version history for the file. On my tenant the file is created as versions 0.1+0.2+0.3, not exactly what I expected :-)

#Purpose: recreate the behavoir in the https://github.com/pnp/powershell/issues/3112#issuecomment-1565666901

$spadminUrl = "https://contoso-admin.sharepoint.com/"
$filepath = "c:\temp\basetemplate2.pnp"  #any file will do  
$tenantUrl = "https://contoso.sharepoint.com/"
$owner = "admin@contoso.onmicrosoft.com"
$url = $tenantUrl + "sites/issue3112"
$NewFileName = "testfile.txt"
$spadminconn = Connect-PnPOnline -Url $spadminUrl -Interactive -ReturnConnection

New-PnPTenantSite -Title "issue3112" -Url $url -Owner $owner -Template "STS#3" -Connection $spadminconn -Lcid 1033 -TimeZone 3 -Wait
$newsiteconn = Connect-PnPOnline -Url $url -Interactive -ReturnConnection
$library = Get-PnPList -Identity "Documents" -Connection $newsiteconn
Set-PnPList -Identity $library -EnableVersioning $true -EnableMinorVersions $true -Connection $newsiteconn

$folder = "Shared Documents"
for($i=0; $i -lt 3;$i++)
{
    $major = Add-PnPFile -Path $filepath -Folder $folder -NewFileName $NewFileName -CheckinType MajorCheckIn -Connection $newsiteconn
}

**Comment by gautamdsheth** [comment]
You are missing the -Checkout parameter in the script.

**Comment by kasperbolarsen** [comment]
Hi @gautamdsheth , you and I  know that I am missing the CheckOut parameter. My point is that either it shouldn't be required (the cmdlet will do this automatically if required) or I should get an error ? Getting a bunch of minor versions is definitely not correct 🙃 😉😁

**Comment by kasperbolarsen** [comment]
hi @gautamdsheth 

if you append this to the script above you will see that trying to add files using CheckinType minorCheckin on a library where minor versioning is not enabled will cause the checkin to be major versions.

New-PnPList -Title "DocumentsMajorOnly" -Template DocumentLibrary -Connection $newsiteconn
$majoronlylibrary = Get-PnPList -Identity "DocumentsMajorOnly" -Connection $newsiteconn
Set-PnPList -Identity $majoronlylibrary -EnableVersioning $true -EnableMinorVersions $false -Connection $newsiteconn
for($i=0; $i -lt 3;$i++)
{
    $major = Add-PnPFile -Path $filepath -Folder "DocumentsMajorOnly" -NewFileName $NewFileName -CheckinType MinorCheckIn -Connection $newsiteconn
}

(also when using CheckOut)
I know that we can't protect people from making mistakes, but I think it would be a benefit for all if the cmdlet would check if the required action was possible or not?

**Comment by kasperbolarsen** [comment]
Hi @gautamdsheth , what is your option on this one?  Should the code be updated to throw an error when the parameters do not match the expected,  or should we resolve this by updating the documentation?

**Comment by kasperbolarsen** [comment]
Thanks , lovely 😁
