### ISSUE TITLE
[BUG] Import-Module fails on version 2.1.1

### ISSUE THREAD

**Issue by ThoughtContagion** [pnp/powershell#3121]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting
Unable to import the module to connect. Receiving an error on a fresh Windows 11 Pro VM in PowerShell 5.1

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets
Module imports 

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.
The following error:
```import-module : Could not load file or assembly 'System.Management.Automation, Version=7.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.```

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)
```Install-Module -Name PnP.PowerShell```

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
`PnP.PowerShell 2.1.1`

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by ThoughtContagion** [comment]
When I uninstalled version 2.1.1 and installed version 1.12.0, the module imports and works as expected.

**Comment by veronicageek** [comment]
@ThoughtContagion - If you wish to use `2.1.x` then you **need to be on PS 7.2 and above**. We don't support PS5 nor the ISE on version 2.

If you can't use PowerShell 7, then version `1.12` will be the latest.

**Comment by ThoughtContagion** [comment]
Thank you.
Would it be possible to implement a dependency check to prevent install on unsupported versions of PowerShell?
We have scripted processes for preparing an environment and updating modules - this stands to break unattended installs and upgrades.
