### ISSUE TITLE
Add-PnPFileSensitivityLabel

### ISSUE THREAD

**Issue by stvpwrs** [pnp/powershell#3135]
If possible it would be very helpful to assign Sensitivity Labels on files with PowerShell.

**Describe the solution you'd like**
Ideally it would be a simple cmdlet like Add-PnPFileSensitivityLabel that takes a path and then assigns a sensitivity label.

**Describe alternatives you've considered**
There are OOTB features for setting defaults on libraries and on containers, but there isn't really much in terms of files and I think most alternatives are covered with existing OOTB features or cmdets.

**Comment by stvpwrs** [comment]
Thanks @danielcecil . I think that makes sense. I do assume that more API calls will become premium overtime and I think PnP should have a strategy for how to deal with those APIs. Even if that is to call back to just calling the Graph API directly.

**Comment by danielcecil** [comment]
Thanks @stvpwrs I've opened a discussion about this #3446, because I'm keen to build the cmdlet. For now you could use [Invoke-PnPGraphMethod](https://pnp.github.io/powershell/cmdlets/Invoke-PnPGraphMethod.html) to call the Graph API directly.

**Comment by gautamdsheth** [comment]
@danielcecil - just ship it 😊

Lets not worry about checking license and stuff. 
If the cmdlet is able to assign sensitivity label , that would be enough for v1/beta release of the cmdlet.
