### ISSUE TITLE
Send-PnPMail - handle attachments like Send-MgUserMail

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/powershell#3137]
It would be very nice if the Send-PnPMail could handle attachments like Send-MgUserMail, as it will allow us to stay with PnP.PowerShell and not having to include Import-Module Microsoft.Graph.Users.Actions :-)

**Comment by gautamdsheth** [comment]
Closing as merged via https://github.com/pnp/powershell/pull/3157 , will be available in tomorrow's nightly.

Thanks
