### ISSUE TITLE
[FEATURE] Add AllowDeletion parameter for Set-PnPList command

### ISSUE THREAD

**Issue by ganesh-sanap** [pnp/powershell#3138]
# Is your feature request related to a problem? Please describe

Currently we do not have any parameter for Set-PnPList command which will allow us to specify whether the SharePoint list can be deleted from SharePoint UI.

# Describe the solution you'd like

Can we enhance `Set-PnPList` cmdlet to support additional parameter (say `-AllowDeletion`) which will allow us to specify whether the SharePoint list can be deleted?

I would like to contribute to this library for above enhancement request if you think it is a valid enhancement request for Set-PnPList command. Thank you!

**Comment by gautamdsheth** [comment]
Go for it @ganesh-sanap , welcome any PRs, thanks :)
