### ISSUE TITLE
[BUG] Connect-PnPOnline and PowerShell 7.2

### ISSUE THREAD

**Issue by patrick-blanc** [pnp/powershell#3145]
### Reporting an Issue or Missing Feature
Bug in Connect-PnPOnline

### Expected behavior 
Connect to SharePoint successfully.

### Actual behavior 
Connect-PnPOnline showing error : **Connect-PnPOnline: The type initializer for 'Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.CoreEventSource' threw an exception.**

### Steps to reproduce behavior
Use PowerShell 7.2.6
Use Connect-PnPOnline -Url ... -ClientId -CertificateBase64Encoded ... -CertificatePassword  ... -Tenant ...

### What is the version of the Cmdlet module you are running?
2.1.1

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [x] Azure Functions

**Comment by veronicageek** [comment]
@patrick-blanc - `Connect-PnPOnline` is the first command to be run for anything, so I think we would have had more issues if it wasn't working. Closing now.
