### ISSUE TITLE
[BUG] Creating library from template when template includes a doc set content type

### ISSUE THREAD

**Issue by paylord** [pnp/powershell#3146]
### Reporting an Issue or Missing Feature
Doc sets created in a library provisioned from a template try to use docsethomepage.aspx and are not usable.

### Expected behavior 
Create a library from a template including a doc set content type and doc sets should work correctly.

### Actual behavior 
Using $list.SaveAsTemplate().the template is correctly saved in the site.
A library created from it using the UI works as expected.
A library created using $web.Lists.Add() creates the library successfully, but any document sets created from the contained content type try to open using docsethomepage.aspx and are not usable.

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)
$listCreation = New-Object Microsoft.SharePoint.Client.ListCreationInformation
$listCreation.Title = 'Title'
$listCreation.Template = 'SavedTemplate'
$web.Lists.Add($listCreation)
Invoke-PnPQuery

### What is the version of the Cmdlet module you are running?
1.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows

**Comment by gautamdsheth** [comment]
This is a CSOM SDK issue. We can't do anything here.
Please reach out to Microsoft support for this.
