### ISSUE TITLE
[FEATURE] OpenInNewTab be populated in Get-PnPNavigationNode cmdlet

### ISSUE THREAD

**Issue by rafayahmed317** [pnp/powershell#3148]
**Is your feature request related to a problem? Please describe.**
Recently in the nightly build, a feature was added that enabled users to create a navigation node with the open in new tab property. I think it should be incorporated in the navigation nodes properties when we request the node. So we can update it too for existing nodes. Presently, there is no "OpenInNewTab" or "OpenInNewWindow" property when we get the node using the Get-PnPNavigationNode cmdlet.

**Describe the solution you'd like**
The "OpenInNewTab" property should be returned when a navigation node is requested through get-PnPNavigationNode cmdlet.

**Describe alternatives you've considered**
Currently the property can only be applied to new nodes using Add-PnPNavigationNode cmdlet and using Sharepoint UI.
I tried digging in the source code of Add-PnPNavigationNode to see where it sets the property, but when I request the menustate using Invoke-PnpRestMethod, I do not get a list of nodes where to set the property.

**Comment by CallumCrowley** [comment]
@rafayahmed317 this seems to be a limitation of SharePoint CSOM, on which this cmdlet relies upon. The properties available for the NavigationNode class can be found via the link below:

[NavigationNode members](https://learn.microsoft.com/en-us/previous-versions/office/sharepoint-csom/ee540930(v=office.15)#properties)

**Comment by rafayahmed317** [comment]
I think you are right, but what this answer here is talking about? 
https://sharepoint.stackexchange.com/a/90216
Did I understand something wrong?

**Comment by CallumCrowley** [comment]
@rafayahmed317 that question is referring to a different PowerShell library, specific to on-premises SharePoint.

At the moment, the NavigationNode class simply doesn't include this property. If you'd like a change to the SharePoint CSOM library, then you can suggest it on the [Microsoft Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/06735c62-321c-ec11-b6e7-0022481f8472). Once it's in the library, PnP.PowerShell can be updated to ensure it is using the latest version of CSOM that contains this additional property.

**Comment by rafayahmed317** [comment]
Sorry, I knew I was not understanding something, thank you for your response, so yeah, I will close this.
