### ISSUE TITLE
[FEATURE] Add classification option to Set-PnPMicrosoft365Group similar to Set-UnifiedGroup xxx -Classification "Sharing - Enabled"

### ISSUE THREAD

**Issue by svermaak** [pnp/powershell#315]
**Is your feature request related to a problem? Please describe.**
No, except it forces me to use Exchange Module

**Describe the solution you'd like**
Add classification option to Set-PnPMicrosoft365Group similar to Set-UnifiedGroup xxx -Classification "Sharing - Enabled"

**Describe alternatives you've considered**
Using Exchange Module

**Additional context**
NA

**Comment by erwinvanhunen** [comment]
We just merged this ability, it will be available in 1.3.16-nightly.

**Comment by svermaak** [comment]
Phenomenal. Will give it a test
