### ISSUE TITLE
[BUG] New-PnPAzureCertificate: Decoded string is not a valid IDN name. (Parameter 'unicode')

### ISSUE THREAD

**Issue by New-Authentication** [pnp/powershell#3161]
### Reporting an Issue or Missing Feature
An Issue

### Expected behavior 
Command creates a certificate and outputs it

### Actual behavior 
The following error is thrown:
![image](https://github.com/pnp/powershell/assets/135658651/7471826c-1551-4287-81fd-6e20b05cfc0a)

### Steps to reproduce behavior
Just run the following with no parameters:
New-PnPAzureCertificate

### What is the version of the Cmdlet module you are running?
2.1.1

### Which operating system/environment are you running PnP PowerShell on?
Windows Server 2019, latest updates
PowerShell 7.3.4

However, if I do the same thing on a Windows 11 Beta channel running PowerShell 7.3.4 I get no error.
I'm not sure what New-PnPAzureCertificate is angry about on my server.

**Comment by gautamdsheth** [comment]
@New-Authentication - have you tried adding some name to the certificate ? Maybe that can help ? 

I can't repro on Win 11 and neither can you.
So, if it works on Win 11, but not on server , not sure if we can do anything here.

**Comment by gautamdsheth** [comment]
Closing due to lack of response.
Also , if it works in win11 but not in win server 2019 , not sure we can fix it either 🤷‍♂️

**Comment by New-Authentication** [comment]
Hi @gautamdsheth 
Sorry for my lack of response. Something is broken with how PowerShell 7 works on Windows Server. Get-ADUser (and other standard ADDS commands) produces the same error. I don't know how to describe it any better. It is run of Azure with a standard Azure Windows 2019 image.
I know it can be hard to troubleshoot but to say that because it works on Windows 11 then there is nothing to do is not really a valid reason for not doing anything.

**Comment by New-Authentication** [comment]
Same issue on 7.3.5

**Comment by New-Authentication** [comment]
Oops - thought I was in PowerShell GitHub - of cause you probably couldn't fix this if it is a generic PowerShell 7 problem.

Sorry for my bitterness!
