### ISSUE TITLE
[BUG] Add-PnPMicrosoft365GroupToSite , -isPublic parameter 

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/powershell#3164]
Add-PnPMicrosoft365GroupToSite -Url $SiteURL -Alias $GroupAlias -DisplayName $GroupName -IsPublic $true  -KeepOldHomePage -
Connection   $adminConn

returns an error that: Add-PnPMicrosoft365GroupToSite: A positional parameter cannot be found that accepts argument 'True' 

### Expected behavior 
That a public Group would be add and connected to the site

### Actual behavior 
Error. I am not sure is IsPublic is expecting a non boolean value, in that case the documentation should be updated?

### Steps to reproduce behavior

Add-PnPMicrosoft365GroupToSite -Url $SiteURL -Alias $GroupAlias -DisplayName $GroupName -IsPublic $true  -KeepOldHomePage -Connection   $adminConn

### What is the version of the Cmdlet module you are running?
2.1.1

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by Tanddant** [comment]
The `-IsPublic` parameter is documented as a SwitchParameter, meaning you don't have to provide a value to it.

If it's there it's evaluated as `true`, if not it's `false`, so you just shouldn't provide a value to it.

Contrary to Boolean values, like the `-IsInverted` on `Add-PnPTenantTheme` that requires you to provide both the parameter name, and a boolean value.

**Comment by kasperbolarsen** [comment]
I suspected as much, yet the name of that parameter triggered the old C and C++ habits to expect an boolean value ;-)  I guess I'll just have to add a code sample using that parameter .
