### ISSUE TITLE
[BUG] "Move-PnPFile -IgnoreVersionHistory" is not working as expected

### ISSUE THREAD

**Issue by 4iJacob** [pnp/powershell#3167]
Hello All,
I am opening a new issue for a closed [issue](https://github.com/pnp/powershell/discussions/3104#discussioncomment-6102131)
I am using and PowerShell 7.3.4.

### Expected behavior 
Cmdlet "Move-PnPFile -IgnoreVersionHistory" is not working as expected.

### Actual behavior 
When using "Move-PnPFile -IgnoreVersionHistory" it moves all version history for one file.

### Steps to reproduce behavior
$job = Move-PnPFile -SourceUrl $SourceFileURL -TargetUrl $TargetFileURL -IgnoreVersionHistory -AllowSchemaMismatch -NoWait

### What is the version of the Cmdlet module you are running?
 PnP.PowerShell 2.1.1 

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
hi @4iJacob , tested this issue. 

This is an issue with the SharePoint API itself that we are using. The endpoint that we use is `_api/site/CreateCopyJobs`. Unfortunately, it doesn't respect the IgnoreVersionHistory parameter. Setting it to true or false doesn't matter, it always copies the version history.

We can't do anything from our side at PnP PowerShell, please reach out to Microsoft via a support ticket for this. Only they will be able to help resolve this issue by providing a server side fix.

Will close this as it can't be fixed from here.
