### ISSUE TITLE
[BUG] Copy-PnPList: newly created list -> list settings -> Edit View broken

### ISSUE THREAD

**Issue by jeroenbrussich** [pnp/powershell#3168]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

### Reporting an Issue or Missing Feature
When I copy a list from one Site to another, or even within the same site, the command runs successfully. The List-Framework is copied, all columns and even the layout-options are copied. However, when I try to create a new view, or edit an existing view (that was copied from the original list), I get an error: Something went wrong -> Correlation ID: 2b81baa0-80f0-6000-aa9b-af6d501da7b6

### Expected behavior 
The cmdlets output no specific errors, the result however is broken. I expect to be able to edit an existing or create a new view after copying a list with Copy-PnPList

### Actual behavior 
explained above

### Steps to reproduce behavior
1. use the Copy-PnpList command
2. open your newly created list on SharePoint Online
3. Go to list settings -> Views -> edit view
4. behold the error

Error also occurs when you create a new view through the modern interface and then try to edit that view by going to list settings.
The original list does not have this problem. I can edit and create views, so it's not a broken list that is being copied.

### What is the version of the Cmdlet module you are running?
2.1.1

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@jeroenbrussich - I'm not able to reproduce your issue (also tested on `2.1.1`).

Tried with Lists & Libraries, editing the Views via List/Library Settings, or directly from the list (using the dropdown -> "Edit current view"). I can also create a new view in the new (copied) list.

All is working fine. Please try again, or copy a different list, etc..

**Comment by jeroenbrussich** [comment]
right!

Looks like to be a problem on my side/site, because even manually copying a list breaks my view :/
A Microsoft-support ticket it is!
