### ISSUE TITLE
Unable to Register-PnPManagementShellAccess

### ISSUE THREAD

**Issue by junterpfe** [pnp/powershell#317]
I am working in GCCH and i am unable to complete the Registration
Register-PnPManagementShellAccess -AzureEnvironment USGovernment

i was able to do so before the new version of PnP released several months ago but am getting an error now

Message: AADSTS65006: Resource '797f4846-ba00-4fd7-ba43-dac1f8f63013' had no entitlements matching required permissions configured on the required resource access for client '31359c7f-bd7e-475c-86db-fdb8c937548e'. Requested permission IDs: '41094075-9dad-400e-a0bd-54e686782033'. This is a problem with one or more invalid permission ids on the client RRA configuration or the resource entitlement configuration.

questioning if this has to do with differences with GCCH endpoints and if someone can work with me internally about it, i am willing/able to do testing.

it could be something simple like this:
GCCH
https://login.microsoftonline.us/common/oauth2/deviceauth 
vs
Commercial
https://login.microsoftonline.com/common/oauth2/deviceauth

for example.

it generates the code, lets me login, and then i get to the "trouble signing you in page"

**Comment by erwinvanhunen** [comment]
We actually made changes to PnP PowerShell in the last nightyl releases specifically for GCC High, Low and DoD cloud instances. Please upgrade to the latest nightly build for that

```powershell
Update-Module -Name PnP.PowerShell -AllowPrerelease
```

We have also introduced a few other additions specifically for GCC environment. See https://pnp.github.io/powershell/articles/authentication.html#authentication-to-gcc-or-national-cloud-environments for more details.

**Comment by junterpfe** [comment]
I got the Pre-Release version, the Registration still failed but at least it made the object in Azure
These two scopes worked:
SPO.Sites.FullControl.All, MSGraph.Group.ReadWrite.All
However this one:
SPO.AllSites.FullControl
came is as a GUID and failed out.

i removed it and approved the application but it seems that i am blocked doing a connect:
Connect-PnPOnline : AADSTS65006: Resource '797f4846-ba00-4fd7-ba43-dac1f8f63013' had no entitlements matching required permissions configured on the required resource access for client '31359c7f-bd7e-475c-86db-fdb8c937548e'. Requested permission IDs: 
'41094075-9dad-400e-a0bd-54e686782033'. This is a problem with one or more invalid permission ids on the client RRA configuration or the resource entitlement configuration.

Guessing my app is missing a permission it needs.

**Comment by erwinvanhunen** [comment]
The error message states you're trying to use the PnP Management Shell application instead of your own registered application. (31359c7f-bd7e-475c-86db-fdb8c937548e is the ID of the pnp management shell application). When you connect, did you specify the -ClientId [yourownapplicationid] parameter?

**Comment by junterpfe** [comment]
Yep missed that, managed to get a template downloaded and reapplied but got a bunch of warnings about navigation:
WARNING: ListInstance Style Library is a Style Library of a site with NoScript enabled and will be skipped
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_0_2007_Title}
WARNING: Provisioning of the navigation node failed : Access denied. You do not have permission to perform this action or access this resource.
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2007_2008_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2008_2009_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2008_2010_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2008_2011_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2008_2012_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2008_2013_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2008_2077_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2008_2078_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2008_2079_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2008_2080_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2008_2081_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2007_2014_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2014_2015_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2014_2016_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2014_2017_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2014_2083_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2014_2084_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2014_2085_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2007_2076_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2007_2082_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_0_2018_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2018_2019_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2019_2020_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2019_2021_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2019_2088_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2019_2089_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2018_2087_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_0_2022_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2022_2023_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2023_2024_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2023_2025_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2023_2026_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2023_2092_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2023_2093_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2023_2094_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2022_2091_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_0_2027_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2027_2028_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2028_2029_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2028_2030_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2028_2031_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2028_2032_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2028_2033_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2028_2097_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2028_2098_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2028_2099_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2028_2100_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2028_2101_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2027_2096_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_0_2075_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_0_2086_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_0_2090_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_0_2095_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_0_2034_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2034_2035_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2035_2036_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2035_2104_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2034_2103_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_0_2037_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2037_2038_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2038_2039_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2038_2040_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2038_2107_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2038_2108_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2037_2041_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2041_2042_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2041_2043_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2041_2044_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2041_2110_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2041_2111_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2041_2112_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2037_2106_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2037_2109_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_0_2045_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2045_2046_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2046_2047_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2046_2048_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2046_2049_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2046_2115_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2046_2116_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2046_2117_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2045_2050_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2050_2051_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2050_2052_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2050_2119_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2050_2120_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2045_2053_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2053_2054_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2053_2055_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2053_2056_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2053_2122_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2053_2123_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2053_2124_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2045_2114_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2045_2118_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2045_2121_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_0_2057_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2057_2058_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2058_2059_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2058_2060_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2058_2061_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2058_2062_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2058_2127_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2058_2128_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2058_2129_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2058_2130_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2057_2063_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2063_2064_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2063_2065_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2063_2066_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2063_2132_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2063_2133_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2063_2134_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2057_2067_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2067_2068_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2067_2069_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2067_2070_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2067_2136_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2067_2137_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2067_2138_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2057_2126_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2057_2131_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2057_2135_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_0_2071_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_0_2072_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_2072_2141_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_0_2074_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_0_2102_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_0_2105_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_0_2113_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_0_2125_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_0_2139_Title}
WARNING: Provisioning of the navigation node failed, retrying for : {res:NavigationNode_0_2140_Title}

this was the new employee onboarding template
but it looks like it's mostly working now.
Thank you!
