### ISSUE TITLE
[BUG] Add-PnPField (also Add-PnPFieldFromXml)

### ISSUE THREAD

**Issue by jasmeeners** [pnp/powershell#3187]
PnP.Powershell

Attempt to create a site column using Add-PnPField  with an ampersand in the Internal Name
eg. "test&"

$displayName = "test&"

$internalName = $displayName

$fldObj = Add-PnPField -DisplayName $displayName -InternalName $internalName -Type "Text"

### Expected behavior 
Site Column should be created
If you use the SharePoint GUI it allows the column to be created 

Create New Site column , creates a new site column with the following attributes:
display name is "test&" and internal name is "test_x0026_" and static name is "test_x0026_"

### Actual behavior 
an error is thrown "An error occurred while parsing EntityName"

$displayName = "test&"

$internalName = $displayName

$fldObj = Add-PnPField -DisplayName $displayName -InternalName $internalName -Type "Text"
Add-PnPField : An error occurred while parsing EntityName. Line 1, position 31.
At line:7 char:11
+ $fldObj = Add-PnPField -DisplayName $displayName -InternalName $inter ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Add-PnPField], ServerException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Fields.AddField

### Steps to reproduce behavior
$displayName = "test&"

$internalName = $displayName

$fldObj = Add-PnPField -DisplayName $displayName -InternalName $internalName -Type "Text"
Add-PnPField : An error occurred while parsing EntityName. Line 1, position 31.
At line:7 char:11
+ $fldObj = Add-PnPField -DisplayName $displayName -InternalName $inter ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Add-PnPField], ServerException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Fields.AddField

### What is the version of the Cmdlet module you are running?
1.11.59

### Which operating system/environment are you running PnP PowerShell on?
- Windows 10
-

**Comment by gautamdsheth** [comment]
Hi @jasmeeners , unfortunately we can't fix this issue from our end.
We use CSOM SDK underneath to create fields from XML. 

This is one of those weird SharePoint issues where the UI uses different API and the code uses a different one.

This is also reproducible outside of PnP PowerShell itself when used directly via CSOM.

If it is a major issue, would request you to raise that with Microsoft support and mention that there is a problem with CSOM when creating fields.

We wont be able to fix it from the PnP PowerShell side, so will have to close it.
