### ISSUE TITLE
[FEATURE] - Addition to Send-PnPMail - Add option to attach files #3136

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/powershell#3195]
It would be very nice if the -Attachment could take an URL (or preferably an Array of URLs ) to files in SharePoint 

**Describe alternatives you've considered**
As of now the -Attachment can take a path to the local file system, and in an Azure Function this is not optimal.

**Comment by gautamdsheth** [comment]
hey @kasperbolarsen , took some time, but finally added support for this via `-Files` parameter. Available from tomorrow's nightly builds :) 

Thanks for this FR.
