### ISSUE TITLE
Add-PnPApp on Sharepoint 2019 Tenant using public url

### ISSUE THREAD

**Issue by PedroMordeP** [pnp/powershell#32]
### Reporting an Issue or Missing Feature
I'm trying to add an App (sppkg) to SharePoint 2019 tenant app catalog from outside the server.
Add-PnPApp is using the internal url of the tenant site app catalog

### Expected behavior 
Using Get-PnPApp it works well listing all the installed apps on Tenant App Catalog
Using Add-PnPApp ,gives and error but should also use the current context to install the app on the Tenant App Catalog

### Actual behavior 
Using Add-PnPApp gives and error saying **The remote name could not be resolved: 'debug-sp'**
"debug-sp" is the internal host name of the server

### Steps to reproduce behavior
Executing this outside the SP2019 server

```
# connecting outside the server using public url
Connect-PnP -url "http://publicurl.westus.cloudapp.azure.com/sites/classicteam"

#this works list all app from the tenant app catalog
Get-PnPApp

# this gives the error: The remote name could not be resolved: 'debug-sp'
Add-PnPApp -Path "complete_path_to_sppkg" -Scope Tenant

```

The only option that I have is to execute this only inside the SharePoint server, but I need to use outside

### What is the version of the Cmdlet module you are running?
SharePointPnPPowerShell2019 3.25.2009.1

**Comment by erwinvanhunen** [comment]
The cmdlet makes a call the underlying PnP Sites Core library. This library resolves the url of the tenant appcatalog from the web the web based upon the context url which is being used, e.g. in this case http://publicurl.westus.cloudapp.azure.com/sites/classicteam. But it's the server APIs that return this URL. What do you get back when you run `Get-PnPTenantAppCatalogUrl` as that cmdlet is running the same API?

**Comment by PedroMordeP** [comment]
To use `Get-PnPTenantAppCatalogUrl` (only available for Online) i need to import SharePointPnPPowerShellOnline cmdlet , running this command it gives the internal url : http://debug-sp/sites/appcatalog

```
Connect-PnP -url "http://publicurl.westus.cloudapp.azure.com/sites/classicteam"
Get-PnPTenantAppCatalogUrl

```
returns **http://debug-sp/sites/appcatalog**

It's not using the host url that I used to connect.

But `Get-PnPApp` resolves it well because it returns all that I have on the tenant app catalog

**Comment by erwinvanhunen** [comment]
Currently it is not possible to provide the app catalog url, but I'll take it up with the team. The core library that this version is using behind the scenes will be archived at the end of this year, e.g. no more changes will happen to both SharePointPnPPowerShell2019 and that core library as of next year. I reclassified this as an enhancement and not a bug as it's actually behaving as we intended it too. I understand your request though and maybe we can push an update in before we do the last release of this module. See https://pnp.github.io/powershell for our roadmap.

**Comment by erwinvanhunen** [comment]
Some additional info: our guess is that the default url configured for the webapp in your case is debug-sp, whereas it should point to the public url instead. So maybe you can fix this with the alternate access mappings of your server. It seems that the CSOM api which we use under the hood only uses the default configured URL for the webapp, which in your case is debug-sp. For now, logging in to the server will be the only way to provision the app to the server.
