### ISSUE TITLE
[BUG] Connect-Pnp Online with managed identity on Azure arc server

### ISSUE THREAD

**Issue by pvanwaeyenberge** [pnp/powershell#3206]
### Reporting an Issue or Missing Feature
Reporting an issue

### Expected behavior 
Connect-PnPOnline -Url ".." -ManagedIdentity. Connect with pnponline form azure arc server to sharepoint online with a system managed identity

### Actual behavior 
Connect-PnpOnline -Url "...." -ManagedIdentity. The server from which I'm running this is azure arc enabled and the system managed identity of the server has been given the Sites.FullControll.All Sharepoint Permissions. The first error I got is that the api version is not found "The api-version '2019-08-01' could not be found"

Connect-pnponline -url "XXXX" -ManagedIdentity -Verbose
VERBOSE: Checking for updates, current version is 2.1.1. See https://pnp.github.io/powershell/articles/configuration.html#disable-or-enable-version-checks for more information.
VERBOSE: No newer version of PnP PowerShell is available
VERBOSE: Connecting using Managed Identity
VERBOSE: Acquiring token for resource https://xxxx.sharepoint.com
VERBOSE: Using scope https://xxx.sharepoint.com for managed identity token coming from the passed in default resource
VERBOSE: Using identity endpoint: http://localhost:40342/metadata/identity/oauth2/token
VERBOSE: Using identity header:
VERBOSE: Using the system assigned managed identity
VERBOSE: Sending token request to http://localhost:40342/metadata/identity/oauth2/token?resource=https://xxxx.sharepoint.com&api-version=2019-08-01
Connect-PnPOnline: {"error":"invalid_request","error_description":"The api-version '2019-08-01' could not be found. Supported are 2020-06-01 2019-11-01 2019-08-15","error_codes":[404],"timestamp":"2023-06-20 10:15:24.2253716 +0200 CEST m=+3964490.460604401","trace_id":"","correlation_id":"ad0f371f-40e5-4a5f-9bd4-64542cf5c4c3"}

So I contacted microsoft support but they couldn't help but gave me the tip that I could change the api version myself. So I made a new build of PnP.Powershell with this line ( https://github.com/pnp/powershell/blob/dev/src/Commands/Base/TokenHandling.cs#L147)
changed to  api version 2020-06-01. After loading this pnp.powershell version I got another error message

VERBOSE: Connecting using Managed Identity
VERBOSE: Acquiring token for resource https://xxxx.sharepoint.com
VERBOSE: Using scope https://xxxx.sharepoint.com for managed identity token coming from the passed in default resource
VERBOSE: Using identity endpoint: http://localhost:40342/metadata/identity/oauth2/token
VERBOSE: Using identity header:
VERBOSE: Using the system assigned managed identity
VERBOSE: Sending token request to http://localhost:40342/metadata/identity/oauth2/token?resource=https://xxxx.sharepoint.com&api-version=2020-06-01
Connect-PnPOnline: {"error":"unauthorized_client","error_description":"Missing Basic Authorization header","error_codes":[401],"timestamp":"2023-06-20 09:59:57.2679388 +0200 CEST m=+3963563.508114901","trace_id":"","correlation_id":"03256194-0a51-44e9-aaaa-e777c9736f10"}

### Steps to reproduce behavior
See above all the information. The server is a Microsoft Windows Server 2022 Datacenter

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
Powershell 7.3.4
Powershell version 2.1.1

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by joelhaslerfhnw** [comment]
I have the same error. I use PnP.Powershell 2.2.0 and Powershell 7.3.5

**Comment by pvanwaeyenberge** [comment]
Does anyone now why this happens?

**Comment by gautamdsheth** [comment]
@pvanwaeyenberge @LeonarddeR - this issue should be fixed now with tomorrow's nightly builds as well as in the next major release. It was because we were not properly handling certain Azure services.
