### ISSUE TITLE
[BUG] Error with colliding assemblies when using Start-ThreadJob 

### ISSUE THREAD

**Issue by AndersRask** [pnp/powershell#3207]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
According to the note in the start of this article: https://pnp.github.io/powershell/articles/azurefunctions.html
![image](https://github.com/pnp/powershell/assets/1651150/b1fbad37-5737-4b8d-8daa-1fbb7a56502a)
We should use Start-ThreadJob as a way to mitigate the assembly load issue that especially now with .NET 6 has been an issue when using PnP.PowerShell with other modules, like Microsoft.Identity.Client in Az.Account 

When I try the examples in the above article with Start-Job in PowerShell 5.1 it works fine, but as soon as I use PowerShell 7 it fails with the dreaded "Assembly with same name is already loaded"

I believe this is because the way AppDomains work in .NET Framework vs .NET Core 

On a related note:
_I know you did a lot to prevent these issues when upgrading to 2.1.1 but did you consider ALC bridging?
ALC is the "new" way of loading assemblies in PowerShell 7, and should have better ways of handling multiple versions of the same assembly. There are a few samples in the code below that show how to avoid this breaking code into two modules and using the IModuleAssemblyInitializer to lazy load and undload assemblies into ALC.

https://learn.microsoft.com/en-us/powershell/scripting/dev-cross-plat/resolving-dependency-conflicts?view=powershell-7.3#more-robust-solutions

Would love to hear your thoughts? :)_

### Actual behavior 
When using Start-ThreadJob in PowerShell 7 we were expecting to be able to use Az along with PnP.PowerShell

### Steps to reproduce behavior

```
$script = {
      Connect-PnPOnline tenantname.sharepoint.com/sites/test -Interactive
      $web = Get-PnPWeb
      $web.Title}
$webtitle = Start-ThreadJob -ScriptBlock $script | Wait-Job | Receive-Job
# webtitle returns title:
$webtitle
PS> test123
```
Also a observe that loaded modules show that modules are indeed not loaded, but checking the appdomain for assemblies reveal that pnp powershell are indeed loaded witch will cause trouble later:
```
[AppDomain]::CurrentDomain.GetAssemblies() | ? FullName -like *pnp.powershell* | select fullname
PS> PnP.PowerShell, Version=2.1.1.0, Culture=neutral, PublicKeyToken=null
PS> PnP.PowerShell.ALC, Version=2.1.1.0, Culture=neutral, PublicKeyToken=null
```
Now if we try to run an Az command like Get-AzADUser in a seperate job look what happens:
```
$getUsers = {
    Connect-AzAccount -Tenantid $tenantId -SubscriptionId $subid | out-null
   Get-AzAdUser
}
Start-ThreadJob -ScriptBlock $getUsers | Wait-Job | Receive-Job
```
_The 'Get-AzADUser' command was found in the module 'Az.Resources', but the module could not be loaded due to the following error: [Assembly with same name is already loaded]
For more information, run 'Import-Module Az.Resources'._

### What is the version of the Cmdlet module you are running?
PowerShell 7.3.4
PnP.PowerShell 2.1.1
Az.Resources 3.3.0

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by AndersRask** [comment]
Just thought i'd bump this one.
Would love to hear @KoenZomers if you guys looked into using an ALC bridging pattern now that you are on core?

> 
> I know you did a lot to prevent these issues when upgrading to 2.1.1 but did you consider ALC bridging?
> ALC is the "new" way of loading assemblies in PowerShell 7, and should have better ways of handling multiple versions of the same assembly. There are a few samples in the code below that show how to avoid this breaking code into two modules and using the IModuleAssemblyInitializer to lazy load and undload assemblies into ALC.
> 
> https://learn.microsoft.com/en-us/powershell/scripting/dev-cross-plat/resolving-dependency-conflicts?view=powershell-7.3#more-robust-solutions
> 

Would love to hear

**Comment by gautamdsheth** [comment]
hi @AndersRask , would you be able to test out this PR , https://github.com/pnp/powershell/pull/3280 ? 

I was able to get it working locally with Az modules , but would be awesome if you could also test it out in your script/code as well.

**Comment by AndersRask** [comment]
> 

Hi @gautamdsheth 

sounds awesome! 
Did you go the ALC bridging pattern route?
I am currently on vacation, but will see if I can find time to test the PR.

Did you test specifically the Start-ThreadJob on 7.3 or did you also manage to solve the colliding assembly loading issue in core?

**Comment by gautamdsheth** [comment]
Yes, using ALC for loading the dependencies. 
I tested it on PowerShell 7.2 latest version.

**Comment by gautamdsheth** [comment]
Going to keep this issue open for now. 
Have merged the fix , should be available in nightly releases starting tomorrow.

Would love to have your feedback on it.

**Comment by Nm-jens** [comment]
I ran into the same issue. After installing nightly build, with the mentioned fix... the assemblies error ("Assembly with same name is already loaded") was replaced by:

`Write-Error: EXITING: Error Connection: Could not load file or assembly 'PnP.PowerShell.ALC`

**Comment by gautamdsheth** [comment]
Yep, fixing it 😊

**Comment by gautamdsheth** [comment]
@Nm-jens - sorry about that, should be fixed with tomorrow's nightly.

**Comment by Nm-jens** [comment]
@gautamdsheth Wow incredibly fast, amizing. Thank you for that!

**Comment by gautamdsheth** [comment]
Welcome 🤗 

This has been long overdue , spent quite some time over this but looks like I finally managed to get it working.

Let me know if it’s still an issue. 

You will need today’s nightly build to test , just tested on my machine and it worked 😊

**Comment by AndersRask** [comment]
> Welcome 🤗
> 
> This has been long overdue , spent quite some time over this but looks like I finally managed to get it working.
> 
> Let me know if it’s still an issue.
> 
> You will need today’s nightly build to test , just tested on my machine and it worked 😊

Very nice job @gautamdsheth !

I just tested connecting to SPO and connecting to Az in the same session without issue.

This just made my day THANK YOU!

**Comment by Nm-jens** [comment]
Also confirmed by me. Works like expected. Thank you for fast resolving.

**Comment by AndersRask** [comment]
Glad I could help pointing at the ALC. 
As this is a. Net core thing, does this mean the module no longer works on posh 5.1?

**Comment by rifton007** [comment]
Hello, I have same issue yet on VS + PS for VS 2023
Someone can help m ?

```PowerShell
Connect-PnPOnline: 
     | Could not load file or assembly 'Microsoft.Identity.Client, Version=4.50.0.0, Culture=neutral,
     | PublicKeyToken=000'. Could not find or load a specific file. (0x80131621)
```
```PowerShell

PS > Get-Module PnP.PowerShell

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   2.2.0                 PnP.PowerShell                      {Add-PnPAlert, Add-PnPApp, Add-PnPApplicationCustomizer, A…

PS > Get-Package Microsoft.Identity.Client
Name                           Version          Source                           ProviderName
----                           -------          ------                           ------------
Microsoft.Identity.Client      4.53.0           https://www.powershellgallery.c… PowerShellGet

PS > $pSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.10
PSEdition                      Core
GitCommitId                    7.3.10
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Thanks,

**Comment by AndersRask** [comment]
Could you try the latest nightly release?
What other modules have you loaded? If you use Az.Accounts or similar, try connecting to PnP first, then do other stuff.

**Comment by rifton007** [comment]
@AndersRask 
I have updated PnP.
```
PS > Get-Module PnP.PowerShell

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   2.3.7      nightly    PnP.PowerShell  
```

But I have another problem
```
Could not load file or assembly 'System.IdentityModel.Tokens.Jwt, Version=6.27.0.0, Culture=neutral, | PublicKeyToken=000'. Could not find or load a specific file. (0x80131621)
```

**Comment by nicole-ge** [comment]
Hello,
I'm using in Azure Automation the module 2.4.0 | PnP.PowerShell and it is still loading Microsoft.Graph.Core, Version=1.25.1.0
so the problem is still there and I could not "Could not load type 'Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider". what can I do?

**Comment by JoeyInvictus** [comment]
Hopefully, this helps someone. I was able to get rid of the `Could not load file or assembly 'Microsoft.Identity.Client` error by running `Import-Module -Name PnP.PowerShell` in my Azure Function code before connecting.
