### ISSUE TITLE
can't create team based on EDU_Class template

### ISSUE THREAD

**Issue by mbouwman** [pnp/powershell#322]
With the new PnP Cmdlet New-PnPTeamsTeam I can't create a team based on EDU_Class template. The option -Template is not available.

**Comment by erwinvanhunen** [comment]
We added the `-Template` parameter to the code, and the functionality will be available in release 1.3.13-nightly which will be available tomorrow:

```powershell
Install-Module -Name PnP.PowerShell -AllowPrerelease
```

**Comment by mbouwman** [comment]
whoow, ythat's quick !
Thank you so much !

**Comment by lucahost** [comment]
is this possible for an existing group?

if I provide the id of an existing group, -GroupId, can I choose the -template?

**Comment by mbouwman** [comment]
Hello Luca,
No that is not possible, it's only possible when you create the team.

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden

________________________________

**Comment by lucahost** [comment]
Thanks for your answer!
using the beta graph it's possible (https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&tabs=http#example-4-create-a-team-from-group).

I was wondering if that feature lands in PnP PowerShell as well?
@erwinvanhunen maybe this is already on your backlog?
