### ISSUE TITLE
[BUG] -Includes param behavior in Get-PnPField has regressed

### ISSUE THREAD

**Issue by benleolander** [pnp/powershell#3220]
### Reporting an Issue or Missing Feature
`Get-PnPField` produces an error when used with the `-Includes` parameter in version 2.1.1. This appears to be a regression from previous versions; same reproductions steps below work as expected in (EG) version 1.12.0 

### Expected behavior 
`Get-PnPField` returns the expected field.

### Actual behavior 
Error produced:
`Get-PnPField: The property or field 'FieldTypeKind' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.`

### Steps to reproduce behavior
Import PnP.Powershell @ 2.1.1 and connect to a site.

`Get-PnPField -List "Documents" -Identity "Title"` 
Returns the expected field

`Get-PnPField -List "Documents" -Identity "Title" -Includes Title` 
Produces the above error.

![image](https://github.com/pnp/powershell/assets/44977343/b4790e56-4033-45a2-91bc-e5e65fe02d25)

### What is the version of the Cmdlet module you are running?
2.1.1
Issue still present in 2.1.86-nightly

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Thanks for catching this.
Has been fixed, it will be available in tomorrow's nightly builds and the next major version whenever that will be out.

**Comment by benleolander** [comment]
Thanks @gautamdsheth !
