### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nanddeepn** [pnp/powershell#3221]
### Reporting an Issue or Missing Feature

We are using below in Azure Function:

- PnP.PowerShell V2.1.1 
- Az 9.5.0
- AzTable 2.1.0

### Expected behavior 

PnP PowerShell functions and AzTable related functions (for e.g. `Add-AzTableRow`) should work from Azure function.

### Actual behavior 

Error as follows:
Could not load type 'Microsoft.Extensions.Logging.Abstractions.Internal.NullScope' from assembly 'Microsoft.Extensions.Logging.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (0x80131621)

I also tried dropping the PowerShell version to 7.0 but that did not help.

### Steps to reproduce behavior

Create Azure function with PowerShell v7.2
Use below statements in Azure function:

```
#PnP.PowerShell
Connect-PnPOnline -Url $SiteURL
$web = Get-PnPWeb
$web.ExcludeFromOfflineClient = $true

$web.Update()
$web.Context.ExecuteQuery()

# Azure Table operation with managed identity
Add-AzTableRow -table $cloudTable -partitionKey $pk -rk $channelId -property $property
```

### What is the version of the Cmdlet module you are running?
2.1.1

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Hi @nanddeepn , this can't be fixed from our end.

Please refer to this discussion https://github.com/pnp/powershell/discussions/3057 , issue mostly lies on Az module side loading different version of assembly as compared to PnP PowerShell.
