### ISSUE TITLE
[BUG] Documentation suggests that `Sites.Selected` permissions are supported on `Sync-PnPSharePointUserProfilesFromAzureActiveDirectory`

### ISSUE THREAD

**Issue by martinlingstuyl** [pnp/powershell#3248]
### Reporting an Issue or Missing Feature
The [documentation](https://pnp.github.io/powershell/cmdlets/Sync-PnPSharePointUserProfilesFromAzureActiveDirectory.html#description) of `Sync-PnPSharePointUserProfilesFromAzureActiveDirectory` suggests that you can use `Sites.Selected` permissions on SharePoint to create a sync job. I've tried it, but it does not work. The JSON file is written to the site that you configured, but the job-creation fails right after with an Authorization exception. It needs access to the Tenant Admin site. 

As soon as you grant `Sites.FullControl.All`, the problem is solved.

### Expected behavior 
I'd expect the documentation to be correct 😁

### Actual behavior 
The documentation is not correct:
![image](https://github.com/pnp/powershell/assets/5267487/c16c99f2-a3fd-4c8a-a69d-4ff9d991e97d)

### Steps to reproduce behavior
Follow the documentation and try it out.

### What is the version of the Cmdlet module you are running?
2.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Wanna update the docs ?

**Comment by martinlingstuyl** [comment]
Sure! I was going to, but the time turned out short today ...
