### ISSUE TITLE
Error when running Register-PnPAzureADApp using 2.2.0 & PS 7.3.5

### ISSUE THREAD

**Issue by gautamdsheth** [pnp/powershell#3263]
### Discussed in https://github.com/pnp/powershell/discussions/3262

<div type='discussions-op-text'>

<sup>Originally posted by **wfi-jonas** July 12, 2023</sup>
Anyone able to run this command on the latest version of PnP? I keep getting this error (I'm GA in the tenant).

PowerShell 7.3.5
PS C:\Windows\System32> Register-PnPAzureADApp -ApplicationName PnPPowershell -Tenant tenantname.onmicrosoft.com -Store CurrentUser -Interactive
WARNING:
 No permissions specified, using default permissions

Certificate added to store
Checking if application 'PnPPowershell' does not exist yet...Success. Application 'PnPPowershell' can be registered.
Register-PnPAzureADApp: {"error":{"code":"Request_BadRequest","message":"A null value was found with the expected type 'Edm.String[Nullable=False]'. The expected type 'Edm.String[Nullable=False]' does not allow null values.","innerError":{"date":"2023-07-12T12:05:42","request-id":"an id","client-request-id":"an id"}}}
PS C:\Windows\System32></div>

**Comment by gautamdsheth** [comment]
Looks like some issue in the code, will check

**Comment by johnguilbert1970** [comment]
Still fails in 7.3.6
