### ISSUE TITLE
[BUG] Connect-PnP using certificate-file fails

### ISSUE THREAD

**Issue by dkNeumanns3** [pnp/powershell#3269]
### Reporting an Issue or Missing Feature
Moved from Interactive logon to using a certificate. However I have big issues connecting.
Using PS 7.3.5 in Visual Studio Code editor.

### Expected behavior 
Expect connection to succeed and return connection variable.

### Actual behavior 
Error message (have seen a lot of different ones, but this one is the latest):
Connect-PnPOnline: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.36.1.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'. Could not find or load a specific file. (0x80131621)

### Steps to reproduce behavior
$conn = Connect-PnPOnline -Url <URL> -ClientId $applicationID -Tenant service3dk.onmicrosoft.com -CertificatePath '<UNC-path>' -ReturnConnection
Using same method with registered app for Microsoft Teams (app was created using the Register...- cmdlet).

### What is the version of the Cmdlet module you are running?
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   1.12.0                PnP.PowerShell                      Core,Desk {Add-PnPAdaptiveScopeProperty, Add-PnPPropertyBagValue, Add-PnPSiteClassification, Copy-PnPFolder…}

Have tried version 2.2.x0also, but with different error than above:
Connect-PnPOnline: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.50.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'. Could not find or load a specific file. (0x80131621)

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.5
PSEdition                      Core
GitCommitId                    7.3.5
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by gautamdsheth** [comment]
hi @dkNeumanns3 , we have seen some earlier issues as well when it comes to using VS code extension. Unfortunately, we wont be able to fix it since it is quite complicated and we would want to fix other issues.

Would recommend that you use standalone PowerShell 7.2 or later editions for this since it doesn't occur in them
