### ISSUE TITLE
[BUG] Set-PnPListItem -Batch not available

### ISSUE THREAD

**Issue by rmillener** [pnp/powershell#327]
### Expected behavior 
Set-PnPListItem allows batching as per the documentation. This should mirror Add-PnPListItem which does have this parameter.

### Actual behaviour 
Running the code as per the documentation returns "Set-PnPListItem : A parameter cannot be found that matches parameter name 'Batch'.".

### Steps to reproduce behaviour
As per documentation:

```
$batch = New-PnPBatch
for($i=0;$i -lt 100;$i++)
{
    Set-PnPListItem -List "Demo List" -Identity $i -Values @{"Title"="Updated Title"} -Batch $batch
}
Invoke-PnPBatch -Batch $batch
```

### What is the version of the Cmdlet module you are running?
1.3.13

### Which operating system/environment are you running PnP PowerShell on?
- [ x ] Windows

**Comment by erwinvanhunen** [comment]
Good catch! Someone a change made recently removed the public availability of that parameter. We'll get it back in place again. It will be available tomorrow in the 1.3.14-nightly release.
