### ISSUE TITLE
[BUG] New-PnPTeamsTeam fails silently when using an App registration

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/powershell#3294]
### Reporting an Issue or Missing Feature
Creating a Group and teamify it afterwards, without specifying any Owner, like this
$conn = Connect-PnPOnline -Url $SharePointAdminSiteURL -ClientId $clientID -Tenant $tenantId -CertificatePath "C:\temp\pnp-dev.pfx" -CertificatePassword (ConvertTo-SecureString -AsPlainText -Force "password") -ReturnConnection 

$group = New-PnPMicrosoft365Group -DisplayName "test987654" -MailNickname "test987654321" -IsPrivate -Description "test" -Connection $conn

$teamsTeam = New-PnPTeamsTeam -GroupId $group.Id -Connection $conn

Nothing happens in the New-PnPTeamsTeam cmd, after 10-15 secs the cmd completes, but returns nothing and the Group has not been teamified.

### Expected behavior 
Since an Owner seems to be a prereq I would expect an exception stating that the group can't be teamified as an Owner is missing?

### Actual behavior 
Nothing happens

### Steps to reproduce behavior
as above

### What is the version of the Cmdlet module you are running?
2.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [x] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Thanks @kasperbolarsen for creating this issue, it has been fixed . 
Will be available in tomorrow's nightly build as well as the next major version
