### ISSUE TITLE
[BUG] Error while compiling Dev branch of PnP.Powershell repository 

### ISSUE THREAD

**Issue by NishkalankBezawada** [pnp/powershell#3296]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

### Reporting an Issue or Missing Feature
I have recently forked the dev branch of PnP.PowerShell and was compiling the code in my machine. The code was compiling and I was able to debug the code as normal until Friday (21st July 2023). It works fine with Master branch

But since Yesterday, Whenever i try to run the code, I get a error as below, 

```WARNING: load.ps1: Import Modules -- Exception has been thrown by the target of an invocation.```

(Screenshot as below)

![image](https://github.com/pnp/powershell/assets/47456098/f523e705-31f9-475c-8851-5a125a35af5b)

I have tried to ignore this error and tried to connect to SPO and then i get this below error. 

```WARNING: load.ps1: Import Modules -- Exception has been thrown by the target of an invocation.
PS C:\Research\PnPPowershell\powershell> connect-PnPOnline -Url 'https://pm3q.sharepoint.com/sites/SampleTeamSite' -Interactive
connect-PnPOnline: The 'connect-PnPOnline' command was found in the module 'PnP.PowerShell', but the module could not be loaded due to the following error: [Assembly with same name is already loaded]
For more information, run 'Import-Module PnP.PowerShell'.
PS C:\Research\PnPPowershell\powershell>
```

(Screenshot as below)

![image](https://github.com/pnp/powershell/assets/47456098/412f1501-c66a-4f1e-b3b9-22010d0c7c2c)

I tried to connect to SPO outside of the repository, it doesnt give me this error.

(Screenshot as below)

![image](https://github.com/pnp/powershell/assets/47456098/2ec4eca0-5f3b-46e7-a649-3109d9a103c8)

### Suggestion

If i try compiling Master branch, It works as a charm. 

![image](https://github.com/pnp/powershell/assets/47456098/a13a8d2d-883f-4e0b-94e7-90aa80acaba4)

![image](https://github.com/pnp/powershell/assets/47456098/0bb33b3c-6c35-4b76-9d46-aaed4ca6d9a8)

I guess this error is from ```src\Commands\_debug\debug.ps1``` & ```src\Commands\Base\PnPPowerShellModuleInitializer.cs```. (Just skeptical, Please correct me if i am wrong). Kindly suggest. 

### Expected behavior 
Should be able to compile the code and debug

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

![image](https://github.com/pnp/powershell/assets/47456098/1798da6b-7430-47d8-827c-c6d004f47c07)

![image](https://github.com/pnp/powershell/assets/47456098/4df8e930-1b8e-4e8e-afbd-21b6a8de6549)

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

Thanks,
Nishkalank Bezawada

**Comment by NishkalankBezawada** [comment]
Hello @gautamdsheth, Kindly suggest. 

Thanks,
Nishkalank

**Comment by gautamdsheth** [comment]
Closing it as I have fixed it, should start working now.
Maybe rebuild the solution if needed.

**Comment by NishkalankBezawada** [comment]
Thanks @gautamdsheth, I've tested and can confirm that it's working now.
