### ISSUE TITLE
Connect-PnPOnline System.Configuration.ConfigurationManager error

### ISSUE THREAD

**Issue by MikkoKoskinen** [pnp/powershell#33]
### Reporting an Issue or Missing Feature
When connecting "Connect-PnPOnline" from Azure Function on PnP.PowerShell  an error is thrown

$spConn  = Connect-PnPOnline -Url $adminSiteURL -Credentials $o365credential -ReturnConnection

### Expected behavior 
The connection is established and a context is returned.

### Actual behavior 
I'm getting an error "Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'." with the following trace:

" Message        : The type initializer for 'Microsoft.SharePoint.Client.ClientContextExtensions' threw an exception.
    Data           : System.Collections.ListDictionaryInternal
    InnerException : 
        Type           : System.IO.FileLoadException
        Message        : Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)
        FileName       : System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
        TargetSite     : Void .cctor()
        StackTrace     : 
   at Microsoft.SharePoint.Client.ClientContextExtensions..cctor()
        InnerException : 
            Type       : System.IO.FileLoadException
            Message    : Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'."

### Steps to reproduce behavior
Create an Azure Function based on PowerShell Core. Run the Connect-PnPOnline command.

$spConn  = Connect-PnPOnline -Url $adminSiteURL -Credentials $o365credential -ReturnConnection

### What is the version of the Cmdlet module you are running?
Using the nightly build PnP.PowerShell 0.2.13.

**Comment by erwinvanhunen** [comment]
We are aware of this issue. It seems to do with the fact that certain latest releases of assemblies in the 5.0.0 that were readied for .NET 5.0 do not work fully on .NET Core 3.1. We are working on fixing this.

**Comment by erwinvanhunen** [comment]
We fixed things in the underlying PnP Framework assemblies and published a new nightly which should solve your issues. Please check out the latest nightly build (0.2.16-nightly or newer). I will close this issue, but do not hesitate to open a new one if the issue still occurs.
