### ISSUE TITLE
[FEATURE]- Update Grant-PnPAzureADAppSitePermission to not require the tenant admin to have access to the site collection

### ISSUE THREAD

**Issue by joerodgers** [pnp/powershell#3302]
When using the -Site option on the Grant-PnPAzureADAppSitePermission cmdlet, a lookup of the siteId using 

```siteId = Site.GetSiteIdThroughGraph(Connection, AccessToken) ```

is executed.  This Graph call mandates the user identity running the cmdlet, if using delegated authentication, have full control access to the target site, which is not likely to be a common scenario.

**Comment by gautamdsheth** [comment]
Well, we need full control to grant the permission itself, so not sure if this makes sense.
Even if we make it like read , the cmdlet will fail if we dont have permission to grant it.

**Comment by joerodgers** [comment]
Sorry, you're right. Closing.
