### ISSUE TITLE
[BUG] New-PnPAzureADGroup returns Object reference not set to an instance of an object with all the required fields.

### ISSUE THREAD

**Issue by Brainless1980** [pnp/powershell#3305]
### Reporting an Issue or Missing Feature
New-PnPAzureADGroup not works as expected.

### Expected behavior 
New-PnPAzureADGroup -DisplayName a3 -MailNickname a3 -Description a3 should create a group.

### Actual behavior 
New-PnPAzureADGroup -DisplayName a3 -MailNickname a3 -Description a3 gives the following error:
New-PnPAzureADGroup: Object reference not set to an instance of an object.

### Steps to reproduce behavior
`Connect-PnPOnline`
`New-PnPAzureADGroup -DisplayName a3 -MailNickname a3 -Description a3`

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 2.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows

**Comment by Brainless1980** [comment]
It works if you use members AND owners with all the required fileds.
`New-PnPAzureADGroup -DisplayName a3 -MailNickname a3 -Description a3 -IsSecurityEnabled -Members "xxx@xxx.com" -owners "xxx@xxx"`

**Comment by gautamdsheth** [comment]
The issue has been fixed , will be available in tomorrow's nightly.

You should also specify `-IsSecurityEnabled` or `-IsMailEnabled` parameter , if both are false, then also it wont work.
