### ISSUE TITLE
[BUG] Error with Organization Chart WebPart in Publish-PnPCompanyApp

### ISSUE THREAD

**Issue by juacruz** [pnp/powershell#3323]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 

The Organization Chart WebPart should display the selected person along with their reporting structure and relevant team members in a visually accurate and organized manner.

### Actual behavior 

The WebPart fails to display the selected person's information. Instead, it appears as if the WebPart is not loading the data or presenting the relevant hierarchy as it should.

### Steps to reproduce behavior

- Create Communication Site and add Organization Chart to the page.
- Select any team or department.
- The WebPart shows the correct information.
- Publish-PnPCompanyApp
- Navigate to the Teams application.
- Observe that the selected person's details are missing on the WebPart.

### What is the version of the Cmdlet module you are running?
1.7.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [X] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [] Other : please specify

**Comment by veronicageek** [comment]
@juacruz - Can you please first update to the latest (major and/or nightly). Note that from version 2.x you'll need PS 7.2 and above.

**Comment by juacruz** [comment]
Updated to the 2.2.0 version and the issue is still present :(

**Comment by gautamdsheth** [comment]
hi @juacruz , we got a word from Microsoft engineering that this cmdlet is now no longer a supported scenario. We have now deprecated this cmdlet and will be removing it in a future release .
