### ISSUE TITLE
[BUG] Add-PnPListItem 

### ISSUE THREAD

**Issue by OLampl** [pnp/powershell#333]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
When executing Add-PnPListItem the first time an exception occurs. (But the Item was created successfully)
When I execute the same code the second time, the Listitem was created either but without any error

### Expected behavior 
The Listitem is created without an issue, by the first time!

### Actual behavior 
format-default : The collection has not been initialized. It has not been 
requested or the request has not been executed. It may need to be explicitly 
requested.
    + CategoryInfo          : NotSpecified: (:) [format-default], CollectionNotIn 
   itializedException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.CollectionNotInitialize 
   dException,Microsoft.PowerShell.Commands.FormatDefaultCommand

### Steps to reproduce behavior
Dynamic loading of the PnP.Powershell commandlets during Runtime
Authentication via Certificate
SharePoint Online SiteCollection, Custom Item list.
Texfields, Peoplepicker 1(No Multiple Values, People Only), Peoplepicker 2(Multiple Values, People Only)
 Add-PnPListItem -List "YOurList" -Values $listItemValues

### What is the version of the Cmdlet module you are running?
1.3.13-nightly

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
The error message you're seeing is a 'quirk' of CSOM and PowerShell. The cmdlet returns an item after adding it. That object that is being returned contains a bunch of properties and collection values. PowerShell will always try to parse those values if they are rendered to the output. However, by default CSOM is limiting what is being returned from the server. It will simply access the properties on the object. CSOM has been developed in such a way that if a collection or property is access that has not been loaded it will throw the exception you see above. 

The result is that we as developers have to explicitly ask for certain fields to return. By default we display the id, the title and the uniqueid when show a list item as we do not know ahead of time what you are looking for in the item.

In your script example, do you do something more after Add-PnPListItem? If you try to access a property from that list item that has not been loaded you will have to retrieve it with Get-PnPListItem.

**Comment by OLampl** [comment]
No, I just create a new Listitem. As I allready mentionend. If I execute the Script again, the Add-PnPListItem works as expected.

**Comment by erwinvanhunen** [comment]
Can you try to modify your script as follows?

```powershell
$i = Add-PnPListItem -List "yourlist" -Values $listitemValues
```

And try again?

You will notice that you most likely do not receive the error message, as PowerShell is not parsing the output it receives from the cmdlet. However, if you then on a new line enter $i<enter>, do you receive the error then? If you receive an error can you enter `Get-PnPException` and paste the result of that here?

What would be interested to know is what is in the content of your `$listitemValues` variable, as that can have an effect on the `Add-PnPLlistItem` execution. So the actual content, or at least obfuscated, but formatted as you have it formatted.

**Comment by OLampl** [comment]
Your where right, as soon as I did modify my code in the way you've mentioned- it worked. But why it came to this behavior. 
I'm using that script since months. I just started to modify my provisioning scripts, to use PnP.PowerShell. Never had an issue, before. Even with earlier versions of the PnP.Powershell, but unfortuanelty I can't tell you the version on which I've testet and it worked. Since I'm updating the bins on time ;)

Here the content of the $listitemValues variable:
Name                           Value                                                                                                
----                           -----                                                                                                
DomCompanyCode                 99999                                                                                                
DomCollaborationTarget         SPOnline                                                                                             
DomProvisioningStatus          Bereit                                                                                               
DomSpaceRequestedBy            Oliver.Lampl02-tst@domain-TST.AT                                                                       
DomDescription                 Prov Test Standard Online                                                                            
DomCostCenter                  0815                                                                                                 
DomCountryCode                 AT                                                                                                   
DomTeamsOwnerOrSCV             {Oliver.Lampl01-tst@domain-TST.AT, Oliver.Lampl02-tst@domain-TST.AT}                                    
Title                          Test random3f42fd2e170f                                                                              
DomItsmParent                  StandardOnline_SN                                                                                    
DomWebName                     random3f42fd2e170f                                                                                   
DomCollaborationTemplate       Standard                                                                                             
DomOrganizationDevelopment     0815

**Comment by OLampl** [comment]
Update: It seems a general issue, now I have the same behavior for Set-PnPListItem , if I use it without an assignment like `$dummyRetval= Set-PnPListItem` I get the same error. The next command is not related to PNP. 
After the `Add-PnPLlistItem` I use the `Move-Item` command.
After the `Set-PnPListItem`, I write a Logentry with nLog.

In both cases, I avoid an Issue if just catch the returnvalue- even I didn't need it. Now I have to add on every PnP-Command my `$dummyRetval`, to avoid further issues? Hopefully not.

**Comment by erwinvanhunen** [comment]
Have you considered removing and reinstalling PnP PowerShell? I'm wondering if the format file ended up corrupt on your end. The file is located in the installation folder and is called PnP.PowerShell.dll-help.xml.

**Comment by OLampl** [comment]
There is nothing to remove / reinstall, currently using 1.3.15-nightly - since I try to avoid to install the modules. I download the Nugets, unpack them and load it with `Import-Module`, probably that might be an issue?
