### ISSUE TITLE
[BUG] Documentation for Submit-PnPTeamsChannelMessage requires non-existent ChannelMessage.ReadWrite.All

### ISSUE THREAD

**Issue by azureskydiver** [pnp/powershell#3330]
### Reporting an Issue or Missing Feature
Documentation for Submit-PnPTeamsChannelMessage says:
> Microsoft Graph API: API required one of 'Teamwork.Migrate.All, ChannelMessage.ReadWrite.All'.

but there is no such permission named `ChannelMessage.ReadWrite.All` anymore.

### Expected behavior 
Expect documentation to have the correct/up-to-date permissions required.

### Actual behavior 
Permission named `ChannelMessage.ReadWrite.All` can't be found in Azure AD app registration.

### Steps to reproduce behavior
Go to the documentation for Submit-PnPTeamsChannelMessage

### What is the version of the Cmdlet module you are running?
2.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Good catch @azureskydiver , have updated the docs, will be reflected in tomorrow.
