### ISSUE TITLE
[BUG] - PnP.PowerShell v2.2.0 - Connection and Import Module Errors

### ISSUE THREAD

**Issue by robertcaretta** [pnp/powershell#3331]
### Reporting an Issue or Missing Feature
There is some issues with importing the module and connecting. Testing with the following:

- VS Code v1.81.0
- PowerShell v7.3
- PowerShell Extension v2023.6
- PnP.PowerShell v2.2.0 – Installed here:
   C:\Program Files\WindowsPowerShell\Modules\PnP.PowerShell

### Expected behavior 
Module imports correctly, and connects correctly.

### Actual behavior 
**Error 1**
Import-Module -Name PnP.PowerShell
Connect-PnPOnline

_Connect-PnPOnline: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.50.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'. Could not find or load a specific file. (0x80131621)_

**Error 2**
Import-Module -Name PnP.PowerShell -RequiredVersion 2.2.0 -UseWindowsPowerShell

_Import-Module: Failure from remote command: Import-Module -Name 'PnP.PowerShell': Could not load file or assembly 'System.Management.Automation, Version=7.2.0.0, Cultu
re=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified._

### Steps to reproduce behavior
See information above in actual behavior.

When I change the required module back to 1.11.0 the code works fine as before. Imports and connects properly. Work-around is this:  Import-Module -Name PnP.PowerShell -RequiredVersion 1.11.0 -UseWindowsPowerShell

### What is the version of the Cmdlet module you are running?
2.2.0
1.11.0
1.8.0
1.7.0
1.6.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by raoue** [comment]
I have the same error message when I run the Connect-PnPOnline command.
I've attached a list of assemblies at run time and it shows "Microsoft.Identity.Client, Version=4.49.1.0" for file C:\Program Files\PowerShell\Modules\Microsoft.Graph.Authentication\2.2.0\Dependencies\Core\Microsoft.Identity.Client.dll. This is the latest version of the Microsoft.Graph module. There is no 4.50 Microsoft.Identity.Client available.
[assemblies-within-PSStudioRun-PnP.PS.v.2.2.0.csv](https://github.com/pnp/powershell/files/12296294/assemblies-within-PSStudioRun-PnP.PS.v.2.2.0.csv)

**Comment by raoue** [comment]
Additional Information, the actual errors received.
Connect-PnPOnline -Url XXXXX @hConnectParams - …
ERROR: |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ERROR: | Could not load file or assembly 'Microsoft.Identity.Client, Version=4.50.0.0, Culture=neutral,
ERROR: | PublicKeyToken=0a613f4dd989e8ae'. Could not find or load a specific file. (0x80131621)
ERROR: |
ERROR: |          $objPnPAdminContext = Get-PnPContext
ERROR: |                                ~~~~~~~~~~~~~~
ERROR: | Could not load file or assembly 'PnP.PowerShell.ALC, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null'. Uncaught
ERROR: | exception during type initialization. (0x80131534)
ERROR: |
ERROR: |          Connect-PnPOnline -Url $OneDriveSiteUrl @hConnectParams -verb …
ERROR: |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ERROR: | Could not load file or assembly 'Microsoft.Identity.Client, Version=4.50.0.0, Culture=neutral,
ERROR: | PublicKeyToken=0a613f4dd989e8ae'. Could not find or load a specific file. (0x80131621)
ERROR: |
ERROR: |  …             Add-PnPSiteCollectionAdmin -Owners $UPNUserRequiresAccess …
ERROR: |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ERROR: | Could not load file or assembly 'PnP.PowerShell.ALC, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null'. Uncaught
ERROR: | exception during type initialization. (0x80131534)
ERROR: |
ERROR: |          Add-RTBText -Content "$(Get-PnPSiteCollectionAdmin | Out-Stri …
ERROR: |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
ERROR: | Could not load file or assembly 'PnP.PowerShell.ALC, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null'. Uncaught
ERROR: | exception during type initialization. (0x80131534)

**Comment by raoue** [comment]
PS Version: 7.3.6
PnP.PowerShell Version: 2.2.0

**Comment by raoue** [comment]
Not certain it has any bearing but noticed the Manifest for 2.2.0 PSEdition is for Desk only, whereas 1.12.0 PSEdition is for both Core, and Desk. This could mean PS is using a different dot Net version depending upon the PSEdition, not certain it does.

**Comment by robertcaretta** [comment]
> Not certain it has any bearing but noticed the Manifest for 2.2.0 PSEdition is for Desk only, whereas 1.12.0 PSEdition is for both Core, and Desk. This could mean PS is using a different dot Net version depending upon the PSEdition, not certain it does.

I did notice that on the home page documentation here. 
https://github.com/pnp/powershell#important---new-pnp-powershell-2x

The weird part is I am using PS 7.x within VS Code, but I do have the module installed in the older directory here. 
C:\Program Files\WindowsPowerShell\Modules\PnP.PowerShell

What I am wondering now is if PnP 2.x needs to be installed in the PS 7.x directory as a requirement?

**Comment by gautamdsheth** [comment]
This issue has been fixed in the latest nightly builds.
Would recommend you to try it out with that.

Check this issue: https://github.com/pnp/powershell/issues/3207

Having said that, would recommend running it in standalone PowerShell first before trying in VS Code.
There have been quite a few old issues related to VS code extensions, we wont be able to fix them. So, recommend using it in standalone PS 7.2 or later versions

**Comment by robertcaretta** [comment]
> This issue has been fixed in the latest nightly builds. Would recommend you to try it out with that.
> 
> Check this issue: #3207
> 
> Having said that, would recommend running it in standalone PowerShell first before trying in VS Code. There have been quite a few old issues related to VS code extensions, we wont be able to fix them. So, recommend using it in standalone PS 7.2 or later versions

This is not a good way to develop. Really need this to work with VS Code. 
Are you saying PnP will not work with VS Code going forward?
