### ISSUE TITLE
[BUG] Set-PnPTerm (by Id) - NullReference setting -CustomProperties

### ISSUE THREAD

**Issue by sparkitect** [pnp/powershell#3338]
### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

### Expected behavior 
Set-PnPTerm can be used to set custom properties on a term (as documented)

### Actual behavior 
When attempting to set a custom property on a term, I get an error message and the property is not set.
![image](https://github.com/pnp/powershell/assets/9206808/38afd6cd-76c6-47c6-b3e2-e2d94fc0985c)

### Steps to reproduce behavior
Connect to Admin Center
Run cmdlet pictured, replacing the guid with the Id of a term in your term store.

### What is the version of the Cmdlet module you are running?
2.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Have fixed the issue, will be available in tomorrow's nightly as well as the next major version whenever it is release.

Thanks for reporting.

**Comment by sparkitect** [comment]
Thanks, @gautamdsheth - I'll give it a go when the nightly drops (if the customer will let me install the nightly).

**Comment by sparkitect** [comment]
I can confirm this is fixed.
Thank you @gautamdsheth!
