### ISSUE TITLE
Unable to update custom metadata properties for List item

### ISSUE THREAD

**Issue by yadavalli1** [pnp/powershell#334]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Set-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting
using below for custom fields failing
$batch = New-PnPBatch
for($i=0;$i -lt 100;$i++)
{
    Set-PnPListItem -List "Demo List" -Identity $i -Values @{"Managedmetadata"="TEST|SITES|internal";"Document owner"="test@contoso.onmicroosft.com";"costcenter"="12345"} -Batch $batch
}
Invoke-PnPBatch -Batch $batch
### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

update the list item

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

set-pnlistitem : field Managedmetadata not present in list.

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows

**Comment by yadavalli1** [comment]
testing with module version 1.2.0. with version 1.3.0 has no batch option.

**Comment by erwinvanhunen** [comment]
Somehow the batch option ended up missing from version 1.3. We reintroduced it in the nightly builds.

I have tested the scenario you described above with release 1.3.14-nightly and have no problems. In case you still have the error message, please double check you're using the -internal name- of the field, not the display name.

**Comment by yadavalli1** [comment]
I've updated module to 1.3.14, was able to run the command, Got new error, asking me to check out file before I can make updates.
"The file "https://test.sharepoint.com/sites/testdl/folder1/folder2/files.xls" is not checked out. you must first check out the document before making changes."

**Comment by veronicageek** [comment]
@yadavalli1 - Then it means that your library has the "_Require documents to be checked out before they can be edited_" option set to **Yes** in the Versioning Settings, as I was able to reproduce your error.

![image](https://user-images.githubusercontent.com/25181757/109398756-b235d780-7936-11eb-99df-e0bc36b919f8.png)

Please double check.

**Comment by yadavalli1** [comment]
thank you @veronicageek and @erwinvanhunen
