### ISSUE TITLE
[BUG]  Get-PnPList: Method "GetListByTitle" does not exist.

### ISSUE THREAD

**Issue by ishaisagi** [pnp/powershell#3345]
### Reporting an Issue or Missing Feature

using latest nightly build, and a TransformationOnPrem in the connection (to sp2013)

The connection connects, but then if I do a get-pnplist (or any command to do with list or list item actions) I get the error:

Get-PnPList: Method "GetListByTitle" does not exist.

### Expected behavior 
expected to get the list/list item and be able to do operations on it

### Actual behavior 
error thrown
Get-PnPList: Method "GetListByTitle" does not exist.

### Steps to reproduce behavior
$cred = Get-Credential
$connection = connect-PnPOnline -Url "http://[sharepoint2013 site]" -TransformationOnPrem -ReturnConnection -Credentials $cred
Get-PnPList "[list name]" -Connection $connection

OR
Get-PnPListItem -List "[listname]" -Id 6000 -Connection $connection

### What is the version of the Cmdlet module you are running?
Manifest   2.2.41     nightly    PnP.PowerShell

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows

**Comment by quophyie** [comment]
I have the the exact same issue i.e. Method "GetListByTitle" does not exist when I pass `TransformationOnPrem` in the connection (to sp2013)

**Comment by quophyie** [comment]
After  some crude investigation, it seems that this problem started appearing in version `2.1.1`  because when I downgraded to version `1.12.0`, it started working. However when I upgrade to version `>=2.1.1`, the error starts appearing. This happens in latest current version `2.2.0` and the nightly builds as well

**Comment by CallumCrowley** [comment]
@ishaisagi the `-TransformationOnPrem` is only supported for transformation cmdlets:

"Connects to on-premises SharePoint 2013, 2016 or 2019 site with the current user's on-premises Windows credential (e.g. domain\user). This option is only supported for being able to transform on-premises classic wiki, webpart, blog and publishing pages into modern pages in a SharePoint Online site. Although other PnP cmdlets might work as well, they're officially not supported for being used in an on-premises context. See http://aka.ms/sharepoint/modernization/pages for more details on page transformation."

[Connect-PnPOnline](https://pnp.github.io/powershell/cmdlets/Connect-PnPOnline.html#example-11)

**Comment by ishaisagi** [comment]
that is a real shame - I have to rely on direct REST api access instead of using pnp.

**Comment by CallumCrowley** [comment]
@ishaisagi you're welcome to use the old version of [PnP PowerShell](https://github.com/pnp/PnP-PowerShell) which supported on-premises SharePoint.
