### ISSUE TITLE
[BUG] Grant-PnPAzureADAppSitePermission intellisense doesn't show all possible values for permissions while Set-PnPAzureADAppSitePermission seems to do that.

### ISSUE THREAD

**Issue by nibubt** [pnp/powershell#3354]
Grant-PnPAzureADAppSitePermission intellisense doesn't show all possible values for permissions while Set-PnPAzureADAppSitePermission seems to do that.

Here's what Grant-PnPAzureADAppSitePermission shows for permissions...
![image](https://github.com/pnp/powershell/assets/9050577/ce485c59-1ee2-478c-9b2c-845c288ace2b)

Here's what Set-PnPAzureADAppSitePermission shows for permissions...
![image](https://github.com/pnp/powershell/assets/9050577/687680c7-5fb8-46de-9e90-4a5e148aad86)

If I manually type it in it does take values like "FullControl", "Manage" etc...

Please fix.

**Comment by veronicageek** [comment]
@nibubt - If the command is working, this is not a PnP PowerShell issue. We don't manage intelliSense in products. Closing.
