### ISSUE TITLE
[BUG] Get-PnPTenantSite doesn't return SensitivityLables when returning all sites

### ISSUE THREAD

**Issue by wadehgsk** [pnp/powershell#3356]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Get-PnPTenantSite doesn't not return SensitivityLabel values when querying all sites. It does return SensitivityLabel values when querying individual sites with -Detailed switch. This impacts reporting as we cannot determine which sites have labels applied.

### Expected behavior 
Get-PnPTenantSite -Detailed -IncludeOneDriveSites returns SensitivityLabel values for all sites with label applied

### Actual behavior 
Get-PnPTenantSite -Detailed -IncludeOneDriveSites returns all sites, however SensitivityLabel is not populated for all objects returned.
However Get-PnPTenantSite -Identity "https://siteurl" -Detailed does return site with SensitivityLabel.

### Steps to reproduce behavior
1. Create a SharePoint site or Teams "https://siteurl"
2. Apply a Purview SensitivityLabel via Teams/SharePoint UI or via code
3. Verify the SensitivityLabel is visible in Admin console
4. Connect-PnPOnline with account or app/certificate
5. Run $sites = Get-PnPTenantSite -Detailed -IncludeOneDriveSites
6. Inspect all of the sites returned. None of the sites have SensitivityLabel populated.
7. Run $site = Get-PnPTenantSite -Identity "https://siteurl" -Detailed
8. Verify the $site does have GUID value for SensitivityLabel

### What is the version of the Cmdlet module you are running?
    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   2.2.0                 PnP.PowerShell                      Desk      {Add-PnPAdaptiveScopeProperty, Add-PnPPropertyBagValue, Add-Pn…

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows Server 2019 Datacenter
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by CallumCrowley** [comment]
It seems this is a limitation of SharePoint CSOM, on which this cmdlet relies upon.

[Tenant.GetSitePropertiesByUrl](https://learn.microsoft.com/en-us/previous-versions/office/sharepoint-csom/dn159172(v=office.15)) has the includeDetail parameter, where as [Tenant.GetSitePropertiesFromSharePointByFilters](https://learn.microsoft.com/en-us/previous-versions/office/sharepoint-csom/mt779505(v=office.15)) does not.

You can request this enhancement via the [Microsoft Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/06735c62-321c-ec11-b6e7-0022481f8472).

**Comment by wadehgsk** [comment]
powershell/src/Commands/Admin/GetTenantSite.cs line 74 constructs the following param which is passed to Tenant.GetSitePropertiesFromSharePointByFilters(filter) on line 98.

SPOSitePropertiesEnumerableFilter filter = new SPOSitePropertiesEnumerableFilter()
                {
                    IncludePersonalSite = IncludeOneDriveSites.IsPresent ? PersonalSiteFilter.Include : PersonalSiteFilter.UseServerDefault,
                    **IncludeDetail = Detailed,**
                    Template = Template,
                    Filter = Filter,
                };
...
                    sitesList = Tenant.GetSitePropertiesFromSharePointByFilters(filter);

Are you saying the Detailed parameter in the filter is ignored?

**Comment by CallumCrowley** [comment]
You're right, I had missed that line. It seems like the call is constructed correctly. I suppose the only way is to test this CSOM call out by itself to determine if SharePoint really is returning additional details, that will determine if this is a problem with PnP.

**Comment by gautamdsheth** [comment]
@wadehgsk - seems like an issue with CSOM SDK method itself not returning the labels. 
Would suggest you to open a ticket with Microsoft if it seems like a major blocker for you.

We can't fix it from our side.

**Comment by wadehgsk** [comment]
I'm not sure what you mean that you can't fix it. The problem is your API is not fulfilling its contract. You are returning objects with bogus values (NULL instead of the correct value). This is a bug with PnP. It shouldn't matter to me as a developer what your internal implementation is. When you ship it, it should work and provide consistent answers. It currently does not. That should be a problem for you and your product.

But yes, this is a major blocker in that I cannot trust your data and I have to code around it. It also implies that your testing is not up to snuff if you didn't find that your API provides inconsistent answers.

**Comment by CallumCrowley** [comment]
@wadehgsk the only fix PnP could do here is to remove the concept of that value being returned at all from this cmdlet. PnP.PowerShell provides cmdlets for interacting with SharePoint Online, if SPO doesn't return the value then there is nothing that can be done by the PnP team. Only Microsoft can makes changes to the SharePoint Online API/CSOM that PnP.PowerShell relies upon. You will need to open a ticket with Microsoft.

**Comment by gautamdsheth** [comment]
@wadehgsk - we won’t fix it because it can’t be fixed from our end. 

This is a fully open source community project not supported by Microsoft. Volunteers spend their time and resources in maintaining it.

We only consume Microsoft SDKs and APIs. The problem here lies with the API that is used by the Get-PnPTenantSite cmdlet. It can only be fixed by Microsoft which provides this API.
So , you need to open a support ticket with them and ask them to fix it.

**Comment by wadehgsk** [comment]
I understand what you're saying. I would think your team (whether volunteer or not) would have more pull fixing this with Microsoft than I would. I also think you have some skin in the game as it affects the quality of your product. I will open a ticket with Microsoft and see how far I get.

Note that I see a similar problem with ConditionalAccessPolicy property, which instead of NULL returns a constant value for all sites. I will file a separate bug report for that for completeness. My guess it is the same underlying issue.
