### ISSUE TITLE
[BUG] - Set-SPOTenant -SiteOwnerManageLegacyServicePrincipalEnable -- Command Doesn't Work Setting to False

### ISSUE THREAD

**Issue by robertcaretta** [pnp/powershell#3359]
### Reporting an Issue or Missing Feature
This command does not work.
Set-PnPTenant -SiteOwnerManageLegacyServicePrincipalEnabled $false

### Expected behavior 
This should set the tenant setting to False.
Set-PnPTenant -SiteOwnerManageLegacyServicePrincipalEnabled $false

### Actual behavior 
When I run this set of commands it does not set the tenant setting to False. It always remains set to True.  
No errors are thrown.

### Steps to reproduce behavior
Import-Module -Name PnP.PowerShell -RequiredVersion 2.2.54
Connect-PnPOnline -Url 'https://DOMAIN-admin.sharepoint.com' -Interactive
Get-PnPContext
Set-PnPTenant -SiteOwnerManageLegacyServicePrincipalEnabled $false
Get-PnPTenant | Select-Object SiteOwnerManageLegacyServicePrincipalEnabled

![image](https://github.com/pnp/powershell/assets/1613085/6296373f-e497-4e51-8c15-113576b3c1f9)

### What is the version of the Cmdlet module you are running?
Latest nightly build of 2.2.54 using PowerShell 7.3.6 in VS Code. Everything is updated.

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by robertcaretta** [comment]
I also tried with just the main domain URL, not admin. Same results, it does not apply.  Always stays set to True.
![image](https://github.com/pnp/powershell/assets/1613085/bae88dc5-3503-4f7b-b6a6-a91bbc442752)

**Comment by joelbibby** [comment]
Can confirm the same using SharePoint Online Management Shell, as per the Message Center ID: MC660075

Connect-SPOService -Url 'https://DOMAIN-admin.sharepoint.com
Get-SPOTenant | Select-Object SiteOwnerManageLegacyServicePrincipalEnabled
Set-SPOTenant -SiteOwnerManageLegacyServicePrincipalEnabled $false

Output of **Get-SPOTenant | Select-Object SiteOwnerManageLegacyServicePrincipalEnabled** remains as 'True' after setting to false, as above.

Using PowerShell 7 and SPO Management Shell ver. 16.0.23710.12000

**Comment by veronicageek** [comment]
If the same happens with the SPO Management Shell, then we'll need to wait for Microsoft to fix it (likely CSOM if this is what we use in the background). Then PnP PowerShell will consume it.

**Comment by robertcaretta** [comment]
Problem isn't solved though.

**Comment by joelbibby** [comment]
We looked at it today. If you read the Message Center info carefully, it does actually state that it will not change even if you set it to false, even if you set to true.

**Comment by robertcaretta** [comment]
Yeah they added that special note 2 days ago. Thank you.

**Comment by Budhead88** [comment]
It appears that Microsoft has resolved this issue in the latest scripts for SharePoint Online. With the script below, it now works for me.

-----------------------------------------------------------------------------
Install-Module -Name Microsoft.Online.SharePoint.PowerShell -Force

# some variables
$adminUPN=""
$orgName=""
$userCredential = Get-Credential -UserName $adminUPN -Message "Type the password."

# login to the SharePoint Service
Connect-SPOService -Url https://$orgName-admin.sharepoint.com -Credential $userCredential

# get App Authentication
Get-SPOTenant | Select-Object SiteOwnerManageLegacyServicePrincipalEnabled

# Setting App Authentication to true
Set-SPOTenant -SiteOwnerManageLegacyServicePrincipalEnabled $true

**Comment by andersnm** [comment]
The previous comment is the best explanation on the internet how enable this thing so I can renew the expired credentials for a task that uploads some build artifacts to Sharepoint (45 minutes to upload 1 gigabyte no less!). Altho ran into some issues during `Connect-SPOService`.

First attempt:
```ps
$> Connect-SPOService -Url https://$orgName-admin.sharepoint.com -Credential $userCredential

Connect-SPOService : The remote server returned an error: (503) Server Unavailable.
```

Second attempt:
```
$> Connect-SPOService -Url https://$orgName-admin.sharepoint.com -Credential $userCredential

Connect-SPOService : Identity Client Runtime Library (IDCRL) did not get a response from the Login server.
```

Out of desperation tried to omit the `-Credential` part, it asked for my credentials and it worked:
```
Connect-SPOService -Url https://$orgName-admin.sharepoint.com
```

Surprisingly, the `Set-SPOTenant` line worked fine afterwards so could finally go back to renewing the credentials, updating the task and get back to work.
