### ISSUE TITLE
[BUG] Get-PnPFolderItem -Recurse doesn't show files in folders

### ISSUE THREAD

**Issue by ToddKlindt** [pnp/powershell#336]
### Reporting an Issue or Missing Feature
When using the -Recurse switch with Get-PnPFolderItem files in folders are not included in the output.

### Expected behavior 
Files in folders are not included in the output when the -Recurse switch is used.

### Actual behavior 
Here are two examples:
![image](https://user-images.githubusercontent.com/2659747/109069040-4ba28680-76b6-11eb-91d1-7c746bfc5ca6.png)
The folders do indeed contain the number of files that Get-PnPFolderItem says they do, but it doesn't include them in its output.

Here Get-PnPFolderItem shows the files in the root of SitePages but doesn't show the News-post.aspx file in the Templates folder, even though it shows there's one there. 
![image](https://user-images.githubusercontent.com/2659747/109069666-282c0b80-76b7-11eb-89dd-03fb2efb944a.png)

### Steps to reproduce behavior
Run Get-PnPFolderItem on a doclib with a folder containing files. 

### What is the version of the Cmdlet module you are running?
1.3.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
strange... I have no problems with that. When I execute the exact same cmdlet on my sitepages folder the template files get included...

![image](https://user-images.githubusercontent.com/7666381/109177664-562d5080-7788-11eb-90b9-bdfc90b15450.png)

![image](https://user-images.githubusercontent.com/7666381/109177795-7c52f080-7788-11eb-976a-3799b92fe7c0.png)

**Comment by ToddKlindt** [comment]
I tried the 1.3.14 nightly and I have the same issue. 
![image](https://user-images.githubusercontent.com/2659747/109185615-cb336280-7755-11eb-9a58-2873050e6681.png)
Any ideas how I can troubleshoot this?

**Comment by erwinvanhunen** [comment]
Could you try this?

```powershell
$folder = Get-PnPFolder -Url "SitePages" -Includes Folders
$folder.Folders
```

You should see a list of folders. If so, there should be a "Templates" folder. If that's the case:

```powershell
$folder = Get-PnPFolder -Url "SitePages/Templates" -Includes Folders, Files
$folder.Files
```

This should return the template files. If it doesn't the only thing I can come up with is that it is an access right issue? Otherwise I really have no clue why it works here and not for you...

**Comment by ToddKlindt** [comment]
I tried your suggestions. Here's what I got: 
![image](https://user-images.githubusercontent.com/2659747/109212107-be723700-7774-11eb-94e1-39102e4fd7de.png)
It doesn't look like a permissions issue since I can see the files if I specify the CAS folder directly. If I pass `-ItemType All` I get the same result.

**Comment by veronicageek** [comment]
@ToddKlindt - I can reproduce your issue _but_ only on a **MSFT Demo tenant** like you have here (also on the right on my screenshot). When I try on _my perso_ tenant, I don't have this problem.

![image](https://user-images.githubusercontent.com/25181757/109394714-4f394600-7920-11eb-8cdb-e3aecbfec3da.png)


Cc @erwinvanhunen

**Comment by erwinvanhunen** [comment]
That's fascinating... I wonder if there is something with how things have been provisioned to that tenant.

**Comment by veronicageek** [comment]
I had inconstant issues in the past with a MSFT Demo tenant when syncing objects (with AADConnect) or other tasks, that's why I wanted to test both. Not sure if MSFT is "blocking" a few things in the background 🤷🏻‍♀️

**Comment by ToddKlindt** [comment]
That was it, @veronicageek . Good catch. The problem doesn't seem to be tenant wide, but I can reproduce it in any of the sites that came with the tenant. If I create a new site in the tenant, Team or Comm, it works fine.
