### ISSUE TITLE
[BUG] New-PnPGroup does not accept -OnlyAllowMembersViewMembership switch parameter

### ISSUE THREAD

**Issue by tshimizu-ykgw** [pnp/powershell#3361]
### Reporting an Issue or Missing Feature
When I specify -OnlyAllowMembersViewMembership switch to New-PnPGroup, it returns an error.
-> A parameter cannot be found that matches parameter name 'OnlyAllowMembersViewMembership'.
And command line auto completion by TAB does not work for "New-PnPGroup -only".

### Expected behavior 
-OnlyAllowMembersViewMembership should be accepted.

### Actual behavior 
As written in Missing Feature above.
Another switch '-DisallowMembersViewMembership' is accepted.

### Steps to reproduce behavior
PS C:\> New-PnPGroup -only[TAB]

### What is the version of the Cmdlet module you are running?
This happens both on PnP.PowerShell versions 2.1.1 and 2.2.0.
The parameter used work on version 1.x.x.

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by a1mery** [comment]
It says here that the parameter was removed with the 2.0 version: [MIGRATE-1.0-to-2.0.md](https://github.com/pnp/powershell/blob/master/MIGRATE-1.0-to-2.0.md) since it is now done by default.
So I guess this is not a cmdlet issue but a documentation issue.

**Comment by veronicageek** [comment]
Thanks, I've updated the documentation.

**Comment by tshimizu-ykgw** [comment]
Understood.
Thank you.
