### ISSUE TITLE
[BUG] Request-PnPPersonalSite: Attempted to perform an unauthorized operation.

### ISSUE THREAD

**Issue by chscott** [pnp/powershell#3362]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature

Running `Request-PnPPersonalSite -UserEmails $upn` fails with `Request-PnPPersonalSite: Attempted to perform an unauthorized operation.`

I have followed the documentation at https://pnp.github.io/powershell/cmdlets/Request-PnPPersonalSite.html. In my scenario, I am using an interactive login, but I believe the documentation is not correct in that regard. It says:

_If you want to run this cmdlet using an interactive login, you must connect using:_
`Connect-PnPOnline -Url https://tenant-admin.sharepoint.com -UseWebLogin`

Attempting this brings up an IE browser that doesn't load anything and a notice that I should be using `-Interactive` instead.

`WARNING: Consider using -Interactive instead, which provides better functionality. See the documentation at https://pnp.github.io/powershell/cmdlets/Connect-PnPOnline.html#interactive-login-for-multi-factor-authentication`

I am able to log in by using `-Interactive`, but that's when I get the error. I have already run `Register-PnPManagementShellAccess`, and the account I am using to log in is a Global Administrator in the tenant. For grins, I also added the SharePoint Administrator role, but that had no effect.

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

It should work as documented.

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

As described above.

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

As described above.

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

2.2.55

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
@chscott - It requires `UseWebLogin` when using Interactive login. If it doesn't work in your case would suggest trying it in a different machine or VM.

We are using pure CSOM methods.

If it is a major blocker for you, please reach out to Microsoft support and mention that there is an issue with CSOM method

https://github.com/pnp/powershell/blob/dev/src/Commands/Admin/RequestPersonalSite.cs

This is not something we will be fix since you are getting an unauthorized error message.

**Comment by hhooiveld** [comment]
Why is it not possible to use Connect-PnPOnline -Interactive with Request-PnPPersonalSite? Doesn't make sense to use a legacy authentication mechanism?
