### ISSUE TITLE
[BUG] `-DisableListSync` parameter of `Set-PnPTenant` cmdlet not working 

### ISSUE THREAD

**Issue by ganesh-sanap** [pnp/powershell#3371]
### Reporting an Issue or Missing Feature
Bug

### Expected behavior 

I think this parameter was the experimental feature and Microsoft removed this tenant property/fields recently. Can anyone from the repository maintainers confirm this, please?

If confirmed, I would like to work on fixing this issue by removing the `-DisableListSync` parameter from `Set-PnPTenant` cmdlet, Thanks!

### Actual behavior 

`-DisableListSync` parameter of `Set-PnPTenant` cmdlet is not working and showing below error:

![image](https://github.com/pnp/powershell/assets/25476310/22d8dd0e-73a8-4293-a76e-d62e33a29d0e)

### Steps to reproduce behavior

- Connect to your SharePoint tenant using PnP PowerShell
- Run below command:

```
Set-PnPTenant -DisableListSync $false
```

### What is the version of the Cmdlet module you are running?

Current Nightly

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows

**Comment by KoenZomers** [comment]
@ganesh-sanap, correct and confirmed. It has been removed from the code.
