### ISSUE TITLE
[BUG] "Get-PnPTenantSite: The operation has timed out." when using "-IncludeOneDriveSites"

### ISSUE THREAD

**Issue by PowerBugi** [pnp/powershell#3374]
### Reporting an Issue
**Can't get all my sites with Get-PnPTenantSite anymore when using "-IncludeOneDriveSites" param.** 

*no updates or major changes in my tenant to be noted, it had been working for months without a problem.*

### Expected behavior 

It's supposed to give me all my sites (Sharepoint/OneDrive).

### Actual behavior 

Instead of giving all the sites, it loads for 5 minutes and then timeouts (without any partial result).

It only give me a single line error : 

![2023-08-29 02_15_33-Window](https://github.com/pnp/powershell/assets/62485307/0a4c8336-552c-4afb-b9b5-b930e14723fc)

if i do `$Error[0] | select *` it give me this : 

![2023-08-29 02_16_41-Window](https://github.com/pnp/powershell/assets/62485307/59a4bade-c639-47df-8bae-1672438f3af9)

### Steps to reproduce behavior

 1. Connect to PnP, for example using this : `Connect-PnPOnline -Url "tenantName-admin.sharepoint.com" -Interactive`
 2. Try to run this : `$SITES = Get-PnPTenantSite -IncludeOneDriveSites`

### What is the version of the Cmdlet module you are running?

- PowerShell : **7.3.6**
- PnP.PowerShell :  **2.2.0**

### Which operating system/environment are you running PnP PowerShell on?

- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

### Note

I also tried on another computer on another network, it's the same.

For information, **I have more than 50k SharePoint/OneDrive sites...** So maybe that's a relevant point.
I don't know if there's any limitation about throttling or max capacity (it's not in the doc of the cmdlet btw), and i can't try to remove some sites to test if it's because the result is too HUGE or not.

**Comment by PowerBugi** [comment]
work again since this morning...
Maybe it was a temporary issue on SharePoint Online ?

**Comment by veronicageek** [comment]
Thanks for feeding back. Will now close.
