### ISSUE TITLE
[BUG] Broken build since 2023-08-27

### ISSUE THREAD

**Issue by jackpoz** [pnp/powershell#3376]
### Reporting an Issue or Missing Feature
On the 2023-08-27 CSOM version 16.1.24009.12000 was released, with changes to Microsoft.Online.SharePoint.TenantAdministration.Tenant . This is now causing build errors in PnP.PowerShell.Commands.Admin.SetTenant :
![image](https://github.com/pnp/powershell/assets/1153754/6d547d49-893a-4baa-be27-b7c7410f0965)

Link to new CSOM: https://www.nuget.org/packages/Microsoft.SharePointOnline.CSOM/16.1.24009.12000

You can see the build errors in the nightly GitHub Action publishing PnP PowerShell to PowerShell Gallery at https://github.com/pnp/powershell/actions/workflows/nightlyrelease.yml

### Expected behavior 
No build errors.

### Actual behavior 
Build errors.

### Steps to reproduce behavior
Build PnP PowerShell using Build-Debug.ps1 or Visual Studio.

### What is the version of the Cmdlet module you are running?
https://github.com/pnp/powershell/commit/9915eee67b0b9be1d731beb46bd5b82a6903926a

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by KoenZomers** [comment]
Well noticed @jackpoz . Thanks for flagging it. It has now been fixed.
