### ISSUE TITLE
[BUG] In Azure Functions, connection contexts bleed through in scripts running at the same time

### ISSUE THREAD

**Issue by martinlingstuyl** [pnp/powershell#3383]
Hi @KoenZomers, @gautamdsheth ,

Just yesterday I ran into an interesting phenomenon that has not occurred to me before in many deployed functions:

If I've got two functions running in the same Azure Function, and I connect using Connect-PnPOnline in the one, I can access the context in the other running function.

This seems very odd to me, as you'd think it's separate processes running, just like you would have two posh terminals open on your PC: the auth context should not bleed through. 

But it appears to be so, checkout this example:

![image](https://github.com/pnp/powershell/assets/5267487/dc5e5d7b-287a-4ed0-82bd-3ed5bdfb820f)

This is two timers running at the same time. As you can see I can get the web title in the function, while I only connected in the other.

Have you noticed this before?
I'm not sure its really a PnP posh bug, its probably related to the infrastructure of Azure Functions. But I'm not sure who to ask here. Maybe you have ideas.

Let me know what you think!

**Comment by KoenZomers** [comment]
My first reaction was also hmm weird. After consulting an Azure colleague I've been informed this is by design. You can read more about this here: https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell?tabs=portal#concurrency

**Comment by martinlingstuyl** [comment]
Interesting @KoenZomers! Thanks for the reference!

**Comment by martinlingstuyl** [comment]
Let's close it then. I'm going to look into this concurrency thing. I do think it's not what you'd expect. But well!
