### ISSUE TITLE
[FEATURE] Add-PnPListFoldersToSiteTemplate does not work with .pnp template files, only .xml template files

### ISSUE THREAD

**Issue by zllzn** [pnp/powershell#339]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
When using the cmdlet Add-PnPListFoldersToSiteTemplate, it should add the corresponding XML in the xml template file in the .pnp zip file.

### Actual behavior 
The cmdlet is not taken into account. The template embedded in the .pnp file is not updated. When using this cmdlet on a .xml template file directly, it works.

### Steps to reproduce behavior
Create folder in the Document Library.
Create a template with : Get-PnPSiteTemplate -Out "template.pnp"
Add the folders with : Add-PnPListFoldersToSiteTemplate -Path "template.pnp" -List "Shared Documents" -Recursive
Extract the .pnp file, open the xml file in the "Files" folder.
--> Does not work, no folder is present

Create folder in the Document Library.
Create a template with : Get-PnPSiteTemplate -Out "template.xml"
Add the folders with : Add-PnPListFoldersToSiteTemplate -Path "template.xml" -List "Shared Documents" -Recursive
Open the template.xml file
--> Works, folders are present

### What is the version of the Cmdlet module you are running?
1.3.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by zllzn** [comment]
Not to be picky, but this should really be considered as a bug. It is even documented in the [documentation](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnplistfolderstositetemplate?view=sharepoint-ps), so it should work as-is.

**Comment by erwinvanhunen** [comment]
When you executed the cmdlet on a PnP file, did you receive an error? As I did. It turned out it tried to write to the wrong location, and it was not able to update the pnp file. It took the root folder name and assumed there was a pnp file at that location, e.g. if you're in `c:\users\test\` and you had a file called `demo.pnp` it tried to update the file `c:\users\test.pnp`. 

After I fixed that issue I successfully ended up with an updated template with the folders listed for the lists.

**Comment by erwinvanhunen** [comment]
I merged a fix. Please test version 1.3.23-nightly which will be available tomorrow.

**Comment by zllzn** [comment]
I did not receive any error, and $? returns that everything was fine. I also tried to use Set-PnPTraceLog but the generated file was empty when creating the template and adding folders, so I had no clue that didn't worked.
Thanks for the fix ! I'll be sure to test it tomorrow !

**Comment by zllzn** [comment]
@erwin

> I merged a fix. Please test version 1.3.23-nightly which will be available tomorrow.

I have tested it with the nightly build and I confirm that it works.
We can see the folders when unzipping the .pnp file, and also tried to apply the template, everything was correct.
Thanks again for having it fixed quickly !
