### ISSUE TITLE
[BUG] Microsoft.Graph and PnP.PowerShell conflict (Could not load type 'Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider') #2285

### ISSUE THREAD

**Issue by duschu** [pnp/powershell#3395]
### Notice
I have also reported this issue in the Microsoft.Graph repository (https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2285), but I would be really happy if you could also investigate the error from this side. Thank you.

### Reporting an Issue or Missing Feature
When using the [Microsoft.Graph](https://github.com/microsoftgraph/msgraph-sdk-powershell/) and PnP.PowerShell module in the same script, the `Get-MgGroup -All` command fails with the following exception:
`Get-MgGroup_List: Could not load type 'Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider' from assembly 'Microsoft.Graph.Core, Version=1.25.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.`

The error occurs if the script is executed locally as well as an Azure Automation runbook.

We locally use PowerShell v7.3.6 and in Azure Automation we also use the latest PS7.2 runbooks.
The latest Microsoft.Graph.* module version 2.4.0 is used as well as a recent PnP.PowerShell 2.2.59-nightly.

According to the blog post https://mortenknudsen.net/?p=2631, the old Microsoft.Graph.Core version 1.25.1.0 seems to originate from the module dependencies of PnP.PowerShell.

### Expected behavior 
Get-MgGroup should return the group objects of the tenants.

### Actual behavior 
````
DEBUG: [CmdletBeginProcessing]: - Get-MgGroup begin processing with parameterSet 'List'.
DEBUG: [Authentication]: - AuthType: 'AppOnly', TokenCredentialType: 'ClientCertificate', ContextScope: 'Process', AppName: 'dsc-group-lifecycle'.
DEBUG: [Authentication]: - Scopes: [AccessReview.ReadWrite.All, Group.ReadWrite.All, User.Read.All, Mail.Send].
DEBUG: [CmdletException]: Received exception with message 'TypeLoadException - Could not load type 'Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider' from assembly 'Microsoft.Graph.Core, Version=1.25.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. :    at Microsoft.Graph.PowerShell.Authentication.Helpers.HttpHelpers.GetGraphHttpClient()
   at Microsoft.Graph.PowerShell.Module.BeforeCreatePipeline(InvocationInfo invocationInfo, HttpPipeline& pipeline)
   at Microsoft.Graph.PowerShell.Module.CreatePipeline(InvocationInfo invocationInfo, String parameterSetName)
   at Microsoft.Graph.PowerShell.Cmdlets.GetMgGroup_List.ProcessRecordAsync()'
Get-MgGroup_List: Could not load type 'Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider' from assembly 'Microsoft.Graph.Core, Version=1.25.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
DEBUG: [CmdletEndProcessing]: - Get-MgGroup end processing.
````

### Steps to reproduce behavior
Minimal code example to reproduce the issue:
````
Import-Module Microsoft.Graph.Authentication
Import-Module Microsoft.Graph.Groups
Import-Module PnP.PowerShell

# Connect to Microsoft Graph and SharePoint via client id + certificate
Connect-MgGraph -TenantId $tenantId -ClientId $clientId -CertificateThumbprint $certificateThumbprint
Connect-PnPOnline -Url $url -Tenant $tenant -ClientId $clientId -Thumbprint $certificateThumbprint

# Get groups (this is the command that will fail)
$groups = Get-MgGroup -All
````

### What is the version of the Cmdlet module you are running?
The following module versions are installed exactly like that both locally under Windows and in the Azure automation account:
| Version | Name |                         
|----|----|
| 2.2.59-nightly |       PnP.PowerShell |
| 2.4.0      | Microsoft.Graph.Authentication |
| 2.4.0       | Microsoft.Graph.Groups |
| 2.4.0        | Microsoft.Graph.User |

The nighly version of PnP.PowerShell has been installed by intention since there were known issues regarding module conflicts with Az.* and others in the last weeks, which should have been fixed in latest nightly versions.

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [x] Other : Azure Automation runbooks

**Comment by duschu** [comment]
Is it possible that you can upgrade the Microsoft.Graph.Core.dll dependency in your module to v3.x according to the comment https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2285#issuecomment-1707469757 by @peombwa? Thank you for any feedback and further help.

**Comment by taraldjoh** [comment]
> Is it possible that you can upgrade the Microsoft.Graph.Core.dll dependency in your module to v3.x according to the comment [microsoftgraph/msgraph-sdk-powershell#2285 (comment)](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2285#issuecomment-1707469757) by @peombwa? Thank you for any feedback and further help.

Bumping this one as i'm experiencing issues because of this as well. 
Hope this can be resolved fairly quickly. Help & feedback would be greatly appreciated!

**Comment by veronicageek** [comment]
@duschu - We have no control over the MSGraph module (or Az module). They may be updating / upgrading their dependencies later on, and we can only suggest running the PnP cmdlets in a different thread. If the PnP cmdlets work on their own, there's unfortunately nothing we can do.

**Comment by jwiersem** [comment]
Errr, apparently this method exists: https://pnp.github.io/powershell/cmdlets/Invoke-PnPGraphMethod.html :D

**Comment by martinb3sharp** [comment]
I worked around this issue by forcing PowerShell to load specific versions of the modules. I hit the issue with an Azure Function and put this in the requirements.psd1:

```
@{
    'Microsoft.Graph.Authentication' = '2.2.0'
    'Microsoft.Graph.Identity.Governance' = '2.2.0'
    'Microsoft.Graph.Users' = '2.2.0'
    'PNP.PowerShell' = '2.2.0'
    'Az.Accounts'  = '1.8.0'
    'Az.Resources' = '2.0.1'
    'Az.KeyVault' = '4.3.1'
}
```
You will be able to do a similar thing for the Azure Automation account, by making sure the module versions installed in the account are the ones that do not conflict.

**Comment by TobiasAT** [comment]
@veronicageek This bug is clearly not solved, and the cause is not a MSGraph module. As mentioned by duschu the outdated Microsoft.Graph.Core.dll from PnP.PowerShell is the cause. Please reopen the issue. 

![image](https://github.com/pnp/powershell/assets/7470044/90cb5385-12fb-41bf-b5fc-a6177abeda50)

A workaround is to delete the outdated DLL from the PnP.PowerShell location (until the next PnP module update). Then the Graph request is working. Graph loads the correct version.

![image](https://github.com/pnp/powershell/assets/7470044/6b7a2a97-1fb0-4fc7-b51c-d75c17abcdd6)

**Comment by danmyhre** [comment]
This is from a fresh install...it is using a version from 2021

![image](https://github.com/pnp/powershell/assets/17068259/3b5b417b-c7c4-4e20-b8e2-e06f615a3888)

**Comment by YuriySamorodov** [comment]
Hey, @danmyhre . I would probably open another issue for this...

**Comment by bnalley** [comment]
I have this issue as well.

**Comment by nicole-ge** [comment]
Hi @gautamdsheth 

Can we reopen this issue? Because it is still not working and pnp loading the wrong msgraph core dll

**Comment by nicole-ge** [comment]
> I have this issue as well.  Manually deleting Microsoft.Graph.Core from PnP module install directory fixed my Graph issues.  Not a great workaround but works.
> 

How I can do this in a runbook?

**Comment by DavidHorsky** [comment]
> > I have this issue as well.  Manually deleting Microsoft.Graph.Core from PnP module install directory fixed my Graph issues.  Not a great workaround but works.
> 
> How I can do this in a runbook?

I have a workaround for the Azure Automation Runbook.
**Use a Graph cmdlet before connecting to PnP. Something basic like Get-MgGroup works just fine. All other cmdlets work after that, even after connecting to PnP.**
Don't know if the graph action has to succeed, haven't tested that. But for my case it works.

**Comment by cythrault** [comment]
I'm having the same issues with scripts that require to use Graph and PnP. Deleting Microsoft.Graph.Core.dll from the PnP module works for me. However, I'm concerned that the PnP module might encounter unforeseen problems. It would be very nice to resolve this long standing issue. Graph has been updating their module quite regularly. IMHO, keeping such a old version of their DLL in the PnP module will just become increasingly problematic.

**Comment by baseballfrk8998** [comment]
So this issue got marked as closed without ever actually being resolved? I'm still having this issue in September of '24 with the latest PnP modules in an Azure Automation Runbook.

**Comment by sabey2000** [comment]
This is still an issue causing a lot of nightmare for us with Azure Function CI/CD pipeline and the maintenance of the requirement.ps1 file.  It still an issue with 

    'Microsoft.Graph' = '2.23.0'
    'PnP.PowerShell' = '2.10.0'

@veronicageek , is it possible to reopen and investigation this issue?

**Comment by sabey2000** [comment]
Ok, I better understand the problem now that I'm able to simulate the situation on my own machine.  

First, I have the problem with I'm using a lot of powershell script in Azure function web app so they all share the same assembly context so conflit occur if script 1 use PnP-Online and than script 2 use the Connect-MgGraph.

Nothing I can do, it's by design and limitation, hard to resolve : https://learn.microsoft.com/en-us/powershell/scripting/dev-cross-plat/resolving-dependency-conflicts?view=powershell-7.4

So the trick, is like it was written in a previous post, you have to Connect-MgGraph before doing a PnP-Online even if the script does not required access to graph.  This is a workaround but the real solution is to resolve the dependency requirement.

**Comment by veronicageek** [comment]
@duschu - There's an open issue #3637 with a longer thread and possible workaround(s). Every module (MSFT, PnP, or else) being compatible with each other is an endless battle and would be more complex to solve (if at all possible) than people think.

**Comment by Borgquite** [comment]
If you are still experiencing this issue, it may be resolved in the latest nightly builds
https://github.com/pnp/powershell/issues/3637
