### ISSUE TITLE
[BUG] Get-PnPTenantSite doesn't return correct ConditionalAccessPolicy values when querying all sites

### ISSUE THREAD

**Issue by wadehgsk** [pnp/powershell#3398]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Get-PnPTenantSite doesn't not return the correct values for ConditionalAccessPolicy when querying all sites. Instead of the correct ConditionalAccessPolicy value, it returns AllowFullAccess on our tenant. This happens to be the tenant default, which may be a coincidence however it is incorrect (most sites actually have AllowLimitedAccess set). It does return correct ConditionalAccessPolicy values when querying individual sites. This impacts reporting as we cannot determine policy settings on the sites correctly..

### Expected behavior 
Get-PnPTenantSite -Detailed -IncludeOneDriveSites returns actual ConditionalAccessPolicy values for all sites

### Actual behavior 
Get-PnPTenantSite -Detailed -IncludeOneDriveSites returns all sites, however ConditionalAccessPolicy is the same value for all sites returned.
However Get-PnPTenantSite -Identity "https://siteurl" -Detailed does return site with the correct ConditionalAccessPolicy values.

### Steps to reproduce behavior
Create a SharePoint site or Teams "https://siteurl"
Modify the ConditionalAccessPolicy setting to AllowLimitedAccess via code
Verify the SensitivityLabel is by querying site properties via code
Connect-PnPOnline with account or app/certificate
Run $sites = Get-PnPTenantSite -Detailed -IncludeOneDriveSites
Inspect all of the sites returned. All of the sites report the same value for ConditionalAccessPolicy including the new site modified above.
Run $site = Get-PnPTenantSite -Identity "https://siteurl" -Detailed
Verify the $site has the ConditionalAccessPolicy value as modified above

### What is the version of the Cmdlet module you are running?
2.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows Server 2019
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
hi @wadehgsk , it is related to the same issue you raised earlier, #3356 .

Only Microsoft can fix it. Nothing we can do here.
