### ISSUE TITLE
[BUG] Add an App through tenant template fails when using certificate authentication, Add-PnPApp works

### ISSUE THREAD

**Issue by YannickRe** [pnp/powershell#34]
### Notice
I assume this is in essence a PnP Framework issue, but I do not grasp the full complexity of authentication in PnP Powershell. If this needs to be moved, I'll gladly do it.
I haven't written C# code directly against PnP Framework to try if it also fails over there.

### Reporting an Issue or Missing Feature
When I login using a certificate, app-only, adding an .sppkg to the tenant app catalog fails when using Apply-PnPTenantTemplate. Using the same logged in session, I can invoke Add-PnPApp without issue.

### Expected behavior 
I expect this to work:
```
Connect-PnPOnline -Url https://{tenant}-admin.sharepoint.com -ClientId {appId} -Tenant {tenantId} -CertificatePath "{path}\{to}\{certificate}.pfx"
Invoke-PnPTenantTemplate -Path "{path}\{to}\{template}.pnp"
```
My template contains
```
  <pnp:Tenant>
    <pnp:AppCatalog>
      <pnp:Package Action="UploadAndPublish" Overwrite="true" Src=".\{package}.sppkg" SkipFeatureDeployment="true" />
    </pnp:AppCatalog>
  </pnp:Tenant>
```

### Actual behavior 
Invoke-PnPTenantTemplate returns with
```
Invoke-PnPTenantTemplate: Your template contains artifacts that require an access token. Please provide consent to the PnP Management Shell application first by executing: Register-PnPManagementShellAccess
```
It should work since `Add-PnPApp` works and I used the same appId and Certificate through CLI for M365 and that works too.
Also, it does not really make sense to suggest Register-PnPManagementShellAccess as I am using my own appId.

### Steps to reproduce behavior

- Create a custom Azure AD app registration, add correct permissions and certificate
- Login with Certificate authentication
- Execute Invoke-PnPTenantTemplate

### What is the version of the Cmdlet module you are running?
0.2.6-nightly

**Comment by erwinvanhunen** [comment]
Until now we always used the PnP Management Shell application id behind the scenes to authenticate towards SharePoint in the context of a tenant template as that makes sure that the correct required permissions scopes are present. The Invoke-PnPTenantTemplate is currently not aware of the fact that a custom clientid has been provided and hence the error message. We will have a look at changing this behavior.

**Comment by YannickRe** [comment]
Well, that certainly explains why I ran into these issues 😃.

I don't get why doing StorageEntity in a tenant template does work when I use my own AppId & Certificate. Isn't that also supposed to fail following that logic?

**Comment by erwinvanhunen** [comment]
the behavior depends on the various handlers. For most handlers we use the provided context, where some handlers will call back into the calling host to provide an access token instead (in this case the Invoke-PnPTenantTemplate cmdlet, which in return will return a token, or tries to return a token, based upon the PnP Management Shell multi-tenant app)

**Comment by erwinvanhunen** [comment]
A fix for this issue has been committed and it will be available in tomorrow's nightly build (0.2.18). Would be great if you could test it! I will close this issue now, but do not hesitate to open a new one if applicable.

**Comment by YannickRe** [comment]
Now that is a service I'd pay for! I'll make sure to test tomorrow, in my DevOps pipeline, and check out that commit to help me understand this better. Thank you!

**Comment by YannickRe** [comment]
@erwinvanhunen I tested this and can confirm it works, so thank you! I am now faced with an underlying PnP.Framework issue that doesn't respect the Overwrite tag. I submitted a PR: https://github.com/pnp/pnpframework/pull/33
