### ISSUE TITLE
[BUG] Connect-PnPOnline: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.50.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'. Could not find or load a specific file. (0x80131621)

### ISSUE THREAD

**Issue by jolscr** [pnp/powershell#3402]
### Reporting an Issue

I use PowerShell 7.2.6 with MicrosoftTeams 5.5.0 and PnP.PowerShell 2.1.1

I connect first with "**Connect-MicrosoftTeams**" and then with "**Connect-PnPOnline**".

I receive the **ERROR**: "_Connect-PnPOnline: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.50.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'. Could not find or load a specific file. (0x80131621)_"

![image](https://github.com/pnp/powershell/assets/46568866/a1983a41-d4e7-436b-a005-f9058d47b9a0)

"Connect-MicrosoftTeams" load Microsoft.Identity.Client with her own version 4.29 and "Connect-PnPOnline" fails to load v4.50

- Microsoft.Identity.Client, Version=4.29.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae
C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\5.5.0\net472\Microsoft.Identity.Client.dll

If I open a new PowerShell 7 session and run first "**Connect-PnPOnline**" and then "**Connect-MicrosoftTeams**" it run with **success**.
And only one dll load (v4.50):

- Microsoft.Identity.Client, Version=4.50.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae
C:\Users\kollyj01\Documents\PowerShell\Modules\PnP.PowerShell\2.1.1\Core\Microsoft.Identity.Client.dll

If I run these cmdlets in PowerShell 5, I have no problem. both dll load (as you cas see I use PnP 1.12 in PowerShell 5 and it use Microsoft.Identity.Client v 4.36)

- Microsoft.Identity.Client, Version=4.29.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae
C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\5.5.0\net472\Microsoft.Identity.Client.dll

- Microsoft.Identity.Client, Version=4.36.1.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae
C:\Program Files\WindowsPowerShell\Modules\PnP.PowerShell\1.12.0\Framework\Microsoft.Identity.Client.dll

PS: I use this cmdlet to show dll loaded:
[System.AppDomain]::CurrentDomain.GetAssemblies() | Where-Object Location | Sort-Object -Property FullName | Select-Object -Property FullName, Location, GlobalAssemblyCache, IsFullyTrusted

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
hi @jolscr , we have potentially fixed this issue with the latest version of PnP PowerShell nightly builds. 

Would encourage you to check it out.

**Comment by jolscr** [comment]
Yes you right. Thank you!
It's fixed... hope main release will come in the next few days.

![image](https://github.com/pnp/powershell/assets/46568866/c7d8a538-99bb-4708-a3f5-49bd762a4d17)
