### ISSUE TITLE
[FEATURE] Links on documentation hub do not appear as links, can be confusing.

### ISSUE THREAD

**Issue by SPDEVGUY** [pnp/powershell#3404]
While on the https://pnp.github.io/powershell/#getting-up-and-running page I noticed that none of the links to other locations actually looked like links to users.  It would be nice to see some CSS adjustments on the page to either have differing colours or underline so that links are more apparent to new users.

![image](https://github.com/pnp/powershell/assets/3208188/e9bb068b-7c28-4392-b50c-e1735196f5c9)

When you hover it shows;
![image](https://github.com/pnp/powershell/assets/3208188/82b9dc51-b947-4b90-a40e-8b297708eddd)

Ideally, good UI design would be to have them always show as a different colour (example being github below "contributing guidelines")
![image](https://github.com/pnp/powershell/assets/3208188/5fd9bcd4-3411-4952-ad46-aa56bee283b5)

**Comment by kunj-sangani** [comment]
Hi @gautamdsheth 

I can fix this issue 
Can you please assign me this issue

**Comment by gautamdsheth** [comment]
Closing this now , as it has been fixed now by @kunj-sangani !
