### ISSUE TITLE
[BUG] Error when using Get-PnPSiteTemplate. Calculated field formulas get translated to english.

### ISSUE THREAD

**Issue by vincepunkrock** [pnp/powershell#3409]
The formula keywords like IF and RIGHT get translated. The formula was written in french originally (SI, DROITE).
When I then use Invoke-PnpSiteTemplate, I get the following error message: "The formula contains a syntax error or is not supported.".
The english formula (which is now in the xml template) is not accepted in a french site.

### Expected behavior 
The formula should stay in the same language it was originally written in. IOne would then be able to Invoke the template on a site using the same language,

### Actual behavior 
The formula gets translated to english, preventing it to work when invoking the template.

### What is the version of the Cmdlet module you are running?
2.2.0

### Which operating system/environment are you running PnP PowerShell on?
- Windows

**Comment by gautamdsheth** [comment]
Hi , you need to raise an issue in [here](https://github.com/pnp/pnpframework/issues). This is where the PnP provisioning code actually resides.

Will be closing it here.
