### ISSUE TITLE
[BUG] build/Build-Nightly.ps1

### ISSUE THREAD

**Issue by matthiasklauke** [pnp/powershell#3410]
The variable $runPublic in line 45 is not defined. It should be named $runPublish. As $runPublic results to $null the comparsion `$runPublic -eq $false` is always false and the code in the if statement is never reachedand the comparsion `$existing_pnpcoresdk_hash -ne $pnpcoresdk_hash` has no impact.

**Comment by gautamdsheth** [comment]
@matthiasklauke - good catch, have fixed it.
