### ISSUE TITLE
Unable to Execute Register-PnPManagementShellAccess in GCC-High

### ISSUE THREAD

**Issue by cpoteet** [pnp/powershell#3419]
### Reporting an Issue or Missing Feature
After several days of troubleshooting, we cannot get the Register-PnPManagementShellAccess cmdlet to successfully execute on a GCC-High tenant. We are wanting to use it for authentication to a remote provisioning console app.

We were able to successfully register our own Azure AD app per the instructions for connecting to the government clouds. However, we cannot run the Register Shell cmdlet. It does execute, goes through the interactive login, but after the password it simply appears to time out and leaves a blank screen. The account running this is a GA, has MFA disabled, write access to AD, and E5 licensed.

This same issue appears to be referenced in other bugs such as this closed item without a resolution: https://github.com/pnp/powershell/issues/1180

### Expected behavior 
I expect to run the cmdlet and see the PnP Management Shell Access application in the enterprise applications area of Azure AD.

### Actual behavior 
After logging in, it simply appears to die without giving the consent prompt. It works as expected in a commercial tenant.

### What is the version of the Cmdlet module you are running?
Nightly pre-release (just updated on Friday).

### Which operating system/environment are you running PnP PowerShell on?
Windows

**Comment by gautamdsheth** [comment]
@cpoteet - did you specify the `-TenantName` parameter and check ?

**Comment by gautamdsheth** [comment]
Closing due to lack of response. Feel free to reopen of the issue exists after checking the above comment,

**Comment by aarontguilmette** [comment]
Still not working. I have a GCCH tenant and attempting to complete the registration. After specifying both the tenant name (TenantName <tenant>.onmicrosoft.us) and the Azure instance (AzureEnvironment USGovernment), I am prompted to enter my credentials. After successfully entering credentials, I receive the following notification:

_You did not consent for the PnP Management Shell Application for use by PnP PowerShell. Feel free to close this browser window.

Error details: error invalid_request error_description:AADSTS65006: Resource '797f4846-ba00-4fd7-ba43-dac1f8f63013' had no entitlements matching required permissions configured on the required resource access for client '31359c7f-bd7e-475c-86db-fdb8c937548e'. Requested permission IDs: '41094075-9dad-400e-a0bd-54e686782033'. This is a problem with one or more invalid permission ids on the client RRA configuration or the resource entitlement configuration. Trace ID: 7d965bc1-633e-4281-8866-2c4a5cfd0200 Correlation ID: 068e5484-49a3-417d-b65b-902343a69d74 Timestamp: 2024-02-16 14:31:39Z_

My tenant is brand new (about a 2 weeks old) and has no users, data, or applications deployed.

![pnpmanagementshellerror](https://github.com/pnp/powershell/assets/126546027/72d5b10d-0477-4d14-834d-f99ad2f5be36)
