### ISSUE TITLE
[FEATURE] Convert a file in SharePoint to PDF. 

### ISSUE THREAD

**Issue by NishkalankBezawada** [pnp/powershell#3422]
**Solution Proposal**
The solution is to convert a file in SharePoint to PDF. 
A new command as ***Convert-PnPFileToPDF***
The command should accept the file url (mandatory) and the target location (as optional) where the file should be saved.
If target location isn't specified, the file will be saved in one drive.

**Will be working on this, and creating a PR soon.**

*Save to Local 
*Retrieve as Memory Stream
*Upload to SharePoint Library 
*CheckInType
*Publish
*Approve

**Comment by Studermarc** [comment]
This looks like a really nice addition. Would it be possible also to provide multiple files as input (e.g. an array of file urls) and merge them into one pdf file?
