### ISSUE TITLE
[BUG] Add-PnPNavigationNode error in 2.2.0

### ISSUE THREAD

**Issue by koki-v3** [pnp/powershell#3423]
### Reporting an Issue or Missing Feature
I recently updated to version 2.2.0 because of the addition of `-OpenInNewTab` parameter in the `Add-PnPNavigationNode` cmdlet. However ever since then, I am unable to run this command successfully. Instead I receive an "error" message, however the message is blank.

### Expected behavior 
In version 1.12.0 that I've been running in Windows Powershell, this command works without issues.
`$node = Add-PnPNavigationNode -Title "Home" -Url "https://contoso.sharepoint.com/" -Location "QuickLaunch"`

When I then check the `$node` variable, I get all the details I need:
```
PS C:\> $node

Id   Title Visible Url
--   ----- ------- ---
3358 Home  True    https://contoso.sharepoint.com/
```
### Actual behavior 
In version 2.2.0, ran in Powershell 7, this happens when I run the same command:
`$node = Add-PnPNavigationNode -Title "Home" -Url "https://contoso.sharepoint.com/" -Location "QuickLaunch"`

I get a response that just shows this:
`Add-PnPNavigationNode:`
^ Note that this response is red, as if it is meant to show an error message, but there is nothing shown.
Additionally, when I check the `$node` variable, it's blank, nothing gets saved into it.

### Steps to reproduce behavior
Running `Add-PnPNavigationNode` always gives me this result, doesn't matter which parameters I use.

### What is the version of the Cmdlet module you are running?
2.2.0

### Which operating system/environment are you running PnP PowerShell on?
Windows, Powershell 7.3.6

**Comment by Studermarc** [comment]
The 2.2.0 version doesn't work in windows PowerShell. You need PowerShell 7. 

Check the documentation to upgrade. https://github.com/pnp/powershell/blob/dev/MIGRATE-1.0-to-2.0.md

**Comment by koki-v3** [comment]
I _am_ running the 2.2.0 version in Powershell 7, as you can see in my post.

**Comment by Studermarc** [comment]
Have you tried providing a connection object with it ?

``` powershell
$Connection = Connect-PnPOnline -Url .... .... -ReturnConnection #Choose your connection options
$node = Add-PnPNavigationNode -Title "Home" -Url "https://contoso.sharepoint.com/" -Location "QuickLaunch" -Connection $Connection
```

**Comment by gautamdsheth** [comment]
Can't repro this issue as well, using the latest version :

<img width="945" alt="image" src="https://github.com/pnp/powershell/assets/8832018/2281aabb-4c90-4846-aad6-470b0a3fc462">

**Comment by koki-v3** [comment]
I was testing this some more and turns out using the -UseWebLogin parameter when connecting to the site is causing the error.
When I don't use the -UseWebLogin connection, and use -Interactive or no parameter at all, the command works fine.

I'd think that all commands should work the same regardless which authentication I use as long as I connect, but here we are. We'll be using -Interactive instead.

**Comment by gautamdsheth** [comment]
@koki-v3  - weblogin authentication is not recommended. The issue here would then lie with the API / CSOM method that we use. Those are owned by Microsoft, so can't really do much about that.

Will close this issue now, thanks for letting us know that you managed to get it working !
