### ISSUE TITLE
[BUG] SiteOwnerManageLegacyServicePrincipalEnabled

### ISSUE THREAD

**Issue by IfEyeOnlyKnew** [pnp/powershell#3433]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

Running this command and parameter:  `Set-pnptenant -SiteOwnerManageLegacyServicePrincipalEnabled $true`

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting - Parameter is missing SiteOwnerManageLegacyServicePrincipalEnabled

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

`Set-pnptenant -SiteOwnerManageLegacyServicePrincipalEnabled $true`

ERRROR: 
Set-PnPTenant: A parameter cannot be found that matches parameter name 'SiteOwnerManageLegacyServicePrincipalEna
bled'.

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

connect-pnponline -Url https://tenant-admin.sharepoint.com/  -interactive (SharePoint Admin role)
Set-PnPTenant -SiteOwnerManageLegacyServicePrincipalEnabled $true

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

>Get-Module -Name "PnP.PowerShell" -ListAvailable

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   2.2.0                 PnP.PowerShell                      Desk      {Add-PnPAdaptiveScopeProperty, …
Manifest   1.12.0                PnP.PowerShell                      Core,Desk {Add-PnPAdaptiveScopeProperty, …
Manifest   1.4.0                 PnP.PowerShell                      Core,Desk {Add-PnPClientSidePage, Add-PnP…

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows

![setpnptenant](https://github.com/pnp/powershell/assets/12399849/d6023206-f0ec-4fc3-857c-f654d0705039)

**Comment by IfEyeOnlyKnew** [comment]
![GetCommand](https://github.com/pnp/powershell/assets/12399849/b4722e47-f6af-488e-9656-332d611e252d)

**Comment by IfEyeOnlyKnew** [comment]
I see this maybe was deployed in August.  https://github.com/pnp/powershell/pull/3318

**Comment by veronicageek** [comment]
That's correct, so you need to use a nightly build.
Seems Microsoft has fixed the problem (as seen in #3359)
