### ISSUE TITLE
[BUG] Invoke-PnPSPRestMethod throws Exception in Azure Runbook

### ISSUE THREAD

**Issue by EA12** [pnp/powershell#3451]
### Reporting an Issue
AudienceUriValidationFailedException from Invoke-PnPSPRestMethod when using this cmdlet in an Azure Runbook

### Expected behavior 
The REST-Method should succeed

### Actual behavior 
Getting error:
{"error_description":"Exception of type 'Microsoft.IdentityModel.Tokens.AudienceUriValidationFailedException' was thrown."}

![image](https://github.com/pnp/powershell/assets/22025808/358256aa-4ade-469e-a39d-d3e7b7bcbf84)

### Steps to reproduce behavior
Automation-Account has System-Identity
Related App-Registration has Sites.FullControl.All and User.ReadWrite.All for Graph and SharePoint

![image](https://github.com/pnp/powershell/assets/22025808/1e98dcab-c775-42f3-bb2b-c9c37bc2c82a)

App-reg has a valid certificate and a valid Secret.
I have added App-Only (ACS) for this App-Reg at the admin site: https://mytenant-admin.sharepoint.com

Connecting:
$cnn = Connect-PnPOnline -Url $adminUrl -ClientId $clientId -ClientSecret $clientSecret -ReturnConnection

The API to use (to assign a UPS-Property)
$url = "https://mytenant.sharepoint.com/_api/SP.UserProfiles.PeopleManager/SetSingleValueProfileProperty"

Calling  Invoke-PnPSPRestMethod throws the error:
$response = Invoke-PnPSPRestMethod -Url $url -Connection $cnn -Method 'POST' -ContentType 'application/json;odata=nometadata' -Content $Body
                           
I couldn't find a code file here on github for Invoke-PnPSPRestMethod, just a documentation and an incomplete test.

### What is the version of the Cmdlet module you are running?
My script is running in an azure runbook with PowerShell-runtime 5.1 and PnP.PowerShell 1.9.59

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [x] Azure Runbook

**Comment by gautamdsheth** [comment]
@EA12 - have you tried using `Set-PnPUserProfileProperty` cmdlet , should work the same way ? Looks like an issue with the API itself , so not sure if we can do anything here.

Maybe using this workaround https://github.com/pnp/powershell/issues/277#issuecomment-866839692 can help ?

**Comment by gautamdsheth** [comment]
Closing this due to lack of response.
Just FYI, ACS has been deprecated as of 27th Nov 2023, so we won't be fixing this specific issue

https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins/retirement-announcement-for-azure-acs
