### ISSUE TITLE
Update Add-PnPNavigationNode with flush cache 

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/powershell#3458]
Wouldn't it be better to include the workaround from https://github.com/pnp/powershell/issues/1881 into the Add-PnPNavigationNode , perhaps as a switch?

I have just used most of a day on trying to figure out how come the updates didn't show up. It might be per design, but it ain't logical.

**Comment by kasperbolarsen** [comment]
Perhaps a new cmd that flushes the cache will a better solution?🤔

**Comment by gautamdsheth** [comment]
Not sure if we need this, I can't repro the issue. 
Whenever I add a new link using OpenInNewTab and QuickLaunch, it works 🤷

**Comment by kasperbolarsen** [comment]
> Not sure if we need this, I can't repro the issue. 
> Whenever I add a new link using OpenInNewTab and QuickLaunch, it works 🤷

Are you adding the nav mode to the hub navigation?

**Comment by kasperbolarsen** [comment]
@gautamdsheth When you have the time available, I would very much appreciate it if you can retest this one, using the Hub navigation. I have tested again on two tenants and gets the same result.

**Comment by gautamdsheth** [comment]
@kasperbolarsen - how are you able to add navigation to hub navigation ? Not sure if `Add-PnPNavigationNode` works for that , tried it didn't work. Maybe am missing something ?
