### ISSUE TITLE
[BUG] A parameter cannot be found that matches parameter name 'AzureADWorkloadIdentity'.

### ISSUE THREAD

**Issue by kkazala** [pnp/powershell#3476]
### Reporting an Issue or Missing Feature
According to the documentation, the `Connect-PnPOnline` has now `-AzureADWorkloadIdentity` parameter: https://pnp.github.io/powershell/cmdlets/Connect-PnPOnline.html#azure-ad-workload-identity

I have PnP.PowerShell 2.2.0
![image](https://github.com/pnp/powershell/assets/22429087/b08f4eac-3610-4115-a13b-ee519429ef12)
But the parameter is missing:
![image](https://github.com/pnp/powershell/assets/22429087/57b5ccf0-2c2a-4b01-901c-b1b6a55ffab0)

Bing tells me that _"According to the documentation, the AzureADWorkloadIdentity parameter was added in version 1.8.0 of the PnP.PowerShell module, which is a cross-platform module that works on Windows, Linux, and macOS. If you are using the SharePointPnPPowerShellOnline module, which is a Windows-only module, you will not be able to use this parameter. You may need to update your module or switch to the PnP.PowerShell module to use this feature."_

I am using PnP.PowerShell and the version is certainly higher than 1.8.0

### Expected behavior 
The `Connect-PnPOnline -Url contoso.sharepoint.com -AzureADWorkloadIdentity` should be executed correctly

### Actual behavior 
Error: `A parameter cannot be found that matches parameter name 'AzureADWorkloadIdentity'.`

### Steps to reproduce behavior
To verify if the parameter is present:
- Install PnP.PowerShell 2.2.0
- Import-Module  PnP.PowerShell
- in the PS console (PS7), type ` Connect-PnPOnline` and than type `-` and follow with `Ctrl+Space` to display all parameters

### What is the version of the Cmdlet module you are running?
2.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@gautamdsheth - Indeed the parameter is not present in `2.2.0` (I've verified in the CHANGELOG and it was part of this version). Surprisingly `2.2.76` had it while the latest `2.2.94` doesn't.

**Comment by gautamdsheth** [comment]
@veronicageek - it is there in the latest, can you maybe do a clean install and check again ?

**Comment by veronicageek** [comment]
@gautamdsheth - I did and it's the same. Got it in `2.2.76` but not the others (`2.2.0` and `2.2.94`) 🤷🏻‍♀️

**Comment by gautamdsheth** [comment]
@veronicageek - That's weird, am using the latest nightly builds and it is there. It doesn't work because it needs to be in some Azure service, but the parameter is there for sure:

<img width="941" alt="image" src="https://github.com/pnp/powershell/assets/8832018/9f889226-5452-41e2-b208-95a37e072dda">

@kkazala - can you please try it out with the latest nightly builds and let us know ?

**Comment by kkazala** [comment]
@gautamdsheth Nightly build (`2.2.100`) has the `-AzureADWorkloadIdentity` parameter. 
Would be great if it stayed in =)

Another weird thing that I see is that after calling
```powershell
$url = "https://$tenantName.sharepoint.com"

 try {
     Connect-PnPOnline -Url $url -AzureADWorkloadIdentity
 }
 catch {
     Write-Host "##[error] (Connect-PnPOnline -AzureADWorkloadIdentity): $($_.Exception.Message)"
}
```
I get the following error message: ` ##[error] (Connect-PnPOnline -AzureADWorkloadIdentity): Value cannot be null. (Parameter 'path')`

I'm running it from a pipeline with [workload identity service connection](https://learn.microsoft.com/en-us/azure/devops/pipelines/release/configure-workload-identity?view=azure-devops), so I guess this should work?

**Comment by gautamdsheth** [comment]
@kkazala - thanks for confirming, am going to close this issue.

Lets keep the conversation going in your FR:  https://github.com/pnp/powershell/issues/3249
