### ISSUE TITLE
[BUG] Get-PnPView does not retrieve ViewQuery

### ISSUE THREAD

**Issue by broilertech** [pnp/powershell#3479]
### Reporting an Issue or Missing Feature
Get-PnPView does not retrieve ViewQuery

### Expected behavior 
Cmdlet gets all available information from view

### Actual behavior 
Only retrieve Title, Id, Default and Personal

### Steps to reproduce behavior
$view = Get-PnPView -List "list name" -Identity "view name"
$view 
$view.ViewQuery --> no output
$view.Properties.ViewQuery --> no output

### What is the version of the Cmdlet module you are running?
2.20

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by danielcecil** [comment]
Hi @sp00kyDD the ViewQuery option can be returned in the View object by including it in the request, e.g:
`$view = Get-PnPView -List "list name" -Identity "view name" -Include ViewQuery`

**Comment by sp00kyDD** [comment]
> Hi @sp00kyDD the ViewQuery property can be returned in the View object by including it in the request, e.g: `$view = Get-PnPView -List "list name" -Identity "view name" -Includes ViewQuery`

@danielcecil  Thank you!!! Didn't know that. Maybe the docu can be adjusted at this point?

**Comment by danielcecil** [comment]
No worries :-) FYI the Includes parameter is in most or all of the 'Get' commands albeit not explicitly explained in the docs for this particular command.

**Comment by veronicageek** [comment]
Thanks for your input @danielcecil 👍🏻
