### ISSUE TITLE
[BUG] Sync-PnPSharePointUserProfilesFromAzureActiveDirectory produces different JSON when passing Users to the Function

### ISSUE THREAD

**Issue by FreakIsTea** [pnp/powershell#3483]
### Reporting an Issue or Missing Feature
When using Sync-PnPSharePointUserProfilesFromAzureActiveDirectory, the JSON generated in the document library does not contain all Properties when passing in Users. If the users parameter is not used, the JSON is generated correctly.

### Expected behavior 
When passing users, the JSON should contain all Properties defined in the UserProfilePropertyMapping parameter.

### Actual behavior 
When passing users, the JSON does not contain all Properties defined in the UserProfilePropertyMapping parameter.

### Steps to reproduce behavior
1. Connect to a SharePoint site with Connect-PnPOnline
2. Run the command: Sync-PnPSharePointUserProfilesFromAzureActiveDirectory -UserProfilePropertyMapping @{'SPS-Department'= 'Department';'FirstName'='GivenName';'LastName'='sn'; 'Department'='Department'; 'Manager'='Manager'} -Folder "<FolderName>" -WhatIf
3. JSON with all properties{ "value": [
"IdName":"<upn>","Manager":"","SPS-Department":"","FirstName":"","Department":""
]}
4. Get Users from Azure AD: $users = Get-PnPAzureADUser
5. Run Command again with users: Sync-PnPSharePointUserProfilesFromAzureActiveDirectory -UserProfilePropertyMapping @{'SPS-Department'= 'Department';'FirstName'='GivenName';'LastName'='sn'; 'Department'='Department'; 'Manager'='Manager'} -Folder "Freigegebene Dokumente" -Users $users -WhatIf
6. JSON with missing properties{ "value": [
"IdName":"<upn>","FirstName":""
]}

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 2.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by KoenZomers** [comment]
Having a quick look at the code with regards to what you're reporting here, it feels like the case must be that the users you are passing in using -Users do not contain the properties which you are missing in the JSON. Is this possible? If you don't provide users yourself, it will fetch all the properties matching the ones in -UserProfilePropertyMapping from AAD itself. If you pass in Users, it will assume you took care of passing in all the right properties. It double checks when creating the JSON that you actually did do so and if not, it will omit them in the JSON. It feels like this is your scenario. Can you validate this?

**Comment by gautamdsheth** [comment]
Closing it due to lack of response, feel free to reopen this with more information, thanks !
