### ISSUE TITLE
[BUG] Add-PnPNavigationNode -previousnode parameter not available anymore

### ISSUE THREAD

**Issue by mvanders** [pnp/powershell#3493]
When adding -PreviousNode parameter to Add-PnPNavigationNode error received

Add-PnPNavigationNode : A parameter cannot be found that matches parameter name 'PreviousNode'.

code example:
Add-PnPNavigationNode -Title "AllGroups by Domain" -Url "/sites/GUESTS/Lists/Groups/?viewid=33f5f8ab%2D77ab%2D4e07%2Dbee1%2D7f3f1f6ac01e" -Location "QuickLaunch" -PreviousNode 2021

**Comment by gautamdsheth** [comment]
hi @mvanders , this parameter is available in newer versions of PnP PowerShell.

You need to use PnP PowerShell 2.2.0 for the stable one or you can use the nightly builds.

<img width="956" alt="image" src="https://github.com/pnp/powershell/assets/8832018/2411339f-17f6-4a8e-bf27-17ddf24484b7">
