### ISSUE TITLE
[BUG] - Unable to pass Guid object to Get-PnPTeamsTeam

### ISSUE THREAD

**Issue by reshmee011** [pnp/powershell#3495]
### Reporting an Issue 
 Unable to pass Guid object to Get-PnPTeamsTeam 

### Expected behavior 
Teams should return with Guid object
e.g. $site.GoupId is Guid

$site = Get-PnpTenantSite -Url https://contoso.sharepoint.com/sites/Company311
Get-PnPTeamsTeam  -Identity $site.GroupId 

### Actual behavior 
Message below is displayed

Get-PnPTeamsTeam: Cannot bind parameter 'Identity'. Cannot convert the "4aced257-38ee-484c-b441-ce09a71a14ad" value of type "System.Guid" to type "PnP.PowerShell.Commands.Base.PipeBinds.TeamsTeamPipeBind".

### Steps to reproduce behavior
$site = Get-PnpTenantSite -Url https://contoso.sharepoint.com/sites/Company311
Get-PnPTeamsTeam  -Identity $site.GroupId 

### What is the version of the Cmdlet module you are running?
2.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows

**Comment by reshmee011** [comment]
Please assign to me to work on it.

**Comment by Mersanko** [comment]
May I ask the fix for this issue?

**Comment by KoenZomers** [comment]
@Mersanko It works well here. Can you try this with the latest nightly build of PnP PowerShell?
