### ISSUE TITLE
[BUG] Get-PnPList -Identity Lists/ListName fails with an exception if List does not exist

### ISSUE THREAD

**Issue by TullettJay** [pnp/powershell#3506]
### Reporting an Issue or Missing Feature
An Issue with **Get-PnPList** when used with the `-Identity`  switch

### Expected behavior 
The command  `Get-PnPList -Identity "Lists/Pages"` should either retuirn a list reference or `$null` if no such List exists

### Actual behavior 
`Get-PnPList -Identity Lists/Pages
Get-PnPList: List 'Lists/Pages' does not exist at site with URL 'https://ELIDED.sharepoint.com/teams-and-projects/platform-dev/operational-services'.`

### Steps to reproduce behavior
`Connect-PnPOnline https://myIntranet.sharepoint.com/sites/mySite`
`Get-PnPList -Identity Lists/Pages`

### What is the version of the Cmdlet module you are running?
2.2

### Which operating system/environment are you running PnP PowerShell on?
- [* ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
hi @TullettJay , this is as designed.

You can specify `-ErrorAction SilentlyContinue` and it will return null.

<img width="857" alt="image" src="https://github.com/pnp/powershell/assets/8832018/3fb6ef49-0039-400b-93f0-40a1fbef2d2b">
