### ISSUE TITLE
[BUG] get-pnpgroup fails to return group by id if passed by variable.

### ISSUE THREAD

**Issue by SPDEVGUY** [pnp/powershell#3508]
### Reporting an Issue or Missing Feature

Passing a variable containing a group id number into get-pnpgroup results in "Site group not found"

### Expected behavior 
Detect if input is numeric or text and retrieve group by id number if numeric. (if not found by numeric, try finding as title of group)
Especially odd behavior was observed where it would accept a number but fail with a variable that held the number. 

### Actual behavior 
**$groupid = (get-pnpgroup)[0].id**
**$groupid**
14809

**Get-PnPGroup -identity $groupid**
Get-PnPGroup: Site group not found

**Get-PnPGroup -identity [int]$groupid**
Get-PnPGroup: Site group not found

**$groupid**
14809

**Get-PnPGroup -identity 14809**

Id    Title              LoginName
--    -----              ---------
14809 Test Members Test Members

### Steps to reproduce behavior
see above

### What is the version of the Cmdlet module you are running?
2.2.0 PnP.PowerShell

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows

**Comment by gautamdsheth** [comment]
hi @SPDEVGUY , this is working as designed.

It needs to be `Id` not `id` which you are using.

In your code, `id` is null , so your code is failing.

<img width="470" alt="image" src="https://github.com/pnp/powershell/assets/8832018/68e1ac6e-eb6d-4449-8488-4d560b4acf4b">

**Comment by SPDEVGUY** [comment]
Powershell is not case sensitive.

The problem is that groupId was an object of type string.  

![image](https://github.com/pnp/powershell/assets/3208188/e316d204-6cbc-49c0-bbbd-75a496ac2002)
