### ISSUE TITLE
[BUG] Set-PnpListItem The specified user (rolemanager group sid) could not be found.

### ISSUE THREAD

**Issue by SPDEVGUY** [pnp/powershell#3509]
### Reporting an Issue or Missing Feature
Set-pnplist item appears to not accept group claims as part of a user picker field setting.
The claim appears to exist (get-pnpuser returns a result for it as expected)

### Expected behavior 

When provided the claim value for an AD group role it should resolve to a user (rolemanager claim)

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

### Steps to reproduce behavior

AD group as role manager claim is created
AD group is added to an SP Group
Retrieved AD Group claim from SP Group Users list (Get-pnpGroup).Users
AD Group claim id (loginname) is: "c:0-.f|rolemanager|s-1-5-21-4187335146-4260307558-3515784065-9947325"
Add the group claim to the field values for the User or Group field (field name is "MyUsersField")
Able to perform get-pnpuser [claimid] and returns expected result.

```
$values
Name                           Value
----                           -----
MyUsersField                          {c:0-.f|rolemanager|s-1-5-21-4187335146-4260307558-3515784065-9947325}

Set-PnPListItem:
Line |
 100 |  $x = set-pnplistitem -list $listName -id $id -Values $values -Up …
     |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The specified user c:0-.f|rolemanager|s-1-5-21-4187335146-4260307558-3515784065-9947325 could not be found.

get-pnpuser "c:0-.f|rolemanager|s-1-5-21-4187335146-4260307558-3515784065-9947325"

 Id Title          LoginName                                                            Email
 -- -----          ---------                                                            -----
477 Test Users c:0-.f|rolemanager|s-1-5-21-4187335146-4260307558-3515784065-9947325 Test.Users@domain.com
```

### What is the version of the Cmdlet module you are running?
2.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by SPDEVGUY** [comment]
The cause was:
A user from Site A (Exists in site user info list, is a member of a group, account was deleted or removed, but still exists in sharepoint)

Was trying to be added to a list on a new Site B (does not have a record in site user info list for the user).

This can also occur if the user simply does not exist in the site user info list as Get-PNPUser doesn't seem to use Web.EnsureUser to ensure some kind of object exists.  So you could be calling get-pnpuser with a valid user but the user isn't yet registered in the site user info list so the call returns no object.  So if get-pnpuser fails you must also try new-pnpuser which will throw an error properly if the user account does not exist in the AD.

Code that helps filter out non-existant users.
```
        $userListStr = ""
	$missingUserListStr = ""
	foreach($user in $group.Users) {
		if($user.LoginName -eq "SHAREPOINT\system") {continue;}
		
		try {
			$userObj = get-pnpuser $user.LoginName
			if($userObj -eq $null) {
				$userObj = new-pnpuser -loginName $user.LoginName -EA 0 #EA0 is to not throw exception on not existing, which could be useful but not in this context
			}
			if($userObj -ne $null) {
				if($userListStr) { $userListStr +=";"}
				$userListStr += $user.LoginName;
			} else {
				write-host "User $($user.Title) ($($user.LoginName)): Not found."
				if($missingUserListStr) { $missingUserListStr +="`n"}
				$missingUserListStr += "$($user.Title) ($($user.LoginName))";
			}
		} catch {
			write-host "Error on user $($user.LoginName): $_"
		}			
	}	
```

**Comment by SPDEVGUY** [comment]
Potentially change this to a bug to a feature request... maybe if Get-PnpUser fails to return a user when provided the username it tries to use New-PnpUser to register it in the site user info list? or a flag -CreateIfNotFound ?

Currently it doesn't make sense to return nothing when someone does Get-PNPUser [UserName] where [UserName] exists in AD but does not yet exist in the Site User Info List.

**Comment by gautamdsheth** [comment]
@SPDEVGUY - this is not something we would like to implement for performance reasons. Querying a user from site info list , if it doesn't exist then try adding it would have a big impact.
