### ISSUE TITLE
[FEATURE] Update documentation for Get-PNPUser & Set-PNPListItem Relative to #3509

### ISSUE THREAD

**Issue by SPDEVGUY** [pnp/powershell#3513]
**Is your feature request related to a problem? Please describe.**
Get-PNPUser does not return a user if the user is not registered in the Site User Info List
Set-PNPListItem will throw an error saying the user does not exist if they are not registered in the Site User Info List
The documentation does not reflect this and the behavior is not intuitive.

The new-PNPUser command is needed to register the user with the site user info list before the account will be returned or usable by those commands and this can cause confusion if creating scripts to automate copying of some data or field values between site collections.

**Describe the solution you'd like**

[https://pnp.github.io/powershell/cmdlets/Get-PnPUser.html exa[m](https://pnp.github.io/powershell/cmdlets/Get-PnPUser.html#example-3) 
Please add a notice that if you receive a user cannot be found error or the get-pnpuser returns no result this is because new-pnpuser must first be used to register the user with the site user info list regardless of whether the user is available from the directory or not.

**Describe alternatives you've considered**
https://github.com/pnp/powershell/issues/3509
I have some code which will try to get the user, if the user returns nothing it tries new-pnpuser and if that returns nothing then it assumes the user is missing from AD.  Improvement on the documentation would be good since the bug report will not be fixed.

**Additional context**

**Comment by gautamdsheth** [comment]
hi @SPDEVGUY , have updated `Add/Set-PnPListItem` cmdlet to reflect what you mentioned here. Totally makes sense. 

For Get-PnPUser cmdlet, the docs is pretty clear, so haven't updated it.
