### ISSUE TITLE
[BUG] Set-PnPListItem -Batch fails when some multivalued columns are not part of the -Values hash

### ISSUE THREAD

**Issue by PHubaut** [pnp/powershell#352]
### Expected behavior 
`Set-PnPListItem` allows batching as per the documentation.
Any `Set-PnPListItem` that works without "`-Batch`" is expected to also work with "`-Batch`".
Specifically, `Set-PnPListItem` could be used to update some, only, of all the columns of an Item.

### Actual behavior 
`Set-PnPListItem -Batch` will fail if the List to update contains some multivalued columns which are not mentioned under the `-Values @{}` parameter.

### Steps to reproduce behavior
I created a "ItemTest" List with column "Title" and another column "MVL" (multivalued lookup column to some other list).
The following, without "-Batch" works fine:
```
Set-PnPListItem -List "ItemTest" -Identity 1 -Values @{ "Title" = "Hello" } # ==> OK THIS WORKS
```
The following Fails:
```
# Batch, update of the single column "Title" (MVL, a multivalued lookup column not updated)
$batch = New-PnPBatch
Set-PnPListItem -List "ItemTest" -Identity 2 -Values @{ "Title" = "Hello" } -Batch $batch # ==> *** THIS FAILS
Invoke-PnPBatch -Batch $batch
```
the error is
```
Set-PnPListItem : Object reference not set to an instance of an object.
At C:\...\Test7.ps1:9 char:1
+ Set-PnPListItem -List "ItemTest" -Identity 2 -Values @{
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPListItem], NullReferenceException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Lists.SetListItem
```

If value(s) (or `$null`) is(are) provided for the "MVL" column in the `-Value` parameters, there is no error.
_To make it clear, the following works because "MVL" is present in `-Value`_:
```
$batch = New-PnPBatch
Set-PnPListItem -List "ItemTest" -Identity 2 -Values @{ "MVL" = 1, 2, 3; "Title" = "Hello" } -Batch $batch
Invoke-PnPBatch -Batch $batch
```

Note: in a more complex test, I could determine that ALL multivalued columns MUST be specified under `-Values` to make the `Set-PnPListItem` work with `-Batch` (I used several multivalued lookup columns and managed metadata).

### What is the version of the Cmdlet module you are running?
```
Version          Name                                   Repository
-------          ----                                   ----------
1.3.15-nightly   PnP.PowerShell                         PSGallery
```
PowerShell:
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17763  1490
```

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows

**Comment by veronicageek** [comment]
Hi @PHubaut, 
I was able to reproduce your error, but if you try with `-UpdateType` and choose your preferred update (see the [Set-PnPListItem](https://github.com/pnp/powershell/blob/dev/documentation/Set-PnPListItem.md) documentation), then it should work.

![image](https://user-images.githubusercontent.com/25181757/109384740-db2e7c00-78e6-11eb-9357-a917f64b8832.png)

**Comment by PHubaut** [comment]
> Hi @PHubaut,
> I was able to reproduce your error, but if you try with `-UpdateType` and choose your preferred update (see the [Set-PnPListItem](https://github.com/pnp/powershell/blob/dev/documentation/Set-PnPListItem.md) documentation), then it should work.

Thank you very much indeed - error only persists with `-UpdateType Update`.
Either `-UpdateType SystemUpdate` or `-UpdateType UpdateOverwriteVersion` are preventing the error to occur.
This workaround works fine for me. Again, thanks a lot.
