### ISSUE TITLE
PnP.PowerShell 2.2.0 Core PS Edition

### ISSUE THREAD

**Issue by hugokaa** [pnp/powershell#3522]
**Is your feature request related to a problem? Please describe.**
The new release of PnP.PowerShell 2.2.0 added the `ListsShowHeaderAndNavigation` parameter to the `Set-PnPSite` cmdlet. However, it is currently only available for Desk, and we require it for the Core PSEdition.

**Describe the solution you'd like**
Please make the new release available for the Core PSEdition.

**Describe alternatives you've considered**
The Microsoft SPO Management Shell also has the parameter, but it is only available for Desk. We have not found any similar functionality in Microsoft Graph.

**Additional context**
![image](https://github.com/pnp/powershell/assets/23038987/f2739157-8b61-4c21-b333-c27cb7aa40c6)

**Comment by veronicageek** [comment]
@hugokaa - PnP PowerShell `v2` is the version we will be supporting in the future (for PS7 only), but we won't be working on 1.12.x.

@gautamdsheth - Can you please confirm and close if correct.

**Comment by hugokaa** [comment]
@veronicageek  - We want to use v2. Is this version going to be available for the _Core PSEdition_?
Thank you!

**Comment by gautamdsheth** [comment]
@hugokaa - PnP PowerShell 2.x will only work on PowerShell 7.2 or later versions. So, yes it is available in Core edition.

If you have questions, please ask in the discussion forum [here](https://github.com/pnp/powershell/discussions)
