### ISSUE TITLE
[BUG] Send-PnPMail does not allow Importance without From

### ISSUE THREAD

**Issue by HeKr09** [pnp/powershell#3523]
### Reporting an Issue or Missing Feature
I want to send a mail with high importance but need to specify the "From" parameter.

### Expected behavior 
I'd expect to send a mail without the "From" parameter.

### Actual behavior 
I am not able to send a mail.
This one is working.
```
Connect-PnPOnline -Url URL -Credentials $creds
Send-PnPMail -To "Mymail@me.de" -Subject "Test" -Body "eadsa"
```
This one is **not** working.
```
Connect-PnPOnline -Url URL -Credentials $creds
Send-PnPMail -To "Mymail@me.de" -Subject "Test" -Body "eadsa" -Importance High
Send-PnPMail: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
```
This one is working again.
```
Connect-PnPOnline -Url URL -Credentials $creds
Send-PnPMail -To "Mymail@me.de" -Subject "Test" -Body "eadsa" -Importance High -From "AnotherValidMail@me.de"
```

### Steps to reproduce behavior
See code above.

### What is the version of the Cmdlet module you are running?
2.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
hi @HeKr09 , this is by design and not a bug.

The `Importance` parameter is only supported if sent via SMTP or Graph. 
When `-From` is not specified, we send it via SharePoint's built-in utility which doesn't support this property.
