### ISSUE TITLE
Add-PnPClientSideWebPart in Legacy SharePoint PnP is not available in current PnP PowerShell.

### ISSUE THREAD

**Issue by agaskelluk** [pnp/powershell#3525]
I used to use the **Add-PnPClientSideWebPart** for adding custom js to modern pages with the previous deprecated SharePoint PnPPowershell. This cmdlet no longer exists in the current PnP PowerShell. I don't see a replacement in any of the cmdlets available.

I investigated using the Add-PnPCustomAction cmdlet but it doesn't seem possible and I can't find an examples that use it.

I know we can use the deprecated PnP SharePoint Online PowerShell cmdlets in parallel, but we should be using the current version not relying on old unsupported libraries.

Please advise if I am missing something and how I should add custom js to a **modern page**. I know that I can use the SPFx Application customizer or script editor WP but I don't want these for my use case.

Thanks

Andrew.

**Comment by veronicageek** [comment]
@agaskelluk - As per the [CHANGELOG](https://github.com/pnp/powershell/blob/dev/CHANGELOG.md#removed-5), `Add-PnPClientSideWebPart` has been removed in `1.10.0` and you need to use `Add-PnPPageWebPart`. If that doesn't suit your needs, maybe one of our devs can point you in the right direction.

**Comment by agaskelluk** [comment]
@veronicageek thanks for the response. I checked that cmdlet already and there is no parameter for adding either inline js or a link to a js file. 
How would you achieve this?

**Comment by veronicageek** [comment]
CC @gautamdsheth @KoenZomers in case they know if that's possible.

**Comment by gautamdsheth** [comment]
Please ask questions in the discussion forum. 

Add-PnPPageWebpart is the same as Add-PnPClientSideWebpart , it was an alias.

**Comment by agaskelluk** [comment]
Add-PnPPageWebpart doesn't have the same params as it's predecessor. I don't see how it can be used as an alias. I have asked in the forum. Thanks.
