### ISSUE TITLE
[BUG] Invoke-PnPSiteTemplate messing up / and \ in current nightly

### ISSUE THREAD

**Issue by reply-jens** [pnp/powershell#3526]
## Category

- [x] Bug

## Describe the bug

Invoke-PnPSiteTemplate -Path "./tmp/pages/de/Page.xml" fails with "Object reference not set to an instance of an object." in Version  2.2.104-nightly when PageName in Page.xml is "folder1/folder2/Page.aspx" contains more than one subfolder. I guess this is the problem, slash and backslah messed up:
![2](https://github.com/pnp/powershell/assets/144896925/968e0fed-367c-4367-9951-31545ffbb2d1)

Even if correct in XML
![1](https://github.com/pnp/powershell/assets/144896925/1a4a93be-d26d-4e43-aa0f-4da017cb638b)

## Expected behavior
No Error, as using just one subfolder, like ./tmp/pages/Page.xml with PageName in Page.xml is "folder1/Page.aspx"

## Environment details (*development & target environment*)
- **PNP version**: 2.2.104-nightly
- **OS**: Windows 11
- **PSVersion**: 7.3.8
- **PSEdition**: Core

**Comment by gautamdsheth** [comment]
hi @reply-jens , thanks for opening the issue.

Could you please open it here instead: https://github.com/pnp/pnpframework/issues ?

PnP PowerShell consumes the provisioning engine, the actual logic resides in the above mentioned repo. Will be closing it here.
