### ISSUE TITLE
[BUG] Set-PnPTenantSite: The property or field 'ServerLibraryVersion' has not been initialized.

### ISSUE THREAD

**Issue by piou13** [pnp/powershell#353]
### Expected behavior 
Edit the settings of a specified site collection.

### Actual behavior 
Regardless the setting I'm trying to define, I get the following error message:
"Set-PnPTenantSite: The property or field 'ServerLibraryVersion' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested."

### Steps to reproduce behavior
Connect using Azure AD registered application:
`Connect-PnPOnline -CertificatePath "<cert_path>" -CertificatePassword (ConvertTo-SecureString -String "<cert_password>" -AsPlainText -Force) -Tenant "<tenant>" -ClientId <clientid> -Url <tenant_admin_url>`

When I use the command:
`Set-PnPTenantSite -Identity <site_collection_url> -DenyAddAndCustomizePages:$false`
I get the following error:
_"Set-PnPTenantSite: The property or field 'ServerLibraryVersion' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested._

As a workaround, I use the following command instead:
`Get-PnPTenantSite -Identity <site_collection_url> -Detailed | Set-PnPTenantSite -DenyAddAndCustomizePages:$false`
But i wonder if it's normal behavior.

### What is the version of the Cmdlet module you are running?
PowerShell: 7.1.2 rev:-1
PnP.PowerShell 1.3.0

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows

**Comment by erwinvanhunen** [comment]
We fixed it already a while ago in the nightly builds. It was a relatively weird issue that took a while to figure out. E.g. if you update to the latest nightly build you will notice that the issue does not occur anymore.

If you want to stay on version 1.3.0, the solution is to execute a cmdlet before Get-PnPTenantSite, straight after Connect-PnPOnline. It could as simple as 'Get-PnPList'.
