### ISSUE TITLE
[BUG] Get-PnPUserOneDriveQuota

### ISSUE THREAD

**Issue by DavidD065** [pnp/powershell#3539]
Reporting an Issue with the "https://pnp.github.io/powershell/cmdlets/Get-PnPUserOneDriveQuota.html" command which does not seem to be working for me, unable to find much online.

### Expected behavior 
Am expecting the current quote limit to be returned. 
Attempting to create a script that gets all users from a specific AD group, for each user check the user's onedrive quota if not specific size, then amend the size to the correct value. 
reason is that the business has decided that departments will have different quotas.

### Actual behavior 
When running the command with a user's account name the command 'hangs' for a longtime (left console open for hours with no response), no value, error code or data is returned.

### Steps to reproduce behavior
As Global Admin + with Powershell 7.3.6:
connect-pnpOnline -Url "https://ORG-admin.sharepoint.com/" -interactive
Get-PnPUserOneDriveQuota -account 'FirstName.LastName@Company.com'
Get-PnPUserOneDriveQuota -account '01234567-0123-1a12-bc34-d058860692d9'
Get-PnPUserOneDriveQuota -Account 'ORG\FirstName.LastName@Company.com''
Get-PnPUserOneDriveQuota -account 'FirstName LastName'
Get-PnPUserOneDriveQuota -account 'i:0#.f|membership|FirstName.LastName@Company.com'

I have also tested with different accounts and account name / upn formats to the same result.

### What is the version of the Cmdlet module you are running?
2.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows 10 - Version	10.0.19045 Build 19045
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by zagee1** [comment]
I have the same issue

**Comment by zagee1** [comment]
the bug started at release 1.11.0
release 1.10.0 is working as expected

**Comment by sticky270** [comment]
I too have this problem. Other commands work as expected, however the Get-PnPUserOneDriveQuota command hangs exactly as described. 

While in the hung state, Fiddler shows it is continually calling every few seconds:
POST https://[tenant]-admin.sharepoint.com/_vti_bin/client.svc/ProcessQuery HTTP/1.1

Which returns a JSON response with the object type Microsoft.Online.SharePoint.TenantAdministration.SPOSitePropertiesEnumerable.

So it doesn't look like a problem with access or something being blocked. It almost looks like the requested info is being returned but the function isn't responding to it??

Would be great to see this reopened for further investigation - have gone back to using the commands in the Microsoft.Online.SharePoint.PowerShell module which are so slooow. Was hoping the PnP functions would be a better option!

**Comment by valis-nz** [comment]
Did this ever get followed up on? I have the same issue, two different machines, stable 2.12 and 2.99.37-nightly. Specifically using application auth and a cert.
App has I think all the required permissions as when it didn't, I got a different permissions based error.
Connect-PnPOnline -Url $SiteURL -ClientId $ClientID -Thumbprint $ThumbPrint -Tenant $Tenant
Connects fine and can run other get-commands, but 
_get-pnpuseronedrivequota -account someaccount@ourdomain.co.nz_
just hangs. The verbose output for the nightly has a bit more detail:
_VERBOSE: Already connect to the SharePoint Online Admin Center at 'https://ourtenant-admin.sharepoint.com/'
VERBOSE: Making call to SharePoint Online using the Client Side Object Model (CSOM)
VERBOSE: Evaluating application permissions in access token for audience SharePoint Online
VERBOSE: Access token contains the following 2 application permission scopes for resource SharePoint Online: User.ReadWrite.All, Sites.FullControl.All
VERBOSE: No required permissions have been defined on this cmdlet_

**Comment by valis-nz** [comment]
@zagee1 Yes! It sure is

**Comment by valis-nz** [comment]
Have opened effectively the same bug with the added context around Education tenant, hopefully that will get more traction:
https://github.com/pnp/powershell/issues/4543
