### ISSUE TITLE
Move-PnPFile between site collections needs multiple Connections but only supports one

### ISSUE THREAD

**Issue by zylantha** [pnp/powershell#354]
### Reporting an Issue or Missing Feature
Attempting to use Move-PnPFile to move a file between two different site collections will result in an "Access Denied" error, since the destination site requires a different connection to the source site.

### Expected behavior 
Move-PnPFile needs to support the passing of two separate Connections in order to be able to authenticate to both the source and destination site collections.

### Actual behavior 
Attempting to move between site collections where the connection is only authenticated to one of those will result in "Access Denied"

### Steps to reproduce behavior
$SrcConnection  = Connect-PnPOnline -Url "mysite.sharepoint.com/sites/Sourcesite" -UseWebLogin -ReturnConnection

Move-PnPFile -SourceURL "Documents/test.pdf" -TargetUrl "/sites/Destinationsite/Documents" -AllowSchemaMismatch -AllowSmallerVersionLimitOnDestination -Connection $SrcConnection

### What is the version of the Cmdlet module you are running?
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.3.0      PnP.PowerShell                      {Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add-...
Manifest   1.2.0      PnP.PowerShell                      {Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add-...

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows

**Comment by veronicageek** [comment]
> since the destination site requires a different connection to the source site

What difference? So we can try reproduce in the same manner

**Comment by zylantha** [comment]
There is no difference in the _account_ that's required.  The account I'm using is site collection admin on both source site collection and destination site collection, however it is not SharePoint administrator.  

However if the _Connection_ that I use was connected to the source site collection, then I can move the file within that site collection - but not to the destination site collection, because it returns "Not authorised".  If the Connection was linked to the top level (i.e. mysite.sharepoint.com) then I can't even move within the source site collection (my account is not an admin on the top level, only on the two individual site collections, i.e. /sites/Sourcesite and /sites/Destinationsite).

**Comment by veronicageek** [comment]
@zylantha - You don't need to specify the `-Connection` parameter when you move the file.
I've tested with an account who's Site Collection Admin (_not Global Admin, not SharePoint Admin_) on both sites (source & destination), and it worked fine. Just use `Connect-PnPOnline` on your source site.


```powershell
Connect-PnPOnline -Url https://<Tenant-Name>.sharepoint.com/sites/SitePnP1 -Credentials (Get-Credential)

Move-PnPFile -SourceUrl "Shared Documents/SPO Roadmap.pptx" -TargetUrl "/sites/SitePnP2/TargetLibrary" -AllowSchemaMismatch -AllowSmallerVersionLimitOnDestination -Force
```

**Comment by zylantha** [comment]
Connect-PnPOnline with "-Credentials (Get-Credential)" does not work and returns:
Connect-PnPOnline : AADSTS65001: The user or administrator has not consented to use the application with ID
'31359c7f-bd7e-475c-86db-fdb8c937548e' named 'PnP Management Shell'. Send an interactive authorization request for this user and resource.

Connect-PnPOnline with "-Interactive" does not work as it asks for site collection admin (I don't know why PowerShell keeps suggesting that I should use "-Interactive" "which provides better functionality" when it just does not work).

I am referring to authentication obtained using "-UseWebLogin" as I originally reported, as this is the only authentication type that works in our environment.

**Comment by zylantha** [comment]
Here is a me authenticating to the "SOURCE" site (subsite of "Customers") with -UseWebLogin and trying to move a file in "WorkOrders" library to the "Contracts" library in "DESTINATION" site and it failing.  Before I try to move it between sites, I move it within the same site to the same library (with no issues) to prove I have access.

I then try doing the reverse, authenticating to the "DESTINATION" site (same credentials - it never even asks for any) and try to move a file in that Contracts library (which was the destination) back to the "SOURCE" site ("WorkOrders" library) and it failing in the same way.  Again, before moving it between sites, I move it within the same site and library to prove I have access.

Note that before the upgrade to 1.3.0 it was returning better error messages ("Access Denied") - now it is just returning "WriteError".

`PS C:\> Connect-PnPOnline -Url https://MYSITE.sharepoint.com/sites/customers/SOURCE -UseWebLogin
WARNING: Consider using -Interactive instead, which provides better functionality. See the documentation at
https://pnp.github.io/powershell/cmdlets/connect-pnponline.html#interactive-login-for-multi-factor-authentication
PS C:\> Move-PnPFile -SourceUrl "WorkOrders/test.txt" -TargetUrl "WorkOrders/test1.txt" -AllowSchemaMismatch -AllowSmallerVersionLimitOnDestination -Force
PS C:\> Move-PnPFile -SourceUrl "WorkOrders/test1.txt" -TargetUrl "/sites/DESTINATION/Contracts" -AllowSchemaMismatch -AllowSmallerVersionLimitOnDestination -Force
Move-PnPFile :
ServerErrorTraceCorrelationId: 66f9af9f-e0df-b000-cec4-31893c430327
At line:1 char:1
+ Move-PnPFile -SourceUrl "WorkOrders/test1.txt" -TargetUrl "/sites/Con ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Move-PnPFile], Exception
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Files.MoveFile
PS C:\> Connect-PnPOnline -Url https://MYSITE.sharepoint.com/sites/DESTINATION -UseWebLogin
WARNING: Consider using -Interactive instead, which provides better functionality. See the documentation at
https://pnp.github.io/powershell/cmdlets/connect-pnponline.html#interactive-login-for-multi-factor-authentication
PS C:\> Move-PnPFile -SourceUrl "Contracts/dest.txt" -TargetUrl "Contracts/dest1.txt" -AllowSchemaMismatch -AllowSmallerVersionLimitOnDestination -Force
PS C:\> Move-PnPFile -SourceUrl "Contracts/dest.txt" -TargetUrl "/sites/customers/SOURCE/WorkOrders" -AllowSchemaMismatch -AllowSmallerVersionLimitOnDestination -Force
Move-PnPFile :
ServerErrorTraceCorrelationId: 87f9af9f-70e8-b000-cedd-5511f2c40004
At line:1 char:1
+ Move-PnPFile -SourceUrl "Contracts/dest.txt" -TargetUrl "/sites/custo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Move-PnPFile], Exception
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Files.MoveFile
`

**Comment by erwinvanhunen** [comment]
@zylantha : The UseWebLogin functionality is built on a very instable premise: cookie based auth which we acquire using an embedded webbrowser in which you authenticate. Initially we took it away in 1.0 but because many people want to use it (for historical and MFA reasons as there was no alternative until we introduced `-Interactive`) we hesitantly returned the functionality.

The UseWeblogin method only allows you to auth towards SharePoint. However, the APIs we use behind the scenes are changing and we have to move over to for instance using the Microsoft Graph to get our data. The Microsoft Graph API resides on a different URL (https://graph.microsoft.com vs https://yourtenant.sharepoint.com) and as a result the cookies acquired for your SharePoint site do not work towards the Graph (cookies work only towards the URL they have been acquired for/retrieved from). Besides that, the Microsoft Graph in general does not accept cookie based auth. When you use -Interactive we acquire access using the supported Azure AD OAuth2 methods and the result is that we can access both your SharePoint environment -and- the Microsoft Graph. There is unfortunately nothing we can change about this: Microsoft has decided to follow this path when it comes to authenatication and we cannot do anything else but to follow.

The administrative request is only required -once- in order to register a clientid in your Azure AD. This means that an entry is added to your Azure AD with a known Id (the Id of the PnP Management Shell), you can however also register your own Azure AD Application if you want, but that goes a bit beyond the scope of this issue. 

When you use -Interactive to login we acquire an access token using that Id from the Azure AD. That token is representing you, not the app (e.g. it's a delegate token). So while the act of registering the app id in the Azure AD requires administrative rights, later requests do not. This also means that access tokens acquired using this method can only do what the user can do that acquired it. For instance, if you do not have access to a certain site, you will not by magic suddenly receive access to that site. E.g. standard SharePoint security still applies. 

Coming back to your issue:

I just tried moving a file using when connected using -UseWebLogin between two site collections and succeeded without a problem.  

Regarding the error message you received: we did not change the error messages being thrown between 1.2 and 1.3. Which sounds to me there is actually a write error that is causing the issue. Something in the site access, library, site level, document level that prevents you from moving the file there?

A bit of detail of the inner workings of the cmdlet:

If the target site is the same as the source site we use a basic method of copying/moving as SharePoint allows very easily to copy or move a file within a site. However, between sites is a different story. If not tried yet, can you try to move the file using the web interface? (Right click on the file, select `Move To`). That functionality uses the same APIs behind the scenes that we use to move/copy a file between site collections.

**Comment by veronicageek** [comment]
Meanwhile, I also re-tested with an MFA account who is only a Site Collection Admin using `-UseWebLogin` and it worked fine.

```powershell
Connect-PnPOnline -Url "https://TENANT-NAME.sharepoint.com/sites/<SiteSource>/<subsite>" -UseWebLogin
Move-PnPFile -SourceUrl "WorkOrders/Test123.docx" -TargetUrl "/sites/SiteDestination/Contracts" -AllowSchemaMismatch -AllowSmallerVersionLimitOnDestination -Force
```

**Comment by zylantha** [comment]
Thanks @erwinvanhunen a lot of what you have said makes sense.  Please be aware that - as you have seen - you can't just remove normal authentication methods that "just work" and expect to replace them with something that requires admin-level approvals - you may understand that it doesn't allow you to do anything you aren't otherwise permitted to do, but that means nothing in a corporate environment.  SharePoint was always meant to be a "citizen developer" platform - and as soon as something needs ICT approval you halt everything and then every citizen developer needs a business case to move forward just to be able to use the tool.  IMHO the move to requiring Azure app registration is ultimately bad and totally counterproductive to the original ideals of the platform.

In any event, to answer your specific questions -
- I swear I was receiving an error message of "Access Denied" initially (I was even googling this error message in this situation to find out what was going), however this was replaced with the nondescript error message I quoted in the command result above at some point - and the only significant thing that seemed to change was a likely upgrade from 1.2 to 1.3 (which I could only traceback through the presence of both versions on my machine).  I haven't seen this "Access Denied" error since the first day I was trying this.
- I am site collection admin in both source and destination sites, and as per the command history above, I can move a file within a library on each site (which is just renaming it really) using the API and my credentials.
- Yes I have moved files between the sites in question, manually, using the web interface.  In fact I was forced to do this manually in this way, across about 1,000 libraries across the same number of sites, over a year ago during the first migration phase.  It was insanely frustrating because every move operation required manually selecting the destination folder for every source, and then clicking through multiple warnings about there being a schema mismatch and version history difference (which there is not, btw, this is an eroneous warning).  I'm now undertaking the second phase of this migration (there are still two more to go), and now that these additional parameters (to AllowSchemaMismatch and AllowSmallerVersionLimitOnDestination) are available (they were not available 15 months ago when I did phase 1 of the migration) I would really like to be able to use this command rather than having to use the web gui which is 100x slower and 1000x more manual than executing the commands in the website.  Indeed in my current migration I have been using a combination of this web interface "move" command and OneDrive to move the files - in the absence of being able to use the PnP Powershell command, which should work by all accounts, but doesn't.

@veronicageek  It is interesting to see that this command in seemingly similar circumstances works for you, yet it still isn't working for me.  Can you shed any light on any other possible explanations of why it may not be working for me when it does for you?

I can potentially try a few other intermediate scenarios, using different site collections that I am also site collection admin for, including a move of a file between a site and a sub-web, however ultimately I need to fix this for the purposes of running this migration activity which requires it to work on those two original sites.

Thanks for your efforts.

**Comment by zylantha** [comment]
I have just tested moving a document from a site to a subsite (sub-web) within the same collection, and it fails the same way, with the same error.  I'm obviously site collection owner across the entire space here.

PS C:\Windows\System32\WindowsPowerShell\v1.0> Connect-PnPOnline -Url "https://MYTENNANT.sharepoint.com/sites/Contracting/" -UseWebLogin
WARNING: Consider using -Interactive instead, which provides better functionality. See the documentation at
https://pnp.github.io/powershell/cmdlets/connect-pnponline.html#interactive-login-for-multi-factor-authentication
PS C:\Windows\System32\WindowsPowerShell\v1.0> Move-PnPFile -SourceUrl "Contracts/dest1.txt" -TargetUrl "Test/Shared Documents1" -AllowSchemaMismatch -AllowSmallerVersionLimitOnDestination -Force
Move-PnPFile :
ServerErrorTraceCorrelationId: c9a0b09f-500b-b000-cec4-3d2aef4d751f
At line:1 char:1
+ Move-PnPFile -SourceUrl "Contracts/dest1.txt" -TargetUrl "Test/Shared ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Move-PnPFile], Exception
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Files.MoveFile

I have also tried moving it from one library into a different library _in the same site_ and it also fails.

PS C:\Windows\System32\WindowsPowerShell\v1.0> Move-PnPFile -SourceUrl "Contracts/dest1.txt" -TargetUrl "Shared Documents" -AllowSchemaMismatch -AllowSmallerVersionLimitOnDestination -Force
Move-PnPFile :
ServerErrorTraceCorrelationId: fba0b09f-90c8-b000-cedd-580ca7d4ceb4
At line:1 char:1
+ Move-PnPFile -SourceUrl "Contracts/dest1.txt" -TargetUrl "Shared Docu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Move-PnPFile], Exception
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Files.MoveFile

Finally, I tried moving it into a new filename in the same library, and it's ifne.
PS C:\Windows\System32\WindowsPowerShell\v1.0> Move-PnPFile -SourceUrl "Contracts/dest1.txt" -TargetUrl "Contracts/dest2" -AllowSchemaMismatch -AllowSmallerVersionLimitOnDestination -Force
PS C:\Windows\System32\WindowsPowerShell\v1.0>

So it would seem to be consistently failing when trying to move anywhere outside of the library in which the document is stored.

And just for good measure I tried moving a file between two other libraries not involving the one that has always been the destination or source in all my other tests, and got the same error -

PS C:\Windows\System32\WindowsPowerShell\v1.0> Move-PnPFile -SourceUrl "Shared Documents/field alignment.png" -TargetUrl "Test/Shared Documents1" -AllowSchemaMismatch -AllowSmallerVersionLimitOnDestination -Force
Move-PnPFile :
ServerErrorTraceCorrelationId: 22a1b09f-a016-b000-cec4-3506a9bd4d3c
At line:1 char:1
+ Move-PnPFile -SourceUrl "Shared Documents/field alignment.png" -Targe ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Move-PnPFile], Exception
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Files.MoveFile

Is there a debug option that I can enable to spit out more detailed failure info?
