### ISSUE TITLE
[BUG] Get-PnPTenantSite does not return information segment

### ISSUE THREAD

**Issue by JasBK** [pnp/powershell#3542]
I see the Set-PnPTenantSite cmdlet can set the information barriers segment on a site.
I have tried numerous methods but cannot get the current property using Get-PnPTenantSite.

I tried Get-PnPTenantSite -Identity -Detailed | Select InformationSegment

Looking for the equivalent to Get-SPOSite -Identity | Select InformationSegment

### Reporting an Issue or Missing Feature
Property seems to be missing

### Expected behavior 
Return information barrier segment

### Actual behavior 
No data is returned

### Steps to reproduce behavior
Get-PnPTenantSite -Identity -Detailed | Select InformationSegment

### What is the version of the Cmdlet module you are running?
7.3.5

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by CallumCrowley** [comment]
@JasBK this sounds very similar to #3356, where the underlying SharePoint CSOM call is not returning the values requested. If this is the case, then only Microsoft will be able to help (only they can make changes/fixes to the CSOM/APIs that PnP.PowerShell relies upon).

@gautamdsheth do you know if this is the case?

**Comment by KoenZomers** [comment]
The information is returned by CSOM but not passed on in our PnP model. Will add it.

**Comment by gautamdsheth** [comment]
hi @JasBK , this has been fixed and will be available in tomorrow's nightly builds as well as the next major one when we release it.

**Comment by gautamdsheth** [comment]
@CallumCrowley - hmm, true, sounds quite similar to older issues . I think it would work if you specify the Identity parameter. Maybe wont return values for all sites in which case only MS support can help.

**Comment by CallumCrowley** [comment]
@KoenZomers thanks! I hadn't had a chance to check, good to hear that CSOM is actually returning the information.

@gautamdsheth it's understandable that MSFT won't always return everything without the information being explicitly requested (I guess it's related to performance). I think the difficulty is changes to the endpoints without us realising.
