### ISSUE TITLE
[BUG] New-PnPAzureCertificate adds hostname to SAN

### ISSUE THREAD

**Issue by JMyklebust** [pnp/powershell#3546]
### Reporting an Issue or Missing Feature
The New-PnPAzureCertificate cmdlet is creating certificates containing the hostname of the generating computer in the SAN field.

### Expected behavior 
Since we don't specify any SAN data (in fact we are missing av parameter for this?). No data should be in the SAN field.  
Or alternatively the same data that is put in the CommonName parameter should be put in SAN.

### Actual behavior 
The SAN field is containing both "localhost" and the hostname of my computer.
![image](https://github.com/pnp/powershell/assets/48317811/25801c5c-b7da-4aa2-b7c9-fb076adfab5c)

### Steps to reproduce behavior
Generate a certificate and check the public part afterwards:
`` New-PnPAzureCertificate -CommonName "Testname" -OutCert .\cert.crt``

### What is the version of the Cmdlet module you are running?
version 2.2.0 (Running on PowerShell 7.3.8)

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by KoenZomers** [comment]
Good point @JMyklebust. Adding `-SanNames` to the cmdlet through [this PR](https://github.com/pnp/powershell/pull/3555) to allow you to influence the SAN.

**Comment by JMyklebust** [comment]
Sounds reasonable to implement this in a non-breaking way. 

Though I am a bit unsure about the why the default SANs are there in the first place?
As far as i know they don't really have much purpose unless you are hosting a service with either the hostname of your computer or serving on localhost.

For just plain authentication cert auth with App registrations the SAN is not really used at all?

Either way being able to influence the SAN should be good enough.

**Comment by KoenZomers** [comment]
Not sure why they are there in the first place. Technically, for an app registration, they serve no purpose. Might be that the initial goal of this cmdlet was to also support using it for hosting a development webserver locally over HTTPS or something. For backwards compatibility, it would be safest to keep the default as is. With the added parameter you can adjust or leave out the SAN part as a whole.
