### ISSUE TITLE
[BUG] Get-PnPAzureADUser: Delta parameter does not work with Filter

### ISSUE THREAD

**Issue by AndersRask** [pnp/powershell#3547]
### Reporting an Issue or Missing Feature
Either parametersets are wrong, or Delta parameter does not work with Filter

### Expected behavior 
Since they are part of same parameterset (ParameterSet_DELTA) Filter and Delta should work together (i can also see in PnP.Framework that the method public static Model.UserDelta ListUserDelta uses both Filter and Delta as parameters).

### Actual behavior 
Using Filter with Delta gives an error
get-pnpAzureADUser -Filter "startsWith(displayName,'Adele')"    # this works
get-pnpAzureADUser -Filter "startsWith(displayName,'Adele')" -Delta   # this fails with Request_UnsupportedQuery

The wording on Delta parameter hints on, that all users should be returned, but this is not reflected in the implementation both in cmdlet parameterset and in ListUserDelta method in PnP.Framework:
-Delta [<SwitchParameter>]: "Retrieves all users and provides a SkipToken delta token to allow to query for changes ..."

### Steps to reproduce behavior
Call Get-PnPAzureADUser with both filter and delta parameter

### What is the version of the Cmdlet module you are running?
2.2.23     nightly

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by KoenZomers** [comment]
Looks to be a limitation in Microsoft Graph. It is described here: https://learn.microsoft.com/en-us/graph/api/user-delta?view=graph-rest-1.0&tabs=http#odata-query-parameters . I will update our documentation to make mention of this as well.

**Comment by KoenZomers** [comment]
Documentation has been updated. Closing this issue.
