### ISSUE TITLE
Get-PnPHubSiteChild: The attempted operation is prohibited because it exceeds the list view threshold.

### ISSUE THREAD

**Issue by Nibushi** [pnp/powershell#356]
When working on a Tenant with a large number of hubsites and sites, Running Get-PnPHubSiteChild returns the following error message:
Get-PnPHubSiteChild: The attempted operation is prohibited because it exceeds the list view threshold.

The tenant has 7811 site collections. Is the issue that the number of site collections is above 5000?

I am running PnP.PowerShell v1.3.0.

The command does run successfully on a Tenant where there are only a few hundred site collections.

**Comment by erwinvanhunen** [comment]
Yes, that is indeed the issue. We retrieve the list of hubsites from a list in the tenant administration site. We'll work on a fix.

**Comment by Nibushi** [comment]
Thanks for the update. I can work around the issue at the moment.

**Comment by erwinvanhunen** [comment]
We fixed the issue and it will be available in the next available release.

**Comment by Nibushi** [comment]
That's customer service for you :-)
