### ISSUE TITLE
[FEATURE] Teams channel moderation preferences

### ISSUE THREAD

**Issue by NizarGrindi** [pnp/powershell#3563]
It will be useful to manage channel moderation preferences via PowerShell as discribed here [userNewMessageRestriction](https://learn.microsoft.com/en-us/graph/api/resources/channelmoderationsettings?view=graph-rest-beta#:~:text=%2C%20unknownFutureValue.-,userNewMessageRestriction,-userNewMessageRestriction)

![image](https://github.com/pnp/powershell/assets/8698368/5b46d75b-6235-4ed6-84fc-302354bb4844)

**Comment by KoenZomers** [comment]
Will be added through https://github.com/pnp/powershell/pull/3580
