### ISSUE TITLE
[BUG] Get-PnPAzureADUser does not account for apostrophe's in UPN

### ISSUE THREAD

**Issue by danielcecil** [pnp/powershell#3569]
### Reporting an Issue or Missing Feature
When using Get-PnPAzureADUser any apostrophe's in the userPrincipalName are not escaped.

https://github.com/pnp/powershell/blob/0ac1939e7c871f67b32fee2eb795fe393d7161d3/src/Commands/Utilities/AzureAdUtility.cs#L86

### Expected behavior 
The Azure AD user is returned when passing in a userPrincipal name of a user (Member or Guest).

### Actual behavior 
`Get-PnPAzureADUser : Code: BadRequest
Message: Invalid filter clause: Syntax error at position 49 in 'userPrincipalName eq 'John.O'Smith_tailspintoys.com#EXT#@contoso.onmicrosoft.com''.`

### Steps to reproduce behavior
1. Create an Account with an apostrophe in the userPrincipalName
2. Run `Get-PnPAzureADUser -Identity "john.o'smith@contoso.com"`

### What is the version of the Cmdlet module you are running?
2.2.125
1.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by KoenZomers** [comment]
PR has been merged. Will be in tomorrow's prerelease.
