### ISSUE TITLE
[BUG] Issue with Document Sets Not Inheriting Properties on Communication Site via PnP PowerShell and XML Template

### ISSUE THREAD

**Issue by J3D1m0** [pnp/powershell#3586]
##Description:
When deploying Document Sets on a SharePoint Communication Site using PnP PowerShell along with an XML template, the Document Sets are not inheriting properties into the contained files as expected.

##Steps to Reproduce:

Deploy a Document Set to a SharePoint Communication Site using PnP PowerShell.
The XML template created by powershell before.
After deployment, the Document Set does not inherit properties to its contained files.

##Expected Behavior:
The Document Sets should inherit specified properties into the contained files, as is the standard functionality.

##Actual Behavior:
The properties are not being inherited by the files within the Document Sets.

##Environment:

PnP PowerShell Version: PnP.PowerShell 1.11.0
SharePoint Online
Communication Site

EDIT: Tests in other tenants with other versions of pnp return the same result. Even if the inheritance is activated , the properties wont inherit to the files in the document sets.

**Comment by diver7** [comment]
@J3D1m0 
When you say " the Document Set does not inherit properties to its contained files." are referring to the metadata columns on the files? We just started seeing an issue a couple of weeks ago where we have a document set that is configured to share some columns with the files contained within it but they are not being populated on the files when uploaded. I think this is the same issue you are describing. Can you confirm?

**Comment by J3D1m0** [comment]
@diver7  yes i can confirm. we created round about 400 sites and deployt via pnp powershell the xml with the document sets and now the shared columns dont get the values from the set.

**Comment by diver7** [comment]
@J3D1m0 
Thanks for the confirmation. I created a new issue on the pnpframework repo because I saw some instructions that told me that issues with this pnp command should be there. Hopefully it will get some attention. Here is the link: https://github.com/pnp/pnpframework/issues/948

**Comment by gautamdsheth** [comment]
Closing the issue here since it is a PnP Framework issue. Once it is fixed there, it will be automatically fixed in here.
