### ISSUE TITLE
Missing "assignments" for Add-PnPPlannerTask

### ISSUE THREAD

**Issue by raclettierer** [pnp/powershell#359]
Currently I can't create or update a task for planner with assigned users. 

Extend the command with a collection of user like **UserPrincipalNames** . Same for Update-PNPPlannerTask

`Add-PnPPlannerTask -Group "Marketing" -Plan "Conference Plan" -Bucket "Todos" -Title "Design booth layout" -UserPrincipalNames "user01@yourdomain.com", "user02@yourdomain.com"`

API Graph: https://docs.microsoft.com/en-us/graph/api/planner-post-tasks?view=graph-rest-1.0&tabs=http
Code Sample: https://github.com/sandytsang/PlannerModule

**Comment by erwinvanhunen** [comment]
We merged functionality to both Add-PnPPlannerTask and Set-PnPPlannerTask. It will be available in 1.3.17-nightly tomorrow.
