### ISSUE TITLE
Copy-PnPFile  ERROR: A command that prompts the user failed because the host program or the command type does not support user interaction

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/powershell#3592]
### Reporting an Issue or Missing Feature
Issue with `Copy-PnPFile -SourceUrl $Request.Body.sourceUrl -TargetUrl $targetUrl -Overwrite -Connection $rootConn`
This is in an Azure function code so there is no user interaction.
The connection is:
```
$rootConn = Connect-PnPOnline -Url ("https://" + $env:AADDomain ) -Tenant $env:TenantId -ClientId $env:ClientId  -CertificateBase64Encoded $env:CertificatePFX -CertificatePassword $CertificatePassWord -ReturnConnection
```
### Expected behavior 
it should copy the file from source to destination

### Actual behavior 
Shows error
`ERROR: A command that prompts the user failed because the host program or the command type does not support user interaction`
### Steps to reproduce behavior
```
param($Request, $TriggerMetadata)
Import-Module -Name PnP.PowerShell
$CertificatePassWord = (ConvertTo-SecureString -AsPlainText $env:CertificatePassWord -Force) 
$rootConn = Connect-PnPOnline -Url ("https://" + $env:AADDomain ) -Tenant $env:TenantId -ClientId $env:ClientId  -CertificateBase64Encoded $env:CertificatePFX -CertificatePassword $CertificatePassWord -ReturnConnection
#    $ProjectNumber = $Request.Body.ProjectNumber
Write-Host $rootConn.Url
Write-Host $Request.Body.sourceUrl  # the full path to the file
Write-Host $Request.Body.targetProjectNumber #": "2222.222"
$targetUrl = "/teams/"+$Request.Body.targetProjectNumber +"/DPCDocuments"
Copy-PnPFile -SourceUrl $Request.Body.sourceUrl -TargetUrl $targetUrl -Overwrite -Connection $rootConn

```
### What is the version of the Cmdlet module you are running?
2.2.0
### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [X ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
This is by design.

You need to specify `-Force` parameter in such a case to avoid user confirmation prompt

https://pnp.github.io/powershell/cmdlets/Copy-PnPFile.html
