### ISSUE TITLE
[BUG] New-PnPSite not working with HubSiteID > Unauthorized

### ISSUE THREAD

**Issue by wfi-jonas** [pnp/powershell#3594]
### Reporting an Issue or Missing Feature
I'm unable to run New-PnpSite when providing a hubSiteID. When I run it without providing the HubSiteID, it works. I have the SharePoint Admin role active and in the SharePoint admin center I can perform this action.

### Expected behavior 
Being able to assign a site to a hub during creation.

### Actual behavior 
Line |
  68 |      New-PnPSite -Type $SiteType -Title $SiteTitle -url $SiteURL -Time …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"error":{"code":"-2147024891, System.UnauthorizedAccessException","message":"Attempted to perform an unauthorized operation."}}

### Steps to reproduce behavior
Import-Module -Name PnP.PowerShell
Connect-PnPOnline https://orgname-admin.sharepoint.com -Interactive
New-PnPSite -Type $SiteType -Title $SiteTitle -url $SiteURL -TimeZone $DefaultTimeZone -Lcid $Lcid -SiteDesignId $SiteDesignId -HubSiteId $HubSiteID

### What is the version of the Cmdlet module you are running?
2.2.13

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by wfi-jonas** [comment]
I'll try again tomorrow with the latest Nightly

**Comment by wfi-jonas** [comment]
tested in 2.2.136, same issue

**Comment by wfi-jonas** [comment]
Add-PnPHubSiteAssociation after creation works fine

**Comment by gautamdsheth** [comment]
hi @wfi-jonas - no issues at all with hubsiteid parameter :

<img width="960" alt="image" src="https://github.com/pnp/powershell/assets/8832018/f5d5d44b-5f46-47d7-9a61-85361093f417">

**Comment by gautamdsheth** [comment]
Closing this due to lack of response and unable to reproduce it.
