### ISSUE TITLE
[BUG] New-PnPSite always throws 'Object reference not set to an instance of an object'

### ISSUE THREAD

**Issue by AlyaKoni** [pnp/powershell#3609]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
New-PnPSite should create a new TeamSite without an error

### Actual behavior 
Error: New-PnPSite: Object reference not set to an instance of an object.

### Steps to reproduce behavior
```
$adminCon = Connect-PnPOnline -Tenant $AlyaTenantName -AzureEnvironment $AlyaPnpEnvironment -Url $TenantAdminUrl -ReturnConnection -Interactive
New-PnPSite -Connection $adminCon -Type "TeamSite" -Title $title -Alias "$($siteUrl)" -SiteAlias "$($siteUrl)" -Lcid $lcid -TimeZone $tmzId.Id -Description $description -Wait
```
Used parameters does not play any role. Tried all except HubSite

### What is the version of powershell you are running?
```
Name                           Value
----                           -----
PSVersion                      7.3.10
PSEdition                      Core
GitCommitId                    7.3.10
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### What is the version of the Cmdlet module you are running?
```
ModuleType Version    PreRelease Name                                PSEdition
---------- -------    ---------- ----                                ---------
Manifest   2.2.0                 PnP.PowerShell                      Desk      
```

### Which operating system/environment are you running PnP PowerShell on?
Windows

**Comment by reinoutD** [comment]
Hi,

I have the same problem. I use Powershell version 7.4.0

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
``` 
And PnP.Powershell version:
```powershell
Version              Name                                Repository           Description
-------              ----                                ----------           -----------
2.2.0                PnP.PowerShell                      PSGallery            Microsoft 365 Patterns and Practices PowerShell Cmdlets
``` 

When i try to create a Communication site it doesn't give me any problem:
`New-PnPSite -Connection $conn -Type CommunicationSite -owner $Owner.UserPrincipalName -Title $Hub.Title -Url $Hub.URL -Description "Hub Site voor $($Hub.Title)" -Lcid "1043" -TimeZone UTCPLUS0100_AMSTERDAM_BERLIN_BERN_ROME_STOCKHOLM_VIENNA -Wait`

However if i try to create a TeamSite is gives me the error Object reference not set to an instance of an object:
`New-PnPSite -Connection $conn -Type TeamSite -Title $Child.Title -owner $Owner.UserPrincipalName -alias $Child.BaseName -Description "Child Site voor $($Child.Title)" -Lcid "1043" -TimeZone UTCPLUS0100_AMSTERDAM_BERLIN_BERN_ROME_STOCKHOLM_VIENNA -Wait`

I connect using a registered app with certificate:
`$Conn = Connect-PnPOnline -Url $url -Tenant $InitialDomain -ClientId $clientId -Thumbprint $CertThumbPrint -ReturnConnection`

**Comment by gautamdsheth** [comment]
hi @reinoutD , @AlyaKoni - can't reproduce the issue :

<img width="949" alt="image" src="https://github.com/pnp/powershell/assets/8832018/d56b9d7a-26f0-45b4-bcc2-79f04f175967">


Can you please update to the latest 2.3.0 and check if it still happens ?

**Comment by reinoutD** [comment]
Hi Gautamdsheth,

Thank you for your answer. Here a fast update, after updating to the new version 2.3.0 we got troubles to login with Connect-MgGraph. We use both modules in the same script. So we updated that to, however it seems that MgGraph and PnP PowerShell don't like each other. We are still researching what is happingen.

**Comment by AlyaKoni** [comment]
With 2.3.0 it's working now. Thanks for the fix.
