### ISSUE TITLE
[BUG]OfficeDevPnP.Core.Enums.SharePointTheme is undeclared

### ISSUE THREAD

**Issue by sathya-bhat** [pnp/powershell#361]
I have a mapping function for OOTB theme, and this is failing with 'Unable to find type 'OfficeDevPnP.Core.Enums.SharePointTheme'

Is this enum deprecated or mapped to a new name?

### What is the version of the Cmdlet module you are running?
1.3.14-nightly

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ x] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
It has mapped to a new name since we released 1.0:

PnP.Framework.Enums.SharePointTheme.
