### ISSUE TITLE
Batching - managed metadata / taxonomy fields - do not query on Add-PnPListItem

### ISSUE THREAD

**Issue by evlo** [pnp/powershell#363]
When using `Add-PnPListItem` with `Batch` specified and item having managed metadata / taxonomy field value specified (term name, not guid), there are still http requests made by PnP.Powershell to get **GUID** for term that is set in `Add-PnPListItem` `Values`

Ideal solution would be to get GUIDs for the terms specified by name in one BATCH before executing BATCH that actually adds items to the list.

This is mostly nice to have thing as I imagine this would be quite hard to implement.

**Comment by erwinvanhunen** [comment]
Actually it's fixed already in the latest nightly :-) If you install 1.3.16-nightly you'll notice we cache information for managed metadata fields. Batching the requests for all terms will unfortunately cause a large overhead in processing. The way it works now is:

Lookup guid and label for term and cache
Add item to batch
Check if guid and label has been cached, if not, retrieve info and add to cache, if yes, use from cache.
Add item to batch

So if you add hundreds of items to a list which use the same taxonomy terms you'll see only a few calls being made.
