### ISSUE TITLE
[BUG] Set-PnpDefaultColumnValues Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by upcreek** [pnp/powershell#3636]
Please see this closed bug for details on the issue: [https://github.com/pnp/powershell/issues/2143](https://github.com/pnp/powershell/issues/2143). The original poster has many details, including steps to reproduce.

The issue is still occurring on PowerShell 7.2.5, PnP v2.3.0.

I'm running on Windows.

**Comment by veronicageek** [comment]
Reopened #2143.
