### ISSUE TITLE
[BUG] Results from Invoke-PnPSPRestMethod when calling API RenderListDataAsStream  no longer displays values of the Rows

### ISSUE THREAD

**Issue by pmatthews05** [pnp/powershell#364]
### Reporting an Issue or Missing Feature
Back in version 1.2.0 when calling Invoke-PnPSPRestMethod against the API 
`
/_api/web/lists/GetbyTitle('$ListName')/RenderListDataAsStream"
`
The output was:
| Name  |                        Value|
|---- |                          -----|
|Row                          |  [{…|
|FolderPermissions           |   0x7ffffffffffbffff|
|ForceNoHierarchy           |    1|
|RowLimit                      | 1000|
|FilterLink                    | ?|
|LastRow                     |   2|
|HierarchyHasIndention| |
|CurrentFolderSpItemUrl| |
|FirstRow                       |1|

I was able to get the Rows, by calling ```$results.Row.ToString() | ConvertFrom-Json```

There seemed to be a BUG #188 fixed by @erwinvanhunen that seem to relate to this problem, and it is after this bug was fixed that the version 1.2.7-nightly build and above of PNP.PowerShell the results do not have any results in the Row. Also the results display differently.

| | |
|--|--|
|Row               |      {}|
|FirstRow               | 1|
|FolderPermissions     | 0x7ffffffffffbffff|
|LastRow                | 2|
|RowLimit               | 1000|
|FilterLink             | ?|
|ForceNoHierarchy       | 1|
|HierarchyHasIndention  | |
|CurrentFolderSpItemUrl | |

The $result.Row is always empty.

### Expected behavior 
To be able to return all the rows using the RenderListDataStream and Invoke-PnPSPRestMethod.

### Actual behavior 
With versions 1.2.7-nightly and above there are never any results returned for Rows.

### Steps to reproduce behavior
I have put together a script [Get-AllItems.ps1](https://gist.github.com/pmatthews05/3b2246f7349a4be3ff8a4b63bbc6346f) which currently works with V1.2.0.

If you are already doing the JSON convertions because you are using a different JSON Serialization engine, then I'm happy to update my script to work, however, I believe your JSON conversion isn't going down enough levels, for this API to bring back the Row Results.

### What is the version of the Cmdlet module you are running?
|ModuleType |Version |   PreRelease |Name| Working |
|----------| -------|    ----------| ----| ---- |
|Manifest |  1.3.16 |    nightly |   PnP.PowerShell | false |
|Manifest |  1.2.0  |            |  PnP.PowerShell| true |

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
I actually noticed it too yesterday but haven't had time to look at it in detail too see what's happening behind the scenes.

**Comment by erwinvanhunen** [comment]
I merged a fix now. Please test the nightly release of tomorrow (1.3.17-nightly)

**Comment by pmatthews05** [comment]
I have tested with the latest version and all seems to be OK now. Thank you.
