### ISSUE TITLE
Set-PnPUserProfileProperty: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided

### ISSUE THREAD

**Issue by saurav2107** [pnp/powershell#3641]
### Reporting an Issue or Missing Feature
Getting below error while trying to Set Profile Property at the same time Get property value is working fine.

<img width="798" alt="image" src="https://github.com/pnp/powershell/assets/1011594/a7ffcb3e-0492-4dda-9053-3f7948d056e3">

Set-PnPUserProfileProperty: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided

### Expected behavior 
Command should update the profile property.

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

<img width="300" alt="image" src="https://github.com/pnp/powershell/assets/1011594/75503a74-eb77-4cee-ae26-d6abbc106f6c">

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows

**Comment by gautamdsheth** [comment]
This is the correct error, you need to specify values as mentioned here in docs, check example section. You are specifying PropertyName , PropertyType, PropertyValue which is incorrect:

https://pnp.github.io/powershell/cmdlets/Set-PnPUserProfileProperty.html
