### ISSUE TITLE
[BUG] Set-PnPTenant -ConditionalAccessPolicy AllowLimitedAccess is missing options for LimitedAccessFileType

### ISSUE THREAD

**Issue by pollev** [pnp/powershell#3667]
The command Set-PnPTenant supports the flag -ConditionalAccessPolicy policy for configuring App-Enforced policies through Conditional Access. This Flag supports the value 'AllowLimitedAccess' in which case several additional flags can be specified to configure in which way access should be limited.

One of those flags is supposed to be 'LimitedAccessFileType', which should have the possible values 'OfficeOnlineFilesOnly', 'WebPreviewableFiles' and 'OtherFiles'. You can find this documented here: https://learn.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices#advanced-configurations

Currently this flag is not supported. I believe instead there is still support for the (no longer supported) 'AllowDownlownloadingNonWebViewableFiles' flag.

Could you look into this issue and update the command accordingly?
Greatly appreciated!

**Comment by gautamdsheth** [comment]
hi @pollev , this scenario is already supported .

You need to specify it as : 

```
Set-PnPTenant -ConditionalAccessPolicy AllowLimitedAccess -LimitedAccessFileType OfficeOnlineFilesOnly
```

The `LimitedAccessFileType` supports 3 values `OfficeOnlineFilesOnly, OfficeOnlineFilesOnly and OtherFiles`

Hopefully this answers your scenario

**Comment by YenNantes** [comment]
Hi
I'm using the lastest version of the PnP module but this switch does not exists:

 Set-PnPTenant -LimitedAccessFileType WebPreviewableFiles
Set-PnPTenant: A parameter cannot be found that matches parameter name 'LimitedAccessFileType'.

The official doc also does not mention this parameter: https://pnp.github.io/powershell/cmdlets/Set-PnPTenant.html
