### ISSUE TITLE
[BUG] Issues with import-module for version 2.2.0 after updating and removing 2.3.0

### ISSUE THREAD

**Issue by cdquinn** [pnp/powershell#3688]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Warning about version 2.3.0 and Powershell 7.2

### Expected behavior 
First I did not expect that 7.2 would be required when performing the update on the sub version of a module, This should have been a new version number like 3.0.
Second, I now have issues running version 2.2.0 even after I uninstalled 2.3.0. The warning is below in the behavior.

### Actual behavior 
After uninstalling all versions of pnp.powershell and re-installing using the following command:
Install-Module -Name PnP.PowerShell -RequiredVersion 2.2.0 -Force -Scope AllUsers
I get the below error when performing the following:
Import-Module -Name pnp.powershell -RequiredVersion 2.2.0
**Import-Module : Could not load file or assembly 'System.Management.Automation, Version=7.2.0.0, Culture=neutral, PublicKeyToken=<redacted>' or one of its dependencies. The system cannot find the file specified.**

This makes me believe that it is trying to use version 7.2 of powershell now. 
This is a server running automation and installing 7.2 of powershell is not possible at this time.

### Steps to reproduce behavior
See above

### What is the version of the Cmdlet module you are running?
2.2.0 (after installing and uninstalling 2.3.0)

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by jackpoz** [comment]
According to https://github.com/pnp/powershell/releases/tag/v2.1.0 , PowerShell 7.2.x has been the required version since PnP PowerShell 2.1.0 .
The version you should try to install is https://github.com/pnp/powershell/releases/tag/v2.1.1 then (as it contains a minor fix right after 2.1.0)

**Comment by veronicageek** [comment]
If you want to use v.`2.x` then you need PS `7.2` or above. We don't support PowerShell 5.1 anymore. 
If you can't use PowerShell 7, then the latest PnP PowerShell version will be `1.12.0`.
