### ISSUE TITLE
[FEATURE] Add TargetAudience to Add-PnpNavigationNode

### ISSUE THREAD

**Issue by Marijnsomers** [pnp/powershell#369]
**Is your feature request related to a problem? Please describe.**
We are setting up multiple sites for students with PowerShell. We would love to be able to hide/show navigation items to be targeted towards a specific audience.

**Describe the solution you'd like**
The solution for us would be to have an extra parameter to the Add-PnpNavigationNode "-TargetAudience" where we could add M365 Groups.

**Describe alternatives you've considered**
This is now done manually, but that is not scalable.

**Additional context**

**Comment by erwinvanhunen** [comment]
While this feels like a relatively small change, it's unfortunately not. We would have to change our whole internal navigation processing away from using CSOM to using the Microsoft Graph. We will make this change, however, it will cause a breaking change, which means it will not happen anytime soon unfortunately.

**Comment by furtivesock** [comment]
Hello!
Is there any existing options to do that? With the CSOM or anything?
I was struggling to find an alternative, unsuccessfully.
