### ISSUE TITLE
[BUG] Get-PNPList, Url property not filterable

### ISSUE THREAD

**Issue by SPDEVGUY** [pnp/powershell#3690]
### Reporting an Issue or Missing Feature
Issue with Get-PNPList, the default console view outputs a member "Url" which cannot be filtered on.
Suggested fix, add whatever "Url" is virtually mapped to as a member property to Microsoft.SharePoint.Client.List when being displayed as a list output to the console.

Although maybe this is a problem for Microsoft?

### Expected behavior 
Expected to be able to filter list based on url intuitively as this property is displayed, or use Url in a piped Select operation.

Get-PNPList | Select Url
Url is blank?

### Actual behavior 
![image](https://github.com/pnp/powershell/assets/3208188/e738f635-50dd-4bed-89e6-07bf3463b702)

![image](https://github.com/pnp/powershell/assets/3208188/7b1a195a-e206-4fdd-9ddb-cbc1ab989e93)
![image](https://github.com/pnp/powershell/assets/3208188/49c7278a-6fc5-4365-b966-bf5f2146371c)

### Steps to reproduce behavior

```
$lists = Get-PNPList
$docLibs = $lists | ?{($_.Url -notlike '*/Lists/*') -and ($_.Url -notlike '*/_Catalogs/*')}
$lists | Select Url

```
$docLibs still contains all lists because "Url" isn't a property despite showing up when you just run get-pnplist

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

2.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
hi @SPDEVGUY , this is by design. The URL property is for display only and is mapped to RootFolder.ServerRelativeUrl . 

Please use `RootFolder.ServerRelativeUrl` for filtering

**Comment by SPDEVGUY** [comment]
Very unintuitive.  Could be addressed with a read only property.
