### ISSUE TITLE
[BUG] Get-PnPFolder -url [PathToFolderInDocLib] results in "The object specified does not belong to a list."

### ISSUE THREAD

**Issue by SPDEVGUY** [pnp/powershell#3692]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
get-pnpfolder used on a folder within a document library by url should return that folder.

### Actual behavior 
![image](https://github.com/pnp/powershell/assets/3208188/f7884482-62f9-4009-ad1f-32e35d0b9774)

```
$parentFolderUrl = 'https://contoso.sharepoint.com/Documents/Subfolder'
$parentFolder = get-pnpfolder -url $parentFolderUrl
returns The object specified does not belong to a list.
```

### Steps to reproduce behavior
1. Have a site with a document library named Documents
2. Make a folder within Documents, custom permissions, your global SP Admin should have access.  Remove all other permissions aside from one user (that isn't your global sp admin)
3. `Get-PnpFolder -url [url to folder]`

Not sure if the permission issue is part of it or not, but my global sp admin can access the folder and content within it despite not being explicitly defined on the folder.

### What is the version of the Cmdlet module you are running?
2.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
hi @SPDEVGUY , this is by design. The `-url` parameter expects server-relative URL of the folder or site, i.e it needs to be something like `/sites/test/Shared Documents/Folder` or `/Documents/Folder`.

https://pnp.github.io/powershell/cmdlets/Get-PnPFolder.html#-url
