### ISSUE TITLE
[BUG] Problems with Get-PnPUserProfileProperty

### ISSUE THREAD

**Issue by gitulm** [pnp/powershell#3694]
### Reporting an Issue or Missing Feature
I want to get detailed information about a user:
$UserProfile = Get-PnPUserProfileProperty -Account xxx
Write-Host "User Principalname: " $UserProfile.UserProfileProperties["SPS-UserPrincipalName"]
I do this with VSC with the VSC Host 2024.0.0 and PS 7.4.1
When I do this query, I recently get the error message:
**Cannot index into a null array**
So far the code has always worked.

The code works perfectly with the legacy version of PnP.Powershell with PS 5.1

### Expected behavior 
User Principalname:  xxx@xxx.de

### Actual behavior 
Cannot index into a null array

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows

**Comment by veronicageek** [comment]
@gitulm - You can just use `SPS-UserPrincipalName` directly

<img width="891" alt="image" src="https://github.com/pnp/powershell/assets/25181757/7a74dd5a-936c-4315-93a0-4d546285b656">

**Comment by gitulm** [comment]
Where will such changes be communicated? I used the old spelling all the time until recently and from one day to the next the command no longer works with PS 7.

**Comment by gautamdsheth** [comment]
Has been documented here - https://github.com/pnp/powershell/blob/dev/MIGRATE-1.0-to-2.0.md
