### ISSUE TITLE
[BUG] Add-PnPTeamsTab -Type PowerBI

### ISSUE THREAD

**Issue by franckcdev** [pnp/powershell#3696]
### Reporting an Issue or Missing Feature
Adding a new MS Teams Tab with "Add-PnPTeamsTab" and Type PowerBI is not working as expected. The new tab is created but it cannot be configured manually.

### Expected behavior 
The tab should allow for setting up the Power BI report like it is when adding the tab manually.
![add-pnpteamstab-ExpectedBehaviour](https://github.com/pnp/powershell/assets/74403890/3c9a161b-9304-42fb-961b-5f6ae2ec171d)

### Actual behavior 
The new Tab is created with the "Ready to set up the tab?" config page 
![add-pnpteamstab-ActualBehaviour-1](https://github.com/pnp/powershell/assets/74403890/8816bd69-b3b5-4a99-b627-62ed1484f6cb)

But when clicking "Set up tab", the Power BI pop-up doesn't display anything to select the PBI report and the "Save" button is greyed out. 
![add-pnpteamstab-ActualBehaviour-2](https://github.com/pnp/powershell/assets/74403890/962c33b8-7182-40a3-aba0-d36d0b25815e)

### Steps to reproduce behavior
Add-PnPTeamsTab -Team "TestTeamPBI" -Channel "General" -DisplayName "PBI" -Type PowerBI

### What is the version of the Cmdlet module you are running?
2.3.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by reshmee011** [comment]
It seems to be a limitation of the graph call not allowing any configuration for PowerBi Tab
https://learn.microsoft.com/en-us/graph/teams-configuring-builtin-tabs

**Comment by markgort86** [comment]
@gautamdsheth do we need to close this issue? This because it's not supported to configure a Power BI tab by using the Graph call? This also regarding PnP.PowerShell is just exposing the Graph API of Microsoft.

**Comment by veronicageek** [comment]
Docs updated. Closing now.
