### ISSUE TITLE
Uninstall-PnPApp :: Microsoft.SharePoint.Client.ResourceNotFoundException

### ISSUE THREAD

**Issue by EA12** [pnp/powershell#371]
### Reporting an Issue or Missing Feature
Getting a Microsoft.SharePoint.Client.ResourceNotFoundException when excecuting Uninstall-PnPApp against a SharePoint-Online Site

### Expected behavior 
Unistalling an Add-In should work

### Actual behavior 
The PowerShell CmdLet returns ResourceNotFoundException:

![uninstallpnpapp](https://user-images.githubusercontent.com/22025808/109793767-5ceb1600-7c15-11eb-962a-ec680b051d87.png)

### Steps to reproduce behavior

`$SiteURL = "https://xxx.sharepoint.com/sites/dt"	
Import-Module Pnp.PowerShell
Connect-PnPOnline -Url $SiteURL -interactive
Uninstall-PnPApp -Identity 2585d744-6065-4cfd-9d10-7c18c70afdb2`

### What is the version of the Cmdlet module you are running?
I installed version 1.3.0 of PnP.PowerShell

![getmodule](https://user-images.githubusercontent.com/22025808/109794126-d551d700-7c15-11eb-93e3-a627e5356e1c.png)

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
The error message you see is being returned from the server, in PnP PowerShell we simply forward the message. This means that the server cannot find an app with that id. Does the app with that ID show up if you execute `Get-PnPApp`?

**Comment by EA12** [comment]
thank you for your quick response.
I used the AppInstanceId from the details page of the add-in. My bad.
With the correct id (by determining the id with Get-PnpApp), the command returned with no error.

The Add-In ist still not deleted and from the details page, I can now see the following error:
**This site cannot be deleted because it is included in an eDiscovery hold or retention policy.**

Should PnP.PowerShell return such an error?

**Comment by erwinvanhunen** [comment]
If the site is part of that policy or a retention policy has been applied, then yes. If a site is in a hold you can't make changes to it. That message is returned from the server, we in most cases do not create our own errors. This means that server sees the site the site being in a state which justifies this message.
