### ISSUE TITLE
[BUG] Getting error for DisableSharingForNonOwners - The type of data at position 3427 is different than the one expected.

### ISSUE THREAD

**Issue by DipakTelePE** [pnp/powershell#3721]
Set-PnPSite -Identity $vSiteURL -DisableSharingForNonOwners
This this command was working for me. Now it is throwing error.
Maybe something changed in SharePoint backend which is not yet updated in PnP PowerShell command.

**Comment by gautamdsheth** [comment]
hi @DipakTelePE , please raise an issue with Microsoft support. Something has changed in the server side. Wont be able to help from here.

Closing as duplicate https://github.com/pnp/powershell/issues/3711
