### ISSUE TITLE
[FEATURE] Add-PnPSiteCollectionAdmin should accept a SiteUrl parameter when connected to the tenant admin site

### ISSUE THREAD

**Issue by rslavey** [pnp/powershell#3727]
**Is your feature request related to a problem? Please describe.**
As a SharePoint administrator, I have to add site admins via the tenant admin site.

**Describe the solution you'd like**
SharePoint administrators have access to add site admins via the tenant admin site. They should also be able to do so via powershell if they connect to the admin site and specify the SiteUrl of the target site.

**Describe alternatives you've considered**
I cannot find a way to add a site collection admin to a site unless I'm already a site owner or admin, even if I have the SharePoint Administrator role.

**Additional context**

**Comment by veronicageek** [comment]
@rslavey - Isn't that what you're looking for?
https://pnp.github.io/powershell/cmdlets/Add-PnPSiteCollectionAdmin.html


![image](https://github.com/pnp/powershell/assets/25181757/85d843c2-4554-444a-9178-7d45b6302388)

**Comment by gautamdsheth** [comment]
hi @rslavey , as mentioned above, please use Set-PnPTenantSite cmdlet for this.
