### ISSUE TITLE
[FEATURE] Template xml - Allow Parameter for DefaultLCID attribute as String

### ISSUE THREAD

**Issue by glasserre-pdw** [pnp/powershell#3733]
**Is your feature request related to a problem? Please describe.**

The idea is to allow Parameter in template to be used in DefaultLCID attribute. If we try to use parameter, we have this error message :

_The 'DefaultLCID' attribute is invalid - The value '{parameter:LCID}' is invalid according to its datatype 'http://www.w3.org/2001/XMLSchema:int' - The string '{parameter:LCID}' is not a valid Int32 value._

This will avoid the fact to have a template file by Language just to define default language and simplify template file lifecycle.

**Describe the solution you'd like**
Be able to replace
Replace

`
<pnp:Localizations DefaultLCID="1033">
	<pnp:Localization LCID="1033" Name="English" ResourceFile="clt-projectv3.en-US.resx" />
	<pnp:Localization LCID="1036" Name="French" ResourceFile="clt-projectv3.fr-FR.resx" />
</pnp:Localizations>
`
by

`
<pnp:Localizations DefaultLCID="{parameter:LCID}">
	<pnp:Localization LCID="1033" Name="English" ResourceFile="clt-projectv3.en-US.resx" />
	<pnp:Localization LCID="1036" Name="French" ResourceFile="clt-projectv3.fr-FR.resx" />
</pnp:Localizations>
`
**Describe alternatives you've considered**
Currently, i create a template file by language. Painfull when you have 6 languages to handle.

**Additional context**

Parameter works on Currency field :
`<Field Type="Calculated" DisplayName="{res:list-Changes-Field-ServicesCostPrice_Title}" EnforceUniqueValues="FALSE" Required="FALSE" ShowInNewForm="FALSE" ShowInEditForm="FALSE" ShowInDisplayForm="TRUE" Hidden="FALSE" ReadOnly="TRUE" CanToggleHidden="FALSE" Sortable="TRUE" ID="{1fea3c7e-93e6-4260-9cf0-d4ed73251f4f}" Name="servicescostprice" StaticName="servicescostprice" Format="DateOnly" LCID="{parameter:Currency}" ResultType="Currency" Percentage="FALSE" Decimals="2" SourceID="{9c348222-764d-4112-8f38-0534d0dec397}" ColName="sql_variant1" RowOrdinal="0" Version="2">`

**Comment by gautamdsheth** [comment]
hi @glasserre-pdw , this feature request belongs to PnP Provisioning schema repository:

https://github.com/pnp/PnP-Provisioning-Schema

This can't be handled from PowerShell here. Once the feature request is approved and implemented, it would automatically start working with PnP PowerShell. I can't move the request , so can you please do that ?
