### ISSUE TITLE
[FEATURE]Set-PnPWebHeader to include Logo Thumbnail

### ISSUE THREAD

**Issue by newfy78** [pnp/powershell#3736]
For modern SharePoint sites, the distinction between the "Site Logo" and "Site Logo Thumbnail" is important, as they serve different purposes across SharePoint and the Microsoft 365 ecosystem. The site logo appears in the site header, while the site logo thumbnail is used in search results, site cards, when copying / moving files, and other areas.  It is a critical component used by end users to differentiate between various SPO sites and Teams.

For many of my clients, they want to apply branding and standardize the look and feel of sites they are provisioning.  This needs to be done in a scalable and repeatable manner (i.e. PnP powershell / Power Automate / Rest API / Azure Automation, etc.).  The Set-PnPWebHeader offers a nice set of options but is missing the ability to set the Logo Thumbnail.  In fact I can't find any other way outside of PnP SDK Core (which isn't an option for many clients).  

I'm requesting for the Set-PnPWebHeader to have an attribute -SiteLogoThumbnailURL added to it's capability to address this gap.

**Comment by reshmee011** [comment]
Interesting, I implemented the feature within https://github.com/pnp/cli-microsoft365/issues/5495 and cmdlet is available within https://pnp.github.io/cli-microsoft365/cmd/spo/site/site-set

The code will have to be modified using the endpoint _api/siteiconmanager/setsitelogo with data 
 for logo 
data: {
    aspect: 1,
    relativeLogoUrl: logoUrl,
    type: 0
  }
and thumbnail 
 data: {
    aspect: 0,
    relativeLogoUrl: thumbnailUrl,
    type: 0
  }

Thanks for the cli for m365 maintainers to find a solution and would be happy to implement it within PnP PowerShell.

@gautamdsheth : I can attempt to work on it, assign to myself.

**Comment by gautamdsheth** [comment]
@newfy78 - the PR by @reshmee011 has been merged and will be available in tomorrow's nightly builds.
You need to specify `-SiteThumbnailUrl` parameter in `Set-PnPWeb` cmdlet.

Thanks for raising this feature request.

**Comment by reshmee011** [comment]
@newfy78 , thanks for the request, it will help many.
