### ISSUE TITLE
[BUG] Creating SingleWebPartAppPage using PnP Powershell does not allow to edit page

### ISSUE THREAD

**Issue by zensho-mjp** [pnp/powershell#3749]
Hi everyone,

### ISSUE : 
Creating a Single WebPart App Page does not work using the PnP PowerShell Command.
The created page is not editable.  The button is not displayed.  This is not a permission issue as I have checked it out already.
The weirdest is that pages that were created manually without a script, and sharing the same page layout do not encounter this issue.

### Expected behavior 
Being able to edit the page, adding section, webpart, etc.

### Actual behavior 
The page is blank and does not have any buttons available, including the Edit button present on any pages under the right permission levels.

### Steps to reproduce behavior
$Page = Add-PnPPage -Name $pageName -LayoutType SingleWebPartAppPage

Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows

Thank you for your help !

Maxime

**Comment by a1mery** [comment]
Hi,

From what I understand, this is not an issue.
**SingleWebPartAppPage** cannot be edited by end users using a browser. This type of page is mainly used to host SharePoint Framework web parts or Microsoft Teams applications.

I guess what your looking for is something like that: `$Page = Add-PnPPage -Name $pageName -LayoutType Article`

More information here: [Using single part app pages in SharePoint Online](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/single-part-app-pages?tabs=pnpposh)

**Comment by zensho-mjp** [comment]
Hi,

Yes, but Article does not span the entire page.  Apparently, I first have to  create the page as "Article", then add the webpart, then switch through powershell into a single webpart app page.
It just seems to be a workaround to me.  

Thank you for your response

**Comment by gautamdsheth** [comment]
Hi @zensho-mjp , as mentioned , this is by design.
Need to create page with article layout first and then set it to SingeWebpartAppPage
