### ISSUE TITLE
[BUG] New-PnPSite Command, -sitealias Parameter does not work

### ISSUE THREAD

**Issue by MS-Andre** [pnp/powershell#3751]
### Reporting an Issue or Missing Feature
I use the New-PnPSite Command, but the parameter "sitealias" is broken

### Expected behavior 
I expect that the site url is https://***.com/sites/site-group004

### Actual behavior 
But the url is https://***.com/sites/mail-group004. So it takes the "alias" parameter, not the sitealias parameter as expected. 

What we want to do: Create a Teams Team, where we want to control what is the mail alias, site url and group name (which should not be the same for all of them). In the UI we have this possibility by first creating a teamsite (with group) 
![image](https://github.com/pnp/powershell/assets/128819667/9d9353bc-d503-4892-a3a8-23a4bd4ae54e)
and then teamify that group. 
By script we want to do the same steps, because when you directly create a Teams Team by Shell, you have no control to change the url and the e-mail address. We don´t want to change it afterwards. 

### Steps to reproduce behavior
New-PnPSite -Type TeamSite -sitealias "site-group004" -Alias "mail-group0004" -Title "test pnp anlage newpnpsite 3rdtry" -Description "keine"
![image](https://github.com/pnp/powershell/assets/128819667/be6d83e0-b431-449a-87d8-dc42687e0fba)
![image](https://github.com/pnp/powershell/assets/128819667/8dd03e98-a49d-49b9-95af-d29b9f9116d5)

### What is the version of the Cmdlet module you are running?
2.3.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

Thanks for your work and help
André

**Comment by gautamdsheth** [comment]
@MS-Andre - can't reproduce this issue in my tenant. Quite weird though.

@veronicageek - can you also please check if you can reproduce this issue ?

**Comment by MS-Andre** [comment]
![image](https://github.com/pnp/powershell/assets/128819667/5185180d-3fc8-40ea-86b1-2561074e7dd5)
![image](https://github.com/pnp/powershell/assets/128819667/52fd3a7d-936e-4510-9677-e140d1ab3e65)


i tried it again today, still does not work. 

Super weird! I tried it again with user authentication, then it works like expected. 

![image](https://github.com/pnp/powershell/assets/128819667/7e9194ba-59c4-4bf8-b13d-7e682a9f8293)


Could it be something about permissions? I did App Authentication. I have following Permission for the App:
![image](https://github.com/pnp/powershell/assets/128819667/2be531d9-497c-42ed-92db-b1eddb35c489)

**Comment by gautamdsheth** [comment]
Ahh ok, so it doesn't work in case of Apponly authentication ? Is that correct ?

**Comment by MS-Andre** [comment]
correct, didn´t tested it with user authentication before creating the issue because i need it for automation, so app authentication is for me the only way.

**Comment by gautamdsheth** [comment]
@MS-Andre - Have managed to figure it out and fix it. It will be available in tomorrow's nightly builds as well as the next major release version. Thanks for raising the issue.
