### ISSUE TITLE
[BUG] Remove-PnPFileVersion -Recycle returns an error

### ISSUE THREAD

**Issue by latchee** [pnp/powershell#3756]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
When running the cmdlet Remove-PnPFileVersion -Url $_.FieldValues.FileRef -All -Force, I receive this error:

> Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.

If I remove -Recycle, the cmdlet works and delete the file completely (bypassing the first and second stage recycle bin).

The -Recycle does not appear to be working for Remove-PnPFileVersion.

Could this be related to https://github.com/pnp/powershell/issues/650 ?

### Expected behavior 
The -Recycle should work and allow deleted file versions to be sent to the recycle bin.

### Actual behavior 
Flag -Recycle does not allow the cmdlet to work.

### Steps to reproduce behavior
There is a bit more to the script but globally it fails on the last line:

`$Files = Get-PnPListItem -List $List -PageSize 2000 -Fields File_x0020_Size, FileRef, Modified -ScriptBlock { Param($items) $global:counter += $items.Count; Write-Progress -PercentComplete ($global:Counter / ($List.ItemCount) * 100) -Activity "Getting Files of '$($List.Title)'" -Status "Processing Files $global:Counter to $($List.ItemCount)";}  | Where-Object {$_.FileSystemObjectType -eq "File" -and $_.FieldValues.Modified -lt $twoYearsAgo}
        Write-Progress -Activity "Completed" -Completed
 
        $VersionHistoryData = @()
        $Files | ForEach-Object {
        Write-host "Getting Versioning Data of the File:"$_.FieldValues.FileRef
        #Get File Size and version Size
        $FileSizeinMB = [Math]::Round(($_.FieldValues.File_x0020_Size/1MB),2)
        $File = Get-PnPProperty -ClientObject $_ -Property File
        $Versions = Get-PnPProperty -ClientObject $File -Property Versions
        $VersionSize = $Versions | Measure-Object -Property Size -Sum | Select-Object -expand Sum
        $VersionSizeinMB = [Math]::Round(($VersionSize/1MB),2)
        $TotalFileSizeMB = [Math]::Round(($FileSizeinMB + $VersionSizeinMB),2)
        $StorageClearedMB = [Math]::Round(($TotalFileSizeMB - $FileSizeinMB),2)
 
        #Extract Version History data
        $VersionHistoryData+=New-Object PSObject -Property  ([Ordered]@{
            "Site Name" = $Web.Title
            "Site URL" = $Web.URL
            "Library Name" = $List.Title
            "File Name"  = $_.FieldValues.FileLeafRef
            "File URL" = $_.FieldValues.FileRef
            "Last Modified" = $_.FieldValues.Modified
            "Versions" =  $Versions.Count
            "File Size (MB)"  = $FileSizeinMB
            "Version Size (MB)"   = $VersionSizeinMB
            "Total File Size (MB)" = $TotalFileSizeMB
            "Storage Cleared (MB)" = $StorageClearedMB
            })

        #Deleting Version History
        If($Versions.Count -gt 0)
            {
            Write-Host -f Red  "Deleting Version History Data for "$_.FieldValues.FileRef
            Remove-PnPFileVersion -Url $_.FieldValues.FileRef -All -Recycle -Force
            }
        }`

### What is the version of the Cmdlet module you are running?
Version 2.3.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
hi @latchee , this is by design. Not a bug.

To recycle a version, you need to specify the version Id like this:

```
Remove-PnPFileVersion -Url Documents/MyDocument.docx -Identity 512 -Recycle -Force

```

Recycling all versions is not supported , so need to specify the version Id.

**Comment by latchee** [comment]
Hi @gautamdsheth ,
Sorry to reopen but then it seems that the documentation needs to be updated as -Recycle is showing as an available parameter with -All.

https://pnp.github.io/powershell/cmdlets/Remove-PnPFileVersion.html
> SYNTAX
> Return as file object (Default)
> PowerShell
> 
> Remove-PnPFileVersion -Url <String> [-Recycle] [-Force] [-Connection <PnPConnection>]
>  
> 
> All
> PowerShell
> 
> Remove-PnPFileVersion -Url <String> [-All] [-Recycle] [-Force] 
>  [-Connection <PnPConnection>] 
> 
> By Id
> PowerShell
> 
> Remove-PnPFileVersion -Url <String> [-Identity <FileVersionPipeBind>] [-Recycle] [-Force] 
>  [-Connection <PnPConnection>] 

Nonetheless, thank you very much for your prompt answer. I will update my code accordingly :)
