### ISSUE TITLE
[BUG] Register-PnPManagementShellAccess not working in GCC High / Azure USGovernment

### ISSUE THREAD

**Issue by aarontguilmette** [pnp/powershell#3761]
I saw issue https://github.com/pnp/powershell/issues/3419 but it is closed. I commented on it, but decided to open a new issue.

Still not working. I have a GCCH tenant and attempting to complete the registration. After specifying both the tenant name (TenantName .onmicrosoft.us) and the Azure instance (AzureEnvironment USGovernment), I am prompted to enter my credentials. After successfully entering credentials, I receive the following notification:

> You did not consent for the PnP Management Shell Application for use by PnP PowerShell. Feel free to close this browser window.
> 
> Error details: error invalid_request error_description:AADSTS65006: Resource '797f4846-ba00-4fd7-ba43-dac1f8f63013' had no entitlements matching required permissions configured on the required resource access for client '31359c7f-bd7e-475c-86db-fdb8c937548e'. Requested permission IDs: '41094075-9dad-400e-a0bd-54e686782033'. This is a problem with one or more invalid permission ids on the client RRA configuration or the resource entitlement configuration. Trace ID: 7d965bc1-633e-4281-8866-2c4a5cfd0200 Correlation ID: 068e5484-49a3-417d-b65b-902343a69d74 Timestamp: 2024-02-16 14:31:39Z

My tenant is brand new (about a 2 weeks old) and has no users, data, or applications configured (or in use).
![pnpmanagementshellerror](https://github.com/pnp/powershell/assets/126546027/c38283a8-b969-44f7-93ef-9af300d8f000)
s no users, data, or applications deployed.

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
1.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by jrudley** [comment]
I am in gcc high and did not have any issues.

**Comment by gautamdsheth** [comment]
@jrudley - thanks for confirming, going to close this issue.

If the issue persists, would suggest you wait a few days for some services to be provisioned. If blocked, you can use the Register-PnPAzureADApp and use that.
