### ISSUE TITLE
[BUG] - Get-PnPTenant errors out as Unable to cast object of type 'System.String' to type 'Microsoft.Online.SharePoint.TenantAdministration.EsignatureThirdPartyProvidersInfo'

### ISSUE THREAD

**Issue by NishkalankBezawada** [pnp/powershell#3766]
### Reporting an Issue or Missing Feature
`Get-PnPTenant` command not working as intended. It errors out as 

`System.InvalidCastException: 'Unable to cast object of type 'System.String' to type 'Microsoft.Online.SharePoint.TenantAdministration.EsignatureThirdPartyProvidersInfo'.'`

### Expected behavior 
`Get-PnPTenant` command should return organization level properties. 

### Actual behavior 
`Get-PnPTenant` command not working as intended. It errors out as 

`System.InvalidCastException: 'Unable to cast object of type 'System.String' to type 'Microsoft.Online.SharePoint.TenantAdministration.EsignatureThirdPartyProvidersInfo'.'`

<img width="943" alt="image" src="https://github.com/pnp/powershell/assets/47456098/79d5fc2c-f92e-473e-9a8e-c0dcc0b55957">

When checked, `EsignatureThirdPartyProvidersInfo` is one of the properties of the Tenant as below, 

<img width="505" alt="image" src="https://github.com/pnp/powershell/assets/47456098/8d3a6849-0e11-492b-a0e1-68d0a8df6728">

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

Thanks,
Nish

**Comment by NishkalankBezawada** [comment]
> Hi Nish,
> 
> I can reproduce the error with the latest version of the module (2.3.62-nightly). However it works fine with PnP.PowerShell version 2.3.0.
> 
> Hope it helps :)

Hey Thomas @a1mery 

I actually have an idea in enhancing one of the command, and wanted to check the Tenant properties, so, I still need the nightly build, as i have forked out to our dev branch. 

Thanks,
Nish

**Comment by gautamdsheth** [comment]
hello @NishkalankBezawada , @a1mery closing this issue as it has now been fixed with the latest nightly builds.

**Comment by NishkalankBezawada** [comment]
> hello @NishkalankBezawada , @a1mery closing this issue as it has now been fixed with the latest nightly builds.

Thanks @gautamdsheth, I will verify this.

//Nishkalank
