### ISSUE TITLE
[BUG] Get-PnPHubSiteChild returns results that are not children of the specified hub

### ISSUE THREAD

**Issue by AndyBoyet** [pnp/powershell#3768]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

### Reporting an Issue or Missing Feature
Get-PnPHubSiteChild returns results that are inconsistent with the Admin center. These results are not children of the specified hub. 

### Expected behavior 
Get-PnPHubSiteChild returns results that are verifiable against the admin center

### Actual behavior 
When using Get-PnPHubSiteChild, some sites are returned showing associations with hub sites that do not exist according to the admin center. 

### Steps to reproduce behavior
Run Get-PnPHubSiteChild and compare with Admin Center hub site settings. It seems to happen on sites with multiple levels of hub sites. 

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
2.3.0

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows

**Comment by markgort86** [comment]
Is there a way how to reproduce this issue? I created just a random HubSite and associated three SharePoint sitecollection to it. All those results are reflected running this cmdlet.

**Comment by gautamdsheth** [comment]
Closing this due to lack of response and also we can't repro this as well at our end.
