### ISSUE TITLE
[BUG] New-PnPSite creates root web with same Id

### ISSUE THREAD

**Issue by arjenbloemsma** [pnp/powershell#377]
### Reporting an Issue or Missing Feature
I have an Azure Function which is called several times a day to create a new SharePoint Online site. This Azure Function makes use of the New-PnPSite cmdlet to create the new site. But I recently noticed that the root webs of every site that was created this way has the same Id. (In my case that is 71a19690-7a7e-4337-8cd8-922f2abc39db). Rootwebs of sites with the same specs that were created via the SPO Admin UI do have different GUIDs as one would expect.

### Expected behavior 
Sites created via New-PnpSite should be the same as the ones created via SPO Admin UI, and therefore I expect the root web of a site created via this cmdlet to have a unique Id.

### Actual behavior 
All the root webs of the sites that were created via that Azure function that uses the code listed below have the same GUID for the root web.

### Steps to reproduce behavior
``` PowerShell
New-PnPSite -Type TeamSite -Alias $alias -Title $sitetitle -IsPublic:$false | Out-Null
Set-PnPSite -Sharing Disabled
$w = Get-PnpWeb
$w.Id.Guid
```

### What is the version of the Cmdlet module you are running?
1.3.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [X] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
We actually do not assign a id. We call an API on your tenant and say, "create a new site collection, with this title, and that and that property" and that's it. It's the server creating the site collection and root web and it's the server that assigns the id. But, keep in mind: in SPO online you cannot assume that every web has a unique id unfortunately (site collections do have a unique id). This is different from SharePoint on-premises and has to do with how sites are being created by the server (they're effectively copies made on database level so to say of a non-user accessible base template site in the farm).

E.g. we're just consuming the API (it's the same API the browser uses when you click on Create Site on the SharePoint Home, e.g. when you click on 'SharePoint' in the top bar and click '+ Create Site').

**Comment by arjenbloemsma** [comment]
Thanks for your quick and elaborate response Erwin 👍🏻

The fact that the site I've created via the UI had a different root web id made me think that something was wrong with the ones created via the cmdlet, but now I know for sure that this isn't the case. Thanks again
