### ISSUE TITLE
[BUG] Get-PnPSiteCollectionAppCatalog does not work with vanity URL

### ISSUE THREAD

**Issue by mkrupeydeloitte** [pnp/powershell#3771]
One of our tenants is multi-geo with a vanity home/root geo. I am able to connect via Connect-PnPOnline to the vanity URL but when I use the Get-PnPSiteCollectionAppCatalog command, it automatically will append "-admin" into the URL when it runs this command and in our environment, our admin site does not follow this pattern.

I have tried adding in TenantAdminURL into the Connect-PnPOnline command but that did not make a difference. Everything works fine in our other Geos as they follow the -admin pattern.

Windows ISE
PnP.Powershell 1.12.0
Powershell 5.1

**Comment by gautamdsheth** [comment]
Can you please try with the latest 2.3.0 version ? 
1.12.0 is quite old and there have been quite a few changes since then.
Do note, that this will require PowerShell 7.2 or later versions since we dropped support for PS 5

**Comment by mkrupeydeloitte** [comment]
I have tried with 2.3.0 version and same result. Using the TenantAdminUrl parameter passes in that value but the message returned is that

Get-PnPSiteCollectionAppCatalog: The resource principal name https://tenanturl**-admin**.contoso.com was not found in the tenant named Contoso (O365). 

Basically it passes the correct value from the Connect-PnPOnline TenantAdmninUrl parameter but still tries to append -admin when it's not necessary.

**Comment by himani-chi** [comment]
any updates on this?

**Comment by gautamdsheth** [comment]
hi @mkrupeydeloitte and @himani-chi , we have fixed this in the latest nightly builds.

It will also be available in the next major version whenever we release it.

Thanks for raising the issue. 
Please reopen this if it still persists.
