### ISSUE TITLE
[BUG] Unable to use Managed Identity when calling `Get-PnPTenantSite` 

### ISSUE THREAD

**Issue by Floobershnoo** [pnp/powershell#3782]
### Reporting an Issue or Missing Feature

`Get-PnPTenantSite` returns the 401 error below when authenticating with a Managed Identity from both Windows VM (AVD) and PowerShell Function App.  It references the **TenantAdminURL** as missing.  

```
Get-PnPTenantSite: Unable to connect to the SharePoint Online Admin Center at 'https://{mytenant}-admin.sharepoint.com' to run this cmdlet. Please ensure you pass in the correct Admin Center URL using Connect-PnPOnline -TenantAdminUrl and you have access to it. Error message: The remote server returned an error: (401) Unauthorized..
```

There are a couple problems with this:
1. The **TenantAdminURL** seems to be auto-resolving with `-admin`, per the first sentence of the error message, but then suggests passing it explicitly via `-TenantAdminURL` parameter in the second sentence. This is inconsistent.
1. If we try to pass **TenantAdminURL** explicitly, using `Connect-PnPOnline -Url "https://{mytenant}.sharepoint.com/" -TenantAdminURL "https://{mytenant}-admin.sharepoint.com/" -ManagedIdentity -ReturnConnection`, we get the following error:
```
Connect-PnPOnline: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
```
Managed Identities we used have the `Sharepoint - Sites.FullControl.All` permission.  We have also tried assigning the `SharePoint Administrator` Entra role.  Both produce the same error. 

We've had to revert to using App Registrations w/certs to get around this.  App Registrations have same `Sharepoint - Sites.FullControl.All` permission and work fine.

May be related to https://github.com/pnp/powershell/issues/3606

### Expected behavior 
Return the Tenant/Collection object.

### Actual behavior 
```
Get-PnPTenantSite: Unable to connect to the SharePoint Online Admin Center at 'https://{mytenant}-admin.sharepoint.com' to run this cmdlet. Please ensure you pass in the correct Admin Center URL using Connect-PnPOnline -TenantAdminUrl and you have access to it. Error message: The remote server returned an error: (401) Unauthorized..
```

### Steps to reproduce behavior
1. Create Powershell Function App, assign a System-Assigned Managed Identity
2. Grant consent for `Sharepoint - Sites.FullControl.All` to managed identity 
   a. This requires a script, like this: https://stackoverflow.com/a/72905062
3. Upload the following script to run.ps1:
```
$PnPTenantConnection = Connect-PnPOnline -Url "https://{mytenant}.sharepoint.com/" -ManagedIdentity -ReturnConnection
Get-PnPTenantSite -Identity "https://{mytenant}.sharepoint.com/sites/{sp-collection-id}" -Connection $PnPTenantConnection
```
4. Run the Function App
   a. `Connect-PnPOnline` will work and return a connection object.
   b. `Get-PnPTenantSite` produces the following error reported above

### What is the version of the Cmdlet module you are running?
v2.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [X ] Azure Functions

**Comment by gautamdsheth** [comment]
```
$PnPTenantConnection = Connect-PnPOnline -Url "https://{mytenant}-admin.sharepoint.com/" -ManagedIdentity -ReturnConnection
Get-PnPTenantSite -Identity "https://{mytenant}.sharepoint.com/sites/{sp-collection-id}" -Connection $PnPTenantConnection
```

can you please try it like above and let us know ?

**Comment by Floobershnoo** [comment]
That did the trick!  Cheers!

**Comment by gurban2013** [comment]
i am having this exact same issues trying to use certificate auth. the above did not resolve it. it times out foreever. trying to use Certificate auth.

update:  module version  is 3.1.0

**Comment by bezik46** [comment]
No, does not work:
`Connect-PnPOnline -Url "https://<tenant>-admin.sharepoint.com/" -Tenant <tenant>.onmicrosoft.com -ClientId 7fd7c81f-675b-4849-87c2-f3b590a44833 -CertificatePath c:\temp\EntraCertApp-PnPOnline.pfx -CertificatePassword (ConvertTo-SecureString -AsPlainText 'mysecurepassword' -Force)`

Get-PnPTenantSite: Unexpected response from the server. The content type of the response is "". The status code is "Unauthorized".

3.1.0                PnP.PowerShell

https://github.com/pnp/powershell/issues/3943#issuecomment-2545120627

I was missing application permission

SharePoint > AllSites.FullControl for delegated permissions
SharePoint > Sites.FullControl.All for Application permissions
