### ISSUE TITLE
[BUG] Rename-PnPTenantSite treating non-required parameter as required

### ISSUE THREAD

**Issue by nmtTomMoody** [pnp/powershell#3795]
Despite the -NewSiteUrl parameter not being required I cannot run the Rename-PnPTenantSite cmdlet without it

![image](https://github.com/pnp/powershell/assets/161541637/394ca91f-d5a0-4166-9523-cb781accd78e)
![image](https://github.com/pnp/powershell/assets/161541637/efa8efaa-71b7-4548-b069-2e77d8184f21)

**Comment by gautamdsheth** [comment]
hi @nmtTomMoody , have updated the docs. The parameter is indeed required, docs will be updated tomorrow.

**Comment by nmtTomMoody** [comment]
Thanks @gautamdsheth why does it need to be required?
