### ISSUE TITLE
[BUG] New-PnPGroup Description HTML gets encoded

### ISSUE THREAD

**Issue by NoralK** [pnp/powershell#3797]
### Reporting an Issue or Missing Feature
When creating a New-PnPGroup that has HTML in the Description the HTML gets encoded.

We are a GCC Tenant.

### Expected behavior 
HTML should not be encoded.

### Actual behavior 
HTML is being encoded

### Steps to reproduce behavior
Here is the command:
```
New-PnPGroup -Title "$($SiteName) Site Designers" `
    -Description "Use this group to grant people full control permissions to the SharePoint site: <a href=""/sites/$($Site)"">$($SiteName) Site</a>" `
    -Owner "$($SiteName) Site Owners"
```

However, when I perform the `Set-PnPGroup` command with the exact same information it works.
```
Set-PnPGroup -Identity "$($SiteName) Site Designers" `
    -Description "Use this group to grant people full control permissions to the SharePoint site: <a href=""/sites/$($Site)"">$($SiteName) Site</a>"
```
### What is the version of the Cmdlet module you are running?
2.3.0 inside VS Code
1.12.0 inside PS-ISE
Same behavior in both versions

### Which operating system/environment are you running PnP PowerShell on?
- [ X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
hi @NoralK , thanks for raising this issue. Has been fixed now.
Will be available in tomorrow's nightly builds as well as the next major version when we release it.

**Comment by NoralK** [comment]
Thank you!  I believe I know this answer already, but a fix will not be back-ported to v1.x correct?

**Comment by gautamdsheth** [comment]
Hi ,yep correct, we don’t back port the fixes.
