### ISSUE TITLE
[BUG] Unable to use Managed Identity when calling Set-PnPAdaptiveScopeProperty

### ISSUE THREAD

**Issue by hbland-cjc** [pnp/powershell#3808]
### Reporting an Issue or Missing Feature
I am trying to build an Azure Function using Managed Identity that will receive a set of Values for some Adaptive Scope Properties we are trying to set as part of our workflow, however when running the Script we are seeing the error `Unable to connect to the SharePoint Online Admin Center at 'https://{tenant}-admin.sharepoint.com' to run this cmdlet`

### Expected behavior 
Set Adapative Scope Property to MyNewValue = Value1

### Actual behavior 
Unable to connect to the SharePoint Online Admin Center at 'https://{tenant}-admin.sharepoint.com' to run this cmdlet. If this URL is incorrect for your tenant, you can pass in the correct Admin Center URL using Connect-PnPOnline -TenantAdminUrl. If you are using Privileged Identity Management (PIM) on your tenant, please ensure you have activated at least the SharePoint Administrator role and allowed some time for it to activate. Error message: The remote server returned an error: (401) Unauthorized.

### Steps to reproduce behavior
Connect-PnPOnline -Url $siteAddress -ManagedIdentity
Set-PnPAdaptiveScopeProperty -Key MyNewValue -Value Value1

### What is the version of the Cmdlet module you are running?
'PnP.PowerShell' = '2.4.0'

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [x] Azure Functions

**Comment by gautamdsheth** [comment]
In your connect-pnponline cmdlet, can you please use `https://tenant-admin.sharepoint.com` site URL and try ?

**Comment by hbland-cjc** [comment]
Hi @gautamdsheth,

Can you confirm how this will attach to an individual site when running the Set-PnPAdaptiveScopeProperty as this command doesn't have any way of setting which site we are editing?

**Comment by hbland-cjc** [comment]
Hi @gautamdsheth,

I have tried your mentioned option however as queried in my original response this tries to make the change against the Tenant Admin portal not the site I am trying to apply the item to. Do you have any further suggestions?

**Comment by gautamdsheth** [comment]
hey @hbland-cjc , can you please try with tomorrow's or later nightly builds and let us know if this still persists ? We have made quite a few changes related to managed identity auth, maybe that helps with your issue ?

**Comment by gautamdsheth** [comment]
Closing this due to lack of response . If the issue is still present with the latest builds, please do reopen .
