### ISSUE TITLE
[BUG] The PSDrive created using the "Connect-PnPOnline -CreateDrive" parameter does not support '#' (and '%'?) characters in file names

### ISSUE THREAD

**Issue by spbuvm** [pnp/powershell#3819]
### Reporting an Issue or Missing Feature
When copying files from the SharePoint PSDrive (created by the -CreateDrive parameter of Connect-PnPOnline) to a local file system using Copy-Item, files with a '#' in the name are not copied.
Error Message:
`Copy-PnPItemProxy: Cannot find path '<PSDriveName>:\<pathToFileWith#InName>' because it does not exist. `

### Expected behavior 
Copy-Item should copy the file from the SharePoint PSDrive to the local file system. (This works fine for files that do not have '#' in the name.)

### Actual behavior 
When trying to copy a file with a '#' in the name, the file is not copied and the following error is displayed:
`Copy-PnPItemProxy: Cannot find path '<PSDriveName>:\<pathToFileWith#InName>' because it does not exist. `

### Steps to reproduce behavior
1>  In a SharePoint Online document library, create a file with the '#' character in the name.
2> Create an App Registration with the 'SharePoint | Site.FullControl.All' API permission, and upload a certificate for authentication
3> Connect to the SharePoint site containing your test file using the -CreateDrive parameter of the Connect-PnPOnline cmdlet
      e.g. `Connect-PnPOnline -Url <url of site> -Tenant <tenant domain> -ClientId <app registration ClientID> -Thumbprint <thumbprint of app registration cert> -CreateDrive:$TRUE -DriveName "SPO"`
4> Use Copy-Item to copy the file with '#' in the name from the 'SPO:' PSDrive to the local file system.

### What is the version of the Cmdlet module you are running?
PnP.PowerShell Version 2.3.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

### NOTES:
I have not tested this, but I expect the same problem would affect files with the '%' character in the name.
Files with '#' in the name can be copied successfully using the Get-PnPFile cmdlet.
e.g.  `Get-PnPFile -Url <serverRelativeUrl of file> -AsFile -Path 'c:\temp' -FileName <original name of file in doc lib>`

**Comment by gautamdsheth** [comment]
Hi @spbuvm , checked this. Looks like a bug in PowerShell , we can't fix this issue.

This is simply an alias for Copy-Item cmdlet, would request you to open this in PowerShell repo.
