### ISSUE TITLE
Get-PnPfile throwing error "The underlying connection was closed: The connection was closed unexpectedly"

### ISSUE THREAD

**Issue by bukhaaaa** [pnp/powershell#382]
### Reporting an Issue or Missing Feature
Hi all! Apologies if this is the wrong place to post this. If so, please advise on where to get help for the issue.

We have 3 windows servers that run scheduled tasks daily, DEV, QUA, PRD (for development, test, and production respectively). The configuration of these servers are identical. We are running a PowerShell script that calls 2 PnP commands:

```
Connect-PnPOnline -Url [SharePoint URL] -ClientId [clientid] -ClientSecret [clientsecret] -WarningAction Ignore 
Get-PnPFile -serverrelativeurl [relative URL] -Path [location in C:\] -Filename "divisions.csv" -AsFile -Force
```

**These commands work perfectly as expected on DEV and PRD servers, BUT not in QUA.** In QUA, Connect-PnPOnline seems to work, but when we run the Get-PnPFile command,  we get an error saying

 **"The underlying connection was closed: The connection was closed unexpectedly"**

We have ensured TLS1.2 is being utilized by running the below code and checking the settings in regedit:

`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 `

We have also ran the below command in command prompt in all 3 servers to compare the path the computer takes to reach SharePoint - all 3 servers returned an identical result for the trace.

`tracert [companyname].sharepoint.com` 

Are there any other settings or things we should check or try to further diagnose the issue? Any help would be highly appreciated.

### Expected behavior 
The expected behavior is that the commands are run, the file is downloaded, and there is no output or errors in the terminal.

### Actual behavior 
 **"The underlying connection was closed: The connection was closed unexpectedly"**
![PowerShell error_LI](https://user-images.githubusercontent.com/80124413/110160925-85a01680-7da1-11eb-9108-f1119572a50a.jpg)

### Steps to reproduce behavior
1. Remote into the QUA VM
2. Open PowerShell as administrator
3. Run Connect-PnPOnline
`Connect-PnPOnline -Url [SharePoint URL] -ClientId [clientid] -ClientSecret [clientsecret] -WarningAction Ignore `
4. Run Get-PnPFile
`Get-PnPFile -serverrelativeurl [relative URL] -Path [location in C:\] -Filename "divisions.csv" -AsFile -Force`

### What is the version of the Cmdlet module you are running?
**PnP.Powershell version 1.3.0**

### Which operating system/environment are you running PnP PowerShell on?
**- [x] Windows**
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@bukhaaaa - I think it'd fair to say that the cmdlet works (as you stated) but there might still be something different on your 3rd server? I'll be moving this to the discussions for wider inputs.
