### ISSUE TITLE
[BUG] add-pnpfile can't upload checkin comment and update value{editor=jane..doe@email.com;} when -checkout is used

### ISSUE THREAD

**Issue by S3rp3nT1nE** [pnp/powershell#3822]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:
### Reporting an Issue or Missing Feature
using add-pnpfile I want to be able to add a new version and specify the modified (Value: Editor) with a checkincomment.

I can do both tasks separately but not together meaning

I can either update the Author and Editor but not specify checkin comment
or 
I can upload with a checkin comment but no update the author or editor.

**Example Below:** Will successfully update the "checkincomment", but the author/editor is going to be MyAppUser (the app registration user running the command) not Jane.Doe@company.com

add-pnpfile -path $MyPath -Folder $Myfolder -NewFileName $MyNewFile -checkout -CheckinType MajorCheckIn -CheckInComment "Another Version" -Values @{Editor="Jane.Doe@Company.com";Author="Jane.Doe@Company.com";}

**Example Below (removed -checkout):** Will successfully update the author/editor but the checkincomment is going to be blank not "Another Version"

add-pnpfile -path $MyPath -Folder $Myfolder -NewFileName $MyNewFile -CheckinType MajorCheckIn -CheckInComment "Another Version" -Values @{Editor="Jane.Doe@Company.com";Author="Jane.Doe@Company.com";}

### Expected behavior 
File should be able to be uploaded to SharePoint with a custom checkincomment and with the modified (Editor/Author) fields set as the author of my choosing. 

### Actual behavior 
I can either upload as the user I desire, but not add a checkincomment
or I can add a checkin comment but cannot change the user (Editor/Author). 

### Steps to reproduce behavior
As above
Below: Will update the checkincomment on versions, but the author/editor is going to be MyAppUser not Jane.Doe@company.com

add-pnpfile -path $MyPath -Folder $Myfolder -NewFileName $MyNewFile -checkout -CheckinType MajorCheckIn -CheckInComment "Another Version" -Values @{Editor="Jane.Doe@Company.com";Author="Jane.Doe@Company.com";}

Below (removed -checkout): Will update the author/editor but the checkincomment is going to be blank not "Another Version"

add-pnpfile -path $MyPath -Folder $Myfolder -NewFileName $MyNewFile -CheckinType MajorCheckIn -CheckInComment "Another Version" -Values @{Editor="Jane.Doe@Company.com";Author="Jane.Doe@Company.com";}

### What is the version of the Cmdlet module you are running?
2.2.4 (Latest at time of writing)

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows

The below two issues are marked as fixed but I am seeing a similar issue still exists
https://github.com/pnp/PnP-PowerShell/issues/1608
https://github.com/pnp/PnP-PowerShell/issues/1607

Thanks in advance, and thanks to all the Devs and contributors, really useful module, I am sure the above is an edge case, although i did notice a closed issue above which are extremely similar if not the same.  👍

**Comment by gautamdsheth** [comment]
This is by design and not a bug.
You can upload the file using Add-PnPFile cmdlet and if you want to set the author/editor values, use the Set-PnPListItem cmdlet for that after the file is uploaded.
