### ISSUE TITLE
[BUG] Set-PnPtenant -DelayDenyAddAndCustomizePagesEnforcement $true not working

### ISSUE THREAD

**Issue by roberAlb** [pnp/powershell#3826]
### Reporting an Issue or Missing Feature
Command Set-PnPtenant -DelayDenyAddAndCustomizePagesEnforcement $true is giving an error

### Expected behavior 
This command should revoke the option to revert NoScriptSite setting to enabled if we have some sites with it disabled unit mod November 2024

### Actual behavior 
I'm getting this error from few tenants, both are in Target Release

Set-PnPTenant: The requested operation is part of an experimental feature that is not supported in the current environment.

### Steps to reproduce behavior
Set-PnPtenant -DelayDenyAddAndCustomizePagesEnforcement $true

### What is the version of the Cmdlet module you are running?
2.4.11 nightly

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows

**Comment by a1mery** [comment]
This new setting is still being rolled out. That is why you have this error message. It should work soon though.

Quote below is from Microsoft 365 Message center:
> while this cmdlet is available in the latest management shell, running the cmdlet will result in an error (The requested operation is part of an experimental feature that is not supported in the current environment) until March when the settings are shipped.

**Comment by gautamdsheth** [comment]
Closing this  as it is still rolling out.

**Comment by roberAlb** [comment]
Is still rolling out? I'm getting still the same error.

**Comment by a1mery** [comment]
Yes, it was updated: 

> PowerShell command (DelayDenyAddAndCustomizePagesEnforcement) to delay the change will be fully available by mid- April (Previously March).
