### ISSUE TITLE
[BUG] PnPAzureADAppSitePermission - Unable to Truly Connect to Site i.e. run Get-PnPList

### ISSUE THREAD

**Issue by LeonArmston** [pnp/powershell#383]
### Reporting an Issue or Missing Feature
I'm having trouble connecting using my application using resource specific (site) permissions. 
I can register the application - grant it permission to a site but then when I try to connect to the site and run a simple Get-PnPList I get  **The remote server returned an error: (401) Unauthorized**.

Unsure if I am doing anything wrong?

### Expected behavior 
Information about the site returned i.e. Get-PnPList = Lists returned, Get-PnPWeb - web info returned

### Actual behavior 
Connect-PnPOnline connects fine but then doing a Get-PnPList returns a 401 unauthorised
![image](https://user-images.githubusercontent.com/12968962/110208186-860edf00-7e7f-11eb-9d0f-5ff2522d801a.png)

### Steps to reproduce behavior

```powershell
Register-PnPAzureADApp -ApplicationName ResourceSpecific -Tenant tenant.onmicrosoft.com -Store CurrentUser -GraphApplicationPermissions "User.Read.All","Sites.Selected" -Username "user@user.com" -Password (Read-Host -AsSecureString -Prompt "Enter Password")

#Connect as global admin user
Connect-PnPOnline -url 'https://tenant.sharepoint.com/sites/marketing' -Credentials user@user.com

Grant-PnPAzureADAppSitePermission -AppId "GUID from previous Register-PnPApp" -DisplayName "ResourceSpecificApp" -Permissions Write -Site 'https://tenant.sharepoint.com'

#Confirm permission has been applied to the site for the App
Get-PnPAzureADAppSitePermission

#Connect to the site as an app
Connect-PnPOnline -Url 'https://tenant.sharepoint.com/sites/marketing' -ClientId "GUID from previous Register-PnPApp" -Thumbprint '<Thumbprint>' -Tenant 'tenant.onmicrosoft.com'

Get-PnPList
```

**Further Troubleshooting - Perhaps the role is not being retained?**

It doesn't look like the Roles i.e. Read or Write are retained 
![image](https://user-images.githubusercontent.com/12968962/110207000-05e57b00-7e79-11eb-82ef-0ec9d3851f2d.png)

Doing a Set-PnPAzureADAppSitePermission seems to apply to Role Write (see returned output -also note appname not returned)
![image](https://user-images.githubusercontent.com/12968962/110208576-eb62d000-7e7f-11eb-81ad-4376065ea00a.png)

But then doing another Get-PnPAzureADAppSitePermission and the role is not retained:
![image](https://user-images.githubusercontent.com/12968962/110208605-16e5ba80-7e80-11eb-87fa-9ecb085a82c3.png)

Site type: Team Site with M365 Group

I've also tried connecting as an Application with Sites.FullControl.All then running Grant-PnPAzureADAppSitePermission but get:
![image](https://user-images.githubusercontent.com/12968962/110208673-79d75180-7e80-11eb-95f7-e35702a30e00.png)
or granting via Pure Graph from Application with Sites.FullControl.All I get the same message above
```powershell
$GraphAccessToken = Get-PnPGraphAccessToken

$siteid = 'bfde2bcd-43ab-4f55-827b-14e15510bd3e'

$apiUrl = "https://graph.microsoft.com/v1.0/sites/$siteId/permissions"

$apiBody = '{

    "roles": ["write"],

    "grantedToIdentities": [ {

        "application": {

            "id": "bdccebeb-1a3f-4187-bd24-6a23d30f5899",

            "displayName": "ResourceSpecificApp"

        }

    }]

}'
Invoke-RestMethod -Headers @{Authorization = "Bearer $GraphaccessToken" } -Uri $apiUrl -Body $apiBody -ContentType 'application/json' -Method Post
```
![image](https://user-images.githubusercontent.com/12968962/110208749-e0f50600-7e80-11eb-92a6-d59149260120.png)

Not sure what next to troubleshoot other than it might be a Microsoft API issue or I might be doing something wrong?

### What is the version of the Cmdlet module you are running?
 1.3.20     nightly    PnP.PowerShell 

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
This is unfortunately nothing we can fix. It's a limitation of SharePoint: the native SharePoint APIs (CSOM, SPO REST) do not handle the site specific permissions. Only calls made to the Graph work with this. As most of the cmdlets do not use the Graph but either CSOM or SPO REST for now this permission is relatively limited in it's use.

**Comment by LeonArmston** [comment]
Ah understood! Will try it out with some pure graph commands!

Will have to keep an eye out in the future for when more of the PnP commands use Graph.

**Comment by SjoerdV** [comment]
@LeonArmston great work on [your blog](https://www.leonarmston.com/2021/03/testing-out-the-new-microsoft-graph-sharepoint-specific-site-collection-app-permissions-with-pnp-powershell/) explaining the 'Sites.Selected' MSGraph App permission in detail. This is a major deal for large organizations trying to decentralize management on some parts (Read: the SharePoint part) of a huge M365 implementation/tenant.

@erwinvanhunen do you have any insights as to when (if possible at all) full parity may be achieved for **truly delegated site management using the full feature scope of PnP.PowerShell using Graph Application Permissions**? Some sort of Roadmap perhaps? Maybe an entirely different angle for achieving this? I know this is highly dependent on work Microsoft is doing, but your educated guess on this is better than anyone else's, any day of the week.
