### ISSUE TITLE
[BUG] Get-PnPTeamsTab ignores ErrorAction:Ignore

### ISSUE THREAD

**Issue by ismaili-de** [pnp/powershell#386]
### Reporting an Issue 
Get-PnPTeamsTab command still logs error to output even if ignore is configured with -ErrorAction:Ignore

### Expected behavior 
If teams  tab does not exist, no error should be logged to output

### Actual behavior 
Error output "Cannot find tab" is logged to output

### Steps to reproduce behavior
Sample command:
`$tab = Get-PnPTeamsTab -Team $TeamName -Channel $channel.DisplayName -Identity $TabName -ErrorAction:Ignore`

### What is the version of the Cmdlet module you are running?
1.3.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
Good catch! Fixed in the upcoming nightly build. 1.3.23-nightly.
