### ISSUE TITLE
[FEATURE] Get PnPFolder asItem object. Similar to Get-PNPFile

### ISSUE THREAD

**Issue by rohit404404** [pnp/powershell#3861]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to get ListITem equivalent of Folder based on its UEL

**Describe the solution you'd like**

Get-PnPFile -Url <String> -AsListItem  
Above command provides easy way to get List item object based on URL. On similar ground if we can get Folders ITEM object

https://pnp.github.io/powershell/cmdlets/Get-PnPFolder.html
https://pnp.github.io/powershell/cmdlets/Get-PnPFile.html

**Comment by gautamdsheth** [comment]
hi @rohit404404 , have added this capability. It will be available in tomorrow's nightly builds as well as next major versions.

Thanks for raising this feature request.
