### ISSUE TITLE
[BUG] Copy-PnPList Copies the list of the first Lookup field instead of the source list

### ISSUE THREAD

**Issue by mstrblueskys** [pnp/powershell#3866]
### Reporting an Issue or Missing Feature
Reporting a bug

### Expected behavior 
When using Copy-PnPList is copying the wrong list. It copies the list in the first lookup column rather than the source list.

### Actual behavior 
Copy-PnPList -Identity [List Name or GUID] -Title [New Title] will create a list with the new title but it will copy the list of the first lookup field.

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

### What is the version of the Cmdlet module you are running?
2.1.1

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by jackpoz** [comment]
Using version 2.4.8.0 I can confirm the issue.

I create a parent list called "Countries" with Title and Continent columns:
![image](https://github.com/pnp/powershell/assets/1153754/9ca4cfbc-1186-46a9-b9ce-b04b1c7b0b7e)

Then a child list called "Cities" with Title, lookup on Countries and Languages:
![image](https://github.com/pnp/powershell/assets/1153754/f67c70d2-3f36-4cc2-bb95-88e75cfc96a8)

I ran `Copy-PnPList -Identity "Cities" -Title "Copy of Cities"`:
![image](https://github.com/pnp/powershell/assets/1153754/5e3342f5-aac7-4c3e-8d11-2195ebd0e180)

The result is not a copy of "Cities" but a copy of the lookup list "Countries":
![image](https://github.com/pnp/powershell/assets/1153754/c82b9db2-c2c5-4d0f-8a0d-8880a3ce306e)

**Comment by jackpoz** [comment]
This happens by the way because GetSiteScriptFromList() returns both lists and the current PnP PowerShell implementation renames them both, with the first one being created.

**Comment by jackpoz** [comment]
I created a PR at https://github.com/pnp/powershell/pull/3870 that copies the correct list:
![image](https://github.com/pnp/powershell/assets/1153754/a7ae06fe-db05-4891-8afc-64c3504790b2)

**Comment by veronicageek** [comment]
Thanks @jackpoz for your help - I'll let @gautamdsheth review it 🙂

**Comment by mstrblueskys** [comment]
Thanks @jackpoz
