### ISSUE TITLE
[BUG] Get-PnPTenantSite command does not return any output if the number of sites is greater than 40k 

### ISSUE THREAD

**Issue by rajarshibhargav** [pnp/powershell#3875]
### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

Get-PnPTenantSite command does not return any output if the number of sites is greater than 40k 

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

Get-PnPTenantSite command  should return the correct output even if the number of sites is greater than 40k

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

Get-PnPTenantSite command does not return any output if the number of sites is greater than 40k . We waited close to 20 minutes in order to get an output for this command but we did not get any response. We also want to know if there is any fixed interval that we need to wait for a response under Get-PnPTenantSite command while running it for an organisation having greater than 40k Sharepoint Sites. 

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

Run Get-PnPTenantSite command  for any organisation which has more than 40k Sharepoint sites.

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

PS /app> Get-Module -Name "PnP.PowerShell" -ListAvailable

    Directory: /home/spm/.local/share/powershell/Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   2.2.0                 PnP.PowerShell                      Desk      {Add-PnPAdaptiveScopeProperty, Add-PnPPropertyBagValue, Add-PnPSiteClassification, Copy-PnPFolder…}

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [x] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by jackpoz** [comment]
Did you store the result in a variable like `$result = Get-PnPTenantSite` or did you call the command like `Get-PnPTenantSite` ?
Note that the latest version is 2.4.0, try updating it.

**Comment by rajarshibhargav** [comment]
We dont store the result in a variable like $result = Get-PnPTenantSite. However we redirect the command output to json like | ConvertTo-Json -Compress -Depth

**Comment by rajarshibhargav** [comment]
Hi @jackpoz We have updated the version to 2.4.0, however we are still facing the same issue. Request you to kindly look into this issue and help us with a solution / workaround here.

**Comment by jackpoz** [comment]
I do remember having no issues in a tenant with 300k site collections but I don't have access to that tenant anymore.
Does the command get stuck still as you said you waited 20 minutes ?

**Comment by rajarshibhargav** [comment]
Yes @jackpoz . From my testing I was able to get 40k Sites after waiting ~ 2 minutes. For organisation with > 40 k sites, I waited beyond 2 minutes (upto 20 minutes) but the command  Get-PnPTenantSite never returned anything.

**Comment by rajarshibhargav** [comment]
May i request an update on the bug fix here?

**Comment by jackpoz** [comment]
Please try this:
```powershell
$sites = Get-PnPTenantSite
$sites.Count
```

If that shows the correct count, then it's not a PnP PowerShell issue.
I would suggest to export the result to csv using [Export-Csv](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/export-csv?view=powershell-7.4) as a different way to save the result.

**Comment by rajarshibhargav** [comment]
Thank you @jackpoz . Export-Csv has solved this issue.

**Comment by ns-khp** [comment]
Cannot thank you enough @jackpoz . [That answer](https://github.com/pnp/powershell/issues/3875#issuecomment-2125245678) was super helpful 🙏 🙏 .

**Comment by jackpoz** [comment]
Thank you too, I learnt something new about ConvertTo-Json 👍
