### ISSUE TITLE
[BUG] Get-PnPTenant is returning an Experimental Feature error

### ISSUE THREAD

**Issue by IzzyBizzy45** [pnp/powershell#3904]
### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

I am Reporting an Issue

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

Output of Tenant settings of the tenant

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

Returns following error
```Get-PnPTenant: The requested operation is part of an experimental feature that is not supported in the current environment.```

![Error](https://i.imgur.com/MCtYYzy.png)

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

1. Login to PnPOnline using ```Connect-PnPOnline -Url "https:\\{tenant}-admin.sharepoint.com/"```
2. Run ```Get-PnPTenant```

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

2.4.0 on PowerShell 7.4.2

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by drs24** [comment]
Hi,

We are running PnP 1.12 version and we have the same problem with this command and with the New-PnPTenant.
Our SPO version is 16.0.0.24810, but in other tenants withe the SPO version 16.0.0.24803 it's working properly

**Comment by veronicageek** [comment]
@IzzyBizzy45 - I've just tested on version 2.4.0 and I have no issue getting the results. It must have been at a point in time, please try again.

**Comment by IzzyBizzy45** [comment]
Hi veronicageek,
Looks like it's still happening for me but as it's working for you, I'll reach out to Microsoft to resolve
![](https://i.imgur.com/m5q7pg8.png)
_(time is in AEST)_

**Comment by techthoughts2** [comment]
Why was this closed?

We are also actively experiencing this issue:

```powershell
PS C:\Windows\system32> get-command get-pnptenant

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Get-PnPTenant                                      1.12.0     PnP.PowerShell
```

```powershell
PS C:\Windows\system32> Connect-M365Tenant -Workload PnP -ApplicationId xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx -TenantId amazon.onmicrosoft.com -CertificateThumbprint xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
PS C:\Windows\system32> Get-PnPTenant
Get-PnPTenant : The requested operation is part of an experimental feature that is not supported in the current environment.
At line:1 char:1
+ Get-PnPTenant
+ ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-PnPTenant], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.Admin.GetTenant

```

**Comment by AdwoodMicrosoft** [comment]
A service side change in SharePoint is rolling out which has introduced a regression in the Get-SPO tenant cmdlet. This regression is currently impacting a subset of customers and is in the process of being addressed.

**Comment by LastElf** [comment]
> A service side change in SharePoint is rolling out which has introduced a regression in the Get-SPOTenant cmdlet. This regression is currently impacting a subset of customers and is in the process of being addressed.

Will addressing it return back to the previous working instance or require a change to PnP for the function to work again? Several of us are still on PS5.1 and can't upgrade due to script engine requirements. We're seeing this issue across at least half of our partner tenants so far.

**Comment by daverickdunn** [comment]
> @IzzyBizzy45 - I've just tested on version 2.4.0 and I have no issue getting the results. It must have been at a point in time, please try again.

Out of a sample set of a few thousand tenants, roughly 50% of them are still affected, so this is very much an active issue.

**Comment by daveyk00** [comment]
There is no notice on the Service Health Dashboards notifying of this.  Perhaps this issue shouldn't have been closed?  Possibly related to https://github.com/pnp/powershell/issues/3910
