### ISSUE TITLE
[BUG] New-PnPTenantSite creates site but warning: "The requested operation is part of an experimental feature that is not supported in the current environment."

### ISSUE THREAD

**Issue by anthonyrhopkins-sap** [pnp/powershell#3910]
### Reporting an Issue or Missing Feature

Issue

### Expected behavior 

Use the 'New-PnPTenantSite' cmdlet to create a new site collection without warnings.

https://pnp.github.io/powershell/cmdlets/New-PnPTenantSite.html

### Actual behavior 

First noticed today (April 23rd, 2024) around 5am UTC, the 'New-PnPTenantSite' cmdlet started to report:

"New-PnPTenantSite: The requested operation is part of an experimental feature that is not supported in the current environment."

Even with this warning, the New-PnPTenantSite cmdlet succeeds in creating the new site collection. I am also able to create new site collections by all other means (New-PnPSite, SPO and Graph API, SPO Admin Center, SPO PowerShell Module, etc).

This is affecting a large tenant, and I am unable to reproduce the behavior in my dev tenant(s).

I am also receiving the same error with the 'Get-PnPTenant' cmdlet as well. 

"Get-PnPTenant: The requested operation is part of an experimental feature that is not supported in the current environment."

### Steps to reproduce behavior

New-PnPTenantSite -title "Test Site -url sites/pnptenantsite -Owner <UPN>-TimeZone 4 -Template "STS#3" -Lcid 1033 -StorageQuota 1024 -StorageQuotaWarningLevel 512
New-PnPTenantSite: The requested operation is part of an experimental feature that is not supported in the current environment.

I have tried the New-PnPTenantSite cmdlet with as many or as little parameters as possible, including -debug and -verbose flags, and although the sites are being created, I continue to receive the same 'experimental feature' warning.

### What is the version of the Cmdlet module you are running?

2.40.  I also tried other versions such as 2.3.0, and 1.12.0 and am received the same warning. 

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Azure Cloud Shell
- [ ] Azure Functions

**Comment by gautamdsheth** [comment]
Closing this as fixed by Microsoft server side change. Was a temporary regression which impacted this.
