### ISSUE TITLE
[BUG] Get-PnPFileSharingLink and Get-PnPFolderSharingLink does not return anything for shared files/folders

### ISSUE THREAD

**Issue by AndersRask** [pnp/powershell#3912]
### Reporting an Issue or Missing Feature
`Get-PnPFileSharingLink`
and
`Get-PnPFolderSharingLink`
does not return anything even when files/folders are shared

### Expected behavior 
When calling the cmdlets
`Get-PnPFileShareingLink`
and
`Get-PnPFolderSharingLink`

I expected to get sharing link kinds for the files/folders (including LinkKind for review sharing according to feature #2949 ) 

When I call the [Microsoft.SharePoint.Client.ObjectSharingInformation]::GetObjectSharingInformation(..) I get the 5 standard sharing links.

What am I doing wrong?

### Actual behavior 
Nothing is returned when calling the cmdlets. If I call the cmdlets with invalid data, they return "Item not found" (expected)

### Steps to reproduce behavior
```
connect-pnponline -url "https://contoso.sharepoint.com/sites/test" -interactive
get-pnplistitem -List Documents | % { Get-PnPFileSharingLink -FileUrl $_["FileRef"]}
```
(nothing is returned even though several files in the doclib are shared)

If I instead call the static method GetObjectSharingInformation(..) i get the link (and all other data left out for this example for brevity)
```
$ctx = Get-PnPContext
get-pnplistitem -List Documents | ? { $_["FSObjType"] -eq 0 } | % {
$SharingInfo = [Microsoft.SharePoint.Client.ObjectSharingInformation]::GetObjectSharingInformation($Ctx, $_, $false, $false, $false, $true, $true, $true, $true)
        $ctx.Load($SharingInfo)
        $ctx.ExecuteQuery()
$SharingInfo.SharingLinks | % { $_.Url }}
```

Example output that shows links are shared:
```
https://contoso.sharepoint.com/:i:/r/sites/test/Shared%20Documents/breach.png?csf=1&web=1
https://contoso.sharepoint.com/:w:/r/sites/test/Shared%20Documents/Document.docx?d=w584a9b0646104a9a95bdc58c446262e8&csf=1&web=1
https://contoso.sharepoint.com/:w:/r/sites/test/Shared%20Documents/Document1.docx?d=wb9ccccfd34d942ba8d0586671fd4e66b&csf=1&web=1
```

for the folder version, it is the same. If i use the above code, a link is shared
`get-pnplistitem -List Documents | ? { $_["FSObjType"] -eq 1 } | % { Get-PnPFolderSharingLink -Folder $_["FileRef"]}`
_(nothing is returned even though folders are shared)_

### What is the version of the Cmdlet module you are running?
2.4.44     nightly    PnP.PowerShell

PSVersion                      7.4.2

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Hmm , not sure.

Works for me :

<img width="732" alt="image" src="https://github.com/pnp/powershell/assets/8832018/6cc15a02-ccbc-4a34-93ad-c006acaadd54">

Also, I am using the "new" Share dialog to share files and folders like this:

<img width="359" alt="image" src="https://github.com/pnp/powershell/assets/8832018/b76ad8d8-038d-436a-bfee-fc6a03aedc44">

This cmdlet to retrieve information for the links generated via this dialog.

Does that clear things ? Maybe try it this way for a certain file and check ?

**Comment by reshmee011** [comment]
@AndersRask , the Get-PnPFileSharingLink and Get-PnPFolderSharingLink return info only when there is an actual link, the format is different, if you go to the "Manage Access" , there will be a links, otherwise it does not return anything if there are no links, although it might have created unique permissions for the file or folder. I started looking into it only 2 weeks ago and not sure whether behaviour changed over the past. I am pondering on the best way to report sharing information.
<img width="325" alt="image" src="https://github.com/pnp/powershell/assets/7693852/f5498eaa-7270-4490-a4af-4567c99b0308">

**Comment by Barbarur** [comment]
MS changed the way how files are shared, MC706173. Now when you invite a user to access the file. This gets direct permissions instead of creating a shared link.
Maybe that's your case?

**Comment by reshmee011** [comment]
Thanks @Barbarur : I don't use sharing that much except and was re exploring after a couple of years to understand functionality and clearly I missed the update MC706173. It makes more sense.

**Comment by reshmee011** [comment]
@AndersRask : I have updated my blog post https://reshmeeauckloo.com/posts/powershell-get-sharing-links-sharepoint/ to include a comparison using CSOM, the PnP cmdlets and REST endpoint. However CSOM only returns all sharing information unfortunately.

**Comment by Barbarur** [comment]
@reshmee011 it's even more weird actually. The new sharing is when you use click on "Share" and then "Invite". But if you use the "Copy link" function, the classic sharing link is still created.
So depending on how you share. User gets direct permissions or through the Shared Link.

**Comment by reshmee011** [comment]
@Barbarur , thanks for explaining the new sharing versus classic sharing. Wonder if it is a feature MS needs to work on to stop the sharing links being created.

**Comment by AndersRask** [comment]
> MS changed the way how files are shared, MC706173. Now when you invite a user to access the file. This gets direct permissions instead of creating a shared link. Maybe that's your case?

Hi @Barbarur 
you are exactly right! 

It works fine when I explicitly use the link.

Microsoft managed to get people even more confused than before with that update :) 

this ticket can be closed

**Comment by AndersRask** [comment]
I was getting access denied when trying to fetch sharing links for a customer. 
Tracking down the code it led me to the List shared method in REST API. Here I noticed that application access is not supported!
https://learn.microsoft.com/en-us/graph/api/insights-list-shared?view=graph-rest-1.0&tabs=http

![image](https://github.com/pnp/powershell/assets/1651150/e31251ef-fbd1-4958-85d4-ba3f136ace02)

I made a feature request on their repo, but I think this would be a good thing to add to the documentation!

Issue:
https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2785
