### ISSUE TITLE
[BUG]User Realm discovery failed error on Connect-PnPOnline command in SharePoint 2016 On-Premises

### ISSUE THREAD

**Issue by uttambobalade** [pnp/powershell#393]
We’ve downloaded the SharePoint Responsive solution from the path - https://github.com/OfficeDev/PnP-Tools/archive/master.zip and ran the PowerShell “Enable-SPResponsiveUI.ps1” on SharePoint 2016 On-Premises server.
We have downloaded the SharePointPnPPowerShell2016 version on the server and ran the PowerShell but we’re getting “User Realm discovery failed error” on the Connect-PnPOnline command. 
Please guide us/suggest any recommendations or solutions.

SharePoint Version – SharePoint 2016 On-Premises 
OS - Windows 

 Thank you.

**Comment by amalwayscharan** [comment]
We're on 2019 On-Premise SharePoint, we're getting the same error message when trying to connect an on-premise site, never happened this before. 

Connect-PnPOnline : User realm discovery failed
At line:1 char:1
+ Connect-PnPOnline -Url [Site-Name]
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-PnPOnline], MsalClientException
    + FullyQualifiedErrorId : Microsoft.Identity.Client.MsalClientException,PnP.PowerShell.Commands.Base.ConnectOnline

**Comment by veronicageek** [comment]
@uttambobalade - As mentioned in the [README.md](https://github.com/pnp/powershell/blob/dev/README.md), this repo is only supporting SharePoint Online. Please open an issue in the original repo where you downloaded the script so they can assist you.

**Comment by uttambobalade** [comment]
Thank you. I will open an issue in the original repo.

**Comment by amalwayscharan** [comment]
> Thank you. I will open an issue in the original repo.

Were you able to use PnP module to connect to any of On-premise SharePoint sites? I wasn't able to since this morning, wondering what the change is.
