### ISSUE TITLE
[BUG] Get-PnPClientSidePage : Access Denied. You do not have permission to perform

### ISSUE THREAD

**Issue by javenu** [pnp/powershell#394]
### Reporting an Issue or Missing Feature
An Issue

### Expected behavior 
Cmdlet `Get-PnPClientSidePage` allows to get SPO page

### Actual behavior 
Access error is raised:
```
Get-PnPClientSidePage : {"odata.error":{"code":"-2147024891,
System.UnauthorizedAccessException","message":{"lang":"en-us","value":"Access denied. You do not have permission to
perform this action or access this resource."}}}
ServerErrorTraceCorrelationId: 4911b19f-404e-0000-d168-af845143a1a5
At line:1 char:13
+  $homePage = Get-PnpClientSidePage -Identity "Home"
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo              :  WriteError:  (:)  [Get-PnPPage], Exception
        + FullyQualifiedErrorId  :  EXCEPTION, PnP.PowerShell.Commands.Pages.GetPage
```

### Steps to reproduce behavior
Connect to SharePoint Online using -UseWebLogin, attempt to get the home page
```
Connect-PnPOnline -Url $Site -UseWebLogin
$homePage = Get-PnPClientSidePage -Identity "Home"
```
### What is the version of the Cmdlet module you are running?
`Manifest 1.3.0 PnP.PowerShell {Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add...}`

I am able to run Get-PnPClientSidePage using legacy SharePointPnPPowerShellOnline
The recent upgrade to 1.3.0 has affected my ability to use PnP PowerShell as a Site Collection Administrator.

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
Hi @javenu - I'm not sure if there's any behind the scenes changes so maybe @erwinvanhunen can confirm, but meanwhile I've tried with an MFA account (using `-UseWebLogin`) who's a Site Collection Admin and I don't see the issue on PS5 or PS7.

![image](https://user-images.githubusercontent.com/25181757/110385607-0f2c3e80-8057-11eb-8742-381a0393fc21.png)

**Comment by javenu** [comment]
@veronicageek - thank you for taking a look.

After installing 1.4.0 today, the issue has been resolved.

```
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.4.0      PnP.PowerShell                      {Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add- 
```

![home](https://user-images.githubusercontent.com/26263645/110686776-a64ae080-8194-11eb-9107-4b46eb1559ca.PNG)
