### ISSUE TITLE
[BUG] Unauthorized Operation Error with PnP PowerShell Cmdlets

### ISSUE THREAD

**Issue by prattay56** [pnp/powershell#3943]
**Bug Report: Unauthorized Operation Error with PnP PowerShell Cmdlets**

**Description:**
When using the `Get-PnPTenant`, `Set-PnPTenant`, `Get-PnPTenantSite`, and `Set-PnPTenantSite` cmdlets, encountering an "unauthorized operation" error. This issue arises consistently across all tenants globally. 

**Error Message:**
Upon execution, the following error is thrown: "Attempted to perform an unauthorized operation." Additionally, when monitoring the network traffic with Fiddler, the error `X-MSDAVEXT_Error: 917656; Access denied. Before opening files in this location, you must first browse to the web site and select the option to login automatically.` is observed.

**Reproducibility:**
The error occurs consistently since May 9, 2024. It is reproducible on various tenants worldwide. 

**Steps to Reproduce:**
1. Execute the `Connect-PnPOnline` cmdlet with the `-ClientId` and `-ClientSecret` parameters to authenticate.
   ```powershell
   Connect-PnPOnline -Url $url -ClientId $id -ClientSecret $sec -Verbose
   ```
2. Attempt to use any of the following cmdlets: `Get-PnPTenant`, `Set-PnPTenant`, `Get-PnPTenantSite`, or `Set-PnPTenantSite`.

Permission of the app:
`<AppPermissionRequests AllowAppOnlyPolicy="true">
  <AppPermissionRequest Scope="http://sharepoint/content/sitecollection" Right="FullControl" />
  <AppPermissionRequest Scope="http://sharepoint/social/sitecollection" Right="FullControl" /> 
</AppPermissionRequests>`

**Expected Behavior:**
The cmdlets should execute without encountering unauthorized operation errors, given valid authentication credentials.

**Actual Behavior:**
The cmdlets consistently throw unauthorized operation errors, hindering their execution.

**Additional Information:**
- The error specifically occurs when using the `-ClientId` and `-ClientSecret` parameters to connect to PnP.
- Interestingly, the `Get-PnPWeb` cmdlet connects to SharePoint sites without any issues, indicating a specific problem with the tenant-related cmdlets.

**Environment:**
- PowerShell Version: [e.g., PSVersion  : 5.1.22621.2506 | PnP PowerShell Cmdlets (1.12.0.0)
- SharePoint Online Environment: [e.g., Office 365]
- Operating System: [e.g., Windows 11]

---

**Comment by veronicageek** [comment]
@prattay56 - There's no issue with those commands when using `2.x`. 
We don't support PS `5.1` and therefore `1.12.x` is not worked on.

**Comment by prattay56** [comment]
Unfortunately the issue persists in latest version

![image](https://github.com/pnp/powershell/assets/74849664/00ddc7b3-b39c-4bb1-9786-5ca097782c61)

**Comment by veronicageek** [comment]
I can query `Get-PnPTenant` with `2.4` and the latest `2.4.62` and get results. Can you please try a different method of auth to first troubleshoot.

**Comment by ndl7** [comment]
We have the same issue using PnP PowerShell.

We have an automated process (PowerShell script as a scheduled task) that uses an Azure app registration with a SharePoint administrator role assigned to it. It connects to SharePoint admin center and runs Get-PnPTenant. It started failing a few months ago with an error "Get-PnPTenant: Attempted to perform an unauthorized operation.". We then assigned Application Sites.Selected permission to the Azure app registration and gave it full control to the SharePoint admin center, but that did not solve the issue. Logging into admin center using an admin account (with -Interactive) and running Get-PnPTenant works fine. Switching to Graph is not an option at this point as it only contains a quarter of functionality we are after.

To solve the issue in OP's post, Application permissions with Sites.FullControl.All need to be granted to Azure app registration, but it's obviously not the right way to work around something that is clearly broken.

PowerShell 7.3.5
PnP.PowerShell 2.5.1-nightly

**Comment by ztrhgf** [comment]
Same issue here.

**Comment by faisaleem-na** [comment]
same issue for me too

**Comment by Barbarur** [comment]
Shouldn't the scope be tenant rather than Site Collection?

**Comment by jherschel77** [comment]
Same issue here, its been months, was hoping it would be fixed by now.   I am trying to connect to get list of all site collections and they cycle through.  The script worked for over a year and then all of the sudden didn't earlier this year.  I upgraded PowerShell as well as PnP.PowerShell and still getting this error

**Comment by adab3** [comment]
Same problem

**Comment by nicodecleyre** [comment]
> Same problem

You need to give your Entra App registration full control in order to get the `Get-PnPTenantSite` command working. That is:
- SharePoint > AllSites.FullControl for delegated permissions
- SharePoint > Sites.FullControl.All for Application permissions

**Comment by Judedouard3** [comment]
> We have the same issue using PnP PowerShell.
> 
> We have an automated process (PowerShell script as a scheduled task) that uses an Azure app registration with a SharePoint administrator role assigned to it. It connects to SharePoint admin center and runs Get-PnPTenant. It started failing a few months ago with an error "Get-PnPTenant: Attempted to perform an unauthorized operation.". We then assigned Application Sites.Selected permission to the Azure app registration and gave it full control to the SharePoint admin center, but that did not solve the issue. Logging into admin center using an admin account (with -Interactive) and running Get-PnPTenant works fine. Switching to Graph is not an option at this point as it only contains a quarter of functionality we are after.
> 
> To solve the issue in OP's post, Application permissions with Sites.FullControl.All need to be granted to Azure app registration, but it's obviously not the right way to work around something that is clearly broken.
> 
> PowerShell 7.3.5 PnP.PowerShell 2.5.1-nightly

do you still have that script?

**Comment by hajdukm** [comment]
> > Same problem
> 
> You need to give your Entra App registration full control in order to get the `Get-PnPTenantSite` command working. That is:
> 
> * SharePoint > AllSites.FullControl for delegated permissions
> * SharePoint > Sites.FullControl.All for Application permissions

I have assigned mentioned permissions to PnP app

<img width="2156" height="452" alt="Image" src="https://github.com/user-attachments/assets/61c8cdc6-2b9f-4fe9-a738-17408540fdbe" />

, but still having the same issue with 



Name                           Value
----                           -----
PSVersion                      7.5.0

PS D:\Scripts> get-module *pnp*         

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   3.1.0                 PnP.PowerShell                      {Add-PnPAlert, Add-PnPApp, Add-PnPApplicationCustomizer, Add-PnPAvailableSiteClassification…}


Global Admin, SharePoint Admin, Teams and Group admin and more... but error I get is 

PS D:\Scripts>     Remove-PnPTenantSite -Url $siteUrl -Force #-SkipRecycleBin
Remove-PnPTenantSite: Attempted to perform an unauthorized operation.
