### ISSUE TITLE
[BUG] Error in Get-PnPContainer : "The attempted operation is prohibited because it exceeds the list view threshold"

### ISSUE THREAD

**Issue by MSFT-klpinhac** [pnp/powershell#3970]
### Reporting an Issue or Missing Feature
while the cmdlet **Get-PnPContainer** works fine in most tenants, the attempt to retrieve the Loop-Workspaces in a large tenant has returned the error "The attempted operation is prohibited because it exceeds the list view threshold" 
![error_get-pnpcontainer](https://github.com/pnp/powershell/assets/84438062/ee601d8b-e0b2-40df-8499-df23c2172233)

### Expected behavior 
I would expect a list of containers / Loop Workspaces to be returned, no matter how large or small the tenant

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 2.4.0
![image](https://github.com/pnp/powershell/assets/84438062/714f6505-444f-44be-96c1-a55bce6cd619)

### Which operating system/environment are you running PnP PowerShell on?
- Windows / PowerShell 7.4.2
![image](https://github.com/pnp/powershell/assets/84438062/3992e3c5-832b-4a70-a637-1ced66857296)

**Comment by reshmee011** [comment]
@MSFT-klpinhac , can you please try get-spocontainer using SharePoint Online PowerShell to see if you get the same behaviour? I am unable to test your scenario as I don't have so many Loop workspaces on my environment.

**Comment by MSFT-klpinhac** [comment]
yes, Get-SPOContainer using SharePoint Online PowerShell returns the same error
<img width="652" alt="get-spocontainer" src="https://github.com/pnp/powershell/assets/84438062/72b8c158-b8f2-475c-8c39-c5fb1109d8a7">

**Comment by gautamdsheth** [comment]
@MSFT-klpinhac - as mentioned above, please use the approach @reshmee011 mentioned above which should work with large tenants.

**Comment by MSFT-klpinhac** [comment]
The cmdlet Get-PnPContainer used with parameter "-Paged" does return the same error:
![image](https://github.com/pnp/powershell/assets/84438062/8f6a6b49-7b12-4c80-84d2-0e1e67fb972b)

The cmdlet Get-SPOContainer used with parameter "-Paged" is returning the same error as well:
![image](https://github.com/pnp/powershell/assets/84438062/3d9b03cc-7acc-4e56-9585-056919146b8d)

How can i retrieve a PagingToken / <Token String>, so that i can use it with parameter "-PagingToken" ?

**Comment by gautamdsheth** [comment]
@reshmee011 @MSFT-klpinhac - have updated the cmdlet , it will now return the pagination token as well if -Paged is specified. Will be available in tomorrow's nightly build as well as the next major release whenever we do that .

Please let us know how it works you now with this update/fix.

**Comment by MSFT-klpinhac** [comment]
that nightly build is returning another error:
![image (1)](https://github.com/pnp/powershell/assets/84438062/7b20595a-ae79-4286-a922-48730e59a21e)

**Comment by reshmee011** [comment]
@MSFT-klpinhac : can you please a microsoft case for microsoft to look into the issue using -Paged parameter with cmdlet Get-SPOContainer returning the error exceeding list view threshold. Most like if the underlying endpoint is fixed by Microsoft, PnP PowerShell cmdlet will work too as they call the same endpoint in the background. 
Unfortunately I don't have a proper set up to test the issues you are facing. Out of curiosity , how many Loop workspaces you have in total?

**Comment by MSFT-klpinhac** [comment]
Support case has been created, @reshmee011 
How many Loop workspaces are in that tenant is unknown - apparently more then 5000 😄
