### ISSUE TITLE
[BUG] Get-PnPFlow throws an error "The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing."

### ISSUE THREAD

**Issue by Rokhanna1** [pnp/powershell#3972]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by Rokhanna1** [comment]
I keep getting below error regardless of the PNP flow commands I try. Please fix this asap.

<img width="809" alt="Screenshot 2024-05-24 151043" src="https://github.com/pnp/powershell/assets/170717931/df9d92c1-495d-47ce-b744-535e99ae2036">

**Comment by markgort86** [comment]
This issue is reported before, and is fixed in the Nightly buil. I just tested the workaround that is also provided here: https://github.com/pnp/powershell/issues/3794.

The fix is not available in the Last Version, and I have no idea when the community is publishing a new version.

**Comment by jackpoz** [comment]
You can install nightly builds using this command
```
Install-Module -Name PnP.PowerShell -AllowPrerelease
```
It's the same visible at https://www.powershellgallery.com/packages/PnP.PowerShell/2.4.74-nightly after clicking the most recent version (2.4.74-nightly is the latest version at the time of writing this)

**Comment by Rokhanna1** [comment]
Hello Gautam,

Thanks this worked fine.


Regards
Rohit Khanna



BV_C2_Internal

**Comment by Haiqi-Wu** [comment]
Can anyone tell me when this update will be released to a stable version please?

**Comment by veronicageek** [comment]
@Haiqi-Wu - We are working on it, and will release a major version very soon.
