### ISSUE TITLE
[BUG] Set-PnPHomeSite throws an error when you have multiple Viva Connections

### ISSUE THREAD

**Issue by ryder-cayden** [pnp/powershell#3978]
### Reporting an Issue
Running the Set-PnPHomeSite when you have multiple Viva Connections throws the following error:
"Set-PnPHomeSite: Operation is not valid due to the current state of the object."

### Expected behavior 
The Home site should be configured without any error.

### Actual behavior 
There is an error when running that cmdlet

### Steps to reproduce behavior
1. Go to Office 365 admin center -> Settings -> Viva -> Viva connections
2. Ensure you have multiple Viva Connections. In my case I have the following:
-  https://tenantName.sharepoint.com
- https://1nds5r.sharepoint.com/sites/intranet
3. Open up PowerShell and run the following command:
`Set-PnpHomeSite -HomeSiteUrl https://tenantName.sharepoint.com/sites/intranet`
(please change the HomeSiteUrl parameter accordingly)
4. The following exception will be thrown:
Set-PnPHomeSite: Operation is not valid due to the current state of the object.

### What is the version of the Cmdlet module you are running?
2.3.0 and 2.4.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by reshmee011** [comment]
Hi @ryder-cayden 
By any chance are you able to use SharePoint Online PowerShell cmdlet Set-SPOHomeSite to set the Home Site? If yes , can please confirm whether you get the same error as using set-pnphomesite?

**Comment by ryder-cayden** [comment]
Hi @reshmee011... The Set-SPOHomeSite works fine based on my testing. I did not get the same error.

**Comment by reshmee011** [comment]
I could reproduce the issue with set-pnphomesite. I checked the code, nothing unusual. It used to work in the past. I will try to find out why it is not working.

**Comment by gautamdsheth** [comment]
@reshmee011 @ryder-cayden - this issue has been fixed now. Will be available in tomorrow's nightly builds and the next major one when we release it. Thanks for reporting and looking into it.

**Comment by reshmee011** [comment]
Thanks so much @gautamdsheth for the fix.
