### ISSUE TITLE
[BUG] Add-PnPPage does not accept names with whitespaces

### ISSUE THREAD

**Issue by HeKr09** [pnp/powershell#400]
### Reporting an Issue or Missing Feature
I want to create a page with Add-PnPPage but get an error while creating pages with whitespaces.

### Expected behavior 
I expect to create a page with whitespaces within the name.

### Actual behavior 
The PowerShell throws an error, although the page got created.

```
Add-PnPPage : Object reference not set to an instance of an object.
At D:\TFS\Create-ContentTemplate.ps1:455 char:17
+ ...     $page = Add-PnPPage -Name $Template -LayoutType Article -PromoteA ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Add-PnPPage], NullReferenceException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Pages.AddPage
D:\TFS\Create-ContentTemplate.ps1 : Page is null
At line:1 char:1
+ .\Create-ContentTemplate.ps1 -Template 'Content Template full scre ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Create-ContentTemplate.ps1
```

The page name is "Content Template full screen". After the error the page is created and named as "Content+Template+full+screen".
If I replace the whitespaces with "%20" the error persists but the site name is correct.
If I delete the whitespaces the error vanishs but the site name is of course not correct.

### Steps to reproduce behavior
```
Connect-PnPOnline -Url [URL] -Interactive
$Template = 'Content Template full screen'
$page = Add-PnPPage -Name $Template -LayoutType Article -PromoteAs Template
```

### What is the version of the Cmdlet module you are running?
1.3.0.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Hey @HeKr09 , this has been fixed in the nightlies. 
Could you use `Install-Module -Name PnP.PowerShell -AllowPrerelease` for this and check ? 
Of course, if you can't use it for production scenarios, would suggest that you wait for `1.4.0` release to be available.

**Comment by HeKr09** [comment]
Sorry about a stupid question: Do you know the release date?

**Comment by gautamdsheth** [comment]
Not a stupid question at all, was a totally valid issue :) 
Please reopen the issue if it happens again !
About the release date, I don't have ETA but it would be within weeks.
