### ISSUE TITLE
[FEATURE] It would be nice to have a command ready to clear the label given by the Set-PnPSiteSensitivityLabel command

### ISSUE THREAD

**Issue by yoinuma** [pnp/powershell#4004]
The Set-PnPSiteSensitivityLabel command can be used to label a site with respect to the site. We find it very useful to be able to label sites with this command when there are a large number of sites.
However, if you want to remove the label after it has been assigned with this command, the only way to do so is to manually change the label from the browser. It would be nice if there was a way to do this with a command.

**Comment by gautamdsheth** [comment]
Hello @yoinuma , we have `Remove-PnPSiteSensitivityLabel` cmdlet which should work for you.

**Comment by yoinuma** [comment]
Thanks for the quick reply!
I see that the command already existed. Sorry for the lack of confirmation, I could not find the command Remove-PnPSiteSensitivityLabel on the https://pnp.github.io/powershell/cmdlets/ reference, which is why I asked the question.
I have confirmed that the Remove-PnPSiteSensitivityLabel command works as expected in my test environment.
Thanks!
