### ISSUE TITLE
[BUG] Get-PnPRecycleBinItem exceeds the list view threshold 

### ISSUE THREAD

**Issue by PRusakPL** [pnp/powershell#4010]
### Reporting an Issue or Missing Feature
In my site collection I have a lot of items in Firt Stage Recycle Bin (approx 150k)
When using following command
```powershell
Restore-PnPRecycleBinItem -Connection $siteConnection -Identity "$(\$item.Id)" -RowLimit 1 -Force | Out-Null
``` 
I receive error:

*The attempted operation is prohibited because it exceeds the list view threshold enforced by the administrator.*

### Expected behavior 
Command should run without error and item should be restored from Recycle Bin

### Actual behavior 
Command fails and restoration also fails

### Steps to reproduce behavior
Make sure you have more than 5k items in Recycle Bin.
Try to restore single item using Command mentioned above.

### What is the version of the Cmdlet module you are running?
2.4.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by markgort86** [comment]
See #3382 and also #3491 where the same issues are described. 

Check also the comments, there should be a work-around available.

**Comment by veronicageek** [comment]
Closing as duplicate as @markgort86 mentioned.
