### ISSUE TITLE
Set-PnPBuiltInSiteTemplateSettings Template Identity not valid

### ISSUE THREAD

**Issue by a-goo** [pnp/powershell#4027]
Despite copyting the commands and template ID directly from the commandlet page: https://pnp.github.io/powershell/cmdlets/Set-PnPBuiltInSiteTemplateSettings.html it fails.

_Set-PnPBuiltInSiteTemplateSettings -Identity a30fef54-a4e5-4beb-a8b5-962c528d753a -IsHidden $false
**Set-PnPBuiltInSiteTemplateSettings: This is not a valid site template ID. Get the ID from "https://go.microsoft.com/fwlink/?linkid=2169454" and and try again.**_

![image](https://github.com/pnp/powershell/assets/105272899/68675947-b10e-45b6-b55d-6cd8ca01b1e7)

![image](https://github.com/pnp/powershell/assets/105272899/f48de6cc-0a3d-4410-9dc1-d2d685b20c7c)

Expected behavior - the actual information that MS explicitly provides should actually work.

Actual behavior  - it's broken.

Steps to reproduce behaviour - run the command as above.

Version of the Cmdlet module I'm running - "PnP.PowerShell 2.4.0

Running PnP PowerShell on Windows 11

**Comment by a-goo** [comment]
Thanks for your reply @jackpoz. 

My intention is to hide all of the templates (this works according to the giving example), and then re-enable the Topic template (broken - error invalid template). 

Even if the problem is SPO server side there's still a problem. Either the PnP documentation is incorrect and needs updating, or the SPO server side hasn't been updated and needs fixing. 
Either way - this needs fixing by Microsoft. It's pretty poor quality control to publish PnP documentation that obviously hasn't been tested fully.

**Comment by veronicageek** [comment]
@jackpoz - Thanks a lot for your help and other contributions to this repo.

@a-goo - This repo is community driven and not managed by Microsoft. The issue being on the server side, there's nothing we can do until it's fixed by MSFT. Then it will work again with PnP.
