### ISSUE TITLE
Remove-PnPTeamsChannel throws an exception, the team channel is deleted though

### ISSUE THREAD

**Issue by frbori** [pnp/powershell#4035]
### Reporting an Issue or Missing Feature
Issue about cmdlet "Remove-PnPTeamsChannel".

### Expected behavior 
The team channel to be removed, without throwing any exceptions.

### Actual behavior 
The team channel is actually removed, but the cmdlet returns an exception:
"Remove-PnPTeamsChannel: Channel not found".

### Steps to reproduce behavior
Remove-PnPTeamsChannel -Team $team.GroupId -Identity $channel.Id

### What is the version of the Cmdlet module you are running?
2.4.0

### Which operating system/environment are you running PnP PowerShell on?
- Windows

**Comment by jackpoz** [comment]
I'll open a PR to fix this, the message "Channel not found" is shown when the channel has been deleted successfully, so you can ignore that error for the time being.

**Comment by frbori** [comment]
Great! Thanks for your help.

**Comment by gautamdsheth** [comment]
@frbori - this issue has been fixed by @jackpoz , will be available in tomorrow's nightly builds as well as the next major release. 

Thanks for raising this and thanks for fixing it :)
