### ISSUE TITLE
[BUG] Documentation issue for Copy-PnPFile regarding SharePoint to OneDrive capability

### ISSUE THREAD

**Issue by EdAlexander** [pnp/powershell#4037]
### Reporting an Issue with documentation
Documentation for Copy-PnPFile states that copying files and folders between SharePoint libraries and OneDrive for Business is not possible but works fine in my environment.  Is the documentation in error or out of date?

### Expected behavior 
According to the documentation at [Copy-PnpFile Documentation](https://pnp.github.io/powershell/cmdlets/Copy-PnPFile.html) this should not work. 

From Description: " It is currently not possible to copy files between a OneDrive for Business site to SharePoint or vice versa"

### Actual behavior 
folder and contents are copied from SharePoint library to personal OneDrive in the specified target folder.

### Steps to reproduce behavior
The following script is working in my environment.
```
$sourceSiteUrl = "https://tenant.sharepoint.com/sites/University"
$sourceRelativeSiteUrl = "/sites/University/Shared Documents/New Hire Onboarding"
$sourceLibrary = "Shared Documents"
$sourceFolder = "New Hire Onboarding"
$destinationSiteUrl = "https://tenant-my.sharepoint.com/personal/user_domain_com"
$destinationRelativeSiteUrl = "https://tenant-my.sharepoint.com/personal/user_domain_com/Documents/ArchiveTarget"
$destinationLibrary = "Documents"
$destinationFolder = "ArchiveTarget"
Connect-PnPOnline -Url $sourceSiteUrl -Interactive
$sourceConnection = Get-PnpConnection
$sourceCtx = Get-PnpContext
Set-PnPContext -Context $sourceCtx
$files = Get-PnPFolderItem -FolderSiteRelativeUrl "$sourceLibrary/$sourceFolder" -ItemType File -Connection $sourceConnection
$subFolders = Get-PnPFolderItem -FolderSiteRelativeUrl "$sourceLibrary/$sourceFolder" -ItemType Folder -Connection $sourceConnection
Copy-PnPFile -SourceUrl $sourceRelativeSiteUrl -TargetUrl $destinationRelativeSiteUrl -Overwrite -Force

```

### What is the version of the Cmdlet module you are running?
2.4.0

### Which operating system/environment are you running PnP PowerShell on?
Windows

**Comment by veronicageek** [comment]
Thanks for raising this @EdAlexander - It does indeed work following a change we made in a previous version (issue #1720).
I've updated the documentation 👍🏻
