### ISSUE TITLE
[BUG] Get-PnPTenantSite: The property or field 'LoopOverrideSharingCapability' has not been initialized. 

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#4041]
### Reporting an Issue or Missing Feature
Running ```Get-PnPTenantSite``` returns an error "The property or field 'LoopOverrideSharingCapability' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested."

### Expected behavior 
```Get-PnPTenantSite``` should return a list of sites,
### Actual behavior 
```Get-PnPTenantSite``` returns an error "The property or field 'LoopOverrideSharingCapability' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested."
![image](https://github.com/pnp/powershell/assets/5260172/222dd54e-f097-4314-a01a-56f30bcbee86)

### Steps to reproduce behavior
```
Connect-PnPOnline
Get-PnPTenantSite
```
### What is the version of the Cmdlet module you are running?
```
PnP.PowerShell 2.4.101
PSVersion 7.4.3
OS Microsoft Windows 10.0.19045
```
### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@gautamdsheth @KoenZomers - I can reproduce this issue with the **nightly** releases
- `2.4.100`
- `2.4.101` - from this issue
- `2.4.102`

But works fine with major `2.4.0`

**Comment by gautamdsheth** [comment]
hi @YuriySamorodov , thanks for catching this, will be fixed in tomorrow's nightly.
