### ISSUE TITLE
[BUG] Get-PnPTeamsChannel 'MembershipType' property returns 'unknownFutureValue' if Teams Channel is a Shared Channel

### ISSUE THREAD

**Issue by djtrustgod** [pnp/powershell#4043]
### Expected behavior 
Returned value should be 'Shared' 

### Actual behavior 
Returned value is 'unknownFutureValue' 

### Steps to reproduce behavior
`$channel = Get-PnPTeamsChannel -Team "Team 1" -Identity "Shared Channel 1"`
`$channel.MembershipType`

### What is the version of the Cmdlet module you are running?
2.4.0

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by jackpoz** [comment]
According to https://learn.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0#properties :
>Note that you must use the Prefer: include-unknown-enum-members request header to get the following value in this [evolvable enum](https://learn.microsoft.com/en-us/graph/best-practices-concept#handling-future-members-in-evolvable-enumerations): shared.

Testing this in Graph Explorer without and with the `include-unknown-enum-members` header:
1. Without `include-unknown-enum-members`
![image](https://github.com/pnp/powershell/assets/1153754/095e071e-e56c-45f4-8bab-b3ba0136a8b4)

2. With `include-unknown-enum-members`
![image](https://github.com/pnp/powershell/assets/1153754/928f42b1-e8c4-44b7-b1df-aa4d18fedd97)

A bit unsure if this header should be added everywhere when calling `GET /teams/{team-id}/channels` as that will change the value returned, so letting the maintainers decide.

**Comment by jackpoz** [comment]
I opened a PR at https://github.com/pnp/powershell/pull/4054 with the least invasive changes, include the header only when needed.
