### ISSUE TITLE
[BUG] Get-PnPMicrosoft365Group -IncludeSiteUrl -IncludeOwners errors due to token expiration on tenants with 4K+ M365 Groups

### ISSUE THREAD

**Issue by joerodgers** [pnp/powershell#4051]
### Reporting an Issue or Missing Feature
Due to the access token being passed in as a string to the _Microsoft365GroupsUtility.GetGroupsAsync_ function, on large tenants the operation can take several minutes to complete, sometimes exceeding the expiration time of the provided (stale?) access token.

```PowerShell
Get-PnPMicrosoft365Group -IncludeSiteUrl -IncludeOwners
```
### Expected behavior 
The cmdlet will automatically refresh any expired access tokens and allow the operation to succeeded.  I potential short term option would be to force a token refresh before passing it over to _Microsoft365GroupsUtility.GetGroupsAsync_, allowing a much longer period of time before token expiration.

### What is the version of the Cmdlet module you are running?
1.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
@joerodgers - can you please try with the latest version and let us know ? Its quite old and the latest version is 2.4.0 which has quite a few changes and updates.

**Comment by tomtorggler** [comment]
I might have the same issue, `Get-PnPMicrosoft365Group` hangs when I use the switch `-IncludeSiteUrl`.

I tried 2.5.0 and 2.5.4-nightly on Windows.

**Comment by veronicageek** [comment]
Closing due to lack of response from the original author. Please open a new issue if you still experience a similar issue with a newer version of the module.
