### ISSUE TITLE
[BUG] Get-PnPGroupPermissions On Premises 401 UNAUTHORIZED

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#406]
### Reporting an Issue or Missing Feature
Reporting a bug

### Expected behavior 
I am farm admin so I expect no errors from Get-PnPGroupPermissions cmdlet

### Actual behavior 
Get-PnPGroupPermissions gives 401 unauthorized although I am a farm admin
![image](https://user-images.githubusercontent.com/5260172/110661354-88ea3680-81d5-11eb-827d-3a84044dde0d.png)

### Steps to reproduce behavior
```
$PnPConnection = Connect-PnPOnline $url -TransformationOnPrem -CurrentCredentials -ReturnConnection
$SubWebs = Get-PnPSubWebs -Recurse -Connection $PnPConnection
foreach ( $web in $SubWebs[0] ) {
    $PnPConnection = Connect-PnPOnline -Url $web.Url -TransformationOnPrem -CurrentCredentials -ReturnConnection
    $PnPOwners = Get-PnPGroup -AssociatedOwnerGroup -Connection $PnPConnection
    Get-PnPGroupPermissions -Identity $PnPOwners -Connection $PnPConnection
    }
}

$Error[-1].Exception

ErrorRecord    : 401 UNAUTHORIZED
TargetSite     : Void ProcessRecord()
StackTrace     :    at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in
                 D:\a\powershell\powershell\src\Commands\Base\PnPSharePointCmdlet.cs:line 70
                    at System.Management.Automation.Cmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Message        : 401 UNAUTHORIZED
Data           : {}
InnerException :
HelpLink       :
Source         : PnP.PowerShell
HResult        : -2146233079
```

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
I am using PnP.PowerShell 1.3.24

![image](https://user-images.githubusercontent.com/5260172/110661667-dcf51b00-81d5-11eb-812f-96de8ab9e824.png)

![image](https://user-images.githubusercontent.com/5260172/110661571-c353d380-81d5-11eb-8078-ec663db94bec.png)

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
Hi, only a limited set of cmdlets will work on-premises for the sole reason of the transformation of content. Get-PnPGroupPermissions for instance requires access to an online environment as it uses more modern APIs than what is available for SharePoint on-premises. We have no intention to fully support on-premises either with the new PnP PowerShell. If you require other functionality we advice you to revert to the legacy releases of PnP PowerShell for the specific on-prem version you're running. They are still available from the PowerShell Gallery.

**Comment by YuriySamorodov** [comment]
Thanks @erwinvanhunen 

For those who might come across the same issue I just located a workaround
https://github.com/pnp/PnP-PowerShell/issues/2471
https://stackoverflow.com/questions/59352609/fetch-user-roles-and-permissions-for-sharepoint-online-using-pnp
````
foreach ( $web in $SubWebs ) {
    $PnPConnection = Connect-PnPOnline -Url $web.Url -TransformationOnPrem -CurrentCredentials -ReturnConnection
    foreach($ra in $web.RoleAssignments) {
        $member = $ra.Member
        $loginName = get-pnpproperty -ClientObject $member -Property LoginName
        $rolebindings = get-pnpproperty -ClientObject $ra -Property RoleDefinitionBindings
    }
}
````
