### ISSUE TITLE
[BUG] Add-PnPPageSection throws error "Invalid character in Xml String."

### ISSUE THREAD

**Issue by exensio-rori** [pnp/powershell#4073]
### Reporting an Issue or Missing Feature
"Add-PnPPageSection" does not add the new section and ends with error message.

### Expected behavior 
"Add-PnPPageSection" adds the new section with the specified properties.

### Actual behavior 
`Error while adding the web part: Invalid character in Xml String. Chr 2 is illegal.`

### Steps to reproduce behavior
SharePoint page with Text web part which contains the following text:
`Test`
(these are 5 characters, four of them are 'normal' and one of them is a special character or control character)
`Add-PnPPageSection -Page <myPage> -SectionTemplate OneColumn`

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 2.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by exensio-rori** [comment]
Entering the control character here in GitHub is not possible (for me).

**Comment by markgort86** [comment]
Is the problem also available with the most recent version of PnP.PowerShell? The community just released version 2.5.0
See: https://www.powershellgallery.com/packages/PnP.PowerShell/2.5.0. 

You can install this version by using `Install-Module -Name PnP.PowerShell -RequiredVersion 2.5.0`
