### ISSUE TITLE
[BUG] Get-PnPUnifedGroup Doesn't Exist

### ISSUE THREAD

**Issue by danmyhre** [pnp/powershell#4090]
### Reporting an Issue or Missing Feature
Missing Feature

### Expected behavior 
Cmdlet Reference:
https://pnp.github.io/powershell/cmdlets/Get-PnPUnifiedGroup.html

### Actual behavior 
The term 'get-pnpunifiedgroup' is not recognized as a name of a cmdlet, function, script file, or executable program.

### Steps to reproduce behavior
Connect to the SPO admin center
Run Get-PnPUnifiedGroup

### What is the version of the Cmdlet module you are running?
2.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by jackpoz** [comment]
The command has been renamed to [Get-PnPMicrosoft365Group](https://pnp.github.io/powershell/cmdlets/Get-PnPMicrosoft365Group.html) a while ago. You can use this command instead 😃 

The page [Get-PnPUnifiedGroup](https://pnp.github.io/powershell/cmdlets/Get-PnPUnifiedGroup.html) seems to be something old that has not been deleted yet (and should probably be deleted).

**Comment by gautamdsheth** [comment]
Thanks for bringing this up. 
Have deleted this page.
The cmdlet to use is `Get-PnPMicrosoft365Group`.
