### ISSUE TITLE
[BUG] Set-PnPPage Does not Update Thumbnail

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#4100]
### Reporting an Issue or Missing Feature
This is a bug

### Expected behavior 
When running cmdlets like `Set-PnPPage -Publish`it should not only  publish a page but also update a page thumbnail 

### Actual behavior 
Right now `Set-PnPPage -Publish` will not trigger updating a thumbnail. However, when pressing a button "Update news" SPO will also update a thumbnail on /_layouts/15/news.aspx page
![CleanShot 2024-07-18 at 21 01 04](https://github.com/user-attachments/assets/ff677536-6c75-43a4-855a-6b654709a23e)

Looks like `$page.FieldValues.BannerImageUrl.Description` does not get updated.
Have tried the following already:

- `Set-PnPPage -Publish`
- `Set-PnPFileCheckedIn; Set-PnPFileCheckedOut
- $page = get-PnPListItem -List SitePages ; $page.File.Publish("Published") ; Invoke-PnPQuery
- ($page = Get-PnPPage page.aspx ; $page.Save() ; $page.Publish()

### Steps to reproduce behavior

1. Create a page in SharePoint Online
2. Add an image in a web part
3. Save a page
4. Rename a folder image is in
5. Navigate to /_layouts/15/news.aspx 
6. You should notice a blank thumbnail
![CleanShot 2024-07-18 at 21 04 49](https://github.com/user-attachments/assets/e5cdddcb-958a-43ac-aac8-964faa5819d3)

7. Navigate to the page and put it on edit, then save the page
8. Navigate back to /_layouts/15/news.aspx Thumbnail should get updated.

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
`PnP.PowerShell 2.5.7`

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
@YuriySamorodov - this is working as designed. To specify the thumbnail image, you need to use `-ThumbnailUrl` parameter.

**Comment by YuriySamorodov** [comment]
Hi, @gautamdsheth .This is exactly the problem I see. 
`Set-PnPPage -identity $p.FieldValues.FileLeafRef -ThumbnailUrl $thumbnailURL -Publish` **did not work** and I had to update `BannerImageUrl` instead to let thumbnails get updated properly

```
foreach ($p in $pages ) {
$thumbnailOld = $p.FieldValues.BannerImageUrl.Description ;
$thumbnailNew = $thumbnailOld -replace "%2FTemporary%20Assets%2520Location%2F","%2FAssets%2520Location%2F"
if ( $thumbnailOld -like "*Assets%2520*" ) {
$p.FieldValues.BannerImageUrl.Description
Set-PnPListItem -Identity $p.Id -Values @{ "BannerImageUrl" = $thumbnailNew  } -List SitePages -UpdateType SystemUpdate
}
}
```
