### ISSUE TITLE
Get-PnPListItem -List "Documents" -Id 2 | Get-PnPFileSharingLink  throwing error

### ISSUE THREAD

**Issue by reshmee011** [pnp/powershell#4105]
### Reporting an Issue or Missing Feature
Issue

When using Get-PnPFileSharingLink  within pipe as described in the documentation `\documentation\Get-PnPFileSharingLink.md`, instead of returning the sharing links, an error is produced.

Get-PnPListItem -List "Documents" -Id 2 | Get-PnPFileSharingLink  throwing error
Get-PnPFileSharingLink: Object reference not set to an instance of an object on server. The object is associated with property File.

 Get-PnPListItem -List "Documents" | Get-PnPFileSharingLink
Get-PnPFileSharingLink: Object reference not set to an instance of an object on server. The object is associated with property File.

### Expected behavior 
Sharing links to be returned

### Actual behavior 
Error is thrown, Get-PnPFileSharingLink: Object reference not set to an instance of an object on server. The object is associated with property File.

### Steps to reproduce behavior

```
connect-pnponline -url <Url>  -Interactive
 Get-PnPListItem -List "Documents" | Get-PnPFileSharingLink
```
### What is the version of the Cmdlet module you are running?
2.5.25

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows

**Comment by gautamdsheth** [comment]
Thanks @reshmee011 , have fixed the issue, will be available in tomorrow's builds

**Comment by reshmee011** [comment]
@gautamdsheth , thanks for looking into the issue. 

<img width="767" alt="image" src="https://github.com/user-attachments/assets/b6cbd405-5658-428c-9bc1-8cd6e184cf1c">

Unfortunately the issue still exists with version 2.7.1.

**Comment by gautamdsheth** [comment]
Thanks @reshmee011 , have merged another fix for this, hopefully will work now with tomorrow's nightly builds

**Comment by reshmee011** [comment]
@gautamdsheth : Thanks so much for the fix, it is working now, if the sharing link is created at the folder level, all items within the folder inherits the sharing links and the `get-pnplistitem -list "Documents" | get-pnpfilesharinglink` returns same sharing links for all the files within the folder. It is working as described in the documentation.
