### ISSUE TITLE
[BUG]Lists created by New-PnPList cannot have custom powerapp forms

### ISSUE THREAD

**Issue by johnstuartfinance** [pnp/powershell#4110]
### Reporting an Issue or Missing Feature
When I attempt to publish a custom PowerApps form into a list that was created by the New-PnPList cmdlet, nothing is published. There are no errors reported by PowerApps, nor on the sharepoint site. However, when I create a list using the SPO ui, custom powerapps forms appear.

### Expected behavior 
The cmdlet runs as expected, a new list is created. However, newly customized powerapp forms will not appear.

### Actual behavior 
The lists form does not change.

### Steps to reproduce behavior
The cmdlet I use is:
New-PnPList -Title  $ListName -Url "lists/$ListInternalName" -Template GenericList -EnableVersioning:$true -OnQuickLaunch:$false -Connection $cn

The steps I take to create a custom form are as follows:
Click "Integrate" > "Power Apps" > "Customize forms"
When the power apps window opens and loads, I save the form as is with no changes, and click publish twice.
I go back to the list, wait a few minutes (have waited a full 24 hours) and refresh
Click the New button

As noted, the custom form does not appear.

### What is the version of the Cmdlet module you are running?
2.4.0

### Which operating system/environment are you running PnP PowerShell on?
Windows

**Comment by johnstuartfinance** [comment]
Looking at the properties, the only thing I can see is that the property called ObjectVersion is 4 whereas lists created by the UI are 5.

**Comment by veronicageek** [comment]
Closing due to lack of response.
