### ISSUE TITLE
[FEATURE] Get-PnPTenant does not include OnedriveSharingCapability and GuestSharingGroupAllowListInTenantByPrincipalIdentity fields

### ISSUE THREAD

**Issue by tkol2022** [pnp/powershell#4111]
**Is your feature request related to a problem? Please describe.**
I tested PnP.Powershell release 2.5.0 and I don't see the fields below being retrieved with Get-PnPTenant.

- OnedriveSharingCapability
![image](https://github.com/user-attachments/assets/e0fec208-2bd1-456d-8409-b1892790ebc7)

- GuestSharingGroupAllowListInTenantByPrincipalIdentity
![image](https://github.com/user-attachments/assets/5e474492-0bf3-42e0-a084-cd247e55ab9d)

**Describe the solution you'd like**
Would like to see the fields returned by the cmdlet.

**Comment by gautamdsheth** [comment]
@tkol2022 , the support for these 2 parameters has been added now by @reshmee011 . It will be available in tomorrow's nightly builds as well as the next major version

**Comment by tkol2022** [comment]
Excellent. We appreciate you all adding them!
