### ISSUE TITLE
[BUG] In the Get-PnPTeamsChannelFilesFolder (and maybe elsewhere) Format  Exception in JSON, size type is wrong in model

### ISSUE THREAD

**Issue by sabey2000** [pnp/powershell#4126]
In the Get-PnPTeamsChannelFilesFolder, and maybe at other places. 

### Reporting an Issue or Missing Feature
I have some of my teams and channels which the size that goes over the maximum of a [int].  Right now I have a case from my graph output : 

{
    "id": "01YI54PWSELRRZ",
    "createdDateTime": "0001-01-01T00:00:00Z",
    "lastModifiedDateTime": "2024-07-26T19:47:19Z",
    "name": "root",
    "webUrl": "https://xxxxx.sharepoint.com/sites/channel/Shared%20Documents",
    "size": 4257182348,
    "parentReference": {
        "driveId": "xxxxx",
        "driveType": "documentLibrary"
    },
    "fileSystemInfo": {
        "createdDateTime": "2024-06-16T05:57:37Z",
        "lastModifiedDateTime": "2024-07-26T19:47:19Z"
    },
    "folder": {
        "childCount": 3
    }
}

So the command fail.

### Expected behavior 
Getting the output of the channel

### Actual behavior 
Nothing at all, no return no error message even in verbose or debug mode.  The only I find out the issue is by running the module in debug mode in my visual studio and saw that the object you use is not correct : file : TeamsChannelFolder.cs

    public partial class TeamsChannelFilesFolder
    {        
        public string id { get; set; }
        public DateTime createdDateTime { get; set; }
        public DateTime lastModifiedDateTime { get; set; }
        public string name { get; set; }
        public string webUrl { get; set; }
        public int size { get; set; }
        public TeamChannelParentReference parentReference { get; set; }
        public TeamChannelFileSystemInfo fileSystemInfo { get; set; }
        public TeamChannelFolder folder { get; set; }
    }

The size should be changed to a int64 or long.  

src/Commands/Model/Teams/TeamsChannelFilesFolder.cs
https://github.com/pnp/powershell/blob/dev/src/Commands/Model/Teams/TeamsChannelFilesFolder.cs

BTW you maybe have to change the prefix from Teams to Team to have consistency with the other model.

### Steps to reproduce behavior
Just create a channel with 

### What is the version of the Cmdlet module you are running?
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   2.5.33     debug      PnP.PowerShell                      Core      {Add-PnPAdaptiveScopeProperty, Add-PnPEntraIDGroupMember, Add-PnPEntraIDGroupOwner, Add-PnPEntraIDServicePrincipalAppRole…}

It's the last build.

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by jackpoz** [comment]
You are correct, https://learn.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0#properties specifies that `size` is of type `Int64`.
I'll work on it and open a PR.

**Comment by gautamdsheth** [comment]
@sabey2000 issue has been resolved by @jackpoz , it will be available in tomorrow's nightly builds. 
Thanks for raising this !
