### ISSUE TITLE
[BUG] Planner Tab Creation No Longer Works

### ISSUE THREAD

**Issue by danmyhre** [pnp/powershell#4128]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
Creating a planner tab in a Team using this example should work:
https://pnp.github.io/powershell/cmdlets/Add-PnPTeamsTab.html#example-5

### Actual behavior 
Planner tab will not load in Teams. It seems Microsoft may have changed the content URL and tab type.

### Steps to reproduce behavior
Example 5 in link above

### What is the version of the Cmdlet module you are running?
2.4.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@danmyhre - I'm using `2.12.19` and could run the example as-is. Please try again and make sure you have the correct permissions. A lot has changed with the authentication, please see here: https://pnp.github.io/powershell/articles/registerapplication.html
