### ISSUE TITLE
[BUG] Add-PnPFile is uploading the files but not setting the -Values on some of the files during migration

### ISSUE THREAD

**Issue by laurencecrummay-dol** [pnp/powershell#4130]
### Reporting an Issue or Missing Feature
Add-PnPFile is uploading the files but not setting the -Values on some of the files during migration
Same as https://github.com/pnp/powershell/issues/2937

I am experiencing this issue, PS 7.4.3 & PNP 2.5.0

### Expected behavior 
Expected results would see the modified date set as shown

### Actual behavior 
Actual result shows the current date/time. The Title attribute is set correctly

![image](https://github.com/user-attachments/assets/c9fca9a2-4f87-4b44-aab7-f91dcfd93a9d)

### Steps to reproduce behavior
`Add-PnPFile -Path ".\66780.jpg" -Folder "Shared Documents" -Values @{"Modified" =[System.DateOnly]::Parse("12/12/2016"); "Title" = "dog" }
`

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

PS 7.4.3 & PNP 2.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by laurencecrummay-dol** [comment]
Tried the advice here, but it doesn't work
https://github.com/pnp/powershell/discussions/1853

Line |
  17 |  $listItem = Get-PnPFile -Url $file_url -AsListItem
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The object specified does not belong to a list.

**Comment by veronicageek** [comment]
@laurencecrummay-dol - I tried with the major `2.5.0` and the nightly release `2.5.42` and had no problem. Please try with the syntax below.

![image](https://github.com/user-attachments/assets/d48ec2cb-1da9-41fb-a35e-30c2688a3ee6)

**Comment by laurencecrummay-dol** [comment]
Interestingly, I have found if I run the script interactively in a PS window it works as expected, but if I run from within VSCode it does not.

<img width="860" alt="image" src="https://github.com/user-attachments/assets/39d8aa40-d409-4268-a384-fa21db9be7f0">

![image](https://github.com/user-attachments/assets/0324004a-a60a-46ec-8286-67cea6a34638)

**Comment by laurencecrummay-dol** [comment]
Update - I closed the PS extn in VS Code, then ran the script again, and it worked correctly. I don't know what changed, but it's now working as required. Sorry for the confusion and thank you for your help
