### ISSUE TITLE
[FEATURE] Ability to use ValidateConnection on ManagedIdentity 

### ISSUE THREAD

**Issue by AndersRask** [pnp/powershell#4131]
**Is your feature request related to a problem? Please describe.**
When connecting with Connect-PnPOnline through system managed identity we do not have a programmatic way to verify the connection like on other parametersets where we have the -ValidateConnection parameter and can put the connection request inside a try/catch block for proper code flow

As it is now, the Connect-PnPOnline -ManagedIdentity will give what looks like a valid connection that on inspection looks correct (try to call Get-PnPConnection or Get-PnPContext and it looks like a legit connection)
But when a call is done to for example Get-PnPList it will wait for minutes where it is completely unresponsive, only to get back with "A task was canceled".

**Describe the solution you'd like**
Is there a specific reason why -ValidateConnection is excluded for system managed identities? 
If not I would very much like it added :)

**Describe alternatives you've considered**
If there is a way to test on Get-PnPConnection or similar without having to wait minutes for a timeout that would be useful as well

**Additional context**
 ```
try { 
   Connect-PnPOnline -ManagedIdentity -Url https://mytenant.sharepoint.com/sites/test
   Get-PnPConnection
   Get-PnPList
} catch { 
   Write-Error -Exception $_.Exception -Message $_.Exception.Message 
}
ConnectionMethod                           : ManagedIdentity
ConnectionType                             : O365
InitializationType                         : Unknown
Scopes                                     :
PSCredential                               :
ClientId                                   : 1234
ClientSecret                               :
ApplicationInsights                        : PnP.PowerShell.ALC.ApplicationInsights
Url                                        : https://mytenant.sharepoint.com/sites/test
TenantAdminUrl                             :
Certificate                                :
DeleteCertificateFromCacheOnDisconnect     : False
Context                                    : PnP.Framework.PnPClientContext
Tenant                                     :
UserAssignedManagedIdentityObjectId        :
UserAssignedManagedIdentityClientId        :
UserAssignedManagedIdentityAzureResourceId :
AzureEnvironment                           : Production
Write-Error: A task was canceled. # this prompt is returned after several minutes from Get-PnPList 
```

**Comment by gautamdsheth** [comment]
@AndersRask - added support for this. Will be there in tomorrow's nightlies , thanks for raising this.
