### ISSUE TITLE
[BUG] Get-PnPWebHeader - The property or field has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.

### ISSUE THREAD

**Issue by FlorianReinprecht** [pnp/powershell#4132]
### Reporting an Issue or Missing Feature
When I try to use Get-PnPWebHeader on a group-connected Site, I recieve the following error. 
"Get-PnPWebHeader: The property or field has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested."

I tested it on multiple tenants and asked my colleagues to try as well. 

### Expected behavior 
It should return the properties of the Site Header.

### Actual behavior 
![image](https://github.com/user-attachments/assets/38da58db-8566-4819-9380-5eff8119b421)

### Steps to reproduce behavior
```
Connect-PnPOnline -Url $GroupConnectedSiteURL -Interactive
Get-PnPWebHeader
```

### What is the version of the Cmdlet module you are running?
2.5.0 

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
@FlorianReinprecht  thanks for raising this issue. Has been fixed and will be available in tomorrow's nightly builds as well as the next major version
