### ISSUE TITLE
[BUG] Documentation issue and inconsistency with Get-PNPFolderItem -recurse

### ISSUE THREAD

**Issue by sg1888** [pnp/powershell#4140]
### Reporting an Issue or Missing Feature
The cmdlet `Get-PNPFolderItem` utilizes `-recursive` rather than the typical `-recurse` when using recursion.  

I'm not sure if this was an oversight or intentional, but it is inconsistent with other PowerShell commands which use `-recurse`.  In addition, Example 2 of the documentation (https://pnp.github.io/powershell/cmdlets/Get-PnPFolderItem.html) shows the recursive feature as:
![Get-PNPFolderItem Recurse Documentation](https://github.com/user-attachments/assets/b0a8f43e-6b81-4c5b-b896-f02897b201cc)

This does not work as `-recurse` is not set up as an alias for `-recursive`.   
### Expected behavior 
Using `Get-PNPFolderItem -recurse` should work as it is consistent with other PowerShell commands, and matches the example in the documentation.

The proper fix would be to:
1) Configure `-recurse` as an alias for `-recursive` to remain consistent with other PowerShell commands, 
OR
2) Fix Example 2 in the documentation to reflect `-recursive`.

### Actual behavior 
![Get-PNPFolderItem Recurse](https://github.com/user-attachments/assets/e8f27217-cdf9-48a8-86d2-94165f9ef35b)
Currently if you use `Get-PNPFolderItem -recurse` you get an error that says:
```
A parameter cannot be found that matches parameter name 'Recurse'.
```

### Steps to reproduce behavior
```Powershell
Connect-PnPOnline -url $url -Credentials $Credentials
Get-PNPFolderItem -Recurse
```

### What is the version of the Cmdlet module you are running?
2.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
@sg1888 thanks for raising this. Have added the alias and also added it to 2 other cmdlets where we were using it.
