### ISSUE TITLE
[BUG] GCC High Authentication Issue

### ISSUE THREAD

**Issue by miketheitguy** [pnp/powershell#4162]
### Reporting an Issue or Missing Feature
`Connect-PnPOnline -Tenant "mytenant.onmicrosoft.us" -ApplicationId "31359c7f-myappID" -Interactive -Url "https://mytenant.sharepoint.us"`

For some reason, when I run this command, I see an attempt to get a token from an IP Address, 65.52.193.237. This isn't a known IP Address to me and belongs to Microsoft. I'm curious why this is happening.

### Expected behavior 
Token Issuance should happen from the client and not through some other server/service.

### Actual behavior 
I see a token issuance request in my Entra ID logs from 65.52.193.237

### What is the version of the Cmdlet module you are running?
2.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
hi @miketheitguy , we use MSAL.NET under the hood for this which handles the authentication part. No ip-addresses are specified anywhere in the code.
