### ISSUE TITLE
[BUG] Get-PnPListItem -List $list not returning all fields on items when list has many fields

### ISSUE THREAD

**Issue by nozzrangar** [pnp/powershell#4164]
### Reporting an Issue or Missing Feature
It looks like Get-PnPListItem does not return all fields on items when there are many fields in the list, when you fetch all list items by only providing the -List Parameter

ListA has 222 fields based on Get-PnPField -List $listA
ListB has 112 fields based on Get-PnPField -List $listB

```
$allItemsListA = Get-PnPListItem -List $listA
$singleListItemListA = Get-PnPListItem -List $listA -Id 104

$allItemsListB = Get-PnPListItem -List $listB
$singleListItemListB = Get-PnPListItem -List $listb -Id 41
```

### Expected behavior 
`$allListItemsListA[1].FieldValues.Count` should be the same value as `$singleListItemListA.FieldValues.Count`
`$allListItemsListB[1].FieldValues.Count` should be the same value as `$singleListItemListB.FieldValues.Count`

### Actual behavior 

For ListA that has 222 fields:
`$allListItemsListA[1].FieldValues.Count` only shows 192 FieldValues.
`$singleListItemListA.FieldValues.Count` shows all FieldValues, or 202 FieldValues.

![image](https://github.com/user-attachments/assets/bc9c80ba-b03e-4b01-8deb-2ab0d35a7b41)

For ListB that has 112 fields:
`$allListItemsListB[1].FieldValues.Count` shows all FieldValues, or 92.
`$singleListItemListB.FieldValues.Count` also shows all FieldValues, or 92.

![image](https://github.com/user-attachments/assets/25804faa-e144-4328-936b-5c72d309f1d1)

### Steps to reproduce behavior
```
# ListA has 222 fields.
$allListItemsListA = Get-PnPListItem -List $listA -PageSize 1000
# allListItemsListA[1] is the same item as $singleListItemListA
$allListItemsListA[1].FieldValues.Count

# singleListItemListA is the same item as allListItemsListA[1]
$singleListItemListA = Get-PnPListItem -List $listA -Id 104
$singleListItemListA.FieldValues.Count

# ListB has 112 fields. 
$allListItemsListB = Get-PnPListItem -List $listB -PageSize 1000
# allListItemsListB[1] is the same item as $singleListItemListB
$allListItemsListB[1].FieldValues.Count

# singleListItemListB is the same item as allListItemsListB[1]
$singleListItemListB = Get-PnPListItem -List $listB -Id 41
$singleListItemListB.FieldValues.Count
```

### What is the version of the Cmdlet module you are running?
2.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by jackpoz** [comment]
In my experience there is no guarantee that `Get-PnPListItem` will return all fields. Most of the times it returns the fields that are included in the default view.

The `-Id` parameter uses different CSOM code to retrieve the data than when loading all list items, which might explain the different behavior .

I would suggest to use the `-Fields` parameter to specify which fields you want to retrieve, documentation at https://pnp.github.io/powershell/cmdlets/Get-PnPListItem.html#-fields

**Comment by gautamdsheth** [comment]
hi @nozzrangar , this is by design.

As @jackpoz mentioned , we use a different query when you specify the `-Id` parameter. It will return different results .

If you need to fetch specific fields, use `-Fields` parameter and pass the field internal names.
