### ISSUE TITLE
[BUG] -Interactive not working after upgrade to 2.7

### ISSUE THREAD

**Issue by HiltonGiesenow** [pnp/powershell#4168]
### Reporting an Issue or Missing Feature
I've just upgraded to 2.7 and when I try `Connect-PnPOnline` with `-Interactive` (because we have MFA) I get the following warning:

`
WARNING: Connecting with -Interactive uses the PnP Management Shell multi-tenant App Id for authentication. It is strongly recommended to register your own EntraID App for authentication. See the documentation for Register-PnPEntraIDApp.
`

which is fine. The problem is that nothing happens after that - the command just pauses. I have to BREAK to get the console back.

### Expected behavior 
The command should launch the interactive login console.

### Actual behavior 
As above, nothing happens after the warning appears.

### Steps to reproduce behavior
1. upgrade to 2.7
2. try connect with `Connect-PnPOnline "https://[tenant].sharepoint.com/" -Interactive

### What is the version of the Cmdlet module you are running?
3.7

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows

**Comment by erwinvanhunen** [comment]
Thank you for reporting it. We just noticed it ourselves in are debugging the cause as we speak. We noticed it is work as expected on MacOS, so it seems a Windows specific problem.

**Comment by HiltonGiesenow** [comment]
Thanks Erwin. Will wait to hear from you

**Comment by erwinvanhunen** [comment]
We did some testing and can confirm that 2.7.0 does not behave correctly on Windows. However, the latest nightly build does work as expected. You can install this one with

Install-Module -Name PnP.PowerShell -AllowPrerelease

We will work on getting a new release out tomorrow. I will unlist version 2.7.0 from the PowerShell Gallery for now.

**Comment by erwinvanhunen** [comment]
@HiltonGiesenow : we released version 2.8.0.

**Comment by HiltonGiesenow** [comment]
looks good, thank you!
