### ISSUE TITLE
[BUG]  Get-PnPSharingForNonOwnersOfSite to get the default sharing setting details is giving incorrect output.

### ISSUE THREAD

**Issue by hmihaella** [pnp/powershell#4170]
### Reporting an Issue or Missing Feature
The command Get-PnPSharingForNonOwnersOfSite to get the default sharing setting details is giving incorrect output.

As per the article https://pnp.github.io/powershell/cmdlets/Get-PnPSharingForNonOwnersOfSite.html the command should return $false if sharing of the site and items in the site is restricted only to owners. I tested on one of our test sites and it returns $True.

### Expected behavior 
The value returned to be "False"

### Actual behavior 
The value returned is "True"

### Steps to reproduce behavior
Connected via PowerShell:

Connect-PnPOnline -Url https://m365x30315824.sharepoint.com/sites/Design -Interactive
Get-PnPSharingForNonOwnersOfSite
![Screenshot 2024-08-19 165745](https://github.com/user-attachments/assets/8026d902-f954-4ebc-b62b-ebccc18e4173)
![Screenshot 2024-08-19 165830](https://github.com/user-attachments/assets/1d3334c9-4ec9-4965-b636-c4f0c9b60403)
![Screenshot 2024-08-19 165931](https://github.com/user-attachments/assets/8cf1d581-4cb9-4b88-b03d-8d34c87d54e2)
![Screenshot 2024-08-19 165948](https://github.com/user-attachments/assets/012d9e82-2378-48bc-8e13-4d2ce06e9156)

### What is the version of the Cmdlet module you are running?
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   2.3.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@hmihaella - Have you just tuned off the ability to share directly via the UI and then run the command?
I have just tested with `2.9.0`, but there might be a delay when turning off via SharePoint and running the cmdlet straight after.

However, if you use `Disable-PnPSharingForNonOwnersOfSite` and then run `Get-PnPSharingForNonOwnersOfSite`, it will correctly show `False`.

**Comment by jackpoz** [comment]
The command `Get-PnPSharingForNonOwnersOfSite` simply returns the result of the CSOM method [Office365Tenant.IsSharingDisabledForNonOwnersOfSite](https://learn.microsoft.com/en-us/previous-versions/office/sp-pnp-dotnet/mt643036(v=office.15)) , so if there is an issue, it should be with CSOM itself.

The SharePoint Online Management Shell has a similar command at [Get-SPOSite -Identity https://contoso.sharepoint.com -DisableSharingForNonOwnersStatus](https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/get-sposite?view=sharepoint-ps#-disablesharingfornonownersstatus) with this note:
>DisableSharingForNonOwnersStatus is not a persisted setting but rather an analysis of the state of the site collection.

That might explain the delay.

**Comment by gautamdsheth** [comment]
Closing this , it’s all CSOM under the hood and the delay looks like server side thingy, nothing we can do to fix  .
