### ISSUE TITLE
[BUG] Getting Warning on Newer Version of PnP.PowerShell

### ISSUE THREAD

**Issue by anthonywhite** [pnp/powershell#4171]
Manifest   **2.5.0**                 PnP.PowerShell                      Core     
Installing SPFx App to App Catalog...
WARNING: 
                                                                         
 **A newer version of PnP PowerShell is available: 2.9.0.**                  
                                                                         
 Use 'Update-Module -Name PnP.PowerShell' to update.                     
 Use 'Get-PnPChangeLog -Release 2.9.0' to list changes. 
          
=========================================

However I think this version/release 2.9.0 does not exist?

**Comment by jackpoz** [comment]
Version 2.9.0 exists on PowerShell Gallery at https://www.powershellgallery.com/packages/PnP.PowerShell/2.9.0 , it's just not a release on GitHub at https://github.com/pnp/powershell/releases

**Comment by anthonywhite** [comment]
> Version 2.9.0 exists on PowerShell Gallery at https://www.powershellgallery.com/packages/PnP.PowerShell/2.9.0 , it's just not a release on GitHub at https://github.com/pnp/powershell/releases

is it going to be?

**Comment by veronicageek** [comment]
@anthonywhite - It will. You can update safely.
