### ISSUE TITLE
[FEATURE] Grant-PnPAzureADApp* for *.SelectedOperations

### ISSUE THREAD

**Issue by kkazala** [pnp/powershell#4173]
**Is your feature request related to a problem? Please describe.**
Microsoft Graph API now offers even more granular API permissions:
- Lists.SelectedOperations.Selected: manages application access at the list level, providing access to a specific list,
- ListItems.SelectedOperations.Selected: manages application access at the files, list item, or folder level, providing access to one or more list items,
- Files.SelectedOperations.Selected manages application access at the file or library folder level, providing access to one or more files.

[Overview of Selected permissions in OneDrive and SharePoint](https://learn.microsoft.com/en-us/graph/permissions-selected-overview?tabs=http)

These scopes are stull not supported by the PnP PS. 

**Describe the solution you'd like**
Would be extremely helpful to have a new cmdlet to allow us granting these granular permissions as well =)

**Describe alternatives you've considered**
POST https://graph.microsoft.com/BETA/sites/{siteId}/lists/{listIf}/permissions works. 

(OK... it's still in beta, but I'll keep the issue open, maybe time will come=) )

thank you in advance! ❤️

**Comment by danmyhre** [comment]
@gautamdsheth did this ever make it to production?  What are the new cmdlet names?

**Comment by MikP87** [comment]
@gautamdsheth Realise this thread has been quiet, but could you provide an update on the cmdlets for this? Can the https://pnp.github.io/powershell/cmdlets page also be updated please with these new cmdlets?

**Comment by pundumx** [comment]
@MikP87 is this an example of what you're looking for? https://pnp.github.io/powershell/cmdlets/Grant-PnPEntraIDAppListPermission.html
