### ISSUE TITLE
[FEATURE] Possibility to use an environment variable for ClientId when connecting

### ISSUE THREAD

**Issue by jhholm** [pnp/powershell#4195]
Hi,

I know that the Multitenant Entra ID Application changes, updates and documentation are still ongoing, but I was wondering if it would be possible to use an Environment variable to set the ClientId instead of setting it manually while connecting? I noticed you already are using some environment variables
at https://pnp.github.io/powershell/articles/configuration.html

Instead of
```
Connect-PnPOnline -Url [tenant].sharepoint.com -ClientId [clientid]
```

You could connect somehow like this
```
$env:CLIENTIDENVVARIABLEEXAMPLE = [clientid]
Connect-PnPOnline -Url [tenant].sharepoint.com
```

The problem is that after the 9th of September change, we need to explicitly set the ClientId on each connection. This becomes a hassle when you have multiple different tenants you're connecting (e.g. as a consultant). I'm currently planning on setting these as environment variables on per project basis which should make the migration to the new application registration model much simpler. M365 CLI is also working like this, which makes migration easier atleast for me.

Though to be fair, it's possible to circumvent this and use **-ClientId $env:CLIENTIDENVVARIABLEEXAMPLE** for now.

**Comment by ToddKlindt** [comment]
Starting in 2.9.0 it already supports one, ENTRAID_APP_ID. I write about how to use it here, https://www.toddklindt.com/blog/Lists/Posts/Post.aspx?ID=904

**Comment by jhholm** [comment]
Thanks! I did not notice that in the documentation. I will be closing this then. Should I create a pull request to update the documentation about this later?

**Comment by gautamdsheth** [comment]
PRs welcome , thank you !
