### ISSUE TITLE
Default values for lookup is not showing after running PNP command successfully using Set-PnPField

### ISSUE THREAD

**Issue by VijayaRimmalapudi** [pnp/powershell#42]
Default values for lookup is not showing in the library after running PNP command successfully using Set-PnPField. Also will the default values set through PNP shown in the Search results page?

Set-PnPField -List "Listname" -Identity "Columnname" -Values @{DefaultValue="1;#Value"}

**Comment by erwinvanhunen** [comment]
You were close :-) 

```powershell
Set-PnPField -List "yourlist" -Identity "ColumnName" -Values @{DefaultValue="Value"}
```

Eg. do not use the `1;#` part, the DefaultValue property of a field is simply text without the index identifier.

You can use the `Get-PnPField` cmdlet to see the actual default value if you set the default value through the web interface first.

```powershell
$field = Get-PnPField -List "yourlist" -Identity "YourChoiceField"
$field.DefaultValue
```
