### ISSUE TITLE
Connect-PnPOnline is missing the -Scope parameter

### ISSUE THREAD

**Issue by dan11990** [pnp/powershell#421]
In PnP-Powershell you supported the -Scope parameter in Connect-PnPOnline, for example:

Connect-PnPOnline -Scopes "Group.ReadWrite.All"

Is this going to be introduced in this version?

**Comment by veronicageek** [comment]
Hi @dan11990,
The `-Scopes` parameter has now been marked as obsolete. Have a look at the [CHANGELOG.md](https://github.com/pnp/powershell/blob/dev/CHANGELOG.md).
