### ISSUE TITLE
[BUG] Get-PnPAzureADGroup failes to work in 2.10.0

### ISSUE THREAD

**Issue by GJPAdmin** [pnp/powershell#4210]
### Reporting an Issue or Missing Feature
I have a PowerShell script that connects using an App Registration and certificate. This has all of the necessary permissions to do what we need, including Group.ReadWrite.All. With PnP 2.9.0, the following command worked OK:

`$group = Get-PnPAzureADGroup -Identity $groupName`

Now with 2.10.0 it generates an error:

> AADSTS1002012: The provided value for scope Group.ReadWrite.All is not valid. Client credential flows must have a scope value with /.default suffixed to the resource identifier (application ID URI). Trace ID: 8637ab1f-43a4-4fd3-8aaf-5f94464f1000 Correlation ID: 707471ca-0ed5-4e60-b215-039778c72a69 Timestamp: 2024-08-30 08:09:13Z.

At the time I am also using Graph 2.22.0, and PowerShell 7.4.5.

### Expected behavior 
It used to get the group and then allow us to retrieve its members using:

`$members = Get-PnPAzureADGroupMember -Identity $group.Id`

### Actual behavior 
Code now fails with the above error.

### Steps to reproduce behavior
Not feasible to include all code, but the bits that do the work are (Terminate is my own function for exiting cleanly out of the code, not important here):

`write-host '`nConnecting to $siteURL...' -ForegroundColor white
Connect-PnPOnline -Url $siteURL -Tenant "$tenant.onmicrosoft.com" -ClientId $PnPClientId -CertificatePath $PnPCertificatePath
$group = Get-PnPAzureADGroup -Identity $groupName`

### What is the version of the Cmdlet module you are running?
2.10.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Thanks for reporting this, have fixed this. It will be available in tomorrow's nightly builds as well as the next major version.

**Comment by GJPAdmin** [comment]
Awesome, thank you for the update, much appreciated.
