### ISSUE TITLE
[BUG] Register-PnPEntraIDAppForInteractiveLogin not registering the Azure app

### ISSUE THREAD

**Issue by David-AP00** [pnp/powershell#4215]
Using PnP 2.10.0 and Powershell 7.4.5 as administrator.  The account used is a Global Admin.

Register-PnPEntraIDAppForInteractiveLogin -ApplicationName "New PnP" -Tenant [name].onmicrosoft.com -Interactive

After authentication and MFA, we get
WARNING: 
No permissions defined, default permissions

And then.. nothing. We don't see the following action "Checking if application New PnP does not exist yet..." and the other actions.

At the beginning i thought it was related with admin consent we have in the tenant, but I tried with 2 different tenants and 2 different global admins with same result. Also, from different workstations. Thank you.

**Comment by gautamdsheth** [comment]
Works fine with me , opens the popup as well , maybe uninstall/delete and reinstall PnP again and try ?

<img width="703" alt="image" src="https://github.com/user-attachments/assets/8af18ee6-bfff-4c40-878d-8d0cd9e0a130">

**Comment by David-AP00** [comment]
Thanks for the feedback. In my case (and also another colleague in another country/network/workstation):

![Captura de pantalla 2024-08-30 121948](https://github.com/user-attachments/assets/d4e7a845-9934-49a6-8ae9-980fa421faa8)

I will try to uninstall everything again..

**Comment by gautamdsheth** [comment]
Just saw that you are running this in admin mode, can you try it in normal user mode as well and let us know ? Maybe that could be the problem ?

**Comment by David-AP00** [comment]
Finally i was able to register the app.., by using a non-corporative laptop. It looks like a Intune or Conditional Access policy was blocking the app registration. Thanks for your help!

**Comment by ZeMuffin** [comment]
i have this exact same issue, however i am not on a policy controlled device

**Comment by David-AP00** [comment]
Check also the antivirus. The laptop I was able to run the command from had a different AV than company laptops.

**Comment by ZeMuffin** [comment]
did you have to make any changes to execution policy or anything else?
ive not used PnP Powershell before and have deployed ps 7.4.5 to configure it for a new project.

**Comment by David-AP00** [comment]
i didnt have to modify the execution policy in my case (I think I would have got an error message about that).

**Comment by ZeMuffin** [comment]
Worked it out, it was SentinelOne. Despite it not saying it was blocking anything, it worked after disabling it.

**Comment by David-AP00** [comment]
Yes, right, i had S1 installed in corporative laptops/servers and it worked when I did it from the personal one. So SentinelOne is not happy with something the cmdlet does.

**Comment by AlNoes** [comment]
Has anybody tried to dig a bit deeper to find the root problem? Disabling works, yes, but we would like to have Sentinel running and this cmdlet working.
Unfortunately, SentinelOne isn't telling, what he's blocking and there are no helpful logs, even with tracing on debug level activated.
