### ISSUE TITLE
[BUG] Get-PnPMicrosoft365Group scope Group.ReadWrite.All is not valid

### ISSUE THREAD

**Issue by DuaneBeis** [pnp/powershell#4218]
### Reporting an Issue or Missing Feature
When using Get-PnPMicrosoft365Group with the GA PnP.PowerShell 2.10.0 the following error is generated:
"Get-PnPMicrosoft365Group: The provided value for scope Group.ReadWrite.All is not valid. Client credential flows must have a scope value with /.default suffixed to the resource identifier (application ID URI)"

### Expected behavior 
A group should be able to be retrieved using the -Identity switch

### Steps to reproduce behavior
Run Get-PnPMicrosoft365Group with a connection generated by an app connection.

### What is the version of the Cmdlet module you are running?
2.10.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
@DuaneBeis - thanks for reporting & apologies for this. 

The issue has been fixed. It will be available in tomorrow's nightly builds as well as the next major version (no ETA, but pretty soon)
