### ISSUE TITLE
[BUG] version 2.10.0 breaks app-only authentication to Microsoft Graph when using certificate authentication

### ISSUE THREAD

**Issue by gruering** [pnp/powershell#4222]
### Expected behavior 
After connecting with a client id and a certificate I can successfully execute Get-PnPSite and Get-PnPMicrosoft365Group

### Actual behavior 
SharePoint Online commands work without any issues. Commands that require access to Microsoft Graph lead to the following error:
AADSTS1002012: The provided value for scope Group.ReadWrite.All is not valid. Client credential flows must have a scope value with /.default suffixed to the resource identifier (application ID URI)

### Steps to reproduce behavior
Connect-PnPOnline -Url -ClientId -CertificatePath -CertificatePassword
 $site = Get-PnPSite Get-PnPSite -Includes GroupId
Get-PnPMicrosoft365Group -Identity $site.GroupId.Guid

**Downgrading to 2.9.0 resolves the error.**

### What is the version of the Cmdlet module you are running?
2.10.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
@gruering - thanks for reporting & apologies for this. We have fixed this in the nightly builds, the latest one is `2.10.7-nightly` , will be releasing a major one pretty soon as well.
