### ISSUE TITLE
[BUG] Incorrect Example in Get-PnPFolderItem docs

### ISSUE THREAD

**Issue by Saurabh7019** [pnp/powershell#4224]
### Reporting an Issue or Missing Feature
One of the examples in the `Get-PnPFolderItem` documentation uses an incorrect parameter.

`Get-PnPFolder -Identity "Shared Documents" | Get-PnPFolderItem -ItemType File`

### Expected behavior 
The example should include the correct and allowed parameters for the `Get-PnPFolder` command.

### Actual behavior 
The example fails with the following error:
![image](https://github.com/user-attachments/assets/50bca4f3-800d-4f69-9ffc-f54ffb077cdd)

### Steps to reproduce behavior
Refer to the Get-PnPFolderItem documentation and review example 6:
https://pnp.github.io/powershell/cmdlets/Get-PnPFolderItem.html#example-6

### What is the version of the Cmdlet module you are running?
2.10.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Thanks @Saurabh7019 for raising this. Have fixed the example, should be updated in few mins !
