### ISSUE TITLE
[BUG] Connecting with custom client id and credentials saves wrong client id in connection object

### ISSUE THREAD

**Issue by reusto** [pnp/powershell#4230]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
When connected with a custom client id and credentials, then the connection object should reflect the usage of the custom client id.

### Actual behavior 
When connected with a custom client id and credentials, then the connection object shows the default PNP Managment Shell client id.

### Steps to reproduce behavior
```powershell
$connection = Connect-PnPOnline -Url "https://contoso.sharepoint.com" -ClientId '{customId}' -Credentials (Get-Credential) -ReturnConnection;

$connection.ClientId;
```

### What is the version of the Cmdlet module you are running?
2.10.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
@reusto - fixed it, will be available in tomorrow's nightly builds ! Thanks for reporting.
