### ISSUE TITLE
[BUG] Grant-PnPAzureADAppSitePermission 

### ISSUE THREAD

**Issue by David-AP00** [pnp/powershell#4236]
Getting this error when trying to use the cmdlet Grant-PnPAzureADAppsSitePermission
However, it works with older PnP versions.

I don't know if the behaviour changed, or we need to add extra configuration into the admin Azure app with sites.fullcontrol.all permissions we use to grant access via sites.selected
Thank you

This is the cmdlet I used to use:

Grant-PnPAzureADAppSitePermission -AppId $clientAppId -DisplayName "GCT" -Permissions Write -Site $site2apply

Grant-PnPAzureADAppSitePermission: AADSTS1002012: The provided value for scope Sites.FullControl.All is not valid. Client credential flows must have a scope value with /.default suffixed to the resource identifier (application ID URI). Trace ID: 9699138d-7c0c-4df0-9f6f-9f7085565500 Correlation ID: 554a7961-2479-46e7-901c-653d3d5ac655 Timestamp: 2024-09-04 08:06:07Z

**Comment by gc-LMA** [comment]
i get the same error with the "Get-PnPMicrosoft365GroupMember" cmdlet

Get-PnPMicrosoft365GroupMember: AADSTS1002012: The provided value for scope Group.ReadWrite.All is not valid. Client credential flows must have a scope value with /.default suffixed to the resource identifier (application ID URI)

Could you DM me if you get a solution for the problem @David-AP00 ? :)

**Comment by gc-LMA** [comment]
Hey @David-AP00 ,
theyre working on a fix:
https://github.com/pnp/powershell/issues/4232#issue-2503236700

**Comment by gautamdsheth** [comment]
Hey @David-AP00 , this issue has been fixed in latest nightly builds , going to close it. Will be releasing a major version soon as well.
