### ISSUE TITLE
[BUG] Get-PnPSiteFileVersionBatchDeleteJobStatus as Function App Managed Identity -- Cannot Call this API w/ App Only principal

### ISSUE THREAD

**Issue by zjferguson** [pnp/powershell#4240]
### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets
1,  Connect-PnPOnline -Url $url -ManagedIdentity -ValidateConnection
2. Get-PnPSiteFileVersionBatchDeleteJobStatus
3. 
OUTPUT:
Url                         : https://$TENANT-admin.sharepoint.com
WorkItemId                  :
Status                      : NoRequestFound
ErrorMessage                :
RequestTimeInUTC            :
LastProcessTimeInUTC        :
CompleteTimeInUTC           :
BatchDeleteMode             :
DeleteOlderThan             :
MajorVersionLimit           :
MajorWithMinorVersionsLimit :
FilesProcessed              :
VersionsProcessed           :
VersionsDeleted             :
VersionsFailed              :
StorageReleasedInBytes      :

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.
500 Internal service error:
ERROR: An error occurred: Cannot call this API with an app-only principal.

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

    Connect-PnPOnline -Url "https://$tenant.sharepoint.com/sites/chettest12" -ManagedIdentity -ValidateConnection
    Get-PnPSiteFileVersionBatchDeleteJobStatus

NOTE other cmdlets work just fine EX::
    Connect-PnPOnline -Url "https://$tenant.sharepoint.com/sites/chettest12" -ManagedIdentity -ValidateConnection
    Get-PnPSite 

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

Have tried on:
- '2.10.10-nightly'
- '2.10.5-nightly'
- 2.10.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [x ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Hi @zjferguson , this error is coming from the SharePoint endpoint. Looks like app-only authentication isn't supported for this. We can't do anything from here as we only consume the methods.

You can reach out to Microsoft support and raise a ticket , only they can help.

You can find the source code for that here which you can use in the support ticket:

https://github.com/pnp/powershell/blob/dev/src/Commands/Site/GetSiteFileVersionBatchDeleteJobStatus.cs

**Comment by Gpn85** [comment]
Facing the same issue. Did you manage to get any response from Microsoft on this one?

**Comment by zjferguson** [comment]
@Gpn85 Yeah -- they confirmed that some cmdlets (this one included) are not able to be called from app only access (even in the SPO module).

So in my function App I called a function that would retrieve a delegated token on behalf of an account, and then passed that through to:

Connect-PnPOnline -Url $Url.body.Url  -AccessToken $authToken.body

It works using that method. Unfortunately managed identity would be preferred though

**Comment by zjferguson** [comment]
I have a Powershell 7 function app w/ multiple functions.

1. I have a function called getAuth, which runs Invoke-RestMethod to get a token
2. Body for token retrieval. You need a service principal created w/ some sort of delegated SPO API permission && You need an account to get a delegated token on behalf of -- it may need SPO Admin I believe.
$body = @{
    client_id     = $env:clientId
    scope         = "https://<tenantName>.sharepoint.com/.default"
    username      = $env:spUser
    password      = $env:spPass
    grant_type    = "password"
    client_secret = $env:clientSecret
}
3. My other functions call GetAuth() to get the token when I can connect-pnpOnline and then run the PnPSiteFileVersion cmdlets
Connect-PnPOnline -Url $Url.body.Url -AccessToken $authToken.body
