### ISSUE TITLE
Connect-PnPOnline -interactive not work for multiple users on two different tenants

### ISSUE THREAD

**Issue by bnalley** [pnp/powershell#4252]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Connect-PnPOnline -Url $adminsite -Interactive 

### Expected behavior 
When using this command, expect an authentication prompt (which we get) and then we are connected.  

### Actual behavior 
When using the "-interactive" command, we authenticate but then are given an error:
  
Request Id:  9291d338-d3b1-4224-97bb-935ab526b300 
Correlation Id:  64c4c035-7980-4ebd-bcae-a71b9b4ba1db 
Timestamp:  2024-09-09T21:43:02Z 
Message:  AADSTS700016: Application with identifier '31359c7f-bd7e-475c-86db-fdb8c937548e' was not found in the directory 'The [companyname]'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant. 

Multiple colleagues have this same issue.  I have validated the PnP is installed in Enterprise applications.  This is happening on our prod and dev tenants.  It seems to be an issue with this command specifically.  Connect-PnPOnline with our Azure app client id, tenant id, and certificate work just fine.  SPO PowerShell connect works just fine.  Please help as this is causing an outage.

### Steps to reproduce behavior
Connect-PnPOnline -Url $adminsite -Interactive 

### What is the version of the Cmdlet module you are running?
running 2.4.57

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by jansenbe** [comment]
@bnalley : see #4250

**Comment by murchelon** [comment]
This problem is related to a change in the PnP framework. See link bellow:

https://pnp.github.io/blog/post/changes-pnp-management-shell-registration/

**Comment by gautamdsheth** [comment]
Hello, please check this:

https://github.com/pnp/powershell/discussions/4249

**Comment by bnalley** [comment]
This is a significant change.  Client Id with interactive login does not work. We are in multi-geo and app only doesn't work for some commands.
