### ISSUE TITLE
[BUG] Register-PnPEntraIDAppForInteractiveLogin freezes Powershell 

### ISSUE THREAD

**Issue by SabbeRubbish** [pnp/powershell#4256]
### Reporting an Issue or Missing Feature
When trying to register an application, even though all the parameters are correct, i.e.
`Register-PnPEntraIDAppForInteractiveLogin -ApplicationName "PnP.Powershell" -Interactive -Tenant "domain.onmicrosoft.com"`
with the login & MFA prompt working fine, it just freezes afterwards. Not only that, I can't even CTRL+C the command so I need to restart my shell completely.

### Expected behavior 
Returns a client ID for the registered application.

### Actual behavior 
Shows a warning:
`WARNING: 
 No permissions specified, using default permissions`
(pretty sure that shouldn't matter)
Freezes the entire shell.

### Steps to reproduce behavior
Just run this command:
`Register-PnPEntraIDAppForInteractiveLogin -ApplicationName "PnP.Powershell" -Interactive -Tenant "domain.onmicrosoft.com"`

### What is the version of the Cmdlet module you are running?
2.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows, PS v7.4.5

**Comment by gautamdsheth** [comment]
Can you please check this issue, can't reproduce this, could be some antivirus or some policy :

https://github.com/pnp/powershell/issues/4215

**Comment by SabbeRubbish** [comment]
Looks like the exact same thing, sorry only looked in open tickets.
