### ISSUE TITLE
[BUG] Get-PnPAzureADUser command fails to authenticate when using Directory.ReadWrite.All permission

### ISSUE THREAD

**Issue by LastGunslinger** [pnp/powershell#4258]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
When using the Get-PnPAzureADUser command with the Directory.ReadWrite.All Graph permission to fetch users, I expect a set of users to be returned.

### Actual behavior 
The command errors with the message:
```
Get-PnPAzureADUser: AADSTS65001: The user or administrator has not consented to use the application with ID 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' named 'PnP PowerShell'. Send an interactive authorization request for this user and resource. Trace ID: a05eb7c9-8af6-4a76-b13b-975e279ba300 Correlation ID: 47ff09b4-acbc-4ab3-8b4f-36622afa5d75 Timestamp: 2024-09-10 18:58:05Z
```
When run with the -Verbose flag, I can see this before the error:
```
VERBOSE: Acquiring oAuth token for permission scope User.Read.All
```

Per the [documentation](https://pnp.github.io/powershell/cmdlets/Get-PnPAzureADUser.html), using this command only requires ONE OF the following permissions: Directory.Read.All, Directory.ReadWrite.All, User.Read.All, User.ReadWrite.All

### Steps to reproduce behavior
Create a new Azure application, using the documentation, assign delegated Directory.ReadWrite.All API permissions, grant admin consent, then attempt to connect to the tenant and use Get-PnPAzureADUser

### What is the version of the Cmdlet module you are running?
2.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by jackpoz** [comment]
Is the application id in the logs the same as the one that you created ? The error probably comes from Microsoft Graph, so make sure you have granted admin consent to the application registration with that id. If possible post a screenshot of the permissions.

**Comment by LastGunslinger** [comment]
@reshmee011 Thank you, it seems that this issue is resolved in the nightly build. Is there a timeline yet for when this fix will be included in the next minor or patch version?

**Comment by reshmee011** [comment]
@LastGunslinger , I will let the PnP PowerShell maintainers answer when is the next release. @KoenZomers , @gautamdsheth
