### ISSUE TITLE
[BUG] Add-PnPMicrosoft365GroupToSite "An error occurred while processing this request"

### ISSUE THREAD

**Issue by khha** [pnp/powershell#4259]
### Reporting an Issue or Missing Feature
I am trying to groupify an existing classic team site by creating a Microsoft 365 group. Using Add-PnPMicrosoft365GroupToSite returns an error "An error occurred while processing this request"

### Expected behavior 
I expect that my non-group-based SharePoint site is groupifyed.

### Actual behavior 
I git an error "An error occurred while processing this request"

### Steps to reproduce behavior
Create Azure app registration. Give it SharePoint full control permissions with api permission Sites.ReadWrite.All. Install a self signed certificate on your local machine. Make a connection to a non-group-based SharePoint site with Connect-PnPOnline with clientId and certificate thumbprint. Groupify this SharePoint site by commando Add-PnPMicrosoft365GroupToSite.

### What is the version of the Cmdlet module you are running?
2.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows

**Comment by maeni70** [comment]
I confirm this bug. Other cmdlets like **New-PnPMicrosoft365Group** or **New-PnPSite** work as expected with my app registration.

**Comment by manlamcheng** [comment]
I have the exact same issue, someone please HELP !!

**Comment by gautamdsheth** [comment]
Hello, this is a backend API issue. You need to use delegated permissions for this cmdlet and ensure that you are the site collection admin of the site getting groupified . Application permissions wont work in this case. We can't fix it in PnP PowerShell.
