### ISSUE TITLE
[BUG] Register-PnPEntraIDApp Hanging

### ISSUE THREAD

**Issue by aefruswg** [pnp/powershell#4260]
### Reporting an Issue or Missing Feature
I'm attempting to create a certificate per the instructions here (https://pnp.github.io/powershell/articles/registerapplication.html) and nothing appears to happen. The command I'm running is:

`$result = Register-PnPEntraIDApp -ApplicationName "PnP" -Tenant tenant.onmicrosoft.com -OutPath $path -DeviceLogin`

I'm on version 2.12 and using PS 7.4.5.

### Expected behavior 
I expect to be prompted a link and code to approve the app in Azure as described in the link above,

### Actual behavior 
I receive a warning that the command is using default scopes/permissions (which is fine to start with) and then nothing happens. I've tried multiple times over the course of two days and have let it sit upwards of 30 minutes. Have also tried running as admin.

![image](https://github.com/user-attachments/assets/9a66322b-8263-4961-8db3-9516701f3578)

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

`$result = Register-PnPEntraIDApp -ApplicationName "PnP" -Tenant tenant.onmicrosoft.com -OutPath $path -DeviceLogin`

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

Register-PnPEntraIDApp. I also tried running Register-PnPAzureADApp with the same results.

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Can you try with the latest nightly build and let us know ? We fixed this issue in there.

**Comment by aefruswg** [comment]
Thanks for the quick reply. The nightly version resolved this issue.
