### ISSUE TITLE
[BUG] Set-PnPMicrosoft365GroupSettings is returning type conversion error

### ISSUE THREAD

**Issue by mblennegard** [pnp/powershell#4263]
### Reporting an Issue or Missing Feature
When calling `Set-PnPMicrosoft365GroupSettings -Identity $groupSettingId -Values @{"AllowToAddGuests"="true"} -Group $groupId` I get the below error:
**Set-PnPMicrosoft365GroupSettings: Cannot implicitly convert type 'void' to 'object'**.

I have verified both the $groupSettingId and $groupId values and they exist.
In fact, I could create the group setting on the same $groupId using `New-PnPMicrosoft365GroupSettings` just a couple of minutes earlier, but with `-Values @{"AllowToAddGuests"="true"}`.

Besides using the id's for the group and group setting, I have also tried using the entire group object as well as the group setting object with no difference.

Workaround right now is to use `Remove-PnPMicrosoft365GroupSettings -Identity $groupSetting.Id -Group $groupId -Connection $conn` which works fine, after which the original `New-PnPMicrosoft365GroupSettings` can be run but with the new Values hash table.

### Expected behavior 
That the group setting to be updated.

### Actual behavior 
Receiving the error: Set-PnPMicrosoft365GroupSettings: Cannot implicitly convert type 'void' to 'object'

### Steps to reproduce behavior
Run cmdlet

### What is the version of the Cmdlet module you are running?
2.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by jackpoz** [comment]
Pull request opened at https://github.com/pnp/powershell/pull/4274

**Comment by gautamdsheth** [comment]
Hello @mblennegard , this issue has been fixed and it will be available in tomorrow's nightly builds. Thanks for reporting.

**Comment by mblennegard** [comment]
> I reproduced the issue and I'm preparing a PR to fix it

That was quick work of that one.
Awesome!

**Comment by thaHoly7** [comment]
Tried with 2.99.111-nightly but produces same error

**Comment by thaHoly7** [comment]
> Works for me on 2.99.112 : ![image](https://github.com/user-attachments/assets/61e93689-c172-4d37-a891-7340b0484759)
> 
> You might want to open a new issue with details about your error

How can I install 112? 
Tried this but only get 111:
Install-Module pnp.powershell -AllowPrerelease

**Comment by thaHoly7** [comment]
Same here works with 112. Thanks a lot.
