### ISSUE TITLE
[BUG] Connect-PnPOnline to SharePoint admin URL in GCCH

### ISSUE THREAD

**Issue by thomeee86** [pnp/powershell#4265]
I'd like to use PnP Powershell in GCCH so I set the ENV variables:
$ENV:MicrosoftGraphEndPoint = "https://graph.microsoft.us"
$ENV:AzureADLoginEndPoint = "https://portal.azure.us"

I used this command:
Connect-PnPOnline -Url "https://xxxxxx-admin.sharepoint.us" -Interactive -AzureEnvironment USGovernmentHigh -Tenant "xxxxxxxxxxxx"

Bit I get an Authentication issue:
![image](https://github.com/user-attachments/assets/95327826-50e5-4285-87d6-9b61136a2dc8)

And this is the error in powershell:
Connect-PnPOnline : AADSTS65006: Resource '797f4846-ba00-4fd7-ba43-dac1f8f63013' had no entitlements matching required
permissions configured on the required resource access for client '31359c7f-bd7e-475c-86db-fdb8c937548e'. Requested
permission IDs: '41094075-9dad-400e-a0bd-54e686782033'. This is a problem with one or more invalid permission ids on
the client RRA configuration or the resource entitlement configuration. Trace ID: cfb40e36-b8df-4f9d-95ea-c61b41aa0600

### Expected behavior 
I would like to have a successful authentication/connection

### What is the version of the Cmdlet module you are running?
1.12.0
(I have to use version 1, because that's a requirement for this: https://github.com/pnp/provision-assist-m365/blob/main/Deployment-guide.md)

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Hello, PnP Management Shell multi-tenant app has been deleted.

Please check this discussion:

https://github.com/pnp/powershell/discussions/4249

You need to create your own App and then connect to SharePoint.
