### ISSUE TITLE
[BUG] Add-PnPStoredCredential does not add an entry  in Credential Manager using PnP.PowerShell 2.12.0 and PowerShell 7.4.5. 

### ISSUE THREAD

**Issue by IamNiteWalker** [pnp/powershell#4268]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

I am running "Add-PnPStoredCredential -Name "TestEntry" -Username" with a valid username and password. The command runs and does not throw any errors. However, there is no new entry created in the Credential Manager. 

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

That a new entry would be added to the Windows Credentials in the Credential Manager.

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

The command appears to run without any errors, but there is no new entry added.

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

Run Add-PnPStoredCredential with a -name, -username, and -password parameters.

Add-PnPStoredCredential -Name "yourlabel" -Username youruser@domain.com as is stated at https://pnp.github.io/powershell/articles/authentication.html#authenticating-with-pre-stored-credentials-using-the-windows-credential-manager-windows-only

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
2.12 Core

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by jackpoz** [comment]
What does `Get-PnPStoredCredential -Name "yourlabel"` return ? If I test the command it seems to work fine:

![image](https://github.com/user-attachments/assets/ef1bfec0-dd96-4bc9-92c0-4124bdc0c5e3)

**Comment by IamNiteWalker** [comment]
Hmm - seems to be working ok today.

... nevermind!

Thanks

**Comment by gautamdsheth** [comment]
Thanks for confirming, closing the issue.
