### ISSUE TITLE
[BUG] The SiteAlias parameter is not taken into account by New-PnPSite cmdlet

### ISSUE THREAD

**Issue by maeni70** [pnp/powershell#4275]
### Reporting an Issue or Missing Feature
The SiteAlias parameter has no effect when running **New-PnPSite**.

### Expected behavior
According to [Example 10](https://pnp.github.io/powershell/cmdlets/New-PnPSite.html#example-10) in the documentation of this cmdlet:
This will create a new Modern Team Site collection with the title 'Team Contoso' and the url 'https://tenant.sharepoint.com/sites/contoso-site' or 'https://tenant.sharepoint.com/teams/contoso-site' based on the managed path configuration in the SharePoint Online Admin portal. The underlying M365 Group will have 'contoso' as the alias.

### Actual behavior 
I have run the exact same command as in this example:
`New-PnPSite -Type TeamSite -Title 'Team Contoso' -Alias contoso -SiteAlias contoso-site`

I could see the output "https://tenant.sharepoint.com/sites/contoso", and corresponding site has been created but with contoso instead of contoso-site.

### Steps to reproduce behavior
```
$rootConnection = Connect-PnPOnline -Url $url -ClientId $clientId -Thumbprint $tumbprint -Tenant $tenant -ReturnConnection -ErrorAction SilentlyContinue
New-PnPSite -Type TeamSite -Title 'Team Contoso' -Alias contoso -SiteAlias contoso-site -Connection $rootConnection -ErrorAction Stop
```

### What is the version of the Cmdlet module you are running?
As the script is running in PS 5:
`Import-Module PnP.PowerShell -RequiredVersion 1.12.0 -DisableNameChecking:$true -ErrorAction Stop`

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Can you please try with the latest version and check? 1.12 is almost 2 years old and there have too many fixes after that.

**Comment by maeni70** [comment]
@gautamdsheth Thanks. I have tested with **2.12.0** and it works.

BTW, **2.10.0** has thrown following error:
AADSTS1002012: The provided value for scope Group.ReadWrite.All is not valid. Client credential flows must have a scope value with /.default suffixed to the resource identifier (application ID URI).

Closing the bug report now.

**Comment by maeni70** [comment]
This issue came back now. I have tested with version **3.1.0** and **3.2.0** (the newest major release).

**Comment by TheCloudConjurer** [comment]
Experiencing the same bug with version 3.1.0.

**Comment by JSamarxhi** [comment]
Also experiencing this bug in version 3.2.0
