### ISSUE TITLE
[BUG] New-PnPMicrosoft365GroupSettings returns error even on successful execution

### ISSUE THREAD

**Issue by mblennegard** [pnp/powershell#4285]
### Notice
New-PnPMicrosoft365GroupSettings always returns the below error message:
`'PnP.PowerShell.Commands.Model.Microsoft365GroupSetting' does not contain a definition for 'GetAwaiter'`

The actual cmdlet is executed correctly, but it seems the cmdlet expects an await that is simply not there in the underlying method.
When I enable `-Verbose` I can see the web request has been successful: `VERBOSE: Response successful with HTTP 201 Created containing 272 characters`

### Reporting an Issue or Missing Feature
Reporting an Issue

### Expected behavior 
Execution to happen just like now, but not to post an error message if it was in fact executed successfully.

### Actual behavior 
Always post an error message, even on successful execution.

### Steps to reproduce behavior
Exceute the below command:
`New-PnPMicrosoft365GroupSettings -Identity $groupId -DisplayName "Group.Unified.Guest" -TemplateId "08d542b9-071f-4e16-94b0-74abb372e3d9" -Values @{"AllowToAddGuests" = "false" } -Connection $conn`

### What is the version of the Cmdlet module you are running?
2.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
@mblennegard - can you please try with the latest nightly builds (`2.12.4-nightly`) and let us know ? This should be fixed in there.

**Comment by mblennegard** [comment]
> @mblennegard - can you please try with the latest nightly builds (`2.12.4-nightly`) and let us know ? This should be fixed in there.

I have tried the latest nightly build and this is indeed working as expected in that version. 👍
Thank you.
