### ISSUE TITLE
[BUG] Send-PnPMail using Array not working as expected

### ISSUE THREAD

**Issue by svermaak** [pnp/powershell#4293]
### Reporting an Issue or Missing Feature
Send-PnPMail using Array not working as expected

### Expected behavior 
The command to send email out to all users in $to array

### Actual behavior 
Command randomly does not send to one or two users (usually the same two)

### Steps to reproduce behavior

Not working
Send-PnPMail -To $to -Subject "Test from M365" -Body "Please disregard this test email - Regards Shaun Vermaak" -Connection $connection

Working
Send-PnPMail -To  'a','b','c','d','e','f','g','h','i','j'  -Subject "Test from M365" -Body "Please disregard this test email - Regards Shaun Vermaak" -Connection $connection

### What is the version of the Cmdlet module you are running?
Latest

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [X] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [X] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
If its random , not sure what could be the issue. Are there any errors related to this, maybe check logs or something ? Can't reproduce this locally. Is there a way to reliably repro the issue ?

**Comment by KoenZomers** [comment]
Just had a look at the sourcecode here as well. We pass on all TO addresses in one go to Microsoft Graph. We don't apply individual processing on each of them. This means if some don't arrive and some do, it did arrive at Graph and the processing internally within Exchange Online fails somehow. You could check your sent items to see if the mail in there does show all to-addresses. You can also leverage the message trace features within Exchange Online Admin Center to figure out how the e-mails have been processed. I'm afraid there's nothing we can do from PnP PowerShell.
