### ISSUE TITLE
[FEATURE] Register-PnPEntraIDAppForInteractiveLogin requires LaunchBrowser parameter for security key login

### ISSUE THREAD

**Issue by AlyaKoni** [pnp/powershell#4299]
**Is your feature request related to a problem? Please describe.**
We need to register the PnP PowerShell app with the cmdlet Register-PnPEntraIDAppForInteractiveLogin. May this cmdlet does not has the LaunchBrowser parameter like Connect-PnPOnline. In our tenant admins are only able to sign in with a security key. Without the LaunchBrowser parameter it's not possible to login with a security key.

**Describe the solution you'd like**
Please add the LaunchBrowser parameter to the Register-PnPEntraIDAppForInteractiveLogin cmdlet and others where required to allow login with security key.

**Describe alternatives you've considered**
No alternative known! We are blocked and are not able to use PnP cmdlets any more!

**Comment by gautamdsheth** [comment]
hi @AlyaKoni , if you can use nightly builds, you can use `Register-PnPEntraIDAppForInteractiveLogin` with `-DeviceLogin` parameter. It asks you to open browser window where you can enter the generated code and then proceed.

**Comment by gautamdsheth** [comment]
hi @AlyaKoni , we have added this parameter now. It works with `-DeviceLogin` . Will be available in tomorrow's nightly builds .

Thanks !

**Comment by gautamdsheth** [comment]
Actually, supports both Interactive and Devicelogin scenarios :)
