### ISSUE TITLE
[FEATURE] Set-PnPContentType

### ISSUE THREAD

**Issue by ingepepe** [pnp/powershell#430]
**Is your feature request related to a problem? Please describe.**
We have a lot of content types. Sometimes we want to change a property like making them read-only or add columns to several content types. It's too tedious and time-consuming doing it on the UI.

**Describe the solution you'd like**
We should be able to update Content Types from powershell. Something like what _Set-ContentTypes_ would be. Currently this command is missing.

**Describe alternatives you've considered**
Using CSOM commands (https://www.sharepointpals.com/post/powershell-script-to-change-the-content-type-for-an-existing-document-in-modern-sharepoint-site/) is **not** an option for those of us using **MFA**.

**Additional context**
I love all you have done so far! Thank you!

**Comment by LeonArmston** [comment]
Agree this would be nice but in the meantime you could use the script you link to above but just replace lines 1-17 with

```powershell

  #Variables for Processing
  $SiteUrl = "https://ps.sharepoint.com/sites/test”
  $ListName="test"

  #Connection  
  Connect-PnPOnline -Url $SiteUrl -Interactive
  $Context = Get-PnPContext
```

**Comment by ingepepe** [comment]
Thank you @LeonArmston for your thorough response!
