### ISSUE TITLE
[BUG]Get-PnPSiteTemplate -PersistMultiLanguageResources can't create resource files 

### ISSUE THREAD

**Issue by ez1003** [pnp/powershell#4300]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

I ran the below commands to get a template file with resource files.

```
Connect-PnPOnline -Url "https://mytenant.sharepoint.com/sites/TemplateSite" -Interactive

Get-PnPSiteTEmplate -Out "Template.xml" -PersistBrandingFiles -IncludeAllPages -PersistMultiLanguageResources 
```

I can have only Template.xml even though I used the option -**PersistMultiLanguageResources**.
I could get Template.en-US.resx and Template.fr-FR.resx on the old version 2.3.0. 

In the Template.xml, there's SupportedUILanguages but, there's still no resource files.

pnp:SupportedUILanguages
<pnp:SupportedUILanguage LCID="1033" />
<pnp:SupportedUILanguage LCID="1036" />
</pnp:SupportedUILanguages>

The PnP PowerShell versions I tried are:
2.12.0 PnP.PowerShell
2.4.23 nightly PnP.PowerShell
2.4.0 PnP.PowerShell

I opend this issue 6 months ago from [here ](https://github.com/pnp/pnpframework/issues/999) also. 

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets
If I added additional language (English, French) on the site setting - site languages of the current template SharePoint site, the resource files should be created for English and French. (Template.en-US.resx and Template.fr-FR.resx)

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.
No resource files. Only Template.xml file is created. 

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)
1. Go to the SharePoint site to extract the site template file.
2. Add the languages on the Site Setting - Site Languages (ex. English and French)
3. Set the $URL to the site you added the language. 
4. Connect to the site using the $URL (Connect-PnPOnline -Url "https://mytenant.sharepoint.com/sites/TemplateSite" -Interactive)
5. Run the commandlet "Get-PnPSiteTEmplate -Out "Template.xml" -PersistBrandingFiles -IncludeAllPages -PersistMultiLanguageResources" and check the resource files are created on the same location. 

### What is the version of the Cmdlet module you are running? 2.12.0
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by jackpoz** [comment]
I opened a pull request at https://github.com/pnp/powershell/pull/4326 to fix the issue.
As a workaround until it's merged, you can use a .pnp template instead of .xml (but I would just wait for the PR to be merged).

**Comment by gautamdsheth** [comment]
@ez1003  - PR for this has been merged , it will be available in tomorrow's nightly builds as well as the next major release. Thanks for reporting.

**Comment by DanielMisch** [comment]
It is not working until now... we used this very frequently and stuck on the last working PnP version :-(
