### ISSUE TITLE
FieldOptions in Add-PnPTaxonomyField doen't work  

### ISSUE THREAD

**Issue by AnisELTAIEF** [pnp/powershell#434]
When Im executing this command this does not apply the new Taxonomy field does not apply to all Content types and there is no way how to create the taxonomy field as site colum;
_Add-PnPTaxonomyField  -DisplayName "QP_Department" -InternalName "FieldName" -Group "QP" -Id "7e556a9b-6c82-41a8-aafb-eb56496e0eee" -FieldOptions  AddToDefaultContentType, AddToAllContentTypes, AddFieldToDefaultView -TermSetPath "Portal|Departments" -List "Site Pages"_ 
Environment: SharePoint Online 
SharePointPnPPowerShellOnline version:  3.29.2101.0

**Comment by veronicageek** [comment]
@AnisELTAIEF - This repo is for PnP.PowerShell which is the successor of the old module (SharePointPnPPowerShellOnline) and we are now on v1.4.0.
Please refer to the [documentation](https://pnp.github.io/powershell/articles/installation.html) to install this module, and feedback if this is still not working.

**Comment by gautamdsheth** [comment]
@AnisELTAIEF  - thanks for flagging this issue. It has been fixed. Will be available in the nightly tomorrow and in the next major release.

**Comment by AnisELTAIEF** [comment]
looking forward to being resolved.
