### ISSUE TITLE
Add-PnPFieldToContentType does not support field types of "Taxonomy Field"

### ISSUE THREAD

**Issue by AnisELTAIEF** [pnp/powershell#435]
Hi all, 

I have created a new Taxonomy Field using the command "Add-PnPTaxonomyField" 
When I've tried to add this field to content type using the command  "Add-PnPFieldToContentType" I get this error:
Add-PnPFieldToContentType : Column 'QP_Department' does not exist. It may have been deleted by another user.

any help would be appreciated thank you in advance

**Comment by veronicageek** [comment]
Which module are you using and which OS? I see you opened issue #434 with the old module (SharePointPnPPowerShellOnline) so if you're in the same scenario, please install PnP.PowerShell 1.4.0 and feedback if still not working. Thanks
