### ISSUE TITLE
[BUG] 'Create Team' parameter in Set-PnPMicrosoft365Group throwing empty JSON payload error

### ISSUE THREAD

**Issue by StevieBleeds** [pnp/powershell#436]
Hey there,

I've updated the PnP.PowerShell module in Azure Automation to v1.4.0 and I've discovered that the _Create Team_ parameter in _Set-PnPMicrosoft365Group_ is no longer working. 

I noticed during the process, it hangs for a short period of time on this line

`Set-PnPMicrosoft365Group -Identity $Group.GroupId -CreateTeam`

Then, the follow error is thrown
`Message : Empty Payload. JSON content expected. Stacktrace : at PnP.PowerShell.Commands.Base.BasePSCmdlet.ProcessRecord() at System.Management.Automation.CommandProcessor.ProcessRecord() ScriptLineNumber : 175 InvocationInfo : System.Management.Automation.InvocationInfo Exception : System.Management.Automation.PSInvalidOperationException: Empty Payload. JSON content expected. at PnP.PowerShell.Commands.Base.BasePSCmdlet.ProcessRecord() at System.Management.Automation.CommandProcessor.ProcessRecord() CorrelationId : TimeStampUtc : 1/1/0001 12:00:00 AM`

Connection is made using a Service Principal and it was working fine in v1.3.0, so I have removed 1.4.0 and redeployed v1.3.0 in my Automation account and can confirm it's working in that version.

**Comment by gautamdsheth** [comment]
Hello, this has been fixed in the subsequent nightly release.
Please use the latest nightly build ( Install-Module -Name PnP.PowerShell -AllowPrerelease ) to use the cmdlet with CreateTeam parameter.
