### ISSUE TITLE
[BUG] Add-PnPAzureADGroupOwner and Remove-PnPAzureADGroupOwner do not work with distribution group

### ISSUE THREAD

**Issue by akkomats** [pnp/powershell#4364]
### Reporting an Issue or Missing Feature
The documentation states that the Add-PnPAzureADGroupOwner and Remove-PnPAzureADGroupOwner commands can be used to change the owner of a distribution group. However, these commands actually return an error message. This appears to be a limitation of the Graph API. Could you please update the documentation accordingly?

https://pnp.github.io/powershell/cmdlets/Add-PnPAadGroupOwner.html
> Adds users to the owners of an Azure Active Directory group. This can be a security, distribution or Microsoft 365 group.

https://pnp.github.io/powershell/cmdlets/Remove-PnPAadGroupOwner.html
> Removes owners from a particular Azure Active Directory group. This can be a security, distribution or Microsoft 365 group.

https://learn.microsoft.com/en-us/graph/api/group-post-owners?view=graph-rest-1.0&tabs=powershell
> Add a user or service principal to a Microsoft 365 or security group's owners.

### Actual behavior 
![image](https://github.com/user-attachments/assets/3d24c8d4-9c62-456a-9949-2641abbab14f)

### What is the version of the Cmdlet module you are running?
2.10.7

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
@akkomats - thanks for reporting this. Have updated the docs. Will be refreshed shortly, its a Graph API limitation at the moment.
