### ISSUE TITLE
[BUG] Get-PnPAzureADAppSitePermission cmdlet repeatedly pops up 'Approval Required' window

### ISSUE THREAD

**Issue by coimbatourean** [pnp/powershell#4372]
### Reporting an Issue
I am having issues running [Get-PnPAzureADAppSitePermission](https://pnp.github.io/powershell/cmdlets/Get-PnPAzureADAppSitePermission.html) cmdlet.
It repeatedly pops up the ‘Approval Required’ window for this cmdlet, despite admin consent already being granted.
The issue started happening after configuring our own Entra ID application named 'PnP PowerShell', as per [this article](https://pnp.github.io/blog/post/changes-pnp-management-shell-registration/).

### Expected behavior 
‘Approval Required’ window should not pop up for this cmdlet.
Admin consent was already granted and the Connect-PnpOnline cmdlet worked fine at the start of the script.

### Actual behavior 
‘Approval Required’ window pops up, despite admin consent already being granted.
![image](https://github.com/user-attachments/assets/caaf728c-466a-415a-af62-1c35eebf8bc6)

### Steps to reproduce behavior
Run Connect-PnpOnline cmdlet using -ReturnConnection parameter and storing it in a variable $ctx
Then run Get-PnPAzureADAppSitePermission cmdlet using variable $ctx in -Connection parameter

### What is the version of the Cmdlet module you are running?
2.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows

**Comment by rachaelsingleton** [comment]
Was this ever fixed?
