### ISSUE TITLE
[FEATURE] Allow adding the graph permission "ExternalConnection.ReadWrite.OwnedBy"

### ISSUE THREAD

**Issue by ndocosta** [pnp/powershell#4379]
To create app registrations for the graph connectors agents we are required to assign the permission "ExternalConnection.ReadWrite.OwnedBy". This is not included in the list of allowed permissions for the cmdlet Register-PnPAzureADApp.
Is it possible to include this extra permission on that list?

Thanks!

**Comment by joshtransient** [comment]
There seem to be several valid Graph API application scopes missing from the validateset for this command. I found that User.ReadBasic.All is also missing.

**Comment by veronicageek** [comment]
You can add this request in issue #4178 so we keep all in a single one.
