### ISSUE TITLE
[BUG] Add-PnPPageWebPart Creating Broken WebPart for Excel Files in Embed Document Viewer

### ISSUE THREAD

**Issue by teofilosalgado** [pnp/powershell#438]
### Reporting an Issue or Missing Feature
The `Add-PnPPageWebPart` command fails to create embed document viewers for Excel files. The resulting WebPart is just a plain gray square as you can see in the screenshot below. Although it is working perfectly fine for PowerPoint presentations.

![image](https://user-images.githubusercontent.com/7178504/111086636-f8289900-84fb-11eb-8f59-8862f2121287.png)

### Expected behavior 
I'd expect to run: 
```
Add-PnPPageWebPart -Page $page -DefaultWebPartType DocumentEmbed -WebPartProperties @{
    "serverRelativeUrl" = "/sites/PnPResultado/Documentos Compartilhados/[file name].xlsx";
};
```
and it should add a WebPart on my page like the one in the screenshot below:
![image](https://user-images.githubusercontent.com/7178504/111086665-2c03be80-84fc-11eb-8585-79747371f510.png)
just like I normally do for .pptx files.

### Actual behavior 
The command is creating a broken WebPart like the one in the screenshot below:
![image](https://user-images.githubusercontent.com/7178504/111086636-f8289900-84fb-11eb-8f59-8862f2121287.png)
just a plain gray area.

### Steps to reproduce the behavior
The simple script below is enough to reproduce the behavior:
```
# User defined variables
$tenant = "[...]";
$sourceSite = "[...]";

# Constants
$webUrl = "https://{0}.sharepoint.com{1}" -f $tenant, $sourceSite;

# Office 365 Login 
Write-Output $("Connecting to {0}..." -f $webUrl);
Connect-PnPOnline -Url $webUrl -Interactive;

$pageName = "[page name].aspx";
$page = Get-PnPClientSidePage -Identity $pageName;

#Create new WebPart
Add-PnPPageWebPart -Page $page -DefaultWebPartType DocumentEmbed -WebPartProperties @{
    "serverRelativeUrl" = "/sites/PnPResultado/Documentos Compartilhados/[file name].xlsx";
};
```

### What is the version of the Cmdlet module you are running?
**1.4.0**

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by jansenbe** [comment]
@teofilosalgado : please check https://pnp.github.io/pnpcore/using-the-sdk/pages-webparts.html#working-with-web-parts as it explains how to put a configured web part on a page. So it's best to set the resulting json configuration via the -WebPartProperties parameter.

**Comment by teofilosalgado** [comment]
So I've checked the PnP core documentation link you provided and followed the procedure to create a WebPart using the JSON data provided by the WorkBench. Below you will find the resulting WebPart JSON I've obtained from the WorkBench:
```
[
    {
        "controlType": 3,
        "id": "caf707ed-a419-47e6-910e-ab3147029d23",
        "position": {
            "zoneIndex": 1,
            "sectionIndex": 1,
            "controlIndex": 2,
            "layoutIndex": 1
        },
        "webPartId": "b7dd04e1-19ce-4b24-9132-b60a1c2b910d",
        "webPartData": {
            "id": "b7dd04e1-19ce-4b24-9132-b60a1c2b910d",
            "instanceId": "caf707ed-a419-47e6-910e-ab3147029d23",
            "title": "Visualizador de arquivos",
            "description": "Exiba um documento ou arquivo em sua página, incluindo o Word, o Excel, o PowerPoint, o PDF, os modelos 3D e muito mais.",
            "audiences": [],
            "serverProcessedContent": {
                "htmlStrings": {},
                "searchablePlainTexts": {
                    "title": "Registros_87349"
                },
                "imageSources": {},
                "links": {
                    "serverRelativeUrl": "/Documentos%20Compartilhados/Registros_87349.xlsx",
                    "wopiurl": "https://digitalfortytwo.sharepoint.com/_layouts/15/Doc.aspx?sourcedoc=%7BA31E384D-3B1A-4D50-9C67-1E108BAE32CF%7D&file=Registros_87349.xlsx&action=embedview&mobileredirect=true"
                }
            },
            "dataVersion": "1.4",
            "properties": {
                "annotation": "",
                "authorName": "João Salgado",
                "chartitem": "",
                "endrange": "",
                "excelSettingsType": "",
                "file": "https://digitalfortytwo.sharepoint.com/Documentos%20Compartilhados/Registros_87349.xlsx",
                "listId": "77806dfe-6dca-4e01-8b44-b1d730e347f1",
                "modifiedAt": "2021-03-15T11:23:05Z",
                "photoUrl": "/_layouts/15/userphoto.aspx?size=S&accountname=joaosalgado%40digitalfortytwo.onmicrosoft.com",
                "rangeitem": "",
                "siteId": "9653c7f8-fc6b-47e8-9a5f-7b668a9f8d95",
                "startPage": 1,
                "startrange": "",
                "tableitem": "",
                "uniqueId": "a31e384d-3b1a-4d50-9c67-1e108bae32cf",
                "wdallowinteractivity": true,
                "wdhidegridlines": true,
                "wdhideheaders": true,
                "webId": "0d3e4ee2-a702-4689-a01c-c029733c6570",
                "webAbsoluteUrl": "https://digitalfortytwo.sharepoint.com"
            }
        },
        "emphasis": {},
        "reservedHeight": 435,
        "reservedWidth": 727,
        "addedFromPersistedData": true
    }
]
```
Passing this entire JSON as `PropertiesJson` does work but I still need to be able to create WebParts containing Excel and PowerPoint files programmatically and the resulting JSON doesn't seem to be something quite easy to generate in code, especially the `wopi` URLs (or it is and I am missing something).
Could you point me out the basic required fields for an embed Excel file viewer? I am quite new to the modern PnP APIs as you may have noticed 😄

**Comment by jansenbe** [comment]
There's no specific public documentation on the actual json format for each web part. In this case the guid in sourcedoc is the UniqueId property of the file you're trying to show, you'll have to manually craft the correct wopiurl to make this work

**Comment by teofilosalgado** [comment]
Thank you for the clarification 😊. I ended up using `ContentEmbed` instead of `DocumentEmbed` because it was way easier to setup. I basically just needed to define the `embedCode` and everything worked just fine like a file viewer. I will leave my code below in case it may help someone:

```
$code = '<iframe width="400" height="250" frameborder="0" scrolling="no" src="https://[tenant].sharepoint.com/sites/PnPResultado20210315/_layouts/15/Doc.aspx?sourcedoc={' + $guid + '}&action=embedview&wdAllowInteractivity=False&wdHideGridlines=True&wdHideHeaders=True&wdDownloadButton=True&wdInConfigurator=True"></iframe>';
Add-PnPPageWebPart -Column $column -Section $section -Page $page -DefaultWebPartType ContentEmbed -WebPartProperties @{
        "embedCode" = $code;
};
```
So... I guess that's it. Now I am not sure if my original problem was an issue or expected behavior due to Excel files having different controls.
