### ISSUE TITLE
[BUG] Latest version in version check is nightly and not stable one

### ISSUE THREAD

**Issue by tivanchuk-hawe** [pnp/powershell#4408]
### Reporting an Issue or Missing Feature
In latest stable release https://github.com/pnp/powershell/releases/tag/v2.12.0 was changed 
"Removed version check dependency on version.txt located in Github repo. Use metadata from powershellgallery.com instead."
This is OK, but now (unlike previously, check the version history) there are nightly versions in PS Gallery, so when you check there the latest version it shows nightly one.
![image](https://github.com/user-attachments/assets/2ee594d4-ed8b-4bdd-91c3-31c6bcae51e6)

Possible solutions as I see them:
(either or)
1. use [prerelease](https://learn.microsoft.com/en-us/powershell/gallery/concepts/module-prerelease-support?view=powershellget-3.x) for nightly  + update check ignores alpha, beta ones
2. Nightly isn't posted in PS Gallery anymore => check will work as expected after the next stable release
3. If you keep posting nightly in PS Gallery w/o 1st - probably the check should be changed back

### Expected behavior 
Nightly isn't shown on new version check

### Actual behavior 
Update check shows latest nightly version

### Steps to reproduce behavior
1. Installed 2.12.0
2. Connect-PnPOnline
5. warning will shown

### What is the version of the Cmdlet module you are running?
2.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by ddouden** [comment]
Same issue here, running the stable version.
@erwinvanhunen On PSGallery the 2.99.8-nightly version is shown as the current version.

https://www.powershellgallery.com/packages/PnP.PowerShell/2.99.8-nightly

**Comment by KoenZomers** [comment]
Correct. I can reproduce this and found the issue. Thanks for reporting it.
