### ISSUE TITLE
[BUG] Send-PnPMail fails to send mail to certain people when called in an Azure Runbook

### ISSUE THREAD

**Issue by ACSirus** [pnp/powershell#4411]
### Reporting an Issue or Missing Feature
When calling the Send-PnPMail cmdlet I seem to be getting mixed results depending on where it is called from and to whom it is sending mail. e.g:
* Sending to user A from a local PS terminal works fine
* Sending to user A from an Azure Runbook works fine
* Sending to user B from a local PS terminal works fine
* Sending to user B from an Azure Runbook gives the error: "The e-mail message cannot be sent. Make sure the e-mail has a valid recipient."

### Steps to reproduce behavior
Send-PnPMail -To "user@domain.com" -Subject "Subject" -Body "Body"

### What is the version of the Cmdlet module you are running?
PnP is on both Azure Runbooks and on my local machine the same: 2.12.0

**Comment by KoenZomers** [comment]
This doesn't give us anything to work with. Can you share logging? Detailed error messages? Run it with -Verbose and share the output where it fails?

**Comment by ACSirus** [comment]
The logging option in Runbooks and -Verbose did not give any extra information regarding the Send-PnPMail cmdlet, but I found out that I forgot to provide the -Connection parameter. It turns out that the user in question had no access to the currently connected site.
