### ISSUE TITLE
[BUG] "Azure environment parameter" not documented for Register-PnPAzureADApp

### ISSUE THREAD

**Issue by chscott** [pnp/powershell#4434]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature

The documentation for `Register-PnPAzureADApp` makes reference to a required _Azure Environment parameter_ but does not document what this is.

![image](https://github.com/user-attachments/assets/f74796dc-1710-4955-8c7c-35fd1a0773a0)

### Expected behavior 

The parameter should be documented.

### Actual behavior 

The parameter is not documented.

### Steps to reproduce behavior

N/A

### What is the version of the Cmdlet module you are running?

N/A

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
hi @chscott , have added the documentation for this parameter.
Thanks for raising this issue.
