### ISSUE TITLE
[BUG] Inapropriate error message for non-existent term queried.

### ISSUE THREAD

**Issue by SPDEVGUY** [pnp/powershell#4437]
### Reporting an Issue or Missing Feature
When using the Get-PNPTerm method if you specify a non-existant term name it throws an exception and the exception is irrelevant to the command being used (which would mean irrelevant error messages being displayed)

### Expected behavior 
I would expect it to simply return null or no items if the term doesn't exist.  

### Actual behavior 
Currently it throws an exception and the exception is irrelevant to the command.

![image](https://github.com/user-attachments/assets/5db93448-e21e-49d4-b54c-77de86cfc498)

### Steps to reproduce behavior

$termSetName = "ExistingTermSet"
$termGroupName = "ExistingTermGroup"
$nonExistantTerm = "Non-Existant Term"
Get-PnPTerm -TermSet $termSetName -TermGroup $termGroupName -Identity $nonExistantTerm

### What is the version of the Cmdlet module you are running?
latest

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Thanks @SPDEVGUY , have fixed this issue. 
It will be available in tomorrow's nightly builds as well as in the next major version.
