### ISSUE TITLE
[BUG] Unable to use Copy-PnpList with DestinationWebURL parameter

### ISSUE THREAD

**Issue by the1chill** [pnp/powershell#4443]
I am trying to copy a SharePoint List from one site to another site using Copy-PnPList cmdlet with in VS Code and the following lines: 
$list = Get-PnPList -Identity "Xxxxxx"
Copy-PnPList -Identity $list -DestinationWebUrl https://xxxxx.sharepoint.com/sites/xxxxx-dev

### Reporting an Issue or Missing Feature
I have established a connection to the source site, using Connect-PnpOnline successfully. Then, run the script.

### Expected behavior 
Expecting the list to be copied to the other site.

### Actual behavior 
Error is returned: Copy-PnPList: {"odata.error":{"code":"-2130575251, System.Runtime.InteropServices.COMException","message":{"lang":"en-US","value":"The security validation for this page is invalid. Click Back in your Web browser, refresh the page, and try your operation again."}}}

-WhatIf -Verbose produces: 
VERBOSE: Looking up list provided through Identity
VERBOSE: Generating script from list at https://unaka1.sharepoint.com/sites/Orders/Lists/Contracts
VERBOSE: Skipping execution of site script to site at https://unaka1.sharepoint.com/sites/cpsts-dev due to WhatIf flag being provided

### What is the version of the Cmdlet module you are running?
2.12

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
For Connect-PnpOnline , which authentication method are you using ?

**Comment by the1chill** [comment]
I am using the -Interactive option to connect with the Connect-PnPOnline cmdlet. Is this issue due to not using the -ClientId parameter with -Interactive? (I was just reading up on that.)

**Comment by gautamdsheth** [comment]
Yeah, ClientId is mandatory. You can do that either via -ClientId or via environment variable as mentioned in here https://github.com/pnp/powershell/discussions/4249

Going to close this now.
