### ISSUE TITLE
[BUG] Invoke-PnPSiteScript

### ISSUE THREAD

**Issue by jh-sigmadx** [pnp/powershell#4468]
### Reporting an Issue or Missing Feature
Running "Invoke-PnPSiteScript" on a site to _Update_ the list there - does not update the list or add the additional column
In fact - the script exits complaining that the "List already Exists"
The script was run once to create the list from the json file.
The json file was then amended to include a brand new column (by extracting from an existing list again using: Get-PnPSiteScriptFromList -List $listName)
The script was then run again on the same site, but giving the output:

### Expected behavior 
I expect the List schema to be _Updated_, and the new column added, as per the documentation here:
[https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview](url)

This Documentation states:
"Site scripts can be run again on the same site after provisioning. Site scripts are non-destructive, so when they run again, they ensure that the site matches the configuration in the script.

For example, if the site already has a list with the same name that the site script is creating, the site script will only add missing fields to the existing list."

### Actual behavior 
The Output for the "CreateSPList" action is:

`ErrorCode   : -2130575342
Outcome     : 2
OutcomeText : List with name TestList already exists.
Target      : 
TargetId    : 
Title       : Create or update list "TestList"`

### Steps to reproduce behavior
Export a List to a json definition using 
`Get-PnPSiteScriptFromList -List $listName > list.json`
Create a new list using 
`Invoke-PnPSiteScript -Script list.json`

Edit the List (manually) to add a new Column
Repeat the above process to update the list.json, and to update the existing list with the additional column

### What is the version of the Cmdlet module you are running?
I have tried with both version 2.12 and the nightly build 2.99.2

### Which operating system/environment are you running PnP PowerShell on?
Linux - Powershell version 7.4.4

**Comment by gautamdsheth** [comment]
hi @jh-sigmadx , this is not a bug.
This is a behavior of the site scripts functionality, not a bug.

Site scripts can't update existing lists. 

You can consider using PnP Templates :

https://pnp.github.io/powershell/cmdlets/Get-PnPSiteTemplate.html

https://pnp.github.io/powershell/cmdlets/Invoke-PnPSiteTemplate.html

**Comment by jh-sigmadx** [comment]
I am sorry, but either you are WRONG, or the documentation is WRONG and misleading.

https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview
[https://learn.microsoft.com/en-us/media/open-graph-image.png]<https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview>
SharePoint site template and site script overview<https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview>
Use SharePoint site scripts and site templates to provide custom configurations to apply when new sites are created.
learn.microsoft.com
"Site scripts can be run again on the same site after provisioning. Site scripts are non-destructive, so when they run again, they ensure that the site matches the configuration in the script.
For example, if the site already has a list with the same name that the site script is creating, the site script will only add missing fields to the existing list."


Please have the Documentation updated, as it is FALSE Advertising, which is illegal in the UK.


Regards,



James Hathaway

Technical Director - Sigma DX Ltd

[cid:cfda0967-e308-4e0b-8592-d527b8717e2b]

m: +44 (0)7764 492 940

e: ***@***.******@***.***>

w: http://sigmadx.co.uk<http://sigmadx.co.uk/>

l:  LinkedIn<http://www.linkedin.com/company/sigma-dx-ltd>

f:  Facebook<https://www.facebook.com/Sigma-DX-Ltd-109405050494760>

Registered in the UK: 12050438

***@***.***?anonymous&ep=bwmEmailSignature>            Book time to meet with ***@***.***?anonymous&ep=bwmEmailSignature>
________________________________

**Comment by gautamdsheth** [comment]
hi @jh-sigmadx , tested this today in my environment. 

The docs are incorrect, we can't update the same list with updated schema. 
They need to be updated by Microsoft, would suggest you raise the issue here and ask them to update the docs : https://github.com/SharePoint/sp-dev-docs , nothing we can do from PnP PowerShell side of things.

Besides this, there are also other issues with Site scripts/designs in general:

https://github.com/SharePoint/sp-dev-docs/issues/4081

https://github.com/SharePoint/sp-dev-docs/issues/4268

**Comment by jh-sigmadx** [comment]
Hi @gautamdsheth,

Thanks for the information.

It is also worth noting that if I use "Invoke-PnPSiteDesign" (renamed from "Invoke-PnPSiteTemplate") as you previously suggested  - then the List Schemas are updated CORRECTLY as per the documentation - This is after uploading the Schemas to the Tenancy using "Add-PnPSiteScript" and "Add-PnPSiteDesign".
It is simply the "Invoke-PnPSiteScript" cmdlet that fails to Update the List Schema, and I would have thought that they both leveraged the same commands/code base... 
Any Idea why "Invoke-PnPSiteTemplate" works but "Invoke-PnPSiteScript" does not?

The main reason that "Invoke-PnPSiteScript" would have been an huge advantage, is that it only requires "Edit/Full Control" delegated permissions on the Site/List in question. Uploading the scripts into site scripts and templates requires SharePoint Administrator security role, and our InfoSec guys are telling me that this is huge overkill, and violates ISO27001...

Still, it's the only way to achieve what we need at the moment, it just involves creating a load of site scripts and site templates, updating the list schemas, and then deleting all the scripts and templates again - The only down-side is the insane elevated permissions I need to do it!

James.
