### ISSUE TITLE
[BUG] With changes to M365 App Registration, we need detailed information on which permissions are required for which cmdlets

### ISSUE THREAD

**Issue by sparkle263** [pnp/powershell#4472]
### Reporting an Issue or Missing Feature
Several PNP Cmdlets are still failing after creating the Tenant-specific App registration.
Because our scripts were working prior to this change, and some are working after, we know it is likely due to some permissions that are still missing in this new registration.
However, when this happens, there is no specific information provided on what is missing (Error is generic).

I am also not finding any specific documentation anywhere - per cmdlet - of which permissions are required to run successfully. 
(This is needed for several/all cmdlets within this module, Request-PnPPersonalSite being one of them for today.)

Our account is being used Interactively (due to MFA), and has the full SharePoint Administrator Role (All sites in Tenant).

Or if there is any resource you can point me to where we can test to identify which permissions are missing / needed. 
i.e. documentation / web tool like they have for MS Graph etc.

### Expected behavior 
For this Cmdlet, perform the task as expected, and if not provide more information as to why / what permission(s) are missing.

### Actual behavior 
For this specific cmdlet (there are others), this is the error information returned:
ERROR: [ Request-PnPPersonalSite : Attempted to perform an unauthorized operation. ]
Error Exception Type Fullname: [ Microsoft.SharePoint.Client.ServerUnauthorizedAccessException ]

### Steps to reproduce behavior
For this specific cmdlet (there are others), this is the syntax used:
Request-PnPPersonalSite -UserEmails "user1@ourdomain.com" -NoWait -Connection $MyPnPConnection -Verbose

### What is the version of the Cmdlet module you are running?
We are using Module version 1.12.0 due to limitation with PS ISE / 5.1.
(We can make this work, but with the new app registration requirement, we need to know more information on the permissions needed)

### Which operating system/environment are you running PnP PowerShell on?
- [ X ] Windows (Server 2022)

**Comment by alexsie48** [comment]
Could not agree more. We have started running into this problem with multiple cmdlets. We need more information to make these fixes.

**Comment by gautamdsheth** [comment]
Closing this since we have a duplicate , https://github.com/pnp/powershell/issues/4353
