### ISSUE TITLE
[BUG] When using Set-PnPListItem in batch mode managed metadata column values are not being set when multiple terms are provided

### ISSUE THREAD

**Issue by kboschman** [pnp/powershell#4475]
### Reporting an Issue or Missing Feature
Reporting an issue

### Expected behavior 
Script:
```
$list = 'List'
$ID = 1
# Store the terms in an array
$terms = @()
terms += 'TermGroup|TermSet|Term1'
terms += 'TermGroup|TermSet|Term2'

$batch = New-PnPBatch

Set-PnPListItem -List $list -Identity $ID -UpdateType "UpdateOverwriteVersion" -Values @{"ManagedMetadataTest" = $terms;} -Batch $batch

Invoke-PnPBatch -Batch $batch
```

After execution of the script, the ManagedMetadataTest column should contain the 'Term1' & 'Term2' values.

### Actual behavior 
The ManagedMetadataTest column is empty.
If the Set-PnPListItem command is executed without the batch parameter, the ManagedMetadataTest column is updated correctly.
Also, if only 1 term is specified, as a string, the Set-PnPListItem command works in batch mode.

### Steps to reproduce behavior
1. Create a term set with multiple terms
2. Create a managed metadata column called 'ManagedMetadataTest' in a document library based on the existing term set
3. Create a file in this library and get the ID of the file 
4. Update the variables in the script & execute the script

### What is the version of the Cmdlet module you are running?
Manifest   2.12.0                PnP.PowerShell                      Core 

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by jackpoz** [comment]
I was able to reproduce the issue and fixed it with https://github.com/pnp/powershell/pull/4597 . You could try out that PR if you know how to build PnP PowerShell yourself, or wait for it to be reviewed and approved.

As a workaround in the meantime, using term guids instead of 'TermGroup|TermSet|Term1' format should work.
