### ISSUE TITLE
[BUG] Conflict between Microsoft.Graph and PnP.PowerShell Modules in VsCode PowerShell Extension

### ISSUE THREAD

**Issue by IoannisGianko** [pnp/powershell#4476]
### Summary
I'm encountering an issue when using the Microsoft.Graph PowerShell module in combination with the PnP.PowerShell module while connecting via a certificate. The issue only occurs within the PowerShell Extension terminal in VSCode.

### Expected Behavior:
The command should execute successfully without any errors.

### Actual Behavior:
After connecting, any attempt to run a MgGraph command results in the following error:
`Could not load type 'Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider' from assembly 'Microsoft.Graph.Core, Version=1.25.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.`

### Notes
- The issue does not occur if the PnP.PowerShell module is uninstalled or downgraded to version 2.2.0.
- The issue is only present when using the PowerShell Extension terminal in VSCode. Opening a standard PowerShell terminal within VSCode does not produce the error.
- I have tested this across multiple machines, and the issue persists.
- Installing PnP.PowerShell v2.2.0 resolves the issue.
- Opening a standard PowerShell Core Terminal, outside of VsCode, does not produce the error.

Is there a known incompatibility between these two modules in the PowerShell Extension, or any workarounds besides downgrading the PnP.PowerShell module?

I had opened a ticket [#5069](https://github.com/PowerShell/vscode-powershell/issues/5069) with the PowerShell VsCode extension and they advised to raise it with PnP.PowerShell saying that there are multiple known issues with their ALC implementation.
Related: [#3510](https://github.com/PowerShell/vscode-powershell/issues/3510)

### Steps to Reproduce
1. Install the Microsoft.Graph PowerShell module.
2. Install the PnP.PowerShell module (any version newer than v2.2.0).
3. Open the PowerShell Extension terminal in VSCode.
4. Run the following command to connect to Microsoft Graph:
   `Connect-MgGraph -ClientId $clientID -TenantId $tenantID -CertificateThumbprint $thumbPrint`
6. After connecting, attempt to run any MgGraph command.
   `Get-MgOrganization`

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

### Visuals
![mggraphnotworkingwithpnp18](https://github.com/user-attachments/assets/1eb662ac-cd8f-4ddc-a720-f207734408de)

**Comment by IoannisGianko** [comment]
Hi @gautamdsheth, I'm not using PnP PowerShell at all, and it is still doing this.
As mentioned above, all you have to do to replicate this is to have PnP PowerShell installed

**Comment by MikeGitUser** [comment]
Hi @gautamdsheth,

This should not have been closed.  This seems to be a unique issue specific to Visual Studio Code and the PowerShell Extension.  I am using Connect-MgGraph with a certificate thumbprint as well.

The workarounds for https://github.com/pnp/powershell/issues/3637 do not work (i.e. calling Graph first) in this case.

Really need a solution/workaround for this!

Thanks!

**Comment by Borgquite** [comment]
If you are still experiencing this issue, it may be resolved in the latest nightly builds
https://github.com/pnp/powershell/issues/3637
