### ISSUE TITLE
 Cannot call this API with an app-only principal.

### ISSUE THREAD

**Issue by harshdamaniahd** [pnp/powershell#4478]
Cannot call this API with an app-only principal.

What kind of permissions are needed for these commands Set-PnPSiteVersionPolicy -EnableAutoExpirationVersionTrim $false -MajorVersions 100  -ExpireVersionsAfterDays 0  -MajorWithMinorVersions 0

**Comment by NishkalankBezawada** [comment]
Hello @harshdamaniahd 

I tried with App only approach and got the same error. 

Required permissions for this command is 
|        Type      |                    API/ Permission Name                    |                    Admin consent required                    |
| --------------- | --------------------------------------- | -------- |
| Delegated       | AllSites.FullControl | yes                               |

With below approach using parameters ClientId, DeviceLogin, LaunchBrowser

```
Connect-PnPOnline -ClientId xxxxxxxx-0000-4xxxx-xxxx-xxxxxxxxxxx -Url "https://xxxx.sharepoint.com/sites/xxxx" -DeviceLogin -LaunchBrowser -Tenant xxxxx
```

I was able to execute this succesfully

```
PS C:\Research\PnPCommunity\powershell> Set-PnPSiteVersionPolicy -EnableAutoExpirationVersionTrim $false -MajorVersions 100 -MajorWithMinorVersions 10 -ExpireVersionsAfterDays 200
WARNING: The setting for new libraries takes effect immediately. Please run Get-PnPSiteVersionPolicy to display the newly set values.
WARNING: The setting for existing libraries takes at least 24 hours to take effect. Please run Get-PnPSiteVersionPolicyStatus to check the status.
WARNING: The setting for existing libraries does not trim existing versions.
PS C:\Research\PnPCommunity\powershell>
```

<img width="847" alt="image" src="https://github.com/user-attachments/assets/f6cb06c0-be88-40f8-b548-5caaf5b4b7a1">


@gautamdsheth I will add required permissions for these two commandlets in the PR #4488 

Thanks,
Nish

**Comment by harshdamaniahd** [comment]
Thanks I should try this
