### ISSUE TITLE
Register-PnPAzureADAppWindows Cryptography Next Generation (CNG) is not supported on this platform.

### ISSUE THREAD

**Issue by levalencia** [pnp/powershell#449]
**Is your feature request related to a problem? Please describe.**
Register-PnPAzureADApp: Windows Cryptography Next Generation (CNG) is not supported on this platform.

**Describe the solution you'd like**
I would like to be able to register Azure AD apps, from a MAC or Cloud Shell.

**Describe alternatives you've considered**
Not sure if there is any other way other than spinning a VM in Azure with Powershell

**Additional context**
I use a Mac and I dont have access to a windows machine. I tried using powershell for Mac, and I also tried runninng powershell on an Azure Cloud Shell, both with same results.

**Comment by mbice** [comment]
We'd also like to see this capability added. Any chance it's in the near term roadmap to add support for it?

**Comment by levalencia** [comment]
agree!

**Comment by nataliyaioffe** [comment]
Would love an update on this issue!

**Comment by srmo** [comment]
Same here. Hitting it on MacOS 11.6 with $PSVersionTable see below. Is this here even the right place to ask for?
```
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Darwin 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEAS…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by maxali** [comment]
I have the same issue on Ubuntu with `New-PnPAzureCertificate` and `Register-PnPAzureADApp`

**New-PnPAzureCertificate: Windows Cryptography Next Generation (CNG) is not supported on this platform.**

**Comment by gautamdsheth** [comment]
Can you paste the error message , maybe a detailed stacktrace here ? You can do that by trying `New-PnPAzureCertificate` and then `Get-PnpException` ? Will be a bit difficult to figure out and fix , but can give it a try

**Comment by kolja1507** [comment]
@gautamdsheth:

`Get-PnpException` after `Register-PnPAzureADApp`:

```
Message          : Windows Cryptography Next Generation (CNG) is not supported on this platform.
Stacktrace       :    at System.Security.Cryptography.RSACng..ctor(Int32 keySize)
                      at 
                   PnP.PowerShell.Commands.Utilities.CertificateHelper.CreateSelfSignedCertificate(String 
                   commonName, String country, String state, String locality, String organization, String 
                   organizationUnit, SecureString password, String friendlyName, DateTimeOffset from, 
                   DateTimeOffset to) in c:\build\src\Commands\Utilities\CertificateHelper.cs:line 313
                      at PnP.PowerShell.Commands.AzureAD.RegisterAzureADApp.GetCertificate(PSObject 
                   record) in c:\build\src\Commands\AzureAD\RegisterAzureADApp.cs:line 516
                      at PnP.PowerShell.Commands.AzureAD.RegisterAzureADApp.ProcessRecord() in 
                   c:\build\src\Commands\AzureAD\RegisterAzureADApp.cs:line 197
                      at System.Management.Automation.Cmdlet.DoProcessRecord()
                      at System.Management.Automation.CommandProcessor.ProcessRecord()
ScriptLineNumber : 1
```

**Additional context**

```
Version              Name                                Repository           Description
-------              ----                                ----------           -----------
1.10.0               PnP.PowerShell                      PSGallery            Microsoft 365 Patterns and Practices PowerShell Cmdlets
```

```
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Linux 5.4.0-1085-azure #90~18.04.1-Ubuntu SMP Fri Jun 10 18:32:22 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by gautamdsheth** [comment]
Can you give it a try with tomorrow's nightly release and let us know ? 
Have merged a potential fix for this , maybe it can help ?

**Comment by gautamdsheth** [comment]
hi @kolja1507 , any update on this ? We also did a major 1.11.0 release, maybe you can try that and let us know ?

**Comment by kolja1507** [comment]
@gautamdsheth Works with v1.11.0, thanks a lot!

**Comment by gautamdsheth** [comment]
@kolja1507 - thanks for confirming!! Closing this issue 😊
