### ISSUE TITLE
[BUG] Get-PnPPlannerPlan: More than one plan with the same title found.

### ISSUE THREAD

**Issue by jthombenj** [pnp/powershell#4494]
### Reporting an Issue or Missing Feature
When running this cmdlet with a specifically titled plan, I receive the error "More than one plan with the same title found"

### Expected behavior 
I expect to be able to pull the specific plan I'm referencing.

### Actual behavior 
I get an error telling me multiple plans with the same title exist. There is a plan with a similar title, but I'm specifically referencing one plan.

<img width="433" alt="get plans" src="https://github.com/user-attachments/assets/db624133-4486-4bb1-9ecb-d414edcd1777">
<img width="662" alt="get 2025" src="https://github.com/user-attachments/assets/ca270a8d-c698-4929-a379-c63cf1bbbe3a">

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Closing this as @jackpoz improved the error message, it will be available in tomorrow's nightly builds.
