### ISSUE TITLE
[BUG] reporting a code issue related to message center post MC244197

### ISSUE THREAD

**Issue by plagooms** [pnp/powershell#450]
### Reporting an Issue or Missing Feature
Hello, I am reporting a code issue related to message center post MC244197.
https://admin.microsoft.com/Adminportal/Home?source=applauncher&ref=MessageCenter/:/messages/MC244197

### Expected behavior 
We expect that the script allows admins to collect information (metadata) about a given document based upon it's site id and unique id.

-- List information about the document based upon the site id and document unique id:
.\GetDocumentMetadataViaSiteIdUniqueId.ps1 "b56adf79-ff6a-4964-a63a-ff1fa23be9f8" "e2a52975-ceae-41b3-9271-315a5cfba6b2"
The output shows the Author and Path toward the provided document:

Author   Path
------   ----
Joe Doe  https://contoso.sharepoint.com/sites/demo/pnp/Rocks!.docx

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

PS C:\Users> Connect-PnPOnline -Url https://tenanturl.com -Interactive

PS C:\Users> cd C:\PSScript

PS C:\PSScript> .\GetDocumentMetadataViaSiteIdUniqueId.ps1 "3a89672d-3336-44d0-befb-91744242fbe6" "854cb195-7675-447a-b651-628db924aacd"
At C:\PSScript\GetDocumentMetadataViaSiteIdUniqueId.ps1:8 char:18
+ <html lang="en" >
+                  ~
Missing file specification after redirection operator.
At C:\PSScript\GetDocumentMetadataViaSiteIdUniqueId.ps1:172 char:21
+                 Sign&nbsp;up
+                     ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:\PSScript\GetDocumentMetadataViaSiteIdUniqueId.ps1:179 char:21
+                 Sign&nbsp;up
+                     ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:\PSScript\GetDocumentMetadataViaSiteIdUniqueId.ps1:206 char:189
+ ... ata-ga-click="(Logged out) Header, go to Features">Features <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\PSScript\GetDocumentMetadataViaSiteIdUniqueId.ps1:206 char:269
+ ... nk-symbol float-right text-normal color-text-tertiary pr-3">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:\PSScript\GetDocumentMetadataViaSiteIdUniqueId.ps1:208 char:165
+ ... ck Link--secondary no-underline f5 Bump-link--hover">Mobile <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\PSScript\GetDocumentMetadataViaSiteIdUniqueId.ps1:208 char:245
+ ... nk-symbol float-right text-normal color-text-tertiary pr-3">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:\PSScript\GetDocumentMetadataViaSiteIdUniqueId.ps1:209 char:176
+ ... k Link--secondary no-underline f5 Bump-link--hover">Actions <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\PSScript\GetDocumentMetadataViaSiteIdUniqueId.ps1:209 char:256
+ ... nk-symbol float-right text-normal color-text-tertiary pr-3">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:\PSScript\GetDocumentMetadataViaSiteIdUniqueId.ps1:210 char:182
+ ... ink--secondary no-underline f5 Bump-link--hover">Codespaces <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingFileSpecification
 

PS C:\PSScript> .\GetDocumentMetadataViaSiteIdUniqueId.ps1 "854cb195-7675-447a-b651-628db924aacd" "3a89672d-3336-44d0-befb-91744242fbe6"
At C:\PSScript\GetDocumentMetadataViaSiteIdUniqueId.ps1:8 char:18
+ <html lang="en" >
+                  ~
Missing file specification after redirection operator.
At C:\PSScript\GetDocumentMetadataViaSiteIdUniqueId.ps1:172 char:21
+                 Sign&nbsp;up
+                     ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:\PSScript\GetDocumentMetadataViaSiteIdUniqueId.ps1:179 char:21
+                 Sign&nbsp;up
+                     ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:\PSScript\GetDocumentMetadataViaSiteIdUniqueId.ps1:206 char:189
+ ... ata-ga-click="(Logged out) Header, go to Features">Features <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\PSScript\GetDocumentMetadataViaSiteIdUniqueId.ps1:206 char:269
+ ... nk-symbol float-right text-normal color-text-tertiary pr-3">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:\PSScript\GetDocumentMetadataViaSiteIdUniqueId.ps1:208 char:165
+ ... ck Link--secondary no-underline f5 Bump-link--hover">Mobile <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\PSScript\GetDocumentMetadataViaSiteIdUniqueId.ps1:208 char:245
+ ... nk-symbol float-right text-normal color-text-tertiary pr-3">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:\PSScript\GetDocumentMetadataViaSiteIdUniqueId.ps1:209 char:176
+ ... k Link--secondary no-underline f5 Bump-link--hover">Actions <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\PSScript\GetDocumentMetadataViaSiteIdUniqueId.ps1:209 char:256
+ ... nk-symbol float-right text-normal color-text-tertiary pr-3">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:\PSScript\GetDocumentMetadataViaSiteIdUniqueId.ps1:210 char:182
+ ... ink--secondary no-underline f5 Bump-link--hover">Codespaces <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingFileSpecification
 

PS C:\PSScript> cd C:\PSScript

### Steps to reproduce behavior
The link below include the complete script and code samples 
https://github.com/pnp/powershell/tree/dev/samples/MetadataViaSiteIdUniqueId

### What is the version of the Cmdlet module you are running?

directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands                                                                                                                  
---------- -------    ----                                ----------------                                                                                                                  
Manifest   1.4.0      PnP.PowerShell                      {Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add-PnPClientSideText, Add-PnPClientSideWebPart...}   

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by plagooms** [comment]
![Github issue-MC244197](https://user-images.githubusercontent.com/44791367/111396684-92563000-86fa-11eb-9b9a-2cb1a76a0205.png)

**Comment by plagooms** [comment]
Please ignore the error I sent earlier..use this new one instead.  Sorry for the confusion. 
![Github issue new-MC244197](https://user-images.githubusercontent.com/44791367/112162558-222e3980-8c27-11eb-983f-7a649eb84ca2.png)

**Comment by erwinvanhunen** [comment]
Hi!

The issue you're seeing is most likely because you're using the wrong id of the file you're looking for. Notice that if you use for instance Get-PnPListItem you get the GUID of the -listitem- but not of the underlying file.

To retrieve the unique id:

```powershell
$site = Get-PnPSite -Includes Id
$siteId = $site.Id
$item = Get-PnPListItem -List <yourlibrary> -Id <id of the item> -Fields "UniqueId"
$uniqueid = $item["UniqueId"]
.\GetDocumentMetadataVisSiteUniqueId.ps1 $siteId $uniqueid
```
