### ISSUE TITLE
[BUG] Add-PnPSiteScript -WhatIf parameter cannot be found

### ISSUE THREAD

**Issue by jh-sigmadx** [pnp/powershell#4513]
When running Add-PnPSiteScript using the -WhatIf parameter, as described in the documentation:
https://pnp.github.io/powershell/cmdlets/Add-PnPSiteScript.html
Results in an error thrown:
"A parameter cannot be found that matches parameter name 'WhatIf'"
 - WhatIf is listed in the Paramters section, but not mentioned in the Syntax section.
 - Is this an error in the documentation? (I have noticed similar issues logged for WhatIf not working for other cmdlets...)

### Expected behavior 
I expect the cmdlet to simulate adding the Site Script.

### Actual behavior 
Results in an error thrown:
"A parameter cannot be found that matches parameter name 'WhatIf'"

### Steps to reproduce behavior
Run Add-PnPSiteScript with the -WhatIf parameter

### What is the version of the Cmdlet module you are running?
2.12.0
2.99.20

### Which operating system/environment are you running PnP PowerShell on?
Linux
(pwsh version 7.4.4)

**Comment by gautamdsheth** [comment]
Thanks for catching this, have removed it.

**Comment by jh-sigmadx** [comment]
Whilst I appreciate that this is the easiest solution, would it not be better to make the -WhatIf parameter actually work?

It would be a really big help for our scripts...!
