### ISSUE TITLE
[BUG] Add-PnPSiteDesign -WhatIf parameter cannot be found

### ISSUE THREAD

**Issue by jh-sigmadx** [pnp/powershell#4514]
When running Add-PnPSiteDesign using the -WhatIf parameter, as described in the documentation:
https://pnp.github.io/powershell/cmdlets/Add-PnPSiteDesign.html
Results in an error thrown:
"A parameter cannot be found that matches parameter name 'WhatIf'"

WhatIf is listed in the Paramters section, but not mentioned in the Syntax section.
Is this an error in the documentation? (I have noticed similar issues logged for WhatIf not working for other cmdlets...)
Expected behavior
I expect the cmdlet to simulate adding the Site Design.

Actual behavior
Results in an error thrown:
"A parameter cannot be found that matches parameter name 'WhatIf'"

Steps to reproduce behavior
Run Add-PnPSiteDesign with the -WhatIf parameter

What is the version of the Cmdlet module you are running?
2.12.0
2.99.20

Which operating system/environment are you running PnP PowerShell on?
Linux
(pwsh version 7.4.4)

**Comment by gautamdsheth** [comment]
Thanks for spotting this, have removed it.
