### ISSUE TITLE
[FEATURE] Add additional parameter -TermGroupAdmin to certain Termgroup Cmdlets to set an Group Administrator in Site Collections or Tenant Wide

### ISSUE THREAD

**Issue by paxvas** [pnp/powershell#4525]
If I want to update multiple Site Collection Termgroups to have a specific Termgroup admininistrator I can do this only via the web interface or via PnP Template import. This is frustrating if I have to update many Sites. Furthermore selfservice automation scenarios are difficult to achive.

The solution would be to add a new parameter **-TermGroupAdmin** certain Termgroup Cmdlets:

- Export-PnPTermGroupToXml
- Import-PnPTermGroupFromXml
- New-PnPTermGroup
- Set-PnPTermGroup

where I can specify a user or group who should be the administrator of this group. With this new parameter I could batch update Site collection term groups and build selfservice automation scenarios like "Set Termgroup admin for Site Collections I own" etc.

Microsoft SPO Management Shell is also not supporting this option.

**Comment by gautamdsheth** [comment]
hi @paxvas , starting with tomorrow's nightly builds, you will be able to set the contributors and managers of the term group via New/Set-PnPTermGroup cmdlets.

Have updated the docs as well around this with an example. 
The `PnPTermGroupToXml` cmdlets already support exporting and importing them. 

Thanks for raising this feature request.

**Comment by paxvas** [comment]
Hi Team,

thank you for the good news :-) appreciate your work.

Kind regards janko


Am Do., 21. Nov. 2024 um 21:18 Uhr schrieb Gautam Sheth <
***@***.***>:
