### ISSUE TITLE
[BUG] Get-PnPTenantSite doesn't report SharingAllowedDomainList when used in For Loop

### ISSUE THREAD

**Issue by keithbreazeale** [pnp/powershell#4552]
### Reporting an Issue or Missing Feature
When using Get-PnPTenantSite the -SharingAllowedDomainList is empty when exporting to CSV but shows when querying directly against a URL.

### Expected behavior 
I expect to see a list of domains where applicable on the csv export.

### Actual behavior 
All other parameters report back as expected but for SharingAllowedDomainList, it's empty.

### Steps to reproduce behavior
`# Connect to SharePoint Online
Connect-PnPOnline -Url "https://123-admin.sharepoint.com" -UseWebLogin

$sites = Get-PnPTenantSite -Detailed -IncludeOneDriveSites

$siteInfo = @()

foreach ($site in $sites) {
    $siteDetails = [PSCustomObject]@{
        DisplayName           = $site.Title
        URL                   = $site.Url
        Owner                 = $site.Owner
        Template              = $site.Template
        StorageUsage          = $site.StorageUsageCurrent
        LastModifiedDate      = $site.LastContentModifiedDate
        SharingCapability     = $site.SharingCapability
        SharingAllowedDomainList = $site.SharingAllowedDomainList -join '; '
        LockState             = $site.LockState
    }
    $siteInfo += $siteDetails
}

$siteInfo | Export-Csv -Path "C:\Script Output\TestOutput.csv" -NoTypeInformation

Write-Host "Site collection information exported to CSV successfully."`

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
2.12.0 Core
### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by ToddKlindt** [comment]
Normally I would recommend adding this to your loop:
`Get-PnPProperty -ClientObject $site -Property SharingAllowedDomainList`
but I get an object type error when I run that. In theory, that would populate the SharingAllowedDomainLIst if it's not one that gets pulled. 
Maybe someone smarter than me will see this and be able to help you out. :)

**Comment by gautamdsheth** [comment]
@keithbreazeale - this is a CSOM limitation. It will only return certain properties if queried against the site itself. 

So , if you need that info, you need to specify it as :

```
$site = get-pnptenantsite -Detailed -Identity "<site-Url>"
```
