### ISSUE TITLE
[BUG] Add-PnPFileSensitivityLabel - Unable to remove label - argument to parameter is an empty string.

### ISSUE THREAD

**Issue by CMoons365** [pnp/powershell#4565]
Running the Add-PnPFileSensitivityLabel cmdlet to remove the sensitivity label information for a file at the specified URL returns the following:

Add-PnPFileSensitivityLabel: Cannot bind argument to parameter 'SensitivityLabelId' because it is an empty string.

Example used:
Add-PnPFileSensitivityLabel -Identity "/sites/XXX-XX/Shared Documents/XXXX.docx" -SensitivityLabelId "" -JustificationText "Previous label no longer applies" -AssignmentMethod Privileged

<img width="497" alt="Screenshot 2024-11-21 121918" src="https://github.com/user-attachments/assets/7b95d695-fe56-43b8-bcb9-f6deec3a7969">

**Comment by gautamdsheth** [comment]
hi @CMoons365 , thanks for testing this and raising this issue.
This has been fixed and will be available in tomorrow's or later nightly builds.
Much appreciated.

**Comment by CMoons365** [comment]
> hi @CMoons365 , thanks for testing this and raising this issue. This has been fixed and will be available in tomorrow's or later nightly builds. Much appreciated.

@gautamdsheth thank you for the fix. I can confirm that this is now working.
