### ISSUE TITLE
[BUG] Add-PnPPageWebPart | WebPartProperties not working as in old version

### ISSUE THREAD

**Issue by HeKr09** [pnp/powershell#459]
### Reporting an Issue or Missing Feature
I try to add WebPart by using the cmdlet Add-PnPPageWebPart with WebPartProperties.

### Expected behavior 
I expect to put in a WebPart with the specified WebPartProperties as worked in the archieved PnP.

### Actual behavior 
I am running this code on a already created page:
```
Add-PnPPageWebPart -Page $page -Section 6 -Column 1 -Order 1 -DefaultWebPartType Spacer -WebPartProperties "{'autoHide':true,'height':84}"
```
I get then the following error:
```
Add-PnPPageWebPart : Cannot bind parameter 'WebPartProperties'. Cannot convert value "{'autoHide':true,'height':84}"
to type "PnP.PowerShell.Commands.Base.PipeBinds.PropertyBagPipeBind". Error: "''' is an invalid start of a property
name. Expected a '"'. LineNumber: 0 | BytePositionInLine: 1."
At D:\TFS\Create-ContentTemplate.ps1:222 char:118
+ ... WebPartType Spacer -WebPartProperties "{'autoHide':true,'height':84}"
+                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Add-PnPPageWebPart], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,PnP.PowerShell.Commands.WebParts.AddWebPart
```

### Steps to reproduce behavior
see above.

### What is the version of the Cmdlet module you are running?
1.4.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
We changed behind the scenes to a different JSON parser. This parser does not accept a single quote as a property delimiter but requires a double quote. Please try:

```powershell
Add-PnPPageWebPart -Page $page -Section 6 -Column 1 -Order 1 -DefaultWebPartType Spacer -WebPartProperties "{`"autoHide`":true,`"height`":84}"
```

Notice the use of the escape character before the double quotes. We'll have a look if we can tell the JSON parser to also accept single quotes in the mean time.

**Comment by erwinvanhunen** [comment]
We just checked the parser but it is not supported, nor will it be supported to allow single quotes around values. The previous engine we used was a bit more flexible there and allowed (in principle invalid) json with single quotes, the newer engine is more strict. So unfortunately there is nothing we can do about it.
