### ISSUE TITLE
[BUG]: `Get-PnPRetentionLabel` is present in `Get-PnPTenantRetentionLabel` docs

### ISSUE THREAD

**Issue by Adam-it** [pnp/powershell#4599]
### Reporting an Issue or Missing Feature

Small glitch in docs.

### Expected behavior 

When I enter docs of [Get-PnPTenantRetentionLabel](https://pnp.github.io/powershell/cmdlets/Get-PnPTenantRetentionLabel.html) I expect to see docs for `Get-PnPTenantRetentionLabel` but I see docs of `Get-PnPRetentionLabel` the same as `Get-PnPRetentionLabel` docs page
![image](https://github.com/user-attachments/assets/6aeec52d-0060-4a48-aef7-30376993592e)

### Actual behavior 

I would expect to see docs for `Get-PnPTenantRetentionLabel`

### Steps to reproduce behavior

Just enter https://pnp.github.io/powershell/cmdlets/Get-PnPTenantRetentionLabel.html and compare with https://pnp.github.io/powershell/cmdlets/Get-PnPRetentionLabel.html
It's the same.

### What is the version of the Cmdlet module you are running?

... it's about the docs

I am willing to fix it up if needed. I need it to fix my script that parses docs to snippets json for the VS Code PnP PowerShell extension.

**Comment by gautamdsheth** [comment]
hey @Adam-it , yeah you are right.
We need to remove `PnPRetentionLabel` docs for this.
As part of the upcoming v3 update, we will be using `PnPTenantRetentionLabel`, its basically a renaming of the old one.

**Comment by Adam-it** [comment]
> hey @Adam-it , yeah you are right. We need to remove `PnPRetentionLabel` docs for this. As part of the upcoming v3 update, we will be using `PnPTenantRetentionLabel`, its basically a renaming of the old one.

ok so:
- [ ] remove `PnPRetentionLabel` docs
- [ ] in `PnPTenantRetentionLabel` rename all `RetentionLabel` to `TenantRetentionLabel` and recheck to align with the command

... have I missed anything?
I may fix it up today  over night if needed

**Comment by gautamdsheth** [comment]
So, 3 things to do:

1) remove `PnPRetentionLabel` docs from `dev` branch
2) remove `PnPRetentionLabel` docs from `gh-pages` branch
2) correct references in the `TenantRetentionLabel` doc in `dev` branch only.

Does that make sense, if not let me know ? Thanks in advance :)

**Comment by Adam-it** [comment]
> So, 3 things to do:
> 
> 1. remove `PnPRetentionLabel` docs from `dev` branch
> 2. remove `PnPRetentionLabel` docs from `gh-pages` branch
> 3. correct references in the `TenantRetentionLabel` doc in `dev` branch only.
> 
> Does that make sense, if not let me know ? Thanks in advance :)

totally. 
please assign me to this one I will go over the needed PRs today over night.

**Comment by Adam-it** [comment]
@gautamdsheth so based on the upgrade guidance 
![image](https://github.com/user-attachments/assets/609999eb-e83c-4042-9062-01241d33be8f)

I think we should have both docs for `RetentionLabel` and `TenantRetentionLabel`. So I did not remove any docs as you suggested but just fixed them up. 
I didn't open any PR since I am not assigned yet to this one so I didn't want to suprise you but you may already double check my fixup in this commit 
https://github.com/pnp/powershell/compare/dev...Adam-it:powershell:4599-fix-retention-label-docs

Let me know if my thinking is correct.
