### ISSUE TITLE
[BUG] Connect-PnPOnline -Credential fails with body must contain client_assertion or client_secret

### ISSUE THREAD

**Issue by azureskydiver** [pnp/powershell#4608]
### Reporting an Issue or Missing Feature
After Sep 2024 when multi-tenant registration for PnP.Powershell was taken away, and we upgraded to PnP version 2.12.0 so that we could pass in the Application ID of our Entra App registration, we've been unable to use the ```-Credential``` parameter with ```Connect-PnPOnline```.

The same Application ID works when using the ```-Interactive``` switch.
The same Application ID works just fine when passing in a certificate when we need it for app-only access.

### Expected behavior 
```Connect-PnPOnline -Credentials``` to succeed like it used to.

### Actual behavior 
I'm getting the following error:
```
Connect-PnPOnline: A configuration issue is preventing authentication - check the error message from the server for details.
You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.
Original exception: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: 9ba92034-70c8-4787-95c0-bf01fab74f00
Correlation ID: e9ea1b71-40b9-495b-817c-b4cd12de230f
Timestamp: 2024-12-03 17:52:15Z
```

### Steps to reproduce behavior
In PowerShell 7, run
```Connect-PnPOnline -Url 'https://<site>.sharepoint.com' -Credentials (Get-Credential) -Verbose -ClientId <client_id>```

### What is the version of the Cmdlet module you are running?
2.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by jackpoz** [comment]
In the authentication tab of your application registration, check what you have in the "Allow public client flows" setting:
![image](https://github.com/user-attachments/assets/5f7d9401-e332-4377-b4bb-3d430629d672)

The -Credentials parameter might require to set this to "Yes".

**Comment by azureskydiver** [comment]
I don't have admin access to Entra at work. I'll try with my personal dev tenant. I'll report back later.

**Comment by jackpoz** [comment]
The most common authentication scenarios are with a certificate and application permissions, or with -Interactive and a MFA-enabled account. These 2 scenarios don't need public flow to be enabled, so that's probably why that documentation doesn't mention it.

I actually realised thanks to you why -DeviceLogin wasn't working anymore,  as that needs public flow too.

I'll see if I can contribute by updating the documentation for both -Credentials and -DeviceLogin .

**Comment by jackpoz** [comment]
Ah nice, good that the default ones have that already. Then I have nothing to do 😄

**Comment by azureskydiver** [comment]
@gautamdsheth :

The problem with the `Register-*` is that we who need to run it do not the permissions to do the registration, and the people who do have the permissions do not had the PnP.PowerShell modules nor want to install the modules on their machines.

I'll put in a pull request for the documentation.
