### ISSUE TITLE
Connect-PnPOnline - On Prem Tranformation

### ISSUE THREAD

**Issue by pkbullock** [pnp/powershell#4609]
When connecting to SharePoint 2013 with latest PnP version (2.12.0)

I am getting 
"Connect-PnPOnline: Specified method is not supported."

Example: 
$sp13Conn = Connect-PnPOnline -Url http://portal2013/en -Credentials OnPrem -ReturnConnection -TransformationOnPrem

![image](https://github.com/user-attachments/assets/a35e7cfd-0484-41c2-8975-48a5486bcb02)

Note: https://github.com/pnp/powershell/blob/572d6973cfd98144cb720df03e5f00e9b4f57178/src/Commands/Base/PnPConnection.cs#L455

Please assign to me :-) I have a test rig back operational to investigate transform issues.

**Comment by pkbullock** [comment]
Reverting to version 2.4.0 allows connect.... oh wait I had my VM pause. Will validate with latest version shortly 🤦‍♂️

**Comment by pkbullock** [comment]
Confirmed, not working in 2.12.0

**Comment by pkbullock** [comment]
![image](https://github.com/user-attachments/assets/7d33342d-76d6-43a1-9d62-ee356bd8e341)
Just for notes

**Comment by jackpoz** [comment]
Question for the maintainers: I'm confused when seeing reports about SP OnPrem whether PnP PowerShell still supports them or not,  as the readme on the homepage states "This version of the cmdlets is cross-platform (i.e it works on Windows, MacOS and Linux) but it will only support SharePoint Online." .

Is the idea to support only certain scenarios, like page transformation, or should every issue related to OnPrem be closed as "not supported" ?
