### ISSUE TITLE
[BUG] -ParentTerm in Get-PnPTerm returns the Parent term not the child of the parent 

### ISSUE THREAD

**Issue by shaunpitt** [pnp/powershell#4610]
Hi there,

I would like to report that -ParentTerm is not working as expected, based on the documentation. My experience is when using the following code:

`Get-PnPTerm -Identity "Expenditure Approval" -TermSet "TermSet1" -TermGroup "TermGroup1" -ParentTerm "Property" -Recursive`

returns the parent term - "Property"

**My term hierarchy is [ TermGroup1 | TermSet1 | Property | Expenditure Approval**

Based on the above TermGroup hierarchy I would have expected "Expenditure Approval" as the result.

Also, without using the " -Recursive " option I get the following error.

Get-PnPTerm: Specified argument was out of the range of valid values.
Parameter name: index

Note: I initially read and posted on this previous issue (now closed) 
https://github.com/pnp/powershell/issues/468

### Expected behavior 
Based on the example command above I was expecting it to return the term "Expenditure Approval"

### Actual behavior 
Instead it returned the term "Property"

### Steps to reproduce behavior
Term store hierarchy:
**My term hierarchy is [ TermGroup1 | TermSet1 | Property | Expenditure Approval**
Code:
`Get-PnPTerm -Identity "Expenditure Approval" -TermSet "TermSet1" -TermGroup "TermGroup1" -ParentTerm "Property" -Recursive`

### What is the version of the Cmdlet module you are running?
I am running the latest version: 2.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [ X ] Windows

**Comment by gautamdsheth** [comment]
hey @shaunpitt , thanks for raising this issue. It has been fixed in the latest nightly builds .
Will be available in the next major version as well whenever it is released.
Closing this.

**Comment by shaunpitt** [comment]
Hi @gautamdsheth awesome! Thank you so much for your help. Appreciate it.
