### ISSUE TITLE
[FEATURE] Add bulk user option to Add-PnPTeamsUser and Remove-PnPTeamsUser

### ISSUE THREAD

**Issue by svermaak** [pnp/powershell#4624]
**Is your feature request related to a problem? Please describe.**
If multiple users are to be added or removed from Team, each user needs to be done individually

**Describe the solution you'd like**
Add bulk user option to Add-PnPTeamsUser and Remove-PnPTeamsUser (as in support string[] on user parameter)

**Describe alternatives you've considered**
Run multiple Add-PnPTeamsUser and Remove-PnPTeamsUser CMDLets, one for each user

**Additional context**
None

**Comment by gautamdsheth** [comment]
Hey @svermaak , `Add-PnPTeamsUser ` already supports this via `-Users` parameter.

Check this:

https://pnp.github.io/powershell/cmdlets/Add-PnPTeamsUser.html#example-3

Will work on `Remove-PnPTeamsUser` to support this.

**Comment by gautamdsheth** [comment]
Hey @svermaak , added support for `-Users` parameter in `Remove-PnPTeamsUser` cmdlet.
Will be available in tomorrow's nightly , thanks for raising this request !

**Comment by svermaak** [comment]
Thank You so much!
