### ISSUE TITLE
[BUG] Missleading results from Get-PnPTenantSite

### ISSUE THREAD

**Issue by timtatam** [pnp/powershell#4638]
### Reporting an Issue or Missing Feature
Bug: Missleading results from Get-PnPTenantSite

### Expected behavior 
Using `Get-PnPTenantSite | Where-Object {$_.OverrideTenantExternalUserExpirationPolicy -eq $true}` to get all sites where the mentioned feature overwrites the tenant default

### Actual behavior 
Getting no sites at all

### Steps to reproduce behavior
```
$tenantSite =Get-PnPTenantSite -Identity https://<tenant>.sharepoint.com/teams/<site>
$tenantSite.OverrideTenantExternalUserExpirationPolicy
```
returns **True**

whereas for the call `Get-PnPTenantSite | Where-Object {$_.OverrideTenantExternalUserExpirationPolicy -eq $true}`
I get **no results**

I believe it is related to the fact that for this property there is 'default data' returned when filtering is used: 
![image](https://github.com/user-attachments/assets/58b07be8-8057-458d-9800-1894e0706504)
https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/get-sposite?view=sharepoint-ps#description

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 2.12.0
PowerShell 7.4.6

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
hi @timtatam , this is a CSOM limitation. It only provides the value for some properties not all. 
For more detailed information, you need to specify `-Identity` parameter , nothing we can change from our side.
