### ISSUE TITLE
[FEATURE] Get-PnPSiteTemplate exports site information using SP Site template JSON schema

### ISSUE THREAD

**Issue by DrEnnui** [pnp/powershell#4639]
Since Add-SPOSiteScript requires the site settings in JSON, it would be nice if Get-PNPSiteTemplate could export the site information in JSON and in the correct schema for immediate use by Add-SPOSiteScript.

**Comment by gautamdsheth** [comment]
hi @DrEnnui , those are two completely different cmdlets. 
The Get-PNPSiteTemplate is to used to with Invoke-PnPSiteTemplate cmdlet.

If you want, to extract the site schema in JSON , you can use `Get-PnPSiteScriptFromWeb` , store the output of it and then use `Add-PnPSiteScript` with that output

**Comment by DrEnnui** [comment]
Thanks!

**Comment by DrEnnui** [comment]
Thanks!  I'll try that out.
