### ISSUE TITLE
[BUG] Add-PnPTeamsUser fails with JSON "EndOfInput" error when using singular -User parameter

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#4654]
### Reporting an Issue or Missing Feature
I am reporting a bug

### Expected behavior
Both `-User` and `-Users` parameters should work interchangeably for the `Add-PnPTeamsUser` cmdlet, successfully adding a user to a Teams team.

### Actual behavior
When using singular `-User` parameter:
```powershell
Add-PnPTeamsUser -Team TeamName -Role Member -User john.doe@contoso.com
```
Fails with error:
```
Add-PnPTeamsUser: An unexpected "EndOfInput" node was found when reading from the JSON reader. A "StartObject" node was expected.
```

![CleanShot 2024-12-26 at 18 17 39](https://github.com/user-attachments/assets/60d15910-460d-474e-95a1-9c81c81465d7)

However, using plural `-Users` parameter works correctly:
```powershell
Add-PnPTeamsUser -Team TeamName -Role Member -Users john.doe@contoso.com
```

### Steps to reproduce behavior
1. Import PnP.PowerShell module
2. Run command with `-User` parameter as shown above
3. Observe JSON parsing error
4. Run same command with `-Users` parameter
5. Verify command executes successfully

### What is the version of the Cmdlet module you are running?
```powershell
ModuleType Version    PreRelease Name           ExportedCommands
----------- -------   ---------- ----           ----------------
Manifest    2.99.85   nightly    PnP.PowerShell {Add-PnPAlert, Add-PnPApp...}
```

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other

**Comment by gautamdsheth** [comment]
hey @YuriySamorodov , awesome finding. Have fixed this issue and it will be available in tomorrow's nightly builds !

Thanks a lot for reporting.
