### ISSUE TITLE
[BUG] New-PnPSite command isn't setting the sensitivity label properly

### ISSUE THREAD

**Issue by prawnz** [pnp/powershell#470]
### Reporting an Issue or Missing Feature
When created a team site using the following powershell, the sensitivity label isn't getting set(i've tried using ID and the Display Name of the sensitivity label)
```
New-PnPSite -Type TeamSite -Title $siteTitle -Alias $groupAlias -SensitivityLabel $sensitivityLabelID
```

### Expected behavior 
Sensitivity label should be set.

### Actual behavior 
Sensitvity label isn't set 

### Steps to reproduce behavior
Update the following powershell with the correct value instead of the placeholder
```
New-PnPSite -Type TeamSite -Title $siteTitle -Alias $groupAlias -SensitivityLabel $sensitivityLabelID
```
### What is the version of the Cmdlet module you are running?
Latest : 1.4.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
How are you using Connect-PnPOnline, as in authenticating to SPO ? 
If you are using app-only context, then this wont work.

Using the username/password flow with delegated permissions will work.
I am using the PnP Management Shell Azure AD app and then connecting using username/password and it works.

**Comment by prawnz** [comment]
I'm connecting using the Azure AD App but using a certificate so it should be the same as yours.

**Comment by astatke** [comment]
> I'm connecting using the Azure AD App but using a certificate so it should be the same as yours.

@prawnz - have you got a workaround for this issue? I am running into a similar problem and I thought I should ask.

**Comment by sharmajitendralal** [comment]
I am still facing the same using certificate

Is this issue not resolved yet?

**Comment by prawnz** [comment]
Check if scripting enabled on your site collection.  It might just be that

**Comment by astatke** [comment]
> > I'm connecting using the Azure AD App but using a certificate so it should be the same as yours.
> 
> @prawnz - have you got a workaround for this issue? I am running into a similar problem and I thought I should ask.

Apologies @prawnz for my late response. In case you still have this issue, this is how I resolved it.

I used this for creating the new SPO site:
New-PnPSite -Type $Type -Title $SiteTitle -Url $SiteURL -Owner $PrincipalOwner

Once the site is created, I used the following to set the sensitivity label of the site. Please remember, depending on your Compliance center (Microsoft Purview) setup, you could have different Sensitivity labels, each identified with a static GUID that you should have captured as hashtable variables before using the  Set-PnPTenantSite cmdlet.

#hashtable to store GoA Sensitivity labels
        $MySensitivityLabelID = @{
            'Public'      = '60c3ebf9-3c2f-4745-a75f-55836bdb736f'
            'Private A' = 'abf2ea38-542c-4b75-bd7d-582ec36a519f'
            'Private B' = '8a86ab16-c33d-4e15-8df8-17dffb73cf6e'
            'Private C' = '6950fef0-80b2-41c0-a6fe-f4610b919434'
        }
        $sensLabel = $MySensitivityLabelID [$sensLabelChosen] 

Set-PnPTenantSite -Identity $newSiteURL -SensitivityLabel $sensLabel -Connection $adminURLConnection
