### ISSUE TITLE
[Issue] Get-PnPFolder : The attempted operation is prohibited because it exceeds the list view threshold

### ISSUE THREAD

**Issue by Shaan0321** [pnp/powershell#479]
1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? 
- No

Reporting an Issue : Get-PnPFolder is not returning values when list contains 5000 or more items.

### Expected behavior 
All items should be return.

### Actual behavior 
Get-PnPFolder : The attempted operation is prohibited because it exceeds the list view threshold.

### Steps to reproduce behavior
If you have any SharePoint list which contain items greater than or equal to 5000. Run following command:
Get-PnPFolder -List 'Documents'

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows 10 Pro

**Comment by veronicageek** [comment]
@Shaan0321 - Can you please try `Get-PnPListItem -List "<YOUR-LIST>" -PageSize 1000 | Where-Object { $_.FileSystemObjectType -eq "Folder"}`.

Note the `-PageSize` which will batch by the number you enter. Worked fine on my 6000 items list.

![image](https://user-images.githubusercontent.com/25181757/112358614-6a516880-8cc8-11eb-83a6-3439323b7552.png)


![image](https://user-images.githubusercontent.com/25181757/112358397-38d89d00-8cc8-11eb-8486-805aeb6c0d35.png)

**Comment by Shaan0321** [comment]
@veronicageek  : Many thanks for your reply. I am able to get values of List Items using PS Command 
(Get-PnPListItem -List 'Documents' -PageSize 1000 | FT  Where-Object { $_.FileSystemObjectType -eq "Folder"}) 
but Get-PnPFolder does not have any such Privilege . Any suggestions here ?

![image](https://user-images.githubusercontent.com/22326131/112363951-57459500-8cd6-11eb-92af-9b971fc327fe.png)

**Comment by veronicageek** [comment]
The cmdlet doesn't have the `-PageSize` parameter. What are you after that the `Get-PnPListItem` would not be suitable for your case instead?

**Comment by Shaan0321** [comment]
@veronicageek : I am not getting Folder Names when using PS Command, Please find screen shots handy :

SharePoint Online Library : 

![image](https://user-images.githubusercontent.com/22326131/112365559-18b0da00-8cd8-11eb-9045-775ff101ba51.png)


PS Output :

![image](https://user-images.githubusercontent.com/22326131/112365451-f9b24800-8cd7-11eb-9ed2-886813bffc05.png)

**Comment by veronicageek** [comment]
Your screenshot above is not filtering for the folders, so it also returns files (ID's 1,2,3, etc..). 
Running the command should give you the folder names:
_Note that the `Format-Table` is the output by default so isn't necessary._

![image](https://user-images.githubusercontent.com/25181757/112383984-bf4fa780-8ce5-11eb-92c5-ee033ff0eab2.png)

**Comment by Shaan0321** [comment]
@veronicageek : Thanks for prompt reply :)

I have used filter also and still 'Title' is returning blank : 

![image](https://user-images.githubusercontent.com/22326131/112434012-526afa80-8d43-11eb-890a-0c3d2b3abf62.png)

Any other parameter I can use here ?

**Comment by veronicageek** [comment]
The following will also work, just choose some other fields if needed:

```powershell
$allFolders = Get-PnPListItem -List "TestLib" -PageSize 1000 | Where-Object { $_.FileSystemObjectType -eq "Folder"}
$results = @()

foreach($folder in $allFolders){
    $results += [pscustomobject]@{
        folderId = $folder.Id
        folderName = $folder["FileLeafRef"]
    }
}
$results
```

I'd also suggest maybe you can try the one-liner on another library, but it does work either way I tried.

**Comment by Shaan0321** [comment]
Tusen Takk  @veronicageek :)

It worked with "FileLeafRef"

Wish you a great day:)

**Comment by RytisDas** [comment]
> @Shaan0321 - Can you please try `Get-PnPListItem -List "<YOUR-LIST>" -PageSize 1000 | Where-Object { $_.FileSystemObjectType -eq "Folder"}`.
> 
> Note the `-PageSize` which will batch by the number you enter. Worked fine on my 6000 items list.
> 
> ![image](https://user-images.githubusercontent.com/25181757/112358614-6a516880-8cc8-11eb-83a6-3439323b7552.png)
> 
> ![image](https://user-images.githubusercontent.com/25181757/112358397-38d89d00-8cc8-11eb-8486-805aeb6c0d35.png)

This returns all the folder. Including subfolder. I would need to get only the root folders. Get-PnPFolderItem does the job, but it does not have -PageSize. Get-PnPListItem does have -PageSize, but I can't find a way to disable the recursion. Maybe you have any suggestion how to overcome this?
