### ISSUE TITLE
Connect-PnPOnline with SPO site only service principle and certificate thumbprint

### ISSUE THREAD

**Issue by NWH-SAmin5** [pnp/powershell#481]
**Is your feature request related to a problem? Please describe.**
I am trying to limit the app permission to site only, instead of providing permission on tenant level SharePoint. Currently Azure AD App permission can only be granted tenant level and not on a particular site.

**Current issue**
SharePoint app-only access gives ability to limit permission to site collection level or even more granular.
**_But_** Connect-PnPOnline connects using legacy authentication which is very limited or probably is on retirement path.

**Describe the solution you'd like**
SharePoint app-only access using Client Id and Certificate authenticate for modern and full feature access

**Solution I have tried**

1. Created SharePoint Online app-only access by following this https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs
2. Provide site collection level permission scope<br/>`<AppPermissionRequests AllowAppOnlyPolicy="true">  
<AppPermissionRequest Scope="http://sharepoint/content/sitecollection" 
Right="FullControl" />
</AppPermissionRequests>`
3. Created self signed certificate
4. As this SharePoint Online apps are only available as Azure Service Principles, using these commands added certificate as credential `Get-AzADServicePrincipal`, `New-AzADSpCredential`
5. Used this command to connect<br/>Example `Connect-PnPOnline -Url "https://contoso.sharepoint.com" -ClientId 6c5c98c7-e05a-4a0f-bcfa-0cfc65aa1f28 -Tenant 'contoso.onmicrosoft.com' -Thumbprint 34CFAA860E5FB8C44335A38A097C1E41EEA206AA`
6. Connection successful
7. Getting 401 unauthorized when try perform requests like `Get-PnPList` etc..
8. Legacy method still works with same app (Client Id and Client Secret authentication)

**Additional context**
Not sure if this is a bug that Connect-PnPOnline needs to get fixed

**Comment by erwinvanhunen** [comment]
Indeed, ACS is regarded as 'legacy' and will not receive much attention from MS.

Unfortunately the scenario you describe will not work. It's indeed a catch-all scenario when using clientid and certificate. e.g. it applies to the whole tenant or not. For that specific reason Microsoft released the Sites.Selected permission (which is app-only scoped). With this permission SharePoint administrators can selectively grant apps access to sites. However, the downside of this approach is that this only works when making calls to the Graph. Any 'classic' calls using CSOM will fail that way. We brought this to the attention of Microsoft, but are still waiting for constructive feedback on this.

**Comment by NWH-SAmin5** [comment]
@erwinvanhunen thank you for that information and for the clarification. Lets see if Microsoft has some news on this.
