### ISSUE TITLE
[BUG] Set-PnPClientSidePage command on 2019 

### ISSUE THREAD

**Issue by amalwayscharan** [pnp/powershell#484]
### Reporting an Issue 
Set-PnPClientSidePage command doesn't seem to work in recent weeks, I used to run this command on my on-premise site all along until the recent update. Get-PnPList command seems to work perfectly fine, so there is an active connection. Not sure what the issue is. 

### Expected behavior 
Connects to specific site and updates the page layout

### Actual behavior 
Set-PnPClientSidePage  command throws  "There is currently no connection yet" error

### Steps to reproduce behavior
Connect-PnPOnline -URL {2019 On-Premise Site}
Set-PnPClientSidePage -Identity 'mySample.aspx' -LayoutType Home

### What is the version of the Cmdlet module you are running?
1.4.0

### Which operating system/environment are you running PnP PowerShell on?
Windows 10

**Comment by erwinvanhunen** [comment]
Hi! PnP PowerShell version 1.4 (actually as of version 1.0) does not support SharePoint On-Premises and we do not test it against any of the SharePoint On-Premises versions. We advise you to use the legacy PowerShell cmdlets for those: https://www.powershellgallery.com/packages/SharePointPnPPowerShell2019/3.29.2101.0
