### ISSUE TITLE
[BUG] Get-PnPSiteSearchQueryResults not returning all sites with the -All switch parameter

### ISSUE THREAD

**Issue by MarekHalfar** [pnp/powershell#492]
### Reporting an Issue or Missing Feature
When using switch ```-All``` with ```Get-PnPSiteSearchQueryResults``` cmdlet it always returns only the first 500 sites.

### Expected behavior 
All sites matching the query should be returned.

### Actual behavior 
Only the first 500 sites are returned like the -All parameter is ignored.

### Steps to reproduce behavior
```
$connection = Connect-PnPOnline -Url $Url -Thumbprint $certThumb -ClientId $appId -Tenant 'contoso.onmicrosoft.com' -ReturnConnection
$allSites = Get-PnPSiteSearchQueryResults -Connection $connection -All

$allSites.count
500
```

### What is the version of the Cmdlet module you are running?
1.4.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
Thank you for reporting this! We found a bug in the cmdlet. The upcoming nightly release (1.4.17-nightly) will include this fix.
