### ISSUE TITLE
[BUG] Add-PnPTeamsTab not returning created tab after successful execution

### ISSUE THREAD

**Issue by achimismaili** [pnp/powershell#499]
### Reporting an Issue 
Command Add-PnPTeamsTab is not returning the created tab as pnp commands usually do.

### Expected behavior 
when assigning the command to a variable, it is expected, that the newly created tab is assigned to this variable, so that e.g. the display name of the new tab can be shown in an output message.

### Actual behavior 
Add-PnPTeamsTab not returning anything after successful execution

### Steps to reproduce behavior

The following snippet does not return the name of the newly created tab.
```
$teamTab = Add-PnPTeamsTab -Team $TeamName -Channel $ChannelName -DisplayName $displayname -Type WebSite -ContentUrl "$absoluteSiteUrl"
Write-Output "Created Teams tab '$($teamTab.DisplayName)'."

```

The following snippet returns the name of the newly created tab.
```
$teamTab = Get-PnPTeamsTab -Team $TeamName -Channel $ChannelName -Identity $displayname
Write-Output "Created Teams tab '$($teamTab.DisplayName)'."

```

### What is the version of the Cmdlet module you are running?
1.4.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Thanks for reporting this issue. 
Has been fixed now, please download the latest nightly releasing tomorrow or wait for 1.5 release which will be happening some time soon :) 
Cheers,
Gautam
