### ISSUE TITLE
[BUG] Set-PnPDefaultColumnValues not applying (termset) when in Azure function after an provisioning list apply

### ISSUE THREAD

**Issue by svermaak** [pnp/powershell#50]
### Reporting an Issue or Missing Feature
Set-PnPDefaultColumnValues not applying (termset) when in Azure function after an provisioning list apply. The same script works in Azure Function runtime ~1 using PNP v3
This might be related to https://github.com/pnp/powershell/issues/42

Yellow is via Set-PnPDefaultColumnValues
Green is manually ivia interface
![image](https://user-images.githubusercontent.com/12259728/101715948-8736a700-3af0-11eb-9709-80869e6bf15a.png)

### Expected behavior 
After Set-PnPDefaultColumnValues new items have the default value specified

### Actual behavior 
No Default value

### Steps to reproduce behavior
Apply template then run
Set-PnPDefaultColumnValues -List "Shared Documents" -Field "theField" -Value "SomeGUID"

### What is the version of the Cmdlet module you are running?
Latest

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ X] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
I tried it here but have no problems with the cmdlet. I do notice that in your example you use the name "Shared Documents" which is the actual folder name of the documents library. You will have to provide the **title** of the document library, e.g. "Documents". Can you try that?

**Comment by svermaak** [comment]
Did you test in Azure function? It works outside of it

Unfortunately still the same with "Documents". When I add item to list the default does not apply. If I run command outside of Azure function for **one** column **both** pops up

![image](https://user-images.githubusercontent.com/12259728/101830879-48086480-3b89-11eb-80af-d3cf7a6f5721.png)

**Comment by erwinvanhunen** [comment]
In the azure function, do you connect exactly the same with Connect-PnPOnline as with running it on your own machine? The code has no dependencies on the environment it's running on (linux, windows, azure functions, azure cloud shell, etc.), but the connection type can affect the functionality.
