### ISSUE TITLE
[BUG] Add-PnPField not returning newly created field, when created with site column object

### ISSUE THREAD

**Issue by achimismaili** [pnp/powershell#501]
### Reporting an Issue
The command Add-PnPFIeld is not returning newly created field, when the field is created in a list with a site column object

### Expected behavior 
when assigning the command to a variable, it is expected, that the newly created field is assigned to this variable, so that e.g. the title of the new tab can be shown in an output message.

### Actual behavior 
Add-PnPField is not returning the newly created field, when created with site column object.
(But it **is** returning the newly created field, when the new field is created in the list and not being based on a site column.)

### Steps to reproduce behavior
`Not working:` The following commands are **not** outputting the title of the new field (, even though it is created.):
```
        $commentColumnObj = Get-PnPField -Identity "_Comments"
        $listCommentColumnObj = Add-PnPField -List "Pictures" -Field $commentColumnObj 
        Write-Output "Field $($listCommentColumnObj.Title) was created."
```

`Working:` The following commands are outputting the title of the new field fine:

```
$locField = Add-PnPField -List "Pictures" -DisplayName "Location" -InternalName "Location" -Type "Location" -AddToDefaultView -AddToAllContentTypes
Write-Output "Field $($locField.Title) was created."
```

### What is the version of the Cmdlet module you are running?
1.4.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Thanks for reporting this issue. 
Has been fixed now, please download the latest nightly releasing tomorrow or wait for 1.5 release which will be happening some time soon :) 
Cheers,
Gautam
