### ISSUE TITLE
Add Quicklinks webpart to page no Thumbnail other than the globe?

### ISSUE THREAD

**Issue by fs366e2spm** [pnp/powershell#503]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting
Issue - when adding a Quicklinks webpart to a page via Add-PnPPageWebPart -Page $page -DefaultWebPartType "QuickLinks" the icon is always the a "Globe". There is no documentation or other trial and error things working to change the itemType oder ThumbnailType.
When a Quicklinks webpart is added it automatically chooses an icone (e.g. DocLib for a documntlibrary, the OneNote icon for a Quicklink to a OneNote notebook. And manually lots of other icons can be selected, but obviously not via PnP Powershell.

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets
Define the thumbnail icons for Quicklinks when adding the web part via PnP PowerShell as a parameter.

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.
See Steps to reproduce behavior, only "Globes" as icons are added, no possibility to define another icon (DocLib, OneNote icon, etc.)

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)
Add-PnPPageWebPart -Page $page -DefaultWebPartType "QuickLinks" -WebPartProperties @{title="QuickLinks 3";items=@(@{sourceItem=@{url="/sites/siteXYZ/Shared%20Documents";itemType=2;fileExtension="";progId=""};title="Documents";thumbnailType=3;id=2};@{sourceItem=@{url="/sites/siteXYZ/SiteAssets/Team%20Site%20Notebook";itemType=2;fileExtension="";progId=""};title="Project Notebook";thumbnailType=3;id=1});hideWebPartWhenEmpty="true"}

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
Version           : 1.4.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Closing this issue , a script for this is available now:

https://pnp.github.io/script-samples/spo-quicklink-wp-creator/README.html?tabs=pnpps

It is already possible, so no need to change anything from the PnP PowerShell side
