### ISSUE TITLE
[BUG] Get-PnPApp Fails with access denied when connected using a SharePoint Addin Principal

### ISSUE THREAD

**Issue by phillipharding** [pnp/powershell#51]
On **Mac OS** I connect to a SharePoint site using a SharePoint Addin principal using the ```-ClientId``` and ```-ClientSecret``` parameters

The Addin principal was granted tenant scoped app-only permissions at the tenant SharePoint Admin centre

When I run the ```Get-PnPApp``` command I get an "Access denied. You do not have permission to perform this action or access this resource" error
![PSCorePnPPowerShellGet-PnPApp](https://user-images.githubusercontent.com/7671418/101844261-ec67b800-3b43-11eb-84f3-486ca3746a17.png)

On **Mac OS** if I connect to the same SharePoint site using the ```-PnPManagementShell``` method, running ```Get-PnPApp``` returns the list of solutions as expected.

On **Mac OS** if I connect to the same SharePoint site using the ```Credentials``` method, running ```Get-PnPApp``` returns the list of solutions as expected.

On **Windows*** if I connect to the same SharePoint site using the Addin ```ClientId``` and ```ClientSecret``` with the ```SharePointPnPPowerShellOnline``` module, running ```Get-PnPApp``` returns the list of solutions as expected.
![WinPnPPowerShellGet-PnPApp](https://user-images.githubusercontent.com/7671418/101844286-fbe70100-3b43-11eb-81eb-0a0bfd9a893d.png)

### Expected behavior 
Connecting to a SharePoint site using a SharePoint Addin principal and running the ```Get-PnPApp` command should return the list of solutions

### Actual behavior 
An access denied error is returned

### Steps to reproduce behavior
Create a SharePoint Addin registration

At the SharePoint Admin site grant the following permissions to the Addin principal
```
<AppPermissionRequests AllowAppOnlyPolicy="true">
  <AppPermissionRequest Scope="http://sharepoint/content/tenant" Right="FullControl"/>
  <AppPermissionRequest Scope="http://sharepoint/content/sitecollection" Right="FullControl"/>
  <AppPermissionRequest Scope="http://sharepoint/search" Right="QueryAsUserIgnoreAppPrincipal"/>
  <AppPermissionRequest Scope="http://sharepoint/social/tenant" Right="FullControl"/>
  <AppPermissionRequest Scope="http://sharepoint/taxonomy" Right="Write"/>
</AppPermissionRequests>
```

Connect to a SharePoint site using the ```ClientId``` and ```ClientSecret``` for the addin registration

Run the ```Get-PnPApp``` command

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 0.3.4

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [X] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
I actually just tried to duplicate what you are doing, and I have no issues at all. It just works for me.

I navigated first to: https://mytenant.sharepoint.com/_layouts/15/appregnew.aspx. Filled in the fields and copied the generated client id and client secret

Then I navigated to https://mytenant-admin.sharepoint.com/_layouts/15/appinv.aspx, entered the client id, clicked 'look up' and pasted the permission list you specified:

```xml
<AppPermissionRequests AllowAppOnlyPolicy="true">
  <AppPermissionRequest Scope="http://sharepoint/content/tenant" Right="FullControl"/>
  <AppPermissionRequest Scope="http://sharepoint/content/sitecollection" Right="FullControl"/>
  <AppPermissionRequest Scope="http://sharepoint/search" Right="QueryAsUserIgnoreAppPrincipal"/>
  <AppPermissionRequest Scope="http://sharepoint/social/tenant" Right="FullControl"/>
  <AppPermissionRequest Scope="http://sharepoint/taxonomy" Right="Write"/>
</AppPermissionRequests>
```

I trusted the app and opened PowerShell on Linux (I have no access to a Mac myself). Entered:
```powershell
Connect-PnPOnline -Url https://mytenant.sharepoint.com -ClientId <myclientid> -ClientSecret <clientsecret>
Get-PnPApp
```

I'm running 0.3.5 (nothing has changed with regards to that functionality between 0.3.4 and 0.3.5)
And results show up as expected...

The code makes no difference between Mac, Linux or Windows when it comes to this type of auth.

**Comment by jackpoz** [comment]
@phillipharding are you running this in a brand new tenant ? In the past months the -ClientSecret authentication has been disabled by default in new tenants, see the "Imporant" part on top of https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs

An alternative way to login is to use a certificate instead of a secret, which can be setup with the [Initialize-PnPPowerShellAuthentication](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/initialize-pnppowershellauthentication?view=sharepoint-ps) commandlet .

A workaround is to re-enable -ClientSecret authentication using ```set-spotenant -DisableCustomAppAuthentication $false``` using latest version of SharePoint Online Management Shell . You can also use ```get-spotenant``` to check the current value of that property.

**Comment by phillipharding** [comment]
@jackpoz @erwinvanhunen 
The tenant is an "old" tenant and using the ```SharePointPnPPowerShellOnline``` module on Windows ```Get-PnPApp``` works as expected using the same ```ClientId/Secret```.

I can connect on MacOS (PowerShell 7.1.0) using the ```ClientId/Secret``` and that works fine, calling say ```Get-PnPWeb``` also works fine, but calling ```Get-PnPApp``` fails with the access denied message.

Using Postman I can get an ```ACS access token``` using the same ```ClientId/Secret```...
![SPGetAccessToken](https://user-images.githubusercontent.com/7671418/101983483-2aafc500-3c73-11eb-97a9-85471543362f.png)

Then if I use Postman to get the list of available apps using this ```access token```, this also works as expected...
![GetInstalledApps](https://user-images.githubusercontent.com/7671418/101983509-4915c080-3c73-11eb-8dc2-9e54a8edb616.png)

**Comment by veronicageek** [comment]
@phillipharding @erwinvanhunen - I do have the same error when testing on MacOS indeed ("old" tenant) - PnP version 0.3.6

![Get-PnPAppErrorMacOS](https://user-images.githubusercontent.com/25181757/101992235-a3ca0f00-3ca9-11eb-9705-b8509d9269d3.png)

**Comment by erwinvanhunen** [comment]
That is very fascinating. I right now have no clue, but I'll dive into it, why it is failing on Mac, but not on Windows or Linux. Especially given it's the same code.

**Comment by erwinvanhunen** [comment]
@veronicageek : do you have a way to monitor outgoing traffic on your computer? Something alike Fiddler for Windows? If so, if you execute Get-PnPApp is the access token included in the request? Also, given you have access to a windows machine or VM, can you install the new PnP PowerShell module on that machine and there it there with Get-PnPApp? I'm trying to figure out where exactly the issue lies on your end.

**Comment by veronicageek** [comment]
@erwinvanhunen - There's apparently _[Fiddler Everywhere](https://www.telerik.com/fiddler)_ for MacOS, Linux & Windows, so I'll dig more into those 2 tests.

**Comment by veronicageek** [comment]
I don't have anything coming out of _Fiddler Everywhere_, but surprisingly, I **don't** have the error anymore on MacOS 🤔  @phillipharding can you please test on your side?

When doing the testing on Windows though, I had the issue (altho not tested yesterday, and nothing coming through Fiddler on my side)...

**Comment by phillipharding** [comment]
@erwinvanhunen @veronicageek 
So I've used [Proxyman](https://proxyman.io/) to trace network calls and _think_ I've found the cause

**```Connect-PnPOnline```** shows a call to ```https://accounts.accesscontrol.windows.net/<tenantid>/tokens/OAuth/2``` which returns the ```ACS access token```

Also is a call to ```https://tenant.sharepoint.com/sites/sitename/_vti_bin/client.svc/ProcessQuery```, the ```ACS access token``` is attached to the header, the ```X-ClientService-ClientTag``` header value is ```PnPCore:0.1:``` and the body is
```
<?xml version="1.0"?>
<Request xmlns="http://schemas.microsoft.com/sharepoint/clientquery/2009" AddExpandoFieldTypeSuffix="true" SchemaVersion="15.0.0.0" LibraryVersion="16.0.0.0" ApplicationName=".NET Library">
    <Actions>
        <ObjectPath Id="2" ObjectPathId="1"></ObjectPath>
    </Actions>
    <ObjectPaths>
        <Constructor Id="1" TypeId="{268004ae-ef6b-4e9b-8425-127220d84719}"></Constructor>
    </ObjectPaths>
</Request>
```
Which results in
```
[
  {
    "SchemaVersion": "15.0.0.0",
    "LibraryVersion": "16.0.20802.12003",
    "ErrorInfo": {
      "ErrorMessage": "Current site is not a tenant administration site.",
      "ErrorValue": null,
      "TraceCorrelationId": "010f979f-c000-2000-7512-db877c93c3c1",
      "ErrorCode": -1,
      "ErrorTypeName": "Microsoft.Online.SharePoint.Common.SpoException"
    },
    "TraceCorrelationId": "010f979f-c000-2000-7512-db877c93c3c1"
  }
]
```
Executing **```Get-PnPWeb```** results in a call to ```https://tenant.sharepoint.com/sites/sitename/_vti_bin/client.svc/ProcessQuery```, the ```ACS access token``` is attached to the header, the ```X-ClientService-ClientTag``` header value is ```PnPPS:0.3:Get-PnPWeb```  and the body is
```
<?xml version="1.0"?>
<Request xmlns="http://schemas.microsoft.com/sharepoint/clientquery/2009" AddExpandoFieldTypeSuffix="true" SchemaVersion="15.0.0.0" LibraryVersion="16.0.0.0" ApplicationName="SharePoint PnP PowerShell Library">
    <Actions>
        <ObjectPath Id="2" ObjectPathId="1"></ObjectPath>
        <ObjectPath Id="4" ObjectPathId="3"></ObjectPath>
        <Query Id="5" ObjectPathId="3">
            <Query SelectAllProperties="false">
                <Properties>
                    <Property Name="Id" ScalarProperty="true"></Property>
                    <Property Name="Url" ScalarProperty="true"></Property>
                    <Property Name="Title" ScalarProperty="true"></Property>
                    <Property Name="ServerRelativeUrl" ScalarProperty="true"></Property>
                </Properties>
            </Query>
        </Query>
    </Actions>
    <ObjectPaths>
        <StaticProperty Id="1" TypeId="{3747adcd-a3c3-41b9-bfab-4a64dd2f1e0a}" Name="Current"></StaticProperty>
        <Property Id="3" ParentId="1" Name="Web"></Property>
    </ObjectPaths>
</Request>
```
And the result is
```
[
  {
    "SchemaVersion": "15.0.0.0",
    "LibraryVersion": "16.0.20802.12003",
    "ErrorInfo": null,
    "TraceCorrelationId": "150f979f-50e1-2000-7512-dc71d67769db"
  },
  2,
  {
    "IsNull": false
  },
  4,
  {
    "IsNull": false
  },
  5,
  {
    "_ObjectType_": "SP.Web",
    "_ObjectIdentity_": "150f979f-50e1-2000-7512-dc71d67769db|740c6a0b-85e2-48a0-a494-e0f1759d4aa7:site:334e5ee2-08ac-469b-a10b-d2893d51494a:web:9fe89123-d343-45e0-a7c6-66e211a1c4f7",
    "Id": "/Guid(9fe89123-d343-45e0-a7c6-66e211a1c4f7)/",
    "Url": "https://platinumdogsconsulting.sharepoint.com/sites/eelhrportaldev",
    "Title": "Personnel Administration Site (SCUD)",
    "ServerRelativeUrl": "/sites/eelhrportaldev"
  }
]
```
Then executing the call to **```Get-PnPApp```** shows a call to ```https://tenant.sharepoint.com/sites/sitename/_api/contextinfo```, this time the ```ACS access token``` is not attached to the header, there is no ```X-ClientService-ClientTag``` header and the result is a ```403``` access denied message
```
{
  "error": {
    "code": "-2147024891, System.UnauthorizedAccessException",
    "message": {
      "lang": "en-US",
      "value": "Access denied. You do not have permission to perform this action or access this resource."
    }
  }
}
```

**Comment by erwinvanhunen** [comment]
This helps much. I will see what's happening internally.

**Comment by erwinvanhunen** [comment]
What makes it complex to debug though is that I have two people within the PnP Team with a Mac to test this: one fails, the other succeeds... same build of PnP PowerShell...

**Comment by phillipharding** [comment]
Thanks for your help @erwinvanhunen & @veronicageek this type of issue is always tricky to track down 🙂

I'll try and spin up a windows VM with PSCore to try and replicate there, if you can point me in the right direction code-files wise happy to look around there too

**Comment by erwinvanhunen** [comment]
So, the logic is as follows:

When you issue a connect-pnponline to login with **ACS** clientid/clientsecret we request from the AuthenticationManager in the PnP.Framework a clientcontext with a valid bearer token. That token is used in every subsequent CSOM request by overriding the ExecutingWebRequest event and adding the token to the header collection. This works for you as you see requests going over the wire to the ProcessQuery endpoint (that's the CSOM endpoint) with the correct bearer token added. However, the AppManager in the PnP.Framework (which is used behind Get-PnPApp) has to use REST, so we have to acquire the accesstoken separately.

For that to work we first check how the original authentication is done. If it's using OAuth, we acquire the token from the MSAL cache. If not we we are temporarily adding an additional ExecutingWebRequest handler to the client context you're using. We then issue a non-modifying CSOM request, and get the Authentication header from the request. We then remove the newly added event handler from the client context as we don't need it anymore. That access token is returned to the AppManager and added to every request made by it.

This all works flawless on my end... in both Windows and Linux...

However, we I did a relatively heavy refactoring of the AccessToken acquisition part in the PnP.Framework today for another issue, so it would be great if you could give it a try with the nightly build of PnP PowerShell that is available tomorrow (0.3.8)

**Comment by phillipharding** [comment]
Sure will, I'll report back once I've tested

**Comment by phillipharding** [comment]
Massive thanks @erwinvanhunen @veronicageek 

Whatever you changed seems to have worked, tested this morning with 0.3.8 and ```Get-PnPApp``` worked as expected
