### ISSUE TITLE
[BUG] New-PnPMicrosoft365Group Issue

### ISSUE THREAD

**Issue by BaronSparky** [pnp/powershell#516]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
When using New-PnPMicrosoft365Group, a new Microsoft 365 Group is created without error.

### Actual behavior 
When using the `New-PnPMicrosoft365Group` command, without the "`-CreateTeam`" switch, the following is displayed to screen although the group is created correctly:

> PS C:\Temp> New-PnPMicrosoft365Group -DisplayName "A New Group 03" -Description "This is the description" -MailNickname "AA003" -Owners "admin@someTenant.onmicrosoft.com" -IsPrivate -Force 
> New-PnPMicrosoft365Group : Unable to provision resource.
> At line:1 char:1
> + New-PnPMicrosoft365Group -DisplayName "A New Group 03" -Description " ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (:) [New-PnPMicrosoft365Group], PSInvalidOperationException
>     + FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.Microsoft365Groups.NewPnPMicrosoft365Group
>  
> 
> PS C:\Temp> get-pnpexception
> 
> 
> Message          : Unable to provision resource.
> Stacktrace       :    at PnP.PowerShell.Commands.Base.BasePSCmdlet.ProcessRecord()
>                       at System.Management.Automation.CommandProcessor.ProcessRecord()
> ScriptLineNumber : 1

If you use the same command and add the "`-CreateTeam`" switch, then both the Group and the Team area created correctly with no issues being logged to screen.

### Steps to reproduce behavior
Create a new Group without the "`-CreateTeam`" switch.
`New-PnPMicrosoft365Group -DisplayName "A New Group 03" -Description "This is the description" -MailNickname "AA003" -Owners "admin@someTenant.onmicrosoft.com" -IsPrivate -Force`

### What is the version of the Cmdlet module you are running?
1.4.20

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
Indeed, I can reproduce the issue. The group is created, but the error `New-PnPMicrosoft365Group: Unable to provision resource.` is showing.

FYI - @erwinvanhunen @gautamdsheth

**Comment by gautamdsheth** [comment]
Thanks for reporting this issue. 
Has been fixed now, please download the latest nightly releasing tomorrow or wait for 1.5 release which will be happening some time soon :) 
Cheers,
Gautam

**Comment by BaronSparky** [comment]
Great, thanks Gautam.  Works a charm.
