### ISSUE TITLE
[BUG]Add-PnPDataRowsToSiteTemplate exception when Web object has not been loaded in the session.

### ISSUE THREAD

**Issue by willholland** [pnp/powershell#518]
### Reporting an Issue or Missing Feature
Using the `Add-PnPDataRowToSiteTemplate` cmdlet on list that contains a non-standard People field (not the *Created By* or *Modified By* fields) results in an error if the "Web" object is not loaded.

### Expected behavior 
Data rows are added to the Site template for the specified list without error.

### Actual behavior 
The following error is thrown and data rows are not added to the site template.

```powershell
The property or field 'Id' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.
    at Microsoft.SharePoint.Client.ClientObject.CheckUninitializedProperty(String propName)
    at Microsoft.SharePoint.Client.Web.get_Id()
    at PnP.PowerShell.Commands.Provisioning.Site.AddDataRowsToSiteTemplate.GetLoginName(Web web, Int32 userId)
    at PnP.PowerShell.Commands.Provisioning.Site.AddDataRowsToSiteTemplate.GetFieldValueAsText(Web web, ListItem listItem, Field field)
    at PnP.PowerShell.Commands.Provisioning.Site.AddDataRowsToSiteTemplate.ExecuteCmdlet()
    at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()
```

### Steps to reproduce behavior
- Create a new "Employee Onboarding" list.
- Add a single list item, filling out only the required **Work** field and the **Mentor** field. 
- Open a new PowerShell instance (**IMPORTANT**)
- Execute the below cmdlets

```powershell
Connect-PnPOnline -Url "<Your Site Url>" -Interactive

Get-PnPSiteTemplate -Out List.xml -ListsToExtract "Employee onboarding" -Handlers Lists

Add-PnPDataRowsToSiteTemplate -Path ListsOnly.xml -List "Employee onboarding"
```

If you then invoke the `Get-PnPWeb` cmdlet and rerun the `Add-PnPDataRowsToSiteTemplate` cmdlet, it will work and data rows are added.

### What is the version of the Cmdlet module you are running?
v1.4.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Hmm, looks like a bug. Will take a look , however to as temporary workaround, you can maybe try it as and check ?

`Add-PnPDataRowsToSiteTemplate -Path ListsOnly.xml -List "Employee onboarding" -TokenizeUrls`

**Comment by gautamdsheth** [comment]
Thanks for reporting this issue. 
Has been fixed now, please download the latest nightly releasing tomorrow or wait for 1.5 release which will be happening some time soon :) 
Cheers,
Gautam
