### ISSUE TITLE
Add-PnPPage: Does not create site page (URL) with spaces[BUG]

### ISSUE THREAD

**Issue by AJD8** [pnp/powershell#519]
### Reporting an Issue or Missing Feature
I thought my issue would have been addressed via this reported Bug: https://github.com/pnp/pnpcore/issues/339, but it does not appear to be.

I am using PnP.PowerShell v1.4 and it appears I am no longer able to create a site page with a name/URL that includes spaces.  The desired result is a site page name and URL with spaces

### Expected behavior 
The page is created with spaces and is usable/accessible.

### Actual behavior 
What will happen is the site page will be created with a URL such as test-page or test+page. Due to the addition of the '-' or '+' the set page will fail as the company name no longer matches.

Here is a real world example:
![image](https://user-images.githubusercontent.com/81631053/113146863-2dbcca00-91fe-11eb-8542-741650f1d208.png)

If I try and force a space by adding '%20' I get "Object reference not set to an instance of an object." error for created page.

### Steps to reproduce behavior

Example:
$CompanyName = 'test page'
Add-PnPPage -Name $CompanyName -CommentsEnabled:$false
Set-PnPPage -Identity $CompanyName -HeaderType None

### What is the version of the Cmdlet module you are running?
I have updated to v1.4, but my machine is showing v1.4 and v1.3
![image](https://user-images.githubusercontent.com/81631053/113147578-e5ea7280-91fe-11eb-8598-f4ca6ffd8c20.png)

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by AJD8** [comment]
Thanks Veronica.  How can I access v1.4.20?  Running a module update only gets me to the 1.4 release

**Comment by ToddKlindt** [comment]
> Thanks Veronica. How can I access v1.4.20? Running a module update only gets me to the 1.4 release

Try this, `Update-Module pnp.powershell -AllowPrerelease`

**Comment by AJD8** [comment]
And if I get the latest version and the issue persists, could it be an issue with our tenant?

**Comment by AJD8** [comment]
This can be closed.  I have verified that the insertion of '-' instead of a space appears to be coming from our tenant/site collection.  I'll need to contact MS.  Many thanks for the responses.
