### ISSUE TITLE
New-PnPSite fails with "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by pankajsurti** [pnp/powershell#525]
### Reporting an Issue or Missing Feature

New-PnPSite is not working as expected. It does work for creating the Modern Communication site but not for Team Site.

### Expected behavior 
The Modern Team site should be created.

### Actual behavior 

See an error "Object reference not set to an instance of an object." instead of the Modern Team site getting created.

### Steps to reproduce the behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)
https://gist.githubusercontent.com/pankajsurti/1465f8df0a5cc7d34df0d79c247eb297/raw/9b2f7c76fa890ffaa8886c5650148a7b8dfdcdda/CreateModernTeamSite.PS1 
### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
1.4.0                 PnP.PowerShell 
### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@pankajsurti - I have no issue on my side with just normal credentials. Can you please try?
Then we can pinpoint if this is coming from the way you authenticate with your script. Thanks

**Comment by pankajsurti** [comment]
I have created headless App ID and Secret on the SPO tenant using this method. https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs

**Comment by gautamdsheth** [comment]
@pankajsurti - This authentication method is not supported for modern Team sites. 
As @veronicageek suggested, please use normal Global admin credentials or AppId + certificate to create team sites.

**Comment by ee61re** [comment]
I've just seen the same error, using a script that worked fine 1 week ago - on the same environment.

I was logging in using -UseWebLogin, but I just changed it to use -Interactive - and the script now works fine again.

The relevant lines in my script are:

Connect-PnPOnline -Url $SPOAdminUrl -Interactive

New-PnPSite -Type TeamSite -Title $Site.Name -Alias $Site.alias -IsPublic

**Comment by lampi84** [comment]
I reverted back to PnP.Powershell version 1.2  . After this Get-PnPSiteTemplate works fine even when using -UseWebLogin as login parameter. I don't see the point why global admin is needed to create a site collection template. Within my organizantion (which is quite large), I'll not get a global admin account to perform this action.
Any other idea what i can do instead of downgrading to version 1.2?
