### ISSUE TITLE
Export-PnPTaxonomy extra option needed:  -IncludeDeprecated [FEATURE]

### ISSUE THREAD

**Issue by prossum** [pnp/powershell#532]
**Is your feature request related to a problem? Please describe.**
While using Export-PnPTaxonomy I get also the deprecated terms. I like to filter on this property.

**Describe the solution you'd like**
Export-PnPTaxonomy -TermSetId <Guid> -Path <outputfile> -IncludeDeprecated $false

**Describe alternatives you've considered**
The available alternative is to download the whole TermGroup as XML and do the selection myself.

**Additional context**
n/a

**Comment by sankarkumar23** [comment]
I've created a PR for this feature. Please review.

**Comment by markgort86** [comment]
@sankarkumar23 you need to make a Pull Request to the main branch to provide this code to the PnP PowerShell repository. It looks like you only pushed it to you're own branch. Could you have a look on this?

See also: https://pnp.github.io/powershell/articles/gettingstartedcontributing.html#submitting-your-changes-for-review

**Comment by sankarkumar23** [comment]
Thanks for reaching out. I've very limited knowledge on GitHub and did not know process.
I created a new PR now.. here is my link https://github.com/pnp/powershell/pull/4053. Appreciate if you can guide me with next steps.

**Comment by markgort86** [comment]
You're PR is now visible for the repo owners to provide feedback on this. 

Let's see if this can be merged.. or that you need to provide some changes on the code or description.

**Comment by gautamdsheth** [comment]
Closing this as it has now been merged. It is available in the latest nightly builds as well as the next major version
