### ISSUE TITLE
Add-PnPFile fails when content-type switch is provided

### ISSUE THREAD

**Issue by Tinathnath** [pnp/powershell#533]
Hi PnP !

I'm facing an issue when trying to upload a file to a SharePoint library using `Add-PnPFile`.
According to the docs I'm able to do this:
```powershell
Add-PnPFile -Path "C:\Users\me\documents\file.docx" -Folder "My Library" -ContentType "My awesome CT" -Values @{customFieldName="value"} 
```
It fails with this error: 

> Add-PnPFile: The folder specified does not have a corresponding list

Same error when uploading with the server relative path to the folder, like:
```powershell
Add-PnPFile -Path "C:\Users\me\documents\file.docx" -Folder "/sites/myAwesomeSite/My Library" -ContentType "My awesome CT" -Values @{customFieldName="value"}
```

However, this works like a charm:
```powershell
Add-PnPFile -Path "C:\Users\me\documents\file.docx" -Folder "My Library" -Values @{customFieldName="value"; ContentTypeId="0x0101..."} 
```

**Environment:**
- SharePoint Online
- Team site collection (Office 365 group site created via Teams)
- Connected using legacy Add-In ClientId/Secret (company won't grant me AAD app access)

Great job with this by the way, saves us a ton of time :)

**Comment by gautamdsheth** [comment]
@Tinathnath  - thanks for flagging this issue. It has been fixed. Will be available in the nightly tomorrow and in the next major release.
