### ISSUE TITLE
[BUG] Connect-PnPOnline -CurrentCredentials Fails

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#534]
### Reporting an Issue or Missing Feature
I am  reporting a bug

### Expected behavior 
`Connect-PnPOnline -Url <some_url> -CurrentCredentials` should connect to SharePoint Online
### Actual behavior 
```
Connect-PnPOnline -Url <some_url> -CurrentCredentials
Connect-PnPOnline: Object reference not set to an instance of an object.
```
### Steps to reproduce behavior
```
$url = 'https://somesite-admin.sharepoint.com'
Connect-PnPOnline -Url $url -CurrentCredentials
```

### What is the version of the Cmdlet module you are running?
```
Name    : PnP.PowerShell
Version : 1.5.0
```

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
Hi @YuriySamorodov,
The `-CurrentCredentials` parameter is only valid when used with `-TransformationOnPrem`. I'll make the documentation clearer.

**Comment by YuriySamorodov** [comment]
Thanks @veronicageek! Probably it would be beneficial to add another parameter `-Location` with the accepted values `Online` and `OnPremises` and create more parameter groups to separate Online and OnPrem parameters and make `Connect-PnPOnline` usage more straightforward and clear?

**Comment by veronicageek** [comment]
@YuriySamorodov - This module only intends to support SharePoint Online. Although this particular case/cmdlet may support SharePoint on-prem, there's no intent in going further. Making it clearer in the documentation is problably faster 🙂

**Comment by YuriySamorodov** [comment]
Thanks @veronicageek. Feel free to review my PR https://github.com/pnp/powershell/pull/539
