### ISSUE TITLE
Issue with Add-PnPGroupMember that works for O365/M365 groups but not for security groups apparently?[BUG]

### ISSUE THREAD

**Issue by mvanders** [pnp/powershell#538]
### Reporting an Issue or Missing Feature
When trying to execute the following, I got no error, but nothing gets added either:
Add-PnPGroupMember -Group "EG-TF-NCAP_P Visitors" -EmailAddress "_STAFF_EXTERNAL@acea.be"

It works for O365/M365 groups but not for security groups apparently?

### Expected behavior 
That it adds the email address for both O365/M365 groups and for Security Groups

### Actual behavior 
It works for O365/M365 groups but not for security groups apparently?

### Steps to reproduce behavior
Add-PnPGroupMember -Group "EG-TF-NCAP_P Visitors" -EmailAddress "_STAFF_EXTERNAL@acea.be"
Where _STAFF_EXTERNAL@acea.be is a Security Group.

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.4.19     PnP.PowerShell                      {Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add-PnPClientSideText, Add-PnPClientSideWebPart...}
Manifest   1.4.0      PnP.PowerShell                      {Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add-PnPClientSideText, Add-PnPClientSideWebPart...}
Manifest   1.3.0      PnP.PowerShell                      {Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add-PnPClientSideText, Add-PnPClientSideWebPart...}
Manifest   1.2.0      PnP.PowerShell                      {Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add-PnPClientSideText, Add-PnPClientSideWebPart...}

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@mvanders - I have no issue on my side with a mail-enabled security group - I'm currently using v1.4.20 (although we've got v1.5 released). Can you please update your module and feedback.

![image](https://user-images.githubusercontent.com/25181757/113333668-a022cc80-931a-11eb-87a1-0268d369f221.png)

**Comment by YuriySamorodov** [comment]
@mvanders, you may also want to try `-LoginName` as well. It works for like a charm. ( I am on 1.5.0 though)

**Comment by mvanders** [comment]
@YuriySamorodov Tried, but failed...
![image](https://user-images.githubusercontent.com/758617/113433061-c873ff00-93de-11eb-9725-274fa91f255c.png)

**Comment by veronicageek** [comment]
@mvanders - Still no issue on my end even when I use the `-LoginName` parameter. 
I can only reproduce your issue above if (like the message says) the group doesn't exist.

![image](https://user-images.githubusercontent.com/25181757/113437319-53a0c500-93de-11eb-9ac6-9fe2e969b514.png)

I'd suggest you check the following:
- Make sure the group exists (for example, you can run `Get-PnPAzureADGroup | Where-Object {$_.SecurityEnabled -eq "true" -and $_.DisplayName -eq "YOUR-DISPLAY-NAME-HERE"}`)

- Try adding this group to another test site
- Try adding another (similar) group to your target site

**Comment by mvanders** [comment]
I updated my PnP.PowerShell and suddenly it all works... :-)

**Comment by mvanders** [comment]
That was TOO quick. Now I tried to remove a M365 group and I get this:
![image](https://user-images.githubusercontent.com/758617/113473486-108c3380-946a-11eb-85e4-4806f8826432.png)

**Comment by veronicageek** [comment]
Then if the "add" command is working, we can close this issue and open another one for the `Remove-PnPGroupMember`.

**However**, please do the minimum of troubleshooting mentioned above before opening the issue, because I don't see a problem with the `Remove-PnPGroupMember`.

![image](https://user-images.githubusercontent.com/25181757/113476966-be054400-9476-11eb-9c56-97b9e1fa3dc6.png)
