### ISSUE TITLE
[BUG] I can't use Connect-PnPOnline PowerShell 7.0

### ISSUE THREAD

**Issue by renatoromao** [pnp/powershell#54]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. I'm using **Connect-PnPOnline -Url <mysitecollection>**
Connect-PnPOnline: The remote server returned an error: (400) Bad Request.

2. PowerShell Version 7.0.0
3. If I use **Connect-PnPOnline -Url ... -ClientId ... -ClientSecret ... ** I got the error below:
Connect-PnPOnline: The type initializer for 'OfficeDevPnP.Core.Utilities.TokenHelper' threw an exception.

### What is the version of the Cmdlet module you are running?
I already installed the PnP.PowerShell module, but I can't see the version, when I run 
Get-Module -Name "PnP.PowerShell" -ListAvailable
I cannot see anything

### Which operating system/environment are you running PnP PowerShell on?
- [ X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ X ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
The error message indicates that PowerShell is loading the wrong version (e.g. its still using the old version of PnP PowerShell for PowerShell 5. I see that because of the namespace OfficeDevPnP.Core.Utilities being used which has been renamed to PnPFramework.Utilities in the new version). Please uninstall the old version first:

```powershell
Uninstall-Module -Name SharePointPnPPowerShellOnline -AllVersions -Force
```

Then please try again.

**Comment by renatoromao** [comment]
Hi @erwinvanhunen 

Now I can install and see the version inside the Windows PowerShell but can't see inside the PowerShell 7 (7.0.0).
When I ran the Connect command, I don't get any issues on PS 7 or PS Windows.

But when I ran the Get-PnPListItem, I got this error inside the PS 7.
_Get-PnPListItem: The remote server returned an error: (400) Bad Request._

**Comment by veronicageek** [comment]
@renatoromao - Can you run ```Get-Module PnP.PowerShell -ListAvailable | Select-Object Name,Version | Sort-Object Version -Descending``` on PS7 

Also, can you post an extract or screenshot of the script you're trying run with the error. Thanks

**Comment by renatoromao** [comment]
@veronicageek  / @erwinvanhunen 

I deleted everything here and install again, now I can run locally.
I'm able to test locally but not able to run in my Azure Function with PS7 and ~v3.

The error is:
$conn = Connect-PnPOnline -Url <mysite> -Credentials <mycredentials> -ReturnConnection;

_OUTPUT: [ERROR]: Cannot index into a null array._

**Comment by erwinvanhunen** [comment]
That seems probably related to an issue with one of the variables your providing.  I assume you're providing the credentials as a variable? That's more an issue with your script and not necessarily with PnP PowerShell.

**Comment by Scayn** [comment]
It still seems to be an issue with Connect-PnPOnline on PowerShell 7+ (Tested on PowerShell 7.2 and 7.3).
PowerShell 5.1 seems to work fine.

Only way that Connect-PnPOnline works on 7+ is to add -UseWebLogin. However I will then be unable to process any other PnP commands. I.e. Add-PnPFile.
It has all been tested on both 5.1 and 7.2 and 7.3.

Works:
[X] PowerShell 5.1
[  ] PowerShell 7.2
[  ] PowerShell 7.3
