### ISSUE TITLE
Get-PnPRecycleBinItem DeletedBy has no data

### ISSUE THREAD

**Issue by crshovrd41** [pnp/powershell#541]
It appears that this command is supposed to return data on what user deleted the file. It appears the field is enumerated with the type  Microsoft.SharePoint.Client.User, but when you dig in to it, there is no data there. 

Using Select-Object -ExpandProperty DeletedBy returns blank results. Using (Get-PnPRecycleBinItem -RowLimit 10 | Select-Object DeletedBy).UserId or any other property returns blank results. The GUI has the proper information.

Seems as though this is a bug.

**Comment by veronicageek** [comment]
@crshovrd41 - Indeed, some CSOM objects are not returned, but unfortunately this is not an easy fix. This might change in the future, but for now please try the below:

```powershell
$allDeletedItems = Get-PnPRecycleBinItem
$results = @()

foreach($item in $allDeletedItems){
    $userID = (Get-PnPAzureADUser | Where-Object {$_.DisplayName -match $item.DeletedByName}).Id
    
    $results += [pscustomobject]@{
        fileName = $item.LeafName
        deletedBy = $item.DeletedByName
        deletedDate = $item.DeletedDate
        userID = $userID
    }
}
$results
```

![image](https://user-images.githubusercontent.com/25181757/113412735-f4788b80-93b0-11eb-9003-a0d82aa260f7.png)

**Comment by crshovrd41** [comment]
Thank you!
