### ISSUE TITLE
[BUG] Add-PnPSiteCollectionAdmin Access Is Denied

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#542]
### Reporting an Issue or Missing Feature
I am reporting a bug

### Expected behavior 
`Add-PnPSiteCollectionAdmin -Owner user@contoso.com` should add collection site admin even if the SharePoint Administrator credentials you are connecting with does not have explicit access on the site.

### Actual behavior 

if I connect with PnP Management Shell app to the site I don't have explicit permission on and then run `Add-PnPSiteCollectionAdmin -Owners Admins` it would thrown an error:
`Add-PnPSiteCollectionAdmin: Access denied. You do not have permission to perform this action or access this resource`

However, if I connect with my own app and then run the same command, it will not error out.
Pretty much the same way I can add site collection admin via SharePoint Admin Portal on the web

### Steps to reproduce behavior
```
$creds = Get-Credential
$url = 'https://contoso.sharepoint.com/sites/test-site'
$connection = Connect-PnPOnline -Url $url -Credentials $creds
Add-PnPSiteCollectionAdmin -Owners SPS.Admins -Connection $connection
```

### What is the version of the Cmdlet module you are running?
```
Name    : PnP.PowerShell
Version : 1.5.0
```

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by ToddKlindt** [comment]
The PnP Management Shell app uses delegation, so if the user you connect with doesn't have permission to change a connect to a site or change its admin then the PnP won't either. Is your app using delegation as well? 
Add-PnPSiteCollectionAdmin should _not_ work if the user you connect with does not have permission to the site.

**Comment by YuriySamorodov** [comment]
Thanks @ToddKlindt! That's a good catch. My app has been assigned with "Have full control of all site collections" **application** permission. That makes perfect sense now, thank you!
It appeared I misread instructions from the article below and used wrong cmdlet
https://github.com/pnp/powershell/blob/dev/documentation/Add-PnPSiteCollectionAdmin.md where it says in Description:
Set-PnPTenantSite -Owners if you are not an Admin for the site but have the SharePoint admin role.
I was under impression `Add-PnPSiteCollectionAdmin` would behave pretty much the same way as SharePoint Online Admin Center where an admin can manage site collection admins without need being assigned permissions on the site itself.
