### ISSUE TITLE
[BUG] Set-PnPTenantSite -Owners: The user does not exist or is not unique.

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#544]
### Reporting an Issue or Missing Feature
I am reporting a bug

### Expected behavior 
`Set-PnPTenantSite -Owners groupname@contoso.com -Identity https://contoso.sharepoint.com/sites/somesite` should add groups as a site collection administrators on the site per the documentation:
https://github.com/pnp/powershell/blob/dev/documentation/Set-PnPTenantSite.md#-owners
> Specifies owner(s) to add as site collection administrators. They will be added as additional site collection administrators. Existing administrators will stay. Can be both users and **groups**

### Actual behavior 
`Set-PnPTenantSite -Owners groupname@contoso.com -Identity https://contoso.sharepoint.com/sites/somesite` throws an error:
`Set-PnPTenantSite: The user does not exist or is not unique.` despite a group can be located via `Get-PnPAzureADGroup`
Works well if I try to add a user as a site collection admin.

### Steps to reproduce behavior
```
Connect-PnPOnlineSite -Identity https://contoso-admin.sharepoint.com -Credentials (Get-Credential)
Set-PnPTenantSite -Owners groupname@contoso.com -Identity https://contoso.sharepoint.com/site/somesite
```

### What is the version of the Cmdlet module you are running?
```
Name    : PnP.PowerShell
Version : 1.5.0
```
### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
Indeed, I can reproduce this error on v1.5.0
@gautamdsheth - Running `Set-PnPTenantSite` will add _users_ as additional admins correctly, but not groups (although it works fine in the UI)

**Comment by gautamdsheth** [comment]
Closing this as it is fixed now.
