### ISSUE TITLE
[BUG] Add-PnPFile message too big error message missing

### ISSUE THREAD

**Issue by peterruzicska** [pnp/powershell#55]
### Notice
Add-PnPFile

### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
error message should be like:
Add-PnPFile : The request message is too big. The server does not allow messages larger than 262144000 bytes.
(as it was in SharePointPnPPowerShellOnline 3.28.2012.0)

### Actual behavior 
error message is:
Add-PnPFile : The underlying connection was closed: An unexpected error occurred on a send.

### Steps to reproduce behavior
$out = new-object byte[] 1073741824
(new-object Random).NextBytes($out)
$TempRandomFile = $env:TEMP+"\"+(get-date -Format "yyyyMMddHHmmss")+"1GBrandom.data"
[IO.File]::WriteAllBytes($TempRandomFile, $out)
$UploadTime = Measure-Command {Add-PnPFile -Path $TempRandomFile -Folder "/Shared Documents/General"}
$out=""
Remove-Item $TempRandomFile -Force

### What is the version of the Cmdlet module you are running?
0.3.6      PnP.PowerShell

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
I just tried your exact example and I receive the expected error message here...

![image](https://user-images.githubusercontent.com/7666381/102192285-7dc38b00-3eb2-11eb-935c-c1aa8e5bdb21.png)
