### ISSUE TITLE
[FEATURE] Recursive search with Get-PnPListItem -UniqueId

### ISSUE THREAD

**Issue by nullingestion** [pnp/powershell#550]
**Is your feature request related to a problem? Please describe.**
Whenever searching via GUID or UniqueId, if the item is not in the root directory of the list it can't be found. (Unsure whether this should be classed as a bug or feature).

**Describe the solution you'd like**
For an item with a UniqueId of `bee85621-82c7-44dd-a87b-4f82f1bad744` which is in two folders deep in the "Some List Library", when running `Get-PnPListItem -List "Some List Library" -UniqueId bee85621-82c7-44dd-a87b-4f82f1bad744`
I would like to have the item returned, regardless of its location in the library.

**Describe alternatives you've considered**
Currently this can be worked around by manually writing the query via the Query parameter:
`Get-PnPListItem -List "Some List Library" -Query "<View Scope='RecursiveAll'><Query><Where><Eq><FieldRef Name='UniqueId'/><Value Type='Guid'>bee85621-82c7-44dd-a87b-4f82f1bad744</Value></Eq></Where></Query></View>"`

**Comment by erwinvanhunen** [comment]
Hi!

We just merged an update which solve this. Please check out the upcoming nightly release: 1.5.9-nightly.
