### ISSUE TITLE
Set-PnPTraceLog does not work with either -LogFile or -WriteToConsole

### ISSUE THREAD

**Issue by sathya-bhat** [pnp/powershell#552]
### Reporting an Issue or Missing Feature
No trace information generated when backing up site template using Get-SiteTemplate in release versions PnP.PowerShell 1.4.0/1.5.0, but works in nightly '1.4.21-nightly' and '1.5.4-nightly'.

Trace generated (this is the only version of PnP module on the machine)
Install-Module -Name PnP.PowerShell -RequiredVersion 1.4.21-nightly -AllowPrerelease

No trace generated (this is the only version of PnP module on the machine)
Install-Module -Name PnP.PowerShell -RequiredVersion 1.5.0

I tried this on Windows (powershell.exe and pwsh.exe) and Ubuntu, it did not generate any logs. 
According to discussions, it should generate log. Is the build flags different for nightly and release?

### Expected behavior 
Generate trace information in log file or console.

### Actual behavior 
No log generated to file or console. When -LogFile is specified, it creates a 0 byte file, but no content.

### Steps to reproduce behavior

<#
 Replace values marked as TODO
#>
$AppGuid = "TODO"
$AppSecret = "TODO"
$SiteUrl = "https://TODO.sharepoint.com/sites/TODO"

Import-Module PnP.PowerShell

<# 
Set-PnPTraceLog -On -Level:Debug -WriteToConsole
#>

Set-PnPTraceLog -On -Level:Debug -LogFile 'c:\temp\pnptrace.log'

Write-Host "Connecting"
$PnPSiteConn = Connect-PnpOnline -url $SiteUrl -ClientId $AppGuid -ClientSecret $AppSecret -ReturnConnection -ea Stop

$Options =@{
    Connection = $PnPSiteConn
    Out = 'c:\temp\sitetemplate.pnp'
    ErrorAction = 'Stop'
    Verbose = $True
    Force = $True
    IncludeAllClientSidePages =$True
 }
  
Write-Host "Getting site template"
$Info = Get-PnPSiteTemplate @Options

Write-Host "All Done"

### What is the version of the Cmdlet module you are running?
1.5.0                PnP.PowerShell                      PSGallery            Microsoft 365 Patterns and Practices PowerShell Cmdlets

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ x] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by anthonywhite** [comment]
Finding same with 1.5.0

**Comment by jenunn** [comment]
Also having this issue with both -WriteToConsole and -Logfile.
The tracelog file is created, but no output is being written.

Using version 1.5

**Comment by bva999** [comment]
Is there any progress with this problem? I have the same problem and cannot use the library because of this.

**Comment by gautamdsheth** [comment]
Have added a fix for this. Can you please try it after tomorrow's nightly ? Do reopen this issue if it exists again.
Thanks for reporting 👍

**Comment by schneika** [comment]
When will this be fixed? Tracelog Debugging not working yet for PnP Provisioning Engine...Error-handling impossible...

**Comment by joshua-probst** [comment]
I am struggling with the same problem. At the moment i couldnt get any informations why a template fails while creation with `Get-PnPSiteTemplate` or why a template fails with `Invoke-PnPSiteTemplate`. 

PS-Version: 7.1.3
PnP-Version: 1.6.0

**Comment by gautamdsheth** [comment]
@joshua-probst , @schneika - I just checked this in both PS 5 and PS 7 with version 1.6.45 nightly and it works for both these commands

Can you please check at your end ? 

If you have old version of PnP installed, can you please delete them first and then try ?

**Comment by sathya-bhat** [comment]
@gautamdsheth Can you please try this with release version (not nightly). I am seeing trace log in 1.6.45-nightly, but not in release version 1.6.0. Is there any difference in release version vs nightly build flags or something? Thanks

**Comment by ciato** [comment]
I have the same issue. Tracelog is empty.

Checked PS version 5 and 7. Installed PnP version 1.6.0

**Comment by veronicageek** [comment]
@sathya-bhat, @ciato - Please update to `1.7.0` released today.

**Comment by ciato** [comment]
No luck. Still no logs on my side. Tried PS 5 and 7.

**Comment by sathya-bhat** [comment]
@veronicageek In release version (1.7.0, 1.6.0), it does not emit trace log. 
However in nightly builds (1.6.45-nightly), it emit trace logs. Strange.

**Comment by veronicageek** [comment]
@gautamdsheth - Do you know what would be the difference between `1.6.45-nightly` and `1.7.0.` that could cause the problem?

**Comment by buckthebug** [comment]
Same here. :( It doesn't work - PnP 1.7.0 with both PS 5 and 7
