### ISSUE TITLE
Set-PnPTeamsChannel -IsFavoriteByDefault $true - not working.

### ISSUE THREAD

**Issue by JimmyHang** [pnp/powershell#563]
### Reporting an Issue or Missing Feature
I'm trying to set Teams channel as favorite by default but its not working, i know this has been working before.

Set-PnPTeamsChannel -Team "Team name" -Identity "Channel Name" -IsFavoriteByDefault $true

### Expected behavior 
Channel is set as favorite by default

### Actual behavior 
Set-PnPTeamsChannel : Failed to execute backend request.
At line:1 char:1
+ Set-PnPTeamsChannel -Team "1199701 FELLES Oslo politihus, rehab." -Id ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Set-PnPTeamsChannel], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.Graph.SetTeamsChannel

Message          : Failed to execute backend request.
Stacktrace       :    ved PnP.PowerShell.Commands.Graph.SetTeamsChannel.ExecuteCmdlet()
                      ved PnP.PowerShell.Commands.Base.BasePSCmdlet.ProcessRecord()
                      ved System.Management.Automation.CommandProcessor.ProcessRecord()
ScriptLineNumber : 1

### Steps to reproduce behavior
run this command:

Set-PnPTeamsChannel -Team "Team name" -Identity "Channel Name" -IsFavoriteByDefault $true

### What is the version of the Cmdlet module you are running?
1.5.0 PnP.PowerShell

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@gautamdsheth / @erwinvanhunen - Still an issue in `v1.5.50-nightly`

**Comment by JimmyHang** [comment]
Hi

**Comment by veronicageek** [comment]
@JimmyHang - I've just tried with `1.7.39` today and the issue seems resolved. Can you please try again and reopen if the problem persists. Thanks.

@gautamdsheth - FYI
