### ISSUE TITLE
[BUG] - The SSL connection could not be established, see inner exception. Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by FourPeaksAdmin** [pnp/powershell#564]
### Reporting an Issue or Missing Feature

Issue

### Expected behavior 

When running 'Copy-ItemProxy', items should download and connection should be stabilized.

### Actual behavior 

Items DO download, but hit & miss randomly will populate an SSL connection error AFTER finishing.

**_Error Message:_** 
The SSL connection could not be established, see inner exception. Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..

### Steps to reproduce behavior

```
Connect-PnPOnline -Url $TenantSiteURL -CreateDrive -Credentials ($Sec) -wa SilentlyContinue -WarningVariable warn

Set-Location -Path SPO:\$SiteRelativeURL

Copy-ItemProxy -Recurse -Force "$LibraryName\$_" "$DownloadPath"
```

### What is the version of the Cmdlet module you are running?

Pnp.Powershell - 1.5.6-nightly

then 

Pnp.Powershell - 1.5.7-nightly

with same issue

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by Anto4595** [comment]
Hello @erwinvanhunen 

I am running a PowerShell script in Azure Automation Account and I am getting this error The SSL connection could not be established, see inner exception. 

This error is not showing up frequently but Occasionally.

How can I fix it and what are the things I need to check. Please advise and help on this thank you..

**Comment by Anto4595** [comment]
I Installed the latest nighty package 2.99.16 in azure automation account will it solves the issue ?

When I installed it shows 5.1 runtime version can we get the 7.2 version ?

Can you please upload it in the azure automation Browse gallery as we have only the 2.12.0 version ?

@erwinvanhunen 

Thank You..
