### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Adhanj** [pnp/powershell#565]
### Reporting an Issue or Missing Feature
Get-PnpAzureADUser -identity Guest User generates error message
Get-PnpAzureADUser -identity 'Guest user#EXT#@<domain>.onmicrosoft.com'"
Get-PnPAzureADUser: Code: BadRequest
Message: Invalid filter clause
Inner error:
        AdditionalData:
        date: 2021-04-08T21:26:08
        request-id: 51079677-8330-4b90-8a34-733b83529d73
        client-request-id: 51079677-8330-4b90-8a34-733b83529d73
ClientRequestId: 51079677-8330-4b90-8a34-733b83529d73

### Expected behavior 
Get-PnpAzureADUser should find and return the user info

### Actual behavior 
Getting error message as shown below
Get-PnPAzureADUser: Code: BadRequest
Message: Invalid filter clause
Inner error:
        AdditionalData:
        date: 2021-04-08T21:26:08
        request-id: 51079677-8330-4b90-8a34-733b83529d73
        client-request-id: 51079677-8330-4b90-8a34-733b83529d73
ClientRequestId: 51079677-8330-4b90-8a34-733b83529d73

### Steps to reproduce behavior
Get-PnpAzureADUser -identity 'Guest user#EXT#@<domain>.onmicrosoft.com'"

### What is the version of the Cmdlet module you are running?
1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows

**Comment by erwinvanhunen** [comment]
Thank for you reporting this. We just merged a fix for this issue, it will be available in the upcoming nightly release: (1.5.9-nightly).
