### ISSUE TITLE
[BUG] Get-PnPListItem with -Query and -PageSize Arguments

### ISSUE THREAD

**Issue by BaronSparky** [pnp/powershell#569]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
When querying a list with `Get-PnPListItem`, using the `-Query` option, expect to be able to return a potentially large set of results with the `-PageSize` argument.

### Actual behavior 
When using the `-Query` and `-PageSize` arguments together, the query fails and you get something similar to:
```
Get-PnPListItem -List SomeList`
   -Query '<View><Query><Where><Eq><FieldRef Name="Status"/><Value Type="Choice">Started</Value></Eq></Where></Query></view>'`
   -PageSize 1000

Get-PnPListItem : The 'View' start tag on line 1 position 2 does not match the end tag of 'view'. Line 1, position 125.
At line:1 char:1
+ Get-PnPListItem -List SomeList -Query '<View><Query><Where><Eq><Field ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPListItem], XmlException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Lists.GetListItem
```
If you remove the `-PageSize` argument, then the query executes successfully.

### Steps to reproduce behavior
Run the command, using an appropriate column for the list:
```
Get-PnPListItem -List SomeList`
   -Query '<View><Query><Where><Eq><FieldRef Name="Status"/><Value Type="Choice">Started</Value></Eq></Where></Query></view>'
```

=Using the same command, append the `-PageSize` argument with a value
```
Get-PnPListItem -List SomeList`
   -Query '<View><Query><Where><Eq><FieldRef Name="Status"/><Value Type="Choice">Started</Value></Eq></Where></Query></view>'`
  -PageSize 1000
```

### What is the version of the Cmdlet module you are running?
Observed with 1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
Hi!

Xml is case sensitive. This means that if you start with `<View>` you also have to end with `</View>`, in your example you end the query with `</view>` (lowercase 'v' instead of uppercase 'V').

**Comment by BaronSparky** [comment]
Thanks @erwinvanhunen apologies for the user error, Interestingly enough, the query does work with mismatching cases until you add the -PageSize argument but if cases match, then -PageSize also works.

Thanks...

**Comment by erwinvanhunen** [comment]
The reason it doesn't works with page size is that we parse the XML and add the required paging XML to the query. Otherwise we send it over to the server as is. The parser code we use internally is more picky about XML than the server it turns out 🙂
