### ISSUE TITLE
[BUG] Handling PNPConnection in a Runbook in Azure Automation

### ISSUE THREAD

**Issue by Tom-CK** [pnp/powershell#571]
I've written a module using functions of PnP.PowerShell and uploaded that module to Azure Automation.
The installed version of PnP.PowerShell in Azure Automation is version 1.5.0.

I am handling the connection within a function of my module - example:

  function Connect-PNP()
  {
     ....
      [OutPutType([PnP.PowerShell.Commands.Base.PnPConnection])
     ....
     [PnP.PowerShell.Commands.Base.PnPConnection]$PNPConnection = Connect-PnPOnline -Url .... -ReturnConnection
     return $PNPConnection
  }

then within another function I call for example

  ...
  $con = Connect-PNP
  $null = Get-PNPListItem -...... -Connection $con

In an Azure Automation runbook this results in an exception "Invalid type". Seems like $con is an object - but not typed as [PnP.PowerShell.Commands.Base.PnPConnection].

Running the exact same code in a powershell (non administrative) on a client everything works fine - same module version.

**Comment by erwinvanhunen** [comment]
there is nothing much we can do about this. PnP PowerShell does not recognize/nor have any understanding of the environment it runs in, and thus does not return different objects depending on the environment. It seems to be an Azure Runbook issue (that we are unaware of) but we do not control that environment. If it works on a client but not in a Runbook it seems to be more related to the Runbook environment than PnP PowerShell?

**Comment by Tom-CK** [comment]
Hmmmm ....
Okay - I will open a ticket in azure.
