### ISSUE TITLE
Submit-PnPSearchQuery fails (with the error NotFound_GetStampsMetadataPluginNoProvisionedOrProvisioningStamps) when running with an AAD App Only connection

### ISSUE THREAD

**Issue by michael-jensen** [pnp/powershell#577]
### Expected behavior 
In the legacy PnP PowerShell module we were able to run the Submit-PnPSearchQuery cmdlet, when connected with an AAD App Only connection, without any issues. We were expecting the same behavior in the current PnP.PowerShell, but this cmdlet does not appear to be working with an AAD App Only connection.

### Actual behavior 
When you have a connection established via an AAD App, which has the 'Sites.FullControl.All', 'TermStore.ReadWrite.All' SharePoint permissions along with the 'Group.ReadWrite.All' Graph permissions, and run the Submit-PnPSearchQuery cmdlet with any query (i.e. `Submit-PnPSearchQuery -Query 'test'`), you receive the following error message:

`Submit-PnPSearchQuery: NotFound_GetStampsMetadataPluginNoProvisionedOrProvisioningStamps`

I then called Get-PnPException to see if the additional details would be helpful:

```
Message          : NotFound_GetStampsMetadataPluginNoProvisionedOrProvisioningStamps
Stacktrace       :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
                      at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
                      at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServerAsync(ChunkStringBuilder sb)
                      at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryAsync()
                      at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQueryAsync()
                      at Microsoft.SharePoint.Client.ClientContext.ExecuteQueryAsync()
                      at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
                      at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
                      at PnP.PowerShell.Commands.Search.SubmitSearchQuery.Run() in c:\PnPPowerShell\src\Commands\Search\SubmitSearchQuery.cs:line 127
                      at PnP.PowerShell.Commands.Search.SubmitSearchQuery.ExecuteCmdlet() in c:\PnPPowerShell\src\Commands\Search\SubmitSearchQuery.cs:line 187
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in c:\PnPPowerShell\src\Commands\Base\PnPSharePointCmdlet.cs:line 60
ScriptLineNumber : 1
```

### Steps to reproduce behavior
1. Create an AAD App (using Register-PnPAzureADApp) with the 'Sites.FullControl.All', 'TermStore.ReadWrite.All' SharePoint permissions and 'Group.ReadWrite.All' Graph permissions
2. Connect to your tenant using the AAD App you just created
3. Run the command `Submit-PnPSearchQuery -Query 'test'`

### What is the version of the Cmdlet module you are running?
1.5.0 (although I just tried with the 1.5.10-nightly and observed the same result)

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
As such nothing has changed between the auth when it comes to AAD apponly when looking at the Legacy and new PnP PowerShell. Both utilize the bearer header for auth with an access token. Have you tried with the latest legacy to see if that still works?

**Comment by wobba** [comment]
@michael-jensen are you saying the "old" version works on the same tenant? And if so, which version are you using?

**Comment by michael-jensen** [comment]
Hi @erwinvanhunen and @wobba, yes the Submit-PnPSearchQuery cmdlet works for us with the SharePointPnPPowerShellOnline module (version 3.29.2101.0) but we encounter the error mentioned above in the PnP.PowerShell module (I've tested it with 1.5.0 and 1.5.10-nightly) - all tested against the same tenant.

Let me know if you need anything else to help troubleshoot this.

**Comment by wobba** [comment]
@michael-jensen can you compare the Bearer token on both requests, as well as the actual requests to spot any differences?

**Comment by michael-jensen** [comment]
Hi @wobba I ran through some tests in a couple of tenants and have some interesting results. In one of the tenants we use for development, the Submit-PnPSearchQuery cmdlet works with both the legacy PnP (version 3.29.2101.0) and PnP.PowerShell 1.5.0, however when testing in two other tenants (one used for development, another for client UAT) the cmdlet fails with both the legacy PnP (version 3.29.2101.0) and PnP.PowerShell 1.5.0.

So this issue appears to be tenant related (including a new tenant I just spun up) when running the Submit-PnPSearchQuery cmdlet that is connected via an AAD App with the "TermStore.ReadWrite.All", "Sites.FullControl.All" permissions.

Is this something that Microsoft needs to look into? Are you able to repo this issue by creating a new tenant, then connecting to that tenant with an AAD App and run the Submit-PnPSearchQuery cmdlet?

**Comment by wobba** [comment]
If you look at the requests, is the bearer token the same for both versions? The new cmdlet used the MSAL lib, while the old used ADAL - so could be some difference in the token fetching. Could also be related to something else which I'll check internally.

**Comment by wobba** [comment]
We are investigating the issue to find a resolution and I'll report back when I have more details.

**Comment by michael-jensen** [comment]
Hi @wobba - I am not exactly sure what sort of differences you are looking for with the bearer token, as a new token is generated with each connection (regardless of the version of PnP version I am using). I ran the Get-PnPAppAuthAccessToken cmdlet and decoded the results and the properties I would expect to be the same are (i.e. aud, iss, appid, idp, etc.)

What is interesting though, is one of the developer tenants where the Submit-PnPSearchQuery cmdlet returned the `NotFound_GetStampsMetadataPluginNoProvisionedOrProvisioningStamps` error in any version of the PnP PowerShell module (new or the legacy SharePointPnPPowerShellOnline module - as I noted in my last comment this issue appears to be occurring in certain tenants) just started working this morning (in both PnP.PowerShell 1.5.0 and SharePointPnPPowerShellOnline 3.29.2101.0). I haven't done anything in that tenant in the past 5 days, and that cmdlet was failing 4 days ago, so it appears that something is happening on the server side with certain tenants when you try to execute a search query via an AAD App.

**Comment by wobba** [comment]
@michael-jensen I have an explanation for the "now working" scenario, and is expected. Which means, the PnP version and token is not involved why it works and not. When running an app-only search all scenario, the backend handles this different for optimization purposes. The error you see is related to the optimization part.

**Comment by michael-jensen** [comment]
Hi @wobba can you please elaborate on your explanation?

I am concerned if we have no control over whether or not an app-only search query will work (i.e. nondeterministic). As part of our automated deployment scripts we had been using a search based approach to find all sites connected to a hub site - this was due to the Get-PnPHubSiteChild cmdlet running into a threshold limit last year on tenants with 5,000+ site collections, but it appears that issue has been resolved. However, it would be good to know if we can reliably execute app-only search queries going forward, or if that is something that should be avoided.

**Comment by wobba** [comment]
It might fail once optimization starts per tenant, but won't happen again once it completes.

**Comment by michael-jensen** [comment]
Ah, I see ... thanks for clarifying @wobba 

Is there a way to determine if the optimization has been carried out in a tenant? That way we know if it hasn't yet, that we can expect this issue to occur (for an unknown period of time) while the optimization is happening.

**Comment by wobba** [comment]
Sorry, but I don't have all the details. I suspect content volume size will impact things.

**Comment by michael-jensen** [comment]
Okay, thanks for all of the info @wobba 

I'll close this issue as it has nothing to do with the PnP.PowerShell module.
