### ISSUE TITLE
[FEATURE] Add-PnPTeamUser Does Not Return Permission Error

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#579]
### Reporting an Issue or Missing Feature
I am reporting a bug

### Expected behavior 
`Add-PnPTeamsUser` should return a permission error when an Azure app it operates under has no _Group.ReadWrite.All_ permissions.

### Actual behavior 
`Add-PnPTeamsUser` does **not** return _any_ error when an Azure app it operates under has no _Group.ReadWrite.All_ permissions. It simply runs.

### Steps to reproduce behavior
Consider the following scenario 1:

- Create Azure App
- Grant Group.ReadWrite.All **delegated** permissions and Group.Read.All **application** permissions
- Issued and install where required a self-signed cert
- Connect to PnP via app using certificate
- Run `Add-PnPTeamsUser -Team <SomeTeam> -User <SomeUser> -Role Member` command
- Run `Get-PnPTeamsUser -Team <SomeTeam> | sort DisplayName`
- **Result**: user is not added due to lack for permission, but no error returned.

Scenario 2:
- Connect to PnP via Microsoft PnP Management app with username and password
- Run `Add-PnPTeamUser -Team <SomeTeam> -User <SomeUser> -Role Member` command
- Run `Get-PnPTeamsUser -Team <SomeTeam> | sort DisplayName`
- **Result**: user is added to the team

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Seems to work fine for me and throws Auth error, can you try again ?

![image](https://user-images.githubusercontent.com/8832018/118392074-3f92e900-b655-11eb-8fbe-6bfbc5bd9033.png)

**Comment by YuriySamorodov** [comment]
Reproduced the same issue with `PnP.PowerShell 1.5.59` and `PowerShell 7.1.3`
