### ISSUE TITLE
[BUG] Get-PNPListItem: The current user dos not have the permission to access the App Catalog ?

### ISSUE THREAD

**Issue by Tom-CK** [pnp/powershell#582]
I have set up an App-Account in SharePoint like described here:
https://www.sharepointdiary.com/2019/03/connect-pnponline-with-appid-and-appsecret.html

Then I call 

$PNPConnection = Connect-PNPOnline -Url .... -ClientId [ID like registered] -ClientSecret [Secret like registered] -ReturnConnection

After this i call

Get-PNPListItem -List [My Listname]

Running this code on a local machine, everything is working well.

Running this code in Azure Automation, i get the error:

ERR: Get-PNPListItem : The current user does not have the permission to access the App Catalog.
![image](https://user-images.githubusercontent.com/77489598/114419854-1691bb00-9bb4-11eb-9469-1e5a63be86e5.png)

After getting this error in azure automation runbook, I also get an error locally:
![image](https://user-images.githubusercontent.com/77489598/114420038-40e37880-9bb4-11eb-9c5d-f65125a44d47.png)

I use PNP.PowerShell 1.5.0 in both environments (locally and azure automation).

Tried to Disconnect-PNPOnline locally - did not solve the problem.

I am using the same ClientID and ClientSecret on my local machine and in my runbook in azure automation.

**Comment by veronicageek** [comment]
@Tom-CK 
> After getting this error in azure automation runbook, I also get an error locally

Do you mean that you come back to your local machine where it worked (on the same session), re-run your script and it suddenly fails?

**Comment by Tom-CK** [comment]
Yes Veronica, this is exactly what happened.

Do you have an idea of how to solve this ?

**Comment by Tom-CK** [comment]
Things have changed a litte bit.
I have now registered two different apps in sharepoint online using "appregnew.aspx" and "appinv.aspx" (see https://www.sharepointdiary.com/2019/03/connect-pnponline-with-appid-and-appsecret.html).

Then i connect on the CLIENT using:
Connect-PNPOnline -Url [URL] -ClientId [ClientID1] -ClientSecret [ClientSecret1]

Everything works as expected, I can query lists and all the other things.

When I connect from AZURE AUTOMATION using:
Connect-PNPOnline -Url [URL] -ClientId [ClientID2] -ClientSecret [ClientSecret2]

I get a valid connection object.
But when I then call "Get-PNPListItem" there is an exception:
"Get-PNPListItem: The current user does not have the permission to access the App Catalog."

Seems like I can not get a valid connection with ClientID and ClientSecret to work in a runbook in Azure Automation ?

**Comment by veronicageek** [comment]
@Tom-CK - I see you opened an issue previously regarding actions in an Azure Runbook/Automation, but I'm afraid that if all is working as expected from a PowerShell PnP perspective on a client, there's not much we can do this time either.

Referring to @erwinvanhunen's answer for your issue #571 

> there is nothing much we can do about this. PnP PowerShell does not recognize/nor have any understanding of the environment it runs in, and thus does not return different objects depending on the environment. It seems to be an Azure Runbook issue (that we are unaware of) but we do not control that environment. If it works on a client but not in a Runbook it seems to be more related to the Runbook environment than PnP PowerShell?

**Comment by Tom-CK** [comment]
@veronicageek - Thank you for taking care ! 
But maybe there is something going wrong. 
Why does a "Get-PNPListItem" respond with an exception concerning the app catalog ? What can be a reason for this ?
Maybe different ways of handling the connection (CSOM / Graph) ?
