### ISSUE TITLE
[FEATURE] Get-PnPGroup | Set-PnPGroup Requests Identity Parameter

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#583]
### Reporting an Issue or Missing Feature
I am reporting a missing feature

### Expected behavior 
Get-PnPGroup should send Identity down the pipeline so a command like the one below can work:
`Get-PnPGroup | Set-PnPGroup -Owner admin@contoso.com`
Looks like `Set-PnProup` cmdlet does not support `valuefrompupeline` or `valuefrompipelinebypropertyname` parameters

### Actual behavior 
When feeding `Set-PnPGroup` command with `Get-PnPGroup` it would request value for `Idenity` 
![image](https://user-images.githubusercontent.com/5260172/114633303-f43d9180-9cc8-11eb-8430-8b18c841acac.png)

### Workaround
`Get-PnPGroup | %{ Set-PnPGroup -Identity $_.Id -Owner admin@contoso.com }`

### Steps to reproduce behavior

1. Connect to a SharePoint Online via PnP.PowerShell
2. Run a command: `Get-PnPGroup | Set-PnPGroup -Owner admin@contoso.com`

### What is the version of the Cmdlet module you are running?
`PnP.PowerShell 1.5.0`

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@YuriySamorodov 
Was it working before and it doesn't now? (for it to be a bug) - Or are you asking for an enhancement? (which I think you are)

**Comment by YuriySamorodov** [comment]
Hey @veronicageek , I think you are correct, I am asking for an enhancement

**Comment by erwinvanhunen** [comment]
Good one! We merged an update and it will be available in release 1.5.19-nightly tomorrow.
