### ISSUE TITLE
[BUG] Set-PnPTenantSite: The property or field 'ServerLibraryVersion' has not been initialized.

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#585]
### Reporting an Issue or Missing Feature
I am reporting a bug

### Expected behavior 
`Set-PnPTenantSite -Owners groupname@contoso.com -Identity https://contoso.sharepoint.com/sites/somesite` should add site collection administrators on the site per the documentation:
https://github.com/pnp/powershell/blob/dev/documentation/Set-PnPTenantSite.md#-owners

### Actual behavior 
`Set-PnPTenantSite -Owners groupname@contoso.com -Identity https://contoso.sharepoint.com/sites/somesite` throws an error:
`Set-PnPTenantSite: The property or field 'ServerLibraryVersion' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.`
Happens for both users and groups
![image](https://user-images.githubusercontent.com/5260172/114771005-c1e96e00-9d74-11eb-91b9-e92be6b21e2b.png)
Was working just fine before updating to `PnP.PowerShell 1.5.13` it was throwing different error #544

### Steps to reproduce behavior
```
Connect-PnPOnlineSite -Identity https://contoso-admin.sharepoint.com -Credentials (Get-Credential)
Set-PnPTenantSite -Owners groupname@contoso.com -Identity https://contoso.sharepoint.com/site/somesite
```

### What is the version of the Cmdlet module you are running?
```
Name    : PnP.PowerShell
Version : 1.5.13
```
### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
Hi @YuriySamorodov - I have no problem with v.1.5.16-nightly when connecting to the `-admin.sharepoint.com` or connecting to the site directly (_tried with a Security Group, a user, or a M365 Group_). Can you please update and try?

![image](https://user-images.githubusercontent.com/25181757/115114705-95a63b00-9f88-11eb-8166-0b1118e21e14.png)

**Comment by YuriySamorodov** [comment]
Hi @veronicageek ,

That's right, it's working just fine with `PnP.PowerShell 1.5.16`
Thanks for checking!

Kind regards,
Yuriy
