### ISSUE TITLE
[BUG] Error using existing connection after running Get-PnPAccessToken

### ISSUE THREAD

**Issue by svermaak** [pnp/powershell#586]
### Reporting an Issue or Missing Feature
Error using existing connection after running Get-PnPAccessToken

### Expected behavior 
I expect to be able to use the existing connection without having to Disconnect-PnPOnline and then again Connect-PnPOnline

### Actual behavior 
Get error
_Get-PnPTeamsChannel: AADSTS65001: The user or administrator has not consented to use the application with ID '31359c7f-bd7e-475c-86db-fdb8c937548e' named 'PnP Management Shell'. Send an interactive authorization request for this user and resource._

### Steps to reproduce behavior
![image](https://user-images.githubusercontent.com/12259728/114817505-74fdaa00-9dfd-11eb-92f8-0219e7219035.png)

### What is the version of the Cmdlet module you are running?
1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
I can confirm this issue. We're looking into the cause and a possible solution.

**Comment by erwinvanhunen** [comment]
We fixed it and the fix will be available in 1.5.19-nightly tomorrow.

**Comment by svermaak** [comment]
Fantastic news!
