### ISSUE TITLE
Set-PnPTerm not updating existing term

### ISSUE THREAD

**Issue by JaeEmAre67** [pnp/powershell#588]
Unable to update an existing term with Set-PnPTerm, simply nothing changes in the term store.

`cls
$startTime = Get-Date -Format 'yyyy.MM.dd HH:mm:ss'
write-host "Started at $startTime"

function getFromEnv() {
    $fe = Read-Host "Enter the environment you want to change the terms from (pr / qa / dev)"
    $fe = "o365_" + $fe.ToLower()
    return $fe
}

function getSiteCollection() {
    Write-host "Enter the URL of the site collection with the term store to update"
    $sc = Read-Host "     (https://portal.ourDomain.com/sites/ourAppo365.....)"    
    return $sc
}

function getToEnv() {
    $te = Read-Host "Enter the environment you want to change the terms to (pr / qa / dev)"
    $te = "o365_" + $te.ToLower()
    return $te
}

if($null -ne $siteCollection) {
    $reuse = Read-Host "It appears you've used" $siteCollection "recently, do you want to continue to use this site collection (y/n)?"
    if($reuse.ToLower() -ne "y") {
        $siteCollection = getSiteCollection
    }
} else {
    $siteCollection = getSiteCollection
}

if($null -ne $fromEnv) {
    $fromBefore = Read-Host "It appears you previously wanted to change from" $fromEnv "to" $toEnv ". Do you want to continue using these settings (y/n)?"
    if($fromBefore.ToLower() -ne "y") {
        $fromEnv = getFromEnv
        $toEnv = getToEnv
    }
} else {
    $fromEnv = getFromEnv
    $toEnv = getToEnv
}

Connect-PnPOnline $siteCollection -UseWebLogin
$allTermGroups = Get-PnPTermGroup
$maTermGroup = ""
$checkTermSets = @()

foreach($termGroup in $allTermGroups) {
    if($termGroup.Name.toLower() -match "ourAppo365") {
        $maTermGroup = $termGroup
    }
}

#Write-Host $maTermGroup.Name
if($maTermGroup -eq "") {
    Write-Host "Didn't find a ourApp term group"   
} else {
    Write-Host "Found ourApp term group"
    $allTermSets = Get-PnPTermSet -TermGroup $maTermGroup
    foreach($termSet in $allTermSets) {
        $checkTermSets+=$termSet
    }
    
    #LOOP AND CHANGE TERMS
    foreach($set in $checkTermSets) {
        $workingTermSet = Get-PnPTermSet -Identity $set.Name -TermGroup $maTermGroup
        $workingTerms = Get-PnPTerm -TermSet $workingTermSet -TermGroup $maTermGroup -IncludeChildTerms
        foreach($term in $workingTermS) {
            $allCreatedTerms = $term.Terms
            foreach($wrkTerm in $allCreatedTerms) {
                if($wrkTerm.Name -match "o365_pr") {
                    $envString = $wrkTerm.Name.ToLower()
                    $newEnvString = $envString.Replace($fromEnv, $toEnv)
                    Write-Host "Changing from" $wrkTerm.Name "to" $newEnvString
                    #Set-PnPTerm -Identity $wrkTerm.Id -Name $newEnvString -TermSet $set -TermGroup $maTermGroup #doesn't update
                    Set-PnPTerm -Identity $wrkTerm.Id -Name $newEnvString #doesn't update
                }
            }
        }
    }
}

$finishedTime = Get-Date -Format 'yyyy.MM.dd HH:mm:ss'
write-host "Finished at $finishedTime"
Write-Host "     "(New-TimeSpan -Start $startTime -End $finishedTime) -ForegroundColor Gray`

**Comment by veronicageek** [comment]
@JaeEmAre67 - The `Set-PnPTerm` works fine for me with the `-Identity` by name or Id. So your issue may be somewhere else.

![image](https://user-images.githubusercontent.com/25181757/114932673-ad1de080-9e2f-11eb-85d4-ec9156e69de5.png)

![image](https://user-images.githubusercontent.com/25181757/114932703-b4dd8500-9e2f-11eb-999d-300a2f143854.png)
