### ISSUE TITLE
[BUG] Get-PnPPage does not resolve Templates path

### ISSUE THREAD

**Issue by HeKr09** [pnp/powershell#590]
### Reporting an Issue or Missing Feature
The cmdlet Get-PnPPage does not resolve the "Templates" path within the identity parameter as described in the documentation.

### Expected behavior 
No error while using the complete path.

### Actual behavior 
```
$page = Get-PnPPage -Identity "Templates/Content Template with vertical column.aspx"

Get-PnPPage : Page 'Templates/Content Template with vertical column.aspx' does not exist
At D:\TFS\Set-ContentTemplateAfterCreation.ps1:79 char:17
+         $page = Get-PnPPage "Templates/$Template.aspx"
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPPage], Exception
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Pages.GetPage
```

This one works:
`$page = Get-PnPPage "Content Template with vertical column.aspx"`

### Steps to reproduce behavior
See above.

### What is the version of the Cmdlet module you are running?
1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
Hi @HeKr09 - Thanks for reporting, it's been fixed in v.1.5.16-nightly
You can update now or wait for the next major release.

![image](https://user-images.githubusercontent.com/25181757/115113815-0a2aab00-9f84-11eb-8f87-cc0e5a372e60.png)
