### ISSUE TITLE
Set-PnPTeamsTeam : NotSpecified is not a valid value for visibility property.

### ISSUE THREAD

**Issue by 3031539** [pnp/powershell#593]
We are unable to change the Displayname nor the Description of newly create TEAMS.

PNP.PowerShell version is 1.5.0

Set-PnPTeamsTeam -Identity LTPTEST -Displayname 'TEST 2'

Set-PnPTeamsTeam -Identity LTPTEST -Verbose -Description 'TEST 2'
Set-PnPTeamsTeam : NotSpecified is not a valid value for visibility property. Valid values are Public,
Private, HiddenMembership
Au caractère Ligne:1 : 1
+ Set-PnPTeamsTeam -Identity LTPTEST -Verbose -Description 'TEST 2'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (:) [Set-PnPTeamsTeam], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.Graph.SetTeamsTeam

**Comment by gautamdsheth** [comment]
Has been fixed , should be available in tomorrow's nightly and the next major version !
