### ISSUE TITLE
[BUG] Publish-PnPCompanyApp: Exception of type 'PnP.PowerShell.Commands.Model.Graph.GraphException' was thrown.

### ISSUE THREAD

**Issue by rachaelsingleton** [pnp/powershell#594]
### Reporting an Issue 
Please confirm what it is that your reporting

### Expected behavior 
Teams app created
Teams app uploaded

### Actual behavior 
`Publish-PnPCompanyApp: Exception of type 'PnP.PowerShell.Commands.Model.Graph.GraphException' was thrown.`

### Steps to reproduce behavior
`Connect-PnPOnline https://tenant-admin.sharepoint.com -DeviceLogin

Publish-PnPCompanyApp `
    -PortalUrl $portalUrl `
    -AppName $appName `
    -Description $shortDes `
    -LongDescription $longDes `
    -PrivacyPolicyUrl $privacyPolicy `
    -TermsAndUsagePolicyUrl $termsUsage `
    -CompanyName $companyName `
    -CompanyWebSiteUrl $companyWebsite `
    -ColoredIconPath $coloredIcon `
    -OutlineIconPath $outlineIcon `
    -AccentColor $accentColor
`

### What is the version of the Cmdlet module you are running?
1.5

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Can you do a `Get-PnPException` just after the error message and paste that here ?

**Comment by rachaelsingleton** [comment]
`Message          : Exception of type 'PnP.PowerShell.Commands.Model.Graph.GraphException' was thrown.
Stacktrace       :    at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in c:\PnPPowerShell\src\Commands\Base\PnPSharePointCmdlet.cs:line 74
                      at System.Management.Automation.CommandProcessor.ProcessRecord()
ScriptLineNumber : 1`

**Comment by erwinvanhunen** [comment]
Hi! Can you confirm you have permissions to publish Teams app to the Teams App Catalog?

Alternatively, try to run the cmdlet with the `-NoUpload` switch, this will generate the zip file, then manually try to upload the app/zip to the Teams app catalog.
