### ISSUE TITLE
[BUG] Get-PnPProperty randomly returning (400) Bad Request error

### ISSUE THREAD

**Issue by wonderlands-nightmare** [pnp/powershell#598]
### Reporting an Issue
We have a script that pulls information from SharePoint Online lists, and uses ```$oItem = Get-PnPProperty -ClientObject $item -Property FieldValuesAsText``` to get text values for outputting into a CSV file. 
This code executes dozens of times iterating over items in the list, but will randomly throw a (400) Bad Request error.

As a note, this happened to a coworker as well when using ```Get-PnPEventReceiver``` from their local machine, but re-executing the code did not throw the (400) Bad Request error like the first time.

I have looked for any system outages/maintenance/etc. from Microsoft and Azure DevOps that would impact this but have not found anything, so I figured I would start here with a raised item and see how we go.

### Expected behavior 
The line of code will execute the same for each item iteration without throwing the error, or at least be consistent with a thrown error.

### Actual behavior 
The (400) Bad Request error is thrown randomly over multiple executions of the exact same code, over the exact same list and items. Note that there is no consistency to which item it throws the error on.
```
Get-PnPProperty : The remote server returned an error: (400) Bad Request.
At D:\a\r1\a\_EBC SPFx\UtilityScripts\DataExportForPowerBI.ps1:214 char:24
+ ...    $oItem = Get-PnPProperty -ClientObject $item -Property FieldValues ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPProperty], WebException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Base.EnsureProperty
```

### Steps to reproduce behavior
1. Set up an Azure DevOps Release Pipeline
2. Make an inline PowerShell step and add code that iterates over items in a list and get the list item properties with ```$oItem = Get-PnPProperty -ClientObject $item -Property FieldValuesAsText``` (assign to variable optional)
3. Execute release pipeline job a number of times until the error occurs

### What is the version of the Cmdlet module you are running?
1.5.0 PnP.PowerShell - Running on Azure DevOps Linux Release Pipeline

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [x] Other : Linux on Azure DevOps Release Pipeline

**Comment by wonderlands-nightmare** [comment]
We've found that this issue may be related to Microsoft not supporting TLS 1.0/1.1 anymore (1.1 as of late March 2021) where the Azure DevOps hosted agent VM might be defaulting to unsupported TLS protocols causing bad requests. We've implemented a forced use of TLS 1.2 and 1.3 (available on the MS hosted VM) as of last night (29/04/2021) and will see how that goes.

**Comment by wonderlands-nightmare** [comment]
Looks like it hasn't resolved the issue. Still occurring, but now happening intermittently with `Get-PnPListItem`

**Comment by paul1976** [comment]
We are also experiencing some random Bad Request (400) errors but on the Apply-PnPProvisioningTemplate cmdlet. We use Azure Automation Powershell Runbook to provision sites and apply XML templates (using Apply-PnPProvisioningTemplate). This procedure runs for some time now, but in the last couple of weeks, we start getting some random Bad Request (400) when applying templates. It does not happen every time a template is applied but more randomly. When restarting the Powershell Runbook, the templates are applied correctly again without an error.

**Comment by wonderlands-nightmare** [comment]
Yeah it has spread for us into `Get-PnPTerm` as well, and even has happened during a co-workers powershell script that updated some list items.

It's good to know others have been experiencing this too! All of my google searching shows old items from early 2020 and before.

I've had to resort to adding retry code to ensure the failing instance complete.

**Comment by paul1976** [comment]
Yes, we were also thinking about some Retry logic to solve the problem. But I would like to know what the real problem is. Here I found another post from somebody experiencing the same issue (I also commented on that post): https://stackoverflow.com/questions/67234860/web-exception-while-calling-clientcontext-web-applyprovisioningtemplate-in-sha

**Comment by wonderlands-nightmare** [comment]
I haven't been able to find anything on this yet, or a resolution for it, but the issue seems to have not occurred for over a week now so maybe it was quietly fixed in the back end somewhere.

For those interested here is the PowerShell PnP retry function and usage!
**Credit**
I found the following article for a retry command and modified it for my use: https://ridicurious.com/2019/02/01/retry-command-in-powershell/

**Function breakdown**
Parameters:
- ScriptBlock - The code to pass into the retry function
- RetryCount - The number of times the command is retried, default is 3
- DelayInSecs - The number of seconds to wait between retries in seconds, default is 30 seconds
- SuccessMessage - The success message when running retries with verbose flag, can use variables to pass in for custom message
- FailureMessage - The failure message when running retries, can use variables to pass in for custom message

Return object:
- returnObject.success - Boolean value on whether the scriptblock passed before retry limit exceeded or not
- returnObject.object - Scriptblock output object that may be required in future code

**Function call**
```
# Example assigns to object for use later in a script, has 1 second delay between retries, and a custom failure message
$getSpGroupsResult = Retry-Command -ScriptBlock {
  Get-PnPGroup | Where-Object { $_.OwnerTitle -ne "System Account" }
} -DelayInSecs 1 -FailureMessage "Failed to get $($siteUrl) SharePoint Groups."
```

**Function code**
```
# Allow for retrying commands in case they fail
function Retry-Command {
  [CmdletBinding()]
  Param (
      [Parameter(Mandatory, ValueFromPipeline)] 
      [ValidateNotNullOrEmpty()]
      [scriptblock]
      $ScriptBlock,
      [int]
      $RetryCount = 3,
      [int]
      $DelayInSecs = 30,
      [string]
      $SuccessMessage = "Command executed successfuly!",
      [string]
      $FailureMessage = "Failed to execute the command"
      )
      
  Process {
      # Initialise variables
      $attemptCount = 1
      $executeFlag = $true
      $returnSuccess = $null
      
      # Execute while $executeFlag is true
      do {
          try {
              # Save previous error action preference and set current preference
              $PreviousPreference = $ErrorActionPreference
              $ErrorActionPreference = 'Stop'
              # Invoke the scriptblock
              $returnObject = Invoke-Command -ScriptBlock $ScriptBlock
              # Reset error action preference to previous preference
              $ErrorActionPreference = $PreviousPreference

              # Only outputs success message if -Verbose parameter used with Retry-Command
              Write-Verbose "$SuccessMessage `n"
              # Set success to true to show successfull execution and flag to false to stop execution
              $returnSuccess = $true
              $executeFlag = $false
          }
          catch {
              if ($attemptCount -gt $RetryCount) {
                  # Output error information once attempts exceed retry limit
                  Write-Host "$FailureMessage! Total retry attempts: $RetryCount"
                  Write-Host "[Error Message] $($_.exception.message)"
                  Write-Host "[Invocation Positional Message] $($_.InvocationInfo.PositionMessage) `n"
                  # Set success to false to show failed execution and flag to false to stop execution
                  $returnSuccess = $false
                  $executeFlag = $false
              }
              else {
                  # Output and increment attempt count and wait for the set delay
                  Write-Host "[$attemptCount/$RetryCount] $FailureMessage. Retrying in $DelayInSecs seconds..."
                  Start-Sleep -Seconds $DelayInSecs
                  $attemptCount += 1
              }
          }
      }
      while ($executeFlag)

      # Return object with both the success boolean and the returned object from the invoked command (if any)
      return @{
        "success" = $returnSuccess
        "object"  = $returnObject
      }
  }
}
```
