### ISSUE TITLE
[BUG] Get-PnPClientSidePage does not return web parts for team site

### ISSUE THREAD

**Issue by Jelon3k** [pnp/powershell#599]
### Reporting an Issue or Missing Feature
Issue
### Expected behavior 
I expect to see home page elements (webPart.Title)
### Actual behavior 
After runing the script on a newly created team site, the script does not return any elements. If I add or remove any element to the default home page then the script returns the all elements. Env sharepoint online.
### Steps to reproduce behavior
1. Create a team site
2. Run script ($sourceUrl = "https://mysharepointonline.sharepoint.com/sites/myTeamSite"
`Connect-PnPOnline -Url $sourceUrl -Credentials $global:credentials`
   `page = Get-PnPClientSidePage -Identity "Home.aspx"`
`$webParts = $page.Controls`
`foreach ($webpart in $webparts) {`
 `$webpart.Title`
`}`
### What is the version of the Cmdlet module you are running?
1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@Jelon3k - According to the [documentation](https://pnp.github.io/powershell/cmdlets/Get-PnPClientSidePage.html), this seems an expected behavior from what you're describing?

> This command allows the retrieval of a modern sitepage along with its properties and contents on it. Note that for a newly created modern site, the Columns and Sections of the Home.aspx page will not be filled according to the actual site page contents. This is because the underlying CanvasContent1 will not be populated until the homepage has been edited and published. The reason for this behavior is to allow for the default homepage to be able to be updated by Microsoft as long as it hasn't been modified. For any other site page or after editing and publishing the homepage, this command will return the correct columns and sections as they are positioned on the site page.

**Comment by Jelon3k** [comment]
@veronicageek Thank you, you're right. The method works according to the documentation. Can you suggest me any other method to access these components?

**Comment by veronicageek** [comment]
What do you mean?
