### ISSUE TITLE
[BUG] Set-PnPTenantSite The property or field 'ServerLibraryVersion' has not been initialized. Custom App

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#600]
### Reporting an Issue or Missing Feature
I am reporting a bug

### Expected behavior 
`Set-PnPTenantSite` should run without errors

### Actual behavior 
When I execute `Set-PnPTenantSite` while connected through custom app it returns an error:

> Set-PnPTenantSite: The property or field 'ServerLibraryVersion' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested

Azure App is granted full access on SharePoint Online sites:

![image](https://user-images.githubusercontent.com/5260172/115418166-f2605a80-a201-11eb-979f-754b4b6c0d6b.png)

When I connect with PnP.PowerShell Management app it works just fine.

### Steps to reproduce behavior
```
Connect-PnPOnline -Url https://contoso-admin.sharepoint.com
Set-PnPTenantSite -Url https://contoso.sharepoint.com/sites/test -SharingCapability ExternalUserSharingOnly
```

### What is the version of the Cmdlet module you are running?
```
get-module PnP.PowerShell  | fl Name, *Version*

Name                   : PnP.PowerShell
Version                : 1.5.19
ClrVersion             :
DotNetFrameworkVersion : 4.6.1
PowerShellHostVersion  :
PowerShellVersion      : 5.1
```

```
$host.version
7.1.1
```

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
We just merged a fix. Please test with version 1.5.23-nightly.
