### ISSUE TITLE
[FEATURE] Rename-PnPSite or Rename-PnPTenantSite Cmdlet Request

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#603]
**Is your feature request related to a problem? Please describe.**
It does not seem there is any way to rename sites using PnP.PowerShell

**Describe the solution you'd like**
It would be great to have some kind of a cmdlet that would allow rename SharePoint Online sites with `PnP.PowerShell` like:

- `Rename-PnPSite`
- `Rename-PnPTenantSite`

**Describe alternatives you've considered**

- SharePoint Online Admin Center
![image](https://user-images.githubusercontent.com/5260172/115478987-0d59bb80-a250-11eb-8301-0a59c07cba37.png)

- `Start-SPOSiteRename`
https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/start-spositerename?view=sharepoint-ps

**Additional Context**
#601

**Comment by robertcaretta** [comment]
@YuriySamorodov - Have a look at this cmdlet. This has a title option.
https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnptenantsite?view=sharepoint-ps

**Comment by YuriySamorodov** [comment]
Thanks @robertcaretta. My intention was changing URL as well. `Set-PnPSite` does not allow to change site address unfortunately.

**Comment by veronicageek** [comment]
@YuriySamorodov - FYI, we looked at this, but we need to discuss this cmdlet a bit further. We'll update this request in due time 🙂

**Comment by YuriySamorodov** [comment]
Thanks @veronicageek You have always been and still are of a great help! Appreciate your insight. 
Quick idea: `-Url` parameter for `Set-PnPSite` or `Set-PnPTenantSite` cmdlets would be probably even better.

**Comment by robertcaretta** [comment]
Start-SPOSiteRename
https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/start-spositerename?view=sharepoint-ps

**Comment by ToddKlindt** [comment]
I'm working on a project and I'd probably give one of my children up to get the ability to do this in PnP. I'm not above bribing someone, just give me their Venmo address. :)

**Comment by ToddKlindt** [comment]
In my quest to find a solution for this issue I noticed that the M365 CLI has[ a command ](https://pnp.github.io/cli-microsoft365/cmd/spo/site/site-rename/)for this. I know there's some code sharing between the two projects. Does that help whoever is going to write the PowerShell version?

**Comment by YuriySamorodov** [comment]
Hi @erwinvanhunen @gautamdsheth ,
Just wondering if there is any progress on this?

**Comment by ToddKlindt** [comment]
> Hi @erwinvanhunen @gautamdsheth ,
> Just wondering if there is any progress on this?

I wrote a function that uses PnP that does this that I've been meaning to blog. I'll get it up in the next couple of days.

**Comment by YuriySamorodov** [comment]
Hi @erwinvanhunen @gautamdsheth , hope you both doing great. Is there any hope this can be added in PnP.PowerShell?

**Comment by KoenZomers** [comment]
Took some time, but it's finally there. From tomorrows PreRelease onwards it will be available as `Rename-PnPTenantSite`. Thanks to @gautamdsheth!

**Comment by YuriySamorodov** [comment]
Hi @KoenZomers , appreciate it, You rock!

**Comment by KoenZomers** [comment]
Kudos go to @gautamdsheth for this one 🤗
