### ISSUE TITLE
Get-PnPClientSidePage behaves differently in different tenants

### ISSUE THREAD

**Issue by NishaRaghu** [pnp/powershell#604]
I get an error while running the command  $page = Get-PnPClientSidePage -Identity Startsida
Get-PnPClientSidePage : After parsing a value an unexpected character was encountered: F. Path 'description', line 1, position 224.
At line:1 char:9
+ $page = Get-PnPClientSidePage -Identity Startsida
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPClientSidePage], JsonReaderException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.ClientSidePages.GetClientSidePage

Whereas, the same command in another tenant works fine.

**Comment by veronicageek** [comment]
@NishaRaghu - I've tried on 3 different tenants with v1.5.25 and I have no issue at all. 
Can you retry, or is there any difference between your tenants? Thanks.

**Comment by NishaRaghu** [comment]
@veronicageek Did you have the same permissions on all 3? If so what were yours roles in each? Are there any features that should be enabled? Or any other settings to consider before running the command? I have these modules installed: 
![Modules](https://user-images.githubusercontent.com/6583553/117270448-8153b080-ae59-11eb-8ae3-4facb0c31568.PNG)
Does it depend on the modules installed?

**Comment by veronicageek** [comment]
I was a Global Admin for testing but you may be able to do it with a SharePoint admin (haven't tested). However, you're using the old (and not maintained anymore) SharePoint PnP Module. The new module (this repo) is **PnP.PowerShell**.

documentation to install and authenticate are here: https://pnp.github.io/powershell/articles/installation.html

**Comment by NishaRaghu** [comment]
@veronicageek I tried unsinstalling the old version and installing the PnP.PowerShell from the above link. I still get the same error as follows:
![image](https://user-images.githubusercontent.com/6583553/117807493-fb21da80-b25b-11eb-9e9f-d70c4d675184.png)
Installed version:
![image](https://user-images.githubusercontent.com/6583553/117807699-3d4b1c00-b25c-11eb-9194-83f3fde0edb4.png)
This should probably be due to permissions I guess! The command does not work in my client's environment where I am not a Global Admin

**Comment by veronicageek** [comment]
@NishaRaghu - OK, a few questions:
- Is this the first time you install or use the PnP.PowerShell module in your environment or for that customer?
- Have you run the `Register-PnPManagementShellAccess` prior to connecting?
- How do you connect with `Connect-PnPOnline`?
- What's the 'F' character the error is mentioning?

**Comment by NishaRaghu** [comment]
@veronicageek Extremely sorry for a delayed reply. 
My client has a classic team site and the command did not work for a page in that environment. I tried running the same command connecting to the client's modern site collection and it worked. 
I have uninstalled the old  version and then installed PnP.PowerShell. I haven't run the Register-PnPManagementShellAccess prior to connecting and I use -UseWebLogin while Connecting. The 'F' character is the outcome of the command Get-PnPClientSidePage.

**Comment by veronicageek** [comment]
@NishaRaghu

>I have uninstalled the old version and then installed PnP.PowerShell. I haven't run the Register-PnPManagementShellAccess prior to connecting and I use -UseWebLogin while Connecting

I guess when you said "_I tried running the same command connecting to the client's modern site collection and it worked_" it was not with the PnP.PowerShell (new module) then? Can you confirm?

If this is correct, can you do your steps with the PnP.PowerShell module after running `Register-PnPManagementShellAccess` which is mandatory for this module. We need to make sure that it's installed/configured properly to be able to troubleshoot the issue because I have no problem on my side.

Thanks

**Comment by NishaRaghu** [comment]
@veronicageek I ran the Register-PnPManagementShellAccess before connecting to the client site and tried running the Get-PnPClientSidePage -Identity Startsida but unfortunately i get the same error. Some points i would like to make it clear:

1. The commands works in my development tenant environment when run against a modern team site collection
2. The command works in my clients environment if its a modern team site collection
3. The command does not work in my clients environment if its a classic team site with a modern homepage. Including any subsite.

**Comment by veronicageek** [comment]
@NishaRaghu - I know it's been a while, but can you provide an update please? Thanks.

**Comment by veronicageek** [comment]
Closing as no update.
