### ISSUE TITLE
[BUG] Cannot connect with credentials

### ISSUE THREAD

**Issue by Geigco** [pnp/powershell#61]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets
Connect-PnPOnline is able to connect to SharePoint Online.

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.
Returns error...
Connect-PnPOnline : The sign-in name or password does not match one in the Microsoft account system.

This would be expected with MFA.  However MFA is not enabled here.

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)
$URL = "https://mysite.sharepoint.com"
$login = "user@mysite.com"
$pwd = "secure-password"

$pwd = ConvertTo-SecureString $pwd -AsPlainText -Force;
$credentials = new-object -typename System.Management.Automation.PSCredential -argumentlist $login, $pwd

Connect-PnPOnline -Url $url -Credentials $credentials

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@Geigco - Could you add a title to your issue please?
I have tested on PS7 and PowerShell 5.1 with your steps, and I had no issue connecting. So you may have the wrong credentials as the error suggest (my account was not MFA enabled either)

![PnP_Issue61](https://user-images.githubusercontent.com/25181757/102281059-25c66c00-3f26-11eb-9c56-bbe735e68f4b.png)

Instead of creating a new object, you could just have a one liner by using ```Get-Credential```.

Also, I would suggest changing your variable ```$pwd``` to something else as it is a reserved/built-in variable.

**Comment by Geigco** [comment]
@veronicageek If somebody else posted this, my first response would be "You have to have the username/password wrong".  I've retyped it a few times.

**Comment by Geigco** [comment]
@veronicageek If somebody else posted this, my first response would be "You have to have the username/password wrong".  I've retyped it a few times.

This produces the same issue.
$credentials = Get-Credential
Connect-PnPOnline -Url $url -Credentials $credentials

However, using the -UseWebLogin will connect but not work for automating as somebody will have to manually enter their password.

I have tried on a different small SharePoint site (a $6/month one) and can connect fine.  It makes me think it's a setting of Azure or the tenet but I'm only guessing.

**Comment by erwinvanhunen** [comment]
In this case it's important to know the version of PnP PowerShell that you are using as there is a fundamental difference in how the legacy edition (SharePointPnPPowerShellOnline) and the new version (PnP.PowerShell) handle credential based auth. Could you provide that information?

```powershell
Get-Module -Name "PnP.PowerShell" -ListAvailable
```
Then try
```powershell
Get-Module -Name "SharePointPnPPowerShellOnline" -ListAvailable
```

If you get results for both entries, make sure first to uninstall SharePointPnPPowerShellOnline:

```powershell
Uninstall-Module -Name SharePointPnPPowerShellOnline -AllVersions -Force
```

**Comment by erwinvanhunen** [comment]
Hi! When you install the latest SharePointPnPPowerShellOnline and run Connect-PnPOnline you will receive a notification of this fact the we will sunset it. To make sure as many people as possible got the news we have been announcing this several times also in the community calls, but we understand that not everyone has the ability to attend those. As of January 2021 we will not release any new version of SharePointPnPPowerShell2013/2016/2019/Online and focus only on PnP.PowerShell. Maintaining 4 versions was simply too much work given the issues/changes/etc. given the fact that we do this all in our free time.

PnP.PowerShell is the new version (which is works cross-platform and as a result also in the latest versions of Azure Functions etc.), and we do support 'classic' auth by means of the -UseWebLogin parameter on Connect-PnPOnline:

```powershell
Connect-PnPOnline -Url <yoururl> -UseWebLogin
```

Using -UseWebLogin is effectively using cookie based auth. There are some functional limitations to this though. That's we we recommend other types of authetication.

Due to the fact that Microsoft changed the underlying SDKs and removed the ability to login into SharePoint Online from code by only using credentials we had to also change the approach in PowerShell. This classic auth with username and password is also regarded as 'legacy' by Microsoft. New SharePoint Online tenants have this authentication functionality turned of from day 1. (You can enable/disable it with Set-PnPTenant/Set-SPOTenant). 

So given that we cannot login with username/password anymore we implemented OAuth based / Azure AD Application ID based authetication. That is the PnP Management Shell application. It's basically a registration in a tenant we own that has been marked as a multi-tenant application. When using it on PowerShell using the `Register-PnPManagementShellAccess` cmdlet you will get a registration in your Azure AD stating that people in your tenant can login using that Application ID (and their username/password) and with the permissions stated for that application. When you run the Register-PnPManagementShellAccess cmdlet you will have to consent to the permissions which is quite a list, basically : access to everything.  The user interface will show the list of permissions. However, one still has to login with username/password, using the PnP Management Shell clientid is not enough. The app will basically act as the user logging into to access the resources.

**Comment by Geigco** [comment]
Let me start out by setting the tone.  It's "thankful".

It appears that you are doing everything in your power to spread the information.  My issue stems from Google searches that take you to a Microsoft.com page that is outdated.  Secondly, the old routines work on my $6/month SharePoint Online site but not my client's 10,000 user tenet.  Again, not your fault.

Thank you for the information!

With "Azure AD Application ID based" it sounds like you grant rights to the "App Registration".  This sounds like the same thing that is going on in the "Register-PnPManagementShellAccess".  Do I have that right?  If so, it sounds like using an Application token is the way to go.

**Comment by erwinvanhunen** [comment]
That is 100% correct. Register-PnPManagementShellAccess basically adds a registration to the Azure AD of the tenant for the PnP Management Shell multi-tenant app registration.

**Comment by Geigco** [comment]
@erwinvanhunen Thank you!  This makes everything clear now.  There is no bug here!

If somebody else is reading this in the future, let me explain what happened.  This is what I've learned.

More or less, in previous versions of SharePoint you could use Connect-PnPOnline (or CSOM) to connect to your SharePoint application using only a username/password.  If you currently "Google" (December of 2020) how to connect to SharePoint you are in fact taken to Microsoft's Connect-PnPOnline.  However, Google isn't always correct.  That page is a bit outdated.  I won't share the link here because I don't want to continue to link to an old resource.

More recently Microsoft has changed some big things.  They have open sourced the PnP project.  Microsoft has also pushed heavily for MFA authentication.  Logging into SharePoint via PnP with just a username/password combination goes against current security practices.

To work with these changes have to take extra steps.  If you are building C# application to connect to SharePoint you can create an "Application Registration" in Azure Active Directory.  There are a couple more steps here but essentially this Registration has an App-ID.  You can use this App-ID, along with users credentials (Username&Password) to connect to your SharePoint services.  You can set the App to have maximum credentials.  This limits any program using this application ID to have the lesser of privileges between the user and the App.  Deleting the application registration also essentially cuts off all applications that use that ID.  In a way, this makes the App registration perform similar to a tunnel.  Modifying this permissions of this tunnel/App-Registration will modify what the application can do in SharePoint.  If the application is ever compromised, you can delete/disable the registration and prevent malicious activities.

Likewise, if you are using the PnP script in PowerShell, you will install the modules from the instructions here... 
https://github.com/pnp/powershell

As of the writing of this comment it is important to note that the PowerShell scripts are not officially released.  They work very well but they are currently in beta.

As part of that you will call Register-PnPManagementShellAccess.  This will add an application registration and allow your PowerShell scripts to access all the portions of SharePoint.  Be aware, Register-PnPManagementShellAccess gives a lot of access that you might not need.

**Comment by AnkitSDesai** [comment]
Thanks @erwinvanhunen  for the clarification. One quick question here, I am also trying to do similar thing and when trying to install https://www.powershellgallery.com/packages/PnP.PowerShell/0.3.20-nightly   with the command suggested it seems getting stuck and do not install anything.
Command: Install-Module -Name PnP.PowerShell -AllowPrerelease
Note: I have already tried this with elevated privilege on my machine.

**Comment by erwinvanhunen** [comment]
That sounds more like a network issue or a general PowerShell issue. The install-module cmdlet is not built by us but comes with the PowerShellGet module. https://github.com/powershell. It's hard to see what is causing that from our side.

**Comment by AnkitSDesai** [comment]
Thanks. Here is what I faced when tried once more with admin rights on my machine.
![image](https://user-images.githubusercontent.com/11935710/103381085-c2f1da80-4ab8-11eb-8013-bf3343a3d568.png)

**Comment by ToddKlindt** [comment]
Are you in PowerShell 5 or PowerShell 7? $PSVersionTable will tell you.
![image](https://user-images.githubusercontent.com/2659747/103381431-5cb58980-4ab1-11eb-9038-6cab5a12a351.png)
You need 7.x for this module. 

Also, I see you're running x86. You might need the x64 version of PowerShell for this module.

**Comment by veronicageek** [comment]
@AnkitSDesai - You are on windows PowerShell (5.1) so you can;t have the -AllowPrerelease parameter. Can you try on PS7 because I have no issues on my side

![image](https://user-images.githubusercontent.com/25181757/103381524-f6962a00-4ae3-11eb-8175-99a510b746a9.png)

**Comment by AnkitSDesai** [comment]
@ToddKlindt  yes I just tried with Powershell 7.x and it still seems getting stuck after accepting to install.(A or Y)
Have tried few times but no luck.
![image](https://user-images.githubusercontent.com/11935710/103413293-e95e5700-4b46-11eb-9a81-021b1dce7d44.png)

**Comment by AnkitSDesai** [comment]
@veronicageek .please find following snapshot for my PS 5.x version.
![image](https://user-images.githubusercontent.com/11935710/103413452-989b2e00-4b47-11eb-83c8-a7e37cc757fd.png)

**Comment by veronicageek** [comment]
@AnkitSDesai - I'd like the version of the ```PowerShellGet``` module please.
You can get it by typing ```Get-Module | Where-Object {$_.Name -eq "PowerShellGet" }```

![image](https://user-images.githubusercontent.com/25181757/103413683-81256a80-4b72-11eb-85e1-036742d7919e.png)

**Comment by AnkitSDesai** [comment]
@veronicageek  doesn't show me anything for the command above(Get-Module | Where-Object {$_.Name -eq "PowerShellGet" }). both for powershell 5.x (first )and PS 7.x second
![image](https://user-images.githubusercontent.com/11935710/103415458-28dd7100-4b50-11eb-8622-f9a1ae81821a.png)


7.x
![image](https://user-images.githubusercontent.com/11935710/103415510-604c1d80-4b50-11eb-8946-1e22faf88638.png)

**Comment by veronicageek** [comment]
@AnkitSDesai - Could you please install it?
https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget?view=powershell-7.1

And then try again for the PnP/PowerShell module. 
Thanks

**Comment by AnkitSDesai** [comment]
@veronicageek . it seems now throwing this error. FYI we do not have any proxy as such which might block.
Do you think I can have it installed it by .exe way if we have one.?

![image](https://user-images.githubusercontent.com/11935710/103417653-89bd7700-4b59-11eb-86dc-eec191ff46b9.png)

Thanks!

**Comment by veronicageek** [comment]
As we don't know about the configuration of your environment, the only other thing I can think of is if you've ever registered the PowerShell Gallery as a trusted repository on this machine? Have you succeeded in installing any other module with the ```Install-Module``` command?

Like @erwinvanhunen mentionned earlier in the thread, this might seem more like a network issue on your side, or something else missing, but not a PnP PowerShell.

Try to run ```Find-PackageProvider -Name "Nuget" -AllVersions``` 
https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5743

Also you can have a look at the following documentation:
https://docs.microsoft.com/en-us/powershell/module/powershellget/register-psrepository?view=powershell-7.1
https://docs.microsoft.com/en-us/powershell/module/packagemanagement/install-packageprovider?view=powershell-7.1

If still not working, maybe open an issue on their repo so they can guide you.
https://github.com/NuGet/Home

**Comment by rohit404404** [comment]
@Geigco  @erwinvanhunen  Thanks a lot to both for a great discussion around the new credentials topic.
I have a simple questions for MFA enabled tenant/accounts

1. who has authority to run  Register-PnPManagementShellAccess command in tenant . I am guessing, only sharepoint tenant admin can provide consent on behalf of Tenant?  So we must convince them how its not a security risk, even though it gives full access everywhere.
2. If Tenant admin doesnt allow  Register-PnPManagementShellAccess command and If i must use PnP.Powershell command in Automated application (Task scheduler, Release pipeline) what are my options. -UseWeblogin/-interactive needs human intervention. 
3. If Tenant admin does allow  Register-PnPManagementShellAccess command, is it right that I can automate application with no Human intervation by harcoding Username and Password (even with MFA)
4. What is the least access way to automate using modern authenticaiton in PnP.Powershell .
