### ISSUE TITLE
[BUG] Set-PnPList: Access denied. You do not have permission to perform this action or access this resource

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#610]
### Reporting an Issue or Missing Feature
I am reporting a bug

### Expected behavior 
`Set-PnPList -Identity 'Style Library' -EnableVersioning:$true -MajorVersions 20 -MinorVersions 0` should change versioning settings for a library.

### Actual behavior 
`Set-PnPList -Identity 'Style Library' -EnableVersioning:$true -MajorVersions 20 -MinorVersions 0` produces an error 
> Set-PnPList: Access denied. You do not have permission to perform this action or access this resource.

Replicable for:

- PnP Management Shell
- In-House Azure App Registration

Happens even though:

- I am assigned SharePoint Online Administrator role
- I am a Site Collection Administrator
or 
- An app I am connecting with is granted `Sites.FullControl.All` application permissions

![image](https://user-images.githubusercontent.com/5260172/115785160-c5f63b00-a3c7-11eb-89c5-0c7a406fdd6e.png)

Error occurs for many system libraries, not only 'Style Library'

At the same time I can change version count in UI no problem:
![image](https://user-images.githubusercontent.com/5260172/115785363-035ac880-a3c8-11eb-91a9-f12629dcfa8a.png)

### Steps to reproduce behavior
```
Connect-PnPOnline -Url https://contoso.sharepoint.com/sites/some-site -PnPManagementShell
$lists = Get-PnPList
foreach ( $list in $lists ) {
    if ( $list.MajorVersionLimit -gt 20 ) {
        Set-PnPList -Identity $list.id -MajorVersions 20 -MinorVersions 0 -EnableVersioning:$true
    }
}
```

### What is the version of the Cmdlet module you are running?
```
Name                   : PnP.PowerShell
Version                : 1.5.19
DotNetFrameworkVersion : 4.6.1
PowerShellHostVersion  : 7.1.1
PowerShellVersion      : 5.1
```
### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@YuriySamorodov - I can reproduce that simply connecting to a site with "normal" creds, and it's coming from the 'Style Library', otherwise it updates correctly for the other libraries.

Can you run:
```powershell
$site = Get-PnPTenantSite "https://<tenant-name>.sharepoint.com/sites/<your-site>"
$site.DenyAddAndCustomizePages
```

**Comment by veronicageek** [comment]
As a matter of fact, once you "_Allow users to run custom script on self-service created sites_", it works for the 'Style Library', and the output of the `$site.DenyAddAndCustomizePages` should return `Disabled`.

**Comment by YuriySamorodov** [comment]
Thanks @veronicageek
