### ISSUE TITLE
[FEATURE] Additional Azure App Permissions Documentation Needed

### ISSUE THREAD

**Issue by robertcaretta** [pnp/powershell#611]
**Is your feature request related to a problem? Please describe.**
Can you document what Azure App permissions are required to run this command "Get-PnPFlowEnvironment"? Our environment requires us to start with minimal set of permissions. From a security perspective we need this documented for each cmdlet.

This is what we have to start...
![image](https://user-images.githubusercontent.com/1613085/115788263-01bde000-a389-11eb-84f7-422a2660834a.png)

This is the error I receive...
![image](https://user-images.githubusercontent.com/1613085/115788277-071b2a80-a389-11eb-818b-cc63eac25b52.png)

**Describe the solution you'd like**
I need a list of permissions required to run this command, so I can put in a require with our security team. 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by erwinvanhunen** [comment]
We added the documentation for the cmdlets. You require the permission `management.azure.com`

**Comment by robertcaretta** [comment]
@erwinvanhunen - Sorry where I would find that documentation? I reviewed these two pages.
https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpflowenvironment?view=sharepoint-ps
https://pnp.github.io/powershell/cmdlets/Get-PnPFlowEnvironment.html

**Comment by veronicageek** [comment]
@robertcaretta - It will be available in the next v1.5.23-nightly tomorrow.

**Comment by erwinvanhunen** [comment]
Correct. The documentation will be automatically updated on the PnP Site (e.g. the second link you posted) during our nightly build process.

**Comment by robertcaretta** [comment]
Got it. Thank you.
