### ISSUE TITLE
[BUG] Set-PnPUserProfileProperty : Access denied when set property for user

### ISSUE THREAD

**Issue by matsla** [pnp/powershell#612]
Account running script has global admin rights. It's possible to update the property for current user executing the script, but access denied when try to update a property for a different account.

Set-PnPUserProfileProperty -Account $accountName -PropertyName "SPS-Birthday" -Value "2021-01-01"

Set-PnPUserProfileProperty : Access denied. You do not have permission to perform this action or access this resource.
At \\Mac\Home\Desktop\Reset-UserProfiles.ps1:25 char:13
+             Set-PnPUserProfileProperty -Account $p.AccountName -Prope ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPUserProfileProperty], ServerUnauthorizedAccessException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.UserProfiles.SetUserProfileProperty

PnP Management Shell application has been granted correct permissions in Azure AD 

### What is the version of the Cmdlet module you are running?
V1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@matsla - To give you an update, this is not an issue with PnP PowerShell but has to do with how SharePoint Online handles authorization. We provided Microsoft with this feedback and are waiting for them to reply on it. We have no ETA when that will happen.

Note: Also related to issue #277.

**Comment by gautamdsheth** [comment]
Closing this as it is a duplicate and we are tracking it in #277
