### ISSUE TITLE
Please add a -RowLimit parameter to Get-PnPFolderItem

### ISSUE THREAD

**Issue by ytrezq** [pnp/powershell#616]
Well, in my folder with 10000 files, any attempt to use the command results in

    PS /home/liveuser> Get-PnPFolderItem -FolderSiteRelativeUrl 'Documents/OpenEthereum/ethereum/db/906a34e69aec8c0d/archive/db' -ItemType Folder
    Get-PnPFolderItem: L’opération tentée est interdite, car elle dépasse le seuil d’affichage de liste.

which means it works on too many files to work. In order to fix this, I would need to ask `Get-PnPFolderItem` to work on fewer files which is not supported.

**Comment by veronicageek** [comment]
@ytrezq - If you are after your files or your folders, you can use `Get-PnPListItem` and use the `-PageSize` parameter.
Have a look at issue #479 where I shared a script snippet.

**Comment by ytrezq** [comment]
@veronicageek Mais ou est `-PageSize` dans la documentation de `Get-PnPListItem`? es-ce que ça signifie qu’il faut l’ajouter?

**Comment by veronicageek** [comment]
Oui, comme example 7 dans la [documentation](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnplistitem?view=sharepoint-ps)

![image](https://user-images.githubusercontent.com/25181757/115923843-c7cb0780-a476-11eb-8973-795533129a81.png)

**Comment by ytrezq** [comment]
@veronicageek ah oui. Mais je ne pas restreindre le résultat au contenu d’un dossier OneDrive spécifique en spécifiant le chemin de ce dernier en paramètre. Ce qui est normal vu que cette commande n’a pas le même rôle.

Il faut donc modifier la commande  `Get-PnPFolderItem`.

**Comment by veronicageek** [comment]
As this is a widely used repository and also for future viewers, we need to speak in english please 😉

>Il faut donc modifier la commande Get-PnPFolderItem

We haven't seen a scenario yet where it was needed, unless `Get-PnPListItem` really cannot solve your problem.

>Get-PnPFolderItem -FolderSiteRelativeUrl 'Documents/OpenEthereum/ethereum/db/906a34e69aec8c0d/archive/db'

This doesn't look like a ODFB URL... What are you trying to achieve exactly? Get the list of your 10.000 files from a folder?
Can you provide a bit more context?
