### ISSUE TITLE
[BUG] Get-PnPFlow - Not pulling flows accurately

### ISSUE THREAD

**Issue by robertcaretta** [pnp/powershell#617]
### Reporting an Issue or Missing Feature
Get-PnPFlow cmdlet is not accurately pulling all of the flows for an environment. 

### Expected behavior 
When running the cmdlet with the -AsAdmin switch I would expect to see ALL flows for the environment.

### Actual behavior 
Get-PnPFlow cmdlet is not accurately pulling all of the flows for an environment. Also it pulls different amounts of flows depending on if the -AsAdmin switch is used. In both cases, the returned results are incomplete. We are testing against a test environment and there are over 50+ flows in our "Default" environment. 

Admin accounts being used with Connect-PnPOnline have the Azure roles of SharePoint Admin, Power Platform Admin, Teams Admin, Exchange Admin, etc.  We have tested this behavior with 2 different admin accounts and the behavior is repeatable. 

The Azure enterprise application being used is the default "PnP Management Shell" with full permissions. This was created by running [Register-PnPManagementShellAccess](https://pnp.github.io/powershell/articles/authentication.html). 

### Steps to reproduce behavior
1) Connect-PnPOnline -Url "https://TESTTENANT-admin.sharepoint.com"
2) $ctx = Get-PnPConnection
    Get-PnPFlowEnvironment -Connection $ctx
3) Get-PnPFlow -Environment 'Default-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx' -AsAdmin

Output WITHOUT the -AsAdmin switch
![image](https://user-images.githubusercontent.com/1613085/115926679-dbf81000-a448-11eb-9d13-3efe2a4157a4.png)

Output WITH the -AsAdmin switch
![image](https://user-images.githubusercontent.com/1613085/115926830-1792da00-a449-11eb-8d8c-6c05f4beac19.png)

### What is the version of the Cmdlet module you are running?
1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by robertcaretta** [comment]
Ping. Not a stale issue. Keep open please.

**Comment by robertcaretta** [comment]
Not stale. Keep open.

**Comment by robertcaretta** [comment]
Not stale. Keep open.

**Comment by robertcaretta** [comment]
Not stale. Keep open.

**Comment by KoenZomers** [comment]
Looking into this one

**Comment by KoenZomers** [comment]
Can reproduce. Found the problem. Fixing it.

**Comment by KoenZomers** [comment]
Fixed in PR https://github.com/pnp/powershell/pull/1136. You can test this after this PR has been merged and the next night has passed with the latest nightly build. Assuming this issue to be resolved by it. If not, feel free to reopen this issue.

**Comment by robertcaretta** [comment]
@KoenZomers - This does not appear to be fixed. Here are the results of my latest test and I did make sure to upgrade to latest 1.7.0 version and import that version of the module,  I am using VS Code with Powershell 7.1.

![2021-09-27_16-31-31](https://user-images.githubusercontent.com/1613085/134988749-6ee9baab-d77a-4a00-8408-d4540ccdf344.png)

![2021-09-27_16-32-34](https://user-images.githubusercontent.com/1613085/134988756-e8e3443e-5102-4ad5-bc34-afaa7d0e9527.png)

**Comment by veronicageek** [comment]
@robertcaretta - You need to update to the prerelease (e.g. 1.7.63). When we release the major 1.8.0 it'll be included, but for now, you get fixes only by updating to prereleases.

**Comment by robertcaretta** [comment]
This does indeed look much better! I validated the record counts against the CoE dashboard and it lines up now.
