### ISSUE TITLE
[BUG] Set-PnPListItemPermission -InheritPermissions unexpectedly breaks inheritance

### ISSUE THREAD

**Issue by felixoctavian** [pnp/powershell#618]
### Reporting an Issue
The -InheritPermissions parameter of the Set-PnPListItemPermission cmdlet breaks inheritance for any item that is already inheriting permissions from its parent.

### Expected behavior 
All list item permissions are cleared and reset to inherit from the parent, per documentation at https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnplistitempermission?view=sharepoint-ps

### Actual behavior 
List items with unique permissions have permissions cleared and are reset to inherit from the parent as expected, but list items already inheriting from the parent have inheritance broken and are given unique permissions.

### Steps to reproduce behavior
Run the following command against a document library that contains a mix of files with inherited and unique permissions:
Get-PnPListItem -List Documents | Set-PnPListItemPermission -List Documents -InheritPermissions

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 1.5.0 in PowerShell 7.1.3

### Which operating system/environment are you running PnP PowerShell on?
Windows

### Workaround
Get-PnPListItem -List Documents | ForEach-Object { if (Get-PnPProperty -ClientObject $_ -Property HasUniqueRoleAssignments) { $_ | Set-PnPListItemPermission -List Documents -InheritPermissions } }

**Comment by erwinvanhunen** [comment]
Very good catch! We just merged a fix for this issue and it will be available in the 1.5.26-nightly release tomorrow. 

To install that version:

```
Install-Module -Name PnP.PowerShell -AllowPrerelease
```

To update to a specific version

```powershell
Install-Module -Name PnP.PowerShell -AllowRerelease -RequiredVersion 1.5.26-nightly
```
