### ISSUE TITLE
New-PnPSite Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by SharePointOz** [pnp/powershell#621]
I'm using v1.5 of the PnP.Powershell module. When I try to create a new site using these commands:

```
Connect-PnPOnline -Url https://<tenant>.sharepoint.com -UseWebLogin 
New-PnPSite -Type TeamSite -Title "Test Team" -Alias "testteam"
```

I get this error:
New-PnPSite: Object reference not set to an instance of an object.

**Comment by veronicageek** [comment]
@SharePointOz - Can you let us know if you still have the issue with the `-nightly` release. Thanks.

**Comment by SharePointOz** [comment]
![image](https://user-images.githubusercontent.com/15919270/119429776-e57bdd00-bd52-11eb-8b87-4e03d28fd66f.png)
Getting a different error this time:

```
New-PnPSite : GetAccessTokenAsync() called without an ACS token generator. Specify in AuthenticationManager
constructor the authentication parameters
At line:1 char:1
+ New-PnPSite -Type TeamSite -Title "Test Team" -Alias "testteam"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [New-PnPSite], ArgumentException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.NewSite
```

**Comment by veronicageek** [comment]
@SharePointOz - Can you please update the module (if not already - `1.5.60-nightly`) and try with `-Interactive` as recommended. I had no issue on my side.

![image](https://user-images.githubusercontent.com/25181757/120359974-2bf7ab80-c300-11eb-889b-c27ad6c61c55.png)
