### ISSUE TITLE
[BUG] ConvertTo-PnPPage doesn't work when source library has more than 5000 items

### ISSUE THREAD

**Issue by darthbazi** [pnp/powershell#625]
Hello everyone, 

I receive the following error message when I try to convert a page inside of a library with 5000+ items

> 
> ... tSidePage = ConvertTo-PnPClientSidePage -Identity $sourcePageName -Li ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : WriteError: (:) [ConvertTo-PnPPage], FileNotFoundException
>     + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Pages.ConvertToClientSidePage
> ConvertTo-PnPClientSidePage : Could not find file 'PnP.Framework.resources'.
> At C:\Users\..\OneDrive -...\Development\20201202-...-PnPMigration\ConvertClassicToModern_withFileAsParameter.ps1:114 char:32
> + ... tSidePage = ConvertTo-PnPClientSidePage -Identity $sourcePageName -Li ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : WriteError: (:) [ConvertTo-PnPPage], FileNotFoundException
>     + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Pages.ConvertToClientSidePage
> 

Unfortunately there are no other error information this script returns.
Same script works with the same list when I delete items and reduce the count below 5000.

----------
Edit : It seems, Add-PnPPage also doesn't work in the same case. Page has been created but shown like this : 
![image](https://user-images.githubusercontent.com/83215551/116116408-6b0c5e80-a6bb-11eb-97df-20c257ece534.png)

> Message          : Object reference not set to an instance of an object.
> Stacktrace       :    at PnP.Core.Model.SharePoint.Page.<SaveAsync>d__128.MoveNext()
>                    --- End of stack trace from previous location where exception was thrown ---
>                       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>                       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>                       at PnP.Core.Model.SharePoint.Page.Save(String pageName)
>                       at PnP.PowerShell.Commands.Pages.AddPage.ExecuteCmdlet()
>                       at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()
> ScriptLineNumber : 1

-------------------

Thanks in advance

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 1.4.0

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@darthbazi - Have a look at this [official documentation](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-powershell) + script which deals with 5000+ items using `-PageSize`.

**Comment by darthbazi** [comment]
@veronicageek  Firstly, thanks for the info. It is interesting that the example code you sent uses the page id as `-Identity`-parameter with the `ConvertTo-PnPPage`.  It is not documented in the [Sharepoint PnP documentation](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/convertto-pnppage?view=sharepoint-ps), and here it explicitly says that we should use page name for this parameter. I will try again using IDs instead of names.
