### ISSUE TITLE
[BUG] Add-PnPFile not setting Modified & Created dates on list item for uploaded file

### ISSUE THREAD

**Issue by saltzimania** [pnp/powershell#627]
### Reporting an Issue or Missing Feature
Issue when uploading a file with Add-PnPFile, values for Modified & Created are ignored.
[The reference indicates explicitly in examples 3-6 that this should be supported](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnplistitem?view=sharepoint-ps)

The issue appears to be identical to [this issue in the legacy PnP Module](https://github.com/pnp/PnP-PowerShell/issues/1550)

I looked in the respective command files in the modern version to see if the fixes from the legacy version fixed for issue 1550 exist but cannot find use of UpdateOverwriteVersion which I think may be required for resolution.

### Expected behavior 
Modified and created dates to be set to the values passed in the -Values parameter hashtable

### Actual behavior 
Modified and created dates are set to current time

### Steps to reproduce behavior
PS > Add-PnPFile -Path $path -Folder $folder -Values @{Modified="1/1/2018"; Created="1/1/2017"}
also tried
PS > Add-PnPFile -Path $path -Folder $folder -Values @{Modified=[datetime]"1/1/2018"; Created=[datetime]"1/1/2017"}
and
PS > Add-PnPFile -Path $path -Folder $folder -Values @{Modified=[datetime]::Parse("1/1/2018"); Created=[datetime]::Parse("1/1/2017")}

### What is the version of the Cmdlet module you are running?
Can reproduce the issue in both 1.3.0 and 1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@saltzimania - Indeed, it's not updating with `Add-PnPFile`, but as a workaround you can use the `Set-PnPListItem`

![image](https://user-images.githubusercontent.com/25181757/116297111-dc6b1080-a792-11eb-876e-964098a9b9b9.png)

I see you mentioned it's not working on v1.3.0 & v1.5.0. Does it mean it works on 1.4.0?

FYI - @gautamdsheth / @erwinvanhunen

**Comment by saltzimania** [comment]
Thanks @veronicageek, I was experiencing the issue on 1.3 and tried updating to 1.5 to see if that resolved.  I did not try 1.4.

Yes, I was looking into Set-PnPListItem as a workaround last night.  As this is being used in a migration script to ingest hundreds of thousands of records from a legacy EDRMS into SPO, the performance hit is not ideal.  Thanks for the quick reply!

**Comment by gautamdsheth** [comment]
Added a fix, will be available in the next nightly tomorrow.

**Comment by saltzimania** [comment]
@gautamdsheth thanks, this is working perfectly now! <3
