### ISSUE TITLE
[BUG] Add-PnPHubToHubAssociation : The method or operation is not implemented.

### ISSUE THREAD

**Issue by ahyland** [pnp/powershell#628]
### Expected behavior 
Currently when running:

`Add-PnPHubToHubAssociation -Source "510ad510-8fe8-4542-8713-000000" -Target "b4a17b54-ca7f-4891-8bac-000000"`

or

`Add-PnPHubToHubAssociation -SourceUrl "https://tenant.sharepoint.com/sites/hub1" -TargetUrl "https://tenant.sharepoint.com/sites/hub2"`

### Actual behavior 
I get the following error:

> Add-PnPHubToHubAssociation : The method or operation is not implemented.
> At line:1 char:1
>  Add-PnPHubToHubAssociation -Source "510ad510-8fe8-4542-8713-000000 ...
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>CategoryInfo          : WriteError: (:) [Add-PnPHubToHubAssociation], ServerException
> FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Admin.AddHubToHubAssociation

### Version
Currently using version 1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Hi, this feature is available for tenant's in preview only. 
It is not supported generally. 
Once this feature is available generally, this command will start working.

**Comment by ahyland** [comment]
Thanks @gautamdsheth , any idea when this will be available generally?
