### ISSUE TITLE
[BUG] Connect-PnPOnline Interactive permissions

### ISSUE THREAD

**Issue by fonbrauzen** [pnp/powershell#629]
### Reporting an Issue
Not sure if this related to PowerShell or something beneath, when I try to update list item (Set-PnPListItem) I receive "access denied" if I connect with Interactive option and no issues when UseWebLogin. Therefore either it should be possible to grant permissions or something need to be fixed.

### Expected behavior 
Interactive have same permissions as UseWebLogin

### Actual behavior 
access denied error
Message          : Access denied. You do not have permission to perform this action or access this resource.
Stacktrace       :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
                      at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
                      at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServerAsync(ChunkStringBuilder sb)
                      at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryAsync()
                      at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQueryAsync()
                      at Microsoft.SharePoint.Client.ClientContext.ExecuteQueryAsync()
                      at
                   Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext
                   clientContext, Int32 retryCount, String userAgent)
                      at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext
                   clientContext, Int32 retryCount, String userAgent)
                      at PnP.PowerShell.Commands.Lists.SetListItem.ExecuteCmdlet() in
                   c:\PnPPowerShell\src\Commands\Lists\SetListItem.cs:line 167
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in
                   c:\PnPPowerShell\src\Commands\Base\PnPSharePointCmdlet.cs:line 60
ScriptLineNumber : 1
### Steps to reproduce behavior
Set-PnPListItem ...

### What is the version of the Cmdlet module you are running?
1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows, PS v7.1.3
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@fonbrauzen - No issue on my side with `-Interactive` (I was using v1.5.24)
Can you try on another list? Or try with the latest `-nightly` build.

![image](https://user-images.githubusercontent.com/25181757/116294142-85b00780-a78f-11eb-9fcc-edc0d7f63d04.png)

**Comment by fonbrauzen** [comment]
@veronicageek could you please provide some background what is the difference? Should it be some permissions granted?
1.5.26 on PowerShell v7.1.3
![image](https://user-images.githubusercontent.com/12198462/116304079-71c1d100-a7a2-11eb-9590-970e145ccbaf.png)

**Comment by fonbrauzen** [comment]
from [PnPConnection.cs](https://github.com/pnp/powershell/blob/master/src/Commands/Base/PnPConnection.cs
)
web login:
`var spoConnection = new PnPConnection(context, ConnectionType.O365, null, url.ToString(), tenantAdminUrl, PnPPSVersionTag, InitializationType.InteractiveLogin);`
vs interactive
`var spoConnection = new PnPConnection(context, connectionType, null, clientId, null, uri.ToString(), tenantAdminUrl, PnPPSVersionTag, InitializationType.ClientIDCertificate)`
means should be some app in Azure AD (from which we use client ID + cert) with some permissions, or?

**Comment by veronicageek** [comment]
FYI - @gautamdsheth / @erwinvanhunen

**Comment by gautamdsheth** [comment]
@fonbrauzen - looks like you are not using PnP Management Shell Multi-Tenant Azure AD Application. So, that's why getting access denied error. Please check this article - https://pnp.github.io/powershell/articles/connecting.html and then try connecting after following the steps mentioned there !

Let us know if you are still facing the issue after following the steps mentioned there.

**Comment by fonbrauzen** [comment]
@gautamdsheth  - thx, now it's working.
