### ISSUE TITLE
[BUG] Set-PnPWebPermission: The parameter "Identity" is declared in parameter-set "__AllParameterSets" multiple times.

### ISSUE THREAD

**Issue by matsn0w** [pnp/powershell#63]
Hello there heroes!

I have migrated my scripts to the preview of PnP.PowerShelll this week. After running one, I noticed that the Set-PnPWebPermission cmdlet isn't working at all. Also, the documentation is missing. The page exists, but it shows a copy of the Set-PnPWebPartProperty documentation...

### Expected behavior 
The cmdlet runs :)

### Actual behavior 
- Missing [documentation](https://pnp.github.io/powershell/cmdlets/released/Set-PnPWebPermission.html)
- No auto-complete in the terminal
- An error is thrown, even when the proper parameters are given:
```
 Set-PnPWebPermission : The parameter "Identity" is declared in parameter-set "__AllParameterSets" multiple times.
At line:1 char:1
+ Set-PnPWebPermission -
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], MetadataException
    + FullyQualifiedErrorId : ParameterDeclaredInParameterSetMultipleTimes
```

### Steps to reproduce behavior
```powershell
Connect-PnPOnline -Url https://contoso.sharepoint.com -PnPManagementShell
Set-PnPWebPermission -User me -AddRole Read
```
or
```powershell
Connect-PnPOnline -Url https://contoso.sharepoint.com -PnPManagementShell
Set-PnPWebPermission
```
or
```powershell
Connect-PnPOnline -Url https://contoso.sharepoint.com -PnPManagementShell
Set-PnPWebPermission -Identity someweb
```

### What is the version of the Cmdlet module you are running?
0.3.7

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
good catch! Working on it as we speak.

**Comment by erwinvanhunen** [comment]
Fixed! It will be available in 0.3.13-nightly which will be available tomorrow.

**Comment by matsn0w** [comment]
You rock 👍

**Comment by CunningTech** [comment]
It would be really nice to have the -url parameter back for working with subsites.  Where can I make that request?

**Comment by Suya677** [comment]
I want to grant a user permission so i used following command
#Parameters
$SiteURL = "https://****.sharepoint.com/"
$UserAccount = "Sayuri@****.onmicrosoft.com"
$PermissionLevel = "Edit"
 
#Connect to PnP Online
Connect-PnPOnline -Url https://****.sharepoint.com/ -Interactive   
 
#grant permission Level to the user
Set-PnPWebPermission -User "Sayuri@Sara56.onmicrosoft.com" -AddRole Edit

But eveytime Permission level not found error will occur 
Any idea why i am getting this error although i tried with different permission level such as Contibute, Owner,Member still getting the same error

**Comment by matsn0w** [comment]
> I want to grant a user permission so i used following command #Parameters $SiteURL = "https://**.sharepoint.com/" $UserAccount = "Sayuri@**.onmicrosoft.com" $PermissionLevel = "Edit"
> 
> #Connect to PnP Online Connect-PnPOnline -Url https://****.sharepoint.com/ -Interactive
> 
> #grant permission Level to the user Set-PnPWebPermission -User "[Sayuri@Sara56.onmicrosoft.com](mailto:Sayuri@Sara56.onmicrosoft.com)" -AddRole Edit
> 
> But eveytime Permission level not found error will occur Any idea why i am getting this error although i tried with different permission level such as Contibute, Owner,Member still getting the same error

Check the site language, permission levels are translated for some reason. In my case, my sites are in Dutch so my permissions are also in Dutch.
