### ISSUE TITLE
Error applying tenant template when connecting with access token

### ISSUE THREAD

**Issue by joelfmrodrigues** [pnp/powershell#636]
Hello,

I am getting this error when using PnP.PowerShell, but believe the problem could be in PnP.Framework instead.
Tested with versions 1.3 and 1.5 of PnP.PowerShell

Steps to reproduce:

``` PowerShell
# Connect using app-delegated access
Connect-PnPOnline -Url https://xxxxxx-admin.sharepoint.com/ -ClientId "xxxxxxxxxxxxx" -Credentials (Get-Credential)

# get access token for use when recreating the issue
$token = Get-PnPAccessToken

# validate that everything works using the previous connection - template is correctly applied
Invoke-PnPTenantTemplate -Path .\TestTemplate.xml -Parameters $templateParameters

# disconnect
Disconnect-PnPOnline

# connect using the access token from previous step
Connect-PnPOnline -Url https://xxxxxx-admin.sharepoint.com/ -AccessToken $token

# invoke template again
Invoke-PnPTenantTemplate -Path .\TestTemplate.xml -Parameters $templateParameters
```

Result:
Invoke-PnPTenantTemplate: The remote server returned an error: (401) Unauthorized.

**Comment by gautamdsheth** [comment]
@joelfmrodrigues - any particular reason you want to use accessToken parameter ?

**Comment by joelfmrodrigues** [comment]
@gautamdsheth, unfortunately, this is being imposed by my client and not something they are willing to change. They have a lot of corporate policies in place that make this approach the only possible option to connect

**Comment by joelfmrodrigues** [comment]
As an update, I was able to do some additional testing and removed the tenant elements from the template, and it works when I sue Invoke-PnPSiteTemplate. After that, I can connect using an access token for Graph and execute the required commands to update Teams channel as required.

**Comment by gautamdsheth** [comment]
Interesting, can you tell me what elements did you remove to make it work ? Also, any chance you can try connecting to a normal site instead of admin site and checking, it shouldn't matter but worth a shot as well ? Thanks !

**Comment by joelfmrodrigues** [comment]
@gautamdsheth I also tried to connect to the root site, and also the the site I wanted to apply the SP template, but no luck.
I basically removed the sequence element where I had my site collection defined and also the Teams elements, making it a normal SharePoint site template. This worked with Invoke-PnPSiteTemplate.

**Comment by joelfmrodrigues** [comment]
Thanks @veronicageek for keeping it alive :)
