### ISSUE TITLE
Add-PnPTeamsUser throws Cannot access a disposed object. Object name: 'System.Net.Http.StringContent'.

### ISSUE THREAD

**Issue by asadrefai** [pnp/powershell#642]
### Reporting an Issue or Missing Feature
I am using below command to add an owner into a Team.

Add-PnPTeamsUser -Team "TeamName" -User "Asad@example.onmicrosoft.com" -Role Owner  

I am using Azure App Registration / Thumbprint to Connect-PnPOnline (_Refer the attached screen shot of permissions of App Reg. It does has Graph Group.ReadWrite.All_) 
![ApiPermission](https://user-images.githubusercontent.com/11193596/116730047-e5045680-a9df-11eb-8b73-8f7dd355c28b.png)

### Expected behavior 
Add-PnPTeamsUser -Team "TeamName" -User "Asad@example.onmicrosoft.com" -Role Owner

Above command should successfully add Asad as an owner into a Team.

### Actual behavior 
I get below error

_Cannot access a disposed object. Object name: 'System.Net.Http.StringContent'._

### Steps to reproduce behavior
The error occurs only when Role as Owner is passed and the User does not exist at all in a team, not even as a Member. 
If command is used to add user with a Role as Member, then it works fine. 

**Use Case 1**: Assume user does not exist in a Team. And command is used to add as an owner. The command will throw error, however that particular user is added as a Member (_This is because it is coded that way in AddUserAsync function in file https://github.com/pnp/powershell/blob/master/src/Commands/Utilities/TeamsUtility.cs line number 365_)

**Use Case 2**: Once the command fails, and the user is added as a Member instead of Owner. And immediately I re run the command again to add as an Owner, then it works and change the user Role from Member to Owner. (_I think for this case the condition at line 363 if(!isMember) does not pass and PostAsync is called just once at line 367 in file https://github.com/pnp/powershell/blob/master/src/Commands/Utilities/TeamsUtility.cs hence the Role is changed to Owner if user already exist as a Member. May be the object stringContent is disposed after first PostAsync Call and hence when executing second, it throws error._)

### What is the version of the Cmdlet module you are running?
1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows

**Comment by gautamdsheth** [comment]
Thanks for reporting, looking into this !
You can also try Set-PnPMicrosoft365Group command with owner parameter which does the same thing.

**Comment by gautamdsheth** [comment]
@asadrefai - issue has been fixed. Will be available in tomorrow's nightly as well as next major version. 
Thanks for raising this !
Please reopen this if it happens again.

Thanks again :)

**Comment by asadrefai** [comment]
Thank you @gautamdsheth
