### ISSUE TITLE
[BUG] Set-PnpListItem not working with batch

### ISSUE THREAD

**Issue by robgarrett** [pnp/powershell#644]
I have a hidden field in my list. I can update this value using Set-PnPListItem as long as I DO NOT use batch.
Turning on batch doesn't update the list items in a batch.

### Expected behavior 
Using batch of 10 or less items should update.

### Actual behavior 
Nothing changes in the list items.

### Steps to reproduce behavior
$batch = New-PnPBatch;
$list = Get-PnpList "MyList";
for ($i = 1; $i -le 10; $i++) {
  Set-PnPListItem -Identity $i -List $list -Values @{ fieldName = $i } -Batch $batch -UpdateType UpdateOverwriteVersion;
}
Invoke-PnPBatch $batch;

Tried all of the update types, including removing it.

### What is the version of the Cmdlet module you are running?
1.5.27

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by robgarrett** [comment]
Changed the hidden field to visible, still an issue. I cannot get set-pnplistitem to work in batch at all!

**Comment by veronicageek** [comment]
No problem on my side with using `-batch` and without any `-UpdateType` parameter on 1.5.27-nightly
Can you try on another field? And if it works, what's the difference between the field not updating and the other one?

![image](https://user-images.githubusercontent.com/25181757/116752531-9cf42c80-a9fd-11eb-8c5f-89d7ad406ba2.png)

**Comment by robgarrett** [comment]
Seems to work now. I had a read operation happening with the batch scope (one of the ills of calling a function inside the batch that does some other work in a different scope).
