### ISSUE TITLE
New-PnPWeb fails for Visio Process Repository subsite template name 'VISPRUS#0'

### ISSUE THREAD

**Issue by sathya-bhat** [pnp/powershell#645]
### Reporting an Issue
New-PnPWeb to create a subsite under a site collection fails for enterprise template 'VISPRUS#0'.
The same thing works from Sharepoint Admin UI.

### Expected behavior 
Successful subsite creation.

### Actual behavior 
New-PnPWeb : File or arguments not valid for site template 'VISPRUS#0'.

### Steps to reproduce behavior

```
$SiteURL = "https://x.sharepoint.com/sites/VisioSubsiteCollection"
$conn = Connect-PnpOnline -url $SiteURL -ClientId '1d39cfb1-c1bf-4199-a0d8-9c96774d0710' -ClientSecret 'xxcHmO-eNsQdn=zJ_?B5pCBMaZr968xxy8iI4xx' -ReturnConnection;
$Options =@{
    Connection = $conn
    Title = 'Hello'
    Url = 'VISPRUSSite'
    Template = 'VISPRUS#0'
    Locale = 1033
    ErrorAction = 'Stop'
}
New-PnPWeb @Options

```
### What is the version of the Cmdlet module you are running?
PnP 1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ x] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@sathya-bhat - I'm using version `1.5.27-nightly` and no issue on Windows/MacOS (can't test Linux), and simply tried with "normal" credentials as the error relates to the template code. Could you update and try again? Thanks

![image](https://user-images.githubusercontent.com/25181757/116791081-e56c2280-aaaf-11eb-85fd-464a99978eeb.png)

**Comment by sathya-bhat** [comment]
Thanks Veronica, you are right, when I tried the connection with a user account (of the form admin@tenant.onmicrosoft.com) in Connect-PnpOnline, it works. 
If I do Connect-PnpOnline with an AppGuid and AppSecret, then it fails.

Could you please confirm this?

**Comment by veronicageek** [comment]
FYI - @gautamdsheth / @erwinvanhunen

**Comment by KoenZomers** [comment]
Checking if I can figure out what causes this.

**Comment by KoenZomers** [comment]
Can't seem to figure it out here. With an app + user token (connecting using -Interactive or -DeviceLogin) it works fine, connecting with any kind of app only token fails (-clientid -clientsecret / ACS or -clientid -certificatepath / AAD). You can already see the difference when connecting and running Get-PnPWebTemplates. If it shows the VISPRUS#0 it will work, if not, it will not. Can't reason why with a user context you have access to different webtemplates than with an app only context.

I'm out of options here. @gautamdsheth @erwinvanhunen you guys have any thoughts left?

**Comment by gautamdsheth** [comment]
@sathya-bhat - Looks like an issue with Microsoft, not sure if we can do anything about it.
Tried with pure CSOM as well, surely a server side issue.

Can you raise a ticket with MS about this ?

**Comment by veronicageek** [comment]
Closing if that's a server side issue.
