### ISSUE TITLE
The collection has not been initialized

### ISSUE THREAD

**Issue by AreAyeZee** [pnp/powershell#646]
I keep getting the following error when I attempting to create a new folder and apply permissions to the folder.

format-default : The collection has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.
    + CategoryInfo          : NotSpecified: (:) [format-default], CollectionNotInitializedException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.CollectionNotInitializedException,Microsoft.PowerShell.Commands.FormatDefaultCommand

**Comment by veronicageek** [comment]
@AreAyeZee - Please create the issue with the template provided, cmdlet used, version, etc...Thanks.
