### ISSUE TITLE
[FEATURE] New-PnPTeamsTeam Add boolean parameter for AllowCreateUpdatePrivateChannels 

### ISSUE THREAD

**Issue by rjpc-github** [pnp/powershell#647]
**Is your feature request related to a problem? Please describe.**
The existing parameter AllowCreateUpdateChannels restricts creation for both Private and Public channels. If we want to restrict just for Private channels, there's no way to do it. 

In the Teams UI (Manage Channel > Channel Settings > Permissions) there is currently a tickbox to "Allow members to create private channels". Having the ability to toggle this on/off via PnP is basically what this feature request is all about.

**Describe the solution you'd like**
Adding a boolean parameter like AllowCreateUpdatePrivateChannels for New-PnPTeamsTeam. The flag should toggle the aforementioned Team setting

**Comment by rjpc-github** [comment]
Hi Gautam / M365 Devs, 

Thank you for looking into this feature request. If I may I ask, is this something feasible to develop and being considered to be added in the near future?

More power.

**Comment by gautamdsheth** [comment]
@rjpc-github - Have added a `AllowCreatePrivateChannels` parameter for your feature request. It will be available in the New/Set-PnPTeamsTeam cmdlet in tomorrow's nightly build and ofcourse the next major version whenever it is released. 
Please let me know how it goes whenever you have time to check, thanks :)

To test it, clear and uninstall your existing PnP PowerShell and install the pre-release one as below tomorrow:

`Install-Module -Name PnP.PowerShell -AllowPrerelease`

**Comment by rjpc-github** [comment]
hi Gautam,


I am happy to report that our testing for AllowCreatePrivateChannels for both the New/Set-PnPTeamsTeam cmdlets are successful. I have tested using the v1.5.53.

Thank you for continued support.

Regards,
Raymond

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by rjpc-github** [comment]
hi Gautam, 

We've been testing v1.6.0 for New/Set-PnPTeamsTeam for this particular feature request. Has this been included in the said version?
