### ISSUE TITLE
[BUG] Connect-PnPOnline cannot connect to USGovernment Cloud

### ISSUE THREAD

**Issue by steve-boyle** [pnp/powershell#65]
### Reporting an Issue or Missing Feature
Trying to connect to a GCC High instance in the USGovernment cloud, using an application registration with private certificate, Connect-PNPOnline returns the following error:
Connect-PnPOnline: AADSTS900382: Confidential Client is not supported in Cross Cloud request.

I'm calling Connect-PnPOnline as follows, with actual values for ClientId, Tenant, and Thumbprint:
Connect-PNPOnline -ClientId 00000000-0000-0000-0000-000000000000 `
-Url https://tenant.sharepoint.us `
-Tenant tenant.onmicrosoft.us `            
-Thumbprint 0000000000000000000000000000000000000000 `
-AzureEnvironment USGovernment

That last param makes no difference, can't seem to tell it to use the Gov cloud.

### Expected behavior 
I would expect the connection to succeed.

### Actual behavior 
Connect-PnPOnline: AADSTS900382: Confidential Client is not supported in Cross Cloud request.

### Steps to reproduce behavior
Create a private certificate.
Import into Local and User Certificate store
Create App Registration in Azure AD, include certificate from above.
Assign API permissions and Grant them.
Try to connect from Connect-PnPOnline

### What is the version of the Cmdlet module you are running?
Manifest   0.3.14     nightly    PnP.PowerShell   Core,Desk {Get-PnPSubWebs, Initialize-PowerShellA…

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
We committed a -possible- fix (we don't have access to a US Government cloud instance to the PnP Framework which we use behind the scenes. The nightly release of tomorrow (0.3.17-nightly) of PnP PowerShell will contain this fix.

**Comment by steve-boyle** [comment]
Thank you very much for the quick turn-around, I sincerely appreciate your work here.  I will try your change once 0.3.17 is available.

**Comment by steve-boyle** [comment]
I believe that the change works, at least as far as Connect-PnPOnline completes and Get-PnPConnection returns a connection object.  

Though I am passing -AzureEnvironment USGovernment, what I see from Get-PnPConnection is:
AzureEnvironment                       : Production

If I try Copy-PnPFile or Find-PnPFile I get an authorization error:
The remote server returned an error: (401) Unauthorized.

Now that could still be on my end, GCC High has its own idiosyncrasies.  Though I believe that the permissions are all in place.

**Comment by erwinvanhunen** [comment]
let me check the internals again. We might have missed something there.

**Comment by erwinvanhunen** [comment]
A bit later today we will release a new build of PnP PowerShell where I fixed some things regarding the setting of the AzureEnvironment. Not 100% sure if this will affect you though, but if you can, please check. Does Get-PnPList works? It's a pretty basic call. If it still fails, what would greatly help is a Fiddler trace of the failing request.

**Comment by steve-boyle** [comment]
What is the best way to share a private Fiddler trace with you?

In fiddler, when I connect I see it connecting to http://login.microsoftonline.us:443 with a 200 response.  When I run Get-PnPList, I see it connect to http://<tenant>.sharepoint.us:443, again with a 200 response.  Though Get-PnPList returns a 401 Unauthorized. 

Thank you!

**Comment by steve-boyle** [comment]
Hello, I'm attaching a screen shot form Fiddler.  Tried to not capture my proprietary info.  Looks like maybe the request is malformed, missing something?

Thank you!

![pnp4](https://user-images.githubusercontent.com/38572478/103699817-5e22fe00-4f58-11eb-8596-2f2d4b9d526e.PNG)

**Comment by erwinvanhunen** [comment]
The most important  is actually what is happening in the headers (e.g is there a correct bearer token in there etc). Do you have a twitter account? If so, ping me there on @erwinvanhunen, alternatively contact me on linkedin. I can share my private email address with you then.

**Comment by steve-boyle** [comment]
Thank you for following up with me.  Looking like I am down to a permissions issue at this point.  In GCC High they seem to have removed the Sharepoint permissions and replaced them with Graph permissions for applications.  But also in GCC High most of the Graph functions are disabled. Waiting to hear back from MS, it may be that this does not work in GCC High right now - or only works in an interactive session with -UseWebLogin as a user with the right permissions.  The -UseWebLogin option or this application/certificate style are the only ways to authenticate in GCC High.  As I'm trying to automate a process -UseWebLogin is not a great option for me.  I'll keep you posted as I learn more.

As always, your effort is greatly appreciated.

**Comment by steve-boyle** [comment]
Microsoft finally confirmed that the permissions that I need to copy files in Sharepoint have been removed in the GCC High environment.  I believe that PnP is doing the right thing here now.  The lack of permissions prevents me from accomplishing my goals.  Feel free to close this issue.  Thank you so much for you assistance.
