### ISSUE TITLE
[BUG] Get-PnPListItem - PageSize Does Not Work when Query is specified

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#651]
### Reporting an Issue or Missing Feature
I am reporting a bug

### Expected behavior 
`Get-PnPListItem` should process `-Query` and `-PageSize` parameters correctly if both are included. Otherwise, those should be in different parameter sets.

### Actual behavior 
It looks like Get-PnPListItem seems to be ignoring PageSize when Query is specified.
I keep getting `Get-PnPListItem: The attempted operation is prohibited because it exceeds the list view threshold.` error
![image](https://user-images.githubusercontent.com/5260172/58249847-9916f480-7d68-11e9-829d-1f58e1389f85.png)

However, if I run ```Get-PnPListItem -ListName $ListName -PageSize 5000``` it works just fine and returns correct item count:
![image](https://user-images.githubusercontent.com/5260172/58249923-cf547400-7d68-11e9-93fa-d99328f1ae15.png)

This is in fact an old issue:
https://github.com/pnp/PnP-PowerShell/issues/2143
https://github.com/MicrosoftDocs/office-docs-powershell/issues/3457

### Steps to reproduce behavior
```
Connect-PnPOnline https://contoso.sharepoint.com/sites/site
Get-PnPListItem -PageSize 50 -List 'Documents' -Query "<View Scope='RecursiveAll'><Query><Where><Contains><FieldRef Name='FileDirRef'/><Value Type='Text'>'Documents'</Value></Contains></Where></Query><OrderBy Override='TRUE' Ascending='TRUE'><FieldRef Name='ID'/></OrderBy></View>" 
```

### What is the version of the Cmdlet module you are running?
`PnP.Powershell 1.5.32`

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by YuriySamorodov** [comment]
Just took another attempt:

```
Get-PnPListItem -List 'Documents' -Query "<View Scope='RecursiveAll'><ViewFields><FieldRef Name='Title'/><FieldRef Name='Title'/><FieldRef Name='FileDirRef'/></ViewFields><Query><And><Where><Eq><FieldRef Name='FileDirRef'/><Value Type='Text'>Test</Value></Eq></Where></And></Query><RowLimit Paged='TRUE'>10</RowLimit><OrderBy Ascending='TRUE'><FieldRef Name='ID'/></OrderBy></View>"  | %{ $_.FieldValues.FileRef  }
```
It has started to return all list items regardless of Query clause:
![image](https://user-images.githubusercontent.com/5260172/117071117-4f4a2d80-ad37-11eb-9104-40bf57845bff.png)

**Comment by jlxq0** [comment]
Does anyone know what happened to this? Still doesn't seem to work; at least for me.

**Comment by YuriySamorodov** [comment]
Hi @veronicageek, @gautamdsheth. Would you please look at this? Seems like a lost issue.

**Comment by Adriaanrau** [comment]
Still an issue

**Comment by vgurus** [comment]
Yes, this is still an issue as others commented.

**Comment by D10ny5u5** [comment]
4 years later, this is still an issue.
