### ISSUE TITLE
Add-PnPHubSiteAssociation syncing permissions regardless of setting

### ISSUE THREAD

**Issue by jessierobbins** [pnp/powershell#652]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Reporting an Issue

### Expected behavior 
Add-PnPHubSiteAssociation links site to hub without syncing permissions if the setting is currently turned off

### Actual behavior 
Add-PnPHubSiteAssociation is adding the Hub Visitors permission group regardless of current hub permissions sync settings

### Steps to reproduce behavior
`Add-PnPHubSiteAssociation -site $site.url -HubSite "[hub site url]"`

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@jessierobbins - Having the "Hub Visitors" group in the associated site(s) is a behavior we can also see even when we go through the SPO interface. However, the users added to the Hub Visitors group in the HubSite are **not** present inside this group in the associated site if the setting _Sync hub permissions to associated sites_ is turned off. 

After testing, that's also what the `Add-PnPHubsiteAssociation` is doing (I've used `v1.5.50-nightly`)

Please reopen if users in the Hub Visitors group (in the Hubsite) are also present in the Hub Visitors group in the associated site(s) are showing up.

**Comment by jessierobbins** [comment]
@veronicageek - we're not seeing this behavior when performing the actions via the SPO interface, only via the Powershell command.  If it makes a difference, we're on a GCC tenant.
