### ISSUE TITLE
Get-PnPHubSite doesn't retrieve all sites' urls

### ISSUE THREAD

**Issue by derhallim** [pnp/powershell#658]
## Category

- [x] Bug

## Describe the bug

I am provisioning sites using PnP provisioning template, the site XML looks like this: 

```
<pnp:SiteCollection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="pnp:CommunicationSite" ProvisioningId="Outsourcing" HubSiteTitle="Outsourcing" IsHubSite="true" Url="{parameter:OutsourcingUrl}" Title="{parameter:OutsourcingTitle}" Owner="{currentuserloginname}" Description="{parameter:OutsourcingTitle}" Language="{parameter:lcid}">

</pnp:SiteCollection>
```

I use this to deploy multiple sites the same way. When I then run `Get-PnPHubSite`  I get the sites, but the Url is null. I noticed that if I unregister the hub site and register it again in the browser, it works fine. 

When running `Get-PnPSite` I can see the url, so it's just an issue with Get-PnPHubSite. 
## Steps to reproduce

Provision a new site using this snippet: 

```
<pnp:SiteCollection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="pnp:CommunicationSite" ProvisioningId="Outsourcing" HubSiteTitle="Outsourcing" IsHubSite="true" Url="{parameter:OutsourcingUrl}" Title="{parameter:OutsourcingTitle}" Owner="{currentuserloginname}" Description="{parameter:OutsourcingTitle}" Language="{parameter:lcid}">

</pnp:SiteCollection>
```

Where OutsourcingUrl is a parameter for the required site url. 

Then run `Get-PnPHubSite`.

## Expected behavior

Expected Behavior is to see the url of the hubsite retrieved with the list of sites when using `Get-PnPHubSite`

PowerShell version used: 1.5.33-nightly

**Comment by veronicageek** [comment]
@derhallim - I know it's been a while, but can you please update the module to the latest and feedback. Thanks.

**Comment by veronicageek** [comment]
Closing as no response.

**Comment by derhallim** [comment]
@veronicageek @jansenbe Really sorry for the late reply, had too many things going on..

I noticed something.. if hub sites have the same title, then this issue will occur when executing Get-PnPHubSite

An example below: 

![image](https://user-images.githubusercontent.com/7239963/136315626-b38fd344-0ca5-4f90-8d46-98d86230c3cb.png)

Hub sites with unique name will have the url retrieved. Others with duplicate names will have the url missing for all. 

This is with version 1.7.71-nightly
