### ISSUE TITLE
[BUG] Can't Register or Connect

### ISSUE THREAD

**Issue by DaleyKD** [pnp/powershell#663]
### Reporting an Issue or Missing Feature
I'm trying to run either `Register-PnPManagementShellAccess` or `Connect-PnPOnline -Url "https://{tenant}.sharepoint.com" -Interactive`, and I keep getting:

>Error details: error invalid_client error_description:AADSTS650052: The app needs access to a service ('https://manage-gcc.office.com') that your organization 'gimmalkyle.onmicrosoft.com' has not subscribed to or enabled. Contact your IT Admin to review the configuration of your service subscriptions. Trace ID: 6c376d8f-0e20-48a2-9191-aed408444201 Correlation ID: b7572cb6-ebb2-46ea-b5b7-b03425b5481c Timestamp: 2021-05-07 20:39:48Z

### Expected behavior 
It'd be nice to be able to get past the first hurdle.

### Actual behavior 
See above error.

### What is the version of the Cmdlet module you are running?
1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@DaleyKD - Looking at the error, it seems you're on GCC. Is this correct? 
If yes, have a look at the [documentation](https://pnp.github.io/powershell/articles/authentication.html#authentication-to-gcc-or-national-cloud-environments) for GCC.

**Comment by YuriySamorodov** [comment]
@DaleyKD , I would also update a module. 1.5.0 seems a bit dated

**Comment by DaleyKD** [comment]
Also, it looks like I signed up in 2014 with an Office 365 E3 Developer license.

**Comment by veronicageek** [comment]
The first thing to do when using this module for the first time is `Register-PnPManagementShellAccess` (one-off activity). Have you managed to pass this? Or is the error you getting occurs when using `Connect-PnPOnline`?

**Comment by DaleyKD** [comment]
@veronicageek : That's what I get stuck on: `Register-PnPManagementShellAccess`  That's the command that makes it look like it wants gcc.office.com (or whatever).  But again, I'm not GCC.

**Comment by gautamdsheth** [comment]
Looks like it is specific to your tenant. Any chance you can try that on a different tenant and check ?

**Comment by DaleyKD** [comment]
@gautamdsheth : I started a brand new dev tenant a couple weeks ago and it worked fine.

I'm wanting to know how to fix my current tenant?

**Comment by veronicageek** [comment]
If it worked fine on another tenant, I think it's fair to say that the command has no issue. 
It's going to be pretty difficult for us to troubleshoot your tenant. Maybe you could open a support ticket with Microsoft directly asking them where this URL is coming from if you're not on GCC.

**Comment by gautamdsheth** [comment]
Closing the issue as it seems now that it’s not related to the library.
