### ISSUE TITLE
[BUG] - I'm trying to add list items in a simple site.. but keep getting "File not Found" error

### ISSUE THREAD

**Issue by ollimenzel** [pnp/powershell#668]
## Category

- [x] Bug

## Describe the bug

I'm trying to use the batch function to add list-items to a custom-list. 
Here is my script
Connect-PnPOnline -Url https://tenant.sharepoint.com -ClientId $clientID -ClientSecret $clientSecret
New-PnPList -Title "PnPTestList" -Template GenericList

$list = Get-PnPList -Identity "PnPTestList"
$batch = New-PnPBatch

for ($i = 0; $i -lt 100; $i++) {
    #Add List Item To The Batch - 100 times
    Add-PnPListItem -List $list -Batch $batch -Values @{"Title" = "Person $i" }
}

# Execute the batch all at once
Invoke-PnPBatch -Batch $batch -Details

But I'm getting this error
![image](https://user-images.githubusercontent.com/11551755/117647963-f262d300-b18d-11eb-91f0-aa7002ac5e80.png)

Doing it without the batch functionality works fine.
Tried it on two tenants and two PC's (work / private) but it doesn't work on either set-up.

## Steps to reproduce

Just run the code on your Pc

## Expected behavior

100 List items should be created

## Environment details (*development & target environment*)

Tried it on my dev and Prod environment

- **SDK version**: Pnp 1.5
- **OS**: Windows 10 
- **SDK used in**: Visual Studio Code & Azure Automation
- **Framework**: [e.g. .NET Framework v3.x | .NET Core v3.x ]
- **Browser(s)**: Chromium Edge beta
- **Tooling**: VS Code 
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by veronicageek** [comment]
@ollimenzel - I didn't have any issue running your script (I'm using `v1.5.38-nightly`) and it created my items.
However, not sure if this is a typo, but your `-Url https://tenant.sharepoint.com` should also include the `/sites/<your-site>`

Please upgrade or correct your URL, and feedback. Thanks

**Comment by gautamdsheth** [comment]
Closing it as it has been fixed in the latest version. Please reopen if it still exists.
