### ISSUE TITLE
[BUG] Get-PnPUnifiedAuditLog - Missing data and pulls wrong date range

### ISSUE THREAD

**Issue by robertcaretta** [pnp/powershell#669]
### Reporting an Issue or Missing Feature
1) Returned dataset does not include power automate events such as PutPermissions, DeletePermissions, etc.
2) The cmdlet does not use the dates applied to the switches.  

### Expected behavior 
Results should include the power platform Audit.General data, as well as the proper date range.

### Actual behavior 
Data is missing and date range is not accurate. We do have unified audit log data for Power Automate. We are actively adding/deleting permissions daily and running a variety of tests to determine how to control sharing.

![image](https://user-images.githubusercontent.com/1613085/117715437-df57ff00-b19d-11eb-8afa-7c662ef675d7.png)

### Steps to reproduce behavior
Run this command:
Get-PnPUnifiedAuditLog -ContentType General -StartTime (Get-Date).AddDays(-1) -EndTime (Get-Date)

### What is the version of the Cmdlet module you are running?
1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by robertcaretta** [comment]
Not stale. Keep open.

**Comment by robertcaretta** [comment]
Not stale. Keep open.

**Comment by robertcaretta** [comment]
Not stale. Keep open.

**Comment by KoenZomers** [comment]
Hi @robertcaretta. PR #1127  should fix the date filtering issue you were facing. I'm not sure what you mean by missing data. On my tenant all works fine. Perhaps it was related to the date filtering not working well? Can you try it again after PR #1127 gets merged by taking the PnP PowerShell prerelease from the night after it got merged to test if that resolves it for you? Closing this issue assuming it did. If it did not, feel free to reopen this issue to continue troubleshooting.
