### ISSUE TITLE
[BUG] Set-PnPApplicationCustomizer

### ISSUE THREAD

**Issue by akashic** [pnp/powershell#672]
Issue with Set-PnPApplicationCustomizer

when using the example in the documentation (which I think is missing an end quote) 

> Set-PnPApplicationCustomizer -ClientSideComponentId aa66f67e-46c0-4474-8a82-42bf467d07f2 -Scope web -ClientSideComponentProperties "{`"sourceTermSet`":`"PnP-CollabFooter-SharedLinks`",`"personalItemsStorageProperty`":`"PnP-CollabFooter-MyLinks`"}"

I always get the error

_Set-PnPApplicationCustomizer: Object reference not set to an instance of an object._

I have found that if I use the **-Identity** method, the command works. **-ClientSideComponentId** always fails

**Comment by gautamdsheth** [comment]
Thanks @akashic  for reporting the issue. It has been fixed. Will be available in the nightly build tomorrow. 
Please reopen the issue if it happens again.
Thanks !
