### ISSUE TITLE
[BUG] Add-PnPFile - Modified/ Editor field cannot be set to a specific person

### ISSUE THREAD

**Issue by Max-Enrico** [pnp/powershell#673]
### Reporting an Issue or Missing Feature
With the Add-PNPFile command i cannot set a specific editor.

### Expected behavior 
To set a specific person in editor field by the Add-PNPFile command

### Actual behavior 
for e.g.
Add-PnPFile -Path $File.FullName -NewFileName $File.Targetname -Folder $Documentlist -Values @{ Editor=$SPOFileOwnerID ; Author=$SPOFileOwnerID}

Author field will be filled correctly
Editor field is even the connect user.

### What is the version of the Cmdlet module you are running?
Tested with PnP.PowerShell 1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
Correct, I can reproduce where the "Modified By" is not amended. For the time being, you could use the `Set-PnPListItem` as a workaround.

@gautamdsheth / @erwinvanhunen: Related to #627 where the `-Values` are not correctly set.

**Comment by gautamdsheth** [comment]
Added a fix, will be available in the next nightly tomorrow.
