### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TroyOHannon** [pnp/powershell#674]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting
When running Connect-PnPOnline -Url $Url -Credentials $PSCredentials get the following messaage:
Connect-PnPOnline : The underlying connection was closed: An unexpected error occurred on a send.

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets
Expected to connect without error

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.
Connect-PnPOnline : The underlying connection was closed: An unexpected error occurred on a send.

I confirmed my user account can access the site...

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)
$password = get-content $credential | ConvertTo-SecureString

$Url = "https://<mycompany>.sharepoint.com/sites/apps/<my site>" 

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
	
[System.Management.Automation.PSCredential]$PSCredentials = New-Object System.Management.Automation.PSCredential($username,$password)
Connect-PnPOnline -Url $Url -Credentials $PSCredentials | Out-Null

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands                                                                                                            
---------- -------    ----                                ----------------                                                                                                            
Manifest   1.5.0      PnP.PowerShell                      {Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add-PnPClientSideText, Add-PnPClientSideWebPart...}                   
Manifest   1.4.0      PnP.PowerShell                      {Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add-PnPClientSideText, Add-PnPClientSideWebPart...} 

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by ToddKlindt** [comment]
Try this:
`$password = $credential | ConvertTo-SecureString -AsPlainText`
 
When you do `get-content $credential` it tries to get the content of a file called $credential You can verify it by leaving off the `$password =` bit and seeing what the output is. You can also see what the value of $password is when you assign it. It should say "System.Security.SecureString"

**Comment by TroyOHannon** [comment]
Hi, wanted to close out my post

**Comment by TroyOHannon** [comment]
Found out that it actually has to do with Cypher suites, TLS and our company Group Policy so it was completely unrelated.  Took a lot of leg work with networking and server teams to finally come to this conclusion!  Wanted other to be aware if they also run into this type of issue.
