### ISSUE TITLE
Required Authorization/Connection Type to utilize this function

### ISSUE THREAD

**Issue by jarvann** [pnp/powershell#682]
Reposting in "correct" repository from original: https://github.com/MicrosoftDocs/office-docs-powershell/issues/7740

When I try to access the `Add-PnPTeamsTeam` function through an Azure Function using:

`Connect-PnPOnline -Tenant [tenant].onmicrosoft.com -ClientId [appid] -Thumbprint [thumbprint] -Url https://[tenant].sharepoint.com`

I get the following error:
![image](https://user-images.githubusercontent.com/14030665/118335311-5ca4ac00-b4dd-11eb-975a-f87d50a8d253.png)

I am wondering if the Doc needs updating to specify which connection methods are permitted, or if the function needs to be updated to allow for "Application" API permissions to execute it.

Any Help appreciated, Thanks!

**Comment by veronicageek** [comment]
Does it work without the Azure Function?

**Comment by jarvann** [comment]
> Does it work without the Azure Function?
I can't remember, I will try again on Monday.

**Comment by gautamdsheth** [comment]
Yeah, certificate auth is not supported for that cmdlet.

@veronicageek / @jarvann - should we update docs for this ? or also update the cmdlet as well to warn users ?

**Comment by jarvann** [comment]
>  should we update docs for this ? or also update the cmdlet as well to warn users ?

I think both is the right answer. If you have a known "negative" path, it should be checked (if possible) and reported prior to throwing an exception. In addition, the documentation would help, especially if it can explain the "why" for not using certificate AuthN. 

Personally, I feel that utilizing Azure Function with "App Registration"/Service credentials is a valid use case. So I would be curious at which point in the call chain would require an update to make that happen? Is it an API permission problem on the AAD side, an issue in the MS Teams cmdlets/API, or is it the PnP Scripts that are preventing this from working?

For now, I am satisfied if the documentation and scripts could be aligned with the existing capabilities.

**Comment by gautamdsheth** [comment]
@jarvann - we fixed this issue couple of days back. 
Can you please try with the latest nightly builds ? 
Please reopen this if it still happens. 
Thanks for reporting !
