### ISSUE TITLE
[BUG] Add-PnPPage throws MissingMethodException

### ISSUE THREAD

**Issue by matsn0w** [pnp/powershell#690]
I found this issue using the PnP.PowerShell module.

Initially, when I tried to invoke a site template using `Invoke-PnPSiteTemplate`, I got an `MissingMethodException` over and over again - no matter what I tried. I've been trying multiple scenario's, configurations and parameters.

Then, I discovered that running Add-PnPPage resulted in the same exact error, even in a very basic form:

```powershell
Add-PnPPage -Name "My Page"
```

This is the error I get:

```
Add-PnPPage : Method not found: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1<Boolean> Enumerator.MoveNextAsync().
At line:1 char:1
+ Add-PnPPage -Name "My Page"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Add-PnPPage], MissingMethodException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Pages.AddPage    
```

I suspect that something in the paging engine is broken. 

Any clues? I'm running the latest stable build, 1.5.0

Thanks in advance and keep up the good work!
matsn0w

**Comment by veronicageek** [comment]
@matsn0w - Can you update please? I don't have this issue with `1.5.52-nightly`.

![image](https://user-images.githubusercontent.com/25181757/119387819-65596700-bcc1-11eb-90cc-912bef94e946.png)
