### ISSUE TITLE
[BUG] Connect-pnponline crash after using "system.Windows" forms

### ISSUE THREAD

**Issue by peteopablo** [pnp/powershell#695]
### What is the version of the Cmdlet module you are running?
Version: 1.5.0      PnP.PowerShell  

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows

Problem:
If you use the connect-pnponline function, after creating an new form object "system.Windows" the Connect-PnPOnline function could not connect, nothing happens and the console crashes.

Code Example :
Add-Type -AssemblyName System.Windows.Forms
$PB = New-Object system.Windows.Forms.PictureBox

$U = "https://test.sharepoint.com/sites/test"
Connect-PnPOnline -Url $U -Credentials "test" # Example works with credential manager

**Comment by peteopablo** [comment]
Some additional Information, the code works fine with the previos version: SharePointPnPPowershellOnline

**Comment by peteopablo** [comment]
Is there anyone who can reproduce this behaviour.

**Comment by gautamdsheth** [comment]
Closing this because it is not related to PnP PowerShell specifically.
