### ISSUE TITLE
[FEATURE] When using Add-PnPAlert to add a Weekly alert, how should a DateTime value be?  

### ISSUE THREAD

**Issue by ghost** [pnp/powershell#700]
**Is your feature request related to a problem? Please describe.**
I am looking to use Add-PnPAlert to apply a weekly alert for many users. I am not sure how Get-Date function should be set up for weekly alerts. For Daily alert, you can just provide 3 values (Hour, Minutes, and Seconds) to set it up as shown in below code. But this is not an option for Weekly because there is no way to work with a day (Monday, Tuesday, etc.)... 

`Add-PnPAlert -Title "Daily summary" -List "Test List" -Frequency Daily -ChangeType AddObject -DeliveryMethod "Email" -Time (Get-Date -Hour 15 -Minute 00 -Second 00) -User "i:0#.f|membership|love@sharelove.org"`

**Describe the solution you'd like**
I'd like a way to select a day for weekly unless it's already possible. 

**Describe alternatives you've considered**
Is there currently a way of solving your problem with existing cmdlets? Optionally through the use of other PowerShell Modules (for instance by using the Microsoft Graph cmdlets or the Microsoft SPO Management Shell)
I am not sure at this point but any existing would be great. 

**Additional context**
I love you guys and all of your work.

**Comment by KoenZomers** [comment]
For what it is still worth seen that this is an old issue, I have updated the documentation of [Add-PnPAlert](https://github.com/pnp/powershell/blob/dev/documentation/Add-PnPAlert.md) to clarify how the weekly occurrence can be used with the -Time parameter.
