### ISSUE TITLE
[BUG] on Connect-PnPOnline in azure function using CertificateBase64Encoded

### ISSUE THREAD

**Issue by pieronegri** [pnp/powershell#704]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? NO, Connect-PnpOnLine in Azure Function
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** the code

### Reporting an Issue or Missing Feature
ISSUE

### Expected behavior 
Connect-PnPOnline -Url $url -ClientId $Env:clientID -CertificateBase64Encoded $Env:secret -Tenant $Env:tenantID -ReturnConnection -ErrorAction Stop
should connect to the requested sharepoint site 

### Actual behavior 
Is working fine on local visual studio code.

the azure function can print the CertificateBase64Encoded string from the key vault.
(only thing I did was I changed the functions_worker_process_count from 1 to 10 and then back to 1)
Get-PnpException output I am receiving:
{
  "Message": "The system cannot find the file specified.",
  "Stacktrace": "   at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)\r\n   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)\r\n   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, SecureString password, X509KeyStorageFlags keyStorageFlags)\r\n   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, SecureString password)\r\n   at PnP.PowerShell.Commands.Base.ConnectOnline.ConnectAppOnlyWithCertificate() in c:\\PnPPowerShell\\src\\Commands\\Base\\ConnectOnline.cs:line 419\r\n   at PnP.PowerShell.Commands.Base.ConnectOnline.Connect(CancellationToken& cancellationToken) in c:\\PnPPowerShell\\src\\Commands\\Base\\ConnectOnline.cs:line 245\r\n   at PnP.PowerShell.Commands.Base.ConnectOnline.ProcessRecord() in c:\\PnPPowerShell\\src\\Commands\\Base\\ConnectOnline.cs:line 207\r\n   at System.Management.Automation.Cmdlet.DoProcessRecord()\r\n   at System.Management.Automation.CommandProcessor.ProcessRecord()",
  "ScriptLineNumber": 12,
  "InvocationInfo": {
    "MyCommand": {
      "Verb": "Connect",
      "Noun": "PnPOnline",
      "HelpFile": "PnP.PowerShell.dll-Help.xml",
      "PSSnapIn": null,
      "Version": {
        "Major": 1,
        "Minor": 5,
        "Build": 0,
        "Revision": -1,
        "MajorRevision": -1,
        "MinorRevision": -1
      },
      "ImplementingType": {
        "IsCollectible": false,
        "DeclaringMethod": null,
        "FullName": "PnP.PowerShell.Commands.Base.ConnectOnline",
        "AssemblyQualifiedName": "PnP.PowerShell.Commands.Base.ConnectOnline, PnP.PowerShell, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null",
        "Namespace": "PnP.PowerShell.Commands.Base",
        "GUID": "5005aa8f-cf7d-39ee-abf2-05d950e12e32",
        "GenericParameterAttributes": null,
        "IsSZArray": false,
        "GenericParameterPosition": null,
        "ContainsGenericParameters": false,
        "StructLayoutAttribute": {
          "Pack": 8,
          "Size": 0,
          "CharSet": 2,
          "Value": 3,
          "TypeId": "System.Runtime.InteropServices.StructLayoutAttribute"
        },
        "Name": "ConnectOnline",
        "DeclaringType": null,
        "Assembly": {
          "CodeBase": "file:///C:/home/data/ManagedDependencies/210427154130965.r/PnP.PowerShell/1.5.0/Core/PnP.PowerShell.dll",
          "FullName": "PnP.PowerShell, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null",
          "EntryPoint": null,
     
### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

##x# What is the version of the Cmdlet module you are running? 1.5.0
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ x] Azure Functions
- [ ] Other : please specify

**Comment by JelleBroekhuijsen** [comment]
@pieronegri I also encounted this issue however this is not a but in the module. You can solve this issue by adding the following function app setting:

`WEBSITE_LOAD_USER_PROFILE = 1`

![image](https://user-images.githubusercontent.com/58708777/120659465-aeaa7300-c486-11eb-9748-ef1ada76510f.png)


The underlying issue is that, if you do not load a user profile in the function app, the environment does not provide a cryptographic keystore or something like that. So it cannot save the certificate data to the hosting environment.

**Comment by pieronegri** [comment]
> @pieronegri this is working file for me and I am connecting with:
> Connect-PnPOnline -Url $SiteUrl -ClientId $clientId -Tenant "$SPO_TENANT.onmicrosoft.com" -CertificateBase64Encoded $CERTIFICATE
> 
> In my case, $CERTIFICATE is an app setting that is a Key Vault reference to the certificate secret, so all is handled by Azure.

This is also what I am doing, but once in a while it fails...

**Comment by pieronegri** [comment]
> @pieronegri I also encounted this issue however this is not a bug in the module. You can solve this issue by adding the following function app settings:
> 
> `WEBSITE_LOAD_USER_PROFILE = 1`
> ![image](https://user-images.githubusercontent.com/58708777/120659795-fe893a00-c486-11eb-9821-44e4cf529035.png)
> 
> The underlying issue is that, if you do not load a user profile in the function app, the environment does not provide a cryptographic keystore or something like that. So it cannot save the certificate data to the hosting environment.

I will give this a try!

**Comment by gautamdsheth** [comment]
@pieronegri - any update on this ? If it is working fine locally but not in Azure function , I don't think it a PnP PowerShell issue but something to do with the AF configuration, so going to close this :)

**Comment by joelfmrodrigues** [comment]
@gautamdsheth 100% works in Azure Functions as I have created a few over the last months and works fine

**Comment by joelfmrodrigues** [comment]
Did a session at the M365 UK user group where I created some functions with certificates. Hope this can help someone: https://www.youtube.com/watch?v=QajesgmwOCM

**Comment by pieronegri** [comment]
sorry for delay. it's actually working with WEBSITE_LOAD_USER_PROFILE = 1
