### ISSUE TITLE
Get-PnPSiteCollectionAdmin returns error 401 Unauthorized

### ISSUE THREAD

**Issue by vayinapurapu** [pnp/powershell#705]
Get-PnPSiteCollectionAdmin : The remote server returned an error: (401) Unauthorized.
At line:1 char:1
+ Get-PnPSiteCollectionAdmin -Connection (Get-PnPConnection)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPSiteCollectionAdmin], WebException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Site.GetSiteCollectionAdmin

**Comment by veronicageek** [comment]
@vayinapurapu - DO NOT DELETE THE TEMPLATE when creating an issue. The information requested helps to troubleshoot faster.

Meanwhile I have no issue when using this cmdlet. Please reopen with more info.

![image](https://user-images.githubusercontent.com/25181757/119224034-786b0c00-baf4-11eb-999c-d99acc4a247d.png)
