### ISSUE TITLE
setuptestenv.ps1: Authentication method is not allowed

### ISSUE THREAD

**Issue by DaleyKD** [pnp/powershell#706]
## Category

- [x] Bug

## Describe the bug
Fresh tenant, trying to run the `setuptestenv.ps1`. When trying to run `Add-PnPTeamsTeam`, I receive `Authentication method is not allowed`.  It may be related to https://github.com/pnp/powershell/issues/462, though we're not using certificate at this point, I don't think?

``` sh
PS C:\repos\pnpcore\src\sdk\PnP.Core.Test> .\setuptestenv.ps1
Please enter UPN: kyle@gimmalkyle2.onmicrosoft.com
Please enter password: ***********
Input your tenant name (e.g. contoso): gimmalkyle2
VERBOSE: Acquiring token
VERBOSE: Token acquired
VERBOSE: PnP PowerShell Cmdlets (1.5.0)
Add-PnPApp: C:\repos\pnpcore\src\sdk\PnP.Core.Test\setuptestenv.ps1:52
Line |
  52 |  $app = Add-PnPApp -Path .\TestAssets\pnpcoresdk-test-app.sppkg
     |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Value cannot be null. (Parameter 'webFullUrl')


Title    ServerRelativeUrl             Id
-----    -----------------             --
Sub site /sites/pnpcoresdktest/subsite b275fee6-caa0-4b92-8b04-b9e4b206df9b
Add-PnPTeamsTeam: C:\repos\pnpcore\src\sdk\PnP.Core.Test\setuptestenv.ps1:67
Line |
  67 |  Add-PnPTeamsTeam
     |  ~~~~~~~~~~~~~~~~
     | {"odata.error":{"code":"10005","message":{"lang":"en-US","value":"Authentication method is not
     | allowed."}}}

format-default: The collection has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.
```

## Steps to reproduce
Fresh tenant. Run the script.

## Expected behavior
I just want to be able to contribute to this repo!  :smile: :rofl:

## Environment details (*development & target environment*)
- **SDK version**: 1.1.0
- **OS**: Windows 10
- **Tooling**: PowerShell 5 (I also tried PowerShell 7)
- **Additional details**: PnP.PowerShell 1.5.0

**Comment by veronicageek** [comment]
Please try with the `-nightly` tomorrow or reopen if the issue persists.
