### ISSUE TITLE
New help website case doesn't match Online Help

### ISSUE THREAD

**Issue by JustinGrote** [pnp/powershell#718]
![image](https://user-images.githubusercontent.com/15258962/119531040-6a0d3200-bd38-11eb-895a-62293a32845e.png)
![image](https://user-images.githubusercontent.com/15258962/119531093-74c7c700-bd38-11eb-86ea-1fc7a6d2bcb4.png)

Correct:
https://pnp.github.io/powershell/cmdlets/Connect-PnPOnline.html

Either fix the website to be case insensitive in the URI, or update the help links.

**Comment by gautamdsheth** [comment]
Thanks @JustinGrote , have fixed the links. 
Also, checking into how we can make the links case insensitive.
