### ISSUE TITLE
Connect-PnPOnline -Interactive Not working with GCC High tenants

### ISSUE THREAD

**Issue by patrickabel** [pnp/powershell#719]
Using the new cross-platform version of PnP.PowerShell, the **Connect-PnPOnline cmdlet is not working for connecting to GCC High tenants**. This works just fine when using the old cmdlets and -UseWebLogin parameter, but with the new module and **-Interactive** parameter it's not working. See screenshots below.
![Screenshot_396](https://user-images.githubusercontent.com/1153976/119532464-85813880-bd4a-11eb-9ca9-cd8394890dbb.png)
![Screenshot_395](https://user-images.githubusercontent.com/1153976/119532467-85813880-bd4a-11eb-8616-5de761376916.png)

I see a **-AzureEnvironment USGovernmentHigh** parameter available, but this doesn't look to work unless using app-only auth patterns (not using -Interactive).
![Screenshot_397](https://user-images.githubusercontent.com/1153976/119532981-050f0780-bd4b-11eb-983b-a828653a90c9.png)

I've tried against multiple GCCH tenants, looks to be a cmdlet issue. Any assistance here would be greatly appreciated!

**Comment by patrickabel** [comment]
Note – I've checked this with both the latest stable and nightly prerelease builds for PnP.PowerShell.

**Comment by rogernichols** [comment]
I can confirm this is also happening across GCCH tenants that I have tried as well.  This has been a replicatable for at least a month, but I originally dismissed it as a one off issue with a single problematic tenant, but I have also been able to replicate it across multiple.

Fiddler looks to indicate it is an issue with the below.


AADSTS65006: Resource '797f4846-ba00-4fd7-ba43-dac1f8f63013' had no entitlements matching required permissions configured on the required resource access for client '31359c7f-bd7e-475c-86db-fdb8c937548e'. Requested permission IDs: '41094075-9dad-400e-a0bd-54e686782033'. This is a problem with one or more invalid permission ids on the client RRA configuration or the resource entitlement configuration.
--

My current understanding is that this may require the using Register-PnPManagementShellAccess as mentioned in a separate issue thread, but that also ran into an Access Denied error when I attempted to run it with the provided command for GCC so I have not been able to work though the issue yet.  The Access Denied error persisted through removal of the Permission parameters and this was performed with a Global Admin account.  I presume there is a step I am missing or misunderstanding.

`Register-PnPAzureADApp -ApplicationName "PnP PowerShell" -Tenant [tenant].onmicrosoft.us -Interactive -AzureEnvironment USGovernmentHigh -SharePointDelegatePermissions AllSites.FullControl -SharePointApplicationPermissions Sites.FullControl.All -GraphApplicationPermissions Group.ReadWrite.All -GraphDelegatePermissions Group.ReadWrite.All`

**Comment by patrickabel** [comment]
the bug label was added, why was this auto-closed?

**Comment by GTH20** [comment]
Any resolution for this issue?

**Comment by Pers2140** [comment]
Was this ever fixed?
