### ISSUE TITLE
[BUG] Get-PnPCustomAction Does Not Find Any Custom Actions

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#72]
### Reporting an Issue or Missing Feature
I am reporting a bug

### Expected behavior 
I am expecting to get a list of custom actions when running ```Get-PnPCustomAction``` against a site that definitely has user custom action.
If running `Get-PnPCustomAction``` command that is a part of SharePointPnPPowerShellOnline 3.26.2010.0 module
![image](https://user-images.githubusercontent.com/5260172/103320084-280be880-4a45-11eb-8a73-1e7d627a5708.png)

I am getting the following results:
![image](https://user-images.githubusercontent.com/5260172/103320009-f5fa8680-4a44-11eb-9bb3-be408f865d31.png)

### Actual behavior 
If I run the same code from "Expected behavior" section with `PnP.PowerShell 0.3.18` loaded
![image](https://user-images.githubusercontent.com/5260172/103320232-9a7cc880-4a45-11eb-886b-2b86e18a66ce.png)
I am getting an error:
`Get-PnPCustomAction: No CustomAction found with the Identity "00000000-0000-0000-0000-000000000000" within the scope 'Web`
![image](https://user-images.githubusercontent.com/5260172/103320370-1ecf4b80-4a46-11eb-826f-747f394a42cb.png)

Specifying `Web` or `Identity` parameters would be no help (although an error returned is different):
![image](https://user-images.githubusercontent.com/5260172/103320485-9ac99380-4a46-11eb-8ec2-6c17ffe1dc19.png)

### Steps to reproduce
`
Connect-PnPOnline -Url https://tenantname.sharepoint.com/sites/sitename
$PnPSite = Get-PnPSite -Connection $PnPConnectionSite -includes UserCustomActions
PnPConnection = Get-PnPConnection
Get-PnPCustomAction -ThrowExceptionIfCustomActionNotFound -Connection $PnPConnectionSite
`

### What is the version of the Cmdlet module you are running?
Non-working environment
![image](https://user-images.githubusercontent.com/5260172/103320232-9a7cc880-4a45-11eb-886b-2b86e18a66ce.png)
```
Name    : Get-PnPCustomAction
Source  : pnp.powershell
Version : 0.3.18
```

Working Environment:
![image](https://user-images.githubusercontent.com/5260172/103320084-280be880-4a45-11eb-8a73-1e7d627a5708.png)
```
Name    : Get-PnPCustomAction
Source  : SharePointPnPPowerShellOnline
Version : 3.26.2010.0
```
### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
Hi! Thank you for reporting this. I can confirm this issue. We fixed it and the next nightly build (0.3.24-nightly) will contain this fix.
