### ISSUE TITLE
When I try to use any functions like Get-PnPFolderItem or Get-PnPFile etc, I get the error message: "The property or field 'ServerRelativeUrl' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested"

### ISSUE THREAD

**Issue by Arrggh1234** [pnp/powershell#721]
TITLE: The nightly versions seem to connect fine, but when I try to use any functions like Get-PnPFolderItem or Get-PnPFile etc, I get the error message: "The property or field 'ServerRelativeUrl' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested"

### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
No
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
Looks like it is the code in all the nightlies.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting
The nightly versions seem to connect fine, but when I try to use any functions like Get-PnPFolderItem or Get-PnPFile etc, I get the error message: "The property or field 'ServerRelativeUrl' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested"
### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets
I expect the function to complete successfully.
### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.
I get the error above.
### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)
Connect-PnPOnline -Url <site> -Credentials <credentials>
Get-PnPFolderItem -FolderSiteRelativeUrl <relativeurl> -ItemType Folder
### What is the version of the Cmdlet module you are running? 
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
1.5.53 Nightly
### Which operating system/environment are you running PnP PowerShell on?
- [ x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by YuriySamorodov** [comment]
@Arrggh1234 , please be more specific in the title

**Comment by Arrggh1234** [comment]
Changed the title as requested

**Comment by veronicageek** [comment]
@Arrggh1234 - I have no problem with `1.5.53-nightly`. What is it you're trying to do?

![image](https://user-images.githubusercontent.com/25181757/119620956-7909e800-bdfd-11eb-8129-be68df7eaad4.png)
