### ISSUE TITLE
[FEATURE] Make DisableAppViews a Switch Parameter

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#722]
**Is your feature request related to a problem? Please describe.**
Not a problem at all. Just for a better consistency and predictability. It's more often than not `Disable`/`Enable` in a parameter name implies a parameter is of switch type.

**Describe the solution you'd like**
It would be much more clear to have `DisableAppViews` be of a switch type

**Describe alternatives you've considered**
N/A

**Additional context**
Probably not possible since parameter accepts value `Unknown` 

![image](https://user-images.githubusercontent.com/5260172/119570429-c6179b00-bdb8-11eb-839c-d9ab12e761cf.png)

**Comment by gautamdsheth** [comment]
This is not possible as it is coming from enum. Microsoft may or may not add more values to this enum so we can't make it as switch parameter.
