### ISSUE TITLE
[FEATURE] Make DisableCompanyWideSharingLinks a Switch

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#723]
**Is your feature request related to a problem? Please describe.**
Not a problem at all. Just for a better consistency and predictability. It's more often than not `Disable`/`Enable` in a parameter name implies a parameter is of switch type.

**Describe the solution you'd like**
It would be much more clear to have `DisableCompanyWideSharingLinks` be of a switch type

**Describe alternatives you've considered**
Perhaps impossible to do since that parameter accepts value of `Unknown`

**Additional context**

![image](https://user-images.githubusercontent.com/5260172/119570927-62da3880-bdb9-11eb-954b-d41797412e4f.png)

**Comment by gautamdsheth** [comment]
This is not possible as it is coming from enum. Microsoft may or may not add more values to this enum so we can't make it as switch parameter.
