### ISSUE TITLE
ConvertTo-PnPPage : Could not find file 'PnP.Framework.resources'

### ISSUE THREAD

**Issue by ma-cu** [pnp/powershell#724]
Hello Everyone,

We've been working on a SharePoint migration project, from **SharePoint 2010** to **SharePoint Online**. 

We are trying to transform the publishing pages from SP2010 directly to SharePoint Online. Unfortunately, we ran into this error where it states "**Could not find file 'PnP.Framework.resources**'". It has been more than a week now trying to search for clues to fix this or maybe tell that we're doing something wrong or missing something. :) All resources were good and we followed, yet it always goes down to this error. 

![image](https://user-images.githubusercontent.com/36274780/119612427-74115c80-be2e-11eb-8130-95a3781cedb4.png)

NOTES: 

- The screenshot intends to try it first in a single page transformation, but it will be updated once it successfully transformed one.
- The source site is a Publishing Site template, while the target site is a Modern Site (commercial\team site)

Hope anyone can advise or give a possible resolution on this.

Appreciate any help on this matter.

**Comment by rmillener** [comment]
For anyone coming across this. I was able to resolve it by using PowerShell 7.2 instead of 5.1 using 1.10.27 nightly.
