### ISSUE TITLE
[BUG] Pipebind does not work when using Set-PnPListItem, Remove-PnPListItem and Add-PnPListItem

### ISSUE THREAD

**Issue by AndersRask** [pnp/powershell#728]
### Expected behavior 
When adding, updating or removing a list item I want to use either list or list item pipebind as specified in documentation:

`-Identity <ListItemPipeBind>`
or
`-List <ListPipeBind>`

### Actual behavior 
You get an error
Set-PnPListItem: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.

If both -Identity and -List are provided without pipebind, everything works.

### Steps to reproduce behavior

```
Get-PnPList test | Get-PnPListItem

Id    Title                                              GUID
--    -----                                              ----
1     test                                               99a034ed-e754-4a02-a8db-84c25501476e

PS C:\temp> Get-PnPList test | Set-PnPListItem -Identity 1 -Values @{Title="test 2"}
Set-PnPListItem: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
PS C:\temp> Get-PnPList test | Get-PnPListItem -Id 1 | Set-PnPListItem -Values @{Title="test 2"} -List test
Set-PnPListItem: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
PS C:\temp> Set-PnPListItem -Values @{Title="test 2"} -List test -Identity 1

Id    Title                                              GUID
--    -----                                              ----
1     test 2                                             99a034ed-e754-4a02-a8db-84c25501476e

```

Exactly the same behaviour with `Remove-PnPListItem` and `Add-PnPListItem` (for -List parameter)

(also note the inconsistent parameter naming: -Identity for Set-PnPListItem/Remove-PnPListItem and -Id for Get-PnPListItem)

### What is the version of the Cmdlet module you are running?
1.5

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by AndersRask** [comment]
@erwinvanhunen I think this got ignored because I forgot to add a proper title :)

**Comment by KoenZomers** [comment]
Looking into this one.

**Comment by KoenZomers** [comment]
Request has been implemented in PR https://github.com/pnp/powershell/pull/1138. After his PR has been merged, wait until the next day and you can try this out using the latest nightly build. Assuming that this PR will resolve this request, I will proceed with closing this issue. In case it turns out to not fully resolve your request, feel free to reopen.
