### ISSUE TITLE
Get-PnPTeamsTeam -Identity "SampleName" does not bring through value of isArchived

### ISSUE THREAD

**Issue by asadrefai** [pnp/powershell#729]
### Issue
**isArchived** is always returned empty on running command Get-PnPTeamsTeam -Identity "SampleName".

### Expected behavior 
A boolean value is expected in the return object.

### Actual behavior 
isArchived column is always empty on running the command Get-PnPTeamsTeam. 

![Get-TeamsTeam](https://user-images.githubusercontent.com/11193596/119825932-1f94dc80-bf15-11eb-94de-f3d7ecab219b.PNG)

### Steps to reproduce behavior
Simply run command _Get-PnPTeamsTeam_ OR _Get-PnPTeamsTeam -Identity "SampleName"_

The command is executing code from function GetTeamAsync in file TeamsUtility.cs, I suspect that the line number 68 in https://github.com/pnp/powershell/blob/dev/src/Commands/Utilities/TeamsUtility.cs does not have isArchived as part of select filters. May be if we include isArchived the problem might get solved.

### What is the version of the Cmdlet module you are running?
1.5.0
1.4.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows

**Comment by asadrefai** [comment]
@veronicageek will you get chance to look at this issue?

**Comment by gautamdsheth** [comment]
Have fixed this issue, will be available tomorrow. 
Thanks for reporting !
