### ISSUE TITLE
Get-PnPTeamsUser -Team "TeamName" -Channel "ChannelName" throws error Index was out of range. Must be non-negative and less than the size of the collection.

### ISSUE THREAD

**Issue by asadrefai** [pnp/powershell#730]
### Issue
Get-PnPTeamsUser -Team "TeamName" -Channel "ChannelName" always throw error "Index was out of range. Must be non-negative and less than the size of the collection."

If we run command without -Channel then the command works fine, its just with -Channel parameter command fails.

### Expected behavior 
Users from the given Team and Channel must be returned.

### Actual behavior 
If -Channel parameter is passed then always get exception "_Index was out of range. Must be non-negative and less than the size of the collection._"

![Get-PnPTeamsUser](https://user-images.githubusercontent.com/11193596/119828486-d3976700-bf17-11eb-8ea2-a7a59f0ad487.PNG)

### Steps to reproduce behavior

Simply run command _Get-PnPTeamsUser -Team "TeamName" -Channel "ChannelName"_

### What is the version of the Cmdlet module you are running?
1.5.0
1.4.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows

**Comment by veronicageek** [comment]
I guess the error is misleading or not very explicit somehow, because the `-Channel` parameter works for Private Channels.
`Get-PnPTeamsUser -Team "myTeam"` should give you the same results as (for example) `Get-PnPTeamsUser -Team "MyTeam" -Channel General`

![image](https://user-images.githubusercontent.com/25181757/119838793-98873a80-befb-11eb-8ed4-34e5119220eb.png)

FYI - @gautamdsheth / @erwinvanhunen

**Comment by asadrefai** [comment]
@veronicageek do you have members or guests in your PrivateChannelTest? if not can you please add a Member Role user and re run the command..

**Comment by asadrefai** [comment]
If you go through the code, command calls overloaded method "GetUsersAsync" with ChannelID. I suspect the problem is that Grapgh api returns empty roles array for Members and Guests. Refer below screen shot, this is returned from Graph API call.

![error1](https://user-images.githubusercontent.com/11193596/119842704-8a99df80-bf24-11eb-8919-4185ee3f4319.PNG)
 
Lines 410 and 417 in file https://github.com/pnp/powershell/blob/dev/src/Commands/Utilities/TeamsUtility.cs has a "m.Roles[0].ToLower()". I suspect here it might be failing as there will be no values at index 0 for Members or Guests. 

Sorry, if am wrong.

**Comment by gautamdsheth** [comment]
Fixed it, should be available in tomorrow's nightly !
Thanks for reporting.

**Comment by asadrefai** [comment]
Thank you @gautamdsheth for quick fix.
