### ISSUE TITLE
[BUG] Use Get-PnPListItem with parameter FolderServerRelativeUrl and PageSize exceeds the list view threshold

### ISSUE THREAD

**Issue by svermaak** [pnp/powershell#734]
### Reporting an Issue or Missing Feature
Bug

### Expected behavior 
Use Get-PnPListItem with parameter FolderServerRelativeUrl and PageSize get items in folder where library contains more that 5000 items

### Actual behavior 
Get-PnPListItem: The attempted operation is prohibited because it exceeds the list view threshold.

### Steps to reproduce behavior
![image](https://user-images.githubusercontent.com/12259728/119903563-37f40e00-bf8c-11eb-964a-7a0eb5093f59.png)

### What is the version of the Cmdlet module you are running?
v1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by svermaak** [comment]
aaa

**Comment by veronicageek** [comment]
@svermaak - Can you update to the latest version (nightly preferred) and feedback to us please. Thanks.

**Comment by svermaak** [comment]
Still the same

![image](https://user-images.githubusercontent.com/12259728/150698756-68fc50c1-ae4d-408b-88af-6886cb307695.png)

**Comment by veronicageek** [comment]
There's been a lot of improvements and bug fixes in the new release. Can you please update to the latest 2.1.x however **PS 7.2 or later** is needed to benefit from it all.

PS5 support has been dropped.

Feel free to reopen if the issue persists. Thanks.

**Comment by Smig0l** [comment]
Hi!
same issue even in the latest nightly 2.99.120:
```
$siteName = "MYSITENAME"
$siteUrl = "https://$tenantName.sharepoint.com/sites/$siteName"

$libraryName = "ARCHIVIO"
$targetFolder = "00.05 HR"

# Non interactive Authentication using a certificate file
Connect-PnPOnline -Url $siteUrl -AccessToken $accessToken -Verbose

# Define the server-relative URL of the target folder
$folderRelativeUrl = "/sites/$siteName/$libraryName/$targetFolder"

# Retrieve items only within the specific folder
$items = Get-PnPListItem -FolderServerRelativeUrl $folderRelativeUrl -List $libraryName -PageSize 5000
```

i get
`Get-PnPListItem: Value cannot be null. (Parameter 'source')`

**Comment by Smig0l** [comment]
Hi!
the issue persist even with the current nightly: `2.99.120` (using `Powershell 7.4.7`)
