### ISSUE TITLE
Request-PnPPersonalSite results in Access denied.

### ISSUE THREAD

**Issue by kpinel** [pnp/powershell#735]
Initially saw this while transitioning from SPO module to PnP using one of my provisioning accounts which has the SharePoint admin role assigned
Request-PnPPersonalSite : Access denied. You do not have permission to perform this action or access this resource

I have also tested it with my global admin account and receive the same error

**Comment by kpinel** [comment]
Just as a demonstration, I ran this using SPO and PnP just to confirm that there wasn't an issue in the tenant. I have also replicated it in our QA tenant which is completely separate from production.
PS D:\Scripts> Request-PnPPersonalSite -UserEmails pinel@uni.edu.au
Request-PnPPersonalSite : Access denied. You do not have permission to perform this action or access this resource.
At line:1 char:1
+ Request-PnPPersonalSite -UserEmails pinel@qut.edu.au
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Request-PnPPersonalSite], ServerUnauthorizedAccessException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Admin.RequestPersonalSite

PS D:\Scripts> Request-SPOPersonalSite -UserEmails pinel@uni.edu.au
PS D:\Scripts>

**Comment by joelhaslerfhnw** [comment]
Hi 

I have the same problem! Is there a solution in in sight? 

I look forward to hearing from you soon ;-)
Joël

**Comment by KoenZomers** [comment]
Looking into this one.

**Comment by KoenZomers** [comment]
Figured it out. You **must** authenticate using -UseWebLogin or when wanting to use this without an interactive login using -ClientId -ClientSecret (ACS authentication) for these cmdlets to work. I've updated the documentation of `New-PnPPersonalSite` and `Request-PnPPersonalSite`, which both effectively do the same, to explain exactly how to authenticate and what permissions to apply.

Assuming that will clarify it and allow you to use these cmdlets, I will proceed with closing this issue. If something is not clear or it still doesn't work for you, feel free to reopen.

**Comment by joelhaslerfhnw** [comment]
> Figured it out. You **must** authenticate using -UseWebLogin or when wanting to use this without an interactive login using -ClientId -ClientSecret (ACS authentication) for these cmdlets to work. I've updated the documentation of `New-PnPPersonalSite` and `Request-PnPPersonalSite`, which both effectively do the same, to explain exactly how to authenticate and what permissions to apply.
> 
> Assuming that will clarify it and allow you to use these cmdlets, I will proceed with closing this issue. If something is not clear or it still doesn't work for you, feel free to reopen.

it is working perfect, many thanks

**Comment by joelhaslerfhnw** [comment]
@KoenZomers But why is it not possible authenticating using a certificate? The appregnew procedure is legacy and can not be used in our tenant, because it is to new :-(  Is there another alternative, so that we can script this to run unattended as a scheduled task? Many thanks for your help. cheers
