### ISSUE TITLE
[BUG] PowerShell 7.1 "Operating System" attribute is empty in Azure Active Directory

### ISSUE THREAD

**Issue by larnera** [pnp/powershell#737]
I originally raised this issue over at https://github.com/PowerShell/PowerShell/, but have been informed that the issue resides with pnp. I'd have thought it would be a PowerShell problem given this works fine in older versions but anyway, if you could help get this resolved it'll be appreciated. 

> Connect-PnpOnline is in this repo: https://github.com/pnp/powershell
> They would need to make the change to address this.
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/296298081/933a6d00-072b-11eb-839d-56df16c29588"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[pnp/powershell](https://github.com/pnp/powershell)**PnP PowerShell. Contribute to pnp/powershell development by creating an account on GitHub.

--------------

We have a AAD Conditional Access Policy in place which blocks unknown operating systems for our enterprise apps and users. 

When using PowerShell 7.1.3, the operating system is showing as empty in "device info" under the "sign-in log within AAD. This has resulted in blocking access to our Enterprise App (SharePoint PnP PowerShell). 

![image](https://user-images.githubusercontent.com/2369339/119807504-1a1aa080-bedb-11eb-8676-c81949f78245.png)

When we use PowerShell 5.1, the operating system; "Windows 10" is shown and access is granted to our Enterprise App. 

![image](https://user-images.githubusercontent.com/2369339/119807613-37e80580-bedb-11eb-8a89-6594b4f0f499.png)

## Steps to reproduce

1. Create a "Block Access" Conditional Access Policy in AAD with "device platform" condition set to:

Include = "any device"
Exclude = "Android, iOS, Windows Phone, Windows, macOS"

![image](https://user-images.githubusercontent.com/2369339/119807394-03744980-bedb-11eb-8019-300e8f09b35f.png)

2. in PowerShell 7, run command: Connect-PnPOnline -Url https://www.xxxxxxxx.com/sites/commsSite -Credentials (Get-Credential)
3. Enter credentials

## Expected behaviour

Access token is provided.

## Actual behaviour

Access token is not provided:

```none
Connect-PnPOnline: AADSTS53003: Access has been blocked by Conditional Access policies. The access policy does not allow token issuance.
Trace ID: a99d8841-0ad6-4d71-b9a5-c602ee844301
Correlation ID: 79c2241b-37af-4ff2-9e66-fe0e2d4c0f81
Timestamp: 2021-05-27 09:50:37Z

```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by veronicageek** [comment]
@larnera 

> When using PowerShell 7.1.3, the operating system is showing as empty in "device info"

Can you confirm that any other module capable of using PowerShell 7.1.3 is not blocked by your CA policies?

>I originally raised this issue over at https://github.com/PowerShell/PowerShell/, but have been informed that the issue resides with pnp

Can you point us to the issue directly please? Or tell us what was their answer?

**Comment by larnera** [comment]
Thanks @veronicageek, 

I originally raised the issue here: https://github.com/PowerShell/PowerShell/issues/15468. They said it was an issue with PnP which I questioned given it worked fine on PowerShell 5.1.

Good suggestion, I've tested using a different module (Microsoft Graph -  https://www.powershellgallery.com/packages/Microsoft.Graph/1.5.0) and the same issue occur: 

**Microsoft Graph PowerShell 7.1**

![image](https://user-images.githubusercontent.com/2369339/121004358-81abd800-c786-11eb-9ae7-f0ba119b4fb1.png)

**Microsoft Graph PowerShell 5.1**

![image](https://user-images.githubusercontent.com/2369339/121004427-938d7b00-c786-11eb-8422-32babee18c10.png)

**Comment by veronicageek** [comment]
I've seen you've reopened their issue, so I'll close this one as this is not PnP.PowerShell specific.

**Comment by TravisEz13** [comment]
@veronicageek We have truly little we can do from the PowerShell side.  The module controls the header it uses to connect to a service.  In this case, you need to adjust your code to deal with this issue.  PowerShell does not server as a middleman between .NET and the module for a C# module.  In fact, it looks like if we tried, you would override our settings:

https://github.com/pnp/powershell/blob/0120ed972265a949a17b40f8ed3d3dd99efacc61/src/Commands/Base/PnPConnection.cs#L563

They are sending the PowerShell assembly version in the `UserAgent`.  For windows PowerShell this can be mapped to an OS Version, but for PowerShell 6.0 and newer, this cannot.  I don't know where this contract is defined or who can modify it, but this assembly is the one that needs to be updated.

**Comment by erwinvanhunen** [comment]
We have added now the Operating System identifier to the user agent. Please try again with the upcoming nightly build: 1.6.2 which will be available tomorrow:

install-module -name PnP.PowerShell -AllowPrerelease

**Comment by larnera** [comment]
Hi @erwinvanhunen. Thanks, but this hasn't fixed the issue. 

PowerShell 5.1

![image](https://user-images.githubusercontent.com/2369339/121363871-37b22600-c92f-11eb-8b5a-20de40d27e78.png)

![image](https://user-images.githubusercontent.com/2369339/121363897-3b45ad00-c92f-11eb-83cb-7ed301299b68.png)

PowerShell 7.1

![image](https://user-images.githubusercontent.com/2369339/121363938-43055180-c92f-11eb-8174-9324e9e8ef9a.png)

![image](https://user-images.githubusercontent.com/2369339/121363955-47316f00-c92f-11eb-9f8f-14b295f11bfb.png)

This probably doesn't make a difference, but running "Connect-PnPOnline -Url https://xxx.sharepoint.com -Credentials (Get-Credential)" in PowerShell 5.1, the Windows PowerShell credential request window appears whereas in PowerShell 7.1 is doesn't.

**Comment by erwinvanhunen** [comment]
Unfortunately we do not have access to an Azure Premium AD subscription to test it ourselves, so it will be bit of a miss or hit effort. It could be that it doesn't recognize the string we're sending (we are sending currently 'Windows'). I will update the code (available in the next nightly build, 1.6.3-nightly, to state "Microsoft Windows NT 10.0.19043.0" e.g. the full OS version string.

**Comment by larnera** [comment]
Ok, thank you. I'll try again tomorrow.

**Comment by larnera** [comment]
Still not appearing I'm afraid:

![image](https://user-images.githubusercontent.com/2369339/121505049-633e1a80-c9da-11eb-8664-673d029fe930.png)

![image](https://user-images.githubusercontent.com/2369339/121506495-acdb3500-c9db-11eb-928b-06ecb43e84bd.png)

I have a E5 dev tenant I'm using to test this. I'm happy to give you access if it'll help you in resolving this issue?

**Comment by Panzerbjrn** [comment]
As I may have a related issue in #904 , is this something that is being worked on?

**Comment by larnera** [comment]
I really hope so @Panzerbjrn. This issue is preventing our team from moving to latest version of PowerShell and PnP.

**Comment by larnera** [comment]
Hi @veronicageek. Can this be worked on please? We are great fans of PnP but sadly feeling disappointed that this is still an issue for us after two months of raising this.

**Comment by veronicageek** [comment]
Tagging @gautamdsheth and @KoenZomers to see if they can look at it or if there's anything more we can do (Erwin already changed things so not sure what more can be done)

**Comment by Panzerbjrn** [comment]
So, do you believe that this bug has been fixed? If your module won't run on pwsh, then it's not going to be very useful for a lot of people.

**Comment by KoenZomers** [comment]
I could reproduce the issue. Took me a bit to figure out where the magic happened, but the above PR should fix this issue.

**Comment by Panzerbjrn** [comment]
good stuff, I'll try to test it out tonight or over the weekend.

**Comment by KoenZomers** [comment]
Unfortunately you cannot test it yet unless you build a custom version of PnP Framework out of my branch and compile your own custom PnP PowerShell build against that. We have to wait for @jansenbe to return from vacation to approve the PR so it can be included in the next nightly build. From thereon you will be able to easily test this yourself by updating your PnP PowerShell to the latest prerelase version.

**Comment by KoenZomers** [comment]
PR in PnP Framework has been merged. You can try it with the nightly build of **tomorrow** to see if the issue is resolved for you. Please provide feedback if this topic can be closed after validating this.

**Comment by larnera** [comment]
Brilliant! Tested using 1.7.38 (nightly) and PowerShell 7.1.4 and "Operating System" is now coming through in AAD so no more conditional policy failures! Thank you @KoenZomers for fixing this and @veronicageek for your help too. 

![image](https://user-images.githubusercontent.com/2369339/131897939-1274dbff-b66c-4a5c-b1cf-ab6ba101d2db.png)

**Comment by Panzerbjrn** [comment]
This sounds great, thanks. When will it be available on the PS Gallery? The version there is still 1.7.0.
