### ISSUE TITLE
[BUG] ConvertTo-PnPClientSidePage incorrect URL transformation for links in /teams/ managed path

### ISSUE THREAD

**Issue by jwiersem** [pnp/powershell#743]
### Reporting an Issue or Missing Feature
When using the ConvertTo-PnPClientSidePage commandlet with a URL mapping file, some links that should not be transformed are transformed and result in broken links. The below URL is not present in the URL mapping file used.
Example: https://ourtenant.sharepoint.com/teams/electrical-system-concepts-and-designs/Pages/Home.aspx is transformed into https://ourtenant.sharepoint.com/teams/electrical-system-concepts-and-designs**/sites/brand-sectors-bf-de-edev-DUV-JWTEST17/APES/sitepages/Home.aspx**.
As you can see the whole relative url of the target site is append after the original URL. The migration is from on prem sp2013 server into SharePoint Online.
I've tried the command with -SkipDefaultUrlRewriting but then other URLs are transformed incorrectly.

The commandlet is used as such:
`$aNewPage = ConvertTo-PnPClientSidePage -Identity $pageFileName -PublishingPage -UrlMappingFile $global:urlMappingFilePath -PageLayoutMapping $global:pageLayoutMappingFilePath -TargetConnection $targetWebConnection -LogVerbose -LogType File -LogFolder "$($global:logFolder)\TransformationLogs" -Connection $sourcewebconnection -ClearCache -Overwrite;`
                
### Expected behavior 
This particular URL to a classic site in SPO should not be transformed and stay the same as in on prem 2013

### Actual behavior 
URL: https://ourtenant.sharepoint.com/teams/electrical-system-concepts-and-designs/Pages/Home.aspx 
is transformed into 
https://ourtenant.sharepoint.com/teams/electrical-system-concepts-and-designs/sites/brand-sectors-bf-de-edev-DUV-JWTEST17/APES/sitepages/Home.aspx.

### Steps to reproduce behavior
Create an on prem sp2013 publishing page with a link to an SPO classic site under the /teams/ managed path and convert the page into a SPO communication site.

### What is the version of the Cmdlet module you are running?
SharePointPnPPowerShellOnline
3.29.2101.0
The PnP.Powershell module does not work for me due to this issue: https://github.com/pnp/powershell/issues/200 
### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows

**Comment by KoenZomers** [comment]
@jwiersem is this issue still occurring and blocking you? We won't be touching the SharePointPnPPowerShellOnline library anymore, so focusing on that is not an option. In the issue you reference regarding not being able to use PnP.PowerShell I see someone reporting it was resolved for him/her. Can you indicate if this issue still needs attention from you?

**Comment by jwiersem** [comment]
Guess you can close this issue, if no one else is experiencing it for the new module. If more people get it then perhaps they'll find it and re open.
