### ISSUE TITLE
[BUG] Failure of getting item properties in Document libraries depending on Sharepoint sites

### ISSUE THREAD

**Issue by Kman-Kid** [pnp/powershell#744]
### Context:

I am trying to get all files and their versions located in our Sharepoint. In order to do so I iterate through all the Document-Libraries and throgh all items of the respective Library. Then getting the individual version.

The script works just fine in 7 out of 12 Shared-Document Libraries.

### Code:

Connection and accesing the Shared-Document Library works fine so i will skip that.

_Getting the items (Collection of File Versions and Metadata / Type: PnPFolderItem) in the Library and subfolders (Type: PnPFolder):_
`$folderItems = Get-PnPFolderItem -FolderSiteRelativeUrl $FolderName -Connection $currentConn -Recursive`

If it is a "faulty" Library the following loop is skipped, meaning `$versions` has no items

_While iterating through the $folderItems getting the "versions" property of each item:_
`$versions = Get-PnPProperty -ClientObject $item -Property Versions -Connection $currentConn`

_For-each Loop to prepare Output / Store information:_
`foreach($ver in $versions) #$item.Versions`
        `{`                    
            `$ver.RefreshLoad()`
            `$createdbyinfo = Get-PnPProperty -ClientObject $ver -Property CreatedBy`
            `$Row = "" | Select Name,Version,Created,Email,Comment`
            `$Row.Name = $item.Name`
            `$Row.Version = $ver.VersionLabel`
            `$Row.Created = $ver.Created`
            `$Row.Email = $createdbyinfo.Email`
            `$Row.Comment = $ver.CheckInComment`
            `$VersionsInfoList += $Row`
        `}`

### Expected behavior 
Should function for all Shared-Documents Libraries

### Actual behavior 
Does not function for all Shared-Document Libraries

### Steps to reproduce behavior
Since it is working just fine on some Libraries, I can not think of a way to reproduce this problem, without solving it first.

### Version / OS
PnP.Powershell 1.5.0 on Windows 10

### Edit / Script:
This is the script to get the different versions of a file in the respective library / page.

```
#Site root
$sharepointsiteroot = "https://tenant-name.sharepoint.com/sites"

function ProcessSPDocFolder
{
param(
    [string]$Site,
    [string]$FolderName
)    

    $VersionsInfoList = @()

    if([string]::IsNullOrEmpty($FolderName))
    {
        return $VersionsInfoList
    }

    Write-Output $Site
    Write-Output $FolderName
	#Connection to Site
    $currentConn = Connect-PnPOnline -Interactive -Url $Site
	#Getting all Files of whole Library
    $folderItems = Get-PnPFolderItem -FolderSiteRelativeUrl $FolderName -Connection $currentConn -Recursive

	#Iterating through all Files
    foreach($item in $folderItems)
    {  
        if ($item -is [Microsoft.SharePoint.Client.Folder])
        {
            continue
        }
		
		#Getting all versions of a file
        $versions = Get-PnPProperty -ClientObject $item -Property Versions -Connection $currentConn

		#Getting metadata for all versions of a file
        foreach($ver in $versions)
        {                     
            $createdbyinfo = Get-PnPProperty -ClientObject $ver -Property CreatedBy
           
            $Row = "" | Select Name,Version,Created,Email,Comment
            $Row.Name = $item.Name
            $Row.Version = $ver.VersionLabel
            $Row.Created = $ver.Created
            $Row.Email = $createdbyinfo.Email
            $Row.Comment = $ver.CheckInComment
            $VersionsInfoList += $Row
        }
    }
    return $VersionsInfoList
}


#Connecting to site root
$generalConnection = Connect-PnPOnline -Interactive -Url $sharepointsiteroot

#Declaring Output
$history = @()


#Name of site
$mysubsite = "subsite"

#Folder Path of Site
$myfoldersubsite = "Shared Documents/subfolder"

#Calling the function with site individual parameter
$history = ProcessSPDocFolder "$sharepointsiteroot/$mysubsite" $myfoldersubsite

$history | Sort -Property Created -Descending | Format-Table Name, Version, Created, Email, Comment

Disconnect-PnPOnline
```

**Comment by Kman-Kid** [comment]
If something is unclear or additional information needed feel free to contact me or leave a comment.

**Comment by veronicageek** [comment]
@Kman-Kid - Can you clarify what you're looping through? 
- Is it all libraries in all SPO sites in the tenant? You also mention subsites in the title?
- What do you mean by `Shared-Document Libraries`? (is it only a normal library?)
- Is there any difference between the 7 libraries working and the 5 others?

**Comment by Kman-Kid** [comment]
@veronicageek Thank you for the questions and sorry for the inaccuracy.

> Can you clarify what you're looping through?

I am iterating through the FileVersionCollection of a file in a folder of an Library

> Is it all libraries in all SPO sites in the tenant? You also mention subsites in the title?

Yes, all libraries in all SPO sites in the tenant. I just got confused with the subsites, sorry.

> What do you mean by Shared-Document Libraries? (is it only a normal library?)

Since almost all files are documents I was tempted to say shared documents. They are indeed normal libraries.

> Is there any difference between the 7 libraries working and the 5 others?

There is not an obvious difference, we looked carefully and since they are on the same access-level it should work just fine. Path misspelling could also be ruled out. 


Further Information:

The script loads the files of a faulty library, but it is not possible to iterate through the FileVersionCollection for these faulty libraries/folders. You can output the name of the file, but not this individual property.

I am not changing tenant only the sites, the root URL(https://tenant-name.sharepoint.com) stays the same.

Example path to a library:
https://tenant-name.sharepoint.com/sites/SiteName/Shared Documents/

Question:
Is it possible to provoke / cause a verbose error message?

Thanks for the comment.

With kind regards 

David

**Comment by veronicageek** [comment]
@Kman-Kid - Thanks for all this information. So you're going through multiple sites, targeting only 1 document library (`/Shared Documents`), you want to get **each version** of each file (even in nested folders), and you have access to all. Correct?

If yes: 
- How many sites are you looping through?
- Any idea of the number of files/folders to iterate through?
- Is it always failing on the _same_ 5 document libraries?

Thanks

**Comment by Kman-Kid** [comment]
@veronicageek

> So you're going through multiple sites, targeting only 1 document library (/Shared Documents), you want to get each version of each file (even in nested folders), and you have access to all. Correct?

Yes that is correct.

> How many sites are you looping through?

I am Looping through 12 sites.

> Any idea of the number of files/folders to iterate through?

It Depends on the Site. Some Sites have 1 Folder and only about 9 Files, some have 5+ Folders and over 50 Files.

> Is it always failing on the same 5 document libraries?

Yes it is failing on the same document libraries?

Further Information:

I forgot to mention that we have run the script on different PCs with different User-Accounts, result stays the same.

**Comment by veronicageek** [comment]
Removing the bug label as I believe the cmd works and might be different issue more with the libraries or the files.
Obvious question but can you make sure that versioning is enabled on the libraries? Also try other troubleshooting steps like create another library in the same site, populate with dummy docs, and run your script.

**Comment by Kman-Kid** [comment]
I will try the suggested troubleshooting steps, I'm pretty sure versioning is enabled on the affected sites but will check again.
Thanks for the comment.

**Comment by veronicageek** [comment]
Closing as not a PnP issue.

**Comment by veronicageek** [comment]
What would make you think that `AccessPolicy` is related to not getting the file versions?

```powershell
$allDocs = Get-PnPListItem -List "Documents" -Fields "FileLeafRef", "_UIVersionString", "AccessPolicy"
$results = @()

foreach($doc in $allDocs){
    $results += [pscustomobject][ordered]@{
        fileName = $doc["FileLeafRef"]
        fileVersion = $doc["_UIVersionString"]
        AccessPolicy = $doc["AccessPolicy"]
    }
}
$results
```

![image](https://user-images.githubusercontent.com/25181757/121548779-381cf080-ca05-11eb-95c5-e4c2ef98f372.png)
