### ISSUE TITLE
Set-PnPSite -LockState not working on SP 2013 On prem

### ISSUE THREAD

**Issue by MaxKraft** [pnp/powershell#745]
Hi,
Set-PnPSite -LockState does not exist on SP 2013 On prem.
Thanks for considering this issue.
Best regards
Hamed

**Comment by veronicageek** [comment]
Hi - This repo is now only supporting SharePoint Online. You can still refer to the (old) [SharePointPnPPowerShell*](https://github.com/pnp/pnp-powershell) to see if working, but we don't support SharePoint on-prem unfortunately.
