### ISSUE TITLE
Add-PnPFile couldn't add files to the site collection root folder however Get-PnPfolder -Url "/sites/xxx/" is functioning

### ISSUE THREAD

**Issue by mohammadamer** [pnp/powershell#747]
### Reporting an Issue or Missing Feature
An issue when using Add-PnPFile to add files to the root folder of a communication site however it works with classic site.

### Expected behavior 
Expected to add files to a communication site root folder the same like a classic site.
It works when adding file to the root site folder of a classic site.
## Command:
` Add-PnPFile -Path .\sw.js -Folder "/sites/mySite/"`
`Error: Add-PnPFile: The object specified doesn't belong to a list.`
## Note
There is an error with adding the file to the classic site but file is actually added when I checked for it.

### Actual behavior 
Got the following errors when trying to add a file to a communication site using the following command.

## Command:
` Add-PnPFile -Path .\sw.js -Folder "/sites/mySite/"`
`Error: Add-PnPFile: Access denied. You do not have permission to perform this action or access this resource.`

## Also I tried the following Command:
` Add-PnPFile -Path .\sw.js -Folder "/"`
`Error: Add-PnPFile: Server relative urls must start with SPWeb.ServerRelativeUrl`

### What is the version of the Cmdlet module you are running?
PnP.PowerShell version: 1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows

**Comment by Kman-Kid** [comment]
I have the same problem, however it does not work at all for me. 
I just try to upload a test file to the Shared Documents Library. 
This works on my test tenant/sharepoint but not on the sharepoint where the script should run. 
I have found out so far that if I enter a wrong path as parameter, I get the same error. 
The error as I understand it can therefore also mean that under the entered path no valid folder can be found. 
Also doesnt work with absolute Paths as for Example:
```-Folder "https://tenant-name.sharepoint.com/sites/SiteName/Shared` Documents"```
The fact that it works on my test sharepoint leads me to believe that it's the sharepoint settings, but I haven't found any different settings yet and I'm stuck. 
Sorry I can't help you but I thought it might be reassuring that someone else is having a similar problem.

**Comment by mohammadamer** [comment]
In my case:
Although I got the following error when I tried to do it with classic site but the file added to the root folder.
`Error: Add-PnPFile: The object specified doesn't belong to a list.`

But for a communication site I got different error and file hasn't added to the root folder.
`Error: Add-PnPFile: Access denied. You do not have permission to perform this action or access this resource.`

It works for adding files to documents library.

**Comment by mohammadamer** [comment]
Hi @jansenbe 
Could you please help us in this issue.

**Comment by KoenZomers** [comment]
I happened to run into the same for a different use case. May have fixed it through https://github.com/pnp/powershell/pull/764 . Did you also experience that it did actually copy the file, even though it threw the `Error: Add-PnPFile: The object specified doesn't belong to a list.` exception?

**Comment by KoenZomers** [comment]
PR has been merged, so @mohammadamer please try your scenario again with the latest nightly build tomorrow and see if the issue persists for you.

**Comment by wonderplayer** [comment]
Hey @KoenZomers 
I can elaborate on this a bit as well.
I will try tomorrow to run that command with nightly build and expect to receive no error for trying to add files to non-document library folder. Yes, the file was still uploaded, so that wasn't the main issue.
The main issue here is with modern sites, that you can't actually add files to non-document library folders.
Try to run:
```
$web = Get-PnPWeb
$folder = Get-PnPFolder -Url "$($web.ServerRelativeUrl)/_cts"
Add-PnPFile -Path $filePath -Folder $folder
```

I can get the folder, but can't add any file to it.
So, we were wondering, is this PnP.PowerShell module issue or SharePoint Online Modern sites limitation.

I used following CSOM code (from [here](https://andrewwburns.com/2014/02/03/upload-a-file-with-csom/)) to try it with pure CSOM:
```
internal static File UploadFile(ClientContext clientContext, Web web, string filePath, Folder folder, string fileName, string title)
{
 string target = folder.ServerRelativeUrl + "/" + fileName;
FileCreationInformation fci = new FileCreationInformation();
 fci.Overwrite = true;
 fci.Url = target;
 fci.Content = System.IO.File.ReadAllBytes(filePath);
File uploadedFile = folder.Files.Add(fci);
 uploadedFile.ListItemAllFields["Title"] = title;
 uploadedFile.ListItemAllFields.Update();
 clientContext.ExecuteQuery();
if (uploadedFile.CheckOutType != CheckOutType.None)
 {
 uploadedFile.CheckIn("Initial Upload", CheckinType.MajorCheckIn);
 }
 clientContext.Load(uploadedFile);
 clientContext.ExecuteQuery();
 return uploadedFile;
}
```
But also got `Access denied` error.
We really need to upload a file to root folder of modern site, so it would be such a bummer if this would not be possible 😔

**Comment by KoenZomers** [comment]
Check. That's because of NoScript being enabled likely. Try switching that off and see if it works. I'll bet you it will work. It's a server side protection and even documented on docs.microsoft.com.

**Comment by wonderplayer** [comment]
Checked `Add-PnPFile` command and can confirm that no error is thrown now for adding files to non-document library folder.
And yeah, you were absolutely right! Didn't even think that DenyAddAndCustomizePages was the one who didn't allow that.
I can see in [here](https://docs.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script), that this limits adding documents to content types. Guess any folder that is a non-document library folder falls under this criterion then.

Anyway, thank you very much 😊

**Comment by gautamdsheth** [comment]
@mohammadamer - can you try with the latest nightly as well and check ?

**Comment by gautamdsheth** [comment]
Closing this issue as it has been fixed. Please reopen it if its not fixed at your end with the latest versions.
