### ISSUE TITLE
[BUG] Set-PnPTeamsTeamPicture: File is not of a supported content type (jpg/png)

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#749]
### Reporting an Issue or Missing Feature
This is a bug

### Expected behavior 
Set-PnPTeamsTeamPicture should process files regardless of the register the file name is in

### Actual behavior 
When a file extension is capitalized, cmdlet throws an error:
`File is not of a supported content type (jpg/png)`
![image](https://user-images.githubusercontent.com/5260172/120247729-32910f00-c27d-11eb-8722-dfead04f9390.png)

### Steps to reproduce behavior

1. Make yourself an owner of the team
2. Connect to PnP Online
3. Have an image file extension written in capital letters
4. Run command:
```
Set-PnPTeamsTeamPicture -Team Team.Name -Path "C:\image.PNG"
```

### What is the version of the Cmdlet module you are running?
![image](https://user-images.githubusercontent.com/5260172/120248044-5012a880-c27e-11eb-97f9-7e76cf228c34.png)

`PnP.PowerShell 1.5.59`

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Have fixed this issue, will be available in tomorrows nightly !
Thanks for reporting.
