### ISSUE TITLE
[BUG] can't report TimeZoneID of Sites

### ISSUE THREAD

**Issue by J-a-k-o-b** [pnp/powershell#754]
Can't read out the TimeZoneID, when using Get-PNPTenantSite. With the old module "sharePointpnppowershellonline" the value was included. Can't find any other way to read out the time zone configured for a SPO Site

Output using the old PNP Module:
![image](https://user-images.githubusercontent.com/46894290/120455577-2e581500-c395-11eb-8e1f-a7fe320f2b43.png)

Output using the actual PNP Module:
![image](https://user-images.githubusercontent.com/46894290/120455637-3b750400-c395-11eb-986a-a08c1e3e1d49.png)

I'm using the pnp.powershell module in the Version 1.5.33. The sharepointpowershellonline module is installed in Version  3.29.2101.0

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows

**Comment by LeonArmston** [comment]
Hi Jakob

I've had a look and it doesn't look like TimeZoneId is there anymore in the site collection level.

Time in SharePoint is stored at the web (site) level so you can get it by connecting using Connect-PnPOnline to the site you wish to get the time zone from then running the commands below:

```powershell
$web = Get-PnPWeb -Includes RegionalSettings.TimeZone

$web.RegionalSettings.TimeZone
```

Not sure if the old Get-PnPTenantSite had some workaround to connect to the web to retrieve the timezoneid...

**Comment by J-a-k-o-b** [comment]
Hi Leon,
that would explain this issue, but unfortunately you need to have permssions for every site when running this, which I want to avoid. I'm curious how the workaround could have worked, maybe we can use it again somehow.
