### ISSUE TITLE
[BUG] Cannot edit pages in a folder with the Set-PnPPage command.

### ISSUE THREAD

**Issue by MakotoIshikawa** [pnp/powershell#755]
## Problems / errors that are occurring

```
$NewPage = Add-PnPPage -Name 'Folder/NewPage'
```

The `/SitePages/Folder/NewPage.aspx` page is created.

```
Set-PnPPage -Identity $NewPage -Title 'My Page'
```

When I try to change **PageTitle** by specifying the return value of **Add-PnPPage** to the parameter **Identity** ...

- A new page (`/SitePages/NewPage.aspx`) with the same name is created directly under the site page separately from the page under the folder, and the title of that page is changed.

**Comment by veronicageek** [comment]
@MakotoIshikawa 
If you reference the variable which contains the `Add-PnPPage` it will create a new page.

You can create the page & change the title with the following:

```powershell
$newPage = 'Folder/NewPage'
Add-PnPPage -Name $newPage | Set-PnPPage -Name $newPage -Title 'My Page'
```

It will create your page in the folder, and update the title to `My Page` at the same time.

**Comment by MakotoIshikawa** [comment]
## What I tried myself

If you try to specify a fixed value set in Add-PnPPage for Identity, you will get an error.

```
Set-PnPPage -Identity 'Folder/NewPage' -Title 'My Page'
Set-PnPPage : Page Folder/NewPage.aspx cannot be found.
発生場所 行:1 文字:1
+ Set-PnPPage -Identity 'Folder/NewPage' -Title 'My Page'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPPage], Exception
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Pages.SetPage
```

**Comment by MakotoIshikawa** [comment]
@veronicageek 
When I changed the version to 1.6.0, I was able to change the title in the above source.
