### ISSUE TITLE
[BUG] Connect-PnPOnline is not fit for purpose for Tenancies which do not allow Delegated Rights

### ISSUE THREAD

**Issue by NPrice99** [pnp/powershell#758]
### Reporting an Issue or Missing Feature
If you are on a Tenancy which does not allow Delegated Rights, then Connect-PnPOnline will not work for subsequent PowerShell commands eg Invoke-PnPSiteTemplate which thows an exception "Access Denied - You Do Not Have permissions to perform this action or access this resource"

### Expected behavior 
On the Previous version of PnP SharePoint Online as written by Erwin and Vesa's team This worked perfectly.

I expect this to work on the version 1.4.0 

### Actual behavior 
See above

### Steps to reproduce behavior
Connect-PnPOnline -Url https://kkhkhkhk etc -Interactive

Invoke-PnPSiteTemplate

### What is the version of the Cmdlet module you are running?
1.4.0

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by NPrice99** [comment]
WE need a version which does not use the Graph interface eg. Apply-PnPProvisioningTemplate in the good old days (pre graph interface - sorry Mr Thake !)

**Comment by veronicageek** [comment]
@NPrice99 

> On the Previous version of PnP SharePoint Online as written by Erwin

@erwinvanhunen IS the creator of both modules, the new PnP.PowerShell (this repo) is now exclusively maintained for SharePoint Online, and is cross-platform (for use on Windows, MacOS, Linux)

> Tenancy which does not allow Delegated Rights, then Connect-PnPOnline will not work

The PnP.PowerShell module & the authentication are dependent on SharePoint Online / MSFT and other changes in the underlying SDKs, so we cannot bypass that. 

> I expect this to work on the version 1.4.0

We are currently on `1.5.0` for the Major release, or you can also update to the `-nightly` releases (currently `1.5.62-nghtly`)
You can update using `Update-Module PnP.PowerShell -AllowPrerelease`.

**Comment by NPrice99** [comment]
So I am confused.  Does Invoke-PnPSiteTemplate + Connect-PnPOnline work without using the Graph Interface.  The enterprise I am working with says using the graph interface requires you to have too many permissions and will not sanction its use.

**Comment by veronicageek** [comment]
You can setup your own Azure AD Application with your own permissions if the `Register-PnPManagementShellAccess` is giving too many for your scenario, and then authenticate. Here is the link to our [documentation](https://pnp.github.io/powershell/articles/authentication.html).

Some commands require access to MS Graph (i.e.: Microsoft 365 Groups), and like I mentioned, other changes in the underlying SDKs do not allow us to have the exact same configuration as there was in the old module.

**Comment by gautamdsheth** [comment]
Please read these docs as well- 

https://pnp.github.io/powershell/articles/connecting.html

and 

https://pnp.github.io/powershell/articles/upgrading.html

The way authentication works has changed. We use OAuth behind the scenes to authenticate. 
The PnP Management Shell requests delegate permissions only. So, only if have valid permissions will you be able to create Teams/Groups/Graph stuff etc. 
Having said that, enterprises do have valid concern. 
So, you can create your own Azure AD app and connect to SPO using only the permissions that you wish to grant the necessary permissions i.e in your case SharePoint permissions.

Once you have done that, you can connect using:

`Connect-PnPOnline "<your-url>" -ClientId <your-client-id> -Creds <your-creds>`

or using certificates etc as well.

Weblogin works in windows only, if that suits you can keep using that.
We also support the old ClientId/ClientSecret, the one created via appregnew.aspx page.

**Comment by veronicageek** [comment]
Closing as there's no issue.
