### ISSUE TITLE
[BUG] Connect-PnPOnline throws "Could not load file or assembly 'Microsoft.Extensions.Logging, Version=2.2.2.0...'"

### ISSUE THREAD

**Issue by JelleBroekhuijsen** [pnp/powershell#759]
### Reporting an Issue or Missing Feature
When executing 'Connect-PnpOnline' with the following parameters (see below) an error is thrown (see below). 

### Expected behavior 
The module connects to the site at -Url.

### Actual behavior 
![image](https://user-images.githubusercontent.com/58708777/120663617-786ef280-c48a-11eb-87dd-02b9d74dbeca.png)

### Steps to reproduce behavior
`Connect-PnPOnline -ClientId $config.ClientId -CertificateBase64Encoded $base64AuthenticationCertificate -Tenant $config.Tenant -Url $QueueItem`

### What is the version of the Cmdlet module you are running?
![image](https://user-images.githubusercontent.com/58708777/120664183-034fed00-c48b-11eb-8acb-7ff176ed1ab7.png)

![image](https://user-images.githubusercontent.com/58708777/120663951-cedc3100-c48a-11eb-9f0f-861305a15e0a.png)

Also tested in 1.5.61-nightly.

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [x] Azure Functions
(issue reproduced in both environments)

**Comment by JelleBroekhuijsen** [comment]
Also tested with interactive log in; same behaviour:

**Comment by JelleBroekhuijsen** [comment]
The issue seems to be related to the Az-module; issue only occurs when this module is loaded in the environment.

This works:
```
Import-Module Az.Accounts
Import-Module Az.KeyVault
Import-Module PnP.PowerShell

$allCertificates = Get-AzKeyVaultCertificate -VaultName $config.KeyVault 
Foreach ($certificate in $allCertificates) {
    $fullCertificateDetails = Get-AzKeyVaultCertificate -VaultName $config.KeyVault -Name $certificate.Name
    if ($fullCertificateDetails.Thumbprint -eq $config.CertficateThumbprint) {
        $base64AuthenticationCertificate = Get-AzKeyVaultSecret -VaultName $config.KeyVault -Name $certificate.Name -AsPlainText
        break
    }
}

Connect-PnPOnline -ClientId $config.ClientId -CertificateBase64Encoded $base64AuthenticationCertificate -Tenant $config.Tenant -Url $QueueItem
```

And this generates the error:

```
Import-Module Az
Import-Module PnP.PowerShell

$allCertificates = Get-AzKeyVaultCertificate -VaultName $config.KeyVault 
Foreach ($certificate in $allCertificates) {
    $fullCertificateDetails = Get-AzKeyVaultCertificate -VaultName $config.KeyVault -Name $certificate.Name
    if ($fullCertificateDetails.Thumbprint -eq $config.CertficateThumbprint) {
        $base64AuthenticationCertificate = Get-AzKeyVaultSecret -VaultName $config.KeyVault -Name $certificate.Name -AsPlainText
        break
    }
}

Connect-PnPOnline -ClientId $config.ClientId -CertificateBase64Encoded $base64AuthenticationCertificate -Tenant $config.Tenant -Url $QueueItem

```

**Comment by gautamdsheth** [comment]
Can you try with the latest PnP PowerShell , 1.6.0 and check ? Also, maybe you can try switching the order i.e load PnP first and then load Az module and check ?

**Comment by JelleBroekhuijsen** [comment]
I checked it with the latest as well, same behaviour. Switching the order of modules leads to a different, but similar error:

![image](https://user-images.githubusercontent.com/58708777/121320246-44258700-c90d-11eb-9f39-108d5fcddc68.png)

**Comment by patrikhellgren** [comment]
We are also seeing the exact same issue (about Microsoft.Extensions.DependencyInjection.Abstractions) using PnP.PowerShell 1.6.0 and Az 6.1.0.
The workaround with loading the modules separately doesn't seem to work for us but we are using different Az modules:
```
Import-Module Az.Accounts
Import-Module Az.Resources
Import-Module PnP.PowerShell
Connect-AzAccount
Get-AzResourceGroup
Connect-PnPOnline -Url https://<tenantname>.sharepoint.com -Interactive
```
This throws the same exception, i.e. ```Connect-PnPOnline: Could not load file or assembly 
 Microsoft.Extensions.DependencyInjection.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (0x80131621)```

The module load order does not seem to make a difference either.

**Comment by ThePoShWolf** [comment]
Hello! I am also receiving an error when attempting to use the PnP.PowerShell module and some of the AZ modules. Here is the relevant code:

```powershell
Import-Module Az.Resources
Import-Module Az.Storage
Import-Module PnP.PowerShell
Connect-PnPOnline -Url $WebUrl -DeviceLogin
```
Here is the error I'm getting:

```text
Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (0x80131621)
Connect-PnPOnline: Unable to connect using provided arguments
```
Here are the module versions:

```powershell
PS>Get-Module Az.Resources

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     4.2.0                 Az.Resources                        {Add-AzADGroupMember, Export-AzResource…

PS>get-Module Az.Storage

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     3.8.0                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add…

PS>Get-Module PnP.PowerShell

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   1.6.0                 PnP.PowerShell                      {Add-PnPAlert, Add-PnPApp, Add-PnPAppli…
```

**Comment by gautamdsheth** [comment]
Sorry a little late, but can you give this a try with latest nightly build ? 

`
Import-Module PnP.PowerShell
Import-Module Az.Resources
Import-Module Az.Storage
`

I switched the order here .

![image](https://user-images.githubusercontent.com/8832018/126635432-be45b9a3-e311-401f-b4bf-dfc3c93590bc.png)

**Comment by veronicageek** [comment]
Closing as no answer.
