### ISSUE TITLE
Initialize-PnPPowerShellAuthentication : The term 'Initialize-PnPPowerShellAuthentication' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/powershell#76]
### Reporting an Issue or Missing Feature
Initialize-PnPPowerShellAuthentication : The term 'Initialize-PnPPowerShellAuthentication' is not recognized as the name of a cmdlet
### Expected behavior 
Initialize-PnPPowerShellAuthentication  does not exist in Module -Name PnP.PowerShell

#
### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   0.3.23     PnP.PowerShell
### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
Hi @Ofer-Gal - Indeed, I can see the **PnP** prefix is missing from the command, although the documentation is correct.
@erwinvanhunen - FYI

![image](https://user-images.githubusercontent.com/25181757/103466150-25a5d900-4d3a-11eb-845f-fb0536540002.png)

**Comment by erwinvanhunen** [comment]
The cmdlet has been renamed to Add-PnPAzureADApp since version 0.2.15. Please check the changelog.

There should be stil be an alias pointing to the old name. If not correct I'll fix that in an upcoming release.

**Comment by erwinvanhunen** [comment]
Correction, it's called Register-PnPAzureADApp. The alias was not set up correctly, and that will be fixed in the nightly build which will be available tomorrow.

**Comment by Ofer-Gal** [comment]
Thank you All

**Comment by AndersRask** [comment]
@erwinvanhunen just a headsup:
the documentation was not updated to reflect this!
this works
https://docs.microsoft.com/da-dk/powershell/module/sharepoint-pnp/initialize-pnppowershellauthentication
but this gives 404 (also when you do a Get-Help Register-PnPAzureADApp -Online)
https://docs.microsoft.com/da-dk/powershell/module/sharepoint-pnp/register-pnpazureadapp

**Comment by erwinvanhunen** [comment]
Hi Anders,

We are aware of that. The documentation you refer to is about the 'legacy' version of PnP PowerShell which still uses Initialize-PnPPowerShellAuthentication.  The new documentation can be found at https://pnp.github.io/powershell/cmdlets. We have updated all the online links too in the latest builds of PnP PowerShell: ```Get-Help Register-PnPAzureADApp -Online```
