### ISSUE TITLE
[BUG] "The user cannot create group sites in this tenant instance."

### ISSUE THREAD

**Issue by svermaak** [pnp/powershell#77]
### Reporting an Issue or Missing Feature
Error when trying to create new Geo site using New-PnPSite

### Expected behavior 
New team site created in the correct GEO location

### Actual behavior 
New-PnPSite : {"error":{"code":"-2146232832, Microsoft.SharePoint.SPException","message":"The user cannot create group
sites in this tenant instance."}}
![image](https://user-images.githubusercontent.com/12259728/103489373-3e141180-4e68-11eb-9bb4-d09c590f5477.png)

### Steps to reproduce behavior
Connect-PnPOnline -Url "https://XXXnam.sharepoint.com" -Credentials $cred;
New-PnPSite -Type TeamSite -Title "Save to Delete" -Alias "XXXSV009" -Wait;

### Which version of the PnP-PowerShell Cmdlets are you using?
- [ ] PnP PowerShell for SharePoint 2013
- [ ] PnP PowerShell for SharePoint 2016
- [ ] PnP PowerShell for SharePoint 2019
- [X] PnP PowerShell for SharePoint Online

### What is the version of the Cmdlet module you are running?
0.3.23

### How did you install the PnP-PowerShell Cmdlets? 
- [ ] MSI Installed downloaded from GitHub
- [X] Installed through the PowerShell Gallery with Install-Module
- [ ] Other means

**Comment by erwinvanhunen** [comment]
Are you using a custom built version of PnP PowerShell? I see you use a -PreferredDataLocation parameter, which PnP PowerShell does not have on the New-PnPSite cmdlet.

**Comment by svermaak** [comment]
No, I just copied the screenshot I used for the PnP v3 issue I opened. Here's the v4 output
![image](https://user-images.githubusercontent.com/12259728/103489312-c9d96e00-4e67-11eb-8499-abde8d257af3.png)

**Comment by erwinvanhunen** [comment]
Hi,

We don't have access to a multi-geo tenant to test this ourselves, but the error message you see is being returned from the server .E.g. we do not generate that ourselves. It could be a matter of connecting to the correct location instead?

The way it works behind the scenes is that when you create a site using New-PnPSite the code will connect to

https://[url]/_api/GroupSiteManager/CreateGroupEx

The [url] part is based upon the URL you used to connect to, e.g. if you connect to https://contoso.sharepoint.com/sites/demo with Connect-PnPOnline then the REST endpoint we use behind the scenes is https://contoso.sharepoint.com/sites/demo/_api/GroupSiteManager/CreateGroupEx.

**Comment by erwinvanhunen** [comment]
btw, I was wrong regarding the -PreferredDataLocation option. It -is- available in PnP.PowerShell.

**Comment by svermaak** [comment]
Very weird. I have tried various combinations, home with PDL, connecting to GEO etc.

I can only  create Sites without o365 groups on GEO, interface works fine

**Comment by erwinvanhunen** [comment]
the UI actually uses the same endpoint, so if you run Fiddler (or use the network tab in the developer pane, F12, of your browser) you should be able to see what endpoint it is calling.

**Comment by svermaak** [comment]
Will give it a go

**Comment by svermaak** [comment]
PnPConnection.CurrentConnection.TryGetAccessToken(TokenAudience.MicrosoftGraph) returns null both on home and GEO creation, should this have a token?
![image](https://user-images.githubusercontent.com/12259728/104137332-ed646180-53ef-11eb-9bb3-594e5f71d322.png)
![image](https://user-images.githubusercontent.com/12259728/104137342-08cf6c80-53f0-11eb-8b38-9f5270e3da99.png)

**Comment by svermaak** [comment]
When I connect with
`Connect-PnPOnline -url "https://xxxnam.sharepoint.com/" -ClientId xxx -ClientSecret xxx
`
and create with
`New-PnPSite -Type TeamSite -Title "Save to Delete" -Alias "xxx0027" -Wait`

it creates in https://xxx.sharepoint.com instead of https://xxxnam.sharepoint.com

**Comment by svermaak** [comment]
Issue was account must have the same PDL as the site if done via CSOM. Doing it via portal doesn't have this requirement
