### ISSUE TITLE
[BUG] - Get-PnPTenantSite does not accurately reflect redirected site

### ISSUE THREAD

**Issue by ToddKlindt** [pnp/powershell#771]
### Reporting an Issue or Missing Feature
Get-PnPTenantSite in 1.6.0 handles redirected sites differently than 1.5.0. Instead of reporting their template as REDIRECTSITE#0 it reports the template of the site it was redirected to.

### Expected behavior 
I expect the behavior to be consistent with previous versions.

### Actual behavior 
It shows the template for the new location. This is 1.6.0:
![image](https://user-images.githubusercontent.com/2659747/121245500-b80c5480-c865-11eb-8741-0b9fa3f450a4.png)
This is how 1.5.0 behaves:
![image](https://user-images.githubusercontent.com/2659747/121245552-c65a7080-c865-11eb-8e67-5c986e2e33c3.png)

### Steps to reproduce behavior
Update to 1.6.0. Use Get-PnPTenantSite on a redirected site.

### What is the version of the Cmdlet module you are running?
1.6.0 has the problem. 1.5.0 seems to work correctly.

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
That's strange, I am guessing CSOM.
We haven't "touched" the cmdlet in this release, so maybe CSOM update may have done something, not sure :(

**Comment by ToddKlindt** [comment]
> That's strange, I am guessing CSOM.
> We haven't "touched" the cmdlet in this release, so maybe CSOM update may have done something, not sure :(

Yeah, go ahead and close it. I definitely saw this, but I could not reproduce it. I tried again on this machine and another. They both performed as expected. I'm glad I took screenshots or I wouldn't have believed it myself. :)
