### ISSUE TITLE
[BUG] from Feature Request #647 - Set/New-PnPTeamsTeam AllowCreatePrivateChannel not working

### ISSUE THREAD

**Issue by rjpc-github** [pnp/powershell#778]
Hi MS Dev Team,

We have successfully tested #647 (Set/New-PnPTeamsTeam AllowCreatePrivateChannel) on v1.5.53-nightly but now with version v1.6.0 we are getting this exception message:

_Requested value 'NotSpecified' was not found._

Regards and Thanks.

**Comment by Sheppounet** [comment]
Hi, i have the exact same error with a "Set-PnPTeamsTeam -Identity $groupId -Visibility "Private"" command.

It was working well with 1.5.0 version, but not anymore on 1.6.0.

**Comment by gautamdsheth** [comment]
Fixed it, will be available in tomorrow's nightly !
Thanks for reporting.
