### ISSUE TITLE
Can't connect when PnP PowerShell and SPO Mngt Shell are installed together

### ISSUE THREAD

**Issue by somesh-bhalerao** [pnp/powershell#780]
### Notice
BUG

I am using PnP.PowerShell 1.6.0 and trying to establish connection to SharePoint Online site.
My computer is also having SharePoint Online Management Shell install 16.0.21314.12000
![image](https://user-images.githubusercontent.com/33805667/121576665-37f11500-ca46-11eb-8075-80f045bd2a58.png)

**Code :** 
$Password = "********"
$Username = "********"
[SecureString]$SecurePass = ConvertTo-SecureString $Password -AsPlainText -Force
[System.Management.Automation.PSCredential]$Cred = New-Object System.Management.Automation.PSCredential($Username, $SecurePass)

Connect-PnPOnline -Url $siteUrl -Credential $Cred

### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
This should establish a connection with SharePoint Online

### Actual behavior 
1] If "PnP.Powershell" and "SharePoint Online Management Shell" both are installed then it do not establish a connection and give error.
Error:
![image](https://user-images.githubusercontent.com/33805667/121577402-1b091180-ca47-11eb-9dfd-299e203ee3c4.png)

_Connect-PnPOnline : AADSTS65001: The user or administrator has not consented to use the application with ID '31359c7f-bd7e-475c-86db-fdb8c937548e' named 'PnP Management
Shell'. Send an interactive authorization request for this user and resource.
Trace ID: ee768208-58a5-4900-8750-f894eebe2000
Correlation ID: 6b546f99-080d-4d7d-9df5-da2649acaedd
Timestamp: 2021-06-10 17:22:12Z
At C:\abc.ps1:10 char:1
+ Connect-PnPOnline -Url $siteUrl -Credential $Cred
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-PnPOnline], MsalUiRequiredException
    + FullyQualifiedErrorId : Microsoft.Identity.Client.MsalUiRequiredException,PnP.PowerShell.Commands.Base.ConnectOnline_

**2] If I uninstall "SharePoint Online Management Shell" and just keep PnP.Powershell then it is not giving error and establish connection to SharePoint Online Successfully** 

### Steps to reproduce behavior
A computer having both installed "PnP.Powershell" and "SharePoint Online Management Shell" run the below command.
Connect-PnPOnline -Url $siteUrl -Credential $Cred

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
![image](https://user-images.githubusercontent.com/33805667/121576969-9e763300-ca46-11eb-8d5d-cbea9329296f.png)

PnP.Powershell 1.6.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows

**Comment by veronicageek** [comment]
@somesh-bhalerao - This error is most likely because you haven't run either `Register-PnPManagementShellAccess` or created your own Azure AD app and given it the desired permissions.

Can you share a screenshot while successfully connecting to PnP.PowerShell using `Connect-PnPOnline`?

I have no problem connecting to both modules when they're installed together

![image](https://user-images.githubusercontent.com/25181757/121602944-f52c3e80-ca3f-11eb-9cd2-991f963934e8.png)
