### ISSUE TITLE
Set-PnPDefaultColumnValues [BUG]

### ISSUE THREAD

**Issue by MikkoKoskinen** [pnp/powershell#784]
### Reporting an Issue or Missing Feature
We a facing an issue to set document library field default values with Set-PnPDefaultColumnValues if the folder names have special characters like ö,ä, or č. Setting things from library settings is working correctly.

### Expected behavior 
The folders will have the default value for a field is set and the inheritance for the childs is working.

### Actual behavior 
The default metadata value for the folder is not set and the inheritance is not working.

### Steps to reproduce behavior
Running the command after the connection is opened.

Set-PnPDefaultColumnValues -List "LIST" -Folder "Ääkkösiä Testi B" -Field "INTERNAL_NAME" -Value "GUID"

The difference can be seen in the html file that is used to control these setting behind the scenes. 
For the special type of letters, the Set-PnPDefaultColumnValues makes an encoding, and this causes the error. Through the UI the encoding does not happen. More details in the image.

<img width="452" alt="SetDefault" src="https://user-images.githubusercontent.com/8733025/121665132-e2058700-cab0-11eb-956c-d866cce33476.png">

Of course, one can modify the HTML file locally and upload it back but going through all the possible letters is a pretty time-consuming thing to build.

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

Manifest   1.6.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by MikkoKoskinen** [comment]
Any idea or comments on this?

**Comment by KoenZomers** [comment]
Looking into this one now.

**Comment by KoenZomers** [comment]
Found the problem. Trying to fix it.

**Comment by KoenZomers** [comment]
Fixed it. Releasing PR.

**Comment by KoenZomers** [comment]
Above two PRs will fix this issue. One they both have been merged, the day thereafter you can download the latest prerelease of PnP PowerShell to test this. Assuming it will be fixed with these PRs, I will proceed with closing this issue. If it turns out not to work for you, feel free to reopen this issue.
