### ISSUE TITLE
Add-PnPTeamsChannel not working for private channels

### ISSUE THREAD

**Issue by othurau** [pnp/powershell#8]
this is the output I receive when I try to create a private channel (with version 0.1.10-nightly / 0.1.11-nightly)*

```
Add-PnPTeamsChannel -Team "My Team" -DisplayName "My Channel" -Private -ownerUPN "example@avira.com"

Add-PnPTeamsChannel : Navigation binding uri
'https://graph.microsoft.com/beta/users/('ObjectID')' has unexpected resource path.
ExpectedResourcePath:'/users'
At line:1 char:1
+ Add-PnPTeamsChannel -Team "My Team" -DisplayName "My Channel" - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Add-PnPTeamsChannel], PSInvalidOperationException
+ FullyQualifiedErrorId : InvalidOperation,SharePointPnP.PowerShell.Commands.Graph.AddTeamsChannel
```

for me it looks like the resource path should be more like
``https://graph.microsoft.com/beta/users('ObjectID') ``
 instead of
`https://graph.microsoft.com/beta/users/('ObjectID') `

*it's also the same with SharePointPnPPowerShellOnline 3.26.2010.0 and all other versions I tested

**Comment by erwinvanhunen** [comment]
Thank you! Indeed the URL we called was wrong. It's been fixed now and the fix will be available in the nightly build of tomorrow.
