### ISSUE TITLE
[BUG] Set-PnPListItem with Person or Group Field type, unable to set a group as value.

### ISSUE THREAD

**Issue by Tetef92** [pnp/powershell#803]
### Reporting an Issue or Missing Feature
I try to update the Author field with a Site group value, each time it return an "user not found" error. It appears that the required value is an email, but site groups don't have email address.

### Expected behavior 
Set the Persron or Group Field with a title group value.

### Actual behavior 
Set-PnpListItem with Person or Group Field accept only user value (not group)

### Steps to reproduce behavior
$Group=get-pnpGroup -Identity "DWP - Collaborateurs"
Id Title                LoginName           
-- -----                ---------           
5  DWP - Collaborateurs DWP - Collaborateurs

$Item=Set-PnPListItem -List $ListName -Identity $id -Values @{"Author" = $Group.Title }
Set-PnPListItem : L'utilisateur spécifié DWP - Collaborateurs est introuvable.

$Item=Set-PnPListItem -List $ListName -Identity $id -Values @{"Author" = $Group.LoginName }
Set-PnPListItem : L'utilisateur spécifié DWP - Collaborateurs est introuvable.

### What is the version of the Cmdlet module you are running?
ModuleType Version    Name                                ExportedCommands                                                                                                      
---------- -------    ----                                ----------------                                                                                                      
Manifest   1.6.0      PnP.PowerShell                      {Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add-PnPClientSideText, Add-PnPClientSideWebPart...}             

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@Tetef92 - I have no issue with a SPO group (Owners & Members). However, I can get your error message if the group has only `Read` permissions (Visitors group) which would be normal due to the access level.

![image](https://user-images.githubusercontent.com/25181757/122040627-f2c73d00-cdcf-11eb-8d23-b5d385c83d86.png)

What type of group is it, and what permissions are given to that group?

**Comment by Tetef92** [comment]
Hi Veronica,

Good to see that you succeed to set a group value, It give me hope :-).

Unfortunatly, I tried with a group with all required permissions (All List Permission, Site Permissions and Personal Permission).

But it still not working.

Reminber : It works with any users value, it doesn't work with any group values.

=> Still unknown user error message. Something occurs during the lookup process....

I'm using an Azure AD app authentification with Application Permissions (not delegated) : could it be related to that ?
