### ISSUE TITLE
[BUG] Set-PnpSite -LogoFilePath doesn't set logo, discriminates site with no group

### ISSUE THREAD

**Issue by skantere** [pnp/powershell#817]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
`Set-PnpSite -LogoFilePath "c:\dummy.png"`
When connected to a modern team site, I expect it to change the site logo as promised by documentation.

### Actual behavior 
The behavior depends on the type of target site and the previously set logo:

1. Modern team site with O365 Group (Template GROUP#0)
    a) if the previous logo appears to match the thumbnail, or both are absent - both appear to be changed to the supplied image;
    b) if the previously set logo doesn't match the thumbnail (for example, someone has changed the logo in GUI) - the logo does NOT get changed, while the thumbnail does!

2. Modern team site without O365 Group (Template STS#3) **as RootWeb** - command produces an exception "Set-PnpSite : Not an Office365 group enabled site." (So what? It's still a modern team site!)

3. Modern team site without O365 Group (Template STS#3) **as SubWeb** - predictably, it's totally impossible to "reach" this object with Set-PnPSite.

Now, you might suggest that in cases (2) and (3) I'm supposed to use `Set-PnPWeb -SiteLogoUrl` instead. This would point to misleading documentation, however I have tried it. It also fails to change the logo, although changes the thumbnail.    

### Steps to reproduce behavior
`Connect-PnPOnline -Url $SiteURL -Interactive`
`Set-PnpSite -LogoFilePath $LogoFilePath`
where $SiteURL is your target site URL and $LogoFilePath is the path of logo file on your local PC.

### What is the version of the Cmdlet module you are running?
1.6

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows

**Comment by gautamdsheth** [comment]
Hi @skantere , have fixed the issue.
Will be available in tomorrow's release. 
Thanks for reporting !
