### ISSUE TITLE
Remove-PnPsiteCollectionAdmin "Unable to remove user as it wasn't found. User will be skipped"

### ISSUE THREAD

**Issue by ckssaas** [pnp/powershell#820]
The basic command is returning "Unable to remove user as it wasn't found. User will be skipped" and does not remove the admin.

Set-PnPTenantSite -identity https://nexvortex1-my.sharepoint.com/personal/alatessa_nexvortex_com -owners "user1@domain.com"

Get-PnPSiteCollectionAdmin
Id Title LoginName Email
33 User 1 i:0#.f|membership|user1@domain.com user1@domain.com

remove-PnPsiteCollectionAdmin -owners "user1@domain.com"
WARNING: Unable to remove user as it wasn't found. User will be skipped.

Remove-PnPsiteCollectionAdmin -owners @("user1@domain.com")
WARNING: Unable to remove user as it wasn't found. User will be skipped.

Thanks

**Comment by veronicageek** [comment]
@ckssaas - Please DO NOT delete the template when opening an issue. Filling the info requested helps troubleshooting faster. 
As for the issue, I can reproduce it, but for now you can use the full `LoginName` as a workaround, it works on `1.6.0`.

![image](https://user-images.githubusercontent.com/25181757/122647633-fedb3380-d11c-11eb-96bb-159e421b9a82.png)

FYI - @gautamdsheth

**Comment by veronicageek** [comment]
@gautamdsheth - Is there anything we can do instead of the workaround? If not, that's a documentation update. Cheers.

**Comment by gautamdsheth** [comment]
@veronicageek , @ckssaas  - the issue has been fixed. Please try with tomorrow's nightly build !
Thanks for reporting.
