### ISSUE TITLE
[BUG] New-PnPTeamsTeam command is not creating team in 1.6.0 anymore

### ISSUE THREAD

**Issue by ismaili-de** [pnp/powershell#824]
### Reporting an Issue or Missing Feature
This is an issue report

### Expected behavior 
Expected is, that the command New-PnPTeamsTeam is creating a m365 group AND a MS Teams Team for this group

### Actual behavior 
Since upgrade from 1.5.0 to 1.6.0, it is only creating a m365 group, but not a team anymore, without any error message.

### Steps to reproduce behavior
Run the following command:
New-PnPTeamsTeam -DisplayName $TeamName -Description $Description -MailNickname $mailNickname -Visibility Private 

### What is the version of the Cmdlet module you are running?
1.6.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Can you try with the latest nightly release and check ?

**Comment by veronicageek** [comment]
@gautamdsheth - M365 group + SPO site created but not the Team.

**Comment by panjkov** [comment]
@ToddKlindt reported the same yesterday on twitter. https://twitter.com/ToddKlindt/status/1407827401124503552?s=20

**Comment by ToddKlindt** [comment]
Yep, I'm having the same problem with 1.6.0. I can confirm that 1.6.17-nightly appears to have fixed it. It also works in 1.5.0. Folks that still have that installed can load that if they need to create a Team.
It is interesting, the Teams I create with New-PnPTeamsTeam do not trigger the Teams icon in the SharePoint Admin UI. 
![image](https://user-images.githubusercontent.com/2659747/123278055-3dca0a00-d4cc-11eb-9d89-8f6528a290e0.png)
If you're testing this, make sure you confirm either in the Teams client itself, or with Get-PnPTeamsTeam to see if it worked.

**Comment by gautamdsheth** [comment]
Thanks @ToddKlindt for confirming, going to close the issue as it has been fixed in the nightly.

**Comment by hsamdani12** [comment]
Hi, I'm facing the same issue, I've the version 1.6 of PnP.Powershell.
I tried on 2 different tenants, it does not create the MS Teams, it just creates the 0365 Group and SPO Modern Team Site.
Please let me know which version should I upgrade to in order for this to work?

**Comment by veronicageek** [comment]
@hsamdani12 - Yes, please update to `1.7.0` released today.

**Comment by hsamdani12** [comment]
@veronicageek thanks, I did and it works!
I've one more question, do I need give Start-Sleep for say 60 secs before I can access the Team and O365 properties after running the New-PnPTeamsTeam ? As I need to do lot of configuration changes after provisioning including applying the PnPSiteTemaplate.
