### ISSUE TITLE
[BUG] Connect-PnPOnline fails in v1.6 and the latest nightly build in PowerShell 7

### ISSUE THREAD

**Issue by arielkropp** [pnp/powershell#825]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
Connect-PnPOnline should connect to the site in the `-Url` parameter

### Actual behavior 
Whenever using the cmdlet (whether using stored credentials, or the `-Interactive` parameter), I get the error:

"Connect-PnPOnline: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.30.1.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'. Could not find or load a specific file. (0x80131621)"

### Steps to reproduce behavior
`Connect-PnPOnline -Url $mysite -Credentials $cred`
or
`Connect-PnPOnline -Url $mysite -Interactive`

### What is the version of the Cmdlet module you are running?
 - 1.6.0
 - 1.6.10

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@arielkropp - This command is used thousand of times everyday, so it must have been at a point in time. No issues now.

![image](https://user-images.githubusercontent.com/25181757/122647930-9c833280-d11e-11eb-9b2f-b827be45bfa6.png)

**Comment by arielkropp** [comment]
@veronicageek - It seems this was an error due to having the Az modules installed as well; removing all Az modules resolved the error;
I'm still not sure why though - I was not importing any of the Az modules into a script.

**Comment by okms** [comment]
@arielkropp @veronicageek I had the same issue while having Az.Accounts module version 2.2.8 installed. Upgrading Az.Accounts to the latest version (2.4.0) fixed the issue for me
