### ISSUE TITLE
Unable to set "Sync hub Permissions to associated sites"

### ISSUE THREAD

**Issue by Chaotix** [pnp/powershell#829]
There is no method to "sync hub permissions to associated sites". The option isn't enabled when you register a hub site via PowerShell, and there is no method to throw this switch programmatically.

Here is the setting in the GUI:
[Sync Hub Permissions](https://i.stack.imgur.com/cesMW.png)

Set-PnpHubSite does not have the option, which is where I expected it to be.

**Comment by gautamdsheth** [comment]
Hello, have added the capability.
Will be available in tomorrow's nightly.

You can use it as to enable permissions sync:

```
Set-PnPHubSite -Identity "https://tenant.sharepoint.com/sites/myhubsite" -EnablePermissionsSync
```

To disable permissions sync:

```
Set-PnPHubSite -Identity "https://tenant.sharepoint.com/sites/myhubsite" -EnablePermissionsSync:$false
```
