### ISSUE TITLE
[BUG] Connect-PnPOnline  throws Method not found

### ISSUE THREAD

**Issue by DSTAlan** [pnp/powershell#839]
### Reporting an Issue or Missing Feature
Since updating to 1.6 I am having trouble calling a script containing Connect-PnPOnline as part of an Azure Automation job that is running on a dedicated VM (Hybrid Worker) connected to our LAN.  This worked fine using 1.5 and works if I uninstall 1,6 and revert to 1.5.

The line causing the issue is 

`Connect-PnPOnline -Url $sharepointSite -Credential $credential`

The error returned is

Method not found: 'Microsoft.Extensions.DependencyInjection.ServiceProvider Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)'

Has anyone come across this before or have suggestions on how I can troubleshoot the issue?

### Expected behavior 
Connect to SharePoint site

### Actual behavior 
exception returned:
Method not found: 'Microsoft.Extensions.DependencyInjection.ServiceProvider Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)'

### Steps to reproduce behavior
`Connect-PnPOnline -Url $sharepointSite -Credential $credential`

I am only seeing this issue when running a script containing the above from Azure Automation on a Hybrid Worker (Virtual Machine).  If I log on to the same VM and run the command from a PowerShell prompt then it seems to work correctly.

### What is the version of the Cmdlet module you are running?
1.6.0

PSVersionTable shows:

Name                           Value
----                           -----
PSVersion                      5.1.17763.1971
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1971
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows

**Comment by gautamdsheth** [comment]
Closing this due to lack of response
