### ISSUE TITLE
 Attempted to perform an unauthorized operation. Get-PnPSiteCollectionAdmin:

### ISSUE THREAD

**Issue by Lpt-wq** [pnp/powershell#845]
I am attempting to get a list of all site owners and members of the sites in my environment using PowerShell. i dont' find a way to do this so I was trying to loop through sites using connect-pnponline then running get-pnpsitecollectionadmin, but I am getting the error " Attempted to perform an unauthorized operation."

I am the sharepoint admin of the current environment. I am using pnp.powershell v 1.2.11

is there a way to get all owners and members of all sites in the current environment? do I need to be an admin to each site to be able to access its info in powershell?

**Comment by gautamdsheth** [comment]
Moving this to discussion as this is not an issue with the PnP PowerShell itself.
