### ISSUE TITLE
[BUG] New-PnPSite : Code: timeout Message: The request timed out error in GCCHigh with Azure Runbook

### ISSUE THREAD

**Issue by cjvandyk** [pnp/powershell#849]
### Reporting an Issue or Missing Feature
***NOTE!  THIS IS IN A GCCHIGH ENVIRONMENT WITH AZURE AUTOMATION RUNBOOK!!!***
When using version 1.6 we are trying to create a new site using the following code (sanitized so replace with your values where appropriate):

```
Disable-AzContextAutosave –Scope Process;
$connection = Get-AutomationConnection -Name AzureRunAsConnection;
Write-Output $connection;
$certificate = Get-AutomationCertificate -Name AzureRunAsCertificate;
Write-Output "Certificate thumbprint: "$certificate.CertificateThumbprint;
$tenant = "tenant";
$connectionResult = Connect-PnPOnline -returnconnection -Tenant "$tenant.onmicrosoft.us" -Url "https://$tenant.sharepoint.us" -AzureEnvironment USGovernmentHigh -Thumbprint $connection.CertificateThumbprint -ClientID $connection.ApplicationId;
Write-Output $connectionResult;
$spoadmin = "Admin@tenant.onmicrosoft.us";
$admingroup = "c:0t.c|tenant|00000000-0000-0000-0000-000000000000";
$tempatesource = "";
$mailalias = "Test20210623Z";
$sitename = $mailalias;
$displayname = $mailalias;
$sitedescription = $mailalias;
#Define site owners.
$siteowners = @('abc@tenant.onmicrosoft.us', 'xyz@tenant.onmicrosoft.us');
$sitetemplate = "TeamSite";
#Create a new Collaboration site.
Write-Output "New-PnPSite -Type $sitetemplate -Alias $mailalias -Title $displayname -Description $sitedescription -Owners $siteowners";
$url = New-PnPSite -Type $sitetemplate -Alias $mailalias -Title $displayname -Description $sitedescription -Owners $siteowners -connection $connectionResult;
Write-Output $url.url;
```

The New-PnPSite cmdlet fails after with either:

"New-PnPSite : Code: timeout Message: The request timed out. At line:31 char:12 + $url = New-PnPSite -Type $sitetemplate -Alias $mailalias -Title $ ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : WriteError: (:) [New-PnPSite], ServiceException + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.NewSite"

or

"Message: Location header not present in redirection response.
System.Management.Automation.ParameterBindingException: Cannot process command because of one or more missing mandatory parameters: InputObject.
   at System.Management.Automation.CmdletParameterBinderController.PromptForMissingMandatoryParameters(Collection`1 fieldDescriptionList, Collection`1 missingMandatoryParameters)
   at System.Management.Automation.CmdletParameterBinderController.HandleUnboundMandatoryParameters(Int32 validParameterSetCount, Boolean processMissingMandatory, Boolean promptForMandatory, Boolean isPipelineInputExpected, Collection`1& missingMandatoryParameters)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
   at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boo"

without creating the site.

### Expected behavior 
Site created successfully.

### Actual behavior 
The above error or timeout.

### Steps to reproduce behavior
Run the above code against a GCCHigh tenant in an Azure Automation runbook.

### What is the version of the Cmdlet module you are running?
1.6

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ X] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
@cjvandyk - Does this work correctly outside of Azure automation as in normal PS 5/ PS 7 ?

**Comment by gautamdsheth** [comment]
Closing this due to lack of response.
