### ISSUE TITLE
Documentation includes cmdlets that are not in PnP PS

### ISSUE THREAD

**Issue by pkbullock** [pnp/powershell#852]
### Reporting an Issue or Missing Feature

Googling and finding on the documentation site a cmdlet that no longer exists e.g.

New-PnPUnifiedGroup

![image](https://user-images.githubusercontent.com/8781041/123265783-4e41ab00-d4f3-11eb-991f-3178f7a470be.png)

I didnt want to just raise a PR without some awareness... should this be removed?

### What is the version of the Cmdlet module you are running?

Latest (v.1.6)

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@pkbullock - Documentation is currently a topic we're discussing, so let's park that for now 🙂

**Comment by KoenZomers** [comment]
This has now been resolved. Thanks for bringing this to our attention @pkbullock !
