### ISSUE TITLE
[FEATURE] Consistent outcomes for Get-PnPTeamsTeam and Get-PnpAzureADGroup

### ISSUE THREAD

**Issue by mdressel** [pnp/powershell#855]
**Is your feature request related to a problem? Please describe.**
I have a need to check for both a Team and a Group based on a users input. When I use Get-PnPTeamsTeam there is a red message "Team not found" and the result is $null. When I use Get-PnPAzureADGroup there is no message but an exception it thrown "Object reference not set to an instance of an object.".

**Describe the solution you'd like**
For me, in all cases there shouldn't be any "message" displayed. Instead you should just get $null.

**Describe alternatives you've considered**
I can solve part of my issue by using a try/catch. It just isn't very nice.

**Additional context**
I thought about making this a bug for Get-PnPAzureADGroup, but I am not sure if there is really an official PnP.PowerShell pattern for dealing with this type of thing. If there isn't I would recommend the one that I just said. I don't want to get exceptions or messages when nothing is returned.

Even if you don't like my suggestion of removing the message, I still feel like these should be consistent.

**Comment by mdressel** [comment]
So after I posted this I found that I could use Get-PnpMicrosoft365Group instead and it doesn't have the same issue. It still doesn't post a message, but it doesn't error which was my biggest complaint.

I think this request still stands, but it isn't a very big deal for me personally.

**Comment by gautamdsheth** [comment]
Fair feedback, will try to work on this issue and fix it.
Meanwhile, you can also use `Get-PnPAzureADGroup -ErrorAction SilentlyContinue` as well which might swallow the error.

**Comment by gautamdsheth** [comment]
Fixed it, will be available in tomorrow's nightly !
