### ISSUE TITLE
[BUG] - Get-PnPFlow & Get-PnPFlowEnvironment - Object not found

### ISSUE THREAD

**Issue by robertcaretta** [pnp/powershell#860]
### Reporting an Issue or Missing Feature
Get-PnPFlow & GetPnPFlowEnvironment both return the error "Object reference not set to an instance of an object."

### Expected behavior 
Get-PnPFlowEnvironment  should pull back all environments. 
Get-PnPFlow should pull back flows when an environment GUID is specified.

### Actual behavior 
I can connect fine using Connect-PnPOnline. I don't appear to have any issues pulling SharePoint sites. When using the Get-PnPFlowEnvironment and Get-PnPFlow both return the error "Object reference not set to an instance of an object."

![image](https://user-images.githubusercontent.com/1613085/123432341-e7260400-d58f-11eb-85b6-487ed8628479.png)

![image](https://user-images.githubusercontent.com/1613085/123432410-f9a03d80-d58f-11eb-94da-c27f8713eef8.png)

![image](https://user-images.githubusercontent.com/1613085/123432936-88ad5580-d590-11eb-981f-53c1ab2432a1.png)

Additional context:
- I am a tenant admin for SharePoint, Teams, Power Platform, etc.
- I am using VS Code 1.51.1
- Machine has only Powershell 5.1
- Azure App is set up correctly using the default setup command "Register-PnPManagementShellAccess".  My user account has access to this app. I am able to connect to it just fine.
- PnP.PowerShell module is installed with a scope of CurrentUser.

### Steps to reproduce behavior
See screenshots above.

### What is the version of the Cmdlet module you are running?
1.6.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by robertcaretta** [comment]
When running Get-FlowEnvironment command using ISE it seems to work correctly. 
![image](https://user-images.githubusercontent.com/1613085/123433818-797ad780-d591-11eb-876a-0dc89022a645.png)

**Comment by veronicageek** [comment]
@robertcaretta - Indeed it's working fine. So I'll close this for now, as it might be related to VSCode in some way, but not a PnP.PowerShell issue.

![image](https://user-images.githubusercontent.com/25181757/123435168-2d498a80-d5c5-11eb-8430-90ecee309ce4.png)

**Comment by robertcaretta** [comment]
OK, but wouldn't you want to test that combination in regards to why that is happening?

**Comment by veronicageek** [comment]
If this is coming from the VSCode extension, then there's not much we can do on our side unfortunately.
