### ISSUE TITLE
[BUG] Add-PnPGroupMember won't map a user

### ISSUE THREAD

**Issue by gitulm** [pnp/powershell#861]
With the following command I will entitle our users to a specfic site:

Connect-PnPOnline -Url https://xxx.sharepoint.com/sites/yyy -Credentials $userCredential2
$groupMember = Get-PnPGroup -AssociatedMemberGroup
$groupMember
$gruppennameM = $groupMember.Title
$groupid = $groupMember.Id
Add-PnPGroupMember -LoginName user@company.com -Group $groupid  

After sending command above I get the following error:
Add-PnPGroupMember : Method not found: "Int32 System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan`1<Byte>)".

The command is full correct, the ID of the group is correct and the user is correct. 
**Why does the command not work for me ?**

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
We use PnP.Powershell 1.6.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows

**Comment by veronicageek** [comment]
@gitulm - I've tried with `1.6.10` (even though I don't think there's much change from `1.6.0`) and have no problem. Please try again or update the nightly build.

![image](https://user-images.githubusercontent.com/25181757/123686640-e9b28300-d847-11eb-9d17-3d389628aa94.png)

**Comment by gitulm** [comment]
On two different PC I started the following commands:

Get-Command -Module *PnP* 
Command is existing:
Cmdlet          Add-PnPGroupMember                                 1.6.0      PnP.PowerShell  

Add-PnPGroupMember -LoginName user@domain.de -Group 6 

and I got following error:

Add-PnPGroupMember : Methode nicht gefunden: "Int32 System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan`1<Byte>)".
In Zeile:1 Zeichen:1
+ Add-PnPGroupMember -LoginName user@domain.de -Group 6
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Add-PnPGroupMember], MissingMethodException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Principals.AddUserToGroup


I'm desperate about this command Add-PnPGroupMember. Every other PnP Command works for me fine except this. Does anybody know what the error message means?

**Comment by veronicageek** [comment]
Do you have any special characters?

**Comment by astavitsky** [comment]
I am experiencing the same issue with 1.6.38.  There are no special characters in the LoginName parameter

**Comment by gautamdsheth** [comment]
@astavitsky - Looks like you are using this in VS code terminal. Can you try it in PS 5 or PS 7 ?

**Comment by veronicageek** [comment]
Closing as no response.
