### ISSUE TITLE
[BUG] PnP.PowerShell Get-PnPList Error

### ISSUE THREAD

**Issue by XxDaShTixX** [pnp/powershell#862]
### Description
We recently updated the SharePointPnPPowerShellOnline PowerShell module (as it is currency out of support according to Microsoft) to PnP.PowerShell v1.6.0. Ever since we updated, our runbooks intermittently / randomly fail on the cmdlet Get-PnPList with the following error: "The data is not available. The query may not have been executed." and I cannot pinpoint the reason to why this randomly fails.

This is running on a schedule n Azure Automation on a hybrid worker. Note that the intermittent failures occur both when I run this in Azure Automation (on-prem hybrid worker) or run it locally (directly in ISE).

Does this library support different runbooks connecting to the same SP site? As we may have one or two runbooks connecting to the same SP site (but in different domains/environments). If it does not, is there a workaround or best-practices to use this?

### Expected behavior 
$connection = Connect-PnPOnline -Credentials $creds -Url https://XXX.sharepoint.com/sites/YYY -ReturnConnection
$list = Get-PnPList -Identity 'Some List Name' -Connection $connection
(DO STUFF)
Disconnect-PnPOnline -Connection $connection

The list should be retrieved with no issue. It does do that, but "sometimes" fails with the error previously mentioned.

### Actual behavior 
Ever since we updated, our runbooks intermittently / randomly fail on the cmdlet Get-PnPList with the following error: 
"The data is not available. The query may not have been executed."
and I cannot pinpoint the reason to why this randomly fails.

### Steps to reproduce behavior
As it randomly happens, its hard to say. 

### What is the version of the Cmdlet module you are running?
PnP.PowerShell v1.6.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows

**Comment by veronicageek** [comment]
@XxDaShTixX - Can you please update the module to the latest version and report back. Thanks.

**Comment by gautamdsheth** [comment]
Closing it due to lack of response
