### ISSUE TITLE
[FEATURE] Get-PnPDeletedTenantSite Restore-PnPDeletedTenantSite Remove-PnPDeletedTenantSite Request

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#871]
**Is your feature request related to a problem? Please describe.**
It looks like currently there is no way to retrieve list of deleted sites using PnP.PowerShell module. At least this is something I am unable to locate:
![image](https://user-images.githubusercontent.com/5260172/123813887-eda0dc80-d8fd-11eb-9acb-6a5e0fba227e.png)

**Describe the solution you'd like**
We need some kind of alternative to `Get-SPODeletedSite` and `Restore-SPODeletedSite` `Remove-SPODeletedSite` cmdlets:
https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spodeletedsite?view=sharepoint-ps
https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/restore-spodeletedsite?view=sharepoint-ps
https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/remove-spodeletedsite?view=sharepoint-ps
![image](https://user-images.githubusercontent.com/5260172/123814005-04dfca00-d8fe-11eb-9f4b-d5c9de4fee15.png)

**Describe alternatives you've considered**
The only alternatives available are `Get-SPODeletedSite` and `Restore-SPODeletedSite`

**Comment by gautamdsheth** [comment]
Added the commands, please check tomorrow.
Thanks !

**Comment by YuriySamorodov** [comment]
Oh wow, that was lightning fast!
Thanks a lot @garrytrinder , you rock!
