### ISSUE TITLE
[FEATURE] Add ability to invoke generic Graph methods

### ISSUE THREAD

**Issue by mdressel** [pnp/powershell#873]
**Is your feature request related to a problem? Please describe.**
I wasn't going to suggest this feature, but then I saw `Invoke-PnPSPRestMethod` and thought what I am asking seems similar.

What I am looking for is a "catch all" way to make Graph API requests that aren't currently supported in PnP.PowerShell. This is important to me because I need access to the commands I listed in #872 and I don't have a lot of good options to work around needing those commands. 

In my case, this is because the `MsGraph-SDK-PowerShell` library doesn't work in Azure Automation. I am sure others will have different things that cause them to have the same issue.

**Describe the solution you'd like**
Add a new command like `Invoke-PnPGraphMethod`

**Describe alternatives you've considered**
Most people could probably install and use the `MsGraph-SDK-PowerShell` library. This doesn't work for me because they don't have the ability to either accept the `AccessToken` from `PnP.PowerShell` or accept a `-CertificateBase64Encoded` parameter

**Additional context**
For my specific issue, if the `MsGraph-SDK-PowerShell` makes it so I can authenticate from Azure Automation I can work around this need.

**Comment by gautamdsheth** [comment]
@mdressel -  Closing this feature request.

@4ndri submitted a PR which has been merged. 

You will now be able to use `Invoke-PnPGraphMethod` to execute direct calls to the MSGraph endpoints !
