### ISSUE TITLE
[BUG] Returned connection not working and breaks main connection

### ISSUE THREAD

**Issue by svermaak** [pnp/powershell#874]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
Be able to utilize main and returned connection

### Actual behavior 
Both the main and returned connections do not work

### Steps to reproduce behavior
![image](https://user-images.githubusercontent.com/12259728/123881346-cf7fbe80-d987-11eb-9049-0a6257206fb0.png)

### What is the version of the Cmdlet module you are running?
1.6.0

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@svermaak - I know it's been a while, but I have no issue with `1.7.38`. Please update and reopen if you're still facing the issue. Thanks.

![image](https://user-images.githubusercontent.com/25181757/131883817-9e76c516-6280-4624-a705-2afd01ea5923.png)
