### ISSUE TITLE
[BUG] Connect-PnPOnline from VS Code integrated terminal stalls on first attempt

### ISSUE THREAD

**Issue by DanielNoord** [pnp/powershell#877]
### Reporting an Issue or Missing Feature
When using `Connect-PnPOnline` with parameter `-Interactive` from the integrated terminal in Visual Studio Code on Mac the initial attempt hangs. My browser is Safari. Something in the communication between VS Code and Safari seems to malfunction.
When I abort the command and retry it does succeed. 

Using iTerm this problem does not occur.

### Expected behavior 
I would expect `Connect-PnPOnline` to log me into the SharePoint.

### Actual behavior 
Not really comfortable with sharing screenshots due to log-in information. 
If needed I can provide screenshots/casts through discrete channels.

### Steps to reproduce behavior
`Connect-PnPOnline $SharePoint -Interactive` on Visual Studio Code Mac

### What is the version of the Cmdlet module you are running?
1.6.0

### Which operating system/environment are you running PnP PowerShell on?
- MacOS
- Visual Studio Code, Version: 1.57.1, Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48

**Comment by veronicageek** [comment]
@DanielNoord - This command (`Connect-PnPOnline`) is used thousand of times everyday, so we can safely say it works. Furthermore, we're not going to be able to troubleshoot third-party software like VSCode (PowerShell extension) or Safari unfortunately. We don't have the capacity / resources.

**Comment by DanielNoord** [comment]
I can understand the lack of capacity/resources might make fixing this bug impossible, although I am more than happy to provide any data/details needed.

I don't necessarily agree with the conclusion that the commands "works" though. It does, but for me only after two tries. I don't believe that is how it is supposed to work. But again, I can understand the circumstances which would prevent you from fixing this.
