### ISSUE TITLE
Invoke-PnPBatch does not save items added via Add-PnPListItem with -Batch $batch parameter

### ISSUE THREAD

**Issue by gandalf516** [pnp/powershell#881]
## Category

- [x] Bug

## Describe the bug

Calling Add-PnPListItem for 200+ items with -Batch $batch parameter and invoking Invoke-PnPBatch also with -Batch $batch parameter and no items get created (first time I ran it, it created 7 items, no items created on subsequent script runs)

## Steps to reproduce
Call Add-PnPListItem for 200+ items with -Batch $batch parameter and invoking Invoke-PnPBatch also with -Batch $batch parameter. I get no error, and no details if I use -Details params, and no expection if I use -StopOnException param within try catch block.

## Expected behavior

200+ new items created in SPO list

## Additional information
When I ran it without batching, items got created as expected.

## ENV/SETUP

Powershell 5.1/7.1+ (tested on both), module PnP.PowerShell v1.6, 
OS win server 2012/win 10 desktop (tested on both).
VS Code 1.38.1

**Comment by veronicageek** [comment]
@erwinvanhunen / @gautamdsheth

**Comment by gautamdsheth** [comment]
@gandalf516 - can you give it try with tomorrow's nightly ? Erwin fixed the issue by updating the PnP Core dependency.

**Comment by gandalf516** [comment]
@gautamdsheth I've tried it today with nightly PnP.PowerShell v1.6.30 and still not working, only this time it's throwing "Object reference not set to an instance of an object." at line `Invoke-PnPBatch -Batch $batch`

**Comment by gandalf516** [comment]
UPDATE: batch updating via `Set-PnPListItem -List $listNameUsers -Identity $userSPO."ID" -Values $values -Batch $batch` works fine, so the issue seems to be only related to Add-PnPListItem cmdlet.

**Comment by veronicageek** [comment]
@gandalf516 - I've just tried with the latest `1.7.43` and no issue creating 200+ items with the `-Batch` method for `Add-PnPListItem`. Please update (if not done yet) and try again. I'll close for now, feel free to reopen if the issue persists. Thanks.

**Comment by jasonseiler** [comment]
This issue is still occurring in version 1.9.0.

**Comment by benjblack** [comment]
Also having this issue in version 1.12.0
