### ISSUE TITLE
[BUG] Error: New-PnPPersonalSite: Attempted to perform an unauthorized operation

### ISSUE THREAD

**Issue by JAK1047** [pnp/powershell#897]
### Reporting an Issue or Missing Feature
Receiving error whenever I try to use the New-PnPPersonalSite cmd on a new licensed user. For additional info I'm connecting to our admin site via app authentication with a certificate and using Powershell 7.1.3.

### Expected behavior 
Cmd runs fine and backend SPO timer jobs kick off to provision the site.

### Actual behavior 
Receive an error of: New-PnPPersonalSite: Attempted to perform an unauthorized operation.

### Steps to reproduce behavior
Running:
New-PnPPersonalSite -Email 'TestUser@contoso.com'

### What is the version of the Cmdlet module you are running?
1.6.0

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by JAK1047** [comment]
I've also tested Request-PnPPersonalSite and connected both with a normal user account and with a certificate. Every combination gives me the exact same message. Issue persists in 1.7.0

**Comment by veronicageek** [comment]
Reproduced with `1.7.43`

**Comment by KoenZomers** [comment]
Duplicate issue of https://github.com/pnp/powershell/pull/1158. Using this cmdlet requires connecting in specific ways. You can find the updated documentation on this here:

https://github.com/pnp/powershell/blob/f3721faedc7c969a5aa34cfd33fcc7ce824a45b4/documentation/New-PnPPersonalSite.md

Closing this issue assuming this answers your question. If not, feel free to reopen.
