### ISSUE TITLE
New-PnPSite command isn't setting the sensitivity label 

### ISSUE THREAD

**Issue by astatke** [pnp/powershell#898]
I am challenged in creating SensitivityLabel for my new modern sites. I used **New-PnPSite** as below but it is not creating a sensitivity label for my site (where $sensLabel holds a GUID/ID of my sensitivity label): 
**_New-PnPSite -Type CommunicationSite -Title $siteTitle -Url $siteURL -Owner $owner -SensitivityLabel $sensLabel_**

Besides I cannot use **Set-PnPSite** to set site's sensitivity label as it seems to be not taking sentivitylabel as an argument.

FYI, I am using PnP.PowerShell version 1.6.1 with my PnP PowerShell script connecting to SharePoint Online using App Permission as described [here](https://github.com/pnp/PnP-PowerShell/tree/master/Samples/SharePoint.ConnectUsingAppPermissions).

Below is how I connect to SharePoint online:
**_Connect-PnPOnline -Url $configSiteUrl -ClientId $clientID -Tenant $tenantName -Thumbprint $thumbPrint_**

Your help is appreciated.

**Comment by gautamdsheth** [comment]
We have observed that this only works if you connect using delegated permissions. 
Can you try this approach and let us know ?

**Comment by astatke** [comment]
Thank you @gautamdsheth for responding to my issue.

Unless you mean something else, I thought **Delegated Permissions** were meant to serve a signed in user. In my case, I want the script to run via a scheduled task i.e. without a user signing into to the M365 tenant interactively.  If I misunderstood your response, please let me know.

**Comment by astatke** [comment]
It turns out there is a PnP cmdlet called **Set-PnPTenantSite** that I was able to use to set the Sensitivity label i.e. after creating the new site. 
_Set-PnPTenantSite -Identity $newSiteURL -SensitivityLabel $sensLabel -Connection $adminURLConnection_
Not sure how it evaded me in the first place.

**Comment by netibex** [comment]
@astatke - Hi, I wanted to follow up on this issue, as we are facing the same challenge at the moment.
Can you share how your connection looks like, and which permissions you were using?
We are currently trying the same command as you provided above, but without success.
The command executes without error, but the sensitivity label is NOT set.
Thanks!
