### ISSUE TITLE
Exception has been thrown by the target of an invocation.   Get-PnPTenantSite

### ISSUE THREAD

**Issue by fikryGaf** [pnp/powershell#899]
Hi, i'm getting this error since yesterday however, the code was working fine and not changed at all. 
when executing Get-PnPTenantSite it throws this error "Exception has been thrown by the target of an invocation. " 
however the app reg has been registered with full control on the tenenant level and it was working as i said before. 

the version which i used was pnppowershell 1.4.0 and also i tried to upgrade it to 1.6 but the same results. 
$AppSecret = "xxxxxxxxx"
$AppID = "xxxxxxxx"
Connect-PnPOnline -Url $Url -ClientSecret $AppSecret -ClientId $AppID 
$masterSPList = Get-PnPTenantSite  -Detailed -Filter  "Url -like '{https://somesite name}'"

* i removed the name of the tenant and ids

again it happened suddenly however, i didn't change any thing in the code and also i check the legacy authentication and found it true on the tenant level 
appreciate your support.

**Comment by veronicageek** [comment]
@fikryGaf - Tried with `1.7.43` and no problem running your snippet. Please update (if not done yet) and reopen if the issue persists. Thanks.

![image](https://user-images.githubusercontent.com/25181757/132412563-5008c4fa-e799-4d81-b07f-42d3b07050fa.png)
