### ISSUE TITLE
Add-PnPNavigationNode - Provide an example of how to create a Label

### ISSUE THREAD

**Issue by mcpsmith** [pnp/powershell#901]
Please add documentation on how to create a Label in the navigation node (vs a Link).

I had to figure it out for myself. Use -url "http://linkless.header/" to create a Label instead of a Link

https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPNavigationNode.md

**Comment by wonderplayer** [comment]
I think that previously this has worked even without this special URL. Maybe Microsoft changes something in their API...
Anyway, added an example to document on how to create a label.

**Comment by gautamdsheth** [comment]
Closing it, docs have been updated by @wonderplayer !
