### ISSUE TITLE
ConnectPnPOnline with certifcate not working version 3.29.2101.0

### ISSUE THREAD

**Issue by mschaaks** [pnp/powershell#907]
### Reporting an Issue or Missing Feature

Requirement:
I need the old V3 version because i need to connect within one and the same session to both on prem and online SharePoint environments. Connecting to SPO using Vnext (1.5.0) with cert no problem, however doing this using old V3 does not seem to work. Old V3 repo is closed, but are you still going to fix issues like this for V3 ?  

Using this setup:
**1.register AAD app + cert registration on machine in cert store**
I used vnext pnp cmd-let as described here: https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/register-pnpazureadapp?view=sharepoint-ps

**2.script:**
$paramsConnect = @{
    Url = $url
    ReturnConnection = $true
    Tenant = $tenant
    Thumbprint = $thumb
    Clientid = $clientid
}
$con = Connect-PnPOnline @paramsConnect

Please confirm what it is that your reporting

### Expected behavior
Succesfull connection 

### Actual behavior 
Connect-PnPOnline : Exception has been thrown by the target of an invocation.
At test.ps1:18 char:8
+ $con = Connect-PnPOnline @paramsConnect
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-PnPOnline], TargetInvocationException
    + FullyQualifiedErrorId : System.Reflection.TargetInvocationException,PnP.PowerShell.Commands.Base.ConnectOnline
 
CorrelationId    :
TimeStampUtc     : 7/10/2021 11:02:51 AM
Message          : Exception has been thrown by the target of an invocation.
Stacktrace       :    at PnP.PowerShell.Commands.Base.ConnectOnline.ProcessRecord()
                      at System.Management.Automation.CommandProcessor.ProcessRecord()
ScriptLineNumber : 18

### Which operating system/environment are you running PnP PowerShell on?
- [ x]xWindows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@mschaaks - The [old PowerShell](https://github.com/pnp/pnp-powershell) module is archived (not maintained anymore) as you mentioned and we have no plans on fixing issues in the old repo. As a Community driven module, unfortunately we simply do not have the capacity/resources for both platforms.
