### ISSUE TITLE
[BUG] new-pnpsite - app-only context - fails with 404

### ISSUE THREAD

**Issue by joenstrup** [pnp/powershell#908]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
Connect to SharePoint online using connect-pnponline using certificate app-only context.
New-PnPSite -Type CommunicationSite -Title [Title] -Url [URL] -Description [description] -Owner [Owner ] -Lcid 1033 -Wait
Site is created

### Actual behavior 
Connected to SharePoint online using connect-pnponline using certificate app-only context.
New-PnPSite -Type CommunicationSite -Title [Title] -Url [URL] -Description [description] -Owner [Owner ] -Lcid 1033 -Wait
New-PnPSite : The remote server returned an error: (404) Not Found.
This started last week, and has been working previously.

### Steps to reproduce behavior
Connect to SharePoint online using connect-pnponline using certificate app-only context.
New-PnPSite -Type CommunicationSite -Title [Title] -Url [URL] -Description [description] -Owner [Owner ] -Lcid 1033 -Wait

### What is the version of the Cmdlet module you are running?
Have tried this using 1.5.0, 1.6.0 and nightly, and issue is the same. Seems Microsoft have changed something or?

### Which operating system/environment are you running PnP PowerShell on?
- [ X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@joenstrup - There was an issue last week, but not entirely sure if this would have an impact. To be on the safe side, could you please update your module to `1.7.0` and try again please. Thanks.

**Comment by joenstrup** [comment]
Not it is working
