### ISSUE TITLE
Permission difference when connecting -Interactive vs -AccessToken

### ISSUE THREAD

**Issue by sanek112r** [pnp/powershell#909]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
The command `Get-PnPRecycleBinItem` should work (return nothing is correct)

### Actual behavior 
After connection with the access token, I got 401 unauthorized.

### Steps to reproduce behavior
Our primary goal is to use connection with AccessToken, the sample below is to showcase that:
* -Interactive auth works
* Using the same token obtained from interactive auth, and establish connection with -AccessToken, the command that previously worked now failed

```powershell
PS C:\Users\aleksandr.klunniy> Connect-PnPOnline -Url https://M365B840657.sharepoint.com/sites/Marketing -Interactive
PS C:\Users\aleksandr.klunniy> Get-PnPRecycleBinItem
PS C:\Users\aleksandr.klunniy> $token = Get-PnPAccessToken
PS C:\Users\aleksandr.klunniy> Connect-PnPOnline -Url https://M365B840657.sharepoint.com/sites/Marketing -AccessToken $token
PS C:\Users\aleksandr.klunniy> Get-PnPRecycleBinItem
Get-PnPRecycleBinItem: The remote server returned an error: (401) Unauthorized.
PS C:\Users\aleksandr.klunniy>
```

### What is the version of the Cmdlet module you are running?
1.6.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by KoenZomers** [comment]
Use `$token = Get-PnPAppAuthAccessToken` instead and it should work. I have updated the documentation to make this more clear.

Closing this issue assuming this will resolve it. If not, feel free to reopen.
