### ISSUE TITLE
PnP "Proxy"Cmdlets do not contain "PnP" in the commands

### ISSUE THREAD

**Issue by LeonArmston** [pnp/powershell#916]
Created an issue from this discussion post from @n300home regarding the PnP Proxy Item cmdlets not having PnP in them and the documentation not being valid. All PnP module commands usually contain "PnP" in them so my guess is the cmdlets need fixing to reflect this or at least a PnP alias added.

![image](https://user-images.githubusercontent.com/12968962/125754197-98283f01-6b69-4fae-a031-e56930662c0e.png)

### What is the version of the Cmdlet module you are running?
1.6.38     PnP.PowerShell  

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

### Discussed in https://github.com/pnp/powershell/discussions/915

<div type='discussions-op-text'>

<sup>Originally posted by **n300home** July 15, 2021</sup>
Hi there,

found out that Copy-PnPItemProxy and Move-PnPItemProxy was renamed to *-ItemProxy without "PnP" in the middle without any compatibility aliases. 
Could you please accordingly advise your documentation?
https://pnp.github.io/powershell/cmdlets/Copy-PnPItemProxy.html
and https://pnp.github.io/powershell/cmdlets/Move-PnPItemProxy.html

Many thanks in advance

</div>

I'd argue that the Proxy cmdlets should have PnP in them been as all the other PnP cmdlets have PnP in them so you can identify which module it comes from. My guess is that that when the new PnP.PowerShell was released that this by mistake wasnt fixed to reflect PnP or at least an alias added.

![image](https://user-images.githubusercontent.com/12968962/125754197-98283f01-6b69-4fae-a031-e56930662c0e.png)

**Comment by gautamdsheth** [comment]
Hello @LeonArmston , this issue has been fixed now !
Please reopen this if it still exists, thank you :)
