### ISSUE TITLE
[BUG] Not providing access needed with site permission API

### ISSUE THREAD

**Issue by tsegato** [pnp/powershell#917]
First we create an app reg:

```
$appName = "KK test 7"
$url = "https://xx.sharepoint.com/sites/Segato-test11"

Connect-PNPonline -url https://xxx.sharepoint.com -interactive
$appReg = Register-PnPAzureADApp -ApplicationName $appName -Tenant xxx.onmicrosoft.com -Store CurrentUser -GraphApplicationPermissions "Sites.Selected" -Username "tse@xxx.com" -Password (Read-Host -AsSecureString -Prompt "Enter Password")

```
Following we grant access to that app reg:
Grant-PnPAzureADAppSitePermission -AppId "xx-74a9-xx-968c-xx" -DisplayName $appName -Site 'https://xxx.sharepoint.com/sites/Segato-test11' -Permissions Write

![image](https://user-images.githubusercontent.com/43033640/125904027-bbb0dda5-adea-49e0-8b63-6788b64b9ded.png)

Everything seems to work. However when I get the permissions it looks like this (notice roles are empty):

```
`$url = "https://xx.sharepoint.com/sites/Segato-test11"`


Connect-PNPonline -url https://xx.sharepoint.com -interactive
Get-PnPAzureADAppSitePermission -Site https://xx.sharepoint.com/sites/Segato-test11
```

![image](https://user-images.githubusercontent.com/43033640/125904424-dd379ebd-1b07-4a16-a2b5-2fb975a19f22.png)

And when I try to test the app reg i get an 403 forbidden:
![image](https://user-images.githubusercontent.com/43033640/125904591-010ccf17-f839-42ba-bf92-8b16b98492c8.png)

```
$conn = Connect-PnPOnline -Url $url -ClientId 6af22786-74a9-4aab-968c-bf4901fc8f8c -ClientSecret  "q.xx.7x-xx-"
$Site = Get-PnPSite -Connection $conn
```

**Comment by kerski** [comment]
I can confirm this bug as well.  I have tried with PnP PowerShell, Postman, and Graph Explorer making sure the appropriate API permissions were set Sites.FullControl.All on the app before granted the other app Sites.Selected (followed: https://mmsharepoint.wordpress.com/2021/08/18/accessing-sharepoint-sites-with-resource-specific-consent-rsc-and-microsoft-graph/) and get the same issue. This may not be a PnP issue.  I'm open to suggestions.

**Comment by tsegato** [comment]
I tried with pure graph API same result.

**Comment by veronicageek** [comment]
@gautamdsheth - Do you have an opinion on that one? 🙂

**Comment by gautamdsheth** [comment]
If it fails with pure Graph API as well, not sure we can do anything about it. 
Also, this permission level is still in preview, so I guess would suggest that you reach out to Microsoft about it.

**Comment by Chipzter** [comment]
It does not fail with pure Graph API when retrieving an access token manually and calling the API with Postman. Using the same access token and trying to use it with connect-pnponline fails with 401 unauthorized.
