### ISSUE TITLE
[BUG] Get-PnPTenantSite: The property or field 'AuthContextStrength' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.

### ISSUE THREAD

**Issue by colonelclaypoo** [pnp/powershell#922]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
Get-PnPTenantSite by itself or with -Connection $connection should return the tenant's site collections.

### Actual behavior 
Get-PnPTenantSite by itself or with -Connection $connection throws error: _The property or field 'AuthContextStrength' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested._

### Steps to reproduce behavior
`Get-PnPTenantSite -Connection $connection`

### What is the version of the Cmdlet module you are running?
1.6.42 (nightly)

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows

I couldn't find anything wrong with cmdlet's such das Get-PnPSite or Get-PnPWeb, they work fine.

**Comment by gautamdsheth** [comment]
Yeah strange error that has suddenly popped in. 
Looks like something has changed server side because it used to work without errors 2 days back.

**Comment by taisuke0710** [comment]
I'm also hitting the same issue.
ProcessQuery API doesn't return AuthContextStrength property in repro tenant. Then the exception is thrown when props.AuthContextStrength is referred in constructor of PnP.PowerShell.Commands.Model.SPOSite.
Fiddler captured in repro tenant is attached.
[failed.zip](https://github.com/pnp/powershell/files/6847087/failed.zip)

![image](https://user-images.githubusercontent.com/87537139/126298964-ad726b94-f2a8-41fc-ba65-5726b2fe9a8e.png)

**Comment by kloosterj** [comment]
Same issue happening here, started yesterday afternoon CET.

**Comment by veronicageek** [comment]
Should be fixed with the `-nightly` release available tomorrow. Check and close if resolved.

**Comment by colonelclaypoo** [comment]
Thank you! It's working again using the latest nightly.

**Comment by kloosterj** [comment]
Confirmed, issue resolved after installing 1.6.44-nightly. Thank you very much!
