### ISSUE TITLE
Get-PnPTenantSite StorageUsageCurrent return 0

### ISSUE THREAD

**Issue by nganbui** [pnp/powershell#923]
I am trying to get storageUsageCurrent of OneDrive site but I got return 0 when using cmdlet below
Connect-pnpOnline
$site = Get-PnPTenantSite -Url $siteURL
$site.StorageUsageCurrent return 0
Please let me know if there is a bug of this or I am doing something wrong.
Thanks.

### Expected behavior 
Connect-pnpOnline
$site = Get-PnPTenantSite -Url $siteURL
$site.StorageUsageCurrent should return >  0

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

### Steps to reproduce behavior
Connect-pnpOnline
$site = Get-PnPTenantSite -Url $siteURL
$site.StorageUsageCurrent return 0
$site.StorageQuotaWarningLevel return 943718

### What is the version of the Cmdlet module you are running?
PnP.PowerShell version 1.6

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Can you try with `-Detailed` parameter ? 
Something like `$site = Get-PnPTenantSite -Url $siteURL -Detailed` ?

**Comment by nganbui** [comment]
> Can you try with `-Detailed` parameter ?
> Something like `$site = Get-PnPTenantSite -Url $siteURL -Detailed` ?

Yes I tried and return same result.

**Comment by veronicageek** [comment]
Have no issue on my side. Also please upgrade to `1.6.44-nightly`.
What site are you connecting to in `Connect-PnPOnline` ?

![image](https://user-images.githubusercontent.com/25181757/126534068-e44b7ba6-d1c5-40e7-9b12-6854318d0f3f.png)

**Comment by veronicageek** [comment]
Closing as no response.
