### ISSUE TITLE
[BUG] Import-PnPTaxonomy

### ISSUE THREAD

**Issue by saltzimania** [pnp/powershell#924]
### Reporting an Issue or Missing Feature
Import-PnPTaxonomy is failing using text file imports with hundreds/thousands of lines.
We are attempt to import files with close to 30,000 terms and the Cmdlet fails with on of two errors.

We have tried splitting the files into smaller batches of 5000 terms each and are still encountering issues.
Having to split the files also means we cannot use -SynchronizeDeletions

Each time we re-run an import it appears to get a bit further but still fails.
It appears the line number from the error may be referring to the line number in the txt import file.

RAM usage seems very high.

Please let me know what you think.
Thanks!

### Expected behavior 
All terms in the txt file get created in the term store.

### Actual behavior 
Import fails during import with one of two (which one is seemingly random) errors:

Import-PnPTaxonomy : Exception on line 7187: Unable to read data from the transport connection: An existing connection
was forcibly closed by the remote host.
At line:1 char:1
+ Import-PnPTaxonomy -Path .\legals.txt -SynchronizeDeletions
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Import-PnPTaxonomy], ApplicationException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Taxonomy.ImportTaxonomy

or

Import-PnPTaxonomy : Exception on line 747: TermStoreEx:Failed to read from or write to database. Refresh and try
again. If the problem persists, please contact the administrator.
At line:1 char:1
+ Import-PnPTaxonomy -Path .\legals2.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Import-PnPTaxonomy], ApplicationException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Taxonomy.ImportTaxonomy

and then it gets further after we run again:

Import-PnPTaxonomy : Exception on line 779: TermStoreEx:Failed to read from or write to database. Refresh and try
again. If the problem persists, please contact the administrator.
At line:1 char:1
+ Import-PnPTaxonomy -Path .\legals2.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Import-PnPTaxonomy], ApplicationException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Taxonomy.ImportTaxonomy

powershell.exe memory usage also continues to climb, eventually consuming all available RAM.
In our specific case, the txt file is 613KB and contains 13914 terms.
 
### Steps to reproduce behavior
Import-PnPTaxonomy -Path .\path\to\file.txt

### What is the version of the Cmdlet module you are running?
tried on both 1.5.0 and 1.5.48

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by saltzimania** [comment]
Last night I tried with v 1.6.43-nightly on a PC with 32GB RAM and it got further but failed with an array out of bounds error - sorry I didn't capture the exact error message.
By the time it failed, powershell.exe had consumed over 20GB RAM

**Comment by gautamdsheth** [comment]
@saltzimania  - is the issue still occurring ? Can you try with the latest nightly builds of 1.8 and let us know ?

**Comment by veronicageek** [comment]
Closing as no response.
