### ISSUE TITLE
Add-PnPFile errors with : format-default : The collection has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.     

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/powershell#925]
The files are downloaded to the current folder from SharePoint 2013 
### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)
```
$writUpConn = Connect-PnPOnline  -Url $Url -ClientId $ClientId -CertificateBase64Encoded $CertificatePFX -CertificatePassword $CertificatePassWord  -Tenant $tenant -ReturnConnection
Add-PnPFile -Path $localPath -Folder $folder -Connection $writUpConn 
```
error:format-default : The collection has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.

but if I run in the command line 
`Add-PnPFile -Path $fileName -Folder $folder `
It works fine.

how can I make it work in the script?

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows server
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@Ofer-Gal 
> The files are downloaded to the current folder from SharePoint 2013

What do you mean? 
I also see you ticked/added Windows Server. Are you trying to upload files from Windows Server to **SharePoint Online**? This repo only supports SharePoint Online, **_not_** SharePoint on-prem, so please confirm.

**Comment by Ofer-Gal** [comment]
By now I can't remember what it was about. closing
