### ISSUE TITLE
[BUG] - Get-PnPTenantSite error: The property or field 'AuthContextStrength' has not been initialized

### ISSUE THREAD

**Issue by fikryGaf** [pnp/powershell#926]
### Reporting an Issue or Missing Feature
the Get-PnPTenantSite was working fine but suddenly it throws this error below inthe actual behavior section

### Expected behavior 
get the tenant sites according to the filter value

### Actual behavior 
it working perfect but suddenly from today it gets this error
|  … terSPList = Get-PnPTenantSite  -Detailed -Filter  "Url -like 'https:/ …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property or field 'AuthContextStrength' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested. 

### Steps to reproduce behavior
  # Connect to the tenant
    Connect-PnPOnline -Url $Url -ClientId $AppID -ClientSecret $AppSecret
    $masterSPList = Get-PnPTenantSite  -Detailed -Filter  "Url -like '/sites/sitename'"
### What is the version of the Cmdlet module you are running?
1.4.0

### Which operating system/environment are you running PnP PowerShell on?
- Windows

**Comment by gautamdsheth** [comment]
Closing this issue, same as #927 , if you are facing this error please update to the latest `1.6.44-nightly` .
