### ISSUE TITLE
[BUG] Set-PnPListItem in batch mode fails to update modified date 

### ISSUE THREAD

**Issue by oliver3twist** [pnp/powershell#928]
### Reporting an Issue or Missing Feature
Set-PnPListItem in batch mode fails when setting "Modified" field value on a list item. Returns the error "Property Author does not exist in this entity". Author exists on list item and was retrieved successfully using Get-PnPListItem.

### Expected behavior 
Should work the same as Set-PnPListItem without batch mode enabled and update the modified date.
This works: 
`Set-PnPListItem -List $libToListMap[$lib] -Identity $item.ID -Values @{ "Modified" = [DateTime]"05/01/2020" };`

### Actual behavior 
`Set-PnPListItem -Batch $batch -List $libToListMap[$lib] -Identity $item.ID -Values @{ "Modified" = [DateTime]"05/01/2020" };`

**Error Output:** 
Set-PnPListItem : Property Author does not exist in this entity
At line:1 char:1
+ Set-PnPListItem -List $libToListMap[$lib] -Identity $item.ID -Values  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPListItem], ClientException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Lists.SetListItem

### Steps to reproduce behavior
Attempt to update the modified date of a list item in a batch. 

### What is the version of the Cmdlet module you are running?
1.6.0, connecting to SharePoint Online

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by oliver3twist** [comment]
It looks like this error is bubbling up from PnP.Core
![image](https://user-images.githubusercontent.com/11632874/126494862-7023377c-876e-45c1-b682-1877a8285daf.png)

**Comment by oliver3twist** [comment]
https://github.com/pnp/powershell/blob/b46a879d78438deccd7dad4bf6ad38dd72674046/src/Commands/Utilities/ListItemHelper.cs#L291

Could it be because the 'Author' field is missing from the existingItem being passed into ListItemHelper.GetFieldValues() when it is called by the SetListItem class? [link](https://github.com/pnp/powershell/blob/b46a879d78438deccd7dad4bf6ad38dd72674046/src/Commands/Utilities/ListItemHelper.cs#L291)

**Comment by gautamdsheth** [comment]
Fixed it. Should be available in tomorrow’s nightly.

Thanks for reporting this issue 😊
