### ISSUE TITLE
[BUG] Add-PnPTeamsChannel with -Private returns Invalid OData type specified: "Microsoft.Teams.Core.channel"

### ISSUE THREAD

**Issue by loryanstrant** [pnp/powershell#933]
Reporting an Issue

### Expected behavior 
When running Add-PnPTeamsChannel with -Private parameter should create the channel, like it does when run without the parameter.

### Actual behavior 
![image](https://user-images.githubusercontent.com/51473494/126605366-23ea4f99-43b3-44dd-8a5f-1adb97a5aeb9.png)
As you can see from above screenshot all other parameters for Team and channel name are fine, but when -Private is added it fails.

### Steps to reproduce behavior
Have tried to run it with variations of parameters and quotation marks, UPNs, even tried running against the group ID directly:
![image](https://user-images.githubusercontent.com/51473494/126605581-77872342-a650-44d1-b43f-e9ff3d4ccf3e.png)

### What is the version of the Cmdlet module you are running?
Have tried with both 1.6.36-nightly & 1.6.0.

### Which operating system/environment are you running PnP PowerShell on?
- Windows

**Comment by gautamdsheth** [comment]
@loryanstrant - can you try with the latest nightly build ? 1.6.44 nightly ? Was a couple of days back

**Comment by loryanstrant** [comment]
That worked, thank you!
