### ISSUE TITLE
[BUG] Dependencies to handle Az DLLs -> Az.Resources "DependencyInjection.Abstractions"

### ISSUE THREAD

**Issue by Henry-Sir** [pnp/powershell#948]
### Reporting an Issue or Missing Feature
In version 1.6.44-nightly, the dependencies have been downgraded to handle Az DLLs.
I think the Microsoft.Extensions.DependencyInjection.Abstractions.dll still needs to be adjusted.

Az.Resources:    2.2.0.18315
PnP.Powershell: 5.0.20.51904 (Folder: Core & Framework)

I use AzTable with requires modules "Az.Storage" & "Az.Resources" to save information from Sharepoint to a Azure table.

### What is the version of the Cmdlet module you are running?

1.6.44-nightly / 1.7.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [x] Other : please specify:
Azure Runbook

**Comment by gautamdsheth** [comment]
@Henry-Sir - what is the error that you are facing ?

**Comment by gautamdsheth** [comment]
Closing this due to lack of response.
Please try with the latest PnP PowerShell and open a new issue if it still exists.
