### ISSUE TITLE
[BUG] Get-PnPFooter does not handle throttle error (http 429)

### ISSUE THREAD

**Issue by sathya-bhat** [pnp/powershell#949]
### Reporting an Issue or Missing Feature
I believe (correct me if I am wrong in my assumption) PnP cmdlets handle M365 throttle error (429) internally and retries before surfacing the error to client.

However I am seeing Get-PnPFooter surfaces the exception immediately on throttle with exception:

Get-PnPFooter : The remote server returned an error: (429) .  System.Net.WebException,  HResult=0x80131509

### Expected behavior 
Get-PnPFooter retry internally on throttle errors.

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.
Get-PnPFooter surfaces the exception immediately on throttle with exception:
Get-PnPFooter : The remote server returned an error: (429) .  System.Net.WebException,  HResult=0x80131509

### Steps to reproduce behavior
This is a stress scenario where the Get-PnPFooter execution gets throttled due to other workloads going on in SharepointOnline.

### What is the version of the Cmdlet module you are running?
This is observed on all PnP versions. 1.5.0/1.6.0 and 1.7.0

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ x] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by KoenZomers** [comment]
You're right on your assumption @sathya-bhat. Will look into implementing retries in this code.

**Comment by KoenZomers** [comment]
Thanks for reporting @sathya-bhat. Retry logic on throttling will be added through this PR: https://github.com/pnp/pnpframework/pull/478

Assuming that will fix this issue, I will proceed with closing this issue. If once this PR is merged and you wait for the next day to get the latest prerelease and find out it is still not working for you, feel free to reopen this issue.
