### ISSUE TITLE
[BUG] Planner commands have -Group parameter as required - giving no option to just select using -PlanId

### ISSUE THREAD

**Issue by LeonArmston** [pnp/powershell#95]
### Reporting an Issue or Missing Feature
The [Add-PnPPlannerBucket documentation](https://github.com/pnp/powershell/blob/dev/documentation/Add-PnPPlannerBucket.md#syntax) states you should be able add a Planner using just -Plan (id or name) and not have to state a -Group. I am unable to just enter a -Plan and instead I am also requested to enter a -Group (name or id). The command works if I enter both a -Plan (id or name) AND - Group (id or name).

```powershell
Add-PnPPlannerTask -Plan "odmeGVFLm02Xb0C9rWMtg5cACLXR" -Bucket "Bucket 4" -Title "Test"
```
The same behaviour occurs on the following other Planner commands (unable to select by just -Plan and then -Group is requested - contrary to the documentation.)

- Add-PnPPlannerBucket
- Get-PnPPlannerBucket
- Get-PnPPlannerTask
- Remove-PnPPlannerBucket
- Set-PnPPlannerBucket
- Set-PnPPlannerPlan

For adding planner tasks in Microsoft Graph PlanId is only required https://docs.microsoft.com/en-us/graph/api/planner-post-tasks?view=graph-rest-1.0&tabs=http and no group id is required.

### Expected behaviour 
To be able to add a Planner task using Plan id or name

### Actual behaviour 

Execute the Add-PnPPlannerTask command using -Plan and don't specify a -Group. I am then asked for Group as it is a required parameter or otherwise it will not execute.

![image](https://user-images.githubusercontent.com/12968962/104034627-0b9c4880-51c9-11eb-9e4c-3d317e5cf184.png)

### Steps to reproduce behaviour
Create a Plan and bucket.
Execute PowerShell below (change to a Plan name or PlanId in your tenant and a valid bucket)
```powershell
Add-PnPPlannerTask -Plan "odmeGVFLm02Xb0C9rWMtg5cACLXR" -Bucket "Bucket 4" -Title "Test"
```

### What is the version of the Cmdlet module you are running?
0.3.29 

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

Thanks

**Comment by erwinvanhunen** [comment]
Hi!

I think you missed a subtle difference in the documentation. Notice the use of `-PlanId`, when you just want to use the id of the plan, and not `-Plan`.

We provide a convenience method, using group and plan which allows you use to the names of the group and the plan. But if you want to use pure the -id- of the plan, you have to use the `-PlanId` parameter.

**Comment by LeonArmston** [comment]
Hi 

Correct - I didnt see the subtle difference! Have checked now and can now see the PlanId.

Thanks for the clarification and I will close this now.
