### ISSUE TITLE
[BUG] Set-PnpTenantSite -ConditionalAccessPolicy AuthContextStrength error

### ISSUE THREAD

**Issue by mdressel** [pnp/powershell#958]
### Reporting an Issue or Missing Feature
When you call `Set-PnpTenantSite -Identity $siteUrl -ConditionalAccessPolicy AllowLimitedAccess` you get `Set-PnPTenantSite : Field or property "AuthContextStrength" does not exist.`. There was another bug fix that addressed this exact issue in `Get-PnpTenantSite` (#931, #927, #926, #922). The fix is in [22985f6f3d15c0d23919a24288d7f92a175c2ab9](https://github.com/pnp/powershell/commit/22985f6f3d15c0d23919a24288d7f92a175c2ab9).

### Expected behavior 
Command operates successfully.

### Actual behavior 
`Set-PnPTenantSite : Field or property "AuthContextStrength" does not exist.`

### Steps to reproduce behavior
```
[CmdletBinding()]
Param(
    [Parameter(Mandatory)]
    [string]$SiteUrl
)

function Test {
    $domain = Get-AutomationVariable -Name 'TargetDomain'
    $cred = Get-AutomationPSCredential -Name 'automate'
    $cert = Get-AutomationCertificate -Name 'App'
    $secret = Get-AutomationVariable -Name 'AppSecret'
    $certPass = Get-AutomationPSCredential -Name 'CertPass'
    $certByteArray = $cert.Export("pfx", $certPass.Password)
    $certString = [System.Convert]::ToBase64String($certByteArray)
    $adminSiteUrl = "https://$domain-admin.sharepoint.com/"

    $connection = Connect-PnPOnline -Url https://$domain.sharepoint.com -ClientId $clientId -Tenant $tenant -CertificateBase64Encoded $certString -certificatePassword $certPass.Password

    Set-PnPTenantSite -Identity $siteUrl -ConditionalAccessPolicy AllowLimitedAccess

    Disconnect-PnPOnline
}

Test
```

### What is the version of the Cmdlet module you are running?
1.7.2-nightly

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ X] Other : Azure Automation, GCC

**Comment by gautamdsheth** [comment]
@mdressel  - can you try this with the latest nightly and check if it still exists ?

**Comment by gautamdsheth** [comment]
Closing it due to lack of response.
Please use the latest version of PnP PowerShell and open a new issue if it still exists !

**Comment by mdressel** [comment]
Sorry I didn't respond sooner. I haven't tested this, but we had a tickets opened with Microsoft support related to this and as I understand it they rolled out a fix to GCC. We are starting to get back into the script that had this specific issue and I can let you know if it is still happening. I am 100% fine with it being closed right now.
