### ISSUE TITLE
[BUG] Set-PnPSite -Sharing Disabled command fails each time with a 401 Unauthorized error.

### ISSUE THREAD

**Issue by rokoda** [pnp/powershell#968]
### Reporting an Issue or Missing Feature
I used the Set-PnPSite command to disable the sharing settings for the SPO sites associated with Teams' team.
The Set-PnPSite-Sharing Disabled command now fails each time with a 401 Unauthorized error.
This began to happen suddenly at July 31, 2021. It runs on AzureAutomation and has not changed any code or modules.
The app specified in-ClientId is pre-registered in Azure AD, and the "Sites.Manage.All" API permission is assigned to the app.

It seems to occur under the following conditions
- Occurs on SPO sites linked to the microsoft 365 group
- Occurs when logging in with a certificate
- Occurs when Set-PnPSite is set to the Sharing option
- Occurs with Set-PnPSite but not with Set-SPOSite

I detected this with SharePointPnPPowerShellOnline 3.24. 2008.1, but it appears to be happening with PnP 1.7. 0 as well.

### Expected behavior 
Set-PnPSite command should succeed without error.

### Actual behavior 
Set-PnPSite command fails with 401 Unauthorized.

### Steps to reproduce behavior
1.Connect-PnPOnline -Url 'SPO sites URL associated with Teams' team' -Tenant 'TenantId' -ClientId 'ApplicationId' -Thumbprint 'CertificateThumbprint'
2.Set-PnPSite -Sharing Disabled -ErrorAction Stop

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 1.7.0
SharePointPnPPowerShellOnline 3.24.2008.1

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [X] Other : Azure Automation

**Comment by gautamdsheth** [comment]
Fixed with this PR - https://github.com/pnp/powershell/pull/969.
Please reopen this issue if it still exists with the nightly release.
