### ISSUE TITLE
MetadataViaSiteIdUniqueId - Submit-PnPSearchQuery : Sequence contains no elements

### ISSUE THREAD

**Issue by fs366e2spm** [pnp/powershell#978]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Provided example code https://github.com/pnp/powershell/tree/dev/samples/MetadataViaSiteIdUniqueId related to M365 admin center announcement MC275577 - Edited OneNote Notebook content was not properly saved just returns an error message:
Submit-PnPSearchQuery : Sequence contains no elements

### Expected behavior 
The output should show the Author and Path toward the provided document:

Author   Path
------   ----
Joe Doe  https://contoso.sharepoint.com/sites/demo/pnp/Rocks!.docx

### Actual behavior 
```
Submit-PnPSearchQuery : Sequence contains no elements
At line:5 char:10
+ $result= Submit-PnPSearchQuery -Query $query
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Submit-PnPSearchQuery], InvalidOperationException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Search.SubmitSearchQuery
```

### Steps to reproduce behavior
# Connect to a site in your tenant, see https://pnp.github.io/powershell/index.html to learn how to get started with PnP PowerShell
Connect-PnPOnline -Url https://contoso.sharepoint.com -Interactive

# List information about the document based upon the site id and document unique id:
.\GetDocumentMetadataViaSiteIdUniqueId.ps1 "b56adf79-ff6a-4964-a63a-ff1fa23be9f8" "e2a52975-ceae-41b3-9271-315a5cfba6b2"

as mentioned on [https://github.com/pnp/powershell/tree/dev/samples/MetadataViaSiteIdUniqueId](https://github.com/pnp/powershell/tree/dev/samples/MetadataViaSiteIdUniqueId)

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
1.7.0

### Which operating system/environment are you running PnP PowerShell on?
- [ X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by alphaEmpyrean** [comment]
I ran into this issue as well. I took a look in the script and removed the brackets from the query template and that seems to have solved the issue for me. I can now successfully run the script.

Modified
$query="SiteId:" + $SiteId + " UniqueId={" + $DocId + "}"

To

$query="SiteId:" + $SiteId + " UniqueId=" + $DocId

**Comment by alphaEmpyrean** [comment]
@fs366e2spm Absolutely!

Just some follow up. I was testing this because Microsoft Health Alert MC275577 points to this script. This alert provided a SiteId and UniqueId for me to use, however I receive the error when trying to use the Guids they provided. If I look up the SiteId and UniqueId of a know document it works fine. 

This led me to test a little more and I modified the UniqueId from a known and working document First I malformed it by removing a character and the second time I modified it (to see what happens if what we are looking for does not exist) and both times I got the same error.

Are you running yours against known documents?

**Comment by gautamdsheth** [comment]
Closing this, looks like a tenant specific issue.
Not sure what we can do here since the cmdlet does work. 
We also made a minor fix for document that doesn't exist.
Would request you to please update to the latest nightly build and test it.
