### ISSUE TITLE
[BUG] Get-PnPWebPart does not return anything

### ISSUE THREAD

**Issue by liamcosgrove30** [pnp/powershell#981]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

### Reporting an Issue or Missing Feature
When I try to get the web parts that are on the home page of a SharePoint site, Get-PnPWebPart does not return anything.
I use Get-PnPWebPart -ServerRelativePageUrl "/sites/ExampleSite/SitePages/Home.aspx"

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets
I expect to see the identities of the web parts that are located on the home page of the SharePoint site that I have connected to.

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.
The Get-PnPWebPart does not return anything

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)
$site = "ExampleSite"
$siteURL = "https://test.sharepoint.com/sites/$site"
Connect-PnPOnline -Url $siteURL -Interactive
Get-PnPWebPart -ServerRelativePageUrl "/sites/$site/SitePages/Home.aspx"

Please note that this still doesn't return anything if I insert the $site manually into the -ServerRelativePageUrl

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
1.7.0

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by a1mery** [comment]
For "modern" pages, you could try to use the `Get-PnPPage` cmdlet.
More specifically, to get the page web parts, you can use : `(Get-PnPPage -Identity "Home.aspx").Controls`

**Comment by veronicageek** [comment]
@liamcosgrove30 - To retrieve the webparts on modern pages please use `Get-PnPClientSidePage` or `Get-PnPPage` like @a1mery suggested.

Also, the `home.aspx` will need to be edited/republished first before as stated in the documentation (this is by design):

>This command allows the retrieval of a modern sitepage along with its properties and contents on it. Note that for a newly created modern site, the Columns and Sections of the Home.aspx page will not be filled according to the actual site page contents. This is because the underlying CanvasContent1 will not be populated until the homepage has been edited and published. The reason for this behavior is to allow for the default homepage to be able to be updated by Microsoft as long as it hasn't been modified. For any other site page or after editing and publishing the homepage, this command will return the correct columns and sections as they are positioned on the site page.

![image](https://user-images.githubusercontent.com/25181757/129482276-58cc54f5-b882-4d8e-a77b-85d2f49feeef.png)

Please close if that solves your issue.

**Comment by liamcosgrove30** [comment]
Hi @a1mery, @veronicageek,

Thank you so much for your help, this has sorted my problem!
