### ISSUE TITLE
[BUG] Get-PnPTerm/Add-PnPTermToTerm cmdlets returns an exception

### ISSUE THREAD

**Issue by vieirav** [pnp/powershell#986]
### Reporting an Issue or Missing Feature
When trying to get a Term the cmdlet Get-PnPTerm returns the error: "Object reference not set to an instance of an object on server. The object is associated with method GetTerm."
Same error when I try to add an item with Add-PnPTermToTerm. 

### Expected behavior 
Return the Term object / Add the Term

### Actual behavior 
```
$taxItem = Get-PnPTaxonomyItem -TermPath "termGroup|termSet"
$parentTerm = Get-PnPTerm -Identity $taxItem.Id -IncludeChildTerms

Get-PnPTerm : Object reference not set to an instance of an object on server. The object is associated with method GetTerm.
+ $parentTerm = Get-PnPTerm -Identity $taxItem.Id -IncludeChildTerms
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPTerm], ServerObjectNullReferenceException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Taxonomy.GetTerm
```

```
$parentTerm = Get-PnPTermSet -Identity $taxItem.Id -TermGroup "termGroup" -Includes Terms
Add-PnPTermToTerm -ParentTerm $parentTerm.Id -Name $termName -LocalCustomProperties @{ "_Sys_Nav_SimpleLinkUrl" = "/sites/something" }

Add-PnPTermToTerm : Cannot invoke method or retrieve property from null object. Object returned by the following call stack is null. "GetTerm"
+       Add-PnPTermToTerm -ParentTerm $parentTerm.Id -Name $termName -L ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Add-PnPTermToTerm], ServerException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Taxonomy.AddTermToTerm
```

### Steps to reproduce behavior
```
$taxItem = Get-PnPTaxonomyItem -TermPath "termGroup|termSet"
$parentTerm = Get-PnPTerm -Identity $taxItem.Id -IncludeChildTerms # ERROR
```

```
$parentTerm = Get-PnPTermSet -Identity $taxItem.Id -TermGroup "termGroup" -Includes Terms
Add-PnPTermToTerm -ParentTerm $parentTerm.Id -Name $termName -LocalCustomProperties @{ "_Sys_Nav_SimpleLinkUrl" = "/sites/something" }
```

### What is the version of the Cmdlet module you are running?
PnP.PowerShell -> 1.6.0 and 1.7.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by jackpoz** [comment]
Could you verify that the value returned by `Get-PnPTaxonomyItem -TermPath "termGroup|termSet"` is not null ?

**Comment by vieirav** [comment]
Hi @jackpoz,

As you requested, here's the test.

```
$taxItem = Get-PnPTaxonomyItem -TermPath "termGroup|termSet"
$taxItem
$parentTerm = Get-PnPTerm -Identity $taxItem.Id -IncludeChildTerms
```
Result:
![image](https://user-images.githubusercontent.com/13801784/132231275-701904cf-09b4-4304-8e79-4172ccfd1495.png)

As you can see the value is not null.
Let me know if you need anything else.

**Comment by gautamdsheth** [comment]
The error message is correct. It is not a bug.
You are getting an error because you are fetching a Termset and not a term. So, you need to use `Get-PnPTermSet` to fetch the termset.

Modify the code as below:

```powershell
$taxItem = Get-PnPTaxonomyItem -TermPath "termGroup|termSet"
$termSet = Get-PnPTermSet -Identity $taxItem.Id -TermGroup "termGroup"
```

To add the term to a termset, you can add it as below:

```powershell
New-PnPTerm -Name $termName -TermSet $termSet -TermGroup "termGroup"
```
