### ISSUE TITLE
[BUG] - '@odata.nextLink' in Invoke-PnPSPRestMethod not returning values

### ISSUE THREAD

**Issue by kevmcdonk** [pnp/powershell#990]
1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
I have a script that uses Invoke-PnPSPRestMethod to return files for libraries with more than 5000 items in them (primarily for deleting them!). It use the REST API to return the $top 500 items and then uses the odata.nextLink in the response to get the next set of 500.

This worked with the classic PnP PowerShell (SharePointPnPPowerShellOnline 3.28.2012.0 on Windows 10) but in the current version, the odata values are never returned. Intriguingly, they are not even returned in the JSON with the -Raw tag.

### Expected behavior 
It should be possible to access odata.nextLink from the REST response.

### Actual behavior 
Value is not returned at all

### Steps to reproduce behavior
SCript below is an example of bulk deleting files but it only ever returns the top number, not moving on to the next batch. And before someone asks, yes I do know that this would work as it will just keep deleting the top number but if you wanted to list the files instead, it would not work!

# EXAMPLE
# .\RemoveBulkFiles.ps1 -TenantName "Contoso" -SiteUrl "Test" -LibraryUrl "Shared Documents"
# .\RemoveBulkFiles.ps1 -TenantName "Contoso" -SiteUrl "Test" -LibraryUrl "Shared Documents" -SiteStub "Teams"
    param(
        [Parameter(Mandatory)]
        [string]$TenantName
    ,   [Parameter(Mandatory)]
        [string]$SiteUrl
    ,   [Parameter(Mandatory)]
        [string]$LibraryUrl
    ,   [Parameter(Mandatory=$false)]
        [string]$SiteStub="sites"
    )
Write-Output "Running"
    $sourceSiteUrl = "https://$TenantName.sharepoint.com/$SiteStub/$SiteUrl"
    Connect-PnPOnline $sourceSiteUrl

    $skipNum=0
    $currentItemNumber = 1
    $currentIteration = 1
    $batchSize=5
    $listUrl ="/_api/web/GetList('/$SiteStub/$SiteUrl/$LibraryUrl')/items?`$top=$batchSize&`$select=Title,File/Name,File/ServerRelativeUrl&`$expand=file"

    do {
        $listUrl
        $listItems = Invoke-PnPSPRestMethod -Method Get -Url $listUrl
        $itemCount = $listItems.value.Count
        
        foreach($item in $listItems.value) {
            $currentItemNumber++

            # For a large number of files, you may want to comment this out to reduce memory usage in PowerShell
            Write-Output "Deleting file $($item.File.ServerRelativeUrl)"
            $removedFile = Remove-PnPFile -ServerRelativeUrl $item.File.ServerRelativeUrl -Recycle -Force
        }
        $listItems
        if ($itemCount -and $itemCount -gt 0) {
            $listUrl = $listItems.'@odata.nextLink'
            $listUrl = $listUrl.Replace("https://$TenantName.sharepoint.com/$SiteStub/$SiteUrl","")
            $listUrl
        }
        Write-Output "Iteration $currentIteration"
        $currentIteration++ 
        $skipNum = $skipNum+$batchSize
    } while ($itemCount -gt 0)

### What is the version of the Cmdlet module you are running?
1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ *] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
@kevmcdonk - can you update to the latest 1.7.0 branch ? I tested it , there is indeed an issue, but if you specify `-Raw` parameter it works and you get the next link. Will try to figure out how to fix this, but hope this unblocks you temporarily  !

![image](https://user-images.githubusercontent.com/8832018/129041292-b6be7519-3d7a-46ad-bc76-943b65797bc7.png)

**Comment by gautamdsheth** [comment]
@kevmcdonk  - should be fixed in tomorrow's build !

**Comment by veronicageek** [comment]
Thanks @gautamdsheth for your quick action on this 👍🏻

**Comment by kevmcdonk** [comment]
Thanks so much for looking at this @gautamdsheth. It's strange though, definitely not got it on the nightly build for 1.7.17 and when I run the command, I just get value back. Searched the full response and no mention of next at all. Will update tomorrow and see if new fix makes any difference. I am on an M1 Mac but can't see that would make a difference.

![image](https://user-images.githubusercontent.com/7413090/129255149-cf7a40b2-4861-42d9-80b2-503d011b0486.png)

**Comment by gautamdsheth** [comment]
Should be $listItems.’odata.nextLink’ , it should give a value

**Comment by gautamdsheth** [comment]
Just tested it on W10 machine with 1.7.17-nightly - 

![image](https://user-images.githubusercontent.com/8832018/129257048-021c9d60-c7b2-4b24-9c20-1da9ae7778ad.png)
