### ISSUE TITLE
[BUG] Add-PnPWebhookSubscription doesn't throw an error on existing subscription

### ISSUE THREAD

**Issue by wonderplayer** [pnp/powershell#996]
### Reporting an Issue or Missing Feature
I believe it is an issue.

### Expected behavior 
When I execute Add-PnPWebhookSubscription with NotificationURL already present in subscriptions of a list, then the command should throw an error, that this notification URL already exists, and web hook can't be added.
This is needed, so it is possible to determine that web hook should be updated instead of added.
If web hook would be updated based on notification URL by adding it, then it would also be fine.

I was trying to update expiration date and time, and client state, but they weren't.

### Actual behavior 
I get regular success response, as if web hook was successfully registered.

### Steps to reproduce behavior
Execute
`Add-PnPWebhookSubscription -List $List -NotificationUrl $NotificationURL -ExpirationDate $expirationDate -ClientState $ClientState -ErrorAction Stop` twice. No exception will be thrown second time.

### What is the version of the Cmdlet module you are running?
1.7.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
This is not a bug.
You need to check it in your code yourself.

To get list of webhooks, you can fetch them using `Get-PnPWebhookSubscriptions` cmdlet and find out if your webhook exists or not.

If it exists, use `Set-PnPWebhookSubscriptions` otherwise use `Add-PnPWebhookSubscriptions`

**Comment by wonderplayer** [comment]
@gautamdsheth The thing itself isn't about the logic. I can, of course, implement it by getting, checking and performing an action. But `Add-PnPWebhookSubscription` should throw an error upon unsuccessful addition, because this is what happened.
The command returned to be an object with ID corresponding to notification URL subscription, with new client state and expiration time, but in reality nothing changed.

**Comment by gautamdsheth** [comment]
@wonderplayer - can you check with Fiddler if you get an error with this scenario ? Then endpoint will be a HTTP POST request with endpoint -  ` /_api/web/lists('list-id')/subscriptions `
Because if you dont get the error there, then the issue lies with API itself and we can't do anything about it.

**Comment by wonderplayer** [comment]
Eh... the issue is in the API (╯°□°）╯︵ ┻━┻
Yeah, then nothing to do about it...
